### ISSUE TITLE
We've archived your Done items for you...

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1000]
## Issue - Enhancement

During a customer session, our folks were surprised that their Done column was wiped. We should consider doing either or both of:

   - Empty state for Done column ("Projects will be automatically archived after a meeting")
   - A message in the web view of the summary, "We've archived (X) Done items for you..."

- **Estimated effort:** 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by colinmatthews** [comment]
I'll do this one for 13 points!

**Comment by jordanh** [comment]
@colinmatthews it's all yours! Good luck!

**Comment by ackernaut** [comment]
🔥

**Comment by jordanh** [comment]
@mattkrick had some suggestions for how to improve the overall experience by only showing this text when it is truly useful.

It:
- [ ] shows the text only after on-boarding
- [ ] once just after the meeting has ended

For this scope creep, we'll offer this Issue up for **18 points** in total. Ok @colinmatthews?

@mattkrick how do you suggest this state be stored? Something to store in redux?
