### ISSUE TITLE
Meeting Auto Time-Out Broken

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#1003]
## Issue - Bug

User added me to their team for a Demo. Noticed ystdy that they didn't "End Mtg" last time and it hasn't auto-tied out so I'm stuck on the "Meeting in Progress" status & can't remove myself for their team.

(If auto time-out isn't already set to 24hrs, it shld be--guessing this is just a bug though)

**Comment by jordanh** [comment]
Fixed by #1081 and related to #1074
