### ISSUE TITLE
Polish up Slack integration

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1007]
## Issue - Enhancement

Currently integrations are hidden behind a big ol' button at the bottom of Team Settings.

![image](https://cloud.githubusercontent.com/assets/103000/26116410/0ee35fb4-3a31-11e7-9f2d-915451299b46.png)

The modal panel to configure the Slack integration looks pretty nice, even if it does contain some technical debugging information at the bottom:

![image](https://cloud.githubusercontent.com/assets/103000/26116463/409c2c20-3a31-11e7-9948-dc4f9a6836fd.png)

When the `bet` flag in the token is `1`, perhaps we can:

- [ ] Create a new panel called "integrations" and put it above the `Danger Zone` in `Team Settings`
- [ ] Add a row for Slack (we needn't even show the state if its been configured or not) with a button labeled 'Configure'
- [ ] When the Slack modal is raised, clean up the copy a bit so it's slightly more user friendly

- **Estimated effort:** 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
@mattkrick I pulled down the latest development environment variables and that helped me get to the Slack authorization screen. However, for some reason I am still not seeing the modal with the channel dropdown and token buttons. This is true for me locally both on `master` and `1007-integrations-panel` branches. Can we troubleshoot together?
