### ISSUE TITLE
Archive is Broken & Bug-gy

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#1013]
## Issue - Bug

When I go to any team archive:
1. "Hi there! There are zero archived projects....
2. spinspinspin
3. window crashes OR after a full minute the archive appears but everything is frozen/have to kill & reopen tab

(both desktop & Chromebook)

**Comment by jordanh** [comment]
This is going to happen to any team who has lots of archived projects. It's because we don't have pagination implemented in cashay. @mattkrick, could we add a `.limit()` to the archive query?

**Comment by mattkrick** [comment]
yeah, limit sounds like a good intermediary step. i'll add it to epic 4.5

**Comment by mattkrick** [comment]
alrighty, we got a 15 day limit coming up, which should be enough for now until we get paginated subs.
