### ISSUE TITLE
possible regression on invoice styling

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#1017]
![screenshot from 2017-05-18 14-47-54](https://cloud.githubusercontent.com/assets/5514175/26224845/1f46d8be-3bd9-11e7-9dc4-3a955b7d5897.png)

I'm getting this the latest stable Firefox & Chrome on Ubuntu 17.04. if it looks good on windows/macOS we can punt it for now

**Comment by jordanh** [comment]
@ackernaut thinks this has been fixed. Closing!
