### ISSUE TITLE
Agenda Links & Editing

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#1018]
## Issue - Enhancement

When users add topics to the Agenda Queue:
- sometimes they make typos
- sometimes the topic evolves btwn authoring & meeting and they want to change it
- sometimes they want to include/add a link to share with the team as a critical part of the Agenda processing discussion (example: works in progress, regular metrics, etc.)

### Acceptance Criteria (optional)
Output: set of wireframed designs & issues for implementation

Users can:
   - edit any Agenda topic as a GraphJS instance
   - add live links to any Agenda topic using CMND+K

- **Estimated effort:** 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
Related to #669 (Links in Agenda Items) and #871 (Standing Agenda Items)

Small Agenda enhancement epic or part of Team Sheet epic (Team Sheet is a landing to go to meeting, edit the agenda, see team members, see integrations, quick link to kanban queried to team projects)...

**Comment by jordanh** [comment]
## Acceptance criteria
- When I highlight words on an agenda item and press ctrl-k, I can add a link
- When I click on the link, it will take me to the URL in a new tab
- When I click on an agenda item I want to be able to edit it

Estimated effort: 12

**Comment by jordanh** [comment]
This one is still fairly high on the Backlog. Revisit for Iceboxing on September 1st, 2018
