### ISSUE TITLE
Checklists

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1026]
## Enhancement

When managing multiple projects, team leads want to add detail to projects breaking them into subtasks so that they can see what is needed to complete a project and how much progress has been made. 📎 🔒 [See user data (internal doc)](https://docs.google.com/a/parabol.co/document/d/1PlpKZXZEu3JeSzaFfJwasBDmUASL3Y7TAHp71tprY9I/edit?usp=sharing)

- This supports projects with a single owner, but multiple defined items to be done.
- This supports integrating with other services that use checklists (Trello, GitHub, Asana, etc.).
- This helps team leads and team members be better organized.

**Estimated effort**: 15 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Closing in favor of #2055
