### ISSUE TITLE
New project status default (team settings > meetings)

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1028]
## Enhancement

When new projects are being created in a meeting, team leads want to control the default status so that they can control their workflow of processing new projects versus existing projects.

Background: A team lead may prefer a default of future/inbox over active for new work coming out of the meeting.

**Estimated effort**: 18 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
I imagine that this'll come back in the future. Iceboxing for now
