### ISSUE TITLE
Longer Tool Tips Life

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#1030]
## Issue - Enhancement

Sometimes users are kicking the tires for a few days/weeks until they actually onboard with us and/or their team. In the meantime, they forget the helpful tips and request repeat reminders or constant access to the info until they're familiar.

Keep initial Dashboard prompts and tool tips cards until **after user conducts first team meeting** OR manually deletes them herself.

**Comment by dan-f** [comment]
By "tool tips" are you referring to the initial cars which tip off the user to the various things they can be doing? I did not realize that they disappeared after a set period of time!

**Comment by dan-f** [comment]
No longer relevant! CLosing
