### ISSUE TITLE
Right-Click "Pup" Cards

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#1031]
## Issue - Enhancement

Ability to right-click & create a “pup” Active task as a subset of a Future project

User tried to click & create a “pup” 4wk Active task off of a main 4mos Future project card. Even after being informed that hashtag & color-coding features were coming, she requested the ability to right-click and create a subset.

**Comment by jordanh** [comment]
Could you add some job stories here?

- **When** <X context>, **they want to** <take x action>, **so that** <beneficial outcome> occurs

That may spurn some interesting design options.

**Comment by jordanh** [comment]
Removing this one from the sprint board until it's groom-ready. This looks like a design issue. Could you write some acceptance criteria, or, draw some lo-fi picture of what this might look like?
