### ISSUE TITLE
Include "Done" Items in Meeting Summary Stats

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#1034]
## Issue - Enhancement

A frequent request/comment/question from users:

1) In case a teammate wasn't present at the meeting and would like a summary by way of update
2) When sharing with a higher circle of management/authority to provide clarity on weekly activity
3) To provide valuable backend data for future HR/People Ops features
4) Some teammates are not assigned/do not create many cards during meetings, either because their work is largely self-initiated (managers) and/or because their priorities and new work happen on a shorter cycle than a weekly cadence. So if they create a card after a meeting occurs which moves through to Done, there is no record of their work or "personal weather" (level of busy-ness/stress). Their contributions should still be tracked and acknowledged.

**Comment by jordanh** [comment]
Closely related to #845 

Experiment for us to consider is including Done items in End of Meeting Summary instead of sending two communications.

Trade offs, trade offs. Re-engagement vs. having information that does not pertain to the meeting.

**Comment by tayamueller** [comment]
Intent was not to create 2 comms; intent was to include Done items in the existing Summary (which currently only includes New cards)

Reopening b/c it's surfaced again (and has been repeated) as a useful feature

**Comment by ackernaut** [comment]
I think this will require some exploration as we loop through team members, it could get rather long. We will have What’s New (and loop through cards coming out of the meeting) and then What’s Done (and loop through cards that were in the Done status when the meeting ended). May be hard to track when scrolling down through an email. There is less cognitive and visual overload when all the cards represent the same idea.

One idea I explored is using a list view instead of a card view for the projects/tasks show in email. I think this will make sense to users overtime if they see their projects in list view in other contexts such as the Inbox concept for batch processing.

**Comment by tayamueller** [comment]
"when you’re selling to management you’re selling reporting." -a smart guy we know

**Comment by tayamueller** [comment]
see comments in #644

**Comment by tayamueller** [comment]
"at one of our clients we've been using a feature called Release to create a "Version" which acts sort of as a weekly ship. It automatically clears your Done Column, creating a list of all the tasks you did that week. If there was a way that that could auto-email to a bunch of stakeholders, would save me 2 hours on a Friday writing my weekly ship. Just a cool feature idea that you might be interested in." - the new Parabol lead at our longest-standing non-adopter company

**Comment by jordanh** [comment]
Leaning into Max/August now is a good idea. This is a good example of "Time Criticality." We have an opportunity to delight a member of August by showing how responsive we can be. Will add to discuss at our product meeting.

**Comment by tayamueller** [comment]
frequent observation (including SPA VI user observation & interview) that "Done" column elicits an emotional response. There is a connection between a user's "Done" column and their sense (and teammate's perception of) contribution and progress.

**Comment by ackernaut** [comment]
Shipped with #1731
