### ISSUE TITLE
Google login bug (?)

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#1037]
## Issue - Bug

When becoming a first-time user, Google login option flashes the Welcome Screen again before placing user in their Dashboard, which is confusing depending on user's internet speed--”am I in yet?”

**Comment by jordanh** [comment]
I've seen this one intermittently – even when it's not a first-time user. I think a possible remedy here is to move to `passport-auth0` and stop using the auth0 lock.

**Comment by jordanh** [comment]
Haven't seen this one in awhile. Closing for now.
