### ISSUE TITLE
Mobile Agenda

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#1038]
## Issue - Enhancement

Users would like the ability to link or otherwise add Agenda items on the fly, as they think of them throughout the week--like a pinned GDoc link or a notetaking app

**Comment by jordanh** [comment]
MVP ideas: synched trello column or Slack integration :)

**Comment by jordanh** [comment]
Removing this from the sprint board until we have acceptance criteria and estimated effort. Some questions around this issue: is it a mobile app? A separate mobile site? A version of our site that is displayed when you visit us on mobile? A slack bot?

**Comment by jordanh** [comment]
Will revisit ideas like this when we investigate mobile interactions. Iceboxing for now
