### ISSUE TITLE
Unfinished Agenda

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#1039]
# Issue - Enhancement

User would like option to table & carry over (save) any un-processed Agenda items until next meeting

### Acceptance Criteria
- Create a lo-fi design to test UX
- Test UX with users. Validate, iterate.
- Write criteria for hi-fi solution design

**Comment by jordanh** [comment]
The reason for a dynamic agenda follows the logic, "if something is truly important, it'll come up again." Holacracy explicitly forbid saving agenda.

I think a small step forward might be to report on which agenda items weren't finished in the summary, so that if a user was bummed that something didn't get processed they can refer to that list and re-add it.

**Comment by ackernaut** [comment]
@jordanh I like the idea of including that in the summary. I actually had a note/list with one team reminding me to pre-load 3 weekly agenda items (like we do with “metrics”) followed by the surfaced tensions.

At some point, if there is a history index of summaries there would various ways to look back (browse the web app, go back to the email, etc.) I like the idea of #1040 (summaries can be seen in app, emails are optional subscription).

**Comment by jordanh** [comment]
@tayamueller this issue needs acceptance criteria and estimated effort.

The acceptance criteria should address: do we change the default behavior for everybody? Or, do we make this a configuration option?

Once these criteria are added please work with @tayamueller please work with @ackernaut or @mattkrick for estimated effort.

**Comment by mattkrick** [comment]
this is gonna be a design task so i'll punt to @ackernaut. i can give an estimate after i know what it's gonna look like.

**Comment by ackernaut** [comment]
Yeah, we need to validate a lo-fi UX, I’d say for 12 points.

**Comment by jordanh** [comment]
Closing in favor of #871
