### ISSUE TITLE
Card editor: Markdown

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1041]
## Enhancement

The card editor supports Markdown formatting (for integrations with GitHub comments, Trello card description, existing Parabol project cards, etc.).

**Note**: The editable formatting gets applied the first time it sees Markdown (users will not see Markdown once they edit a second time). However, future updates to the content using Markdown patterns should apply the correct style:

**Example**: Terry has an existing Parabol card with MD. It gets updated to editable formatting. Terry edits the content and uses back ticks for `inline code`. The card editor should recognize the MD pattern and apply the correct styling.

The card editor supports:

- [x] bold `**text**` or `__text__`
- [x] italics `*text*` or `_text_`
- [x] single tick inline code block
- [x] code blocks ` ``` `
- [x] blockquotes `>`
- [x] strikethrough `~` or `~~`
- [x] links `[link](url)` (See #1042)
- [ ] ~~bullets~~ (what about existing Parabol cards?)
- [ ] ~~headings~~ (what about existing Parabol cards?)

**Estimated effort**: 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

#WYSIWYG

**Comment by mattkrick** [comment]
what should we do about pasted markdown? is that within scope?

my current vision for this is to do kinda a one-off manual build of markdown. 
check for markdown when a space or split-block (enter/shift+enter, etc) is hit. it'll look at the past word, compare it to a regex, and if it matches one of our defined markdown regexes, we'll replace the text. this is how our inline linkify works currently

the challenge is gonna be when markdown is pasted. i think the strategy will go something like this:
- look at the data about to be pasted, if it's html just paste direct. if it's just text, then run it through a markdown processor (whether i build it or use something like markdown-it TBD).

similar to pasting is cards being imported from 3rd party APIs. I'm gonna assume most of them save the content as markdown, so our pasting strategy will have to work for this as well. where it gets hairy is how many features we offer. for example, if they paste in something with checkboxes & we don't support them. 

all of this to say-- this is gonna be a 2 parter. part 1-- realtime markdown. part 2-- imported fragment markdown. I'll use this issue to track part 1. we'll deal with part 2 later.

**Comment by ackernaut** [comment]
Breaking it down totally makes sense! We also need to consider what happens with our current cards, but since it’s Beta I think most things are safe.

**Comment by ackernaut** [comment]
@mattkrick I took a first crack at inline code and blocks of code in Figma. I need to add quotes if we do want to tackle those (any of this could be deferred I suppose).

**Comment by mattkrick** [comment]
i wrote a migration to handle our current markdown. basically, it goes like this markdown -> html -> draftjs. this works fine for now, but if we want to extract extra stuff from it i'll have to adapt it.

**Comment by ackernaut** [comment]
Ah, I see—sounds good then.

**Comment by mattkrick** [comment]
manual test:
- [ ] `_a_` is italic
- [ ] `*a*` is italic
- [ ] `__a__` is bold
- [ ] `**a**` is bold
- [ ] `__*a*__` is bold italic
- [ ] `__*~a~*__` is bolid italic strikethough
- [ ] `` `__*~a~*__` `` is bolid italic strikethough code 
- [ ] hitting backspace does the same thing as undo
- [ ] undo undoes the styling, but does not move the char back
- [ ] a split block (enter, shift+enter) or space triggers the markdown
- [ ] for split block, the style does not follow onto the next line

**Comment by mattkrick** [comment]
@ackernaut what css styles would you like for blockquotes? i basically wrapped the whole thing in a `<blockquote>` but that's it.

**Comment by ackernaut** [comment]
I started with a simple, thick bar on the left of the block with a little indention (in Figma/Card editor…) —I can take a pass at styling some of the new hotness if you wish.

<img width="368" alt="card formatted blocks 2x" src="https://user-images.githubusercontent.com/307286/26952448-1ec1e512-4c6b-11e7-9380-7367a1be220b.png">

**Comment by mattkrick** [comment]
oh i can work with that. looks like italics, a little padding, and a gray 0.25rem border?

**Comment by mattkrick** [comment]
when should a blockquote get triggered? 
- after you type `> `
- after you hit enter and the line looks like this ` >   nice`
- both (but really this means the first one, unless you paste it in)

**Comment by ackernaut** [comment]
I think the first one! Good deal!!

**Comment by mattkrick** [comment]
alrighty, markdown complete!
