### ISSUE TITLE
Card editor: title + description

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1045]
## Enhancement

The card OOUX supports 2 editable fields instead of 1:

Currently we have the **Content** of an outcome (project card).

In the future let’s consider having a **Title** and **Description** for each outcome.

Many other services (including candidates for Parabol integrations) have both a Title and a Description so the justification is that it is 1) a UX bar and 2) might make 2-way synced integrations feel right in the system.

### Title

**Proposal 1)** This is just plain text with a charmax somewhere around `140-256` (bigger, like some services, integrations?) or smaller `32-64` (just force titles to be simple for reference). We control the styling of it (larger? bold?)

**Proposal 2)** This is editable (shortcuts, MD, links, etc.) and has a charmax somewhere aroudn `140-256`. To distinguish from the description we make it around 120-150% bigger font size?

### Description

This either has a medium charmax `256` or larger charmax `512`. It can be visually smaller than the Title. It is fully editable (links, mentions, formatting).

### Card UI

**Card face variants**:

We can have a condensed card face (1 line of title with ellipsis, 2 lines of description with ellipsis) or expanded card face (show all lines of both title and description). A user can toggle this on their dashboard.

Hover reveals the expanded card face with a slick animation. Users can tap into the title or description and edit without having to open the full card back.

**Card back**:

The full title and description always fully show on the card back. The description can have a toolbar and help link for users learning to format. This is the same formatting that could be used on the title or in the future, comments.

**Estimated effort**: 15 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

#WYSIWYG

**Comment by mattkrick** [comment]
I like it! There are still some things i don't grok, but will probably get once i see a mock up. Could you walk me through the nitty gritty of what happens when I click the + and create a new card? 

- Does it autofocus on the title? 
- How do they get from the title to the description without another click? down arrow? 
- If they edit the description & wanna change the title, how do they get back up? 
- If they're 2 distinct fields, the caret won't be easy to position (we could implement some heuristics, but it still might be a little off) is this OK for UX? 
- Can a card have a title & no description? description but no title? 
- How do we keep folks from putting the description in the title field? do we move it down automatically?

**Comment by ackernaut** [comment]
- Autofocus the title—yeah!
- Users can press `tab` and `shift + tab` to go back and forth (default browser behaviors). Also, I was thinking that if the cursor is at the end of the content of the **title**, the user can press `down` to jump down to the **description**. Likewise, if the cursor is at the beginning of the content of the **description**, the user can press `up` to jump to the **title**. Hard to do?
- Not sure about the caret problem you’re describing.
- Perhaps a placeholder for empty state of either **title** or **description**? (“no title…add one”) (“no description…add one”) —we need to test this with users.
– I kind of like the idea of keeping a tight `charmax` on the title (and no rich editing) —just a string that we style ourselves (bigger, bold). If users want more content and rich formatting, they learn to do it in the description. The description could have placeholder text: “Add a description with links, user mentions, tags, etc.”

I’ll need to mock some empty states up.

**Comment by mattkrick** [comment]
alrighty, this is good!
issues:
- Tab. So from the title, hitting tab goes to description. From description, hitting tab blurs? Or do we blur on Enter? I feel like if it's a description, maybe Enter should make a new line, i know we tried that before & it was no good, but with 2 fields, maybe it'll be more intuitive? I just don't know

- For the caret problem, imagine editing a big blob of text. For fun, turn this comment into a contenteditable.
.........................................
MMMMMMMMMMMMMMMMMMMMMMMMMMMM

Let's say you're on line 2 with your caret right after the first M. when you hit the up arrow, the cursor is now after the 3rd period. That's because (assumably) the native solution measures width & tries to put the caret at about the same width, regardless of character count. that'll be really hard to do!

**Comment by ackernaut** [comment]
I like you’re thinking:

- Title tabs to description.
- Description shift-tabs to title.
- Description tabs to commit/blur.

I guess we’ll have to experiment with the cursor…`monospace`!

**Comment by ackernaut** [comment]
<img width="248" alt="card face concept empty 2x" src="https://cloud.githubusercontent.com/assets/307286/26747415/348c1d18-47bb-11e7-9b34-a07cededc73a.png">

**Comment by mattkrick** [comment]
this is helpful!
I'm not sure we should show the "See Formatting Tips" part on the card front though, here's why:
there is joy in finding out features on your own (snapchat is the alltime KING of this) if i try and hit ctrl+b and it just works, I'm delighted.
...and then for the old farts we can put a link to formatting tips on the card back

**Comment by mattkrick** [comment]
feel free to edit this, i'll design it to this spec:

It
- [ ] autoFocuses if no title is present
- [ ] if it has focus, goes to the content if you hit the down arrow or the tab key
- [ ] if it has focus, saves changes to server if you hit the down arrow or the tab key
- [ ] blurs the card if you hit the Enter key
- [ ] shows `editing...` if you are editing the title
- [ ] has `Add a title...` for a placeholder
- [ ] content has an `add a description` placeholder
- [ ] has max char limit of 140 chars when typing
- [ ] if title is over limit & it is integrated, it will break at the last word & move the rest to the content
- [ ] migration options (pick one @ackernaut @jordanh):
  - [ ] will copy the first line up to 140 chars from the content & make that the title (content stays intact)
  - [ ]  will copy the first 4 -5 words from the content & make that the title (content stays intact)
  - [ ] remove the first line of content and set to title _as long as that line does not contain a tag or link or other entity_
  - [ ] be set to "No Title"
- [ ] is big & bold & cannot be changed
 

my remaining tensions around titles:
- i cannot use tags in title
- part of me still wants to only have 1 content field & style the first line big & bold to allow for full functionality in the title

**Comment by ackernaut** [comment]
@mattkrick I’d like to hear more about your idea on making the first line big and bold…so does first line me when it breaks or when it wraps or both? Also, I would probably only make it % bigger since the user should have editing capabilities to make things bold…best of both worlds? Users realize the first line is larger so they can put some key words (title-esque) there to remember the gist of the card, but it is completely editable and really just one group of entities. I’m just curious where/how first line ends?

**Comment by ackernaut** [comment]
@mattkrick oh another question! I’m wondering (and assuming) if it would be trivial to map [Parabol card first line content (aka title-esque) + rest of content (aka description-esque) **TO** GH issue title + first comment content] for the sake of a two-way synced integration feature?

**Comment by mattkrick** [comment]
first line would be up until a line break (they hit enter, shift+enter). we could limit it/bump them to the next line after a certain # of chars.

breaking up the title/content is pretty trivial. basically the title is the first "block" and the content is everything else.

I already built it using 2 separate fields. give it a try & let me know how it feels.

**Comment by ackernaut** [comment]
Interesting, a few more questions about content with first-line superpowers:

1. Would we only have one placeholder?
2. Would we have cards that are potentially first-liners only?

**Comment by mattkrick** [comment]
yes & yes

multiple placeholders kinda make it feel like a form or something heavier than a "jot a quick description", you can uncomment out the placeholder in ProjectEditor.js in the title PR & see how it feels (note the styling is still pretty bad).

I think we'll have 1 liners regardless of whether we separate the title or not, sometimes you just want something short n sweet. all depends on how light/heavy we want the "Project" entity to feel

**Comment by ackernaut** [comment]
Well, I'm ok trying a single content field where the first line is a % bigger. But I would let users decide what is bold. I was thinking 18/13 or 20/14 on default font-size but still experimenting in Figma. 

I also like the single placeholder: (something like) “Describe your project or task”

So if you feel strongly is it ok to move that direction?

**Comment by ackernaut** [comment]
Correct me if I’m wrong @mattkrick but we are going to move forward with a single content area and dynamically pull a title (ex: for a GH issue) from first set of characters up to a charmax and/or break to next line? The comment (GH issue) is all characters after that charmax and/or break?

First line is default styling (not bold) —users can make it bold if the want? And perhaps change size in the future?

**Comment by mattkrick** [comment]
yeah this is all good, i'll close down the title PR
