### ISSUE TITLE
Card editor: emojis

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1046]
## Enhancement

The card editor supports:

- [x] An emoji menu triggered by pressing colon `:`
  - Do we autosuggest?
  - Can users type `:` and keyword?
  - Users press enter to commit?
- [x] Users can paste/insert emoji from standard OS keyboards (Mac OS, iOS, Android, etc.)

**In the Future**: We may have a formatting bar with a 😄  icon that triggers the same emoji menu.

**Estimated effort:** 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
feel free to rule this out of scope, but should we offer universal emojis?
Problem:
- Taya's emojis on her chromebook look different from your emojis, look different from my UGLY linux emojis 
![screenshot from 2017-06-01 11-40-47](https://cloud.githubusercontent.com/assets/5514175/26695282/36c533a0-46bf-11e7-9cfd-d3b1e5b98648.png)

we could use something like https://www.emojione.com/

**Comment by ackernaut** [comment]
Part 2? It’s a good detail to catch.
