### ISSUE TITLE
Remove Slack channel

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1049]
## Issue - Enhancement

Let's add a control (and the plumbing) to make it possible to remove a configured Slack notification channel.

![image](https://cloud.githubusercontent.com/assets/103000/26724537/9c64f0f6-475f-11e7-8732-dcd74232c83a.png)

Let's use the space that currently displays "ID" and replace it with a small button, for now.

- **Estimated effort:** 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mwalendzik** [comment]
This issue seems to be closed, can anyone agree?

**Comment by jordanh** [comment]
That's true! This looks closed now too. Closing...
