### ISSUE TITLE
Card editor: drag n drop support -- safari bug

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#1050]
Currently, because the card is wrapped in DnD, no caret shows up in safari. (bug in draft)
In chrome, everything works, we just get a nasty error message when we drop the card.

These problems will go away on their own after we solve our UX problem--

In action today, you click once and that card turns into an editable field (and the caret goes to the end). That means, to edit something in the middle of the card, you need to click twice.

This is bad because you have to click twice, but good because there are no accidental drags. We could do the same with draft: basically set the card to read-only mode, and when you click it, turn that mode off & focus, but again, we get the caret at the end problem.

My dream UX would look something like this:
- start in read only mode. This is mandatory because otherwise a click & drag on text will just put the anchor down & begin selecting text. that's annoying if you have a textful card and wanna drag
- onMouseUp, if we didn't drag, activate the card where the click occurred. We can see if we dragged by mutating a higher-scope var in an "onDrop" handler. the hard part is figuring out where to put the caret based on the read-only mode.

options:
- guess and check. get the x,y coords of the click, then turn off read only mode, then move the caret around until we get close to the x, y coords. then manually set the caret there.
- replay event. given a synthetic mouse click, it may be possible to copy it, turn read-only mode off, then replay it. 
- BAU. just make them click once to turn read-only mode off, then click again to get where they wanna get.

**Comment by jordanh** [comment]
Oh fun! I'm not opposed to starting with the punt ("BAU") and coming back to make this better later.

**Comment by mattkrick** [comment]
i agree, i'm just not sure what better is:
- if i click on text, i want to see my caret going right where i clicked
- if i click and drag somewhere in the text, i could either want to highlight a text block, or i could want to drag the card. it's possible to drag the card by clicking on nontext, but this is the only want to highlight text, so that should be the behavior. 
- if i click and drag somewhere not on the text, i want to drag
- if i click on nontext, i probably want my caret to appear on text closest to my click

left to do:
- if my cursor is hovering over text, i should see the caret
- if my cursor is hovering over a button, i should see a pointer
- else, i should see a drag finger
