### ISSUE TITLE
client exception fetchScripts of undefined on [draftjs]

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1051]
## Issue - Bug

When I attempt to use the latest on `draftjs`, I see the following exception. Here are my repro steps:

1. npm run build:dll && npm run dev
2. Navigate to localhost:3000
3. Login via auth0 (jordan@prbl.io / ...)
4. Witness redirect to `/me`, see blank screen, open dev console and observe:

![image](https://cloud.githubusercontent.com/assets/103000/26793470/faa8ba60-49d2-11e7-9b5d-db3e619c0547.png)

I think I must be missing something new. What might I be doing wrong?

- **OS:** OSX
- **Browser:** Chrome

**Comment by mattkrick** [comment]
oh yeah, i'm running a couple things off symlinks. i'll push an update in a few mins

**Comment by mattkrick** [comment]
ok, good to go
