### ISSUE TITLE
User Name prompt

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#1054]
## Issue - Enhancement

Several users have indicated that it is unclear that they're selecting a User Name during this sign-up/team formation prompt:

current: “Please type in your name”

edit: "Please type in your User Name"

**Comment by ackernaut** [comment]
Interesting—when I think of a username I think of something sans spaces, usually all lowercase. I wonder if people will start typing something along those lines when we change it. Whereas with “name” I just write “Terry” or “Terry Acker” —what is our intention? Showing their name or a username?

**Comment by jordanh** [comment]
What about, "would you like your team mates to call you?"
