### ISSUE TITLE
Project vs. Private card prompts

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#1055]
## Issue - Enhancement

Ongoing user confusion about Project vs. private

**CURRENT:**
_[prompt/line1]_ [User Name + Agenda item]
_[prompt/line2]_ What do you need?
_[prompt/line3]_ Projects: tracked outcomes - Tag with #private for quick personal tasks

_[1st card/line 1]_ Add a New Project
_[1st card/line2]_ (or just press "p")

![project personal](https://user-images.githubusercontent.com/14892189/26893002-0e1dbea4-4b88-11e7-8402-f3f039b274f5.jpeg)

**EDIT**
_[prompt/line1]_ [User Name + Agenda item]
_[prompt/line2]_ What do you need?
_[prompt/line3]_ [delete]

_[1st card/line 1]_ Add a Project or Task
_[1st card/line2]_ (tag #private for personal Tasks)

**note: I have _never_ observed a real user "press p"; perhaps this could become a  hover toast/prompt?

**Comment by ackernaut** [comment]
👍 🔥
