### ISSUE TITLE
scheduling prompt

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#1056]
## Issue - Enhancement

![scheduling](https://user-images.githubusercontent.com/14892189/26893180-99667b04-4b88-11e7-92d1-2c0e166cf92d.jpeg)

Many first-time users need to be verbally guided past this to scroll down to the meat of the Summary--they assume the purpose of this screen is to get them to schedule. I propose we move this scheduling prompt for the following reasons:
-it takes too much real estate at the top of the Summary
-it is information that is only useful to the teammate responsible for scheduling, not all users
-it is not necessary after regular cadence is established

Proposal: move this to the sign-up process and also permanently house the option in the Team Settings toolbox

**Comment by jordanh** [comment]
Could be part of an onboarding and freemium epic.
