### ISSUE TITLE
Rejoin Facilitator prompt constancy

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#1057]
## Issue - Bug
During testing, when the Facilitator was on the first Agenda prompt screen (not actually processing Agenda yet, just prompting users to enter Agenda items) a user went back to Updates but the "Rejoin Facilitator" prompt didn't show up in their bottom right until after the Facilitator moved to the first Agenda item

**Comment by jordanh** [comment]
Looks like a good one for an intern!

**Comment by tayamueller** [comment]
fixed!
