### ISSUE TITLE
delete teams

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#1058]
## Issue - Bug

I see that now when I "Leave Team" the team is deleted from my leftnav column. 

However, 5 old teams (before the update?) remain, although I am no longer a teammate

**Comment by ackernaut** [comment]
Yeah, I have this same issue. Is there a way to migrate data and clean up those old teams @mattkrick ?

**Comment by jordanh** [comment]
This only applies to old teams. Step 1: let's come up with a query.

**Comment by mattkrick** [comment]
Duplicate of #1001
