### ISSUE TITLE
Long agenda list autoscroll

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1060]
## Issue - Enhancement

When the agenda list is long (so long that it needs to be scrolled) and the meeting progresses to later agenda items, the list stays scrolled to the top making it difficult to see what item you are on and what items are coming next. It's be great if we autoscrolled this such that the current item is always visible.

- **Estimated effort:** 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mwalendzik** [comment]
This issue seems to be closed, can anyone agree?

**Comment by jordanh** [comment]
That's true! This looks closed now. Thank you for verifying.
