### ISSUE TITLE
collaborative editing for projects (Draft-js vs others)

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#1061]
After playing around with draftjs, it looks like collaborative editing is going to be a challenge. this is because draft stores the state, not the operations. Both OT & CmRDT need operations. We could use a CvRDT, but those are rarely talked about because we'd basically be passing around the whole paragraph & the merge would be painful.

So, if we wanted to implement OT/CmRDT in draft, we'd have to fork it & make it talk in operations instead of state. that's not the end of the world, basically all the operations already exist under `Modifier` so we'd just make a json of the method & its args & send it on its way. the undoStack can remain a state because you only care about undoing your local changes, not remote changes. The problem arises with transforming the operation. for example, `{type: 'insert', pos: 5, val: 'a'}` and `{type: 'insert', pos: 6, val: 'b'}` are 2 ops. as is, op1(op2(state)) != op2(op1(state)). in order for correct this, we'll need to create a position map after each operation. for example, if the word is `foo` and one person changes it to `afoo` and another changes it to `food`, we want the final result to be `afood`. this works great if the `d` msg comes first, but if the `a` comes in first, we need to offset that `d` msg transformation.

while draft js isn't really prioritizing this (https://github.com/facebook/draft-js/issues/93), there are a few other WYSIWYGs that are: 
- https://github.com/ProseMirror/prosemirror has an OT implemented 
- https://github.com/ianstormtaylor/slate/issues/259 is in the exploratory phase of moving to OT

if facebook could turn relay classic into relay modern, i have no doubt that they could also rewrite draftjs from the ground up _if_ collaborative editing is made a priority. if they don't we'll have to check back in with slate in 6 months & see where they are. for now, our super naive soft-lock/last write wins strategy will have to suffice.

**Comment by mattkrick** [comment]
if the V8 engine has taught me anything, it's that nothing is impossible given enough $$. I'm still happy that we chose Draft & I'm betting the facebook guys will at least make this a possibility. 

Fun quote i found along the way (wrt OTs): "Wave took 2 years to write and if we rewrote it today, it would take almost as long to write a second time." I quietly repeat that to myself when i wonder why i can't just make it work in a weekend.

**Comment by jordanh** [comment]
I think we could close this issue, yes?
