### ISSUE TITLE
card editor: paste, migrate, import

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#1064]
with all the new functionality, we need to decide how crazy we wanna get with pasted text--
- do we want to convert pasted markdown?
- do we want to convert tags to entities? (eg if someone pastes `this is a #private message` should we make `#private` a super power?)
- do we normalize pasted-in styles?

**Comment by mattkrick** [comment]
if text is not typed into the draftjs editor, there are 3 ways it can end up there:
- get pasted in. pasted in text can be html or text. if it's text, it could be plain or markdown.
- migrated from old content. this is markdown text.
- imported. imported could be html (although i don't think it will be). it could also be text. if it's text, it could be plain markdown (but again, doubtful).

so, we can punt on html, but to support migrations for this PR, we need to support markdown.

In order to support markdown, we can do it a couple ways:
- convert MD to HTML to draftjs. then, to add in things like `#private`, we'll need to traverse the content looking for a list of keywords to convert to entities. this requires a DOM (or synthetic DOM). if we do this, then we'll need a markdown library on the client side. we'll need to write a separate function for pasting. for example, when we catch a paste, we'll want to scan it for keywords. if any are found, then we need to calculate the range & save it. then, we let draft-js do its thing (text -> draftjs). afterwards, if that trigger was hit, then we need to go through that range & look for those keywords and replace them.
- write a converter that goes directly from MD to draftjs. this will take more time because it'll basically just be a series of regex (and so more error-prone, too). it does not require a DOM. it is faster & smaller and it will work for paste, migrate, and import. 

so, the top option looks like the best (for now). it'll be a 2-part function. part 1 takes a markdown string & returns a draftjs structure. part 2 traverses that structure looking for key phrases & turns them into entities. only part 2 will be executed on pasted text.  (and at a reduced range, because it's possible that there is some text above/below that pasted range that doesn't want to become a superpower).

**Comment by ackernaut** [comment]
Thanks for sharing your thinking on this one. What you’re describing makes sense to me.

**Comment by jordanh** [comment]
I'm suspecting this might get closed...

**Comment by mattkrick** [comment]
flagged as discussion, closing since we ruled paste/migration to be out of scope.
