### ISSUE TITLE
Inconsistency between trial and invoice date

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1065]
Of course, I extended my trial several weeks ago. However, I unexpectedly saw this today when signing in. Somewhere there is a discrepancy in our maths.

![screenshot 2017-06-12 10 27 07](https://user-images.githubusercontent.com/307286/27041516-d4f25aa6-4f59-11e7-8e66-e8f2b7cf75f9.png)

**Comment by jordanh** [comment]
Iceboxing. And, we don't have trials any longer.
