### ISSUE TITLE
Free Trial Start Date = First Meeting, Not Upon SIgnup

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#1066]
## Issue - Enhancement

The lag between signup and first meeting is not a good indicator of interest or intent to use. A new user may sign up and kick the tires MONTHS before their team is in a good place to implement a new product.

Frequent use case: a user is conducting research for future purchase, or simply hears about us "somewhere" and decides to sign up. Currently, our free trial clock starts ticking immediately. However, it often takes a while for these things to kick in--timing, team readiness, internal selling, etc. **The larger the org, the longer the lag time.**

Proposal: 
1) The product remains free for all users until First Meeting with at least 1 other user.
2) All Billing Leaders get a free 30-day trial which begins on the day of the First Meeting with at least 1 other user.

**Comment by jordanh** [comment]
This issue should become a part of a larger _freemium_ epic. Needs more design and consideration.

**Comment by jordanh** [comment]
Hey, we implemented Freemium! Closing this.
