### ISSUE TITLE
Suggested "Stuck" card refers to "Team Settings" that is not visible in "My Dashboard" view, and only in a specific team view

### ISSUE THREAD

**Issue by oliver-zhou** [ParabolInc/action#1067]
## Issue - Enhancement

![image](https://user-images.githubusercontent.com/906828/27058812-4c52e556-4f88-11e7-962a-344d5713cdf8.png)

The message 
"Invite any missing team members to join the team. Tap on ‘Team Settings’ in the dashboard header above."
is only relevant when in the individual team view - in the "My Dashboard" view, the "Team Settings" button is not there. I spent a bit looking for the Team Settings button before realizing where it is - 

i.e., only available in this view: 
![image](https://user-images.githubusercontent.com/906828/27058918-be073dfa-4f88-11e7-89d7-da940cbd12b1.png)

- **OS:** OSX
- **Browser:** Chrome
- **Estimated effort:** 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Trivial fix. Let's reword seed card to include "by navigating to your team and then clicking..."
