### ISSUE TITLE
Changing Team Name doesn't update references 

### ISSUE THREAD

**Issue by oliver-zhou** [ParabolInc/action#1068]
## Issue - Bug

After updating the team name - references to the old team name persist across the application
For example - the "Show Projects For" dropdown dialogs remain referencing the old name

![image](https://user-images.githubusercontent.com/906828/27059118-c28feb50-4f89-11e7-82a6-f08f64c78616.png)

- **OS:** OSX 16F73
- **Browser:** Chrome Version 58.0.3029.110 (64-bit)
- **Estimated effort:** X points

**Comment by jordanh** [comment]
Good find @oliver-zhou! _Muchas gracias!_

Oh! Could this be another `@cached` directive thingy @mattkrick?

**Comment by jordanh** [comment]
Retested this on v2.3.0 and this bug no longer exists. Must have fixed it when we moved to Relay. Huzzah!
