### ISSUE TITLE
Copy edit: what's changed since last week?

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1069]
## Issue - Enhancement

It'd been a couple of weeks since Sasha and I had last held a meeting. The question, "what's changed since last week?" was a little presumptuous of our team rhythm. I think we should consider changing this to, "briefly, what's changed on each project?"

- **Estimated effort:** 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
final copy: What's changed since our last meeting?
