### ISSUE TITLE
Assign to all

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1071]
## Issue - Enhancement

When I want all team members to take the same action, I'd like to "Assign to all" team members, so I don't have to repeat myself.

We'll need some design on this one. Initial thoughts: click face to assign, special icon indicates all. When selected, card is styled to look like a stack to show duplication.

Any other ideas?

- **Estimated effort:** 15 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
I have been wanting to improve our menus to support multi-select (optional). I could see a way where one could toggle all menu items to be selected/deselected. Once all menu items are toggled, you could deselect any that do not apply. Taya had mentioned assigning the 3 of us, but not herself.

So: 1) Taya opens assign menu 2) Taya toggles all selected 3) Taya deselects herself

This is more utilitarian and could be used in other contexts.

Also, on the dashboard we have filtering by (all teams / single team) and (all team members / single team member). Adding multi-select could be interesting there, too—especially as we begin to iterate on dashboard search + filtering concepts.

I like the stacked cards idea (reducing visual clutter). One simply edits the top card to apply to the ones below (same content, just multi-assigned during the agenda round).

**Comment by jordanh** [comment]
Super-ceded by #2010 and iceboxing.
