### ISSUE TITLE
Auto-scroll project columns

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1072]
## Issue - Enhancement

I often have difficulty using _My Dashboard_ to prioritize project columns because the columns don't always autoscroll neatly. For example, have a look at the following gif:

![project scrolling](http://g.recordit.co/oxhpo3GMCK.gif)

I want to de-prioritize buying shoes. I select the card and attempt to drag it to the bottom. I'd expect that when I do this, the column will scroll to allow me to move the project cleaning to the bottom of the list if I want to. However, the column does not scroll.

This may be a rare "b-hancement"

- **Estimated effort:** 15 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by tayamueller** [comment]
YES.

**Comment by tayamueller** [comment]
increasing observation of this frustration as our users move from early (sparse) boards into 2nd & 3rd months of usage

**Comment by mattkrick** [comment]
Prioritizing this to epic 8 after chatting with Larry.

**Comment by ackernaut** [comment]
- [ ] Move to Relay
- [ ] Build a "cheap" card component w/o functionality
- [ ] add animations (V2.0)
- [ ] auto-scroll w/ react-virtualized

**Comment by dan-f** [comment]
I'm able to grab this one, assuming nobody is working on a fix yet.

**Comment by mattkrick** [comment]
@dan-f that would be great. could you build it with react-virtualized? (the website has really good docs & we use it in the team archive). that way auto-scrolling will be trivial to implement & we can support boards with a stupid amount of cards.

feel free to work off of projects-to-relay branch

**Comment by ackernaut** [comment]
@mattkrick @dan-f I’m wondering about what flexibility we may have with sizing columns. My impression was that react-virtualized is pretty rigid (not fluid) but maybe there is a way where we can control the size of columns and have the virtualized DOM fill it 100%? We should take offline to discuss.

**Comment by mattkrick** [comment]
yeah, a fill is pretty easy. The archive is a different story because that was a grid, not a column. still, it can all be done inside JS.

**Comment by dan-f** [comment]
@mattkrick - roger, I'll look into react-virtualized, and the sizing issue.

**Comment by ackernaut** [comment]
@dan-f up to you if you want to re-classify this as E8 or E8.5. I personally don’t think the classification prevents this value from being merged into master and released early, or released in an E8 or E8.5 branch. Imperfect but moving forward!
