### ISSUE TITLE
Project column insert point enhancement

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1073]
## Issue - Enhancement

When I want to insert an item at a particular point in the list, I'd like to hover at that point and access an easy control to add the item, so that I don't have to create the item and then scroll it to where I want it to go.

- **Estimated effort:** 15 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
Here’s a visual (the ➕  in a circle shows when you hover):

<img width="1280" alt="dashboard-chrome 2x" src="https://user-images.githubusercontent.com/307286/27088107-6e33ad74-501c-11e7-9922-450bc789febf.png">
