### ISSUE TITLE
Menus overflow; expand viewport

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1076]
## Issue - Bug

Trying out menus for #1075, I noticed they can push the viewport around.

One thing I did try was throwing (CSS) `max-width: 100vw` on the `<div/>` that contains the portal locally in inspector. Not sure if that is the solution that we want to try, but it did seem to force the menu to auto-position more consistently.

Here are some samples:

![recordit](http://g.recordit.co/GguzrsO9bF.gif)

![screenshot 2017-06-13 15 54 09](https://user-images.githubusercontent.com/307286/27104282-53b0f648-5051-11e7-9bc9-0d7e78217197.png)

**Estimated effort**: 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
ah this is a good one that i was waiting on to design.
if you're happy with the 100vw i'm happy with it. the way that this is commonly accomplished is by measuring where the modal will appear, what the width will be, and get the min of width+left and 100vw.

**Comment by mattkrick** [comment]
should we worry about the Y axis, too?

**Comment by mattkrick** [comment]
imma go ahead & worry bout the Y

**Comment by ackernaut** [comment]
Yeah, I think `width/max-width: 100vw` and `height/max-height: 100vh` on the div dedicated to the portal would work?
