### ISSUE TITLE
"Observer" or Occasional User Status

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#1078]
## Issue - Enhancement

When a user is not on a team, but needs, or likes to see what that team is up to, our users/team leads are requesting a status differentiated from fully "Active"

> "When you’re selling to management you’re selling reporting." -a smart guy we know

### Acceptance Criteria (optional)
Users can:
- Observers are not charged. There is no limit to how many Observers can be added to a Team.
- Observers have full visual access to the Dashboard.
- Observers ARE included in the upper right lineup of the static Team Dashboard view; to the furthest right position/s, with a darker/darkest dot
- Observers are NOT included in the upper right lineup/any phase of a Meeting
- Observers ARE included in the Summary roundup & email

- **Estimated effort:** 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
I like where you’re going with this! I have pondered the idea of having “guests” —what would that entail? What is the use case around having guests. Would it lead to more adoption?

**Comment by jordanh** [comment]
This would be done around the same time we think about adding team settings to make a team private, and requiring that a user be a paying user in order to enjoy these rich features.

**Comment by tayamueller** [comment]
11.17 - reinforced by passive user team observation: "I wish there was an Observer role in the meeting.” “Haha, I would be drunk with power on that feature!” :)

[context: a person at their company wants to observe this team's meetings; the team doesn't mind but they don't want them to slow them down or distract them.]

**Comment by tayamueller** [comment]
Notes from Pro user: 

> probably a feature that most of your customer orgs don't want/need, but... this message was posted in our Origination team channel, and _as another person at August who is not on the Origination team but likes to see what other teams are up to_ ... I clicked the link and then was disappointed to discover that I needed to log in to see the info"

> this [issues, as written] would solve my own need in this case. however, i think i'm more interested in a general 'default to open' setting where all meeting summaries are available to view for everyone. but, again, not something i assume most users want/need"

**Comment by tayamueller** [comment]
*requested by client on 5.21.18

"Just a view-only link; sometimes we're cranking along but we have no way of showing anyone what we're doing b/c it's in Parabol. Even if it's not a user type but a publicly viewable link, to share with someone not in my orgr that would get us what we need. No one's going to go find my Parabol board."

**Comment by ackernaut** [comment]
I like that idea, read-only view to perhaps dash, meeting, summary as a team settings option?

**Comment by jordanh** [comment]
Iceboxing for now. I'm _sure_ it'll come up again.

**Comment by tayamueller** [comment]
feedback from a 31-person Pro team:

> we want to share the after-action report with other teams. But for access or email report everyone would need to be in the other teams, which doesnt make sense. Is there a way to share that semi-publicly? 

> basically, we want to share updates between the other teams and a separate "caretaker" account and while CSV is nice, it's not as readable as the mail format.

**Comment by tayamueller** [comment]
variation on this request from [this user](https://app.hubspot.com/contacts/3888472/contact/3254151/):

> I have a use case that I cannot easily cover with Parabol: we have the need of inviting other people in our retrospective sometimes (usually for exchange programs we have to allow developers to spend a sprint in another team every quarter or so, or when a project manager was involved in a sprint for instance). **It would be great to have a way to invite someone for just one retrospective, not giving him access to all the ongoing and done actions.**

**Comment by tayamueller** [comment]
variation from [this 14-person Free team](https://app.hubspot.com/contacts/3888472/company/1691135010):

> The invitation process was clunky for me. I would have much preferred to be able to send a link out rather than have to scrap through all my teammate's emails. **The meeting invite email didn't just let them in. If I had external parties, that would make it challenging since I wouldn't want them to be apart of all our retros**

**Comment by jordanh** [comment]
Iceboxing again
