### ISSUE TITLE
Card Date Revision

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#1080]
## Issue - Enhancement

PROPOSAL: date marker remains tethered to first creation, not most recent edit.

- The current date marker shows the date of last edit. This is less useful than showing the date of first entry.
- When a teammate accepts a Project card, there should be a simple visual method for the team to mark the passage of time from the date of first request/assignment.
- This will improve both the assignee's visual ability to self-prioritize, and assist the requester/team leader in tracking & enforcing accountability. 

*closely related/can be combined with #985 Card Rot

**Comment by jordanh** [comment]
It should:
- [ ] display `createdAt` by default
- [ ] click to toggle `updatedAt`

**Comment by ackernaut** [comment]
Same as #551 for this Epic.
