### ISSUE TITLE
Asynchronous Project/Task Assignment Notification

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#1082]
## Issue - Enhancement

When a user assigns a project or task card to another user outside of a meeting* the assignee should receive a notification of their new responsibility, and an option to Accept/Decline:

1) User A assigns a card to teammate User B, outside of a Meeting
2) Until the card is "Accepted" the owner avatar at bottom left is masked grey; the card is visible in User B's "My Dashboard" and appears if users sort for User B tasks in any Team
3) User B receives an email (Slack?) notification:
> Hi [User B], it's [User A]--will you accept this [Project/Task]? [card text copy] [Accept/Decline]
4) If User B "Accepts" card, their grey-masked avatar is unmasked and they own it
5) If User B "Declines" card: the owner avatar reverts to User A, and an Agenda item titled [snippet] is automatically created for the next meeting. When that Agenda item surfaces, the card is already present, and the team can discuss assignment

Alternately, if User B happens to see the grey-masked card on Parabol before they see the email notification, they can manually click on their avatar, and click on their face to unmask & claim ownership.

*propose that these needn't be sent to non-present users DURING a meeting because they'll receive an emailed Summary with all cards at the end.

**Comment by jordanh** [comment]
Let's leave out the "will you accept this project?" logic for now, and push forward on the notification itself

**Comment by ackernaut** [comment]
Let’s use #1430 to scope the actual implementation of v1 for this epic.
