### ISSUE TITLE
Add Project Card to Agenda

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1083]
## Issue - Enhancement

Inspired by #1082 and explorations around Inbox…

When existing project work (represented by a card) needs additional discussion/review (new information/tension/background), I want to attach it to an Agenda Item so that the project card is readily available (for review/updates) in the Agenda Round.

Additional use cases:

When a unit of work (request/signal) comes into the Inbox column/list from an integrated service (source) and I’m not sure what to do with it, I want to add it to the Agenda Queue for the next meeting so that I can process it with the team.

Initial ideas on design specs:

- Action: Add Card to Agenda (can be in dashboard chrome or card menu)
- Agenda Item with Attached Card:
  - Card Title === Agenda Item Placeholder Text
  - Card Owner === Agenda Item Owner
  - Add small card icon (and Parabol card ID number?) to the Agenda Item in the Agenda Queue (can be tapped to view async to the meeting—goes to “card back” details view/route.
- During the Agenda Round
  - The existing card is already present as the first card in the row (in its latest state, including any changes to card from Updates round)
- Perhaps this whole process also can be triggered by adding `#agenda` to card content?

**Estimated effort**: X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
**Another story to validate**: When I get a delta report and see that there are some stuck outcomes, I want to add those outcomes as agenda items, so that we can explore them in the next meeting.

Which makes me think that staggering the timing of the reports (at least as a default) may be helpful. Summary (after Mon/Tuesday meeting) Delta (on Thurs/Fri)…

When/how do we integrate with calendars to know when folks meet? “When does your team meet?”

**Comment by ackernaut** [comment]
Ways to add an agenda item:

- Use input (agenda list) on team or meeting view
- Use Slack command (channel to team configuration?) `/agenda [content]` or `/agenda [team] [content]`
- Reply to Delta email; parse each new line with `#agenda [content]` from email
- Tap “Add to Agenda” per outcome in Delta email
- Add action to project/task card “Add to Agenda”

**Comment by jordanh** [comment]
Let's scope this down only to add a link to the email generated for stuck items so that a stuck item can be added to next week's meeting agenda.

**Comment by tayamueller** [comment]
Sometimes, a Stuck item needs to be escalated to a Team Agenda Queue.

Currently the steps are:
-(original card is in Stuck)
-related Agenda item is typed in Queue
-Agenda item is processed in Meeting
-(no access to original card) new card is typed
-redundant cards now exist

Would be nice to be able to simply "Move to Agenda" from inside the bottom right menu options:
-(original card is in Stuck)
-user selects "Move to Agenda" from menu options
-card remains in Stuck column (perhaps highlighted light purple? some other visual signifier?)
-first line of card text is also added to Agenda Queue
-(if Agenda item is deleted, original card reverts to normal protocols)
-when Agenda item is processed in Meeting; original card is visible as a pre-populated card
-card (with any new edits & column classification; moved to Active, etc.) reverts to normal protocols

**Comment by jordanh** [comment]
Iceboxing for now
