### ISSUE TITLE
remove staging, use master

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#1087]
right now, the master branch only serves to confuse. I propose that we remove staging & use master to serve that purpose. objections? @jordanh?

**Comment by jordanh** [comment]
I'd like to keep `master` as "tip development, integrated across feature branches" and the branches as hooks to deployment (think of them as synchronized to server infrastructure). I do want to setup a development server though.

So:
* merge from any feature branch to dev
* merge from master to staging
* merge from staging to production

I think I may be missing an important tension of yours though, so I'd like to talk about it more.

**Comment by jordanh** [comment]
@mattkrick would you like to discuss this further, or may I close this out?

**Comment by mattkrick** [comment]
closing out, master -> dev, staging -> staging
