### ISSUE TITLE
Handle deleting a team member (post-MVP)

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#109]
## Issue - Enhancement

Just a reminder that when we delete a team member from a team, we also need to remove that from the in-memory `socket.authorization` array.

The easiest way to do this is probably:
- publish `{type: KICKOUT, user: userIdToRemove}` to both `meeting/:meetingId` and `presence/:meetingId`.
- write a `PUBLISH_OUT` middleware that listens for `req.data.type === KICKOUT`. And if the `req.data.user === authToken.sub`, then we know this is the guy we should remove
- call `socket.kickOut` within that middleware
- call `next(true)` to fail silently so nothing ever goes back to the client for any of them

How critical is it that a removed team member be kicked out immediately? Probably not very, but since our server is open source, that means _The World is Watching&trade;_ so we gotta keep it tight.
- **Estimated effort:** 2 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))
- **(Optional) link to mission spec:** ([duplicate and edit template](https://docs.google.com/document/d/1lgTJnJzBt9-4If883iOvthmc0hy-6C6hBF7KNN-lsXU/edit))

**Comment by jordanh** [comment]
Ha! Good to stick in the icebox. ❄️

**Comment by jordanh** [comment]
Perhaps related to #488 ?
