### ISSUE TITLE
accepted Project card content length is long [draftjs]

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1092]
## Issue - Bug

Our test cycle specifies that maximum content length should be 512 bytes, but I've tested that a draftjs project card will at least happily take 4096 bytes.

At some point, a card with a lot of content degrades the user experience if the content isn't hidden behind a design element such as an ellipses. I don't have a lot of tension holding up the merge for this, but I think we should track it and make some decisions...

**Comment by mattkrick** [comment]
`content` now contains a stringified JSON object that includes not only the plain text, but things like metadata (link urls, mention userIds, etc) and styles. i bumped the total length to 51200. Alternatively, we could limit the _plaintext_ length to 512 characters if you prefer, it just means parsing the JSON object, hydrating the raw object into a draft-js object, and then calculating the plaintext length. little extra overhead, but nothing too bad.

**Comment by jordanh** [comment]
Closing.
