### ISSUE TITLE
Link removal doesn't work for multi-word links [draftjs]

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1094]
## Issue - Bug

Reproduction steps:
1. Create a new project card
2. Type `I Like Google` and make it a link to `https://google.com` with command-k
3. Type `/` to make a pretty delimiter
4. Type `I Like Bing` and make it a link to `https://bing.com` using command-k
5. Highlight the words "I Like Google" (or place the editor cursor within them) and attempt to remove the link

- **OS:** OSX
- **Browser:** Chrome

**Comment by mattkrick** [comment]
Nice find, I can see how this yields an unexpected result!
How about this proposal:
- if the selection is collapsed (ie you have a single flashing caret, no selection range), remove the link from every character to the left and to the right until a character is found that is not part of that link
- If the link takes up 2+ blocks, remove it from characters in those surrounding blocks as well
- To remove the link from a subset of the whole linkified phrase, you must highlight that subset & click remove.

Give me the thumbs up & I'll change @jordanh

**Comment by jordanh** [comment]
Yes. This sounds perfect! 👍

**Comment by jordanh** [comment]
This UX also applies to link changes as well. Can you make it such that if links across words are the same, that the Link Changer changes the link for all words?

**Comment by mattkrick** [comment]
aahhhhh yeah

**Comment by mattkrick** [comment]
- if the selection is collapsed 
  - if the character to the left of the caret is a link
    - go all the way to the left & right until the link ends
  - else
    - select the word
