### ISSUE TITLE
Pasting a block of markdown does not work as expected [draftjs]

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1095]
## Issue - Bug

This block of test markdown does not render as expected. Perhaps this case isn't supported?

````
I am _italic_
I am also _italic_
I am __bold__
I am also **bold**
I am __*bold italic*__ 
I am __*~bold italic strikethrough~*__ 
I am `__*~bold italic strikethrough code~*__ `

> blockquote line 1
> blockquote line 2
> blockquote line 3

```
somecode() {
  // in a block
  while (1) { console.log(“hello!”); }
}
```

[Go Parabol](https://parabol.co)
````

Reproduction:
1. Copy above to clipboard
2. Create new Project card and paste
3. Observe render result

- **OS:** OSX
- **Browser:** Chrome

**Comment by mattkrick** [comment]
i haven't built in paste/migration support. will close for now, i'll leave it up to you to decide where we want to prioritize this. My gut tells me that when we work on migrations, we'll have to write a markdown converter & then we can reuse it for pasted text, too.
