### ISSUE TITLE
extra click needed to apply #private tag styling [draftjs]

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1097]
## Issue - Bug

Reproduction steps:

1. Create a new project card with the content `super secret project #private` and save it by pressing tab
2. Note that card does not turn yellow
3. Click elsewhere, e.g. blank space below a column of project cards. Note that card turns yellow.

- **OS:** OSX
- **Browser:** Chrome

**Comment by mattkrick** [comment]
Currently:
- Hitting tab does _not_ save. It simply moves to the next item on the card (in this case, it selects the team member avatar in the lower left, hit it again & it highlights the wrench, hit it a 3rd time & it'll move to the next card

Is this a bug? If so, we need to consider:
- how should someone change the user, status without the mouse?
- how do we delete an empty card? we want to allow them to change the user before typing text, so if they hit tab & it blurs the whole card, then they can't change a user.

**Comment by jordanh** [comment]
It _is_ interesting to consider. Previous to draftjs, when a user wanted to save a card they pressed `enter` and `shift+enter` to create a blank line. Now, we've got a tab blurs the card and (a subsequent click?) saves the card.

Let's look at your excellent questions:

> how should someone change the user, status without the mouse?

I think we should refine our concepts of card hover and card blur and then think about how to apply operations to cards. I'll attempt to pin a couple of things down, but continue to clarify:

1. When a cursor is anywhere within a card's dimensions, it's got hover or,
2. When no card has hover (or focus) and tab is pressed we cycle through each card (notes on card order given at bottom)

I think from hover state, we can then proceed through a number of edit states:

1. `enter` then focuses content field (until title comes along, then it'll focus title field). `tab` then cycles between fields on the card, just like it's a form. `tab` saves (unless we want to make `enter` save, but I don't have a lot of tension about this). Pressing tab retains hover.

2. When a card has hover, status may be edited. Options for key shortcuts `meta-k` moves a card up in priority order, `meta-j` moves it down in priority, `meta-h` moves the card a column to the left, `meta-l` moves the card a column to the right. And, also when a card has hover (and no field has focus) perhaps pressing `s` opens the status menu (and a status can be selected via arrow keys and enter).

3. When a card has hover (and no field has focus), a user may be assigned by `u` which raises the user menu.

> how do we delete an empty card? we want to allow them to change the user before typing text, so if they hit tab & it blurs the whole card, then they can't change a user.

I _think_ this will be resolved by adding an explicit hover state... I'd also like to enable something like 656 by tracking state and styling cards, perhaps with a unique color state. This is for context, not scope on this PR.

_Notes on card order:_ when no card has hover or focus, we'd probably want to make the first Card the Card that the user is most likely to interact with. This is probably the topmost Card in the Active column. Extending this out a bit, the order might look like: topmost Card in Active, then topmost card in Stuck, then topmost Card in Future, then topmost Card in Done.

**Comment by mattkrick** [comment]
I think Enter used to be OK back in the day where the concept of "content" was much more lightweight. it was little more than an agenda item and a 1-liner wasn't out of the norm. Even though we broke default browser textarea behavior by making Enter submit, the lightweight nature made it OK.

Now with a title field & a description field, we expect users to have at least 2 lines per card, and we offer a lot more rich text editing, so it feels more like a textarea. Just like this comment box I'm typing into right now, it feels natural to create a new line with Enter and to goto the next field with Tab.

I have some big tensions around mouse hover state dictating keyboard behavior. I think this deviates too much from standard browser behavior to be useful for folks (not to mention it means opening ourselves up to crazy cross-browser compatibility issues). I think the 2 states should be decoupled, meaning that hitting tab should do the same thing no matter where my mouse cursor is.

As a keyboard user, I expect the following to be true on any website:
- hitting tab will focus the next focusable element
- hitting enter when an element is focused is the same as clicking it

As long as we hold those truths, I'm happy to adjust as you see fit. Are there any actions I can take on this issue to wrap up the PR?

**Comment by ackernaut** [comment]
I like trying to stay true to expected tab and enter behaviors. Also I think I’m convinced on having a single content area where we can size the first line to a % larger or give users the option of cycling up/down 3 sizes (small, normal, large) using `command + shift + plus/minus`.

**Comment by jordanh** [comment]
Ok, now that @mattkrick and I are sitting next to each other its a bit clearer what's going on. The root of what I was experiencing is that I could not tell that after I hit tab to exit the content textfield that the focus for the form was shifting to the owner field, then to the status wrench, before finally exiting the card to save it.

To resolve this one, I actually think it's a minor design and style fix that's needed. @ackernaut could you have a look at styling the focus state for the components on the card? It should be obvious when the members and the status wrench have focus.

For example, here's a card that hasn't be saved yet where the content field is focused:

![image](https://user-images.githubusercontent.com/103000/27400128-f9a76208-5673-11e7-82a0-dac73fa33e1d.png)

Here's the same card with the owner control having focus:

![image](https://user-images.githubusercontent.com/103000/27400147-0dad6d74-5674-11e7-8a52-6aa0375ed6b0.png)

Maybe we need a classic blue border or a hot border?

**Comment by jordanh** [comment]
Capturing more thoughts from @mattkrick, perhaps we could also save the card when the contents are not blank.

**Comment by ackernaut** [comment]
Taking a gander 👀

**Comment by ackernaut** [comment]
I left some comments in Figma…I’m wondering if we can defer this to at least the first sprint of Epic 6 as I have some card updates that I want to propose. But basically I’m thinking add an outline for focus, otherwise background or just darker for hover.

**Comment by ackernaut** [comment]
A solution for card footer action focus as been designed and will be address when adding menus #694 (which has been prioritized for GH UI/UX)
