### ISSUE TITLE
Filter by Owner and/or Team (first step toward single kanban)

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1100]
## Enhancement

We can move to a single kanban (My Dashboard) and a first version of a Team Sheet (meeting link, agenda queue, team member settings, integrations) by adding 3 multi-select filters to the kanban.

### Updated Acceptance Criteria

- [ ] User can filter by any teams she is on (multi-select)
- [ ] User can filter by any owners per team filter setting (multi-select)
- [ ] User can filter by #archived or #private or no label (default) (multi-select)
- [ ] The default is Teams: all, Owner: me, Tag: none

Requires #692 and some solution for a simple team sheet/hub #1101

**Contextual menu options**:

Both menus are contextual based on the value of the other menu.
Example: If I filter by Team: Product, then I can only filter Owner by any team member of Product.
Example: If I filter Owner by Jordan Husney, then I can only filter Team by any team he is a member of (that I am also a member of).

**Estimated effort**: 15 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

<img width="1280" alt="dashboard-side-nav-collapsed 2x" src="https://user-images.githubusercontent.com/307286/35451060-99d469b4-0287-11e8-99e4-b121aec7af30.png">

**Comment by ackernaut** [comment]
See #843 for more ideas…

**Comment by jordanh** [comment]
Iceboxing for now.
