### ISSUE TITLE
Team Sheet v0.0.0

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1101]
## Enhancement

[spec/design WIP]

Team Sheet has:

- The team name
- A primary action: the button/link to the Meeting Lobby
- A secondary action: A link to the dashboard with pre-defined filters [owner: all, team: this team] ( designed and implemented by #1100 )
- The agenda queue (team members can CRUD)
- Header shows name and meeting link
- First phase of navigation:
  - Initial view: Agenda Queue, Link to filtered dashboard “Team Projects”
  - Team Settings: CRUD team members, CRUD team
  - Integrations: See providers, team integrations ( designed and implemented by #1098 )

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Iceboxing for now
