### ISSUE TITLE
un-archiving a project not unicode safe? [draftjs]

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1109]
## Issue - Bug

This isn't big enough to slow down merging the PR, but might be good to fix before we close out the full epic.

Steps to reproduce:

1. Create a Project card with the content: `Hang out with my friends: 🐱 🐱 🐱`
2. Next, append ` #archived` to the end of the content
3. Navigate to the archive and unarchive the card
4. Observe:

![image](https://user-images.githubusercontent.com/103000/27464399-21a40810-5782-11e7-8b75-358c5d5ca1c8.png)

- **OS:** OSX
- **Browser:** Chrome

**Comment by mattkrick** [comment]
that's a really good find.
so draft-js converts everything to UTF-8 for storage & then rehydrates to UTF-16.
I've been using the UTF-8 version because it exposes some things that the rehydrated version didn't. 
Looks like i'll need to perform an extra step
