### ISSUE TITLE
Add Slack Provider

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#1114]
Assumptions & reasoning for design decisions:

A Provider is a service like "Slack"
An integration is, in slack's case, a channel to post stuff to
1 Provider has many integrations

Slack is interesting because it only gives 1 token per user. if they ask for a new token, they get the same token they had. AFAIK there's no way to refresh the token.

OAuth every time? No!
- The OAuth window always feels daunting. It's slow, it opens up a new window, it takes away from the experience. For that reason, I want to avoid it as much as possible.
- If a user has OAuthed slack for our app previously, regardless of the team or organization, we should try to re-use that `Provider`. We can do this on a Provider-basis. If it's Slack, just do it. If we're not sure, pop a modal & ask. If we can't, fallback to OAuth. To do that, we'll change the Provider object to have a `teamIds` indexed array. That way we can reuse the accessToken without creating a whole new document. This could be dangerous if we need to put Provider-specific stuff on the Provider object, but we should probably stay away from that anyways. That's what the `Integration` doc is for.

Token Removal
- With a single Provider doc that can span across teams, when someone removes a Provider on a team, we could do 3 things:
  - Remove that teamId from the Provider doc
  - Remove that Provider from all teams
  - Ask
- I'm going with the top one because if they want to remove slack from all of their teams, i think it's fair to make them do it for each & every team. Sure, it might be a little painful, but removing Providers is rare & frankly, it's behavior that we don't want.

**Comment by mattkrick** [comment]
when you go to the integrations settings tab it
- [ ] opens a subscription to get all the Providers associated with that teamMemberId
- [ ] highlights or sorts the Providers by the one's you've already linked with (@ackernaut to decide)
- [ ] gives you an "Add Provider" button next to Providers that you haven't OAuthed with yet
- [ ] gives you a "Refresh Token" button if we know the Provider will give you a new token (Slack won't, but GH will)
- [ ] gives you a "Remove Provider" button for Providers that you have linked with

when you click add provider it
- [ ] checks to see whether you authorized that Provider with another team.
- [ ] if this is the first time linking to the Provider, or the token is team-specific, pop the OAuth window
- [ ] else, the Provider should already be autolinked when you join/create the team so it's a noop
- [ ] the OAuth window calls the Provider-specific endpoint with the teamMemberId and a new token
- [ ] the endpoint calls the Integrator MS and creates a new Provider doc

when you click Refresh Token
- [ ] it does the same exact song & dance as the Add Token

when you click Remove Provider
- [ ] it removes that team's id from the `teamIds` array on the Provider doc. This means we could end up with many orphaned Provider docs that are like tombstones for abandoned account links. Good data to be had.

**Comment by mattkrick** [comment]
## Integrations

when you go to a specific Provider's page under integrations settings tab it
- [ ] opens a subscription for all the Integrations (eg channel, repos), both yours & your team mates
- [ ] invalidates all cached data (eg channelName) if the caller is the owner of the integration
- [ ] show every channel that start/end meeting notices are sent to

for every channel it
- [ ] shows the channel name
- [ ] has a `Remove` button
- [ ] has a `Refresh` button

when the user clicks the remove button it
- [ ] checks to see if any other users have that same integration
- [ ] if so, it safely removes that user's integration
- [ ] if not, it pops a specific warning modal saying exactly what will happen if the user removes the integration (no more slack messages, cards will get archived, etc.)

when the user clicks the refresh button it
- [ ] invalidates all cached data (channelName, list of channels, etc.) and pushes fresh stuff to the client. if this is clicked by someone who doesn't own the integration, the server will use another person's accessToken to fetch the data

**Comment by mattkrick** [comment]
## Questions

Currently, we invalidate the cache (eg channelName) when
- anyone clicks the refresh button
- the owner subscribes to the integration
Can we do without the 2nd? If everyone is connected to slack, that means it'll get invalidated every time & our server will have to call slack. that also means that the refresh button only serves a purpose for non-owners. @jordanh 

What should the schema for `SlackIntegration` look like?
Currently, we have `id, channelId, channelName, teamId`. We need a way to tie it to a user. We have 2 options:
- have a `userIds` indexed array field
- have 1 doc per user per integration
The first is nice because it's easy & concise. It's how the data will look on the front-end.
The 2nd is nice because it allows for user-specific stuff to be put on the integration. The question is-- will an integration ever be user specific? This will occur if we need an accessToken stored on the integration instead of just the Provider. If we build it out like this, we'll need an additional array of objects like `[{userId, accessToken}]` and then we just return 1 of them to the client. I kinda like this because then we don't have to worry about keeping cached data updated across multiple docs. Instead, we'll just have to update a sub-doc if user specifics change.

**Comment by mattkrick** [comment]
With the latest mockups we have a new field: `providerUserName` which is the username (like my name here on github) that is attached to the oauth token.

How should we invalidate that?
- Make them hit refresh token & we'll grab it again
- Add another refresh button (Gold star for UI right hurrr)
- Refresh it for every provider for every time they load the integrations page

**Comment by ackernaut** [comment]
@mattkrick Can we close this issue?

**Comment by mattkrick** [comment]
yessir!
