### ISSUE TITLE
Meeting summary not rendering to HTML

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1117]
## Issue - Bug

Here's a bug that slipped through the cracks: since shifting to our new draftjs editor the meeting summaries are not rendering to HTML4 any longer. See:

![image](https://user-images.githubusercontent.com/103000/27555506-c70d4d70-5a66-11e7-99cd-679746c18b3a.png)

This was reported by user/investor Larry Kraft.

- **OS:** OSX
- **Browser:** Chrome

**Comment by mattkrick** [comment]
it
- [ ] works on the webpage
- [ ] works in email
