### ISSUE TITLE
Enhance getCashaySchema.js to work on Windows

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1118]
## Issue - Bug

[Parabol Slack community](https://slackin.parabol.co) @nhannv reported that the following exception occurs on Windows:

```
` ERROR in ../~/cashay/lib/schema/cashay-loader.js!./server/utils/getCashaySchema.js
[0] Module build failed: Error: C:/Users/vnnguyen/Documents/My Web Sites/action/src/server/graphql/rootQuery.js: Cannot find module 'graphql' from 'C:\Users\vnnguyen\Documents\My Web Sites\action\src\server\graphql'
[0]     at Function.module.exports [as sync] (C:\Users\vnnguyen\Documents\My Web Sites\action\node_modules\resolve\lib\sync.js:40:15)
[0]     at resolveModuleSource (C:\Users\vnnguyen\Documents\My Web Sites\action\src\server\utils\getCashaySchema.js:18:20)
```

When he dug into it, it was because the module path resolver was not resolving from the relative directory `./src` but rather from the project root. He offered the following work around:

![image](https://user-images.githubusercontent.com/103000/27556271-c405f8f4-5a69-11e7-99e2-938faaf3a115.png)

I'm opening this issue to document this work-around for others who run into it, but we should make it official.

It should:

- [ ] use `babel-resolver`
- [ ] be tested to work on Linux, OSX, and Windows

- - -

- **OS:** OSX
- **Browser:** Chrome
- **Estimated effort:** 1 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
I've also added this Issue to our [Equity for Effort](https://github.com/ParabolInc/action/projects) program. If you, a community member, would like to bid and submit a PR for this Issue you may qualify for equity in [our company](https://parabol.co)

**Comment by mattkrick** [comment]
problem is here `'C:\Users\vnnguyen\Documents\My Web Sites\action\src\server\graphql'`. it should be pointing to node_modules instead of server.

i propose we flag this as `wont fix` and close. At 268 issues our backlog is already out of control. I'll never fix this & if a community member offers a fix, it won't provide us any value since we'll be moving to relay-modern in the next 6 months or so.

**Comment by jordanh** [comment]
Ok. Will close this one for now. If we see more Windows folks in our community and we're slow to switch over the relay fully, I'll reopen this.
