### ISSUE TITLE
"Pointer" Feature During Meetings

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#1123]
## Issue - Enhancement

While running teammates quickly through your personal Updates during a Check-In meeting, it would be swell if there was a visual indicator of which card the speaker was addressing. Similar to Trello: as the user moves mouse over the board, each card is highlighted light grey. We could do similar light [Parabol color] or a temporary halo border, etc.

**Comment by ackernaut** [comment]
This makes me think of cursors in Figma…

**Comment by jordanh** [comment]
Duplicate of #656
