### ISSUE TITLE
Team Integrations: Integration Details

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1126]
## Enhancement

This view allows users to see and update the settings for a single integration. They drill down to here from the Provider Details #1125 view.

- [ ] Decision: Users still see the Provider header component (icon, provider name, my connection)
- [ ] User sees an external link when applicable (to a repo, a channel, a board, a drive, etc.)
- [ ] Users can remove themselves from the integration
- [ ] Users and team leads can remove the integration for the team
- [ ] If the integration is being removed it needs to be confirmed. All cards will be archived in last state.
- [ ] If a team member leaves the team resulting in the integration being lost, the cards are archived and reassigned to the team lead.
- [ ] Sections with controls allow you to configure different aspects of the integration. Only team leads or integrated folks can edit these, otherwise the controls are read-only.
- [ ] Decision: Is there an initial state including controls for first time setup, or is this really a different view (New Integration View) per provider?

**Estimated effort**: 15 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Visual concepts**:

<img width="1280" alt="team-integration-github 2x" src="https://user-images.githubusercontent.com/307286/27649678-1616001e-5bf8-11e7-870f-c04cf609e459.png">
<img width="1280" alt="team-integration-slack 2x" src="https://user-images.githubusercontent.com/307286/27649677-16149a80-5bf8-11e7-9a12-0a987e2e9e35.png">

**Comment by jordanh** [comment]
I'm sure this will come back in the future. Iceboxing now per policy.
