### ISSUE TITLE
Team Integrations: New Integration Form/Wizard

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1127]
## Enhancement

Placeholder issue (TBD) for instances when adding an integration includes multiples steps like:

- Selecting what/how to sync
- Mapping columns/labels
- Mapping users

This is probably necessary for importing as proposed with the Tagging/Inbox epic. We shall see.

**Estimated effort**: 18 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Iceboxing
