### ISSUE TITLE
Viewport jumps when link created

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1130]
## Issue - Bug

I noticed this one when recording our new features movie. I didn't notice it before, but now I notice it every time.

When you highlight some text and press ⌘-k, the viewport will jump scroll and the scroll position will change as the portal animates in. Check it out:

![gif](http://g.recordit.co/T1uV3ctFre.gif)

It'd be nice if it didn't do this, as it degrades the experience.

- **OS:** OSX
- **Browser:** Chrome
- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
Interesting! I haven’t seen that yet, personally. Will look into it.

**Comment by mattkrick** [comment]
The gotcha is that the list of teams is longer than the viewport height. @ackernaut for the future version in Epic 8 we should make the sidebar scrollable like slack. let's not worry about it for this current version.

**Comment by ackernaut** [comment]
Ah, I see that now! Yeah, I’m ok waiting for that overhaul of the dashboard/team sheet layout (at least v1).

**Comment by jordanh** [comment]
I believe this is fixed now. Closing...
