### ISSUE TITLE
consider what to do about shouldValidate and handleSubmit

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#1132]
- our current `shouldValidate` logic is identical to the default except for the fact that we don't validate on the initial render.
- validation is NOT called during `handleSubmit`
- that means pristine forms will not get validated & will get submitted...without data!

options to take:
- validate on initialRender, which would mark the form as invalidate initially until stuff gets fixed
- validate inside handleSubmit & throw a SubmissionError

The first is good because it's less code.
The second is good because it's lazier. Plus, we already call the schema to normalize the values before they go to the server, so it's no extra work, just extra code.

i'd like to arrive at a solution that can be used everywhere

**Comment by jordanh** [comment]
Let's make a list of where else we'd want to consider applying this pattern

**Comment by mattkrick** [comment]
i think the right way to do this is to explicitly validate on submit, because that will give us normalized data too. This logic will have to be revisited as we move from cashay to relay, and we can fix both problems in 1 swoop.

**Comment by mattkrick** [comment]
i've moved away from using redux-form because we rarely have more than 1 or 2 inputs so it doesn't provide any value & overcomplicates a lot of stuff.
