### ISSUE TITLE
subscriptions: component based vs type based

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#1142]
The ProviderList component cares whether you add or remove a Provider. If you add one, it'll give you a new ProviderRow. If you remove one, it'll give you a new ProviderRow (with a null accessToken).

The SlackChannels component also cares whether you add or remove a Provider. If you add one, itll want a Provider. If you remove one, it'll want the ProviderId and a list of all slack channels to remove.

We could set up subscriptions in 2 ways:
- We could have a ProviderList subscription and a SlackChannels subscription. Each one would return what their respective fragments cares about.
- We could have an AddProvider and RemoveProvider subscription. Each would return a payload that is sufficient for either component.
- We could have a ProviderEvent subscription that would be the union of AddProvider and RemoveProvider.

I implemented the first option, but I'm not sure I love it. That's because if our components change, so must our subscriptions, meaning changes on the backend. that's not great.
The second option is similar to how mutations work. The RemoveProviderMutation wants to know about everything across the whole site that could change.
The third option would be very similar to the second option However, instead of managing 2 subscriptions, we'd only have to manage one. This comes at the expense of payload. We'd have to have an {add, remove} field where only 1 would be defined. the updater would look like (if add {AddMutation)...). Is that conditional worth the overhead of establishing a new subscription? I'm not sure i can definitively answer that, but i'll try.

- By having 1 larger sub (Add+Remove+Update) instead of 2+ smaller subs (Add, Remove, UpdateX, UpdateY) it means the websocket messages we send to subscribe go from N to 1.
- On the server, we'd only have to write 1 subscription instead of N. That means 1 less AsyncIterator, which is slightly more expensive than a listener. NBD.
- On that server subscription, it's possible that each Add/Remove/Update has different filtering & resolve logic. For example, we send the AddProvider back to the originating socket because it goes client->Slack->ActionServer->client push. Similarly, if a new subscription payload results in a new query, then we'll have a big switch/case in the subscription. In short, it means a larger/uglier resolve function.
- 1 larger sub also means a larger payload with N fields (with N-1 of them being undefined).
- on the client, we'll also need an ugly switch/case in the updater to interpret that larger payload.

So ideally, for things where we don't expect too much activity, we'd use 1 big one (fewer initial socket messages, less memory use on client + server)
For active subs, we'd want to break it out (smaller payload, simpler handlers)

I want to use the same strategy for the entire app, regardless of how often stuff is used. So, I'll say RAM is cheaper than headaches & go with the singular subscriptions.

**Comment by ackernaut** [comment]
That makes since to me. Optimize and modularize the subs that are very active. Take the easier to manage, but more expensive route, using larger subs that aren’t happening all the time.

**Comment by mattkrick** [comment]
now, we need to decide how full the subscription payload should be.
Currently, we have a subscription payload that matches the mutation payload.
This is nice because it's pretty simple, but it's also annoying because we'll need to subscribe to a lot more stuff & we may forget about some things.

for example, if we listen to slackChannelRemoved, we must also listen to providerRemoved since the latter event might contain slack channels that are removed. This could cause us to oversubscribe.

as an alternative, we could limit the providerRemoved subscription payload to only being about the provider. then, we could send 1 slackRemoved event for each deletedIntegrationId that would have been sent. 

another alternative would be to do both: send the full mutation payload and also trigger the slackChannelRemoved event multiple times. 

from a performance aspect, the first option is the best because it means fewer messages & fewer rerenders at the cost of larger payloads & more subscriptions. However, let's consider someone getting kicked out of an org. that user touches many team members and each team member could have many providers and each provider will affect all of the integrations. having only 1 message means every component needs to be subscribed to an orgKickout. alternatively, we could send 1 smaller orgKickout payload that handles the org stuff. many teamMember kickouts to handle team stuff. many provider removed events to handle provider stuff, many integration kickouts to handle integration stuff.

there are some cases where the subscription payload needs to be larger than the mutation payload.
for example, leaveIntegration. we do not need any reply from the server to know exactly how to handle it on the client. However, subscribers need to know the service, integrationId, and userId to remove. Similarly, joinIntegration only needs a User for the mutation, but for the subscription it needs a User, integrationId, and service. 

so, our options are:
- grow the mutation payload to match the subscription payload & essentially ignore it on the client.
- send a small payload for the mutation & a larger one for the subscription

then, for the subscriptions we can: 
- create a subscription payload for both join & leave, resulting in 2 more subs to watch
- combine the 2 and have an `updatedGitHubIntegrationPayload` that returns only a GitHubIntegration that will replace the old one. Then, if eg leaveIntegration results in removing that whole integration, we just send a removeRepo event instead.

**Comment by ackernaut** [comment]
@mattkrick is there any way to help with this using UI? do we inform users when they are making big, sweeping changes and show proper states/progress “Doing some housecleaning…”? Or is most of the burden on unseen performance?

**Comment by mattkrick** [comment]
if it's done right, it's all unseen & it just works. the biggest mutation out there will probably be removing someone from your org & that would only take < 1 second and it'll seem instance since we'll handle it optimistically. It's kinda a multivariate optimization-- we wanna maximize performance but minimize surface area for bugs. for example, when building the github integration component, it seems error-prone that i'd have to pay attention to org members getting kicked out, but a removed org member means removed team member means removed provider means updated and/or removed integrations. (this is in the future, when everything is evented instead of livequery).

To reduce the complexity we have options:
- reduce the subscription payload to only one entity & send multiple payloads. for example, if i delete an org member, i would send removeOrgMember, then removeTeamMember1...n, then removeProvider1...n, then removeIntegration1...m, etc. 
  *Pro*: very logical
  *Con*: Poor performance. sending 20 websocket messages in quick succession will mean we update the store & attempt to rerender 20 times. that'll cause the UI to lock up like it does now with the archived projects.
  *Con*: we need separate payloads & handlers for mutations & subscriptions.
- reduce the mutation & subscription payload to only one entity & send multiple payload.
  *Pro*: very logical
  *Con*: Poor performance
- send a single subscription payload just large enough to handle all necessary store changes
  - *Pro*: great performance
  - *Con*: we need separate payloads & handlers for mutations & subscriptions.
  - *Con*: Each component needs to be aware of EVERY subscription that could affect it
- send a single subscription payload where `MutationPayload == SubscriptionPayload == Union(MutationRequirements, SubscriptionRequirements)`
  - *Pro*: good performance
  - *Con*: Each component needs to be aware of EVERY subscription that could affect it 

So, if we want a minimum of good performance, we need to choose option 3 or 4. We can always add more servers, but we can't give every client a faster CPU, so 1 & 2 are out. The performance delta between 3 & 4 is mostly on the server, as homogenizing the payloads between mutations & subscriptions means the mutation will need to send redundant data to the client that triggered the mutation. That's the price we pay for reducing the number of different types of payloads we send. I think that's a fair trade because fewer handlers means simpler code, less mental overhead, fewer bugs.

Now, we need to mitigate the con of making every component aware of every subscription. 
As much as I dislike inheritance, i think it'd be really helpful in this case if child subscriptions inherited the subs from their parents. for example, `SlackChannelRemoved` subscription would automatically trigger `ProviderRemoved` which would trigger `TeamMemberRemoved` which would trigger `OrgMemberRemoved`. That way, as the app grows, we don't need to go through every component to see if it needs the new sub. This is also a huge burst of outgoing socket messages (sub1..n). If we want to decrease the amount of subscription messages sent at once, we could write a buffer into our network layer that waits eg 20ms and then subscribes to multiple subs in 1 single message. Since the message doesn't have a response, i don't see that being a bottleneck for now.

**Comment by ackernaut** [comment]
What you describe here seems to make sense to me…obviously you’ve put a great deal of thought into it. As for that last paragraph, it sounds like we can buffer inherited subscriptions because a person is probably not just jumping around willy, nilly through the app or did I misunderstand?

**Comment by mattkrick** [comment]
ok, this strategy kinda falls apart for some more advanced mutations. for example, take `inviteTeamMembers`. User A sends in a list of invitees & gets back that same list with the result. 

Everyone else on the team should also be able to subscribe to those changes so they can see the invitees list update in realtime, so the `teamMembersInvited.${teamId}` subscription should share the same payload. Note that the same payload should be handled differently on the client. For reactivations, the inviter should get something like "Joe has been automatically reactivated because he was previously on the team" while the team members should just get "Joe is back!".

In addition to that payload, we need to send a REQUEST_NEW_USER notification to all the org billing leaders. they may not even be on the team, so adding it to the `inviteTeamMembersPayload` and making each billing leader subscribe to invites from all the teams they own seems like overkill. 

Finally, if a user is being reactivated, then that triggers a notification including a new authToken to that user. That needs a payload all to itself. 

so, the new strategy is to minimize the # of payloads sent. Another payload is OK if the following criteria is true:
- the payload in question is not a subset of the original payload AND
- the audience for the payload in question is distinct from the original audience

Since org billing leaders want a notification that no one else will get AND they are not the original audience for `inviteTeamMembers`, they get their own payload.

Since a reactivated user wants an authToken that no one else will get AND they are not the original audience, they get their own payload.

Since a reactivated member will trigger a toast for all team members can be derived from the original payload AND the team is the original audience, they must share the original payload (this means REJOIN_TEAM can go away since it's a subset).

**Comment by mattkrick** [comment]
> We could have a ProviderEvent subscription that would be the union of AddProvider and RemoveProvider.

revisiting this train of thought as it might still prove useful for simple things like AgendaItems. If i subscribe to AGENDA_ITEMS.teamId, i care about created, updated, and deleted agenda items.a payload would always have 2 fields: type, fields. if the type is delete, then the only field will be id. This feels really familiar because that's the protocol we use today with changefeeds. For complicated usecases like addProvider, it doesn't work, but it could at the expense of 1 extra round trip. For everything else, I think it works beautifully at the expense of a subscription payload that differs from the mutation payload.

**Comment by mattkrick** [comment]
Relay does a little something magical, which isn't always desired.
Say i have {id: 1, name: 'matt', fruit: 'peach'} in the cache.
Now say there is a mutation to change my name & another one to change my fruit.
So that means i need 2 subscriptions, 1 for changing the name, and 1 for changing the fruit.
This is because if a subscription asks for {id, name, fruit} and i don't return name, then GraphQL fills it in with `null` and relay does a replace, not a merge.
To avoid this, we could do 3 things:
- use 2 subscriptions. Bleh, this gets bloated fast
- create a distinct `NameChangePayload`, `FruitChangePayload` and write a subscription like:
```
{
  id
  ... on NameChangePayload {
    name
  }
  on FruitChangePayload {
    fruit
  }
}
```
again, this just bloats the server with implementation details
- write a custom mergeHandler that runs on updates and call it with:
```
me @__clientField(handle: "merge") {
  type
  person {
    id
    name
    fruit
  }
}
```
this is getting better, but there is still a problem because Relay creates that partial document before the mergeHandler can touch it. So, there is a (albeit very minimal) runtime cost. I still think it's preferable because the runtime cost is likely equal to the extra parsing of a larger obect (not to mention it'll be easier on our server)

now the question exists what to do if the type is DELETE. sending in `person { id}` isn't ideal because relay will then update the person with null fields & then we'll have to delete it ourselves. Again, not a huge deal, but it's something.

Some alternatives:
- change the id to something like `1::update` or `1::delete` so when relay tries to be magical, it can't find the existing doc.
- add a `deletedId` field and don't pass in the `person` field for deleted things.

yay weekend thoughts!
