### ISSUE TITLE
Ability to add links to seed project cards

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1144]
## Issue - Enhancement

Currently folks who sign up and create a team get a set of seed cards (first tasks to do in order to get a tour of Parabol). Currently they have to find the UI per card instructions. Although it might be helpful for folks to have to find where settings etc. are (which should be changing a bit in the future), perhaps its better to give them direct links? This requires that we at least have the team id in order to create the link for them (`/team/[id]/settings/`).

**Estimated effort**: 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Still a thing. Likely will be gated behind switching editors. Icebox per policy for now.
