### ISSUE TITLE
Empty state for menus

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1145]
## Enhancement

In the cases where a menu may be open but no longer has valid options (when the realtime app is updating on the fly)…we may need a default empty menu state that can be contextual when we know what is going on in the app. For example, we could update the text to be more specific to the user’s context:

![empty menu panel demo](https://user-images.githubusercontent.com/307286/28291220-2ad51f1e-6b0f-11e7-9031-324c359aec61.png)

**Estimated effort**: 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Iceboxing for now
