### ISSUE TITLE
Autosuggest input + dropdown

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1146]
## Enhancement

There may be cases where a text input with autosuggest and a dropdown may be helpful. If users know what they are looking for they can just begin to type and make a selection from a menu that appears. Otherwise, they can tap a dropdown icon and scroll through options and make a selection.

I’m not sure if a global component makes these most sense as this may be a mashup that is used in various contexts. I would think that it simply needs some options for presentation then a list of items to choose from (or type to autosuggest).

**Estimated effort**: 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Iceboxing for now
