### ISSUE TITLE
Join/Leave Integration

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#1147]
When a github repo is added, it should
- [x] first check to see if the repo previously existed & was just inactivated. that way we can reactivate cards later on
- [x] add you to the list of users
- [x] check the rest of the providers on the team & add them

when a github repo is removed it should
- [x] reset the list of userIds
- [x] set isActive to false

when you leave an integration it should
- [x] remove you from the userId array
- [x] if you're the last one, then it should remove the integration

when you join an integration it should
- [x] add you to the userId array

when you create a new github provider it should
- [x] get a list of all the integrations & attempt to assign you to all of them, if you have privileges

when you remove a github provider it should
- [x] remove that teamId from the provider doc
- [x] grab all the integrations where you were the only member & remove them

when you join a team it should
- [x] do nothing because we can't assume the Provider

when you leave a team it should
- [x] act the same as removing the Provider

things to consider:
- should we change teamIds on Provider to teamId? A token-per-team strategy isn't terrible, and at least GitHub makes authorization 0 clicks if you're logged in, so it can be faster than asking if they'd like to use the same token as another team
- get rid of the blackList on the integration? I think we don't need it now
- how should we structure integration updates? Should join/leave integration have their own distinct payloads? If so, that means less data, but more subscriptions to keep track of. for a subscription on the teamId, we would need to know the service (github), the integrationId, and the userId to remove. alternatively, we could just refetch the GitHubIntegration & send that down the pipe. the latter is more expensive, but simpler. i'll start there & if it ever becomes a bottleneck we can improve.

**Comment by ackernaut** [comment]
This is good stuff, @mattkrick!

What was the `blackList` that you mentioned?

**Comment by mattkrick** [comment]
oh just an old artifact, cant even remember why it was necessary
