### ISSUE TITLE
Import from providers, integration

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1149]
## Enhancement

When trying Parabol, users want to import from existing tools, to see if they can exclusively use Parabol.

How can we call out the action of integrating with an existing tool with the desire to import? For folks making a switch, they may not want to sync, just import once. Perhaps they start with a sync, and then when they’re wanting to drop the other tool, they turn off the sync in order to only use Parabol?

This is a meta issue of sorts as we would have to make sure the underlying provider and integration system can handle various tools: Trello, Asana (any more providers that would represent segments who might be willing to switch to us?)

This has UI/UX implications involving inbox, tagging, snoozing.
This also has implications with syncing #1150 

Our provider/integration system can:

- [ ] handle an import of tasks, subtasks from Asana (by project?)
- [ ] handle an import of cards from Trello (by board, list)

**Estimated effort**: 30 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
@mattkrick Here’s the use case for justifying turning off a sync that we discussed.

**Comment by sarakhatri** [comment]
Trello one-time import survey results: https://docs.google.com/a/parabol.co/document/d/1jgePWRlFPm7qxeDaE_TKRcZd8QbsYd0kscKfs-XjUdo/edit?usp=sharing

**Comment by jordanh** [comment]
Iceboxing for now (this is a big issue!)
