### ISSUE TITLE
Revise server/webpack strategy: move to koa2

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#115]
## Issue - Enhancement

There are a few things are aren't critical yet, but would be nice to have
- [ ] Put the entire server in webpack. See https://medium.com/@sidjain/kickback-with-koa-webpack-a51d7e5d7911#.newrnd3sf. This will allow us to do a few cool things:
  - [ ] HMR the server (goodbye server restarts)
  - [ ] Do away with commonjs transpiling (hello tree-shaking!)
  - [ ] remove the funky `routesOrPrerender` hack that we do
- [ ] Move to Koa2, which is designed for await/async (no more error swallowing!) so we can write more expressive code
- **Estimated effort:** 10 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
a good place to start: https://github.com/ctrlplusb/react-universally

**Comment by jordanh** [comment]
This would be a super-fun, and super-valuable [Equity for Effort](https://medium.com/parabol-focus/equity-for-effort-an-experiment-e45f5ae40d3a) project for a community member to tackle. Any takers out there?
