### ISSUE TITLE
Syncing with providers, high-level list

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1150]
## Enhancement

When using Parabol’s Action Meeting, users want to sync with existing tools, so that they can create tasks/issues/cards (whatever the object is named in the provider’s system) in the tools they like.

These users may find value in the meeting feature but want to feed existing tools that different folks like to use.

This is a larger issue that can be represented by smaller issues. We’re already building for GitHub.

Our provider/integration system can:

- [ ] Sync issues with GitHub repositories (mapping labels, users, etc.)
- [ ] Sync cards with Trello boards (mapping lists, labels, users, etc.)
- [ ] Sync tasks and subtasks with Asana projects (mapping users, other meta, etc.)

Any more providers that we want to focus on where two-way syncing may make sense? We can have a unique issue for each once as it makes sense.

This has UI/UX implications for tagging and inbox.

This has design implications with #1149 “Import from providers, integration”

**Estimated effort**: 30 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Iceboxing for now
