### ISSUE TITLE
Messages (error, success, etc.) for card UI

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1153]
## Enhancement

**JTBD**: When there is a helpful message that needs to be displayed in the context of a card (why there is a problem, success feedback, etc.) users want clear UI so that they can understand quickly and take any necessary steps or continue using the software.

There’s the attempt at framing this is a JBTD…basically we are thinking of adding a prepended or appended message panel at the top or bottom of a card that either goes away on a timer or can be cleared. We may find some use cases for presenting flat buttons that give optional actions the user can take.

**Estimated effort**: 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
Here’s a first-pass concept:

At first I was thinking that the appended message floated off of the end of the card (not changing the layout of what’s beneath it). But now I’m thinking it could slide down to view and up to go away, pushing whatever is beneath it. Maybe that could be an option too. After trying it out we could polish the look based on context.

![image](https://user-images.githubusercontent.com/307286/28483479-188110da-6e33-11e7-8f05-f8a6d66cb197.png)

**Comment by ackernaut** [comment]
@mattkrick anywhere in the ballpark of what you had in mind? (I left comments in Figma, too, but basically the same thing.)

**Comment by mattkrick** [comment]
yeah, i dig it! I could totally imagine a little thing sliding down from the bottom like it's coming out from under the card. I can't think of a success/neutral use case, but it's good to have those if they need arises.
Maybe the message constructor takes in a timeout that will auto-expire the error after that much time, otherwise it'll be there until you hit clear?

**Comment by ackernaut** [comment]
Yeah I think the timeout makes sense. I can begin adding this panel (Mon?) to the card component and we can improve it as we go. Unless you are eager to get to it.
