### ISSUE TITLE
Delete first agenda item

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1157]
## Issue - Enhancement

When I added a single agenda item I no longer care for (or made a typo entering), I would like to delete it, so that I don't have to process it.

- **Estimated effort:** 15 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
You are unable to delete any agenda items?

**Comment by ackernaut** [comment]
Ah I see, you are unable to delete the first agenda item in the meeting views…but you probably could delete it in the team dash.

I think there is definitely a regression as we fixed this too.

We also had a regression on dashboard nav for the team you were actively on.

@mattkrick

**Comment by mattkrick** [comment]
should you be able to delete it when it's active?

**Comment by ackernaut** [comment]
So I think the rules were fine (active cannot be deleted)…but the regression is that the first item is stuck (cannot delete) in the lobby/updates whereas it can be deleted from the team dash.
