### ISSUE TITLE
Tethering bug at end of meeting

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#1163]
## Issue - Bug

- **OS:** Mac
- **Browser:** Chrome
- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

During user research onboarding:
 * User & Facilitator were tethered correctly throughout meeting until
 * User clicked back to previous Agenda item and Facilitator clicked forward to "Wrap Up” screen
 * User couldn’t tether back to Facilitator (no "Rejoin Facilitator" button visible) until both clicked back to the Agenda first

**Comment by jordanh** [comment]
Let's look out for more instances of this and how to reproduce it

**Comment by jordanh** [comment]
I think we must have fixed this one along the way. Closing for now.
