### ISSUE TITLE
Remove “Here/Not Here” from non-facilitator view

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#1164]
## Issue - Enhancement

Frequent observation of confusion, uncertainty, and/or unintended user behaviors during Check-In round of Meetings, related to the "Here/Not Here" buttons.

Access to participation in this part of Check-in seems to have a greater negative impact on clarity of use, that outweighs any positive aspects of autonomy and equal participation. 

Recommendation: remove "Here/Not Here" from the view of any teammates that are not the Facilitator.

**Comment by jordanh** [comment]
Might need instructions for non-facilitators on what to do, lest they get frustrated

**Comment by tayamueller** [comment]
How about italic hot pink "Waiting for [teammate] to share." Similar to "Waiting for Facilitator to end meeting" in other places where User/Facilitaotgr views differ.

**Comment by ackernaut** [comment]
My thoughts:

If the meeting progress is not greater than Check-In, we show the “Waiting” message, and disable the click on top-right avatars (for non-facilitators)? Then if meeting progress is greater than Check-In, there is a simple “Next” link and avatars are clickable (so those that click around do not get stuck)?

**Comment by ackernaut** [comment]
A little hesitant to try and knock this out without more thought on the UX.
