### ISSUE TITLE
"Enter" to activate hashtags

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#1165]
## Issue - Enhancement

Repeat observations of user trying to hit "enter" to activate hashtags.

We currently require users to stop typing, and use their mouse to click-select the desired hashtag label

Recommendation: as a user types #...etc, the list of recommended hashtags should follow their typing, similar to typing in a search bar (or typing #xxx in GitHub :) IE: 
 * As a user begins by typing "#..." a pop-up menu of 5 recently used hashtags pops up, with the first highlighted
 * As the user expands to "#m..." the pop-up menu changes to 5 "#m" options (#marketing, #music, #munchies, etc), with the first highlighted
 * As the user expands to "ma..." the pop-up menu changes to 5 "#ma" options (#marketing, #math, #Mary, etc), with the first highlighted 
 * When the user finishes typing, OR when the desired hashtag is visible as the top hihghlighted pop-up option, hitting "enter" should activate the link

This better mimics natural use and other familiar interfaces so it should improve user speed. Will also be helpful for tagging projects in the future.

**Comment by jordanh** [comment]
Can you try tab completion? Or, hitting the arrows up or down and then pressing enter?
