### ISSUE TITLE
Multilingual Experience

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#1166]
## Issue - Enhancement

Many of our users are/will be international, domestic with international contacts, and otherwise multilingual.

How might we incorporate existing technologies to make the Parabol experience available to and seamless for multilingual teams? (Trello already has plug-ins to facilitate this.)

Scenario: a Japanese teammate types and functions inside of Parabol exclusively in kanji/kana, while her English-speaking teammates view her cards and communicate back in English. Users might switch languages* at will in their Settings.

*yes, one of the languages should be [Pirate](https://searchenginewatch.com/sew/how-to/2109984/avast-ye-talk-scurvy-pirate-wit-facebook-twitter-google)

**Comment by jordanh** [comment]
This issue also needs acceptance criteria. It looks like a design issue first, as this could get big fast. Is there a subset of our entire experience we might try to localize first? Is the localization team-wide (my team is in Spanish) or person-side (Parabol is in Spanish for me)? Do meeting prompts also get translated? Or only things like "User is editing..." and "new Task..."?

**Comment by tayamueller** [comment]
from a partner/Pro user on 5.23: 

> These pals are hooked. The CEO said "Where has this been all my life". Actually, she said ""Donde ha estado esto toda mi vida" Any idea on timeframe?

**Comment by jordanh** [comment]
Not likely to get here before Series A (18-24 months). Iceboxing for now
