### ISSUE TITLE
Export projects

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1168]
## Enhancement

When closing a team…
When using another service for some reason…

…I want the ability to export project content…
…so that I can archive it or do something with it in another software that Parabol doesn’t integrate with.

- What can we learn about why folks are closing teams? Motivations?
- What can we learn about folks wanting to export? To what systems? For what outcome?

**Estimated effort**: 18 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Iceboxing this one. Needs need to be refined.
