### ISSUE TITLE
Integrate with Figma

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1169]
## Enhancement

When working on objectives and outcomes that involve visual design on a multidisciplinary team, team leads want to integrate with Figma, so that they can add a layer of clarity and prioritization to the effort and conversation, while maintaining helpful syncs to files and conversations (comments) for product owners, designers, developers who are implementing etc.

Ideas:

- Users can easily link a Parabol card to a Figma file
- Users can easily find links to clickable prototypes and presentation mode on the card
- Users can see activity in Figma represented on the card (comments, contributors)
- Figma users can generate Parabol agenda items from within comments in Figma

**Estimated effort**: 30 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
I know we’re not there yet, but I’m thinking Figma would be willing to talk with us about integration possibilities in the future. See the last section of this writeup: [Figma 2.0](https://blog.figma.com/figma-2-0-now-with-prototyping-and-developer-handoff-1b309a5d025c)

**Comment by mattkrick** [comment]
i really like this. if there is any signal at all from designers, i think that we could really help each other out.

**Comment by jordanh** [comment]
Iceboxing for now
