### ISSUE TITLE
Async Component Pattern w/o router

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#1171]
I'd like to establish a pattern for async components w/o using routes. For example, I shouldn't have to load the `GitHubIntegrationMenu` logic before the user clicks (or hovers over) the github button on the project card footer. 

Ideally the pattern is:
- Hover the button to load the module
- Click the button to open a menu
- If the module is still being fetched, the menu opens to a specified size with a loading icon & proper css in it
- The module loads & triggers a fetch for the query (in this case, the list of integrated GitHub repos)
- While that list is being fetched, we show a menu that matches the previous one
- When it comes back, the list is shown in the menu.

I think we can get close by doing something like:
- Async Menu component that houses the button as a trigger
- The menu takes in promise to fetch a Root component (one that has QueryRenderer in it)
- When the trigger is hovered, we prefetch that Root component module
- The Async Menu component shows loading while that module is being fetched
- After the module is fetched, mounting it will trigger the query for the repo list
- While that's loading, the async menu component will go back to loading. We can accomplish the identical one by having `loading` be state on the async menu & setLoading belong to the QueryRenderer
- when the list comes, we populate.

**Comment by ackernaut** [comment]
Sounds good to me…let me know how/when I can help with styling the component states.
