### ISSUE TITLE
Click on faces filter cards

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1172]
## Issue - Enhancement

During a user test, we asked the user to filter the board by user. They tried to click on the avatar above the dashboard. If we preserve the avatars on the dashboard in our next design:

When a user wants to filter a board, they want to click on a face to add to the existing filter, so that they can view cards involved with that user

When a user wants to remove a user from an active filter, they want to either remove that filter manually or click the avatar face to toggle it from the active filter, so that they can get a wider view

- **Estimated effort:** 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
That makes a lot of sense—what I think we may end up having is a section on the initial view of the team sheet that shows team members by avatar group. Perhaps when/if a team member is tapped we give them a little menu:

- See Terry’s projects for this team (filters the dashboard by Terry, by {team})
- See Terry’s roles for this team (maybe goes to a Terry profile/sub-view? very future)
- Manage Terry on this team (team settings? Terry profile/sub-view?)

If we started with just the first item (filter dash by team member, by team) then perhaps we don’t have a menu, just a tooltip and a tap?

**Comment by jordanh** [comment]
Iceboxing for now
