### ISSUE TITLE
Creating a GH issue

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#1174]
https://developer.github.com/v3/issues/#create-an-issue

To create an issue, we need the following:
- Title: The first X chars of the first block of Project.content. We could try putting the entire body in here & letting GH break it apart.
- Body: We can only _send_ a string, but we can retrieve HTML. Maybe not even a markdown string. we should test & find out. Since we can't send HTML, that means we'll lose data if we pull direct from GH. So, we should preserve fidelity by keeping the content stored in Parabol. The problem is how do we update edits. 
  - Diff: we can do this by memoizing on the old GH body. So, when we create an issue on parabol, we store content and content_GH. then, we receive newContent_GH. we compare this to content_GH & minimize the damage that will surely come. 
  - Full replace. Take what comes from GH & replace what we had in parabol. This is cheap & easy, but could make folks angry.
  - No replace. Instead of replacing our beautiful content with bastardized (albeit up-to-date) content, we could just put a warning label at the bottom saying "This has been updated! Goto GH to see"
- Assignees: we look up the teamMemberId, convert it to their GH ID. if none is found, we throw an error. if they don't have access to the repo, we throw an error.
- Milestone: Don't use for v1
- labels: couple options:
  - don't push labels for v1
  - push all labels from parabol, including private & archived.
  - push non-parabol-specific labels
  If we wanna push labels, we're gonna have to first add the ability to add labels to projects. This means:
  - Add the ability to add custom labels
  - Autosuggest labels that already exist in all the repos

@jordanh @ackernaut: for body & labels, what is your preference?

**Comment by jordanh** [comment]
I think on this first pass, we do cheap and easy all the way. Learn and enhance. My vote is:

* cheap-ass replacement of plaintext. if folks complain, we celebrate as signal they want the feature
* labels: don't push labels for v1 – let's handle label mapping after we hit up tagging and labels in our own software

Safe to try?

**Comment by mattkrick** [comment]
sounds easy enough!

**Comment by mattkrick** [comment]
on the backend, we're gonna have to create some mappers (labels, users, etc). These mappers are gonna be specific to a repo, because some folks may not wanna be associated with a repo, or in the future folks can use different accounts on a per-repo basis instead of per-team.

However, right now all we have to do is the username mapper.
We can populate that automatically when a repo is added by doing the following:
- looking for the username on the Provider, stored next to their token
- looking for the username on another GitHubIntegration for the same team
- looking them up when addRepo gets called

The 2nd option is important because we want to allow folks to be linked even if they aren't integrated.

**Comment by ackernaut** [comment]
Yeah, +1 for simple content syncing and skipping labels for the first pass.

**Comment by mattkrick** [comment]
i don't think the repo is where we should store the human resource mapper. all this mapper does is connect the github username to the parabol userId. we got choices:
- store the human resource mapper on the team. 
- store the human resource mapper on the org.

if we store it on the team, then that's less setup & fewer errors when you add a new repo. however, if you mention someone in the GH issue, it's possible that person is in your org, but not on your team. it'd still be useful to grab this information so we could intelligently say, "hey, this person gets mentioned a lot. maybe invite them to the team?" I really like that since it gives us insight into how the org operates.

if we store it on the org we get that ability, but then we have an edge case of 1 parabol user having multiple GH accounts. for example, i've got my matt_product and matt_exec GH accounts for my respective teams. if someone mentions me in parabol, it doesn't know who to notify on GH.

that means we can either store it on the org & keep a blacklist/whitelist of teamIds, or we can create a replica per team. & just choose one & let them alter it if needed. if it's stored on the org, then 1 person can bork stuff for the whole org, so that's no good. also, since it will appear in the team integration settings, there's a nice benefit to having the data look like the UI. 

@ackernaut if we make the human resource mapper team specific instead of repo specific, should we move it from the repo settings to a block below the list of repos? something else?

**Comment by jordanh** [comment]
From an IA standpoint, I think we should keep it the username mapping on the team. If an org user isn't on the team and they are mentioned in the GitHub repository, I think we should ignore it.

(as a starting point)

**Comment by ackernaut** [comment]
This sounds like a reasonable approach. @mattkrick yeah I could see us trying a “User Mapping” panel below the panel where repos are added and listed.

**Comment by mattkrick** [comment]
if we _Really_ wanted to simplify this, we could completely remove the mapper & just make folks integrate with github. if they don't integrate their account with each team, then the mentions don't work.
this works because when you authorize github for a team, it links your github account to an auth token.

the downsides are:
- no cross-team mentions ( @jordanh already ruled this out of scope, plus we could still accomplish this with a slightly more expensive query as long as the are integrated on GH in at least 1 team in the org)
- mentions won't work for folks that aren't integrated (this is probably fine, if you aren't integrated, you probably don't care)

you guys see any other downsides? think it's a fair tradeoff? I kinda like this option because if we can make the setup that much simpler, then it's less stuff that can get screwed up.

**Comment by ackernaut** [comment]
**Question**: To whom, ha, can we assign GH integrated cards?

I'm ok starting that simple and seeing how it works with users. I think we may need to actually reach out and ask integrated teams (GH) what is good, bad and ugly once they use it.

Leading me to my next thought: What metrics do we add to start gauging integration usage to inform what we build next, how deeply do we integrate, etc? (gonna start a discussion issue)

**Comment by mattkrick** [comment]
anyone who has linked their GH account to their parabol team can get a GH card assigned to them. 
i agree with starting simple, but if we know we will eventually want more, then it'll be 10x cheaper to build it that way now vs migrating + rewriting later.

**Comment by ackernaut** [comment]
@mattkrick was this essentially a discussion? Safe to close?

**Comment by mattkrick** [comment]
yup, just scopin er out.
