### ISSUE TITLE
When text is highlighted and link is made, focus on url field not label

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1175]
## Issue - Enhancement

Trivial enhancement. To be more in line with GDocs interaction. When a user highlights text in a draftjs editor and hitts command-k, focus the url field (not the link text) so that the user can paste a link without having to hit tab first.

- **Estimated effort:** 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
This could make a real nice intern BP

**Comment by ackernaut** [comment]
+1 for enhancement and ENG BP

**Comment by colinmatthews** [comment]
Forgot to bid on this.. 11 points seems good!
