### ISSUE TITLE
Ensure that `teamId` and `orgId` are populated on most page load events

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1177]
## Issue - Bug

After auditing the segment events this morning, I see that `teamId` is on most page events (if its available from the url). `orgId` is only sent if somebody accesses `/me/organizations/:orgId`. Looking at the code, this is how we've designed it.

I'd like to change this, like so:

   * When a `teamId` is extracted from the url, also look up the `orgId` and send it along with the page load event

...this will make our weekly active org's metric meaningful.

**Comment by mattkrick** [comment]
an alternative:
- instead of sending events straight from the client, send them to our server first, then send them to segment. that way we can populate all the info we want (including team name, org name, person's name, etc.) _and_ we avoid adblockers, so our data capture rate is 100% instead of just a sample. probably not necessary for page change events, but for the big events, we'll wanna capture as many of those as we can & make sure they contain all the metadata they can.

**Comment by jordanh** [comment]
True dat. I like this approach. Design a little `pageEvent` mutation?

**Comment by mattkrick** [comment]
yeah, that'd be really clean. The only downside is that a mutation will want a response from the server. so our options are: 
- treat it as a mutation, receive a boolean payload from the server & just ignore it
- set up a segment endpoint & call that. internally, it could still use graphql, but then we dont need to reply.
- tell our network layer to sniff for pageEvent and if it gets it, resolves the promise with a bool. then, send it off. on the server, sniff for pageEvent & don't reply if found.

**Comment by ackernaut** [comment]
I like what I’m seeing here!

**Comment by mattkrick** [comment]
hey @jordanh 
what's the shape of the object you wanna send to segment?
most of the time, teamId is a peer to userId.
For endMeeting though, it's a peer but also lives under properties:
https://github.com/ParabolInc/action/blob/master/src/server/graphql/models/Team/endMeeting/endMeeting.js#L108-L117

Is this required? I feel like we only need it once, but if we need it twice here, I'd like to put it in both places everywhere.

Also, same question with orgId.

**Comment by mattkrick** [comment]
hey @jordanh i see we're tracking stripe errors with segment. why use segment over sentry? feels like we should be calling raven instead of segment...
