### ISSUE TITLE
card footer buttons only visible on focus, not menu open

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#1179]
repro:
1. click on the status menu button in the card footer
2. hit tab
3. notice that the button that opened the menu is no longer visible, but the menu is open.

ways to fix this:
- always show buttons
- add an `onOpen` callback to react-portal-hoc
- forego the toggle & manage isOpen explicitly for the portal
- listen for a click on the button, also listen for a click on closePortal

overall, not a huge deal. we'll probably deprecate react-portal-hoc soon now that react v16 has portals natively so i think we can wait until we switch & change our portal strategy.

**Comment by ackernaut** [comment]
I’m glad you captured this one! Definitely wanting to get these nuances right. I’ll add to 6.5 for now.

**Comment by ackernaut** [comment]
See #1199 and #1198
