### ISSUE TITLE
make boundedModal handle right & bottom

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#1180]
right now, the async menu component requires a maxHeight param. The only reason it needs this is because internally, it feeds boundedModal which only supports `left, top` calculations. we should additionally support `right, bottom` calcs, too.
This has the following benefits:
- for menus where you don't know the height, you don't have to guess
- when the data comes back, the menu won't flash in the wrong location if the anchor is anything but `left, top`.
- you can use rem instead of pixels for the width.

**Comment by ackernaut** [comment]
👍 👍

**Comment by mattkrick** [comment]
_kinda_ fixed.
we still need a max height for guessing until data comes in the case of the anchor being in the center of the target. that's because center = height / 2. still, not the end of the world.

because of that, we still need pixels. however, i noticed that our app doesn't obey the base browser font size, which means 16px == 1 rem ALWAYS. that makes it easy.

the big importance is that when the data comes in, the menu in anchored correctly so it just shrink to the left & then teleport to the right real fast, which was ugly.
