### ISSUE TITLE
boxshadow for focused cards

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#1181]
hey @ackernaut i noticed that when a card is focused, the box shadow goes to level 2.
level 2 is also what the menu is set at.
that means when i click eg status menu on a focused card, i have a level 2 _on top_ of a level 2. that feels funny.
should we promote 1 or demote the other?

**Comment by ackernaut** [comment]
Yeah, I think we promote the modal up 1 level, but I’ll take a look at it.
