### ISSUE TITLE
Pricing!

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1183]
## Issue - Enhancement

Two bits of work to clear up here:

- When I am browsing Parabol's website and thinking about adopting it with my team, I want a transparent pricing page, so that I can know if its feasible for me to adopt

- When a team leader's trial ends and we pop them a modal to input payment information, they want to be reminded how our software is priced and how much they can expect to pay, so that they feel comfortable giving us their payment info and resume using the software

**Comment by ackernaut** [comment]
+1

**Comment by mattkrick** [comment]
Assigning to @ackernaut cause this sounds like a healthy amount of squarespace stuff

**Comment by ackernaut** [comment]
@jordanh I’m moving forward on design here, as our current model will not change until the [Freemium Epic](https://github.com/ParabolInc/action/milestone/24). I’ll share designs internally before implementing.

**Comment by jordanh** [comment]
Sounds great!
