### ISSUE TITLE
Fix avatar spacing on GitHub integration

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1187]
## Issue - Bug

![image](https://user-images.githubusercontent.com/103000/28882997-c93101a6-7761-11e7-9885-707410fb082e.png)

- **OS:** OSX
- **Browser:** Chrome
- **Estimated effort:** 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
@ackernaut now we've got:

![image](https://user-images.githubusercontent.com/103000/28886005-bef9616e-776c-11e7-93e1-d14e1150e1bf.png)

🙃

**Comment by mattkrick** [comment]
FWIW github actually does this _really_ well with the collapse & expand stuff. go to your github notifications & you'll see for issues with 2+ people is makes it pretty nice.
