### ISSUE TITLE
GitHub integration, list a user's repositories

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1191]
## Issue - Enhancement

For fun, I pushed a commit to https://github.com/jordanh/ffmpeg2gif to see if that repo would show up on my team, it looks like for now that our GitHub integration will only list repositories nested under an organization.

Is it difficult to list an individuals repositories as well?

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
flagging as a bug because i tested this & it worked for me!

Easy: wait 30 seconds & try again. Currently I only hit GH once every 30 seconds.

If that doesn't work, hit refresh & see if it's there

If that doesn't work, go to AddGitHubRepo and find the line
`const oneMonthAgo = Date.now() - ms('30d');`.
and change that `30d` to something like `30y`. and see if it shows up.

if that doesn't work shoot me your GH oauth accessToken stored in the DB Provider table & i'll play with it.

**Comment by mattkrick** [comment]
hey @jordanh are you sure you pushed the commit?
Here's what i see on your repo:
`Latest commit 644f411  on Apr 7`

Just tried this with a 2 year old repo on my account & it worked. 

Cynical me wants to say "why the heck do you care about integrating against an old repo" but i guess there's a reason? I'll update it to show the newest 60 items.

**Comment by jordanh** [comment]
I pushed a new branch, with a new commit: https://github.com/jordanh/ffmpeg2gif/tree/0.3.2

Interesting corner case!

**Comment by mattkrick** [comment]
well that is bizarre, this comment said the exact opposite & they're clearly mistaken:
https://stackoverflow.com/questions/15918588/github-api-v3-what-is-the-difference-between-pushed-at-and-updated-at

so what's the filtering mechanism you'd like to see?

**Comment by jordanh** [comment]
I think what we have now is safe to try. In the future (where everything is better™), we can do an autocomplete textfield that talks with our server. But for now, I think the heuristic you've got works for most cases, is simple, and will let us learn.

**Comment by mattkrick** [comment]
oh yeah, i forgot abut the typeahead dropdown. note to future self: github's typeahead repo search doesn't have a lot of filters, so it'll actually be easier to grab all the repos in 1 go & then do the filtering locally.
