### ISSUE TITLE
No first line, GH integrated card blocker

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1194]
## UX Bug

I literally had a card with a blank first line and didn’t realize it. The screenshot is just me replicating the issue. Perhaps we could:

a) Trim the empty first line and make it seamless or
b) Have a more user-friendly error message

I say UX bug because this is working as designed. I realize this is an edge case, too.

![image](https://user-images.githubusercontent.com/307286/28893557-7fcc361c-7797-11e7-9952-25a61654352e.png)

**Estimated effort**: 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
@mattkrick is it fairly simple to trim an empty first line?

**Comment by mattkrick** [comment]
yep!

**Comment by ackernaut** [comment]
@mattkrick feel free to pick this one up if you’re on the hunt for low-priority bugs for Epic 6.5, otherwise I can try my hand post-travel.

**Comment by ackernaut** [comment]
@mattkrick so this is my thinking on how to solve this, but I’m a little slow in this neck of the woods.

We have `createGitHubIssue.js`. Here we can check the project content for an empty first line by looking at the content blocks. If the first line is empty, we could call a mutation to update the project. I’m unsure how to get the content state, remove the first block, then pass the new content state into the mutation to update the project content. But if we perform this here, then check for an empty first line (which fails GitHub: title) there will now be a first line and we don’t get the issue.

I think the main gotcha is how to update the content blocks without actually using the editor. Thoughts?

**Comment by mattkrick** [comment]
ah i was looking for this issue!
i can't see a good reason for ever having a blank first line, so i think whenever we update a card on the server, we should check for that & always remove it, github integration or not.
In case you're curious, all the more bespoke draft-js helpers are stored in universal/utils/draft. we don't have one for this purpose, but those will show you how to grab the content state from a raw state. for this purpose though, i think the case is simple enough to keep it in the raw state & avoid instantiating it.

**Comment by ackernaut** [comment]
Yeah, I was wondering if we should just always trim the content.

In that case, I’ll take a look at those more general Draft helpers and see if I can get started.

Thanks @mattkrick !

**Comment by mattkrick** [comment]
for sure! a good place to get started would be just looking at the `content` stored in the DB. once you JSON.parse(content) you'll get a raw content object that'll have an array of blocks. then, you just need to see if the first block has any non-space character. if it doesn't then remove & send the new one back to the DB.

**Comment by ackernaut** [comment]
Ok @mattkrick not sure my effort is very productive…I can see the blocks but not sure how to merge  new blocks (sans first line, whitespace) into the content for the DB. Feel free to pick this up and hopefully I can be more productive elsewhere.

**Comment by mattkrick** [comment]
@ackernaut finally got around to this one. here's what i came up with in case you're curious ^^^^
