### ISSUE TITLE
Show userCount and integrationCount more

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#1195]
Currently, we don't show the userCount & integrationCount if the person hasn't integrated:
![screenshot from 2017-08-02 13-25-29](https://user-images.githubusercontent.com/5514175/28893683-47aebd1e-7787-11e7-9340-8907b3df058e.png)

I think it's important to show the "This is what it does" message for people who haven't integrated.
But i also think it's important to tell them "other people are doing this"
Is there a fancy way we can fit it all in @ackernaut?

**Comment by ackernaut** [comment]
I'm ok making it 3 lines when there is activity, otherwise 2 lines:

- Provider
- Description
- Activity (icons, count)

How does that sound?

**Comment by mattkrick** [comment]
Yeah, that sounds good!

**Comment by ackernaut** [comment]
Also, do we only show the description for folks who are not integrated? Or always?

**Comment by ackernaut** [comment]
To keep things simple, consistent, and a bit tidy:

Row 1: Provider Name (+ Activity Meta when it’s a thing)
Row 2: Description (always)

And then far right: Link or Settings button (depending on `accessToken`)

**Comment by mattkrick** [comment]
i like always!
