### ISSUE TITLE
Remove #private helper line from meeting?

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#1197]
![screenshot from 2017-08-02 14-27-36](https://user-images.githubusercontent.com/5514175/28895837-d89ce1b4-778e-11e7-877f-dee9e7bc8c8c.png)

Now that the menu has a `#private` line, I think it's safe to remove that line from the card placeholder. yay/nay?

**Comment by ackernaut** [comment]
I just added the `#private` line by request from UX testing so I prefer to let it ship and see if any tension returns. At any rate, I think it’s a minimal way to learn the UI, but by removing it the UI would be cleaner.

**Comment by mattkrick** [comment]
right, but that was before we had a `set as #private` menu item. The tension is that the hint never goes away. Even after the 100th meeting, it's there. As a recurring user, i shouldn't have to put up with the same UI as a first timer, right?

**Comment by ackernaut** [comment]
I see your point. Perhaps we pass down the meeting number. Meeting number less than 4 and show.? @tayamueller should it stay or go?
