### ISSUE TITLE
Tab and Enter to trigger card menus during Agenda

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1198]
## UI Bug

It is possible to tab to the card menu (GH or Status) and tap `enter` to open the menu. This also advances to the next step of the Agenda. Can we prevent that event from being captured when using the menu to avoid advancing?

**Estimated effort**: 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
What do you think @mattkrick ?

**Comment by mattkrick** [comment]
This is the joy of hotkeys. I think we should honor browser defaults as much as possible.
If enter is pressed & something has focus, we should not activate the hotkey.
if enter is pressed & nothing has focus, it is safe to activate the hotkey.
so, we just need to load up our hotkey callbacks with a bunch of `if (document.activeElement)`...

**Comment by ackernaut** [comment]
Totally agree with the “honor browser defaults as much as possible”

So I take it I can tinker with the meeting container to listen for the active element and conditionally handle the hotkey?

**Comment by ackernaut** [comment]
This applies to both Updates and Agenda…as users can attempt to tab and enter to trigger the status menu in Updates as well.

**Comment by ackernaut** [comment]
Alternatively, we could consider just removing `enter` and only leaving `left`, `right` or tapping navigable elements. @mattkrick what say ye?

**Comment by ackernaut** [comment]
Remember we are considering Here / Not Here controls only be visible to the Facilitator.

**Comment by ackernaut** [comment]
@mattkrick feel free to pick this one up if you’re on the hunt for low-priority bugs for Epic 6.5, otherwise I can try my hand post-travel. (I think we just yank `enter` altogether and DONEZO)

**Comment by mattkrick** [comment]
i think the conditional in the hotkey callback should work, but i haven't tried it.

**Comment by ackernaut** [comment]
I did try it. `document.activeElement` returns the `<body/>` if nothing else…

**Comment by mattkrick** [comment]
ah, so if the activeElement is not the body, then disable the button press
