### ISSUE TITLE
Card menu behaviors (with keyboard handling)

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1199]
## Enhancement

Users should be able to interact with the card menus via mouse or keyboard.

**Scoping the behaviors**:

- [ ] Users can press `tab` to focus on the toggles (avatar or flat button) (first addressed by #1198).
- [ ] Users can press `enter` to open the menu (first addressed by #1198).
  - [ ] The button (toggle) that was tapped no longer has focus.
  - [ ] When the menu is opened via `enter` or mouse click no option is selected.
  - [ ] Pressing `down` the first time highlights the first option.
    - [ ] Users can cycle up to the top or the bottom after this point, via single taps or holding the arrow key.
  - [ ] Users can press `enter` to make a selection (which closes the menu).
- [ ] Users can press `escape` to close the menu.
- The toggle gains focus when the menu is closed if:
  - [ ] `tab` is pressed while the menu is open. This is true even if the user opens the menu with the mouse, then presses `tab`
  - [ ] A selection is made using `enter` and the menu was opened via keyboard (tab/enter)
  - [ ] When `escape` is pressed and the menu was opened via keyboard (tab/enter)
- The toggle _does not gain focus_ when the menu is closed if:
  - [ ] The user taps something other than the card.
  - [ ] The user opened the menu using the mouse and presses `escape`.
  - [ ] A selection is made and the mouse was used to open the menu.
- If the user opens the menu with the mouse, but then uses arrow keys and enter:
  - [ ] The toggle does not gain focus if the menu is closed via selection or `escape`

**Notes**:

- The `AsyncMenu` container+component currently does the work of positioning the component.
- The `Menu` container+component currently does the work of creating the actual menu in the `AsyncMenu`.
- We need to hook into key events using React. These are already there for elements like `input`s but need some wrangling to add to `div` elements.
- **Suggestion**: We create an HOC for menus `withBehaviors` or build in the behavior into the `Menu` container.
- **Alternatively**: We create an HOC that adds keypress superpowers to any component, looking to cycle through an array of inner components, with general helpers like highlight/“make active” and select on `enter` etc.

**Estimated effort**: 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
@mattkrick taking a look at how you handle `up` and `down` arrows in [withSuggestions.js](https://github.com/ParabolInc/action/blob/master/src/universal/components/ProjectEditor/withSuggestions.js). I want to see if I can use a similar pattern to select menu options once the menu opens. I’m curious where the `<ComposedComponent/>` comes from? Taking a 👀

**Comment by ackernaut** [comment]
@mattkrick I updated the main comment here, with an attempt to be more granular on menu behaviors via mouse or keyboard in the card context. Some of these behaviors may translate well to a menu in any context but I haven’t made that much progress with the thinking. If you get a chance, let me know if those behaviors make sense to you. I found inspiration in how Google Keep handles some of these nuances.

**Comment by mattkrick** [comment]
1 thought:
- trello has a night up arrow/down arrow to highlight cards. wondering if that might be good? how might someone navigate the kanban without tabbing 5 times to get to the next card?

**Comment by ackernaut** [comment]
Yeah, that is a nice touch.

I could see, perhaps, arrowing around cards ala Trello style, and then pressing something, like `enter`, to select the card. Then as the card has focus, one can tab around through the elements and interact with menus as described in the top comment. One may need a way to un-focus the select card as well. Perhaps `escape` works when no menu is open?

**Comment by mattkrick** [comment]
yeah, that's something we'll wanna dig into deeper before the build out. for example, google keep lets you have a selected card while you're still focused on the menu (using those terms loosely, not sure if that's what it tells the DOM). it'd be interesting to see what kinda benefits there are from decoupling selection from focus.

**Comment by ackernaut** [comment]
Gonna defer this one until a later Epic (too big for the scope of this Epic)…may work in a little more goodness into the basic menu handling from #1198

**Comment by jordanh** [comment]
Scrubbed. @ackernaut this will likely get iceboxed. May I suggest opening a new issue with AC and EE around what we've learned here through the discussion?

**Comment by ackernaut** [comment]
This will be handled in future menu enhancements, no need for this older issue.
