### ISSUE TITLE
Redesign or revert GitHub links to only contain issue numbers

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1201]
## Issue - Bug

Observe:

![image](https://user-images.githubusercontent.com/103000/28900745-529b58a6-77a8-11e7-9c8d-0065b8847758.png)

- **OS:** OSX
- **Browser:** Chrome
- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
oh gosh dang, the ol commit without saving first i guess. fixed!
