### ISSUE TITLE
Meeting Component Names

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#1202]
## Issue - Enhancement

I'm still observing confusion around the purpose & use of the Meeting components, even by our most frequent & highly trained Holocratic practitioners.

Recommended order & naming updates:

1) Social Check-In [emphasize NON-work-related nature]
2) Shared Metrics [see #330 ] 
3) Solo Updates [emphasize individual voices]
4) Team Agenda [emphasize collaborative opportunity]

I'd love to eventually drop back to single-word headers, but for now--when this type of process is still so new--I think it's better to be explicit & educational.

**Comment by ackernaut** [comment]
See #1213
