### ISSUE TITLE
Governance

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#1204]
## Issue - Enhancement

Our consultant users request--and we anticipate the need for--governance capability. Is there a way to integrate with Guru as an intermediate step to building our own?

**Comment by ackernaut** [comment]
Oh wow! So I think we have a solid start to a document editor (UXed as a project/task card) that can be used to capture team knowledge. I think this is really about abstracting a little bit on meetings (I would like to see Action™, Retro™, Gov™) which can reuse bits in the system (cards, workflows, team notes, cadence). And then we organize a team as a hub (users, notes, etc.) opposed to it being another kanban.

See #1101 #1008 #1059

**Comment by jordanh** [comment]
Can we please add some acceptance criteria to this issue or close it please?

**Comment by jordanh** [comment]
Scrubbed twice
