### ISSUE TITLE
Billing for Consultants

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#1205]
## Issue - Enhancement

"Billing is still confusing, and doesn’t support fluctuating team sizes, which is common for my clients. As a consultant, I want to be my own Billing Organization, with multiple client Teams. That way I can offer it for free to my clients and skip the part about selling them on Parabol. That's way easier and they trust me as the expert."

**Comment by mattkrick** [comment]
@tayamueller any suggestion on what to do here? Seems to me like you absolutely could have an "ABC Consultants" organization & each team be a different client.

**Comment by tayamueller** [comment]
@mattkrick I think this is safe to shelve for now & revisit after partnership agreements are solidified. @jordanh thoughts?

**Comment by jordanh** [comment]
I think it is safe to shelve, with the Freemium epic as it is, we have a way forward
