### ISSUE TITLE
Remove "Priorities" in invites

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#1207]
## Issue - Enhancement

Recommend removing "teammate priorities" from the invite process. I have _never_ observed a user do this naturally (unprompted) during an onboarding observation. It doesn't seem to make sense to users outside of the context of seeing a dashboard. 

I think the goal behind this (populating the team dashboard) can be better achieved through new first-time card pre-sets.

**Comment by dan-f** [comment]
I'm not aware of a "teammate priorities" feature in the invite process.

**Comment by jordanh** [comment]
*Estimated effort:* 11 points

**Comment by mattkrick** [comment]
fixed in #1917
