### ISSUE TITLE
What's changed since our last meeting?

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#1210]
## Issue - Enhancement

Several of our users do daily or twice-weekly check-ins rather than weekly. (the greater the pace of change & chaos, the more frequently a team needs to re-prioritize))

Recommended copy change during Solo Updates: "**What's changed since our last meeting?**"

[current: "What's happened since last week?"]

**Comment by ackernaut** [comment]
+1

**Comment by mattkrick** [comment]
duplicate of #1069
