### ISSUE TITLE
Design: Auto-Sort of Cards by Due Date

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#1211]
**After #1212, and before #296, #213, and #612:**

## Issue - Enhancement

Users currently have to manually sort cards, which is cumbersome (#1072), time-consuming, and sometimes results in upcoming cards getting forgotten in a long list.

Following completion of #1212 , how might we incorporate auto-sorting that reflects users' natural tendency to sort soonest-due to the top of columns?

### Acceptance criteria:
Design uncertainty: 3
- Is a lo-fi design we can test internally
- Parabol auto-sorts all cards in each column by due date, instantly
- If a user re-orders cards with the same due date, Parabol honors that order until/unless a due date is changed
### Estimated Effort
11 points

**Comment by jordanh** [comment]
From SPA V, this one sounds like a sort column at the top. It may also auto-assign a date when a card is moved up and down the column. Deferring for now until we add dates.

**Comment by jordanh** [comment]
Stuck on lack of dates on cards/backend data model. Also needs estimated effort. Will remove from sprint board for now until this issue is groomable.

**Comment by jordanh** [comment]
iceboxing
