### ISSUE TITLE
Facilitator coaching tips

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1213]
Hat tip @tayamueller for the 💪  user observations of late!

Here’s one I had an idea for:

>Love the feel & friendliness of interface but it’s too much in the way--too present & condescending, let it fade into the background so it’s a more neutral voice. I enjoy that you’re part of us, and happy for us but it should be secondary.

**JBTD**:
When learning how to lead an Action Meeting in Parabol, leads/facilitators want private coaching tips that they can toggle on/off at their own pace, so that they can become familiar with the pro-tips that make the meetings successful.

**I imagine**:
- The UI becomes cleaner, more neutral for everybody
- We iterate on the help/tip copy that exists
- We put that copy in a panel private to the facilitator
- The copy is contextual to the view (lobby, check-in, updates, first-call, agenda, etc.)
- The panel floats in the bottom right of the viewport and has a toggle
- The panel defaults to open, and can be closed
- The panel stays closed until the facilitator opens it again

**Estimated value**: [15 points](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md)

**Comment by ackernaut** [comment]
@tayamueller thoughts on this? good, bad, ugly?

**Comment by jordanh** [comment]
I'm going to consider this implemented with our help button!
