### ISSUE TITLE
GitHub integration removal notification

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1214]
## Enhancement

Related to #1155 #1159 

When a GitHub integration is removed, team members want a notification so that they are aware of the change to the team and are aware that all associated cards were archived.

“An integration was removed with the GitHub repository [repo-name]. All integrated cards were archived. [button: ‘Okay’]”

### Acceptance criteria

- [ ] All team members get the message
- [ ] Perhaps we do not show this based on 1) if the activity/change is on GitHub and not in our integration settings (#1159) 2) There were not any integrated cards to archive? any other reasons @mattkrick ?

**Estimated effort**: 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Scrubbed. This will likely get iceboxed before we get to it. But I've added AC to @ackernaut's text
