### ISSUE TITLE
Reply to email to add agenda items

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1215]
## Enhancement

When I get an email that is timely, team-specific and raises a tension (or I remember a tension I wanted to raise), I want to reply via email with my agenda items to get them in the queue for the next meeting.

Maybe this could work in a few contexts:

1) I get an email for a meeting reminder (email as UI, more sticky on mobile).
2) I get a Delta Report™ with what’s changed since last meeting.

In both cases I can reply with my agenda items.

- [ ] Parse each line with the hashtag as a new agenda item: `#agenda [content]`

- [ ] Perhaps we add an optional, secret, shorter pro move: `a: [content]`

Users may like the ability to queue up and forget. They may not see if somebody already raised the same or similar topic, but that gets sussed out in the meeting, no problema.

**Estimated effort**: 15 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
This is a good idea

**Comment by jordanh** [comment]
Scrubbed once. Needs AC and EE

**Comment by ackernaut** [comment]
Probably not happening within a year. If we think so, we can re-open.
