### ISSUE TITLE
teamQuery failing on MeetingContainer

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#122]
## Issue - Bug

I'm getting an exception tossed when performing a relatively simple `cashay.query()`. The message is:

```
utils.js:62 Uncaught (in promise) SyntaxError: Unexpected token u in JSON at position 0(…)
```

It's very possible this is user error. If so, there is an opportunity for some useful error processing in Cashay.

### Details

I wrote a simple query to fetch team information from Cashay:

```
query ($teamId: ID!) {
  team: getTeamById(teamId: $teamId) {
    name,
    members {
    	isActive,
    	isLead,
    	isFacilitator,
      cachedUser {
        picture,
        profile {
          preferredName
        }
      }
    }
  }
}
```

My options look like:

```javascript
teamQueryOptions = (teamId) => ({
  component: 'MeetingContainer',
  variables: { teamId }
});
```

I invoke it in mSTP as:

```javascript
const mapStateToProps = (state, props) => {
  const {params: {teamId}} = props;
  return {
    authToken: state.authToken,
    team: cashay.query(teamQueryString, teamQueryOptions(teamId))
  };
};
```

I get:

![image](https://cloud.githubusercontent.com/assets/103000/16949902/aa699d9c-4dbd-11e6-81c7-f688aedd7ff8.png)

Can be debugged to here:

![image](https://cloud.githubusercontent.com/assets/103000/16949896/9bb93118-4dbd-11e6-8bb4-66bb45534e35.png)

- **OS:** OSX
- **Browser:** Chrome
- **Node version:** v6.2.0
- **NPM version:** 3.8.9
- **RethinkDB version:** rethinkdb 2.3.4 (CLANG 7.3.0 (clang-703.0.31))
- **Estimated effort:** 1 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
just flying blind here with a repo, but i know i don't defensively protect against non-object variables, so maybe it's that?

Just for funsies, try
```
const mapStateToProps = (state, props) => {
  const {params: {teamId}} = props;
  const options = {component: 'MeetingContainer', variables: {teamId}};
  return {
    authToken: state.authToken,
    team: cashay.query(teamQueryString, options)
  };
};
```

**Comment by jordanh** [comment]
Fixed by https://github.com/mattkrick/cashay/pull/86, will close this on new Cashay release.

**Comment by mattkrick** [comment]
closing per cashay release v0.13.1
