### ISSUE TITLE
handle card errors & dragging

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#1221]
currently, a drag just makes a card error disappear. it'd be nice to either animate it away, or make it look like not-a-bug. labeling with design because i'm not sure what the UX should be

**Comment by ackernaut** [comment]
via recordit

![gif](http://g.recordit.co/m2kLX81yrG.gif)

**Comment by ackernaut** [comment]
@mattkrick been doing a little thinking on this one. What if we try having it fade away (opacity) then the card naturally resizes (no animation) when the message is gone?

Right now we have `{error && <Message/>}` —would we need some state to handle an `isClosing` prop? I took at look at `isClosing` on menus and modals and wasn’t sure what was handling the timing there, assuming there is some delay before the component is completely gone.

**Comment by ackernaut** [comment]
It seems the sequence would be: `error`, then `error (&& isClosing)`, then we we would have `!error` so the message would not render after that.

**Comment by mattkrick** [comment]
when exactly would the fade take place? Right now we have a Card and a DragLayer. As it is today, the Card has the error, but the DragLayer does not. The Card turns into DragLayer the moment the dragStart event occurs, so there's no time to run an animation. We could put the error on the DragLayer, too, but if we did that we may as well put the error back on the Card at the end. 
I'd feel OK about kicking this issue down the road if you like, it'll be some trial & error to build out the DragLayer.

**Comment by ackernaut** [comment]
Yeah, I agree it can be deferred…no longer prioritized marking as snoozed.

**Comment by sarakhatri** [comment]
[Parabol Animation Guidelines ](https://docs.google.com/a/parabol.co/document/d/1UnjHCEHsRWsmTLIsGrbBFY8hVyoiRyw0EQXPgSN4xDM/edit?usp=sharing)

**Comment by mattkrick** [comment]
iceboxing, good nuff for now
