### ISSUE TITLE
Corner case: 'add your first repo' from within meeting not so good

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1233]
## Issue - Bug

1. Add GH integration but no repos
2. Start meeting
3. Click 'Add your first repo' link from project card:

![image](https://user-images.githubusercontent.com/103000/29150234-19b09566-7d2e-11e7-9983-f7e83a08896c.png)

**Comment by mattkrick** [comment]
what's the desired flow here? let them in settings or disable the button?

**Comment by jordanh** [comment]
I think it's probably "disable the button." But, I'm not sure. I think we can safely let this bug sit awhile until we collect more data.
