### ISSUE TITLE
Removing GitHub integration can leave stray repos

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1234]
## Issue - Bug

Reproduction steps:

1. Add GH integration
2. Add 2-3 repos
3. Click "Remove Integration"

Watch:

![gif](http://g.recordit.co/JacMT60MwO.gif)

Note: this failure is intermittent.

- **OS:** OSX
- **Browser:** Chrome
- **Estimated effort:** 11 points

### Acceptance criteria
A user can:
 - Remove the integration and have all repos reliably removed

**Comment by mattkrick** [comment]
how did you start out with a repo with no members?

**Comment by jordanh** [comment]
Good eye! This was because I repro'd this bug twice. By adding 2-3 repos and then removing the integration, it can leave a repo with no members. When I then made the gif, that repo was already there...

**Comment by jordanh** [comment]
Added AC and EE, added to Sprint board

**Comment by ackernaut** [comment]
GitHub integrations are not being widely used, or driving sales. Is this a priority within the next 12 months? Consider ice-boxing.

**Comment by jordanh** [comment]
iceboxing
