### ISSUE TITLE
GitHub UX – add org third-party access tip

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1236]
## Issue - Enhancement

When I created a new org on GitHub to test integrating a team with a repo, I couldn't get the repo to list. @mattkrick informed me I needed to acccess my GitHub organization's "Third-party access" settings and change the policy to `No restrictions`:

![image](https://user-images.githubusercontent.com/103000/29177805-889195c2-7da4-11e7-9941-ca3376dcefe4.png)

Without making this clear for our users, I could see how this could frustrate them and/or generate support requests.

Some thoughts on how to resolve this:

* Add some documentation / setup steps to the GitHub integration settings itself
* Add a link to external documentation at parabol.co/integrations/github or similar...

Other idears?

- **Estimated effort:** 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
i was thinking about this last night & i think it'd be good info for a help modal, but then again:
- setting up webhooks only works if they are the admin for the github org
- if they have integrated any other 3rd party apps, they've already done this
- these webhooks are more of a convenience than a necessity

for those reasons, i don't think it's critical that we make them follow a list of steps. In the future, I could see it being helpful to send them a hint if they are an org admin. It's still very likely that someone who does not admin an org set up a repo & they won't get this benefit & there's nothing we can do.

**Comment by jordanh** [comment]
I think there is a good chance that as an org admin they are setting up their first 3rd party app and could get stuck. For data, I cite myself 👅 

What do you think about starting with a link to external documentation? I can get that setup quickly and we can evolve from there...

**Comment by mattkrick** [comment]
i absolutely hate external documentation. it goes back to windows 95 when you have a problem, hit F1 & you're given a book & you double click the chapter, you read all about it and after the whole thing you still didn't get resolution, so you click the index button, type in every possible keyword, still nothing. then sites copied that model & put a half assed "still have questions? contact us" at the bottom. or "rate the quality" or "did this fix the problem?". i don't like any of it.

i'd be much more inclined to offer something highly contextual. For example, when they add a repo, we see if a webhook exists and if they have admin access. If they don't, we send them a message under the freshly added repo saying "Hey, looks like you're not an org admin. Everything will still work, but we won't be able to detect when someone joins/leaves the org'. If they do, we send them a message asking them to make sure 3rd party apps are enabled. When they click "OK", it'll retry to create the webhook. For repos that do not have org access, we can leave a message at the bottom of the repo settings page telling them it's not connected. When they hit connect, then it tries to add the webhook & if it succeeds, then the message goes away.

**Comment by jordanh** [comment]
I like this. Ok, let's then prioritize this for two-way sync since it'll be related. Sound good?

**Comment by jordanh** [comment]
Err – one-way sync (currently Epic 9)

**Comment by ackernaut** [comment]
Ice-boxing for now.
