### ISSUE TITLE
GitHub user added/removed from org hook enhancement

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1238]
## Issue - Enhancement

This is part bug, part enhancement.

### The bug part

Currently, when the Parabol server receives a GitHub hook notifying us that a user has joined or left a GitHub the logic that handles this doesn't link or unlink the user from the repos integrated with us.

### The enhancement part

When a user becomes unlinked from a repo, I want the Project Cards owned by this user to reflect that the change has occurred, so that I might take action (like reassigning them, relinking the user, etc.)

We can use our fancy-schmancy on-card dismissible notification to to make a notification. Something like, "Person X is no longer a member of GitHub org Y."

- **Estimated effort:** 15 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
assigning to terry for the UI flow. couple thoughts:

currently, card errors are not persisted, which means either the error only shows to folks who are currently online, or we have to persist those errors.
if someone gets kicked out of a GH org, they're probably gonna get kicked off the team soon enough. can we just wait till then?

**Comment by ackernaut** [comment]
Probably not happening in a year. Ice-boxing.
