### ISSUE TITLE
Move from react-look to fela or aphrodite

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#124]
## Issue - Bug

React 15.2 has pretty much killed react-look, and the package is unmaintained, so we need something different.
The successor to react-look is [fela](https://github.com/rofrischmann/fela).
A lightweight version put out by the good folks at khan academy is [aphrodite](https://github.com/khan/aphrodite)

Right now, my preference would be to go with aphrodite for the following reasons:
- I'm not sure I like the fela API, where you have to create your children before you can use them: http://fela.js.org/docs/guides/UsageWithReact.html
- aphrodite is older & has a larger community
- aphrodite is smaller
- concerning dynamic css (a fela feature), aphrodite handles it like: [this](https://github.com/Khan/aphrodite/issues/98), which may actually be more performant if we memoize that function call.
- concerning fallback values (another fela feature), we aren't targeting older browsers, so we don't need the extra logic
- aphrodite is front-end agnostic, which means new versions of react won't break it (15.2 😞 ). To be fair, Fela is front-end agnostic, too, but it has a a react wrapper that currently is suffering from the 15.2 passdown props problem, so we'd need to do a PR to get up and running.

However, at the end of the day, I'll go with @ackernaut's preference, since he'll use it a lot more than I will.

- **Estimated effort:** 3 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes

**Comment by mattkrick** [comment]
https://www.youtube.com/playlist?list=PLo4Zh55ZzNSBP78pCD0dZJi9zf8CA72_M

**Comment by mattkrick** [comment]
Also, consider where to place style.
Currently, we define styles above the component (per eslint), then put the bulk of them below.
However, style constants then must also live above the component, making up eat a component sandwich: (https://github.com/ParabolInc/action/blob/master/src/universal/components/UserHub/UserHub.js#L7-L10).

So we have options:
- component sandwich
- define below
- define all styles in another file

**Comment by mattkrick** [comment]
when we move, we should also put the `theme` in the react context if there's no way to set it at compile time.

**Comment by mattkrick** [comment]
Another option is JSS:
- here's an article biased towards JSS: https://medium.com/@oleg008/aphrodite-vs-jss-a15761b91ee3#.ittwup4t6
- and a response biased towards aphrodite: https://github.com/kentcdodds/ama/issues/172

After reading both, i'm still bullish on aphrodite

**Comment by ackernaut** [comment]
Thanks for dropping those two posts here @mattkrick —I read them, going to let that simmer until we start looking more closely at this again.
