### ISSUE TITLE
Remove Team Member: send to pubsub

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#1240]
leaving a team should send a message to the pubsub listing out the repos that should be unjoined. we don't do this yet because i want to refactor it to follow the rule that all pubsub calls should be called directly from the mutation because nesting those in helpers can get confusing & cause double messages

**Comment by jordanh** [comment]
@mattkrick is this still an issue? I think the relay refactor et al took care of this...

**Comment by mattkrick** [comment]
still an issue, this pertains just to the github repos

**Comment by jordanh** [comment]
Scrubbed twice. @mattkrick, sorry to be a broken record. Is this still an issue? If so, could we add AC + EE?

**Comment by mattkrick** [comment]
iceboxing
