### ISSUE TITLE
Facilitator tethering issue

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#1243]
## Issue - Bug

When conducting 2nd session with a user group:
1) Facilitator advanced to 2nd teammate during 1st teammate's Social Check-In. (forgot we were all tethered to him)
2) Facilitator returned to 1st teammate but the other users had all become untethered
3) Facilitator attempted to return to beginning of meeting.
4) Other teammates hit refresh
5) Facilitator was kicked off of Facilitator role, which was reassigned to another teammate

6) Noted several times during subsequent meeting that teammate cards weren't always reflecting real-time changes during Updates section

7) At end of meeting, I watched new Facilitator End Meeting, however upon returning to my Dashboard, it appears the meeting has not been ended.

8) Team is unable to use Team Board b/c it's locked for "current meeting" :(

**Comment by mattkrick** [comment]
3. what does beginning of meeting mean? they facilitator was already on the 1st teammate of the checkin round, where did he go from there?

5. did the facilitator hit refresh? the facilitator should not lose control unless he does

6. can you define subsequent meeting? this whole thing occurred during the 2nd meeting, right? any details on what changed & when?

**Comment by jordanh** [comment]
The resulting bug state is _way_ interesting. Here's the view of the user:

![image](https://user-images.githubusercontent.com/103000/29293770-1fe6ed64-8101-11e7-9219-1ed6312d12ea.png)

Now, when the go to join the meeting:

![image](https://user-images.githubusercontent.com/103000/29293784-2d695670-8101-11e7-8f97-ec2e38cc650e.png)

(more notes coming)
