### ISSUE TITLE
Switching from My Dashboard to Team causes blank render

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1244]
## Issue - Bug

1. Log in as oliver@hirevisor.com 
2. Navigate from My Dashboard to his team
3. Observe:

![gif](http://g.recordit.co/ci7T6UxKJh.gif)

This smells like a router issue to me...

Thank you @oliver-zhou for reporting this!

- **OS:** OSX
- **Browser:** Chrome (Chrome Version 60.0.3112.90 (Official Build) (64-bit))
- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by oliver-zhou** [comment]
Looks good now too

**Comment by jordanh** [comment]
💃 🕺
