### ISSUE TITLE
Project disappears when dragged to Done column

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1245]
## Issue - Bug

Only on My Dashboard, when the user drags a project from Active->Stuck or Active->Future it works fine. However, when the drag the project from Active->Done the card disappears (although the Done column counter indicates the card is in that column). Observe:

![gif](http://g.recordit.co/o9etggIYYV.gif)

Note also that when the navigate to their team board, the dragged Project card is duplicated across columns!

![image](https://user-images.githubusercontent.com/103000/29294500-7e8635b6-8104-11e7-9e79-4bbe92e46f18.png)

Other note: this creates a new console message each time – exception generated is #1228 

- **OS:** OSX
- **Browser:** Chrome
- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
This exception may also be related: https://sentry.io/parabol/action-production/issues/328403328/

**Comment by oliver-zhou** [comment]
Looks good to me now

**Comment by jordanh** [comment]
Thank goodness! Thank you again _so_ much @oliver-zhou for helping us out here. Feel free to open issues for _anything_ (even features you'd like to see).
