### ISSUE TITLE
Outcome Card editing state turns off when the link modal is open

### ISSUE THREAD

**Issue by totally-not-dan** [ParabolInc/action#1258]
## Issue - Bug

- **OS:** Linux (I know, I know...)
- **Browser:** Chrome and FF Nightly
- **Node version:** v7.10.1
- **NPM version:** 5.3.0
- **RethinkDB version:** rethinkdb 2.3.6~0zesty (GCC 5.4.1)
- **Estimated effort:** 13 points perhaps given my familiarity with the app

To reproduce:

- Pick an outcome card
- Note the header displays "Created X minutes ago"
- Now select/edit that card
- Note the header displays "Editing..."
- Hit Cmd/Ctrl-K to open the link modal
- Note the header displays "Created X minutes ago" again

I consider this a bug since I'm still "editing" the card `¯\_(ツ)_/¯`

**Comment by mattkrick** [comment]
I'll let @jordanh confirm point values, but i think this a great little batting practice.

**Comment by jordanh** [comment]
13 points, confirmed! @totally-not-dan it's yours.

I'd recommend submitting a PR early and pushing to that branch. It's helped folks get feedback as they go along...

**Comment by totally-not-dan** [comment]
Sounds good! Will ping as soon as I do so.
