### ISSUE TITLE
Automatic URL / link detection doesn't handle websites without a subdomain

### ISSUE THREAD

**Issue by oliver-zhou** [ParabolInc/action#1264]
## Issue - Enhancement
I've noticed that URLs/domains/links are automagically detected, which is nice.
However, it doesn't handle domains that do not have a subdomain. i.e., api.hirevisor.com, www.hirevisor.com are detected and handled properly, but it seems that hirevisor.com isn't detected. As a regression, I tested this against Trello - which properly handles all 3 url formats.

I think if the behavior is to remain consistent, handling non-subdomain'ed websites, at least for the top 3 domain extensions - i.e., .com, .org, .net would be great.

![image](https://user-images.githubusercontent.com/906828/29383008-733af8ce-8283-11e7-8106-cbd650549f1a.png)

- **Estimated effort:** 11 points

**Comment by oliver-zhou** [comment]
Interesting note - I guess github only handles www.*.com urls

**Comment by mattkrick** [comment]
oh this is a fun one! i'll fix that up today & get it in the next release

**Comment by mattkrick** [comment]
@oliver-zhou just for my own sanity, can you assure me that you hit space after `hirevisor.com`? just tried it out & it happens if you hit space, but you're absolutely right that it does _not_ happen when you finish editing

**Comment by oliver-zhou** [comment]
@mattkrick you're right - this seems to happen regardless of URL type if there is no trailing space.

**Comment by mattkrick** [comment]
oh cool, i'll close as working as intended. as cool as it'd be to linkify the url when you finish editing, i could see that getting really annoying if you didn't want it linkified

**Comment by oliver-zhou** [comment]
@mattkrick I'd still prefer it to match other tools I'm familiar with - and by that I mostly mean Trello, which can generates a link without require a space after the URL if typed

**Comment by mattkrick** [comment]
@oliver-zhou

**Comment by oliver-zhou** [comment]
Obviously this boils down to your tastes. However, I think the right way is to default to link creation, since almost all my other tools do this on a regular basis, so that becomes my new expectation. The fully baked out method would be to allow something like "Right Click" -> "Remove Link" or something similar. 

Gmail is another example - if I merely type hello.com or www.hello.com with a line break and send the email, when I get the email, they've all automagically turned into hyperlinks.

![image](https://user-images.githubusercontent.com/906828/29425464-2e3e7042-8338-11e7-8a4d-ea4139050850.png)
