### ISSUE TITLE
Archived Projects do not show up for https://action.parabol.co/team/HkZ_gKAyb

### ISSUE THREAD

**Issue by oliver-zhou** [ParabolInc/action#1270]
## Issue - Bug

For our team, old items do not show up in the "Show Archived Projects"

https://action.parabol.co/team/HkZ_gKAyb

I don't see things from previous weeks or even test/example projects that I created to see if I could get Archived projects to show up.

- **OS:** macOS 10.12.6 (16G29)  
- **Browser:** Chrome  60.0.3112.101 (Official Build) (64-bit) 
- **Estimated effort:** 13 points

**Comment by oliver-zhou** [comment]
Possibly related to the issue where our Team was stuck in "Meeting Mode" that @jordanh manually fixed for us. (Unsure if there was a github issue tracking that)

**Comment by oliver-zhou** [comment]
I archived a card called "asdf"

**Comment by mattkrick** [comment]
thanks for the heads up @oliver-zhou! 
@jordanh may be worthwhile either cherrypicking this commit into a hotfix or just merging what we have of epic 6.5 to prod to fix this regression (pushin to prod on a friiiiiday).
