### ISSUE TITLE
Move summary "Quick stats" above the fold...

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1283]
## Issue - Enhancement

Feedback from Adam P – the Meeting Summary quick stats should _always_ be above the fold – even above your "good job for first meeting!" and "schedule meeting" messages.

I agree with him, I think it entices folks to begin an eyeball scan downward.

- **Estimated effort:** 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
see #1056 and #735

**Comment by ackernaut** [comment]
My proposal:

Currently we have…

- header (team name, date, go to dashboard link)
- message (way to go! **or** first time schedule recurring prompt **or** no agenda items?)
- quick stats
- map over teammates with new projects
- map over teammates with no new projects
- general appeal to ask us for help, give us feedback

I think we try A or B. Either can help with #1056:

A) We move the message above the general appeal but only show it if it is first time (prompt) or there are no agenda items. We get rid of the “way to go!“ message as it seems like noise, no value.

B) We merge the message and the general appeal for help/feedback:
- default: “How’d your meeting go? We’re eager for your feedback! Email us: love@parabol.co Learn More [link] about the Action Meeting Process.”
- first time: <prompt to schedule recurring meeting on calendar> see #1056 
- no agenda items: “Hey there! It looks like there weren’t any agenda items. Did our software give you trouble? Let us know: love@parabol.co”

**Comment by ackernaut** [comment]
we can wordsmith, too!
