### ISSUE TITLE
Add segment events when folks integrate

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1284]
## Issue - Enhancement

Let's add some server-side segment events for when folks add an integration. It'd be great to know the usage stats.

- **Estimated effort:** 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
Duplicate of #1176

**Comment by jordanh** [comment]
Closing this for now
