### ISSUE TITLE
GitLab integration

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1285]
## Issue - Enhancement

One user wrote in after our Friday Ship requesting an integration to GitLab. Opening this to track how many requests we get...

**Comment by frankdugan3** [comment]
Would this be something you'd accept as a pull request?

I took a quick peek, and it looks like you have integrations in `src/server/integrations`, but I'd also guess there is quite a bit more code that is coupled into other parts of the system. If you are interested in a pull request for this, would you be able to give a couple quick pointers to what I need to work on?

**Comment by jordanh** [comment]
Positively @frankdugan3!

I'm not certain if you've tried our Git integration, but our first cut is very rudimentary. It allows a team to (1) Add GitHub as an integration provider to a team (2) add one or more repositories to the team (3) link one or more Parabol team members with their GitHub credentials for a given repository and finally, (4) when a user creates a Parabol Task card, it will generate a new GitHub issue. It's a one-way deal right now. In the future, we'll catch GH webhooks and keep our Task card state in sync with their state on GH according to a configurable rule set.

We'd probably want to start in the same place with GitLab.

I'd suggest we break this down into a set of smaller PRs, and integrate them one-by-one. I'd be happy to write issues for them, one at a time if you like. The first would be something along the lines of:

- `/team/:teamId/settings/integrations` route extended to list GitLab integration and hidden behind a release flag in `src/universal/releaseFlags.js`
- "Link My Account" flow implemented for GitLab
   - Including set of mutations in `server/graphql/mutations/*GitHub*`

Would you like to take a crack at this first step?

**Comment by frankdugan3** [comment]
@jordanh Hmm, I think it may wait until the GH integration is a little more mature before tackling GitLab.
