### ISSUE TITLE
Invalid token error on sign-out

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1289]
## Bug

There is an issue with JWT upon signing out of the app locally or in production.

![screenshot 2017-08-22 11 49 54](https://user-images.githubusercontent.com/307286/29577220-45a2c52a-8730-11e7-8553-4c09afd35102.png)

**Estimated effort:** 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
fixed on my personal branch... i'm gonna go ahead & get that thing ready for merging
