### ISSUE TITLE
New project placeholder text styling assistance [epic6.5]

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1297]
## Issue - Bug

@mattkrick / @ackernaut, we should probably make this placeholder text a smaller font...

![image](https://user-images.githubusercontent.com/103000/29676484-36ff6e6e-88c6-11e7-8481-8288b545c7e0.png)

**Comment by mattkrick** [comment]
could we just make the card taller? it'd feel weird if the placeholder was a different size than the actually text, right?

**Comment by mattkrick** [comment]
oh ignore me, i see terry did it!
