### ISSUE TITLE
Check-in sprint

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#130]
## Issue - Enhancement

Following up from #121, here is the bite-sized chunk:

- Check-in round:
   - [x] List of team members rendered into cards
   - [x] Cards processed one at a time (ignore animation for now)
   - [x] Attendees receive checks-marks after check-in (only a green check, we assume all check-in status are "good")
   - [x] When all attendees have checked-in "This wraps up our check-in round" is displayed
   - [x] ProgressBar component iterated based on latest design
   - [x] PushButton component iterated based on latest design

**Comment by mattkrick** [comment]
Hey @jordanh what's up with the "This wraps up our check-in round" page?

- What's the url?
- what's it look like? Just text & a button?
- This kinda caters to first timers, is this necessary for experienced teams?
 - If this is a path you wanna consider, I'd suggest we always go directly to `/updates` & if this is the user's first meeting, then pop a toast when they hit `/updates` that says something like "hey, great job doing check in! now do this"

**Comment by jordanh** [comment]
Here's an old mock [from invision](https://projects.invisionapp.com/d/main#/console/7910441/169377472/preview) for "this wraps up our check-in round." It's only intention was to make the demarkation between meeting phases  complete. URL is the same as the check-in round URL, it's display would likely be derived from state.

![image](https://cloud.githubusercontent.com/assets/103000/17296026/2247d810-57cd-11e6-800b-9f7cf4031516.png)

I think a toast would be a fine alternative. Go for it!

@ackernaut any objections?

**Comment by ackernaut** [comment]
I think the centered, contextual prompt makes more sense in the long run considering the overall design and flow, but I am willing to skip for now and use a toast.

```*lobby->checkin->*move to updates prompt->updates->*agenda first call->agenda items->*agenda last call->summary```

The starred sections represent the transitions in and out of each main section.

**Comment by jordanh** [comment]
Now lint free!

**Comment by mattkrick** [comment]
closed by #134
