### ISSUE TITLE
new cards w/dates in meetings get date-influenced sortOrder

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1306]
## Issue - Enhancement

When a card is created in a meeting, its `sortOrder` is set by its date.

This one needs to be scoped.

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by tayamueller** [comment]
duplicate of #1211
