### ISSUE TITLE
Slackbot Agenda Items Designed

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1307]
## Issue - Enhancement

When I am in a Slack channel and a need arises in a conversation, I want to agenda item so that I don't need to leave the slack window & lose focus but feel as though my need will get taken care of

- **Estimated effort:** 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
iceboxing

**Comment by ackernaut** [comment]
Related:
- #54 (see GIF, a sample of an inline UI)
