### ISSUE TITLE
Current billing model unimplemented

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1308]
## Issue - Enhancement

When moving to freemium. We got a bunch of trialing stuff to yank. Let's make a list here and scope it.

**UI views**:
- [ ] Scrub Org > Billing view (panels)
- [ ] Scrub Dashboard side navigation (isPaid)
- [ ] Scrub Active Trial Alert Bar on Dashboard
- [ ] Scrub Expired Trial Alert Bar on Dashboard
- [ ] Scrub Team Dashboard Unpaid Team Modal
- [ ] Scrub New Team form (no need to enter CC for a new Org, remove yellow panel)

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
We've got 3 states for users:
- trialing: remove from trial, assign to FREE plan
- paying: keep on same plan
- trial expired: put on FREE plan

so steps probably look like:
- remove all trial_expired trial_expiring_soon notifications
- remove isPaid on the teams, replace with the plan name, denormalized from the org
- add plan name to the org
- invoices: is there value in showing a bunch of $0 invoices? if not, maybe we don't even bring stripe into the mix until they sign up to go pro

**Comment by mattkrick** [comment]
@jordanh any preference on whether we tell stripe about non-paying customers? seems to me we may wanna just tell stripe about them when they enter CC info.

**Comment by mattkrick** [comment]
Alrighty, so there is no value is just telling stripe about all the folks not paying us, so here's the revised flow:

- [ ] remove trialOrg from users
- [ ] when a new org is created, don't tell stripe, don't set a periodEnd, stripeId, etc 
- [ ] remove all trial_expired trial_expiring_soon notifications
- [ ] keep isPaid on the teams, but remove the check from all mutations & queries & subscriptions

**Comment by mattkrick** [comment]
closing in favor of smaller issues to burn down
