### ISSUE TITLE
Freemium Archive nag

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1309]
## Issue - Enhancement

When I am a freemium user and I browse my team's archive, I will only be able to see ~1 month's worth~ _a limited amount_ of archived items and see some designed elements which will prompt me to convert.

**The details**:
- [ ] Users on the Personal plan can see projects that have been in the archive **14 days**.
- [ ] On day 15 the card can no longer be seen or unarchived.
- [ ] The timer starts when the card is archived, not when the card was created. The timer resets if the user unarchives a project and later archives it again.
- [ ] The nag model sits above the bottom of the archive grid, where enough gutter is in the inner container to be able to see above the nag all cards 14 days or less.
- [ ] Bonus points: The nag model tells the user how many cards they’re missing out on.

**Estimated effort**: 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
how will this look when we get rid of the archive section in epic 11 with the UI redesign?
also, is it worth it to invest the time to build a nag for something that is gonna go away in next month or 2?

**Comment by ackernaut** [comment]
I have an idea for how to implement the nag on the current archive and what we _think_ we want to do in the future. Basically the nag sits toward the bottom of the view. The current inner container has an added gutter the height of the nag. So once you scroll to the bottom, any last cards will show above the nag. For the future, single kanban, the nag could also sit toward the bottom of the kanban, but when the user is filtering by archive and not paying, each inner column gets that same empty gutter at the bottom. If any user has a full column, they should be able to scroll to the bottom and the last card will be above the nag. I imagine a little fading perhaps. I’ll have to mock it up. If we show the first idea we will get to the better ideas. :)

**Comment by mattkrick** [comment]
fixed!
