### ISSUE TITLE
remove react-router-redux

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#131]
## Issue - Bug

react-router-redux has changed quite a bit from its glory days of redux-simple-router... and I don't like it.
Reasons:
- it no longer offers useful state, everything i need is in `params` or `location`
- it muddies up our clean it. it complicates the beautiful react-router by making me use `dispatch`. Using dispatch within `render` is an anti-pattern. By doing that, dispatch calls all listeners, and that component may be a listener, which means it is all too easy to start an infinite loop & crash your browser.
- it isn't performant-- all those extra closures with nothing to show for it.
- it doesn't consolidate state, it duplicates it. The url holds state, and you can't put that in your store, you can just put a copy in the store.
- I (think) Dan doesn't like it anymore. Otherwise, he probably would've mentioned it in: https://egghead.io/lessons/javascript-redux-navigating-with-react-router-link. Granted, it could be that he doesn't want to chose a winner (react-router-redux vs redux-router)

Why i need to remove this TODAY:
- in the `MeetingLobby` I want to call a redirect to wherever the facilitator is (ie don't let people in the lobby if the meeting is in progress). I can't do this unless I catch it in both the constructor & the cWRP.

**Comment by mattkrick** [comment]
Refactor is complete on the checkin branch. I think this is a BIG win for cleaner code.
@ackernaut Check out how much easier it is to make links now:
https://github.com/ParabolInc/action/commit/b27eb84f2258bf244ee809d1a957a6d228a5fe06#diff-405d6eb9df90d08a48e6c30cffeebcf8L9

Since the `Link` can match the url to determine if it's active or not, `active` is no longer something we have to worry about as a prop. 

To trigger a `push`, we just call `router.push` instead of `dispatch(push(...`. `router` comes from the props when you add a `@withRouter` HOC.
https://github.com/ParabolInc/action/commit/b27eb84f2258bf244ee809d1a957a6d228a5fe06#diff-48763b734bc2d96822541ecf20f0bbb1L22

Now our meeting flow logic is gonna be a breeze to implement, since we don't have redux calling `setState` inside of a deeply nested `render` function.

**Comment by ackernaut** [comment]
👍 👍 big, big win @mattkrick thanks!!!

**Comment by mattkrick** [comment]
closed by #134
