### ISSUE TITLE
Check-in questions freemium nag

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1310]
## Issue - Enhancement

When I am a youngster and I reject being told what to do, I want to edit my own check-in question – however when I am a freemium user I will be prompted to convert.

**The details**:

- [x] Any Personal™ user on the team can see a pencil icon on the standard Check-In questions. Upon clicking the button they get a tooltip letting them know that they can upgrade to customize the question. They can’t edit, sadness, badness 😢. They have to upgrade outside of the meeting at a later time.
- [x] A Pro™ user will not see the nag. Anyone on the Pro™ team sees the pencil icon and can edit the Check-In question. The question only persists for that meeting. The Pro™ team will return to standard Check-In questions for the next meeting, but can customize as often as they like.
- [x] The question supports **bold** and _italic_ formatting via DraftJS.

**UI specs**:
- [x] The question is an inline editable component (like the Team Name under Team Settings) but with the appropriate type formatting. The component including the text and the pencil can be clicked or hovered.
- [x] When any user on a Personal team hovers the editable question they get the “paywall” tooltip.
- [x] When any user on a Personal team taps the editable question, the “paywall” tooltip stays open until they tap again or tap another element.
- [x] When any user on a Pro team hovers the editable question, they get the “tap to customize” tooltip.
- [x] When any user on a Pro team taps the editable question, the cursor appears at the beginning of the input with the current question as the value. This is so that they do not immediately lose the text if they decide to back out.
- [x] Pressing enter, or tapping away element, commits the updated value.
- [x] When the user is editing the editable value, the pencil does not show.

**Estimated effort**: 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Related to #870

**Comment by mattkrick** [comment]
does this text field have styles (bold, italics, etc)? @mentions? links? my gut reaction says just styles.

**Comment by ackernaut** [comment]
@jordanh 👀 the details for a simple first version. Safe to try?

**Comment by ackernaut** [comment]
Added UI specs for details, behavior.

**Comment by dan-f** [comment]
Waiting for my e2e PR to build, picking this up now.

**Comment by dan-f** [comment]
Fixed in #1435
