### ISSUE TITLE
Try moving end-to-end tests to cypress.io

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#1316]
The new hotness that is supposedly replacing selenium is cypress. A dead-simple example is here: https://dashbouquet.com/blog/frontend-development/cypressio-and-docker-the-ultimate-e2e-stack-part-1

I love the API. It looks a LOT like my MockDB that i made for testing server functions. When we get time, I'd like to try to move our manual e2e tests to it & see how it works.

**Comment by jordanh** [comment]
This is really hot. This could be a good first activity for Dan...Looking forward to discussing!

**Comment by dan-f** [comment]
Definitely seems interesting. I think this warrants a comparison between a WebDriver-based system and cypress. Looks like cypress [doesn't use WebDriver at all](https://docs.cypress.io/faq/questions/general-questions-faq.html#Does-Cypress-use-Selenium-Webdriver), meaning your tests are run in the browser within the same context as your app. I'm trying to better understand what the implications of that design decision are; at the very least, seems like cypress and action will be sharing a runtime / DOM.

The API and debugging tools definitely look nice!

Another thing to note is that they [currently only support Chrome-based browsers](https://github.com/cypress-io/cypress/issues/310).

**Comment by mattkrick** [comment]
IMO i'm OK with starting with chrome for now, especially since they mention more browsers are coming (although i won't hold my breath).
I'm less concerned with "this works on chrome but not firefox" and more concerned with "the signout button no longer works". Sure, there are a couple cases where this isn't the case (draft-js has a firefox bug that hasn't been fixed yet) but we wouldn't catch those bugs anyways since the goal is not 100% code coverage with e2e tests (that'd be waaay to time consuming to write and test). When those cross-browser bugs get patched (either by the browser or the package), they _rarely_ regress, which means running an e2e test for a bug that we haven't seen for the last 12 months is just wasted time. So for those, I suppose I'd take the StackOverflow approach to bugs & let the customers tell us about them & then that allows us to fix the bug, give them a free month, get them stoked on us, etc.

**Comment by dan-f** [comment]
I had another thought this morning on cypress v. webdriver. Seems to me that webdriver would enable us to test realtime behavior, since we can drive two browsers in parallel. I'm not exactly sure what the story is here for cypress, since tests are executed inside of the browser runtime.

**Comment by ackernaut** [comment]
Ah, are you thinking we could simulate 2 users at once? (facilitator and participant, inviter and invitee, realtime interactions, etc.) or am I misunderstanding?

**Comment by dan-f** [comment]
@ackernaut - that's exactly what I'm thinking.

**Comment by mattkrick** [comment]
fixed in #1413
