### ISSUE TITLE
Manual synchronization tension...

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1319]
## Issue - Enhancement

We're getting fairly strong signal on a user need, and I'm not quite sure what to do about it. Adam and Larry have both written in asking to be able to add projects _either_ during a meeting's Check-In or Updates phase. Here's an synthesis from their feedback on the job to be done:

When an Action meeting has started and a user uses an outside tool to track their tasks (Evernote, Trello, Post-It Notes®, [Things](https://culturedcode.com/things/)) and they realize they haven't updated their tasks in Parabol, they want to quickly be able to enter the tasks from another system and put them in the proper status, so that they look like a good team member and can benefit from Parabol's meeting process.

Clearly, some of this tension is resolved through synchronizing to platforms like Trello. But, what about platforms we can't/never will integrate against? How can we reduce this friction?

Can use Slack in some way? Could we give user's the power to setup a reminder for themselves? Something else?

I think what we _don't_ want to do is take away from the intended purpose of a check-in round or updates...

**Comment by ackernaut** [comment]
It was AP that noted:

>Someone made a comment about it feeling linear.

It is not clear that this is negative but I take it that it is.

I think, per user feedback (folks are unsure what to do, who is doing what), we have been giving more ability to navigate to the facilitator, where the team can’t move forward. We have to solve for changing facilitators, making sure the team doesn’t get stuck, etc.

Part of me wants to swing back toward an open UX where anybody can be anywhere at anytime, more like a Google doc. Perhaps there is logic to where only a user can add cards to their Updates view, etc.

I still think we are left with the problem of folks not knowing what to do. Perhaps a starting point is:

1. Open nav for everybody, and more generative (users can add to their own updates)
2. Facilitator gets private tips that can be toggled on/off. Facilitator should be apparent and perhaps we prompt folks to ask the facilitator when they’re stuck.
3. Easy and apparent how to take over the meeting, end the meeting, etc.

Some of the less-used apps, like Things, might make for good intern work, where we find some minimal points of integration.

**Comment by wonko9** [comment]
It was more about the Update phase than the Check-in phase.

**Comment by jordanh** [comment]
@wonko9 one thing we'd like to discourage is folks using the Updates phase for anything other than Quick Updates...perhaps an incremental improvement is to allow only the team member giving the updates the ability to create new projects? Do you suppose that would be a good next step forward?

**Comment by jordanh** [comment]
Ok. So as we've discussed this inside and outside here's the conclusion: #1418
