### ISSUE TITLE
Upgrade to React 15.3

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#132]
@ackernaut remember our conversation last week where we built a higher-order function that shallowly compared the props & didn't rerender if they were the same?

React finally implemented it: https://github.com/facebook/react/pull/7195

To use it, instead of `class Dashboard extends Component` we write `class Dashboard extends PureComponent`.

Note that the shallow comparison is cheap, but not free, so we should only use it where we have a performance bottleneck, exactly like how we did it last time.

**Comment by ackernaut** [comment]
Sounds good…I will give it a try on a few presentational components! Thanks @mattkrick

**Comment by mattkrick** [comment]
closed by #134

**Comment by raphaguasta** [comment]
Hey guys! It's looks good! :) We already have a documentation for this feature?
