### ISSUE TITLE
appTheme.json build race condition

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1325]
## Issue - Bug

So there is [still](https://circleci.com/gh/ParabolInc/action/3340) a rather annoying race condition in our build process that intermittently causes builds to fail.

The root cause of this is, if unlucky, appTheme.json can be deleted just as one of `build:server` or `build:client` is opening it.

To fix this, I believe we should:

- [ ] create yet another npm run command, this time calling it `build:theme`
- [ ] strip `WebpackShellPlugin` from our webpack configuration
- [ ] add `build:theme` to the `build` command

**Comment by mattkrick** [comment]
i think that's a good idea!
another thing we should do is remove tinycolor2 from our client files. the original intent was to replace the 15000 character package with a 5000 character JSON, but right now we serve both, which is no good.
alternatively, we could just use the dev strategy in prod & not even have an appTheme.json.

**Comment by jordanh** [comment]
> another thing we should do is remove tinycolor2 from our client files. Replace the 15000 character package with a 5000 character JSON, but right now we serve both, which is no good.

Right now the only thing that 5,000 character JSON buys us is savings of some CPU cycles when generating the theme file. @ackernaut computes a fairly extensive palette :)

Removing tinycolor altogether might be difficult. Consider code like this:

```js
  const makeSolidTheme = (themeColor, textColor = '#fff', buttonStyle = 'solid') => {
  const buttonColor = buttonStyle === 'inverted' ? tinycolor.mix(themeColor, '#fff', 90).toHexString() : themeColor;
  const color = buttonStyle === 'inverted' ? tinycolor.mix(textColor, '#000', 10).toHexString() : textColor;
```

@ackernaut is computing the component's button color dynamically. It's pretty slick, but not easy for us to precompute unless we redesign the component...

**Comment by ackernaut** [comment]
I can take a stab an minimizing what we are doing with the palette and how we are customizing the button…but if that can wait, and this is a good step forward, I’d say we capture an issue to simplify color usage and then iterate after this merges.
