### ISSUE TITLE
Updates module sprint

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#133]
## Issue - Enhancement

- **Project updates section scaffolded**:
   - [x] We can navigate attendees via the `ProgressBar`.
   - [x] Indication of meeting progress via the `ProgressBar`.
   - [x] Placeholder for four-column project list rendered.
   - [x] Shows current team member (avatar and @PreferredName).

- **Not in scope** (?):
   - Drag-n-drop between columns
   - Keyboard shortcuts

- **Estimated effort:** 3 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

![action-updates-with-shortcuts 2x](https://cloud.githubusercontent.com/assets/307286/17524665/24142000-5e25-11e6-914b-606b5f7641eb.png)

**Comment by ackernaut** [comment]
Updated this issue!

**Comment by jordanh** [comment]
This is next up!

**Comment by mattkrick** [comment]
Data Strategy: Poke all the holes you can.
Projects:
- Projects are stored in the `Tasks` table
- Every time a project is updated, the existing document in the `Task` table is mutated.
- Additionally, we create a document in the `TaskHistory` table that is a superset of the document stored in the `Task` table.
- During a meeting, we mutate the `Task` document, but we _do not_ add a record in the `TaskHistory`
- When a meeting is concluded, every `Task` is diffed with the most recent version in `TaskHistory`. That diff takes the shape of `{old: oldTaskHistoryID, new: newTaskHistoryID}` and is stored in `MeetingProjectHistory`. (Every row of meeting history will require 2 lookups on the task history).
- This `MeetingHistory` feeds the meeting summary

Actions (@jordanh this is where I need some help):
- Actions are stored on the `Task` table
- Everyone on the team has permission to read (not edit) your actions, but it is a UX decision to not provide a view for them
- Actions _do not_ have a history. The are short lived, done/not done items.
- For actions, the meeting summary is populated directly from actions in the `Task` table. This means that if I change the wording of a task after the meeting, the summary will use the updated wording, too.


If the above is correct, I think it'd make a lot more sense to break this into 2 table:
- Action status _does not_ follow the same enum
- Actions need a userId (and index!) Projects don't
- Actions have a `isComplete` flag in place of the enum
- Currently, we need to use a `.filter({type: 'project'})` on our sub. That isn't ideal.

**Comment by mattkrick** [comment]
@jordanh care to comment?

**Comment by jordanh** [comment]
Grokking...

**Comment by jordanh** [comment]
Love it. Some thoughts:

- It's ok to break into two tables, sure. Let's call them `Projects` and `Actions`.
- The idea that mutating an Action mutates a historical meeting summary is _no bueno_. 

There are three possible futures:

1. We do as @ackernaut considered, and only show an action count
2. We rename `TaskHistory` to `ProjectHistory` and `MeetingHistory` contains diffs of Projects _and_ initial Action states.

For the MVP, I'm kosher with 1. But, if you're ambitious, what do you think of 2? (or some similar alternative?)

**Comment by mattkrick** [comment]
> The idea that mutating an Action mutates a historical meeting summary is no bueno.

@jordanh Let's dig into this.
The only thing that can change here is the name of the action. Chances are that means they fixed a typo, or made the name a little bit more detailed. Is that so bad?

Option 2 isn't bad. The reason I'm not a huge fan of it is the schema for an Action (`{MeetingId, TeamMember, content}`) is very different from a Project (`{MeetingId, old: {TeamMember, content, status}, new: {TeamMember, content, status}}`).

**Comment by jordanh** [comment]
> @jordanh Let's dig into this.
The only thing that can change here is the name of the action. Chances are that means they fixed a typo, or made the name a little bit more detailed. Is that so bad?

I don't think this is true. I'm guilty of reusing Trello cards for all sort of inappropriate purposes 😉  At worst, we'd leak something where folks have the expectations (admittedly not the guarantee) of privacy. I think we can do better.

Shall we go option #2?

**Comment by mattkrick** [comment]
`if (!isGuaranteed(expectation)) throw new Tantrum`.

Yeah, if it's really a bad idea to allow for the possible change of an action's content, then option 2 it is. We could implement it a few ways:
- `MeetingHistory` stores Projects & Actions, it has a `meetingId` FK
- `ProjectHistory` stores Projects, `ActionHistory` stores Actions.
- The `Meeting` table stores both projects & actions as arrays of subdocs
- The `Meeting` table stores actions as subdocs, but projects are stored in `ProjectHistory`.

I kinda like the idea of storing these as subdocs. The rule of thumb is to only use subdocs when you'll never fetch the subdoc w/o the parent. The parent would have things like meeting number, endedAt, isActive, etc. We'd just append an array for actions and an array for projects to the document.

**Comment by jordanh** [comment]
I like that last option two. I feels so modern! :)

**Comment by mattkrick** [comment]
last bullet point or the paragraph? (paragraph references bullet point 3).

**Comment by jordanh** [comment]
I think option 3 is the way to go for now. We might revisit option 4 when it comes time to add an audit log, but I think that'll be a straightforward migration...
