### ISSUE TITLE
Error when tapping GitHub card button during Meeting Updates

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1336]
## Bug

During the Meeting Updates, tapping the GitHub card button causes this error:

![screenshot 2017-09-12 11 32 48](https://user-images.githubusercontent.com/307286/30337604-61933308-97ae-11e7-8a02-83c32291c95b.png)

**Estimated effort**: 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Closing this for now. Other, newer GH bugs should address this.
