### ISSUE TITLE
refactor fullName to preferredName

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#1341]
Personally, i dislike the name `preferredName`, too.
Maybe we should go with nickname?
Either way, we've got some legacy "fullName" stuff that is causing crap.

Acceptance criteria:
- [ ] fullName is turned into preferredName
- [ ] preferredName is turned into name (or some other name that points to the user)

effort: 11 points

**Comment by jordanh** [comment]
Touched during scrub. @mattkrick if this is still important add AC and EE, else close?

**Comment by jordanh** [comment]
iceboxing
