### ISSUE TITLE
refactor teamsettings user row into its own

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#1342]
currently, teamsettings component does too much. we need to break the row into its own component so it can have its own error state, waiting state, etc.

**Comment by mattkrick** [comment]
the Resend & Cancel divs should also be buttons so we can stop folks from double clicking.

**Comment by jordanh** [comment]
Touched during scrub. @mattkrick could you add AC and EE?

**Comment by mattkrick** [comment]
this is done
