### ISSUE TITLE
Shortcuts and formatting modal

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1343]
## Enhancement

When users are unsure what shortcuts are available for cards and the UI they want help content that they can access at any time.

**A simple first solution**: Users can press `?` in a Dashboard or Meeting view and see tips for Card formatting, and maybe even tips on adding Agenda Items using `+` or pressing `p` to add new Projects during the Agenda Round.

**Rough early concept as an example**:

<img width="1280" alt="formatting overlay example 2x" src="https://user-images.githubusercontent.com/307286/31196737-6e2b44d0-a914-11e7-95f7-c7b39e15e8ac.png">

**Estimated effort**: 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
This looks *fantastic*!
