### ISSUE TITLE
Unable to access Project archive for some teams [epic6.5]

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1353]
## Issue - Bug

While running the `epic6.5` integration tests I logged in as `jordan@parabol.co` and tried to access the Project archive for team https://action-staging.parabol.co/team/SJ8JvS-Jx/archive (my personal Projects) and for team https://action-staging.parabol.co/team/ry13-k1UW/archive (The Pen, which is a team related to one of our museum users). Both teams don't have many projects (certainly less than a few dozen). The archives never loaded.

However, when I invited a new user, created a new team, a single project, and archived it. No problemo! I was able to see the archive and restore a project card from the archive.

- **OS:** macOS
- **Browser:** Chrome

**Comment by jordanh** [comment]
I have no idea if this is a regression or not. I suspect not. But that's just a hunch.

**Comment by mattkrick** [comment]
This is interesting, should we invest the time to fix or just prioritize getting rid of the archive section?

**Comment by mattkrick** [comment]
I went creepy pockets-- it works on local, does not work on staging. staging logs show jwt expired & that the org leader hasn't paid for a team that doesn't exist in the DB.
not gonna dig any deeper on this since we're totally revamping team archive & after we do that this problem will fix itself.

**Comment by jordanh** [comment]
This might not be an issue any longer. Closing for now.
