### ISSUE TITLE
Toasts too brief, let's make 'em hang a bit longer

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1355]
## Issue - Enhancement

When I was inviting a user to a team, a toast popped informing me that the person I invited needed billing leader approval. However, the text dismissed itself before I could read the text.

1) I think we should do the following add a default `autoDismiss` option to the toasting system's duck, and make it 10 seconds (instead of the [toast system](https://github.com/igorprado/react-notification-system)'s default of 5.

2) audit and make sure we're not passing `autoDismiss` on any of the other toast action creators

- **Estimated effort:** 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
Was this still an issue with the latest 6.5?
All notifications now have 1 home: https://github.com/ParabolInc/action/blob/master/src/universal/subscriptions/helpers/notificationHandler.js#L49

**Comment by jordanh** [comment]
Yeah, I noticed that other toasts we pop (aside from team invites) were just too fast for my nearly 40-year old mind. I think we should change the default in the duck to 10s.
