### ISSUE TITLE
conditionally load es5 polyfills

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#1357]
most of our visitors won't need things transpiled to es5, which according to this article takes up half the parse time & payload size:
https://philipwalton.com/articles/deploying-es2015-code-in-production-today/

we can tackle this after we move away from cashay and SC and revisit SSR.

**Comment by jordanh** [comment]
@mattkrick can you add AC and EE so we can prioritize?

**Comment by mattkrick** [comment]
we only support evergreen browsers (and Edge + websockets) so we don't need to do this.
