### ISSUE TITLE
Exception while extending trial

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1361]
## Issue - Bug

While issuing this GraphQL mutation:

```
mutation {
  a: extendTrial(email: "sean@gr..x.com", days: 60),
}
```

(email hidden for privacy, refer to DB)

This exception was encountered:

```
{
  "errors": [
    {
      "message": "{\"_error\":\"Stripe: \\\"id\\\" must be a string, but got: object (on API request to `DELETE /subscriptions/{id}`)\"}"
    }
  ],
  "data": {
    "a": null
  }
}
```

- **OS:** macOS
- **Estimated effort:** 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
trials gone!
