### ISSUE TITLE
Seed team content scoped

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1362]
When sharing screenshots/videos for marketing and documentation, it would be nice to have seeded demo content so that different views can be captured as images/video without having to stage manually.

My thinking is that we could potentially have 2 seeds:

1. Marketing seed team. The purpose of this is to satisfy the tension above. Developers could seed this team from `npm` scripts. Perhaps admins could seed this team from a minimal admin interface on our staging or dev environments.
2. Optional demo team for onboarding. When users sign up they have the option of seeing a demo team board in order to better learn the software. Perhaps they opt in at the end of the welcome views. This would be separate from any small number of seeded projects for team leads.

**Comment by ackernaut** [comment]
See #1278

**Comment by jordanh** [comment]
I think this can be closed now
