### ISSUE TITLE
Scroll to active agenda item during meeting

### ISSUE THREAD

**Issue by dan-f** [ParabolInc/action#1365]
When the agenda list gets long, it could be nice to scroll the active agenda item to the top of the list.

----

Updated acceptance criteria (thanks to @ackernaut and @jordanh)

## Acceptance criteria:
A user sees:
- [ ] the “Add Agenda Topic” input control at the end of the list (not above the list)
- [ ] once overflow happens, the active agenda item is obvious to the user (list is scrolled to bottom)
- [ ] once overflow happens, the input control is pinned to the bottom
- [ ] explore: visual affordance for overflow top and/or overflown bottom (perhaps a subtle box shadow shows at either end only when that end of the list is overflow)
- [ ] extra credit: input gains focus when users submit an item so that they can write out many without having to manually focus again

## Concepts:

![agenda scroll concept](https://user-images.githubusercontent.com/307286/35582759-53a78f94-05b5-11e8-88e2-d10256a47afa.png)

![screenshot 2018-01-30 11 54 55](https://user-images.githubusercontent.com/307286/35582776-65722ae0-05b5-11e8-9eed-952fdc0fb643.png)

**Comment by ackernaut** [comment]
We are considering a few other UI updates:
- The “Add Agenda Topic” input control will be at the end of the list (not above the list).
- As a new item is being added, we show an initial view of it that says something like “Terry is adding…” to give it that real-time, multiplayer jazz.

**Comment by dan-f** [comment]
Hey, great ideas!

I've got one too, and I wonder if others would like it: could we keep the input focused after submitting an item? It'd help rattle off a few items in a row without having to click on the input again.

**Comment by ackernaut** [comment]
Yes @dan-f ! I’ve wanted that, too. It would be nice to be able to `esc` out of it when ready.

**Comment by mattkrick** [comment]
the `scrollIntoViewIfNeeded` polyfill is in #1695, which this will need, so use that as your base branch if you start before it gets merged to master

**Comment by jordanh** [comment]
## Acceptance criteria:
A user sees:
* the “Add Agenda Topic” input control at the end of the list (not above the list)
* when the agenda list gets long, so the active agenda item is obvious to the user

## Point value: 12
