### ISSUE TITLE
UI for Pro™ customer support

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1366]
## Enhancement

When paying for the Pro™ service, users want a quick and easy way to message Parabol for prioritized and timely support.

**Estimated effort:** 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

#### Design
- We decide where floating actions are in the app: rejoin facilitator, help dialog, support chat, etc.
- We decide on default support content to show when interacting with a help dialog in any new places (perhaps Dashboard Tips 101 outside of the meeting, etc.)
- Write the implementation issues, first thoughts below
#### Implementation
- We configure a service like Olark to show when the users are Pro or Enterprise (we can reconsider using this tool for all users when we feel we have the bandwidth to attend to any user conversation)
- We update the location of existing components to make room for floating support chat control

**Comment by jordanh** [comment]
We could embed Olark or similar if we wanted to

**Comment by jordanh** [comment]
@ackernaut could you add AC to promote this to being a design issue?
