### ISSUE TITLE
Resources limited

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1367]
## Issue - Enhancement

Let's hold a design meeting to create what our initial Personal/Pro/Enterprise tiers will look like.

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Can you create a Pro account from the get go, or must you create a Personal account and upgrade?

When I create a new organization, can I create a new paid organization or will is start as free?

How do we make the concept of an organization obvious to the user?
(we already have the issue of adding copy to the UI)

**Comment by jordanh** [comment]
> Can you create a Pro account from the get go, or must you create a Personal account and upgrade?

Ease of onboarding even over early or repeat conversions. So, Personal account only from the get go.

> When I create a new organization, can I create a new paid organization or will is start as free?

New organizations begin in the Personal, free tier. However, we should make it obvious what tier an org/team is in and make the conversion pathway obvious.

When creating a new team, we are ripping out the credit card form when a new org is created.

> How do we make the concept of an organization obvious to the user?

For example, on the new team page, when a user is debating between creating a new team and a new organization – how does a user know the difference between these two concepts?

*Bonus:*

What is free today will likely always be free.

**Comment by ackernaut** [comment]
Yet another question for this discussion (and I posted in Slack):

**Is there a discount when paying annually instead of monthly (either Pro and/or Enterprise)**?

@mattkrick @jordanh

**Comment by mattkrick** [comment]
nope, enterprise is out of scope as is pro_monthly, pro_annual, etc. Just wanted to declare that 1 tier (pro, enterprise, etc) can have many stripe "plans" (pro_annual, pro_monthly). Just a lil futureproofing is all.

**Comment by ackernaut** [comment]
ah so for this iteration we are designing for: Personal (monthly) `||` Pro (monthly)

**Comment by jordanh** [comment]
Correct!

**Comment by mattkrick** [comment]
discussion complete!
