### ISSUE TITLE
Newly linked card content loses formatting

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1369]
## UX Bug

When selecting card content that has formatting (let’s say **bold**) but isn’t yet linked, it loses any formatting when the link is added to the content.

### Acceptance Criteria
- Formatted text (bold, italic, etc.) doesn’t lose formatting when a link is added to any portion of the text

**Estimated effort**: 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
Would add a record.it but it is acting buggy, delayed…

**Comment by jordanh** [comment]
@ackernaut scrubbed once. Can you please add AC (should be trivial)
