### ISSUE TITLE
Invitation notifications

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1372]
@mattkrick a couple of questions about notification invitations:

1. Does the notification show realtime? (I haven’t seen this to be true locally.)
2. When accepting the invitation is it supposed to go away real time and add the team to the left nav? (I haven’t seen this either, when I tap the button there is no feedback/indication that something is happening. If (A) I refresh the browser, I see the team is added (B) I do not refresh, but try tapping the button again, I get an error in the console.

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
@ackernaut can you please provide repro steps

**Comment by ackernaut** [comment]
I see that this is working locally. We can bring it up again if we see it again.
