### ISSUE TITLE
invite fail

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#1373]
## Issue - Bug

When running a demo, the user sent an invite to me (received) but when I clicked "join" in the email it opened a tab that just kept running this screen w/ the jumping ducks:
![invite bug](https://user-images.githubusercontent.com/14892189/30930094-8eb47e00-a38e-11e7-8630-e2a5bfae54de.jpeg)

User resent invite but it continued to fail (I let it run for an hour)

**Comment by ackernaut** [comment]
Related to #1356 ?

**Comment by tayamueller** [comment]
@ackernaut to clarify: this was a brand new invite for a brand new team (shouldn't be expired, but maybe you mean the mechanics are similar?)

**Comment by ackernaut** [comment]
@tayamueller yep! basically want to link up the related “ducks upon invite” theme in our current issues.

**Comment by tayamueller** [comment]
recurrence of failed invite from Angelo to TM @ 8pm EST 10.05.17

**Comment by tayamueller** [comment]
recurrence for both myself & potential client on 10.09 @ ~2:20pmEST

**Comment by tayamueller** [comment]
Note: in first 2 instances, the teams did show up on Parabol when I went directly to the URL. In this 3rd instance (probably b/c it also failed for her) the team did not show up on Parabol when I went directly to the URL
