### ISSUE TITLE
"Project" -> "Task"

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#1374]
## Issue - Enhancement

Repeat observation of this behavior: when a user first encounters the Process Agenda portion of the meeting, they are often confused about what level of detail to enter in the card. Query indicates that "Project" is perceived as a larger unit, comprised of smaller "Actions" (preferred naming over "Task"). They feel that a Project card should allow more back-of-card detail. It isn't organic behavior for many of our users to break a large project/topic down into discrete tasks.

![project action](https://user-images.githubusercontent.com/14892189/30930338-72c3cd76-a38f-11e7-91fe-d85043bc5aed.jpeg)

--
CURRENT COPY:

**[prompt]**
Derrick: "agenda item xyz"
What do you need?

**[first card]**
Add a **P**roject
(tag #private for personal projects)

--
SUGGESTED COPY REVISION:

**[prompt]**
Derrick: "agenda item xyz"
What Actions do you need to complete this Project?

**[first card]**
Add an **A**ction
(tag #private for personal reminders)

**Comment by mattkrick** [comment]
Options:
- Action (taya's favorite)
- Task
- Project
- Ticket
- Card
- Outcome

@jordanh what say you?

**Comment by ackernaut** [comment]
Just noting that we would have to scrub UI in ALL the places to get this right. Perhaps its own mini-Epic?

**Comment by tayamueller** [comment]
repeat observation of this confusion in both onboarding sessions this week, with a startup user and an enterprise innovation consultant: 

"I feel like my team IS the 'project team', so calling a card a Project is confusing. Also, a project is comprised of units so I'm looking for backend like Trello. I guess I'd call it a 'task' or 'to-do' card ."

"It says Team Projects in the upper left, so is this board just for all the macro projects in my company, or...? Also, why is that a calendar icon? Is there a calendar? That would be great!"

![projects vs tasks](https://user-images.githubusercontent.com/14892189/32680724-041ab6a0-c63a-11e7-9335-4101b84ec60f.jpeg)

**Comment by tayamueller** [comment]
rename "Project/s" to "Task/s" @dan-f
