### ISSUE TITLE
Add tooltip component to Check-In greeting

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1375]
## Enhancement

We’ll most likely be adding the tooltip component for the Check-In customization UX. So let’s follow suite and add it to the international greeting.

**Estimated effort**: 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
can be completed in same PR as #1310

**Comment by dan-f** [comment]
Indeed, addressed in #1435.
