### ISSUE TITLE
Meeting Link updated to use meeting route (w/ feedback)

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1378]
Currently, the Meeting Link in the Meeting Lobby links to the team, not the meeting. Let’s change that so that it routes to `/meeting/` which will already redirects to the appropriate current phase (lobby, check-in, etc.) and add some visual feedback.

- [x] Link routes to `/meeting/` not `/team/`
- [x] Adds the tooltip component (appears below the Meeting Link, centered) that says something like “Copied the URL!”
- [x] Optional: We could consider changing this to the Button component to utilize the animation. Perhaps setting props to `buttonStyle: inverted, colorPalette: cool` with a right icon.

**Comment by ackernaut** [comment]
To clarify I think `CopyShortLink.js` could use a nested `Button` component instead of the `a` tag.

**Comment by dan-f** [comment]
Yeah. Buttons "do things", links "go somewhere", eh?

**Comment by ackernaut** [comment]
Yeah, good point. Also, I was also trying to imagine having a similar look to the current “copy link” component. The `Button` could probably use the default shadow level.

**Comment by dan-f** [comment]
Fixed in #1383.
