### ISSUE TITLE
Integrations List view discoverability

### ISSUE THREAD

**Issue by dan-f** [ParabolInc/action#1379]
## Issue - Enhancement

I was initially confused by the "link to my account" copy; seeing GitHub in the integrations list made me think it had already been "set up". I realize now that I had to allow Parabol to post as me.

I think that "link to my account" could use a tooltip explaining what "link" means, and why you'd want to do so.

<img width="728" alt="screen shot 2017-09-29 at 10 52 05 am" src="https://user-images.githubusercontent.com/2146312/31024786-2fd39c46-a50e-11e7-9f2a-6d4a5ed2baeb.png">

**Comment by jordanh** [comment]
Closing this for now
