### ISSUE TITLE
refactor ownedOrganizations to relay

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#1385]
convert OWNED_ORGANIZATIONS to relay

- OrganizationsContainer

- [ ] turn ownedOrganizations into a query
- [ ] created events subs to feed that query

**Comment by dan-f** [comment]
Alright, taking a look at this!

**Comment by mattkrick** [comment]
i'll use this comment to jot down helpful things that we should probably document somewhere but since it was only me it's all just been in my head:

- Where sensible, I execute 1 GraphQL Query per leaf route (eg `/me/organizations`). It should have a single graphql query that is populated by many fragments that are pulled from the child components
- The component that fetches that query always uses a `QueryRenderer` component & the name of the component has a `Root` suffix (if migrating from cashay to relay, you'll see me change the name suffix from "Conatiner" to "Root".
- If the query is supported by subscriptions to keep it up to date, those should be passed into the QueryRenderer as well

**Comment by mattkrick** [comment]
@dan-f i'm gonna go ahead & knock this one out since it's on the critical path.

**Comment by dan-f** [comment]
Ah, please do. I'm down with the e2e work currently, but if there's something more critical, please let me know!
