### ISSUE TITLE
Failure to redirect user to /welcome after login.

### ISSUE THREAD

**Issue by atannus** [ParabolInc/action#139]
Expected: After login, the user should be redirected to /welcome
Actual: The user stays in /
Env: Chrome, Debian Unstable

**Comment by jordanh** [comment]
Interesting. I tried this on [staging](http://action-staging.parabol.co) with a new user account and wasn't able to reproduce.

I wonder if it's something environmental?

**Comment by jordanh** [comment]
@atannus is this still an issue for you?

**Comment by atannus** [comment]
Not anymore!

**Comment by jordanh** [comment]
That is _great_ to hear!
