### ISSUE TITLE
"Have A Super Day" ....?

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#1390]
## Issue - Enhancement

When I click the hamburger in this view, I expect action options...but I get this message...what is the point? (is this a bug? if not, recommend removal)
![super day](https://user-images.githubusercontent.com/14892189/31205849-1a047df8-a942-11e7-99de-39f3b17c69ad.jpeg)

**Comment by ackernaut** [comment]
@mattkrick perhaps we could educate Billing Leaders here: “You can remove the Billing Leader role from yourself if you promote another member to Billing Leader.” That is verbose, but you get the idea. 

Explicit knowledge for this issue:

You (as Billing Leader, when there is another Billing Leader) can take these actions on yourself:
- Remove Billing Leader role
- Leave Organization

You can take these actions for another Billing Leader:
- Remove Billing Leader role
- Remove from Organization

You can take these actions for a non-Billing Leader:
- Promote to Billing Leader
- Remove from Organization

![_billing](https://user-images.githubusercontent.com/307286/31505440-811f2288-af3a-11e7-8474-cb50c1aa8715.gif)

**Comment by ackernaut** [comment]
See #1405 —perhaps we could make a quick pass on this view.

**Comment by mattkrick** [comment]
duplicate of #742. let's move the convo back over there
