### ISSUE TITLE
Get team-based authz out of Auth0

### ISSUE THREAD

**Issue by dan-f** [ParabolInc/action#1399]
## Issue - Enhancement

Based on discussions w/ @mattkrick, and the bug seen in #1373, I think it'd be useful for us to decouple our authorization from our identification.

We're currently relying on Auth0's `tms` claim to tell us which teams a user belongs to. In order to change a user's teams, we have to:

1) Update their `tms` on Auth0 using their Management API
2) Immediately re-issue them a new JWT, this time signed by _us_.

This puts us in the business of providing identity, and also results in non-atomic authorization updates.

Alternatively, I propose we move the source of truth regarding team membership to our own database. That way we don't have to sometimes be issuing our own JWTs.

We can implement an authorization flow whereby for a request lifetime we only check the DB once for any particular user's set of roles, and use that cached answer for the rest of their interactions. We'd have to take care of the scenario in which one process races to access some data while another process alters a user's role after roles were checked.

**Comment by jordanh** [comment]
Closing this discussion for now
