### ISSUE TITLE
Missing guidelines for ECMA6 (and React?) syntax support on Linux.

### ISSUE THREAD

**Issue by atannus** [ParabolInc/action#140]
This information helps people to get up and running faster on Linux.

* I'm not sure how much React overhauls ECMA.

**Comment by mattkrick** [comment]
Can you give some more info on this?
Syntax shouldn't be OS specific, rather it should come from the `.eslintrc` & then your editor/IDE should know what to do with that.
React is pure ES2015+, _except_ for JSX, which needs babel/typescript to transpile into pure JS.
JSX aside, it's all stage 2+, as can be seen here: https://github.com/tc39/proposals.

**Comment by atannus** [comment]
What I mean is when I open a .js file I expect to see it properly highlighted. Instead, all .js files in the src/ get flagged with parse errors. Standard text editors (nano, vi, kate, kwrite, gedit, etc...) were unable to properly highlight the files. Debian is notorious for being slow at adopting latest standards (e.g. Debian dev currently packages node 4.3), so support for ECMA6 is not there yet. Debian users are used to this and expect to find instructions on how to overcome these issues.

In my case it was: install Sublime 3 with Babel plugin.

Perhaps this is not important ATM, but it cost me a whole morning whereas a couple of lines in the README file would have made it a no brainer.

I'll take a look at how .eslintrc can help.

**Comment by jordanh** [comment]
@atannus, you're completely right. We need to add some documentation to the README to let folks know we're living on the JS edge. Otherwise, they'll be confused as all heck, just as you were.
