### ISSUE TITLE
Define application logging strategy

### ISSUE THREAD

**Issue by dan-f** [ParabolInc/action#1404]
## Issue - Enhancement

Let's come up with a strategy for capturing application logs securely and getting them into some sort of indexed system for reporting / support purposes.

https://www.owasp.org/index.php/Logging_Cheat_Sheet

@mattkrick

**Comment by mattkrick** [comment]
let's also include how to handle things from sentry.io in this, too.

**Comment by ackernaut** [comment]
Can close this discussion? Or defer to another milestone?

**Comment by dan-f** [comment]
I don't see it as part of a particular milestone yet. Rather than close it, can we just remove the `Epic 8` tag?

**Comment by mattkrick** [comment]
pushing to 8.5. I still _really_ want this, & sooner is better than later

**Comment by dan-f** [comment]
Yeah, I sketched out some use cases this morning and a potential API. Next step is to see what's out there that'd work for us.

**Comment by jordanh** [comment]
I'll do some research and let's continue the discussion

**Comment by jordanh** [comment]
I think this can be closed now
