### ISSUE TITLE
handle pause option for free accounts

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#1405]
we need a tooltip or maybe even hide the ability to pause for free accounts

**Comment by ackernaut** [comment]
You talking Active/Inactive toggle?

**Comment by mattkrick** [comment]
yeah! what are your thoughts? do we keep the toggle for the free folk?

**Comment by ackernaut** [comment]
I think it might be confusing for free folks. Perhaps we only show for billing leaders on the paid plan. Also we may find a way to add a tooltip and link to our pricing page where it explains with activity means and how it affects invoicing.

**Comment by mattkrick** [comment]
yeah, i could be up for that! 
i mean, it's only be available for billing leaders anyways, so it's not super high priority.
would you mind making a low fidelity design of whatcha got in mind?

**Comment by ackernaut** [comment]
So…I noticed one thing.

We soon will give folks a little estimated cost below the big button to upgrade to the Pro Plan.

![screenshot 2017-10-11 22 33 07](https://user-images.githubusercontent.com/307286/31478186-2b47f6de-aed4-11e7-9bb7-3aec37bf42a2.png)

They may be curious as to who is active and may think to look under the Members tab. So I was thinking we could keep the INACTIVE badges, but only show the toggle for the billing leader when they are on a paid plan. I would want to change the badge theme to the neutral gray to not be confused with the billing leader badge.

![screenshot 2017-10-11 22 32 06](https://user-images.githubusercontent.com/307286/31478177-17df30f8-aed4-11e7-8406-0ad1e84b427d.png)

**Comment by mattkrick** [comment]
_only_ the billing leader can see that page.
why do we have an inactive badge & an inactive toggle? can we just nuke the badge?

**Comment by ackernaut** [comment]
I was thinking they could have some context for who is active so they could make choices about their team(s) and plan.

So an alternative approach would be: show a passive element when FREE and show a toggle with PAID, but both indicate activity (once again for decision making).

**Comment by mattkrick** [comment]
just spitballing here:
- get rid of badges
- keep toggle since that now provides unique info
- for free folk either leave it as is or disable + pop a message if they try to inactivate to 

i'm thinking it'd be nice to keep the toggles around because they serve a secondary purpose of reminding the leader that they aren't PRO, but once they become pro, they won't be surprised by something new

**Comment by ackernaut** [comment]
I like keeping them for the learning and clarity. A disabled state is an option. A tooltip explaining what they can’t do yet is an option. I’ll make a note to yank the INACTIVE badge.

**Comment by mattkrick** [comment]
fixed in #1425
