### ISSUE TITLE
Clean up npm scripts

### ISSUE THREAD

**Issue by dan-f** [ParabolInc/action#1407]
## Issue - Enhancement

I think it'd be awesome to apply a bit of UX work to our npm scripts. In particular:

- I'd like to make them consistent in their handling of `NODE_ENV`. E.g. all of them obey `NODE_ENV`, or they're all named in terms of the `NODE_ENV` they use. (I prefer the former)
- I'd love to make it clear which scripts are developer-facing (e.g. do what needs to be done no matter the state of the working tree) vs internal helpers (e.g. help the developer-facing scripts do their work)

@mattkrick if ya have any thoughts, send 'em over!

**Comment by mattkrick** [comment]
our scripts could definitely use some love. Getting your fresh eyes on it is super valuable & I'd be happy to review a PR!
