### ISSUE TITLE
[object Object] is now facilitator bug

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1420]

**Comment by dan-f** [comment]
Adding a description:

Issue - Bug

When running a meeting, and when the facilitator drops out of the meeting for some reason, a notification is shown with the copy `[object Object] is now the facilitator`.

OS: macOS
Browser: Chrome
Node version: production version as of 10/17/2017
NPM version: production as of 10/17/2017
RethinkDB version: production as of 10/17/2017
Estimated effort: 12 points

**Comment by mattkrick** [comment]
fixed in #1460
