### ISSUE TITLE
dig into multiple tab use on presence

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#1421]
When a user is in the meeting (agenda processing) on one browser tab and on their dashboard on another tab, there may be a “User and User are editing…” message on the same card.

**Comment by mattkrick** [comment]
this is the "terry & terry is editing..." bug. deferring for now

**Comment by ackernaut** [comment]
deferring for now

**Comment by mattkrick** [comment]
had to handle editing differently for relay, fixed in projects-to-relay.
