### ISSUE TITLE
#private bug

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#1422]
## Issue - Bug

this #private card created during Agenda Processing, isn't #private 
![private](https://user-images.githubusercontent.com/14892189/31685552-5a402106-b351-11e7-8ea0-5e33d182691e.jpeg)

**Comment by tayamueller** [comment]
interesting--I was able to fix this by going back & manually clicking then selecting "private" from the pop-up. This is clunky & was not what I expected from the feature. (can't tell if this is an actual bug or intentional)

**Comment by mattkrick** [comment]
this is caused when you don't use the autocomplete. if text matches but autocomplete isn't selected, then let's make it a tag anyways.

**Comment by mattkrick** [comment]
we're gonna need to redesign how we handle tags in epic 12 because we'll be allowing for custom tags then. let's tackle this then.

**Comment by jordanh** [comment]
@mattkrick is this still an issue?

**Comment by jordanh** [comment]
If so, can you please add estimated effort to fix?

**Comment by mattkrick** [comment]
still an issue, 11 points

**Comment by jordanh** [comment]
Probably stuck behind switching editors. But, adding to Sprint Board

**Comment by jordanh** [comment]
Iceboxing, should tension resurface we'll reopen
