### ISSUE TITLE
New Team form: Improve fields for invitees by email

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1426]
### Acceptance Criteria
- A prototype is designed that explores the items in the checklist below (original thoughts that can be updated as part of the design process)
- The prototype is tested internally and externally
- A next-steps issue is written, either hi-fi design or implementation

**Checklist**: the invitee by email field…
- [ ]  assumes that the user has chosen the right organization if at least one of the emails is already a member of the org.
- [ ] notifies the users with a hint box (TBD) that there are users who are not members and will require Billing Leader approval.
- [ ] notifies the user when there are no recognized user emails (for that org) and suggests maybe creating a new org
- [ ] check for emails that trigger hint on key up (and show the hint)
- [ ] mock up hint boxes for validation tips (approval, new org)
- [ ] bonus points: mock up hint box for duplicate team name
- [ ] bonus points: (perhaps separate issue) adding DraftJS and autosuggest menus that include existing org members as user is typing emails

- **Estimated effort:** 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
@ackernaut is this still relevant? Is it a design issue? What is the EE?

**Comment by ackernaut** [comment]
I’m not sure we will get to this any time soon, it is a high level of polish for the UI/UX in place, but I did update it. Let’s call it safe to icebox.
