### ISSUE TITLE
Org dropdown list has conditional Pro™ badge

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1427]
## Enhancement

- [ ] The organization dropdown menu has a Pro™ badge by the organizations that are Pro™.

**Estimated effort**: 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
moving to epic 8, can push back to snooze if we dont have time.
