### ISSUE TITLE
Agenda input considerations

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1428]
## Enhancement

- A label can be used as a visual placeholder, whereas a true placeholder can be accessible.
- A label and/or placeholder could have either an explicit action “Do this thing” or an example “this example thing” depending on the context / UX.
- Consider updating the icon (perhaps a comment bubble?) and perhaps taking it out of the input.

**Deferring any bigger design changes** until the UI Updates epic is scoped and underway.

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
@dan-f I know some of these are probably just good general considerations, but want to start building up the thinking. I like the extra attention to accessibility, beyond the “typical” UX considerations that are made.

**Comment by jordanh** [comment]
Scrubbed today. @ackernaut still relevant? Safe to close?
