### ISSUE TITLE
Assignment or mention notification v1

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1430]
## Enhancement

**JBTD**:

_When working asynchronously outside of a meeting, users want to be notified when they are assigned as the owner of a new outcome card, or at-mentioned in an outcome card, so that they can be aware and take next steps toward the outcome of the card._

**UI details**:

- Notification copy (a or b):
  - “**UserName** _has assigned you a project for TeamName_:”
  - “**UserName** _has mentioned you in a project for TeamName_:”
- Card content:
  - Shows status by color
  - Shows latest content including formatting, no truncation
  - Can support #private (assigner creates content with private _then_ switches to new owner)
  - Links are tappable
- Has a ✔️  button that clears the notification.
- Can be cleared by the “Clear All” button.
- v1 has a button to simply “See Board” routing to the team board where the card lives. We are embarrassed and ashamed because the user has to find the card on the team board.
- v2 (captures in issue #1476) has a button to “See Project” where we route to team dashboard, and the project column scrolls to and highlights the project card. We will do this in E8 if we have time. We are embarrassed and ashamed because there may be an extra step to prioritize the work.
- See [latest logic flows](https://github.com/ParabolInc/action/issues/1430#issuecomment-343290952)

[ 👀  internal team see [Figma](https://www.figma.com/file/gUU2VeOEIziFw7Bd3GAmyc0S?utm_campaign=team&utm_source=slack&utm_medium=message&utm_content=file_comment#405467) ]

**Estimated effort:** 18 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
@mattkrick I’m wondering if for the first pass we don’t try to show the latest content, but it could be slick in the long run if it supports a real UX story. My thinking in checking for latest content is since we don’t have a link to a card back, then I would want the notification to be as accurate as possible.

**Comment by ackernaut** [comment]
the details say “task” but this language has yet to be decided…it would probably be more consistent to use “project” in the current UI implementation.

**Comment by mattkrick** [comment]
OK so let's lay out the flows:

From the meeting:
- no notifications sent

At the end of the meeting:
- notifications sent to all users who were not present

On a dashboard
- notifications sent to the new owner

From an integration (ie changed owners on github, future spec)
- notifications sent to the new owner

@ackernaut @tayamueller does that conform to spec?

When a notification is created:
- remove all other notifications for that card, if any
- send the new notification to the new owner

**Comment by ackernaut** [comment]
> **Possible ideas for throttling / clearing notifications**:

- Delay sending 5-10 seconds because the user may have tapped the wrong person in the assignment menu and/or unknown other nuances.
- If the card gets reassigned, automatically clear the notification from previous owner’s bell box.
- Pop up a little modal: “Notify so-and-so?”
- If the project is archived, automatically clear the notification?
- User can only have **1** outstanding task notification in bell box per outcome (in case of some weird back-and-forth assignment behavior)
- Other ideas?

**Comment by ackernaut** [comment]
>I argue that See Board should route to My Dashboard allows me to prioritize my work.

**Comment by mattkrick** [comment]
- let's say i change the mention from `@terry` to `@matt`. I'd have to remove terry, and his notification, and add a notification for matt. Same thing if i get booted from a team, all my team-related notifications should go away. Since we have to do that diffing procedure, we might as well do it all the time, so i don't see a technical reason to throttle.
- for now, let's veto the confirmation. if it gets annoying we can scale back or add one in, either on the sender or receiver.

@ackernaut can you confirm that the logic in the comment above (https://github.com/ParabolInc/action/issues/1430#issuecomment-340846327) is correct?

**Comment by ackernaut** [comment]
@mattkrick 

- Are you saying that unread notifications automatically go away (for original owner/mentionee) when the owner is changed, or the mention is changed/removed? If so, I say YES, confirmed!
- Yep, let’s ignore the confirmation idea for now.

**Comment by ackernaut** [comment]
@mattkrick @tayamueller 

**Updated flows!**

During the meeting:
- a user receives project notifications when assigned or mentioned and is marked as “not present” at the time the assignment/mention occurs

On a dashboard:
- project notifications are sent to the new owner or mentioned teammate

When a project assignment notification is created:
- remove all other assignment notifications for that card, if any
- send the new notification to the new owner

When a user has a mention notification, but the mention is later removed, automatically remove the notification.

If a user is both assigned and mentioned, then the assignment notification takes precedence.

Remove the un-cleared project notifications if the project is later archived.

When removed from a team, also removed uncleared project notifications related to that team.

UX Note: We are erring on the side of accuracy/clarity/signal-over-noice opposed to activity/history/more notifications.
