### ISSUE TITLE
Option to leave/hide organizations

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1431]
## Enhancement

I’ve left a lot of teams created under other users’ organizations (demos, user testing, batting practices, etc.).

I see a long list on the Org dropdown on the New Team form. It’s not ideal.

Should we give users the option to leave an org they don’t own, perhaps a 2nd list of organizations under user settings?

**Concept**:

User > Organizations

**List one**: My Organizations
**List two**: Organizations I belong to (with the option to leave or hide (like soft deleting/archiving) Orgs where you are not on a team)

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
@tayamueller would probably especially appreciate this one. :)

**Comment by jordanh** [comment]
Already implemented, but bug exists. See #1956 and #2115
