### ISSUE TITLE
flavor our verification emails

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#144]
This ain't us
![screen shot 2016-08-02 at 9 22 38 pm](https://cloud.githubusercontent.com/assets/5514175/17353729/57c6005e-58f7-11e6-82cc-e0840185f72c.png)

**Comment by jordanh** [comment]
Oh, duh. Yeah. @ackernaut is this something you can look into?

**Comment by jordanh** [comment]
Definitely still have to do this before wrapping up the beta epic. Be a nice thing to knock down.

**Comment by ackernaut** [comment]
Ok, will consider it as we prioritize next smaller enhancements alongside our weekly sprints.
