### ISSUE TITLE
Add functionality for those without websockets

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#1440]
It happened! We finally got a client who has an IT department that disabled websockets.
For me, this makes me want to prioritize the switch from cashay to relay. The way I'm writing the relay implementation is so websockets are optional (for everything but meetings). 
we should also pop a toast if websockets are not working.
@jordanh looping you in because this is the largest prospective client we've got & we'll need to fix this if we want the big fish.

```
https://www.gravatar.com/avatar/6c068283c931d95b2bed46afc03bc0d3?d=404&s=160 Failed to load resource: the server responded with a status of 404 (Not Found)
32_7e92a3cf9e00d565afde.js:15157 WebSocket connection to 'wss://action.parabol.co/socketcluster/' failed: Error during WebSocket handshake: Unexpected response code: 200
raven.js:321 Uncaught SyntaxError: Failed to execute 'insertRule' on 'CSSStyleSheet': Failed to parse the rule '@keyframes keyframe_zw20ua{0%{transform:rotate(0deg);}100%{transform:rotate(360deg);}}'.
console.js:26 Unhandled promise rejection Error: query was found in the query response, but not the request.
  Did you optimistically add more fields than you originally requested?e.(anonymous function) @ console.js:26
122_7e92a3cf9e00d565afde.js:15157 WebSocket connection to 'wss://action.parabol.co/socketcluster/' failed: Error during WebSocket handshake: Unexpected response code: 200
https://www.gravatar.com/avatar/6c068283c931d95b2bed46afc03bc0d3?d=404&s=160 Failed to load resource: the server responded with a status of 404 (Not Found)
52_7e92a3cf9e00d565afde.js:15157 WebSocket connection to 'wss://action.parabol.co/socketcluster/' failed: Error during WebSocket handshake: Unexpected response code: 200
```

**Comment by jordanh** [comment]
Let's see if we run into this again. At a minimum, we should add an error message informing the user that websockets are unavailable (is it your firewall?)

**Comment by jordanh** [comment]
I just ran into this again with a user in France. Transcript from the support case is at: https://olark.com/transcripts/show/yK3T9lIS7o6b1xR07I2zB0V92JE4rdBB

Suggest we do two things:

1. Pop a toast on a WebSocket connection error
2. Send a Segment event so we can get a better handle on the number of users affected

**Comment by mattkrick** [comment]
@dan-f fixed this one in sprint 1.
