### ISSUE TITLE
Flush all clear-able notifications

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1441]
## Enhancement

**JTBD**:

_When on a humming, highly active team, users want controls to batch process notifications (mark read, etc.)…
**…so that** they can mark multiple notifications as read
**…so that** they can quickly clear their notifications down to the ones that require more considered action (approve a new org member, join a team, etc.)
**…so that** they can quickly get back to the real work, not the meta work._

**UI details**:
- With a single tap on “Clear All 🚽  ” at the top right of the panel, all notifications that can be cleared will be cleared. [See Figma](https://www.figma.com/file/gUU2VeOEIziFw7Bd3GAmyc0S?utm_campaign=team&utm_source=slack&utm_medium=message&utm_content=file_comment#405467) (We jokin’ ‘bout dat toilet!)

**Data**: Needs a migration to add clear-able `boolean` to notifications.

**The notifications that can be cleared**:
- User rejected with reason
- Team was archived
- User was approved and an invitation sent
- You are now billing leader
- New: assignment notification
- New: mention notification

**Estimated effort**: 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
i'm not a fan of this at all. I don't want a list of checkboxes. that's not fun.
so we have 2 types of notifications:
- those that require action
- those that don't

we could
- break them into 2 lists AND/OR
- have a "acknowledge all" button that clears everything that doesn't require action (like github)

**Comment by ackernaut** [comment]
@mattkrick yeah I like your 2nd bullet point and that is what is in the latest design “Mark As Read” for all non-actionable types.

**Comment by dan-f** [comment]
What's an example of a notification that's not clearable? Does that mean it lives in my inbox forever?
