### ISSUE TITLE
Accepting invite by email for new user fails intermittently

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1453]
## Bug

While on staging after Epic 7 shipped, I had an issue when accepting a team invite via email with a +hack Gmail address that wasn’t used for a Parabol user yet.

Will add console messages when I reproduce. Kind of looked like this:

1. Get the team invite email.
2. Copy the link and paste in a private browser session.
3. At first I see ducks, then the auth0 modal.
4. I create a new user, but don’t get sent to the team that I was invited to.
5. When I try to use the invite URL again, I get the expired invitation message.
6. I had to go to the `/welcome` route to make any progress with the new user.

**Estimated effort**: XX points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Please check it again. I have also seen users talk about issuing multiple invites and not being clear why invitations expire.

**Comment by jordanh** [comment]
Should be resolved by #1799
