### ISSUE TITLE
Redirect fails intermittently when creating new team + new org

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1454]
## Bug

When creating a new team with a new org, sometimes the redirect doesn’t work and I get stuck with the loading ducks. This is intermittent and we think it is race condition and has to do with web sockets.

I will add web socket logs here when I reproduce again.

1. Go to the New Team form.
2. Select the radio button for a New Organization.
3. Complete the form.
4. Do you see the new team or ducks when the app redirects?

**Estimated effort**: XX points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Please check to see if this is still a thing. Else, let's close.

**Comment by mattkrick** [comment]
`addTeam` has been completely rewritten & nothing fires until a message comes back from the server. Fixed in #1576
