### ISSUE TITLE
cant click link on  archived card

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#1458]
use case:
- i wanted to go to the epic 8 spec
- i knew terry had a link on a card, so i went to the archive to click it
- i can't click the link because it's read-only unless i unarchive

workaround: unarchive, click, rearchive

better options:
- make archive cards editable
- make archive cards editable, but don't persist changes
- If the content is `readOnly`, can we render a basic link that opens in a new tab opposed to the editable link module?

cases:
- archive
- read-only outcome content in project notifications (assignments/mentions)

**Comment by ackernaut** [comment]
make links in archive card content clickable??

**Comment by ackernaut** [comment]
If the content is `readOnly`, can we render a basic link that opens in a new tab opposed to the editable link module?

**Comment by jordanh** [comment]
Related / dup of #1364

**Comment by mattkrick** [comment]
closing in favor of #1364
