### ISSUE TITLE
Sentry error - `error`

### ISSUE THREAD

**Issue by dan-f** [ParabolInc/action#1459]
I'd love to figure out what's going on with our most frequent sentry error. It's just got the message "error", which is not particularly useful, and the stack trace doesn't reach our app code.

Sentry includes a [breacrumb](https://docs.sentry.io/learn/breadcrumbs/) implying that the error may be occurring when trying to POST to the Segment API, which can happen if you have an adblocker installed.

https://sentry.io/parabol/action-production/issues/329031181/

```
Stacktrace (most recent call first):

  at captureException (../node_modules/raven-js/src/raven.js:372:1)
  at wrapped (../node_modules/raven-js/src/raven.js:324:1)

error
```

**Comment by jordanh** [comment]
If this becomes an issue in the future, let's dig into it a bit more.

**Comment by jordanh** [comment]
@dan-f triaged, root cause is still unknown
