### ISSUE TITLE
Do not encode the client secret to base64 by default

### ISSUE THREAD

**Issue by jkbowa** [ParabolInc/action#1461]
## Issue - Enhancement

From Dec 2016, Auth0 no longer offers base64 encoding for client secrets. The existing secrets will however remain that way, but the newly generated strings wont be base64 encoded. I think by default we shouldn't encode these strings to base64 as to maintain out of box functionality.

**Comment by jordanh** [comment]
auth0 actually offers a config option to supply secret with or without base64 encoding. Closing this for now.
