### ISSUE TITLE
When I am processing an agenda item I want to defer, I want to reorder it

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1463]
## Issue - Enhancement

When the facilitator advances the meeting to an agenda item they'd like to defer, we presently don't allow the _current_ agenda item to be reprioritized.

MS from iMatter has requested that we fix this

### Acceptance criteria
- As the Facilitator, if I wish to defer the agenda item currently being processed I:
   - Drag it to a lower position in the agenda list
   - When I release it, the next highest agenda item becomes the current item

- **Estimated effort:** 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
requires refactored action meeting, closing
