### ISSUE TITLE
Fix auto-update "createdAt/updatedAt" card headers

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1464]
per-second resolution feels bad (updated 41 seconds ago)

### Acceptance criteria

instead, let's be more generic:
- < 10 seconds = "just now"
- < 30 seconds = "seconds ago"
- < 60 seconds = "less than a minute ago"
- cards created 6.5+ days ago round up to 1 week

**Comment by tayamueller** [comment]
recommend just one: 

< 60 seconds = "just now"

(guessing folks don't have a need to mark time less than 1min increments)

**Comment by jordanh** [comment]
@ackernaut taking a card to see if this is still a thing

**Comment by ackernaut** [comment]
Yes, this is still a thing.
