### ISSUE TITLE
Capture more granular meeting data

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1465]
- time spent on each stage of meeting
- who assigns projects to whom
- changes in ownership

**Comment by ackernaut** [comment]
@mattkrick looks like we have a game plan for the first bullet, I’m guessing the other 2 are important when we want to start visualizing trends between roles/teams, etc. Should we close this for now?

**Comment by mattkrick** [comment]
sure, we already capture the 2nd and 3rd bullet today via the createdBy and projectHistory.
