### ISSUE TITLE
Social Check-Out Round

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#1468]
## Issue - Enhancement

Observed positive effect of a rapid-fire Social Check-Out Round to close the meeting.

*wire so that Facilitator always goes last, with reminder to End Meeting.

### Acceptance Criteria
- A lo-fi prototype is created and tested internally, externally
- An issue is written for next steps, either hi-fi design or implementation, depending on outcome of this issue

- **Estimated effort:** 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
I like this! I think it would also make for a nice option that could be customized via team meeting settings in the future.

**Comment by jordanh** [comment]
Could be added as a configuration option or a Pro feature.

**Comment by jordanh** [comment]
@tayamueller can you please draw up some pen and ink designs for this? Is this round optional (and controlled by a team setting) or is it required? If it's required, can my team skip it?

@ackernaut, when the above is complete could you please add estimated effort to draw up hi-fi designs?

**Comment by jordanh** [comment]
Scrubbed, needs AC.

**Comment by jordanh** [comment]
Iceboxing during scrub. We'll probably stack this behind updating Action meetings to the new meeting format.
