### ISSUE TITLE
Stuck because <dependency>

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#1469]
## Issue - Enhancement

Our own use & user research suggest that a dependency is useful for cards in the Stuck column. See Parabol boards for examples

### Acceptance Criteria
- A target UX is described in writing
- Design uncertainty level 3: lo-fi designs are created and checked internally and externally to validate a first phase of the target UX
- Hi-fi design issue created

- **Estimated effort:** 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
I'm a big fan of this idea. @tayamueller this issue needs some acceptance criteria. How will we know it's done? Is it a set of lo-fi designs we can validate? Hi-fi designs we can execute on?

@ackernaut, once it's spec'd a bit more, please add estimated effort

**Comment by jordanh** [comment]
Scrubbed, needs acceptance criteria.

**Comment by jordanh** [comment]
Scrubbed 3 times, iceboxing by policy.
