### ISSUE TITLE
Switching users leads to cache badness

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#147]
## Issue - Bug

Take the following steps:

1. Login as one user ("user1"), peruse the dashboard
1. Logout
1. Login as a different user ("user2"), ideally with different team memberships
1. Note that user2 lists user1 team memberships. Uh-oh!

Perhaps we should completely invalidate the persisted store if the user id changes?

- **OS:** OSX
- **Browser:** Chrome
- **Node version:** v6.2.0
- **NPM version:** 3.8.9
- **RethinkDB version:** rethinkdb 2.3.4 (CLANG 7.3.0 (clang-703.0.31))
- **Estimated effort:** 2 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))(https://docs.google.com/document/d/1lgTJnJzBt9-4If883iOvthmc0hy-6C6hBF7KNN-lsXU/edit))

**Comment by jordanh** [comment]
As I thought through this, I realized a few things had to happen:

- We must detect when the user id changes (which will happen on a prop transition via redux)
- We must be able to wipe the redux store
- We must be able to restore the auth token in the new store

So, @mattkrick a modest design proposal for you. 

1. Create a new sync function in `makeReducer.js` called makeInitialReducer() that creates a new, clean reducer
1. Extend the `RequiredAuthAndRole` by adding cWRP method to detect a change in user.id, if this occurs
1. Call `makeInitialReducer()`
1. `dispatch(setAuthToken(authToken))`

How do you think that looks?

**Comment by mattkrick** [comment]
I think it should be much simpler--
logging out should wipe everything. There is PII cached in localStorage & a logout has the expectation that it will be removed.

**Comment by jordanh** [comment]
Ah, of course, you are correct.

You ok with `makeInitialReducer()` as a call? I can invoke it from the `/logout` route.

**Comment by mattkrick** [comment]
If we did that we'd need an `INIT` for each reducer, right? Or at least a piece of middleware to wipe everything.
Why not `localStorage.removeItem('Action')`?

**Comment by jordanh** [comment]
Yes. Why not? Mostly because I am ignorant of the interface for localStorage and/or when it's okay to cross the redux-storage interface boundary.

**Comment by mattkrick** [comment]
You know, it'd be a good PR.
Right now, it has a LOAD and SAVE action. makes perfect sense to have CLEAR as well.

**Comment by mattkrick** [comment]
https://github.com/michaelcontento/redux-storage/issues/150

**Comment by jordanh** [comment]
Working here: https://github.com/ParabolInc/action/pull/157
