### ISSUE TITLE
Better communication of purpose in project assignment UI 

### ISSUE THREAD

**Issue by dan-f** [ParabolInc/action#1470]
## Issue - Enhancement

As a new user, I want to know how to assign a card to a teammate. I find the current assignment UI for cards unclear in a few ways:

- When I am looking at a card, I see a name and a profile icon at the bottom. I don't know why this name and profile icon are there. Did this person _make_ the card? Are they currently _working_ on the issue? Is it on _their_ board?
- When I hover and click on a username/icon, I see a dropdown of my team members with no additional copy. I now see that the name probably isn't the creator. I am probably changing the name that will appear at the bottom of the card. But what does this have to do with the card more generally?

- **Estimated effort:** 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
"Assign to:" or "Owner:" label could be added to dropdown list
