### ISSUE TITLE
changing the team of a card/s

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#1474]
## Issue - Enhancement

Users need to be able to quickly change the team of a card when they:
- have expanded in size or scope & need to start a new team
- create a card related to an issue elevated in Team A's meeting, but it's intended for Team B
- have a recurring item (often admin) that needs to be assigned to teammate son multiple teams

### Acceptance Criteria
- On My Dashboard clicking the team in the lower left of a Task opens up a Team assignment menu
- The menu lists every team the user is a part of, except the team the card is currently in
- Clicking a team reassigns the card to that team
- Mentionees that are not a part of the new team have their mention & mention notification removed
- Mentionees who are part of the new team have their notification updated
- trying to change teams for a project belonging to someone else results in a server error
 
- **Estimated effort:** 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by tayamueller** [comment]
I'd like to reassess the value/priority of this Enhancement, with new insight:

(From an onboarded user considering adoption for an internal team AND for use with clients:)

When a corporate user wants to use Parabol for both internal team mgmt AND for external client mgmt, they need to be able to reassign cards created during Team meetings to Client Dashboards. 

> "We want to have 1 call [meeting] for our internal team, that creates work across all of our client teams. Can we set each customer project up as a team and then do an internal call where we review ALL customer projects?"

When queried, this user agreed that "assign card to different team" would get him what he needs.

**Comment by mattkrick** [comment]
@tayamueller tackling this now

**Comment by mattkrick** [comment]
SPEC

FRONTEND
- On My Dashboard, you seen the team on the outcome card. clicking it opens a menu that shows all the teams that you are on.
- Clicking a team reassigns it to another team

BACKEND
- change the teamId, assigneeId, updatedAt, fields
- Change the teamId on the projectHistory. NOTE: we'll need to think extra hard about what permissions are required for this later, but for now, we don't even do stuff with project history, so it doesn't matter
- use a new `ChangeProjectTeam` mutation.Although the mutation is pretty simple & could fit easily into `updateProjectMutation`, we may want to listen for this event specifically & it'll be nice to be explicit

**Comment by mattkrick** [comment]
@tayamueller if you mentioned me in a card like `@matt` and then moved that card to a team i wasn't a part of, what would you want to happen?

**Comment by mattkrick** [comment]
from slack-- if moved to a new team & that mentionee doesn't exist on the new team, we remove the entity, but the text stays.
