### ISSUE TITLE
Meeting phase prompts for first meeting

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1475]
When a team meets for the first time, they want conditional prompt language so that they can have a productive/helpful/delightful first meeting. A simple example of prompt language that doesn’t make sense: “since last meeting” This may also relate to empty states when new teams may not have projects.

**Comment by ackernaut** [comment]
@tayamueller how does this sound as a Solo Updates prompt when it is the very first meeting?

I’d like to find an easy, first update for the prompt when it is the first meeting. We could show different text for the current user giving updates (and can add cards to their own board), versus the rest of the team.

I could get probably get this out in the next batch of updates since I am working on meeting prompts. I also want to work on #1535 

```
Name, _what are you working on now_?
(Add cards to track your work on your dashboard.)
```

**Tagline when you can add cards**: (Add cards to track your work on your dashboard.)
**Tagline when it is not your round**: (Add agenda items to discuss next tasks or projects.)

Alternatively (because it could be a new team with a new project cycle):

>Name, _what are your first tasks on this team_?
>Name, _what are you working on next on this team_?

**Comment by ackernaut** [comment]
@mattkrick should I be able to get the `meetingNumber` with the query found in `MeetingContainer`?

**Comment by tayamueller** [comment]
related to #1208

**Comment by mattkrick** [comment]
@ackernaut yep! if you base it off the projects-to-relay branch, you'll be super delighted with how easy it is to do that :-)

**Comment by ackernaut** [comment]
ok! I’ve been branching off of `epic8.5` — will your relay branch merge to `epic8.5`? (and thanks for the quick response!)

**Comment by mattkrick** [comment]
yeah, i'll merge it in the next hour

**Comment by ackernaut** [comment]
🔥

**Comment by ackernaut** [comment]
going to get this in along with #1535 with 8.5

**Comment by ackernaut** [comment]
The latest here:

Instead of making assumptions about first meeting or not, we (Matt and I) have taken a first pass at having UI copy that reflects whether or not a user has cards on the board:

No cards: “_NAME, what are you working on_?”
Has cards: “_NAME, what’s changed with your tasks_?”

Additionally, as seen on #1582 

Not here, no cards: “_What is NAME working on_?”
Not here, has cards: “_Any updates with NAME’s tasks_?”
