### ISSUE TITLE
Scroll to and highlight card on dashboard

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1476]
## Enhancement

When I see a notification that I have been assigned to or mentioned in a project card, I want to tap a button that allows me to see the card on the appropriate dashboard.

- [ ] Routes user to team dashboard (or single kanban filtered by team in the future). We are embarrassed and ashamed if and when they have a hard time prioritizing their new card. The card will be scrolled to and highlighted as following…
- [ ] Tapping the backdrop returns to normal viewing mode at the same scroll position
- [ ] Tapping into the card returns to normal viewing mode at the same scroll position, with the card in it’s normal focused or editing state (depending on where the user taps).
- [ ] [See Figma for a design concept](https://www.figma.com/file/UajHtvdJi2AtTHjK8CURUuq8?utm_campaign=team&utm_source=slack&utm_medium=message&utm_content=file_comment#367940)

**Note**: This is low priority for Epic 8. If we run out of time, we will simply send users to the appropriate board.

**Estimated effort**: X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
May be obsolete when cards/card backs have URLs. We'd raise that instead.

Closing for now.
