### ISSUE TITLE
Establish TTLs for persisted cache

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#148]
## Issue - Enhancement

Just a placeholder for now. Let's propose a global TTL for the cashay's data and TTLs for specific queries.
- **Estimated effort:** 3 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
this may sound crazy, but hear me out--
the queries obey the document-level TTLs and should refetch whenever a single doc goes stale.

That way, i don't have to know what the query contains, since query-refetching is more or less a computed value based on the established TTL.

**Comment by jordanh** [comment]
That doesn't sound crazy at all. Will implementing this require a cashay enhancement?

**Comment by mattkrick** [comment]
i don't think so, i think i'll just have to read up on where the graphQL annotation PR went. i know something got merged, i'm not sure how useful it is yet.

**Comment by mattkrick** [comment]
implemented in our own custom QueryRenderer in relay.
