### ISSUE TITLE
change pencil icon in Social Check-In

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#1481]
## Issue - Enhancement
Both new users onboarded this week got stuck on this & didn't know how to move forward without prompting: "I thought I needed to write my Social Check-In response because of the pencil icon"

![adrienne tell your teammates](https://user-images.githubusercontent.com/14892189/32680150-58756e64-c637-11e7-99c8-822be3c95bf4.jpeg)

suggestion: change to a lightbulb, exclamation point, nerdface, etc?

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
I was wondering when this would happen. One idea: perhaps we only let the facilitator change the question to reduce confusion? Other ideas?

**Comment by mattkrick** [comment]
- change the icon
- remove the icon
- make the tooltip only appear on the icon, not the text

**Comment by tayamueller** [comment]
Make the icon visible ONLY to the Facilitator; also see #1482

**Comment by mattkrick** [comment]
in addition to only showing this to the facilitator,
@ackernaut any recommendations on how to remedy? you like any of the 3 options i presented?

**Comment by ackernaut** [comment]
@mattkrick I’m willing to go with option no. 3 — scope the tooltip to the icon only, not the text.

**Comment by ackernaut** [comment]
@mattkrick curious, are you working on this issue? is so, mind updating the assignee? otherwise I’d be happy to work on it.

**Comment by ackernaut** [comment]
@mattkrick I’ve started working on this issue.

**Comment by mattkrick** [comment]
ah good deal! nope, never started on it, that's all you!
