### ISSUE TITLE
Social Check-In prompts

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#1482]
## Issue - Enhancement

When unguided, new users are experiencing confusion at the Social Check-In prompts.

CURRENT: [see image]

SUGGESTED COPY EDIT:
  Hello, Adrienne:     **[add colon]**
  What are you cooking next?   **[make pencil icon visible ONLY to Facilitator]**

  (Share with your teammates!)                   **[view for 1 user; add parens]**
  (Waiting for Adrienne to share with the team...)            **[view for other teammates; add parens]**
   
related to #1481 

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by tayamueller** [comment]
![adrienne tell your teammates](https://user-images.githubusercontent.com/14892189/32680378-5c0c848a-c638-11e7-8285-8f2f0cdef378.jpeg)

**Comment by jordanh** [comment]
Adrienne tried to type because she saw a pencil. Adrienne thought, "why is it telling me to share with the team?" It should be an instructional prompt for _that_ person.
