### ISSUE TITLE
no nerd face on PC

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#1483]
## Issue - Bug

When a user is using a PC (?) the nerd face emoji appears as a grey box:

![no nerd face](https://user-images.githubusercontent.com/14892189/32680489-e92f10d0-c638-11e7-8823-89cbc9bbbbf1.jpeg)

SAD.

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Can we get details on browser and OS version?

**Comment by tayamueller** [comment]
Chrome on Windows7

**Comment by jordanh** [comment]
**Estimated effort:** 11 points

**Comment by jordanh** [comment]
Iceboxing via policy
