### ISSUE TITLE
Team Agenda Wrap-Up

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#1484]
## Issue - Enhancement

When unguided, users are frequently confused at the "Agenda Wrap-Up" screen. When queried,
 it is not clear to them that this is a "last call".

**CURRENT COPY:**
[see image]

**SUGGESTED COPY CHANGES:**
  
Last Call:*
We worked on [X] Agenda items so far**--need anything else?
Waiting for [Facilitator/you***] to move on...****     

*to imply opportunity to continue--"this is not the last step"
**to emphasize opportunity
***Facilitator should see "Waiting for you to move...." so they don't forge to End Meeting
****use "move on" to indicate a) there may be more b) gentle prompt to move forward to End Meeting which is still frequently skipped

![last call](https://user-images.githubusercontent.com/14892189/32680989-53f40130-c63b-11e7-917e-c199eff65d21.jpeg)

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Folks are also forgetting to end the meeting. An opportunity exists to try something to make this better when addressing this issue.
