### ISSUE TITLE
Agenda & Agenda Processing sprint part 1

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#149]
When a lean, mean team wants to surface ideas, tensions, needs, etc. they need an Agenda round so they can capture Actions and Projects with clear Owner-ship.

UI views for Agenda round:

- **First call**: a prompt to capture Agenda Items
- **Agenda item**: initial state with the ability to capture Actions and Projects (`CreateCard`)
- **Agenda item**: processing using the `OutcomeCard` component
- **Last call**: a status on progress (# Agenda Items, # Projects, # Actions) and a prompt to surface any new agenda items

**Estimated effort**: 3 points

**Checklist**:

- [x] A user can tap or press “+” to add an agenda item to the placeholder list in the left navbar.
- [x] A user has an inline text field when tapping the “add link” or pressing “+”.
- [x] An agenda item placeholder can be deleted on hover if it is not current or processed.
- [x] A user can click on the description of the placeholder to navigate to that agenda item.
- [x] Module can handle routes to first-call and last-call views.
- [x] First-call view can navigate to first agenda item.

**Out of MVP scope**?

- Keyboard shortcuts for cards?
- Help text (that can be toggled) under meeting section heading (“Whatcha need?”)?
- DnD Agenda Item placeholders
- Bertie and/or left navbar countdown timer for any sections?

Latest UI design concepts:

![01-agenda-first-call 2x](https://cloud.githubusercontent.com/assets/307286/17368814/4dc8f980-595b-11e6-8165-f921da5811a3.png)
![02-agenda-item-initial 2x](https://cloud.githubusercontent.com/assets/307286/17368816/4dca85b6-595b-11e6-9b1d-5b3449a99e24.png)
![03-agenda-item-processing 2x](https://cloud.githubusercontent.com/assets/307286/17368817/4dd18e42-595b-11e6-9397-7d091ae160d1.png)
![04-agenda-last-call 2x](https://cloud.githubusercontent.com/assets/307286/17368818/4ddeb5f4-595b-11e6-85ca-fc830f32ccf4.png)

**Comment by jordanh** [comment]
Bertie and DnD are def. out of scope for now.

**Comment by ackernaut** [comment]
Hehe, I realize that the “End Meeting” button is a single item on the checklist, but is a weighty amount of effort.

**Comment by jordanh** [comment]
This sprint could "End Meeting" without summary. I think that would be more than fine.

**Comment by ackernaut** [comment]
I can definitely see how “End Meeting” functionality may be partially or complete done in the Summary sprint—so we could scratch that from this sprint if we want. I can just get the button and layout in order.

**Comment by jordanh** [comment]
The fun starts here: https://github.com/ParabolInc/action/tree/agenda-sprint-part1
