### ISSUE TITLE
View archive from My Dashboard

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1491]
## Issue - Enhancement

When a user wants to see what they've archived from My Dashboard (perhaps they mistakenly archived a card), they want to access their Project archive from within My Dashboard, so that they don't have to browse to each team to find the archived Project card they are looking for.

Suggested by user Larry. Will additional user requests for this feature.

- **Estimated effort:** 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
I think this will be revisited during “New UI” because we should be able to filter the single kanban by tags including archived. Going to move it to that Epic for now.

**Comment by jordanh** [comment]
Agreed!

**Comment by jordanh** [comment]
Closed during scrub in favor of New UI. @ackernaut to create/refine good first step forward.
