### ISSUE TITLE
Empty outcome content in assignment notification

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1495]
## Issue - Enhancement

Seeing empty outcome content is most likely confusing. We should catch this state of not having content before showing a notification.

Steps to reproduce:

1) Create a card with user A, but do not add content.
2) Assign it to user B before creating content.
3) User B will get a notification with empty content.
4) User A can then add content and user B’s notification will update. The toast shows for both instances, the empty notification and the updated notification with content.

**Assigned with not content**:
![screenshot 2017-11-16 12 22 50](https://user-images.githubusercontent.com/307286/32910686-89966088-cacf-11e7-8f7d-6ed0a4dca88e.png)

**Then the user adds content**:
![screenshot 2017-11-16 12 23 02](https://user-images.githubusercontent.com/307286/32910687-89c824f6-cacf-11e7-8089-d08dce1263e5.png)

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by dan-f** [comment]
Taking a look at this.

**Comment by ackernaut** [comment]
🔥

**Comment by mattkrick** [comment]
this was fixed by updating the notification in real time when the project gets updated. if you've seen that since we've merged epic 8 lemme know!
