### ISSUE TITLE
First Pass at Team Settings Page

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#15]
Checklist:

- [ ] Can add team members
- [ ] Can remove team members
   - [ ] Can remove team members (reassigns projects to team leader)
- [ ] Team Creator is default Team Leader
- [ ] Team Leader can give Team Leader permissions to others
- [ ] Team Leader can take away Team Leader permission from other Team Leaders
- [ ] Can edit team name

**Comment by ackernaut** [comment]
Do we want to add “Can update team name” here?

**Comment by ackernaut** [comment]
Also, what is the value of the avatar at this point? I’m on multiple teams across organizations, so I may just add my company logo at the beginning? (Parabol Engineering could be an example of a team...)

**Comment by ackernaut** [comment]
Also, just to be clear:

1) We are going to set all users to have `isFacilitator` abilities?
2) Are we going to expose “Team Lead” yet? I think perhaps it should be called Owner or Admin instead of Lead since it is mostly an administrative role (not hierarchical). When we do expose it, we could perhaps create the action that allows the Team Lead to pass the role on to another user.

**Comment by jordanh** [comment]
On "team avatar" I had meant "team member avatar". Right now the way we've got it in the data model, we can have a per-team avatar. We can also choose not to bite this off now :)

**Comment by jordanh** [comment]
1) Yes, let's set isFacilitator abilities to everybody.
2) Yes, let's expose Team Leader now. Added to checklist.

**Comment by ackernaut** [comment]
Yeah, I would say let’s punt on an avatar at the team level.

I would suggest calling the role “Team Admin.” Maybe we can punt on the hand-off functionality (show, no action, for beta).

I would add the Team Name field.

**Comment by mattkrick** [comment]
What's the purpose of multiple team leaders? That seems confusing.

**Comment by ackernaut** [comment]
I believe we discussed having only one admin at each level: teams and orgs

**Comment by ackernaut** [comment]
So, unless there is an objection, we are wanting to go with:

- One team lead per team (who can transfer that role to another team member).
  - Perhaps there is a toast/modal/inline button/message where they can undo or confirm?
- When a team member is removed, having a single team lead model helps keep the transferring of projects simple.

**Comment by ackernaut** [comment]
Here’s a first pass at a combined settings pages:

- I like the idea of having two sub-views in the future: one for name, avatar, privacy, org, etc. and the other only for team members—but I think we can combine for an MVP!
- Can update name
- Can send invites
- Team Lead:
  - Can transfer role to another member. Perhaps it needs a confirmation?
  - Can remove team members
- Team Member:
  - Can leave team

Thoughts? Concept mock-up:

![team-settings-combined 2x](https://cloud.githubusercontent.com/assets/307286/19906392/9969a194-a048-11e6-9a46-80025fd63a31.png)

**Comment by ackernaut** [comment]
I was discussing with Matt: Perhaps when I remove, or leave team, there is an inline “Undo” button until I navigate away from the page? Or there could be a confirmation modal/toast for that or any action (promote to lead, remove, leave)?

**Comment by mattkrick** [comment]
@ackernaut this is now wired up on the team-settings branch, but no components yet.
I was thinking the "Leave Team" button looks weird when "Remove from Team" is in the dropdown. 
Also, another idea for adding members is that we could have a blank team member at the bottom of the list & you just fill in the name & email & click invite. That should cut down on the vanilla form look.

If we put a pencil next to the team name at the top, that should also remove the other team name field, so then we'd just show a list of team members.

So many possibilities!

**Comment by jordanh** [comment]
I like where we're going here. Nothing to add to @mattkrick.

**Comment by ackernaut** [comment]
@mattkrick I like those ideas!! That is partly why I like starting with vanilla sometimes, gives you room to toward the essentials. I'll come up with another mock.

**Comment by ackernaut** [comment]
Got some minimal concepts (ala Matt style) going here, looking for feedback:

As a team member I can leave a team (pop an “Undo” toast?):

![team-settings-as-team-member 2x](https://cloud.githubusercontent.com/assets/307286/19937459/5909f020-a0ef-11e6-8425-07bd296e97ae.png)

When I add valid email address to the form, the “Send Invites” button appears (pop a success toast?):

![team-settings-sending-invites 2x](https://cloud.githubusercontent.com/assets/307286/19937460/5915cb7a-a0ef-11e6-83a3-fa0f11696bb7.png)

When I am a team lead I get a drop-down for each team member. If I click on myself, perhaps I see one option “Transfer lead role and leave team” which pops a modal where I have to choose a different team lead before the action is successful:

![team-settings-as-team-lead 2x](https://cloud.githubusercontent.com/assets/307286/19937458/58f6bab4-a0ef-11e6-9b68-41d549cc64b1.png)

**Comment by ackernaut** [comment]
Some iterations for feedback:

What if we went with buttons instead of menus for the team lead? Also, I’m showing rounded buttons vs. pill buttons. I was exploring the pill style because I think it compliments the rounded avatars. Preference on buttons (pill, square, rounded)?

![team-settings-as-lead-buttoned-up 2x](https://cloud.githubusercontent.com/assets/307286/19939291/4d596e8e-a0f6-11e6-99a4-9b87432a0243.png)

Here’s an iteration for inviting a single user, button always showing:

![team-settings-invite-single 2x](https://cloud.githubusercontent.com/assets/307286/19939292/4d5d83c0-a0f6-11e6-9c08-ceaea8c30874.png)

**Comment by ackernaut** [comment]
Iterated: invite avatar icon updated, and field has pencil icon (I imagine some properties may respond to hover for that inline form!)… @mattkrick 

![team-settings-invite-single 2x](https://cloud.githubusercontent.com/assets/307286/19939840/8c4a4030-a0f8-11e6-965e-bb560de5729a.png)

**Comment by mattkrick** [comment]
LGTM!

**Comment by ackernaut** [comment]
Latest state of UI components:

![screenshot 2016-11-03 13 42 07](https://cloud.githubusercontent.com/assets/307286/19980292/763285e0-a1cb-11e6-971c-ad1a986cab5b.png)
