### ISSUE TITLE
Handle unsubscribes for cashay subscriptions

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#150]
for the MVP i think we'll have 3 socketized components with their subscriptions:
- team
 - teamMembers/:teamId
 - projects/:teamMemberId (for EACH teamMember)
 - agenda/:teamId
- user
 - teamMembers/:teamId
 - projects/:teamMemberId (for the currentUser)
 - actions/:teamMemberId
- meeting
 - presence/:teamId
 - team/:teamId
 - teamMembers/:teamId

SHARED:
- teamMembers: team/meeting
- projects: team/user

The goal is to diff the subscriptions, expire unused ones after ~15 seconds, and stay subscribed to the overlapping ones (eg moving from team to meeting should not cause a teamMembers resubscribe). 

A 15 second keepAlive is nice because a stray click won't make us re-send all the info from the start. As a rule of thumb, as the number of watched documents grow, so should our keepAlive. So large initial dumps with infrequent updates should have a _very_ high keepAlive (eg get all customers). Conversely, something with little-to-no initial dumps that update frequently should have a _very_ low keepAlive (eg realtime tweets for a certain hashtag).

I'm not sure how to do this (@jordanh, feel free to chime in).
- `cashay.subscribe` gives us an unsubscribe handle. 
- we should call it 15 seconds after the component dismounts
- we should cancel that call if `cashay.subscribe` is called on that same subscriptions

so perhaps, it'd be easiest to have a `cashay.unsubscribe` that will unsub from a subscription given the same `subString`. It can do this because it has the user-defined `unsubscribe` function cached.

The API would have to be something like `cashay.unsubscribe(subString, {keepAlive: 15000})`.
When that is called, cashay will internally call the `unsubscribe` after the keepAlive expires in a `setTimeout`.

_Then_, we'd have to store that `destructionTimer` on the subscription result inside cashay. For every call to `cashay.subscribe`, we see if the `destructionTimer` exists, and if it does, we kill it.

**Comment by jordanh** [comment]
At first glance, this design seems sound. I am going to have to meditate on the unsubscribe logic... but that shouldn't hold anything up :)
