### ISSUE TITLE
Task Assignment immediately after Invitation

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#1501]
## Issue - Enhancement

User/Leader of a distributed team: “I need to be able to assign things to teammates BEFORE they accept the initial invite."

This user was stuck on not being able to assign things to teammates that hadn't accepted yet (in 1 case, didn't accept UNTIL the meeting started). Their pains:
 * Could not transfer tasks from previous documentation system.
 * Teammates who didn't have the benefit of onboarding had no idea what Parabol was, or how they might use it.
 * Teammates seeing Parabol for the first time didn't understand how this mapped to their current meeting & task management system."

RECOMMENDATION:
 * When ANY team member invites someone to the team, the team is able to assign cards to that new teammate immediately after invite. 
 * The teammate receives DAILY prompts to accept or decline the invite (effective in Gusto :) with Notifications on what cards have been assigned to them since the invite was issued.
 * If the teammate declines OR does nothing, after 6 days the email prompts end, and card ownership reverts to all of the original author/s

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
This seems very pertinent to the on-boarding phase of the UX journey.

I could see us devising a first pass of a “soft user” state (exists, assigned, but hasn’t accepted) — we have an email, perhaps we could optionally ask for a name, and/or optionally ask for a first task (in the spirit of the welcome step 3).

![screenshot 2017-11-30 10 16 17](https://user-images.githubusercontent.com/307286/33441154-9c4a2064-d5b7-11e7-95c9-0591a72d63c2.png)

There’s no reason that the unaccepted user’s board couldn’t show up in the meeting, in the case they are unable to make that first meeting(s) for some reason. The Team Lead could simply choose to speak about their projects, or not, during Updates.

I would see this as being no different than a team lead writing down my name and writing down a list of things I am responsible for in any software—doesn’t really need my input or consent for that first step, as the team lead is organizing content. Later I could be invited to contribute, or own. Seems like a natural progression.

I like the idea of somehow deferring projects back to the original owner/assigner if the person doesn’t accept. Makes me think of how we handling removal of teammates—existing tasks get reassigned to the Team Lead.

**Comment by jordanh** [comment]
@tayamueller, is this still an issue—or can we now close this now that we have the ability to assign tasks to an email address?

**Comment by jordanh** [comment]
Assuming resolved by soft user task assignment.
