### ISSUE TITLE
Bug: I see facilitator controls when I am not the facilitator

### ISSUE THREAD

**Issue by dan-f** [ParabolInc/action#1503]
## Issue - Bug

When testing on the dev server, I noticed that I was seeing the "wrap up the meeting" facilitator control. I suspect this is because I was the facilitator briefly earlier in the meeting.

- **OS:** macOS
- **Browser:** Firefox
- **Estimated effort:** 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Try to repro, else let's snooze

**Comment by dan-f** [comment]
[@dan-f reminding myself to repro]

**Comment by dan-f** [comment]
Can't repro; closing
