### ISSUE TITLE
Strikethrough formatting shortcut

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1512]
## Bug

The keyboard shortcut `shift + command + x` is not adding strikethrough formatting when editing cards. However, the `~strike me~` Markdown-style syntax is working as intended.

### Acceptance Criteria

- Users can press `shift + command + x` on selected text and they get ~strikethrough~
- Markdown-style syntax continues to work as intended

### Estimated Effort
- 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by p-parafiniuk** [comment]
I've created a PR that seems to resolve an issue: https://github.com/ParabolInc/action/pull/1824

**Comment by jordanh** [comment]
Tested resolved in #1824
