### ISSUE TITLE
Admin portal send: global notifications

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1515]
To be explored: we have a notification inbox to notify users about events related to using the software, how about product/company notifications from Parabol like “We released New Feature XYZ: [read more here] (button)”?

### Acceptance Criteria
Design a visual concept that illustrates:
- How notifications from Parabol to users might look in their existing workspaces (dash, notifications)
- How a minimal admin interface might look that allows Parabol admins to create/read/update/delete notifications to users, with a layout/navigation that allows room to build in other sections and features as they are prioritized

### Estimated Effort
- 12 points

**Comment by jordanh** [comment]
Be good to add some AC to this one. Still a need.

**Comment by ackernaut** [comment]
AC and EE added re: admin portal for global notifications

**Comment by ackernaut** [comment]
Iceboxing
