### ISSUE TITLE
Lobby Experience

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#152]
## Issue - Enhancement

- [ ] We need something to indicate that folks should "wait" in the lobby together...words or animated ellipses? OR...
- [ ] ...lobby video game:  pac-man is our Bertie The Tortoise Timer, pac-dots are tiny strawberries, and power pellets are "un-animated" teammates not yet in attendance (animated upon sign-in). Teammates accrue visible points. When facilitator hits "Start Meeting" button in the center of the game, kill screen and Bertie crawls up to take position in the upper left as the start of the timer.
- [ ] The lobby game should be our google doodle. I also imagine a version where the first teammate to enter lobby sees an animated flock of NYC pigeons flutter up from the center of the screen with coo-coo-ru-coo sounds and: "Hey early bird! You're the first one here!" The pigeons fly to a wire at the top of the screen and each teammate's avatar becomes a Breakout ball. The paddle is a slightly angled Everything bagel.

**Comment by mattkrick** [comment]
one day, when we are wildly successful, i want to hire a guy full time to recreate all the best 80s video games using our avatars in the lobby. 

- circle-pong
- breakout
- centipede
- pacman
- space invaders
- duck hunt

**Comment by tayamueller** [comment]
This is still important :)
