### ISSUE TITLE
Duplicate "Welcome to Parabol" email sent

### ISSUE THREAD

**Issue by dan-f** [ParabolInc/action#1521]
## Issue - Bug

This one comes in from a customer who claims they received two identical "Welcome to Parabol" emails, a couple minutes apart. Waiting on more details.

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by dan-f** [comment]
(FYI @tayamueller)

**Comment by jordanh** [comment]
User received two of these emails:

![image](https://user-images.githubusercontent.com/103000/33510353-51e837ea-d6c0-11e7-9086-16510cb0323c.png)

Either we are hitting the same logic twice, or mailgun hiccuped. Let's track here, see if it happens again.
