### ISSUE TITLE
Show "Next Agenda Item" button just to the Facilitator

### ISSUE THREAD

**Issue by dan-f** [ParabolInc/action#1522]
## Issue - Enhancement

As a meeting facilitator, I want to see the "Next Agenda Item" button during the Agenda meeting phase. As a non-facilitating teammate, I don't want to see it, because it makes me think I can push the meeting along when I can't.

- **Estimated effort:** 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
This will be addressed in recommendations for #1676
