### ISSUE TITLE
Generate Notifications, not Toasts, during Meetings

### ISSUE THREAD

**Issue by dan-f** [ParabolInc/action#1524]
## Issue - Enhancement

This is sort of a bug, sort of an enhancement. In the spirit of "don't be annoying," I propose we:
- Do not suppress `@mention`/assignment notifications that are generated during meetings
- Suppress the Toast UI for any and all notifications that occur during a meeting.

I tried to get this together before launch, but there's some sort of sinister bug occurring whereby *clearing* notifications that you received during a meeting fails to update the notifications screen, even though notifications are cleared in the database. A subsequent clear action crashes the page, as the UI attempts to clear notifications which have already been deleted in the database.

If I recall, we are in fact calling the correct mutation, and the mutation resolver is correctly queueing a message to the pub/sub. That notification is presumably being published to the notification target user, who wouldn't otherwise see it displayed on the page. I suspect that the client cache (relay) is not being properly updated after a server response.

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
i think we still want notifications during meetings, maybe not all, but certainly a few.
for example, when you request to be the meeting facilitator, or when the facilitator disconnects.
also, when teams first try the product, more often than you'd think, a person is in a meeting when someone joins the team. it's a really good feeling to see someone joined your team when you're in the meeting.

i think the bugs are all fixed on the projects-to-relay branch (currently on the dev server). if that's not the case lemme know!

**Comment by dan-f** [comment]
Taking a look at this once more post `projects-to-relay`

**Comment by dan-f** [comment]
Closing this, but keeping in mind it will be nice to have some kind of post-meeting notification, and/or ability to control types of notifications & frequency etc.
