### ISSUE TITLE
Users can add emoji status to avatar/preferred name

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1532]
## Enhancement

This could be a playful enhancement to the Social Check-In, but perhaps could be updated at any time via User Settings.

During my Social Check-In, I would like the option to add/update an emoji that shows by my avatar and/or preferred name so that I can build empathy and social culture on my team. (Intention is hard on chat. Much communication and sentiment is non-verbal, visual.)

I could optionally see this in other spaces in the future (a user dashboard, a user profile etc.).

Here’s one concept for presentation:

![emoji avatar concept](https://user-images.githubusercontent.com/307286/33446332-48ea1d30-d5c5-11e7-9872-04606644bd38.png)

An interactive way of expressing #1531 

This could be coupled with check-in timed writing see #1533 

### Acceptance Criteria
- A lo-fi clickable prototype is tested internally and externally
- An issue is written for next steps, either hi-fi design or implementation, depending on outcome of this issue

### Estimated Effort
- 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Take a pass at adding AC to this @ackernaut

**Comment by ackernaut** [comment]
Ice-boxing for now. Can revisit later.
