### ISSUE TITLE
Check-In: timed status writing (optional), then share in rounds

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1533]
## Enhancement

Some folks have commented that they feel like they should be writing something during the check-in.

Quick, low-risk writing can be helpful in general.

Currently, the Updates and Agenda phases of the meeting are generative of information/input, but the Check-In is not so much, except where they can mark Here or Not Here.

Womp, womp.

The idea:

1. The Check-In phase (view 1) prompts the Facilitator to pick the random question, or write in a custom question. If they are not paid, they simply can Start step 2.
2. The Check-In phase goes to a 1-2 minute timed moment where each meeting participant gets a screen with a textarea to answer the question. Think of it as micro-blogging. Writing is optional, and users are reminded that they will get to share shortly. Users could also optionally add/update their social emoji ( see #1532 )
3. Once the time is up, the rounds begin. Users can still update their text if and when they navigate to their round, but by default they follow the facilitator through each person’s check-in, where that person gets airtime and users can see the text they wrote, emoji, etc.

This could help alleviate folks having trouble answering some questions if they had a second to think without pressure of time. It could be a fun way to generate information. We could perhaps give a snapshot of “team mood” based on the text input (like 750words) and share that in the summary:

![screenshot 2017-11-30 12 07 38](https://user-images.githubusercontent.com/307286/33446923-3a59a7de-d5c7-11e7-996f-7d7fa62ef05d.png)

![screenshot 2017-11-30 12 08 10](https://user-images.githubusercontent.com/307286/33446925-3a8efd30-d5c7-11e7-831f-4d51bcea393e.png)

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by tayamueller** [comment]
note: this user observation was actually related to confusion generated by the pencil icon (they thought they were supposed to write something), not wanting a different notation system

**Comment by ackernaut** [comment]
noted! I’m still curious to explore and test a prototype sometime, but it may not be a priority based on addressing current users’ needs; perhaps a car instead of a faster horse one day.

**Comment by jordanh** [comment]
Closing this in favor of a future story
