### ISSUE TITLE
Notification bell count only updates on refresh

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1536]
## Issue - Bug

I've noted twice now that on a long-opened tab on Chrome, my notification bell count is only updating when I refresh Chrome.

I've seen this happen when:
   - Somebody has mentioned me/assigned a project
   - I've received an invite to a new team

- **OS:** macOS
- **Browser:** Chrome
- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
@mattkrick mind updating this issue?

**Comment by mattkrick** [comment]
fixed in #1460
