### ISSUE TITLE
allow approval in team settings for org leader

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#1538]
currently, the org leader sees "cancel pending approval" in the team settings.
instead, they should see an "approve, reject" action, just like their notifications.
optionally, we could just link to the notification page.

AC
- [ ] org leader sees "approve/reject" on team settings

effort: 10.5

**Comment by jordanh** [comment]
Needs final AC and EE.

**Comment by ackernaut** [comment]
I would also comment that it might be helpful to expose basic info at the team level: org name (with link for those who can view), tier (with a CTA for those that can upgrade), and list of billing leader emails (a minimal meta that allows folks to have conversations for what they need outside of the app).

In this same space, a non BL might see “Pending approval from one of your billing leaders: name@place.co, name@place.co, name@place.co”

See #2059 might be nice to bundle efforts here. Also consider progress against #2042

**Comment by ackernaut** [comment]
AC and EE added re: inline teammate approval in team settings

**Comment by jordanh** [comment]
Stuck on: #2108

**Comment by mattkrick** [comment]
closing in favor of #2108
