### ISSUE TITLE
fail softer on subs

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#1539]
now that graphql supports different types of failures for subscriptions, we should handle them differently.
currently, if returning a payload hits an error, we end that sub, and end all other subs that are tied to it.
in the future, we should only do this if it fails auth.
if a payload returns an error, we should log it (via console or toast) and keep on truckin.

**Comment by jordanh** [comment]
This probably needs some design work. Now that we can surface this information to the user, we should think about what to suggest to them when it occurs.

**Comment by mattkrick** [comment]
testing locally, this is the cause of a lot of our woes. if ever a bad payload is received, the subscription goes full on seppuku.

So, let's try a new protocol:

Scenario 1: Unauthorized sub (eg sub to a team you're not a part of)
1. Client subscribes to A
2. Socket Server calls GraphQL subscription, which throws an error
3. GraphQL `subscribe` function throws, and is caught by socket server
4. Socket server sends an unsub message with an error
5. Client calls dispose
6. disposable unregisters subscription from query, marks quere relaseOnDismount to true

Scenario 2: An erroneous payload is received
1. Client successfully subscribes to A
2. Socket server calls GraphQL subscription, which starts an async iter
3. a mutation publishes a message to the pubsub
4. the subscriber picks up the message and has a error while crafting a response
5. GraphQL returns {data, errors} to the socket server, where errors is an array with 1 value
6. socket server returns {data, errors} to the client
7. Client calls Observer.onError(errors)
8. VERIFY: does onError call dispose? I sure hope not, but i think it does. If so, dispose should do nothing & we'll have to re-do scenario 1

Scenario 3: Team member gets added/removed from team
1. GraphQL sends a NEW_AUTH_TOKEN to socket server
2. socket server flushes all subscriptions
3. Each unsub is sent to the client with a "try again" message to resubscribe
4. When client receives unsubscribe, it looks for a "try again" message & resubs if found
5. Goto scenario 1 for failed resubs
6. This is necessary for added to teams, too, because things like the notification subscription check all the teams you're on once.

Scenario 4: Client unsubscribes from subscription
1. Client sends unsub message with opId
2. socket server tells graphql to call `asyncIterator.return()`
3. socket server flushes all data for that opId

We're gonna need to add an ERROR and COMPLETED message from the server to distinguish between the 2.
