### ISSUE TITLE
project editor menu isn't where it should

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#1542]
steps to repro:
1. go to team dash
2. click the + on the done column
3. hit `@` to open the mention menu
4. see the menu appear in the stuck column

### Acceptance Criteria
- Replace withCoords with withCoordsV2

Estimated effort: 12 points

**Comment by dan-f** [comment]
Dan wonders why we can't just use relative positioning ... :)

**Comment by dan-f** [comment]
My work on https://github.com/ParabolInc/action/tree/a11y-menu-component has included a fix for this by ditching the portal approach and just using relative positioning. That branch however also redesigns the `Menu` API, so it's larger in scope than what needs to be done.

**Comment by mattkrick** [comment]
@dan-f we absolutely cannot use anything but a portal. if you're doubtful, please read a blog or 2 on why portals exist. position absolute isn't absolute. relative positioning gets clipped by parent divs. there is no alternative.

**Comment by dan-f** [comment]
Send a link please!

**Comment by mattkrick** [comment]
https://codeburst.io/modals-in-react-f6c3ff9f4701 is good for comparing our options. Note that he arrived at a different conclusion because his modals can all be serialized. If we could, we would (and we do, that's how our toasts work today!).


The official docs on why relative positioning (ie context stacking) doesn't work: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context

A conversation I've had in the past explaining the downfalls of context stacking, complete with Parabol screenshots: https://github.com/draft-js-plugins/draft-js-plugins/pull/746

a fun example why position:fixed doesn't work: https://output.jsbin.com/fepime/

**Comment by mattkrick** [comment]
See #1695 for a better implementation of portals. The main difference is that I use inline styles instead of aphrodite styles. since aphrodite loads styles async, doing calculations on DOM position must be async, and that leads to some bad times. Now that the Modal has inline styles, position is determinate. using this pattern for other menu components is pretty darn easy, just swap out withCoords for withCoordsV2 and replace react-portal-hoc with the Modal wrapper.

**Comment by jordanh** [comment]
@mattkrick, this is fixed now, right?

**Comment by mattkrick** [comment]
@jordanh nope, i only fixed it in 1 of the menus. I'll add some AC.
