### ISSUE TITLE
Team Meeting reminder

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#1543]
## Issue - Enhancement

**How might we help users be better individually prepared for their Parabol meeting, and thus have a more positive and fully-present experience during Individual Updates?**

Observed behavior:
- Many users are still late for meetings, particularly on teams that don't use Slack/integration. (6min late for a 30min meeting is 20% of the whole meeting time allotted.)
- Many teammates, whether late or not, seem unprepared and unengaged as they shuffle cards last-minute, or type cards during others' Solo Updates, or are unaware of docs or Agenda items being covered
- When teammates are unprepared, this can engender feelings of frustration or embarrassment, which sometimes generates negative comments about the software > similar to the tone of comments made about "the naggy office admin person". This is a signal that "the process is working" [users feel a sense of accountability] but that it doesn't "feel good" [UX opportunity]
- When teammates are unprepared, they are also less engaged with their teammate's comments, which dilutes the experience for all.

### Acceptance Criteria (optional)
Users can get reminders notifications X min before scheduled the Team Meeting: 
- Explore either integrating directly with the users calendar or,
- Observing past behavior to infer meeting time or,
- Providing direct configuration in our software for setting a reminder time

Example:
> Your [team name] check-in starts in 30min! Here's the link to your Team Dashboard: [xyz] 

**Estimated effort:** 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by tayamueller** [comment]
logging repeat observation: 

Only 1 teammate has ever contributed to the Agenda. Curious if the other teammates feel agency to participate in that process. How might we remind users to add Agenda items before each meeting? (This may be driving the crosstalk during “Solo Updates”?)

**Comment by jordanh** [comment]
Iceboxing via policy
