### ISSUE TITLE
Avatar Meeting Functions (switch Facilitator, navigate Solo Updates, etc.)

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#1544]
See latest [Acceptance Criteria and Estimated Effort](https://github.com/ParabolInc/action/issues/1544#issuecomment-385455912)

## Enhancement

>Users have never once organically discovered the clickable functions of the avatars during a meeting, which means they're missing opportunities to switch/request/relinquish Facilitator role, or to navigate back to previous Solo Update if accidentally forwarded too soon.

>How might we make the avatar functions more obvious during Onboarding?
---
### Update

We’ve made progress on considering meeting avatar UX for both on-boarding and general meeting enhancements. Here’s what we’d like to try:

#### Visual states
- [ ] Facilitator badge is updated to have the warm palette color over a light background
- [ ] Updated border color states: facilitator (warm), view is for user (dark)
- [ ] Border color is always present with default light gray (during lobby etc.)
- [ ] Reconsidering normalizing size across breakpoints
- [ ] During the Updates and Agenda rounds/topics, the current teammate’s avatar is larger (let’s say the image is 2x). The avatar is removed from the prompts for those 2 phases.
- [ ] Status dot is light gray for disconnected, new palette green for connected
- [ ] Status dot is solid as a default, has a checkmark when marked as here, has a minus sign when marked as not here
#### Interactive states
- [ ] Meeting user avatar has a hover state; cursor changes; a simple tooltip is optional “PreferredName (main actions that can be taken)”
- [ ] Meeting user avatar has a focus state (when using keyboard)
- [ ] Meeting user avatar has a tab index (and menu will open when pressing enter)
#### Menu affordances
- [ ] Replace “request to facilitate” with “assume facilitator” affordance (see #1583)
- [ ] Menu is accessible (can use esc, keyboard up/down, click/tap, etc.)
- [ ] Optional: meeting user avatar has vertical ellipsis icon hanging on right side (we could consider turning this on during on-boarding and off during regular meetings, overall it is a little explicit but may attract more interaction)
- [ ] Optional: allow users to be able to update their own avatar from the menu (triggers the update modal — could be done in lobby, etc.)
- [ ] Don’t use these on the team dashboard; in the short term, map over basic avatars; in the long term we can consider the states and menu items they need on the team sheet or hub.

**Comment by dan-f** [comment]
Yes, I have this tension as well!

I'll argue for moving this to the meeting enhancements epic. If a user isn't finding a button, let's see first see what we can do by making the affordance clearer.

**Comment by tayamueller** [comment]
logging repeat observation:

Team hasn’t discovered the avatar tools yet (returning to previous Solo Updates in this case)--how might we make those features more explicit?

**Comment by dan-f** [comment]
A few thoughts:

Seems to me that "things that can be interacted with" should offer a set of affordances throughout their interaction lifecycle to make them discoverable and intuitive:

- They should "pop out" of their environment in some way
  - For able-sighted folks, we can use high-contrast colors, sharp borders, familiar/metaphorical iconography, even animated states. They should draw your focus towards them.
  - For users with visual disabilities, they can discover these elements by way of roles that draw their focus
- Once your focus has been drawn to them, there should be some sort of feedback to indicate what you can do with them
  - Actual browser `:focus` states should either not be overridden, or they should be styled in a way which gives just as much focus/contrast as the standard browser outline.
  - E.g. for a sighted individual, the mouse could change from the default to a pointer for something that's clickable, or to an open hand for something that's draggable
  - Hover states can help elements further pop out and ask to be interacted with!
  - For folks with visual disabilities, they should have labels indicating what can be done with them.
- Once you initiate an interaction with them, it should be clear what state they're in
  - E.g. a button becomes depressed and then pops back up
  - For elements which offer further interactions, such as a dropdown menu, focus and aria states need to be managed

**Comment by jordanh** [comment]
Excellently written issue. @ackernaut can you please add estimated effort to this issue so we can make it `groom-ready`?

**Comment by ackernaut** [comment]
I will take a card to review, update, and add estimated effort. I wrote a lot of the latest version of this.

**Comment by jordanh** [comment]
Still needs estimated effort

**Comment by ackernaut** [comment]
Here’s my preferred next step:
#### Acceptance Criteria
- Figma concepts updated to reflect latest UI affordances:
  - Meeting avatars illustrated with all state considerations (marked as present/not present, connected or not, is facilitator, read-only, navigation location, etc.)
  - Meeting avatar affordances illustrated with all component states (menus and items for what can be done when interacting with meeting avatar)
- Issue created to implement changes to existing components in codebase
#### Estimated Effort
- 11 points

**Comment by jordanh** [comment]
Iceboxing via policy
