### ISSUE TITLE
Speech to Text during Team Meetings

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#1545]
## Issue - Enhancement

During live meetings, would be amazing if speech-to-text was activated by a few simple prompts:
1) "Take a card" [new card starts typing all following speech]
2) "Assign to" [teammate in registered Parabol Company]
3) "End card" speech-to-text stops typing

Would be incredibly useful for mobile. Clearly not our next Epic (OR IS IT :)

**Comment by jordanh** [comment]
This would probably not be difficult using the Google text-to-speech API. @tayamueller if you feel passionate, bring this up during our Product meeting and hand @mattkrick a card to swag for estimated effort.

**Comment by jordanh** [comment]
Icebox it for now
