### ISSUE TITLE
Persist Presence

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#1553]
The current presence model isn't great because it's per-team, instead of per-user. We've moved the `editing` piece of it to projects, now the only thing left to do is to move the rest of it to either RethinkDB or redis.

Pros of RethinkDB: we could put `online` (or, more accurately, "connectedSockets") on the User Doc. that means I could query `user { id, isConnected}`. that's awesome.

Pros of redis: faster, but a little harder to query, kinda lame that a piece of the user is stored somewhere else. Personally, I'd say we should use RethinkDB for now & then when the time comes, we move the entire User document to redis as part of the caching layer.

With both approaches, the challenge is how to wipe it out when we restart the server.
- We could write a dokku plugin (http://dokku.viewdocs.io/dokku/development/plugin-triggers/#post-deploy)
- We could use dokku to trigger a shell command (https://github.com/dokku/dokku/blob/master/docs/advanced-usage/deployment-tasks.md)

However, I think the easiest thing to do would be to use dokku's `postdeploy` script. We already use a predeploy to run the migration. we could use a postdeploy to run a query that just sets everyone's presence to null.

**Comment by jordanh** [comment]
We'll want to think about horizontal scaling here too. As servers are deployed, I don't think we'd want each server deleting this doc.

On first blush, this sort of state information sounds like it's be _perfect_ to store as a key on redis with a TTL. Are you sure you don't want to store it there? I mean, isn't this one of the reasons we should be patting ourselves on the back for using GraphQL? 👅

**Comment by mattkrick** [comment]
Happy to move it to redis, is the reason because redis will flush its data on redeploy? if so, we'll need to 
- write a trigger to redeploy redis when the code changes
- adjust the `redis.conf` to flush on restart

The first part is difficult, because that trigger is precisely what I'm struggling to find, unless we call it from circleCI or something?

Can you elaborate on how a TTL would be useful here? If I start a meeting, I need to know if someone is online now, not 5 mins ago, right?

**Comment by dan-f** [comment]
Addressed somewhere in epic 8.5.
