### ISSUE TITLE
"Open" vs "closed" team invitations

### ISSUE THREAD

**Issue by dan-f** [ParabolInc/action#1554]
## Issue - Enhancement

When I wish to invite my pal **X** to my team **Y**, I want to make sure that **X** joins my team, and not some other person. I'll call this a "closed" invitation.

When I wish to invite someone to my team who doesn't yet have an account, I want to send them an invitation which allows them to use whatever account they end up creating on their way into the system. I'll call this an "open" invitation.

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
yep! so here's the deal-- let's say you invite me at my old email address at viperKidd@aol.com. I get the invitation, but that's not the email i want associated with parabol. I already use gmail for my other teams with parabol & i want to use it with your team, too. So, when I accept your invitation, I can choose to log in or sign up. I choose log in & provide my gmail credentials. 

One of the most annoying things ever is sending someone an invite & them replying "yeah thanks, can you send it to my _other_ email address?" This is how we avoid that

**Comment by dan-f** [comment]
Talked to @jordanh this morning about this.

I think this all depends on how we define an invitation:

A) A general authorization for **some person** to join Team Y
B) A specific authorization for **User X** to join Team Y

My assumption when I wrote this was that we used definition B, since the in-app team invitation workflow's authorization model fits that definition as well. If we were to extend definition B) to our email workflow, we would only accept authorized **User X** to join team Y, no matter which email address the invitation ended up in.

**Comment by mattkrick** [comment]
I think what you're proposing is:
A specific authorization for User X to join Team Y _if User X exists_, else A.

For some background info, we didn't even have in-app invitations until shortly after you came on board; they're super new!

I 100% agree that's a better way to go. I also think we should offer a typeahead for users within your orgs when you invite folks to your team so you don't accidentally make a typo in your invites. We should also discuss what it'd look like for having 1 user with 2 email addresses. Only question is how to prioritize...

**Comment by dan-f** [comment]
> I think what you're proposing is:
> A specific authorization for User X to join Team Y if User X exists, else A.

Good catch, I had not considered the "else" case! So what I'm proposing is a bit different than that: In the world of option B), an authorization for <non-existent-user> to join <real-team> would just be an invalid invitation.

I don't have a ton of tension for how things are currently done. This is just how I intuitively thought about team invite logic before I realized how it currently is implemented.

I'm going to rename/tag this issue to make clear it's not a "bug" but an "enhancement" :)

**Comment by dan-f** [comment]
[Updated the opening comment]
