### ISSUE TITLE
public Billing Leader

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#1555]
## Issue - Enhancement

When a User is a Member of a Team, it would useful to know what Organization and Billing Leader that Team falls under in case of administrative need, billing error, or if the team wants to level-up to Pro.

### Estimated Effort (11 points)

**Comment by jordanh** [comment]
@ackernaut can you please add estimated effort to this issue?

**Comment by ackernaut** [comment]
I think this depends on either what we surface when designing a team space that includes handbook etc. and excludes kanban, or as an improvement under existing team settings view. Either way I think including this in design effort is 11 points.

**Comment by tayamueller** [comment]
04.09.18 use case:

1. Contracted user wanted to add a new teammate to the team
2. User sent invite, but recipient didn't receive email
3. User "cancelled pending invite" and resent a 2nd invite, but recipient didn't receive meail
4. User became frustrated and reported the issue as a bug & wanted a fix.
5. When queried, she said "i don’t think we have a billing leader? we're on the free plan" [indicates she did not know that Free teams do have a Billing Leader, and that she doesn't know who that person is]

[outcome: new teammate missed their first team meeting + User thinks we're broken]

**Comment by jordanh** [comment]
Closing as solution provided in #1980
