### ISSUE TITLE
Notification view error

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1557]
## Bug

Steps to reproduce:

1. I had an assignment notification that mentioned the original owner.
2. I tapped to see the card on the team board.
3. I went back and the notification was still present.
4. I tapped the checkmark button and got the error.

See screenshot (doesn’t look very helpful but that is all that came up in console in production):

![screenshot 2017-12-12 15 05 55](https://user-images.githubusercontent.com/307286/33908556-6df8e24a-df4e-11e7-91d9-8b02b185ba6c.png)

**Comment by ackernaut** [comment]
Try to reproduce in prod and/or latest Epic changes.

**Comment by jordanh** [comment]
Going to close this one for now. Let's reopen if we see it again.
