### ISSUE TITLE
Don't send mutation result when the subscription will handle it

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#156]
Sometimes, a mutation doesn't need to respond to the server. This is especially true if a mutation triggers a changefeed.

So, the question becomes: How do we a know if a certain mutation is going to trigger a changefeed?

We could:
- blacklist certain mutations by name & compare to the output from graphql, but this breaks down for aliases
- blacklist certain query strings that are used for the input
- ???

**Comment by jordanh** [comment]
How about an option passed to `cashay.mutate()`?

**Comment by mattkrick** [comment]
i'm hesitant because that would tightly couple the server to cashay, but that wouldn't be terrible if it was pretty flexible, like allowing someone to send a `context` or `rootValue` that cashay just shuttles into the server. I wouldn't feel bad about that.

**Comment by jordanh** [comment]
Or, is there a way to add meta information to the GraphQL `resolve` functions that would inform Cashay "data to be provided by subscription stream"?

**Comment by mattkrick** [comment]
That's interesting. Maybe a schema-level directive?
If we did that, it'd still involve reading the JSON object, looking for a particular field, and then deciding to send it if that field is found. I wish GraphQL would throw that in the spec, I still don't fully understand it from the PR.

**Comment by jordanh** [comment]
Oh, yeah, schema-level would be great. Are there any meta fields we can stick up there?

I suppose we could _hack_ it (warning: icky) by defining an arg with a custom type (icky icky).

**Comment by mattkrick** [comment]
nooo, that's what `context` is for. Just like we pass in the authToken, we pass in a "I don't want this junk" flag.
If it originates from the client (cashay), then we have the benefit of sometimes replying, sometimes not.

**Comment by jordanh** [comment]
Ah, I like that. Full circle back to [here](https://github.com/ParabolInc/action/issues/156#issuecomment-238059881):

> i'm hesitant because that would tightly couple the server to cashay, but that wouldn't be terrible if it was pretty flexible, like allowing someone to send a context or rootValue that cashay just shuttles into the server. I wouldn't feel bad about that.

**Comment by mattkrick** [comment]
yeah, when you give variables to cashay, those aren't guaranteed to make it to the server (eg pagination: you ask for 15, cashay asks the server for 5 at cursor X). We could just shuttle context to the server no questions asked though. a GraphQL server should be robust enough to ignore junk context.

**Comment by mattkrick** [comment]
fixed in #261
