### ISSUE TITLE
Chore: refactor notifications.userIds to userId

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#1561]
Back in the day we used to make notifications that could be seen by multiple people. This was great for notifications that went out to billing leaders because if 1 billing leader fixed the issue, then it'd disappear for the other. Now that we have a lot more notifications, a pattern has emerged to make 1 per user & when a notification gets removed, we can just hunt down the one that exists for other users & remove that one, too.
Removing this complexity means 2 things
- changing the index from userIds to userId
- replacing the value from [userId] to [userIds]
- removing code that iterates over userIds (yay prettier code!)

**Comment by mattkrick** [comment]
will triaging an issue, i came across a notification that has `userIds: [null]`. This should not exist. We should promote this issue to higher importance so we can fix this.

Acceptance criteria:
- [ ] notifications use userId instead of userIds
- [ ] a migration is in place to support the above change
- [ ] removing a notification sets the `isActive` flag to `false`. Required for #1792

Estimated effort: 12 points

**Comment by jordanh** [comment]
Iceboxing via policy. Open a new one, if this is still a thing.
