### ISSUE TITLE
Adding a card at agenda phase pushes the rest of the cards to the right (epic8.5 branch)

### ISSUE THREAD

**Issue by dan-f** [ParabolInc/action#1570]
## Issue - Bug

When I add a card for an agenda item by clicking one of the card placeholders, I expect that the placeholder "turns into" an actual project card, which I proceed to edit. On the `epic8.5` branch currently, at the moment that you click one of the placeholders, the rest of the cards on the board shift to the right, and you're editing the card in the top left.

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by dan-f** [comment]
Steps:
- during a meeting, add an agenda item
- move to the agenda item, and add a card
- add another card, and note that the "new" card moves from the placeholder position to the far left as you edit

**Comment by ackernaut** [comment]
I would like to discuss the UX of it.

**Comment by dan-f** [comment]
Happy to discuss here, or out-of-band. Let me know!

**Comment by ackernaut** [comment]
I took a 2nd look at this locally. I think in the spirit of keeping within the scope of this milestone, I would like the behavior to be restored to what is currently in prod. Any UX exploration would be future effort.

Currently in prod:
- The “Add a Project” card is first for a new agenda item.
- Tap the “Add a Project” card and it moves to the right and you are actively editing a card where the “Add a Project” card was.
- New project cards are added left to right.
