### ISSUE TITLE
Hitting the `/summary/` endpoint (no summary id) logs you out

### ISSUE THREAD

**Issue by dan-f** [ParabolInc/action#1571]
## Issue - Bug

I accidentally hit the `/summary/` endpoint (with no summary id) when trying to clear the route and go back to my dashboard. I ended up being redirected to the homepage with a toast telling me I've been logged out.

I suspect this may be the case for arbitrary URLs that do not match ordained routes.

I suggest we either:
- Implement a 404 page for non-matching routes with an affordance to "take me to my dashboard", or
- redirect to the dashboard when a route does not match

- **Estimated effort:** 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Still a thing, but didn't drive enough tension with users to fix. Closing via icebox policy.
