### ISSUE TITLE
revisit UI for changing facilitator

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#1583]
For consideration:

**Assume vs. Request**
Idea: Instead of allowing folks to request to become the facilitator, let’s change it to where they can assume the facilitator. I can think of a couple of cases where this could be a good thing: 1) the facilitator gets stuck, and somebody else needs to take over 2) the meeting wasn’t ended and only the facilitator can end it (and is out of touch when the team needs to access their board). I think we can allow folks to develop their own etiquette around asking to become the facilitator. Let the room win over the software, not the other way around. “Hey, can I take over?” “Sure” [user assumes instead of requests]

**UI affordances**
TBD: Make user controls more obvious? Perhaps a menu icon appears on hover of each avatar?

**Comment by jordanh** [comment]
@mattkrick this needs AC

**Comment by mattkrick** [comment]
already implemented in new meeting format
