### ISSUE TITLE
Check-In facilitator marker accuracy

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#159]
I noticed a few things while clicking around as the facilitator…this may be improved as we work through the state of all meeting phases (so not urgent).

1. A non-facilitator can click back to Check-In, and see a facilitator point/marker on the `ProgressBar` even if the facilitator is in the Updates section. There should be no marker for facilitator.

2. If the facilitator clicks back into Check-In, the pink Sidebar marker should move up from Updates to Check-In but does not.

3. If the facilitator navigates back to a fully completed Check-In round (100% progress bar) and begins to navigate to team members (perhaps to check a late-comer in?) the `ProgressBar` meeting phase progress (light teal bar) starts changing again. I think it should stay 100% complete since it represents overall meeting phase progress.

**Comment by mattkrick** [comment]
I _think_ these will all work themselves out once finish the updates sprint, since that'll update the `facilitatorPhase`. These will make awesome unit tests!
