### ISSUE TITLE
Lobby: pop tooltip when link is copied

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#160]
## Issue - Enhancement

Feedback from testing with @mikearauz:
- When in the meeting lobby and pressing the control to copy the meeting link, I want a tooltip or message to be displayed, so that I know the link has actually been copied.

![image](https://cloud.githubusercontent.com/assets/103000/17457213/f3a16bba-5bbf-11e6-917a-b5025f7debcd.png)
- **Estimated effort:** 1 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
👍

**Comment by ackernaut** [comment]
@mattkrick @jordanh this is the only Alpha issue assigned to me (although there may be others that I could take on) —that being said (and to show progress on our Epic 1 Milestone) —do we want to take a first pass at a Tooltip module that could be used for UI enhancements like this.

**Comment by mattkrick** [comment]
Yeah, ibthink the next step to to browse all the react component libraries and find the beat way to implement it so we don't have to worry about it getting clipped by its parent. Either insert it into a root div or make it absolute maybe?

**Comment by ackernaut** [comment]
Yeah, I’m not opposed to figuring out the root element + absolute layout option.

**Comment by dan-f** [comment]
In prod! yay! 🎆
