### ISSUE TITLE
8.5 Privacy updates

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#1604]
1. When a card is changed to private, a `projectDeleted` message should be sent to everyone but the user (not mutatorId) so that card goes away
2. During the updates phase, no private cards should be seen
3. in the MeetingSummary, no private cards should be seen

**Comment by ackernaut** [comment]
So we just shipped to prod and I tested bullet no. 2 “no private cards seen during updates” — I created a private card from the team dash, and saw that card during my Solo Updates. Not sure if this bullet was skipped, or addressed in code but not working for some reason. All that said, if nothing was done to address this bullet, I’m ok leaving it as is, where users can see their own private cards during solo updates, as I have looked at them during solo updates and I suspect others do too based on comments.

**Comment by mattkrick** [comment]
you're right! i'll backlog this sucker & get it in along with a few other meeting bug fixes.
