### ISSUE TITLE
`CreatedAt` during agendaItems phase doesn't update

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#1605]
During the agenda items phase, none of the card's createdAt values update as time elapses while processing the current agenda item

**Comment by mattkrick** [comment]
punting on this for now

**Comment by mattkrick** [comment]
AC
- [ ] while sitting on the agenda item page, the newly made cards have an updated timestamp

estimated effort: 11 points

**Comment by jordanh** [comment]
See also: #1464

**Comment by jordanh** [comment]
Iceboxing
