### ISSUE TITLE
Filter out private cards from Solo Updates phase

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1606]
## Enhancement

During the Solo Updates phase, I only want to see cards that other teammates can see for clear communication on what’s changed, blocked, etc.

**Comment by mattkrick** [comment]
jinx! captured in #1604

**Comment by ackernaut** [comment]
Closing since it was a duplicate of #1604 (but not seeing that it works as expected, will leave a comment on #1604)
