### ISSUE TITLE
Lobby: change copy to better illustrate when check-in round begins

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#161]
## Issue - Enhancement

More feedback from @mikearauz:

- When a team member enters the meeting lobby, they want to know what will happen when the hit the meeting button, so they feel grounded in the process.

Right now the copy is, "Shall we begin with a check-in round?" For those familiar with the action meeting process, it isn't clear if they should check in _right then_ in the meeting lobby or if the check-in will happen after they hit the button.

![image](https://cloud.githubusercontent.com/assets/103000/17457223/53721daa-5bc0-11e6-8655-123e2986cc0a.png)

- **Estimated effort:** 1 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
👍

**Comment by mattkrick** [comment]
I vote to close this in favor of #162 since both center around the copy above the Start Meeting button. If you agree, feel free to close @jordanh @ackernaut
