### ISSUE TITLE
Publish Team/Project Mission & Teammate Goals

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#1620]
## Issue - Enhancement

How might we help a team publicly state and update their larger collective goal/mission/project milestones?

Most observed teams are currently tracking this in a separate  lightweight system like Google Docs, or written across the top of their whiteboard. Usually a macro team goal with individual milestones.

### Acceptance Criteria
- Create a clickable, lo-fi prototype that illustrates:
  - How to navigate to team knowledge in the team space
  - How to search and find team knowledge in the team space
  - How to create/read/update/delete a team knowledge document or note
  - How to share the note and gather feedback as comments
  - How to pin essential knowledge to the initial view of the team space
- Test the clickable prototype with users

### Estimated Effort (13 points)

**Comment by ackernaut** [comment]
Ah, sounds like some ideas dubbed “Team Sheet” (or hub). Related enhancement issues are currently under “New UI.” Here are some early concepts:

![team-overview](https://user-images.githubusercontent.com/307286/34570091-67dda244-f130-11e7-8f7d-e3478b1d4892.png)

![team-notes](https://user-images.githubusercontent.com/307286/34570090-67af8bb6-f130-11e7-8891-b9e17d4ab8ab.png)

**Comment by jordanh** [comment]
This is a _huge_ issue and one that is oft-requested from our users. @ackernaut I think team sheet might give us a way to navigate to this data, but I think it needs to be designed out yet.

@tayamueller what are the acceptance criteria here? Lo-fi designs we can validate with folks?

**Comment by ackernaut** [comment]
I can’t remember if Bojan is working on some of these views as well.

There are many assumptions to test about what and how when working with team data.

As always we could create a lo-fi, clickable UX prototype that illustrates navigating to or finding team data in the team space, and then reading/editing/deleting a single document.

I’m basing this on our assumptions that folks want team knowledge: purpose, process, policy, role definition, how-to, reference for standards (brand, design, code), etc.

I would say:

### Acceptance Criteria
- Create a clickable, lo-fi prototype that illustrates:
  - How to navigate to team knowledge in the team space
  - How to search and find team knowledge in the team space
  - How to create/read/update/delete a team knowledge document or note
  - How to share the note and gather feedback as comments
- Test the clickable prototype with users

### Estimated Effort (13 points)

**Comment by jordanh** [comment]
Iceboxing for now. One day. One day.
