### ISSUE TITLE
Add project button inaccessible to screen reader users

### ISSUE THREAD

**Issue by dan-f** [ParabolInc/action#1625]
## Issue - Bug

The add project button at the top of the project column is a `<span>` with `aria-hidden="true"` making it impossible to navigate to for users with assistive technology.

It's best to replace the `<span>` with a `<button>`, possibly using the `PlainButton` component.

### Acceptance Criteria
- Replace the <span> with a properly-labelled <button>

- **OS:** macOS / Linux / Windows / ?
- **Browser:** Chrome / Safari / Lynx / ? + version
- **Node version:** `node --version`
- **NPM version:** `npm --version`
- **RethinkDB version:** `rethinkdb --version`
- **Estimated effort:** 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Acceptance criteria:
 - Replace the `<span>` with a `<button>`, possibly using the PlainButton component
-  Screen readers can use add project button

Estimated effort: 11 points

**Comment by jordanh** [comment]
Iceboxing via policy

**Comment by jordanh** [comment]
(it may even be fixed, when we updated our button components)
