### ISSUE TITLE
Error while dragging cards between columns during update phase

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1627]
## Issue 

See: https://sentry.io/parabol/action-staging/issues/430712459/

About to take off on a plane, so being brief.

Repro:

1. Put multiple cards in one column (all same owner)
2. Put only one column next door (same owner)
3. Start meeting, proceed to updates
4. Drag card from column with multiple cards to column containing only one

- **OS:** macOS
- **Browser:** Chrome
ONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by dan-f** [comment]
Fixed by #1628
