### ISSUE TITLE
Check-in: add left and right arrow hotkeys

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#163]
## Issue - Enhancement

Feedback from @mikearauz:

- When a team member is in the check-in round, they want use the arrow keys, so that they can navigate between cards.

Mike was surprised that they didn't work. Good feedback!

- **Estimated effort:** 1 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
💯
