### ISSUE TITLE
Isolate 3rd party dependencies for local development

### ISSUE THREAD

**Issue by dan-f** [ParabolInc/action#1630]
## Issue - Enhancement

Developers working on the app locally should not need live credentials for 3rd party services to begin development work.

- **Estimated effort:** 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Acceptance criteria:
 - Itemized list of 3rd party tools / APIs that need to be mocked or otherwise removed as developer requirements

**Comment by jordanh** [comment]
Sadly, this is still a thing. Iceboxing for now
