### ISSUE TITLE
Error messaging UX for when you become inauthenticated

### ISSUE THREAD

**Issue by dan-f** [ParabolInc/action#1636]
## Issue - Bug

When we redeploy the app the user's session is no longer valid. However, the user isn't aware of that until they continue using the app which results in unexpected behavior.

closely related to #1649

As @tayamueller mentioned, we could do a couple things:

0. Automatically log the user out when their session expires
0. Don't log them out, but have a consistent error UI that informs them they need to log back in.
0. It's been a while since I've thought about OpenID. Could we use a refresh token to re-authenticate behind the scenes?

The first option is probably easiest from an implementation / UX point of view.

- **OS:** macOS / Linux / Windows / ?
- **Browser:** Chrome / Safari / Lynx / ? + version
- **Node version:** `node --version`
- **NPM version:** `npm --version`
- **RethinkDB version:** `rethinkdb --version`
- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by dan-f** [comment]
This one needs more detail. @mattkrick you've been thinking about this right? Any thoughts as to whether we can "silently" reauth the user or whether we'll have to log them out?

**Comment by mattkrick** [comment]
yeah, no need to log them out whatsoever.

Acceptance Criteria:
- [ ] toast pops when new version drops
- [ ] user clicks update
- [ ] update tirggers refresh
- [ ] user keeps using app
- [ ] auth token is no longer kept in redux

effort: 11 points

**Comment by jordanh** [comment]
No longer a thing, we already do this.
