### ISSUE TITLE
Filter controls on archive

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1640]
## Issue - Enhancement

When I want to get a picture of what I have done (or a colleague has accomplished) in the recent past, I want to be able to filter the archive by username, so that I look at only the archived projects I am interested in.

Of course, date and tag filter controls would be nice too. The question is: do we defer until search?

- **Estimated effort:** 15 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
I think the first step to a single kanban (SKB) is something like:

- Filter by (my) teams (multi-select)
- Filter by owner (per team context, multi-select)
- Filter by tag (start with none, private, archived, multi-select)

Then you can see by team, owner and #archive in a single place.

Consequently the team view becomes a first version of the team sheet, something like:

- Big ol’ big ol’ meeting button
- Agenda topic list with input
- Show teammates, and optionally see their tasks for this team (clicking gives an option to see that person’s work on the SKB — route, filter by team, owner, done)
- Perhaps an easier, inline invite for quick team building
- Access to settings (team, integrations)

Later, add purpose, roles, and perhaps a single page of notes using our editor. Later organize notes as documents by type: policy, how-to, knowledge, etc. with default categories?

**Comment by jordanh** [comment]
Closing in favor of New UI / single Kanban
