### ISSUE TITLE
1st Meeting Journey UX

### ISSUE THREAD

**Issue by dan-f** [ParabolInc/action#1641]
### Motivation
We want the first meeting experience to be intuitive, and to help guide the user through the core meeting concepts.

### Parameters
The solution should spec out how we're going to remove the old welcome wizard.

### Acceptance Criteria
- A set of high-fidelity wireframes and information architecture for how we're going to solve this problem
- A set of scrubbed stories targeting the implementation of said designs
- Addresses tension in:
  - #1207 
  - #1501 
  - #1544 
  - #1278 
  - #999 

- **Estimated effort:** 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
Also, look at #999

**Comment by ackernaut** [comment]
For review: considering this issue completed…

- [x] Created high-fidelity prototype in Figma useful for both user testing and capturing acceptance criteria to implement UI components (visual, states, UX)
- [x] Created issues under both Onboarding and Meeting Enhancements epics based on this work
- [x] Addresses tensions for issues above (removing welcome wizard, inline invitations to soft user, onboarding seed cards, initial check-in questions and UX, updated meeting avatar functionality)

@jordanh I think you are probably have the best role to pull on to approve and move to the done column.

**Comment by dan-f** [comment]
Is this "done"?

**Comment by ackernaut** [comment]
Yes, safe to say it is.
