### ISSUE TITLE
Remove Cashay

### ISSUE THREAD

**Issue by dan-f** [ParabolInc/action#1643]
### Motivation
- Have a single client cache
- Move towards isolating GraphQL in it's own microservice

### Parameters
- User entity will have to be moved to relay
- Remaining org mutation moved to relay

### Acceptance Criteria
- We've removed `cashay` from the codebase
- Manual Integration test pass completed, no bugs!

- **Estimated effort:** 15 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
See PR #1653
