### ISSUE TITLE
Reset password not working

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1646]
## Bug

Currently it seems the option to reset password (on the auth0 lock modal) does not work.

### Steps to reproduce

- When signed out and at the landing view at action.parabol.co, tap “Log In”
- Tap “Don’t remember your password?”
- Enter the email address of a test user that uses an email/password combination to authenticate
- Notice that an email never arrives from auth0 that allows you to begin the process of resetting the password for the user

### Note

This may not be an issue if we first take care of #1618 (auth0 lock deprecation).

**Estimated effort**: X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
I think it may be a client-side exception. Here's a potential sentry trace: https://sentry.io/parabol/action-production/issues/435835073/

**Comment by jordanh** [comment]
Acceptance criteria for #1654
