### ISSUE TITLE
Archived team still persists until hard refresh

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1647]
## Bug

Steps to reproduce:

- Go to an unused team that can be archived. You may need to create one. I was on a team where I was the Team Lead and there was one other user (team member).
- Under “Team Settings > Danger Zone” type the name of the team and press enter in order to delete the team
- Notice that you get a toast, but the team is still in the left nav and you can navigate to the team dashboard and team settings for the recently deleted team
- If you refresh the URL with the browser, the team goes away from the left nav, but you get stuck with loading ducks (with dashboard left nav) if you try to load that URL

**Estimated effort**: X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
@ackernaut could you please retest this one?

**Comment by ackernaut** [comment]
Currently unable to reproduce this one on staging or locally. We can open it again if we see it.
