### ISSUE TITLE
Remove universal/utils/schema.js

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#165]
## Issue - Enhancement

I don't believe we're using this file...

- **Estimated effort:** 1 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
@jordanh is this fixed by #181?

**Comment by jordanh** [comment]
That one didn't make it in #181. I'll address it in #185.
