### ISSUE TITLE
early user Notifications by email

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#1655]
## Issue - Enhancement

**New users may benefit from receiving teammate Notifications via email as a reminder to visit and begin habit of daily use.** This could be softened by including a prominent “Would you like to turn off email Notifications?” link in each email which connects to the user’s Settings = easy to shut off & encourages exploration of other settings

**Frequent observations:** 
- New users are often scrambling immediately before a meeting to reconnect with Parabol for the first time since the previous meeting--they're not using us between meetings, at least initially.
- New users are slow to adopt co-authoring Agenda items, often because of above.
- New users, and "junior" staff are hesitant to assign tasks or @mention other teammates, which is a huge part of our magic.

### Acceptance Criteria (optional)
Users can:
   - Do this
   - Do that
   - Cannot do that

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
@tayamueller did you know we do this already? The product is currently implemented to send an email summary of unread notifications to all users who have not been seen within the last 24 hours.

If it's not working, we've got a bug...

**Comment by jordanh** [comment]
Closing in favor #1543
