### ISSUE TITLE
custom syncSince for reducing payload

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#166]
Now that we've got `upsert`, we'll never store 2 identical docs in a stream.
But, on a reconnect, we'll still send the client those docs because the server has no idea what the client has. We can change this.

For example, the client can tell the server to not send initial docs if it's all caught up.
We know it's all caught up until the max `updatedAt` value for all docs. We could resub with `includeInitial`, and then docs with updatedAt < clientLastUpdatedAt don't get sent down the wire.

**Comment by jordanh** [comment]
Wow, interesting!

**Comment by mattkrick** [comment]
I really like this, but the one problem with it is things that got removed while the subscription was down.
I have `A,B,C` on the client. I disconnect. someone deletes A. someone updates B. I connect again. I receive the updated B, but i still assume A is good.

If we wanted to follow through with this, here's how we'd do it:
- send an `updatedAt` and a list of all the IDs we have in the context like `clientHas`
- start the changefeed on the server
- before a document gets sent to the client, ensure `doc.updatedAt > udpatedAt`
- remove `doc.id` from `clientHas` array
- when the changefeed is done sending the stream of initial docs, send the remaining `clientHas` array as `IDs to remove`.
- Back on the client. Remove these docs from the result _but not the entities_ since it could have been moved from 1 subscription to another.
