### ISSUE TITLE
App updated to use IBM Plex

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1661]
## Enhancement

We are upgrading to use IBM Plex on the marketing website, and considering its sole use in the app as well.

### Acceptance Criteria
   - In Figma, app views updated to use the correct type
   - In Figma, UI components updated to use the correct type
   - In codebase, components and constants updated for new typeface and weights
   - In codebase, app scrubbed of old typefaces: files, usage, constants
   - In codebase, include new WOFF2 files for regular (+ italic) and semibold (+ italic) weights

**Estimated effort**: 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Could tackle along with #1690

**Comment by ackernaut** [comment]
Getting started here…

**Comment by ackernaut** [comment]
@mattkrick I am going to get this started following suit using Aphrodite so that I can begin adjusting font properties where needed. When I’m done, perhaps I can hand off or create a second issue which is to move font handling from Aphrodite to Emotion? Your call, but I don’t want to be blocked ATM.

**Comment by mattkrick** [comment]
for sure, let's leave it in aphrodite, if it ain't broke...

**Comment by ackernaut** [comment]
Addressed in #1819
