### ISSUE TITLE
new Meeting ending: back to Team Dashboard

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#1663]
## Issue - Enhancement

request from user:

When a team completes the Meeting process, they voiced a desire to return to the Team Dashboard view together [related to issue #? RE being able to view/reference Team Dashboard throughout Meeting]

frequent observation: first individual user action immediately following a Meeting is to go to Team Dashboard to reprioritize for the week, then to My Dashboard to reprioritize for self. 

### Acceptance Criteria (optional)
Users can:
   - Do this
   - Do that
   - Cannot do that

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
This issue needs acceptance criteria. How would we change the product? Instead of showing the meeting summary, would we immediate return to the team dashboard? Would we show a toast saying "team summary sent!" or something?

**Comment by jordanh** [comment]
## Acceptance criteria:
 - A design and implementation issue(s) where:
   - The meeting summary is not displayed when a meeting ends, instead
   - A user is returned to their team dashboard immediately
   - An optional message appears on the dashboard congratulating the user and displaying simple stats

### Estimated effort: 13 points

### Blocked by:
   - Implementation of #2031

**Comment by jordanh** [comment]
Will revisit after Timeline implemented. Iceboxing for now via policy.
