### ISSUE TITLE
“Schedule your first team meeting” calendaring super card

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1672]
### JTBD

>When team leads are on-boarding to Parabol and want to get started with their team, they want an explicit task card so that they can easily set up their first meeting.

### Acceptance Criteria
Users can:
  - [ ] Have general affordances of super cards (see #1670)
  - [ ] Optionally tap a button that pre-populates a new Google Calendar event with meeting details including a link to the lobby
  - [ ] Optionally tap a button that pre-populates a standard calendar event format (like Apple Calendar, Outlook, etc.) with meeting details including a link to the lobby

**Note**: We could repurpose the CTAs that conditionally show at the bottom of the No. 1 Meeting Summary that a team receives.

**Estimated effort**: 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
@mattkrick mind reviewing this one for acceptance criteria and estimated effort? (just trying this, will try not to pull on you for too many of these)

**Comment by mattkrick** [comment]
yeah, this looks easy enough! The bulk of the work is gonna reside in #1670.
