### ISSUE TITLE
Bertie bot dialog UI

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1673]
### JTBD

>As team leads on-board with Parabol and considering using with their team, they want some light coaching so that they understand how to use the software and can get started with first tasks to on-board their team.

### Acceptance Criteria

Users can:
  - [ ] See a dialog box in the bottom right from a scripted bot with name and avatar. The box floats of the meeting UI.
  - [ ] See unique messages in the dialog box for coaching (purpose, pro tips, to move forward, etc.)
  - [ ] Tap on links inside the unique messages to “getting started” website content for meeting tips
  - [ ] Close the dialog box
  - [ ] See if there are new messages in the dialog box if it is closed
  - [ ] Toggle this during regular meetings for messages that include general tips and pointers

General:
  - [ ] This component is reusable
  - [ ] This component uses nested “dialog message” components that stack up in the dialog box
  - [ ] Has a design for a collapsed state with alert badge

**Estimated effort**: 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Concept (dialog box in bottom right)**
<img width="1280" alt="frame 2x" src="https://user-images.githubusercontent.com/307286/35460969-6bce9fb6-02ab-11e8-9bcf-770664b131f3.png">

**Comment by jordanh** [comment]
Is this a duplicate of #1835 ? If so, could we close this issue for now?

**Comment by ackernaut** [comment]
That sounds good to me, #1835 is more of a next-step story, and this issue probably needs to be closed and ice-boxed, although I don’t like losing the  “Onboarding” milestone. Just closing for now.
