### ISSUE TITLE
Meeting prompt updates

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1678]
## Enhancement

Let’s clarify messages, update terminology, make prompts more consistent, and apply the updated, lighter look!

### Acceptance Criteria

- [ ] All prompts lose the clunky, rounded box with drop shadow
- [ ] Updates and Agenda topic prompts lose the avatar
- [ ] Copy updates to be provided for all prompts (including Agenda _topic_ instead of _item_)

### Effort

11 points (see [CONTRIBUTING](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
@ackernaut is this issue still accurate? If not, could you update it or close it (if you feel it has been implemented)?

**Comment by ackernaut** [comment]
Forgot about this one, closing in favor of newer #1888
