### ISSUE TITLE
Assign menu updates (including inline invitations)

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1684]
## Enhancement

Addresses part of the onboarding UX for team adoption of the software. Helps address tensions from #1501 as well.

### Acceptance Criteria

- [ ] The “assign menu” is accessible and usable with a keyboard (enter, esc, up/down, etc.).
- [ ] The last option of the menu is an inline input with unique styling.
- [ ] The inline invitation input accepts an email for the first version.
- [ ] Adding a new email address creates a soft user and assigns to that user
- [ ] Adding a new email address creates an invite that may need approval or can be sent automatically
- [ ] Adding an email of a pre-existing org user automatically invites that user to the team

#### The editable input child component (note, can be like our Editable component where we handle some extra presentation than just an input element).

- [ ] The menu has placeholder text.
- [ ] Tapping the input allows a user to enter 1 email address (that of the intended new owner of the task card). So, no comma separation tricks, that results in an error.
- [ ] I think that we can show the error text below (the height of that last item will grow), or find an alternative, minimal slick way of denoting error (perhaps the value entered or placeholder text show a hot palette color,  the input animates, can explore).
- [ ] As the user types, the characters entered will flow toward the right. I think the input is 1 line only and overflows.
- [ ] Pressing escape while the input is focused will close the menu with no commit.
- [ ] Users can tab through or up/down key through menu items including this input. Pressing up while on the input, will go up to the menu item above, etc.
- [ ] The user has to press enter to submit the email address. If it is a valid email address, the menu closes and the owner is updated on the card.
- [ ] When the user opens the menu again there is a new teammate that is a soft user by email.
- [ ] The inline input is there on the new instance of the menu meaning it could be reassigned to another soft user.
- [ ] We can use SVG for the avatar placeholder. I would like to have a set of default SVG avatar placeholders in a variety of our extended, new palette colors.

**Estimated effort**: 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
@mattkrick I added the bullets for extra inline invitation input details.

**Comment by mattkrick** [comment]
Awesome!
Here's some more acceptance criteria to test:

- [ ] After typing text in a project card, hitting tab, then Enter will open the assign menu
- [ ] After selecting a new assignee, the menu closes. Pressing Enter reopens the menu
- [ ] In a menu longer than the max height, pressing the down arrow automatically scrolls the active assignee into view
- [ ] pressing the down arrow after the last assignee highlights the new member input & focuses the caret inside the input
- [ ] hitting Enter submits the input. If there is an error (ie invalid email) then the error shows up below the input & the menu scrolls to show the entire error.
- [ ] The error goes away when the email address is valid
