### ISSUE TITLE
My Dashboard archive

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#1689]
## Issue - Enhancement

When a user is asked to report on "what did you do this week/month/quarter?" it would be useful to see all of their personal accomplishments in one place as an Archive view in My Dashboard. It makes both the ask and the fulfillment lighter.

"When you’re selling to management you’re selling reporting." -a smart guy we know

**Comment by ackernaut** [comment]
It sounds like the single kanban board is still a good idea.

I can see any non-private cards from any teams I’m on (or later subscribed to?).

I can filter by: team (multi-select), owner (multi-select), tag (#private, #archived, #useradded) (mult-select filtering is #692 and a kanban filter box is #843)

Similar to #1491 #1640 #621 

The single kanban could also help with #1500 (I could see all my teams, but filter by a single teammate that may span across many of those teams)

First step to single kanban is seen in #1100 (but I say we add #archive and #private as the V1 label filter)

<img width="1280" alt="dashboard-side-nav-collapsed 2x" src="https://user-images.githubusercontent.com/307286/35450852-e482cbbe-0286-11e8-8a14-07d6d4cfd8af.png">

**Comment by jordanh** [comment]
Related to #621

**Comment by tayamueller** [comment]
closed by #621
