### ISSUE TITLE
Design: filter bar

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1690]
## Issue - Enhancement

On the road to adding search to our product, we'll need to re-orient the UI to include a search bar. However, implementing the front-end and backend tasks to implement full search is _a lot_ of work. So, I suggest that we take a step toward search by adding a bar that _only_ filters the current view. We'll start with currently visible cards and agenda, but move toward other lists of data elements as we create them.

This issue only refers to designing out callout 1, below:

![handbook_hand_wire_1](https://user-images.githubusercontent.com/103000/35461164-868913a0-029b-11e8-935a-c7b810751bb4.png)

### Acceptance Criteria
Design must:
   - Design uses new palette, aesthetic, and typography (implementation of palette addressed in #1766)
   - Include place for users to enter text to filter the current view
   - Include other navigation elements necessary at the top of the view
   - When the screen is vertically scrolled, filter bar remains at the top

- **Estimated effort:** 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
I think the bullet under Acceptance Criteria
> Implement new palette
warrants its own issue, criteria, and effort, but I can definitely see how layout, palette, and typography (#1661) work can be done at the same time.

**Comment by ackernaut** [comment]
Added an issues for implementing the new palette (#1766)

**Comment by ackernaut** [comment]
For fun, here’s a current lo-fi concept that supports a search/filter control in a top bar that can filter away the dashboard tasks by text string (it’s also a step toward the future where we add a handbook, move away from a left nav, etc.):

<img width="1280" alt="product team dash concept 2x" src="https://user-images.githubusercontent.com/307286/36328059-5e52edb6-1326-11e8-9455-0f6b1a07748c.png">

**Comment by mattkrick** [comment]
@ackernaut is this done? i think this was done before the sprint even started?

**Comment by ackernaut** [comment]
The v1 is, ha! I think we can create a new issue to add it to the My Dashboard view, and perhaps another AC when we move things around some more. I’m ok closing it.

**Comment by jordanh** [comment]
Already implemented in production product, will revisit/create new issues of demand warrants around this filter/search bar.
