### ISSUE TITLE
Add filter props to AgendaList and ProjectColumn components

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1691]
## Issue - Enhancement

Related to #1690. The actual implementation may deviate from the title of this issue; the issue is merely evocative of the limited scope of this issue.

Let's take a step toward search by allowing users to filter the current view. In order to do that, list components will need to limit the sub-components they display. This issue refers to implemented the box, below, in callout 1, below:

![handbook_hand_wire_1](https://user-images.githubusercontent.com/103000/35461372-7d884fc2-029c-11e8-8db5-4d33499d32ec.png)

### Acceptance Criteria (optional)
Tests are written that demonstrate:
   - when the filter prop is empty, all cards and agenda will be rendered
   - when the filter prop is set, only cards and agenda containing that substring (`.*pattern.*` as a regex) will be rendered

- **Estimated effort:** 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Quoting @dan-f, "let's be careful that we're not making the components aware of search, but that they are just rendering a list of items."

This might imply that there is a filter component in the render chain that limits the number of items being fed to the lists themselves.

**Comment by mattkrick** [comment]
adding @ackernaut to help out with the style

**Comment by mattkrick** [comment]
pushin this ugly thing across the finish line behind a feature flag so we can start working with the new version of relay on master

**Comment by ackernaut** [comment]
👍 I think I may be able to prioritize next steps to dash layout (including the first search UI designed) in the next sprint, we shall see.
