### ISSUE TITLE
@Mentions in cards generate notifications

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#17]
Original title: _@Mentions in Meetings generate new notifications_

- [ ] When a card gets updated & it has a `@Matt` mention, I should get a notification saying I've been mentioned in a card

**TBD**:
- How to throttle? Add @Matt remove @Matt add @Matt
- Should it trigger a notification from card updates during a meeting if the mentioned person is checked-in?

**Comment by sarakhatri** [comment]
@jordanh is this different from generally tagging someone in a project card?

**Comment by mattkrick** [comment]
- [ ] When a card gets updated & it has a `@Matt` mention, I should get a notification saying i've been mentioned in a card

F

**Comment by mattkrick** [comment]
closing in favor of the newer one #982 since it has more details
