### ISSUE TITLE
Clicking on meeting lobby for a team uses last teamId, not teamId from route

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#170]
## Issue - Bug

Encountered this bug when:

1. Logged in, hit `/welcome` route. Added new team and invited erica@xxx.co
2. Erica joined team, we had meeting
3. Logged out
4. Logged in manually hit `/welcome` route; added new team and invited taya@xxx.co
5. Taya joined team, new team appeared in her list, she entered correct meeting lobby
6. I pressed leftnav link to team, pressed "Join meeting" and got meeting lobby containing Erica and Erica's team name. Boo!

- **OS:** OSX
- **Browser:** Chrome
- **Node version:** v6.2.0
- **NPM version:** 3.8.9
- **RethinkDB version:** rethinkdb 2.3.4 (CLANG 7.3.0 (clang-703.0.31))
- **Estimated effort:** 2 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Looking at this one now for demo purposes...

**Comment by jordanh** [comment]
Testing on `team-dash` branch this looks to be resolved in part by some new cashay changes (subscriptions being properly separated by variables).

However, there is still an opportunity to clean up the duck a bit...

**Comment by mattkrick** [comment]
yeah, the duck should probably just be an array, if we use a duck at all.
It's weird to make an array of computed values. When people talk about taking the best of MobX and redux, I think handling computed values is the best place to start. Not sure I like the pattern, but it's better than cramming that logic in the container.

**Comment by jordanh** [comment]
Yeah – I hear you on all counts.

Shall we merge this in the meantime?

**Comment by mattkrick** [comment]
yeah, no harm there!

**Comment by jordanh** [comment]
I think programmers should also take the hippocratic oath
