### ISSUE TITLE
Reword label for the new project button

### ISSUE THREAD

**Issue by dan-f** [ParabolInc/action#1705]
## Issue - Enhancement

This one's super small! I'm having trouble parsing "Add project set to {column}" as English. A suggested alternative: "Create a project with the {column} state".

### Acceptance Criteria (optional)
Users can:
   - Tell what's going to happen when they click the button based on its label

- **Estimated effort:** 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
No longer relevant.
