### ISSUE TITLE
Remove socketcluster

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#1706]
## Issue - Enhancement

For back-end services, we have a 3-step plan:
- [x] remove cashay
- [ ] remove socket cluster
- [ ] move graphql to its own microservice (bull powered?)

This will either eliminate the memory leak in #1196 or will help us easily identify it.

### Acceptance Criteria (optional)
   - socket cluster gone on front end
   - socket cluster gone on back end
   - vanilla websockets used on front end
   - uws used on backend

- **Estimated effort:** 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
auth requires extra thought.
when a client attempts to connect, that attempt could use a bad auth token.
then, when they attempt to query, they'll get rejected.

let's assume a 300ms round trip.

current:
At t0, send init and query frame. TCP guarantees the init gets there first. handle init in sync, then query gets rejected.

proposal 1:
At t0 send both. when init begins, set status to pending. if it's legit or it needs a new auth token, make it & clear the pending status. if a query comes in, put it in a queue until pending clears.  when pending clears, flush the queue. This is nice because it seems pretty fast

proposal 2 (socket cluster):
At t0 send the init frame. wait for the ack. at t300, send the queries. this is nice because the messages are stored on the client, but bad because it takes longer. however, waiting ~10ms wouldn't be bad, since we could batch up messages if we wanted. but 300 is long, especially on mobile devices., which could take 10x longer.

proposal 3:
Same as proposal 1, but instead of an actual array, we do something fancy like use an observable.

i'm gonna opt for proposal 1

**Comment by jordanh** [comment]
See PR #1712
