### ISSUE TITLE
“Me” Dashboard Part 1

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#171]
When Ava is working on her outcomes for the week, she needs a dashboard so that she can see and update actions and projects.

**The “Me” Dashboard**:

- [x] Allows Ava to update her account settings.
- [x] Has navigation to Ava’s teams.
- [x] Has a column of Ava’s Action outcomes.
- [x] Has four columns showing Ava’s Project outcomes by status.
- [ ] Has buttons to add new outcomes (Actions and Projects).
- [ ] Has a sort option to see Projects by team.
- [x] Has a notification bar that shows if one of Ava’s teams is currently meeting.

**Not in scope for Alpha** (?):

- Cards have drag-n-drop functionality between columns.
- Actions can be changed to Projects and vice versa.
- Can update email address from settings.
- Can add/update avatar from settings.

**Estimated effort:** 3 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

![my-outcomes-left-nav-list 2x](https://cloud.githubusercontent.com/assets/307286/17524358/e79aaa0a-5e23-11e6-8183-d666972b4876.png)

**Comment by mattkrick** [comment]
>  Has buttons to add new outcomes (Actions and Projects).

Stuck on this one. 
- Where does the button go?
- Also, how do we know which team the new outcome is being created for?

On the team dash, we can create a new outcome with the active user being the assigned team member, and then change if needed. But tasks can't change teams.

Options:
- have a CreateCardTemplate that includes Team, Content, and a submit button. The Outcome is only created after the submit button is clicked. I know, submit buttons are lame, but if we submit on blur, I got a feeling folks will have to delete a lot of mistakes.
- Use the above for the TeamDash as well, so things are more homogenous.
- Select the team before the card appears, (eg click +, select team from a menu, then the card pops up & they can fill it in)

**Comment by jordanh** [comment]
Closed by #189.

Saving these for a later sprint:

- [ ] Has buttons to add new outcomes (Actions and Projects).
- [ ] Has a sort option to see Projects by team.
