### ISSUE TITLE
GraphQL as a micro service

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#1717]
Eventually, we'll need to move GraphQL to its own microservice.
Today, I don't see a major benefit in doing this.
Tomorrow, it will help us scale.

To do that, we'll need to do a few things:

on the application server
- write a wrapper that turns bull into an async iterator
- remove SharedDataLoader

on the GraphQL server
- ensure that it is stateless
- Decide whether to use a job queue (like bull) or a http queue + nginx or some other way to share the load. Bull seems easier initially, and faster, since it has no http overhead.
- feed the async iterator from graphql into messages that will feed the application server's async iterator

### Acceptance Criteria (optional)
- app works, GraphQL schema is not imported by the application server

- **Estimated effort:** 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Iceboxing for now.
