### ISSUE TITLE
Update docs to include deployment process

### ISSUE THREAD

**Issue by jane3r** [ParabolInc/action#1720]
Parabol's value extends beyond the services it provides to agile teams, it is also a good source for developers to learn about the right way to build products at scale. Overall, the team has done an exceptional job documenting the project i.e with the [S3](https://github.com/ParabolInc/action/blob/master/docs/s3.md) docs. 

It would be nice if you could also share your insights into your deployment process. Specifically, since you already have all the deployment scripts in place - how does this integrate with dokku. 

@jordanh & team thank you for all your hard work!

**Comment by jordanh** [comment]
Hi @jane3r, I took a first stab at writing some documentation. Could you have a look?

https://github.com/ParabolInc/action/commit/84d8ba174747bcf2bb837f0b454e956e7dbe54de#diff-00e64a8af4dd5116b95476a6691792dc

We welcome enhancements here if you make your own deployment.

Are you running your own instance now?

**Comment by jordanh** [comment]
I haven't heard back on this one. Assuming what we have now is good!
