### ISSUE TITLE
Add Retro Lobby for FREE users

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#1724]
### Background
Retros aren't free. We could either disable the Retro button, or use the lobby as a learning & sales platform. The latter is far more attractive because it allows us to 1) measure how many free folk visit the page 2) sell them on the idea of retros 3) Upsell them

### Acceptance Criteria 
- Write copy exclusively that includes what a Retro is & why it is useful
- Write copy explaining that Retros are for paid users only
- Add a "Upgrade My Account" button that opens the "get access" modal
- the "get access" modal is like the CC modal, but you can also email us to ask for access
- The Start Meeting button is grayed out if `retrosAvailable > 0`
- Each team has a set number of retros that they can run. We can manually increase that limit, or in the future we may set that to 3 for all free teams. pro teams have unlimited. 

- **Estimated effort:** 11points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
I like the idea of using this as a squeeze.

**Comment by mattkrick** [comment]
expository:
"A retrospective is a 30-minute meeting run every other week during a project to learn how to move forward more effectively"
"As a free user, you can start running retrospectives immediately, even if your team members do not use the software! GET ACCESS NOW"

**Comment by mattkrick** [comment]
Seems like we have 5 states:
- Team is a pro user: OUT OF SCOPE
- Team is a free user & has never received trial meetings
  - "As a free user, you can start running retrospectives immediately, even if your team members do not use the software! GET ACCESS NOW"
- Team is a free user & has all of their trial meetings remaining
  - "You have X trial meetings remaining. Go ahead and run a trial meeting on us!"
- Team is a free user & has used at least 1 of their trial meetings
  - "You have X trial meetings remaining. Ready for the full experience? Upgrade your team to PRO!
- Team is a free user & has no trial meetings remaining
  - "Nice work! You've successfully run X trial meetings. Upgrade to PRO for unlimited retrospectives! Are we missing a feature your team needs? Let us know"

**Comment by jordanh** [comment]
## Expository text:
> A retrospective let's your team reflect on past work and discover opportunities for how to work better in the future
> As a free user, you can start running retrospectives immediately with your team:
>
> **[GET ACCESS NOW]**

## Acceptance criteria:

- [x] Write copy exclusively that includes what a Retro is & why it is useful
- [x ] Write copy explaining that Retros are for paid users only
- [ ] Add a "Get Access Now" button that opens a placeholder "get access" modal (todo: create design issue for modal, the "get access" modal is like the CC modal, but you can also email us to ask for access)
- [ ] The Start Meeting button is grayed out if retrosAvailable > 0
- [ ] Each team has a set number of retros that they can run. We can manually increase that limit, or in the future we may set that to 3 for all free teams. pro teams have unlimited.

**Comment by jordanh** [comment]
To close this issue, all we need to do this sprint is complete the above ^
