### ISSUE TITLE
Build retro cards

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#1726]
### Background
To use a retro, we need a React Component that looks similar to a Task card, but has no status, offers anonymity, and has different DnD features. @dan-f if you take this on & feel the desire, consider React Storybook. I think we're at a good place to try incorporating it into our workflow. Heck you might get so good with it that you could use it to prototype instead of figma!

### Proposal
- Wrapped in an `AnonymouseEditorCard` that says “Someone is typing…” if the editor is not the creator. Similar to the NullCard for Tasks.
- Cards created by other participants show blurred text when not being edited.
- Cards have a hover state.
- Has a graphQL schema like {id, content, createdAt, group, isCreator}. In the DB we'll save the creatorId, but we'll only offer `isCreator` so we don't leak that information to the client.
- onHover, the zindex animates to 0 (to see the card when it's in a group)
- can be dragged as a RetroCard entity
- it shows a drop zone if being dragged but not onto another card/group
- if dropped on another RetroCard, it joins the droptarget's group, or makes a new group if none exists. a drop zone is shown behind the existing card/cards in group as new cards are placed behind the others.
- if dropped in the column (the area with remaining space at the bottom of the column), it leaves the group. if it was the 2nd to last card in the group, then the group is deleted.
- when the card is grabbed in order to be dragged is has a state indicating that it is being dragged. While it is being dragged it leaves a visual copy in the original position with styles that indicate multiplayer activity. The visual copy disappears when the card is dropped in the new position.
- The group has a label (input) with error states.
- The group can be toggled to an expand list view of cards and back to a stacked visualization.
- The card has placeholder text when a user creates a new one “My reflection thought…”
- The card has a delete button (visual: icon only) that appears on hover of cards that the user created during Reflect/Think.
- The card is read-only during Theme/Group and Discuss/Agenda.
- The cards can have a label for their column heading when dragged outside of their original column.
- Cards/groups can receive up to a max number of votes.

- **See** [1767 comment](https://github.com/ParabolInc/action/issues/1767#issuecomment-367115504) for more granular details and the link to Figma.

- **Estimated effort:** 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by dan-f** [comment]
Pulling this into sprint 3.
