### ISSUE TITLE
Build Retro Card Groups

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#1729]
### Background

During the grouping phase of a retro, cards will be grouped. These groups will have titles.

### Acceptance Criteria
- Drag a card on top of another ungrouped card to form a group
- Drag a card on top of a grouped card to join that group
- Drag a card from a group to the flex space below to ungroup the card
- Dragging the 2nd to last card out of the group removes the grouping

### Proposal
During the entire grouping phase, I think it's easiest to let cards live as a peer entity to groups. After that phase, we may decide to turn single cards into 1-card groups. If we do this, we could use a heuristic to auto-summarize the card so the agenda items look OK.

- **Estimated effort:** 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
This looks great. I think it needs details on how a title will be added to the group. Something like:
- When a group is created, an inline input appears with a placeholder “Group Title”
- The user simply types in a title and presses enter
- The user can tap the title and it behaves as an editable component. It can be updated by typing and press enter.

**Comment by jordanh** [comment]
Blocked behind design issue #1767
