### ISSUE TITLE
Current dashboard breaks ~12 teams

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1732]
## Issue - Bug

See screenshot:

![image](https://user-images.githubusercontent.com/103000/36127149-c06dbc42-1010-11e8-94c2-3c951f95a9fd.png)

Let's stack this fix up with #1690 

- **OS:** macOS
- **Browser:** Chrome

### Acceptance Criteria (optional)
Users can:
   - Have, and scroll to, more teams than their screen's vertical height can display

**Comment by ackernaut** [comment]
I think this overflow issue can be addressed as we update the layout for new UI considerations.

**Comment by ackernaut** [comment]
Pushed a fix today. The list of teams will scroll within the dashboard nav container.
