### ISSUE TITLE
Creating new cards on My Dashboard

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1735]
## Bug

When I am on My Dashboard and filtered by a team, the behavior used to be that tapping the plus icon to add a new card would automatically create a card for that team. Now I see that I have to select a team. Additionally, selecting a team other than the currently filtered team will add a blank card to that team, but you can’t see it because it is already filtered away.

**Note**: we may not get to this depending on how we move forward with New UI changes involving the Team spaces and My Dashboard (single kanban?).

### Acceptance Criteria

- When I am on My Dashboard and not filtered by any given Team, I have to choose a Team when adding a Task card to a column.
- When I am on My Dashboard and I am filtered by a Team, any newly created Task card should automatically belong to the filtered Team.

### Estimated effort 

- 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Moving over to E4E

**Comment by jordanh** [comment]
Iceboxing this
