### ISSUE TITLE
Retro Frontend: Minimum-Viable Retro Lobby

### ISSUE THREAD

**Issue by dan-f** [ParabolInc/action#1739]
## Issue - Enhancement

This will create the lobby front-end experience for Retro Meetings.

### Acceptance Criteria (optional)
- The Retro Lobby matches the wireframes
- Team Members can see the presence of their teammates
- Team Members can see the Retro outline on the left-hand side
- The navigation is feature-flagged (behind a user-token feature flag) such that the code path is dead and eliminated in production (can probably handle this by feature flagging the “Start Retrospective” button)
- A Team Member can click “Start Retrospective” in order to become the facilitator and begin the Retro Meeting

- **Estimated effort:** 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Hey there @dan-f, this needs an estimated number of points...

**Comment by mattkrick** [comment]
- stuck on #1853 since it has all the components
- the link to the org billing page is gonna be inside the payment/get a few free modal that still needs to be designed
