### ISSUE TITLE
Retro Backend: Phase Navigation

### ISSUE THREAD

**Issue by dan-f** [ParabolInc/action#1740]
## Issue - Enhancement

This adds support in the backend for the Facilitator to navigate between different phases / phase items in a Retro Meeting.

### Acceptance Criteria (optional)
- The facilitator can navigate the Retro to a different phase via GraphQL mutation
- Clients can subscribe to the Retro phase such that they’re updated when the facilitator changes the phase

- **Estimated effort:** 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
@dan-f this also needs an estimated number of points...

**Comment by mattkrick** [comment]
Stuck behind the check-in phase

**Comment by mattkrick** [comment]
guess i'm not _stuck_ stuck because this is just for the backend part. will PR
