### ISSUE TITLE
Retro Frontend: Social Check-In

### ISSUE THREAD

**Issue by dan-f** [ParabolInc/action#1741]
## Issue - Enhancement

This story will deliver the ability to run through the social check-in for Retro Meetings.

### Acceptance Criteria (optional)
- Uses the latest UX in code—at present the "old style"
- Uses the newest, modular meeting architecture (as merged in #1837)
- The Retro social check-in operates exactly as the Action social check-in does
- Team Members can be marked as “Here” or “Not Here” by the facilitator
- At the end of the check-in round (the last user), the Facilitator gets an affordance to move to the “Think” phase of the retrospective
- Clicking that button calls the appropriate phase mutation

- **Estimated effort:** 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
@dan-f this issue also needs an estimated effort...

**Comment by jordanh** [comment]
Waiting on #1836

**Comment by mattkrick** [comment]
NOTE: In the action meeting, we didn't have the concept of stages. Now that we do, life is better in all cases except for one: we have to be sure that when someone joins/leave the team mid-meeting that we add/remove them to the stages array. This should be nothing more than an extra function in the add/remove team member mutations that checks for an active meeting & if it's there, then mutate the stages. This is more back-endish, but i'll leave this here until the back-end check-in issue gets created
