### ISSUE TITLE
Retro Frontend: Reflect Phase

### ISSUE THREAD

**Issue by dan-f** [ParabolInc/action#1743]
## Issue - Enhancement

This story outlines the ability to participate in the Reflect phase of a retro meeting; creating thoughts.

### Acceptance Criteria (optional)
- The facilitator can select the active Reflect Phases column
- Team Members can add, edit, and delete Reflections across columns
- Once the facilitator moves to the Theme/Group phase, the contents are immutable
- Reflections have an error state with appropriate message for when mutative operations fail.
- Each Reflect Phase gets a 2 minute timer. The timer has no effect other than indicating to the Team Members the amount of time they should spend on that particular phase item. It’s up to the Facilitator to move on.
- The user is notified when the time expires by an appropriate animation [and optionally a sound, if time permits]

- **Estimated effort:** 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
Editing title & AC to reflect updated verbage & flow

**Comment by dan-f** [comment]
Since the facilitator timer is captured in https://github.com/ParabolInc/action/issues/1834, I propose we kick it out of the AC for this story.
