### ISSUE TITLE
Retro Backend: Creating & Editing Reflection Groups

### ISSUE THREAD

**Issue by dan-f** [ParabolInc/action#1744]
## Issue - Enhancement

This story outlines the ability for clients to manipulate reflection groups on the backend.

### Acceptance Criteria (optional)
- Any Team Member can create a Reflection Group given any number of Reflections
- Any Team Member can add a Reflection to a Reflection Group
- If a Reflection in Group A is added to Group B, it is removed from Group A
- Any Team Member can remove a Reflection from a Reflection Group
- Reflection Groups are given an initial display name such as “Group 1”
- Reflection Groups can have their display names edited, but they cannot be made the empty string or some non-visible name, or a name that is already taken
- Team Members can subscribe to the Reflection Groups for the meeting; when they’re created, edited, and renamed
- Removing the penultimate Reflection from a Reflection Group removes the group
- Groups cannot be modified once the meeting has moved past the grouping phase

- **Estimated effort:** 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Depends on #1742

**Comment by mattkrick** [comment]
is the group name plaintext or draft-js? it should be draft-js if you'd like it to be: bold, italic, etc. add emojis, mentions, anything other than simple plain text.

**Comment by dan-f** [comment]
IMO the name should be a regular old utf-8 encoded string
