### ISSUE TITLE
Retro Frontend: Grouping Reflections

### ISSUE THREAD

**Issue by dan-f** [ParabolInc/action#1745]
## Issue - Enhancement

This story outlines the ability to group reflections together during the group phase of the retro meeting.

### Acceptance Criteria (optional)
- Show all the Reflections from the Create Phase, layed out in some sort of grid
- Team Members can drag and drop a Reflection onto another Reflection. When this happens, a Reflection Group is created with an initial display name.
- Team Members can in some way see all the cards in a Reflection Group
- Team Members can drag more cards onto a Reflection Group
- Team Members can drag cards out of a Reflection Group
- Team Members can edit the name of a Reflection Group
- (carried over from issue #1729 / PR #1872) When dragging cards out of retro groups, the "dragging" state is visible, including the user that is dragging
- Once the Facilitator moves on from the Grouping Phase, Team Members can no longer edit Reflection Groups

OPTIONAL: - There’s a two minute timer (#1834)

- **Estimated effort:** 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by dan-f** [comment]
From @ackernaut's [comment](https://github.com/ParabolInc/action/pull/1872#issuecomment-373178565) on #1872:

> For #1745, I would clarify that when a card is being dragged out of a group, and that group is open for a user, that the user sees the original position MP indicator.
> - I open a group, and grab a card, I see my 50% opacity with name.
> - Another has the same group open, they see that I grab a card 100% opacity with name.
Another has the same group closed, they don’t see the feedback.

**Comment by mattkrick** [comment]
Stuck on #1743
