### ISSUE TITLE
Retro Frontend: Voting

### ISSUE THREAD

**Issue by dan-f** [ParabolInc/action#1747]
## Issue - Enhancement

This story adds the ability to vote on Reflection Groups for retro meetings, on the frontend.

### Acceptance Criteria (optional)
- Team Members see all Reflections and Reflection Groups
- Team Members see their available votes
- Team Members can add their vote to a Reflection or Reflection Group
- Team Members can remove their vote from a Reflection or Reflection Group
- Team Members can only see their own votes
- Team Members cannot vote once the Voting Phase is no longer the active Phase
- Once the Vote Phase starts, all ungrouped Reflections are turned into one-item Groups to simplify voting logic ([see Figma design for details](https://www.figma.com/file/ClYTi13FvvTZ2y03Om8wNrXq/Retro-Views))

- **Estimated effort:** 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
@dan-f, this needs an estimated effort
