### ISSUE TITLE
Retro Backend: Moving the meeting

### ISSUE THREAD

**Issue by dan-f** [ParabolInc/action#1748]
## Issue - Enhancement

This story will add the ability to move the retro meeting through its various phases on the backend.

### Acceptance Criteria (optional)
- The facilitator can move the meeting between phases and phase items
- When the facilitator moves from the Grouping to the Voting phase, the various discussion phases are computed and appended to the meeting
- This is done by picking the top-N-voted (N to be determined) Reflections / Reflection Groups and adding them to the Discussion Phase

- **Estimated effort:** 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
@dan-f this needs an estimated effort

**Comment by jordanh** [comment]
Needs to #1745 completed before being able to fully implement

**Comment by jordanh** [comment]
Possible dup of #1740

**Comment by jordanh** [comment]
Closing, likely duplicating other work
