### ISSUE TITLE
Retro Frontend + Backend: Discussion

### ISSUE THREAD

**Issue by dan-f** [ParabolInc/action#1749]
## Issue - Enhancement

This story outlines the ability to discuss Reflection groups during the discussion phase of the meeting.

### Acceptance Criteria (optional)
- Team Members can see the current Reflection Group or Reflection being discussed
- Team Members can add Tasks inspired by their reflections just like they add Tasks inspired by Agenda Items during Action Meetings
- Team Members can add Tasks for Reflections / Reflection Groups that are not currently being facilitated
- Team Members can reorder the Reflection Groups
- **Optional**: Team Members see a N-minute timer which roughly informs how long they should be discussing the current Reflection / Reflection Group for

- **Estimated effort:** 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
closed by #1986
