### ISSUE TITLE
Agenda Item Assign Inline

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#175]
## Issue - Enhancement

When a device-less teammate needs an agenda item added to the queue, the control needs an inline assign menu so that a teammate who is entering in agenda items can quickly add the device-less teammate’s avatar to the item.

**Estimated effort:** 15 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))
- [ ] User can trigger the inline menu by typing the `@` character.
- [ ] User can optionally trigger the menu by tapping the `@` avatar placeholder graphic/button.
- [ ] User can interact with the menu via mouse. -or-
- [ ] User can type first characters to filter the list and hit up, down, enter to confirm.

**_Current view design_**:

![agenda-first-call-inline-assign 2x](https://cloud.githubusercontent.com/assets/307286/17540790/f0123b0c-5e7e-11e6-9b7a-007687575f3e.png)

**_Older view designs, but they show the states of the interaction_**:

![agenda-list-add-item 2x](https://cloud.githubusercontent.com/assets/307286/17540635/3d607ba0-5e7d-11e6-9bfb-23297438b73b.png)
![agenda-list-add-item-hover 2x](https://cloud.githubusercontent.com/assets/307286/17540631/3d5e0d16-5e7d-11e6-9c8d-a99f1890e791.png)
![agenda-list-active-empty-input 2x](https://cloud.githubusercontent.com/assets/307286/17540633/3d5e3d68-5e7d-11e6-898e-029c4a38cefa.png)
![agenda-list-assign-inline 2x](https://cloud.githubusercontent.com/assets/307286/17540632/3d5e2dd2-5e7d-11e6-8423-96fc0f43d4d3.png)

**_A concept, using the agenda item list to capture in advance of meetings on the dashboard_**:

![team-view-agenda-item-list-v4 2x](https://cloud.githubusercontent.com/assets/307286/17540634/3d5e767a-5e7d-11e6-9558-2d66050b231e.png)

**Comment by jordanh** [comment]
**Estimated effort:** 5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
I've added this to our [Equity For Effort](https://github.com/ParabolInc/action/projects) program. If you out there on the internet are would like to help us implement this in exchange for points that can qualify for equity in Parabol Inc., please leave a comment with how many points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md)) you'd be willing to do this work for.
