### ISSUE TITLE
Retro Backend: Ending the Meeting

### ISSUE THREAD

**Issue by dan-f** [ParabolInc/action#1750]
## Issue - Enhancement

This story outlines the ability to end the retrospective meeting on the backend.

### Acceptance Criteria (optional)
- The Facilitator can end the meeting just like they would end an Action Meeting
- This generates a Summary (with Email / Page)

- **Estimated effort:** 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
closed by #1986
