### ISSUE TITLE
Retro Frontend: Summary Email / Page

### ISSUE THREAD

**Issue by dan-f** [ParabolInc/action#1751]
## Issue - Enhancement

This story outlines the ability to view a summary email and summary page upon completion of a retro meeting.

### Acceptance Criteria (optional)
- The Summary Email / Page shows new tasks
- The Summary Email / Page shows discussed Reflections / Reflection Groups
- The Summary Page offers an affordance to go to the Team Dashboard

- **Estimated effort:** 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
Getting started with the new section that shows discussion topics that were voted for (including the reflection cards).

**Comment by ackernaut** [comment]
Getting started on a PR, see #1960

**Comment by ackernaut** [comment]
Calling this stuck until we wrap up the retro phases. A PR has started (#1960)

**Comment by ackernaut** [comment]
Shipped as part of Sprint No. 6
