### ISSUE TITLE
dash sidebar styles bad when team settings overflow

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#1754]
currently, i see this:
![screenshot from 2018-02-14 13-30-54](https://user-images.githubusercontent.com/5514175/36229223-62a327c4-118b-11e8-8dbc-3818c5fb16ac.png)

AC
- sidebar looks the same, no matter how much stuff is in the main content panel

estimated effort: 11 points

**Comment by ackernaut** [comment]
Oh, wow! I wonder if something changed with how browsers or handling flex layouts or if we changed something. I think some of these may be naturally addressed with working on updated layouts that support search & filtering.

**Comment by ackernaut** [comment]
### Acceptance Criteria:
- Dashboard views have appropriate overflow when content sections are lengthy.
### Estimated Effort:
- 13 points

**Comment by ackernaut** [comment]
Pushed a fix today. The main content area for dashboard views will scroll when overflown.
