### ISSUE TITLE
Signup Page

### ISSUE THREAD

**Issue by dan-f** [ParabolInc/action#1757]
## Issue - Enhancement

This story implements the the [new signup page](https://www.figma.com/file/dlFsGHNy7TclcNQDaacFP0pR/Signin%2FSignup).

### Acceptance Criteria (optional)
- Can sign up with 3rd party auth
- Can sign up with username/password
- Must confirm password
- Error & validation states for username/password/confirm password
  - passwords not matching
  - email being taken
- Upon successful account creation, you are redirected to the welcome wizard

- **Estimated effort:** 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
This one also needs an estimated effort @dan-f
