### ISSUE TITLE
Decide on using emotion-js moving forward

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#1761]
### Background
Right now, we use a forked version of aphrodite. It isn't great because:
- we can't stream from the server (we must generate everything, then send it)
- styles load ASYNC (this is just awful for when we're trying to place things)
- styles are added in runtime, not build time
- global styles are really hacky (but hey, they work for now, so let's keep em)
- child styles aren't possible
- new css rules aren't possible
- we still have to use inline styles for things like font-awesome, application state, etc. 

The async loading is my biggest tension. It causes really ugly menu flickers in menus and animations.
Emotion fixes all of these! I've been watching it for awhile now and my 1 reservation was that there were _too many_ ways to accomplish styling with it. With their v9.0.0, they've removed some of the patterns that I didn't care for (namely the compose css-modules thing). The community has also seemed to rally around it. https://github.com/emotion-js/emotion

I'm not proposing that we get rid of our aphrodite fork. That'd be way too much work. Instead, I'd like to build new components with emotion for the primary benefits of:
- no placement-related errors due to styles not being applied 
- cleaner code where all styles live in the same place
- ability to use new css things like grids

### Acceptance Criteria
- Decide yes or no

**Comment by jordanh** [comment]
This is interesting. Perhaps we could pick a thing to implement using emotion and see if we like it? I don't think we should stick this on the critical path (in case we encounter unforeseen challenges) but I'm open to suggestions for something we could safely try...

**Comment by ackernaut** [comment]
But what is the estimated effort of deciding yes or no? 😜

**Comment by ackernaut** [comment]
PS. I’d be willing to explore using it on some views/components to get a feel for it. But I’m not sure how much effort is required to include it alongside our existing patterns of writing styles. I imagine we declare the dependency then import the parts we need and try newer patterns?

**Comment by jordanh** [comment]
Going to take a stab and add estimated effort:

**Estimated effort:** 12 points
