### ISSUE TITLE
Improve our babel strategy

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#1762]
### Background
We don't follow the current best practices wrt babel. For example, we don't tree shake & we have a bunch of babel-register files across the app. This is bad for 2 main reasons:
- The application bundle is much bigger than it should be
- Building the app in CI takes a few minutes longer to deploy than necessary
- Webpack takes much longer than it should to compile

Acceptance Criteria:
- Upgrade to babel 7
- Implement tree shaking
- Fix SSR strategy
- maybe use an ES6 uglifier to further reduce bundle size & parse size. we can still build both & send down the correct one depending on if the client can handle it.

Estimated effort: 13

**Comment by jordanh** [comment]
@mattkrick needs estimated effort...

**Comment by mattkrick** [comment]
added!
