### ISSUE TITLE
Implement a slack-like scroll bar

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#1763]
The default scroll bar is just ugly as can be. Slack has a pretty one, but it's implementation is very in-depth. I think that's because they want to support all the browsers.

We can just style ours like https://scotch.io/tutorials/customize-the-browsers-scrollbar-with-css

Acceptance Criteria:
- A nice looking scroll bar in the Dash sidebar & the kanban columns

Estimated Effort: 11 points

**Comment by ackernaut** [comment]
This may make for a good improvement to the `<ScrollableBlock />`. We could consider having an optional prop to constrain it to horizontal or vertical scrolling where it enhances the space with fancy scrollbars and the shadow that appears on the end that is overflown (as a visual affordance). We may could yank that if the scrollbars are always visible.

**Comment by mattkrick** [comment]
promoting this because our growing number of ugly scrollbars is gonna become a large debt.

**Comment by jordanh** [comment]
I think we can unstick this one, right @mattkrick ?
