### ISSUE TITLE
Design: Card design, Card grouping and Theming

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1767]
## Issue - Enhancement

Cards may or may not be given a "theme". A theme may also consist of a group of more than one card.

_Idea:_ when a user creates a card, they may also suggest a theme.

### Acceptance Criteria (optional)
Implementers can see how:
   - Card changes:
      - What specific changes/affordances are given to a card used within the retrospective
   - Card grouping and theming:
      - Users can create a group by dragging and dropping one card on another
      - The hover state showing the user what will result if they drop one card on another
      - Clicking/hovering on a group to expand it into its constituent members
      - Dragging a card out of a group
      - Removing the last card from a group, removing it's title/grouped status
      - A view of a group that has needs a title
      - A view of a group that is having its title edited
      - Consideration from how to add single cards to the agenda
      - Validation states:
         - Entering a duplicate title
         - Entering an empty title

Validating these designs with:
   - August Public

- **Estimated effort:** 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
Going to start building a list of Acceptance Criteria for the UI that can be copied to respective stories:
- Reflection cards have an explicit control for deleting the card during the Think phase.

**Comment by ackernaut** [comment]
@jordanh the list of AC above roughly reflects what is illustrated in Figma.

**Comment by jordanh** [comment]
_Great work!_ Let's move this to the Done column.
