### ISSUE TITLE
Retro Design: Voting

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1768]
## Design

We want a high-fidelity artifact that informs the front-end implementation of retro voting UX.

### Acceptance Criteria

- Designed a visual concept or prototype that demonstrates views, components, and states for #1747 

### Estimated effort

- 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
Here are the Acceptance Criteria supported by the views conceptualized in this Figma doc:

### Simple voting mechanics:

- Users see a subtle [check] icon hovering top right of a card or group where they can add their first vote. Toggling removes the vote that was added.
- Once the first vote is added, an additional [check] icon appears if they can place additional votes. (We are considering allowing up to 2 or 3 votes to increase diversity and empathy of feedback. I think good grouping will keep the agenda small.)
- A user cannot add more votes but can toggle votes off.
- The votes (as toggle doff) collapse back down toward 1 icon that is off or on.
- There is a subtle animation when toggling votes
- I can only see my votes on cards and groups during the Vote phase.
- I can see how many votes I have left / have placed.
- I can see how many votes the team has left / has placed.
- I don’t think we block the facilitator from being able to move forward in case somebody loses connection, freezes up etc. I think the facilitator gets a prompt when moving on in the UI “Ask your team if everybody is done” — this could also allow folks from refraining from some votes, etc.

### Theming single cards (grooming in Group phase or Vote phase?)

- a) We can optionally show a view at the end of the Grouping phase that requires folks to add a theme to any cards that were not grouped. This sets the stage for more equal footing during voting, as all cards and groups will have a theme. The facilitator would either need to go back to the previous view (if we allow that) to allow more grouping, or perhaps we could allow additional grouping here. But really I think we need to constrain to keep the meeting forward.
- b) We can optionally show a view at the end of the Voting phase that requires a theme to be added to single cards that were voted for. This approach might be faster, because we could get right into voting without adding themes to single cards, and only groom single cards that were voted for.

### Building the agenda based on the vote

- After the Vote phase ends, the agenda appears showing the theme (as agenda topics) of all groups and single cards that got voted for. Those that didn’t have a vote don’t make the cut.
- The agenda topics are in order from most votes to least votes.
- The retro can be ended early, not all topics have to be covered.
- For each agenda view, we show the number of votes that each topic received along with the reflection card(s) on a grid view and the theme text.
- I think we DO NOT push list debt forward to the action meeting. I think we encourage folks to open the summary if there were any topics they want to refer to and discuss outside of the meeting.

**Comment by jordanh** [comment]
Super great work! I look forward to testing this with the August crew. I left a few comments [on the clickable proto](https://www.figma.com/proto/ClYTi13FvvTZ2y03Om8wNrXq/Retro-Views?node-id=65%3A1&scaling=min-zoom).

I look forward to seeing more comments from @ackernaut, @dan-f, and @mattkrick.

**Comment by dan-f** [comment]
Oh excellent. Taking a parabol task to review.

**Comment by ackernaut** [comment]
Yes! My next steps are address the feedback and it will also been see in the full prototype for #1737

**Comment by dan-f** [comment]
I'm going to begin my review. The figma doc says "See top left in Figma nav", but I'm still not sure what to do 😆 help?

**Comment by dan-f** [comment]
Ok, clicked through the prototype. I'll collect my thoughts by updating this comment, but just wanted to say upfront that the prototype is totally gorgeous! Excellent work!

**Comment by ackernaut** [comment]
Done in Sprint No. 3
