### ISSUE TITLE
Bug: duplicate agenda item regression

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1771]
## Issue - Bug

@tayamueller notices this one this weekend too.

When User A adds agenda items to a board, and User B does some (as of yet unidentified steps), User B can see duplicate agenda items:

![image](https://user-images.githubusercontent.com/103000/36385328-1fd9ebb6-1547-11e8-85a4-ed448f001fa9.png)

It's not clear if this is created by having multiple tabs open on the same account, or what the specific conditions may be.

- **OS:** macOS
- **Browser:** Chrome
- **Estimated effort:** 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### Acceptance Criteria (optional)
Users can:
   - add and browse agenda items without having them duplicate on the team dash

**Comment by jordanh** [comment]
Notes:

The duplicate agenda items remain when the page is refreshed.

They also remain when navigating to the team lobby:

![image](https://user-images.githubusercontent.com/103000/36385512-9cd5f24a-1547-11e8-9861-9b622f7990ae.png)

**Comment by tayamueller** [comment]
notes: I entered "Bojan" first, then "Pilot", then reordered to put Pilot ahead of Bojan. 

I saw nothing amiss, but after seeing this I hit refresh and then also saw the above mess

**Comment by tayamueller** [comment]
2 more instances today:
![more bug](https://user-images.githubusercontent.com/14892189/36398610-f2435f6c-1595-11e8-9857-375ba4b10cb0.jpeg)

![gld bugs](https://user-images.githubusercontent.com/14892189/36398614-f577e89c-1595-11e8-997d-3a20ab48da17.jpeg)
