### ISSUE TITLE
broken/crashing team page

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#1780]
## Issue - Bug

-User's Team Dashboard is slow to load, doesn't have functionality, then crashes.
-Seems to be isolated to this Team (my other 6 active Dashboards are fine)
-Happens repeatedly in different tabs, etc.

video of problem:
https://zoom.us/recording/play/FFaw1Z8_gwbmX-S7EBf0288V6LJdDvrXg0lNChDebSKUwzpHIUeoVBsBowBK1Aqr 

### Acceptance Criteria (optional)
Users can:
   - Do this
   - Do that
   - Cannot do that

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
side effect of the reconnect bug that created like 5000 cards on the dash. fixed
