### ISSUE TITLE
bug in agenda

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#1785]
## Issue - Bug

[see fw email from user]

Hi there! There seems to be something off with the agenda on our team page. It seems to have pulled agenda items from our last team meeting and put them in over and over again. Just wanted to flag this!

### Acceptance Criteria (optional)
Users can:
   - Do this
   - Do that
   - Cannot do that

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

 
--

**Comment by mattkrick** [comment]
fixed!
