### ISSUE TITLE
Link editor button not working on click

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1787]
### Reproduction Steps
- Create a task card
- Add text
- Using `command + k` begin adding a link to selected text
- Instead of pressing enter, try tapping on the button
- The editor menu doesn’t commit, no link on the text

The focus or tab index seem to be the problem.

Screen recording (the 2nd time I pressed enter)

http://recordit.co/Pji1YpdGvB

### Acceptance Criteria
- Users can tap on the link editor button to commit the link addition/changes.

### Estimated effort
- 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Note**: may be fixed alongside #1829

**Comment by jordanh** [comment]
Dup of #1791
