### ISSUE TITLE
Notification archive designed

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1792]
### JTBD

When I’ve taken an action or cleared my notifications (perhaps in error), I’d like to see what the notification was, so that I can refer back to what I was told:

### Acceptance Criteria
Users can:
  - Navigate to the notifications archive from the notifications center
  - See archived notifications in a list view 
  - If all of the user's organizations are upgraded to Pro, they can see all of their notifications
  - If one of their accounts is on the free tier they:
    - Do not see any past notifications
    - See a nag to upgrade their org(s) to Pro

### Estimated Effort
- 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
@jordanh I updated the acceptance criteria (added “See archived notifications in a list view” and added an estimated value of 12 points.

**Some extra thought** (you’re the PM!): I’m not sure what our razor is for what a paid feature is or not, but I have a feeling that it should be more about feeling the pain of closing a loop even over limiting a utility. If that were true, then I think limiting the notifications may not pass. This seems more like a utility than a primary loop to be closed. Also, by this razor, as I user I should feel like I’m missing a powerful tool that I do not have, not annoyed by a limited tool that I already have. I’m just expressing this thinking while I feel the tension, take it as you will. :)

**Comment by bjanjanin** [comment]
@jordanh Sounds good to me. Another option for the free tier: 

- Users with free accounts see the last 5 notifications.
- They also see a nag to upgrade their org(s) to Pro.

**Comment by jordanh** [comment]
Iceboxing for now
