### ISSUE TITLE
New Auth Style Cleanup

### ISSUE THREAD

**Issue by dan-f** [ParabolInc/action#1796]
## Issue - Enhancement

All the new auth UI was implemented using UI primitives. To more closely match the wireframes / new branding, we should update all the auth pages to match the wireframes more closely.

### Acceptance Criteria (optional)
Users see:
   - The correct new brand colors (purple nav bar, purple headings)
   - No "beta" messaging
   - Warm, rounded submit buttons

- **Estimated effort:** 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
Some of my work (next in the queue) involves updating the palette and typography in the app…meaning this gets applied to existing components. Eg. no need to create new buttons from scratch as they will benefit from the update in both look and color etc. Perhaps we “stuck” this issue after #1766 and #1661 .

**Comment by dan-f** [comment]
Right on, I'm cool with that. Take a look at #1805 implementation examples, in case it's of use!

**Comment by ackernaut** [comment]
Ah, sounds good! I’m trying to block work in the codebase (and get out of Figma) for Wed (2/28) and Thurs (3/1) of this week, all geared toward first steps of new palette, type, style. Can I look at this on Wed?

**Comment by dan-f** [comment]
That sounds great to me. Please feel free to pull on me if you want to chat about the implementation or pair on it or anything. Looking forward to reviewing what you come up with!
