### ISSUE TITLE
Production deployment of new authentication pages

### ISSUE THREAD

**Issue by dan-f** [ParabolInc/action#1798]
## Issue - Enhancement

There are a few bits of work to be done before we can deploy this thing:

- We'll need to flip the `newSignIn` release flag to `true`. This will later be removed in #1799, once the feature is stable on production
- We'll need to update configuration on Auth0 to make sure that we can make use of the new cross-origin signin. At the very least, I think we're going to have to update the accepted callback URIs to include `/signin`, but we'll want to make sure other settings are appropriate too. We should do this the prod, staging, and dev environments.

### Acceptance Criteria (optional)
- `/signin` included in auth0 callback URIs for all environments
- other production settings verified

- **Estimated effort:** 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
@dan-f is there any other pre-requisite we need to do, any other design work, before we can prioritize this issue?

**Comment by dan-f** [comment]
@jordanh as far as I'm concerned, this is prioritize-able as-is!

As for whether it's shippable - this is dependent on #1848. I believe that @ackernaut wanted us to incorporate his new styling patterns into the pages, which is captured in #1848.

**Comment by jordanh** [comment]
I see it now. Thank you!
