### ISSUE TITLE
Sunset Auth0 Lock

### ISSUE THREAD

**Issue by dan-f** [ParabolInc/action#1799]
## Issue - Enhancement

This describes the final bit of clean up involved in migrating to the new cross-origin auth pages. We'll just need to remove the `newSignIn` release flag (as if it were always true), and remove the old landing page, including the auth0 lock.

### Acceptance Criteria (optional)
- Default experience stays the same; you still see the new auth when you reach the home page
- No more LandingPage or Auth0Lock
- auth0 lock removed from the package dependencies
- `newSignIn` release flag removed, and all the toggle points "flattened out" such that the new code paths are statically live, while the old ones are simply removed

- **Estimated effort:** 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Blocked by #1848 and #1798
