### ISSUE TITLE
Meeting summary re-routing in browser?

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1804]
### Repro Steps
- When team A, call it Product (I’m on the team and participate in the meetings), ends the meeting, the meeting summary view shows in the browser. I leave the summary in the tab, and pay attention to other tabs. Later…
- When team B, call it Sales (I’m on the team but don’t participate in the meetings)), ends their meeting, my summary view (for Product) tries to reload. It shows an error. I refresh and am on the Sales meeting summary.

### Additional Bug
- If a user stays on an action summary view, and another team of which they belong completes an action meeting on the other team, this view will try to update to the show the new summary but gets an error and the message about developers being notified.

### Estimated Effort
- 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### Acceptance Criteria
- Users are not redirected from the meeting summary of one team when another team ends their meeting.

**Comment by ackernaut** [comment]
I left my Meeting Summary from Product open in browser today, and once again it did get re-routed to Sales automatically once their meeting ended. It’s not a 🐛 , it’s a feature 😉 !

**Comment by ackernaut** [comment]
Happened again…I was on My Dashboard, but when the exec team finished their meeting I was re-routed to the exec team meeting summary.

**Comment by ackernaut** [comment]
I would like to nominate this for bug-fix budget for Sprint No. 9 if not sooner. :)

**Comment by jordanh** [comment]
This is definitely still a thing, but #2118 tho.
