### ISSUE TITLE
remove/fix csstransition

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#1808]
## Issue - Bug
csstransition doesn't work with any css-in-js strategy because any re-used rule will appear higher up in the cacade & override the newer rule. for example, `class="enter enter-active"` is not OK, it needs to be wrapped like `class=css(enter, enter-active)` to guarantee proper cascading (true for aphrodite & emotion). i'm pretty impressed that we got as far as we did!

to move forward, we need to write a custom "setClass" to replace the addClass and removeClass handlers.alternatively, we could use inline styles, but that is difficult/impossible because the class is applied to the child & if the child is a React.Fragment, then it won't pass down the styles. 

### Acceptance Criteria (optional)
Users can:
   - use AnimatedFade with different params on different components just fine

- **Estimated effort:** 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Iceboxing for now
