### ISSUE TITLE
bug: cannot read property 'hideAgenda' of undefined [0.29.1-1]

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1809]
## Issue - Bug

Encountered during `0.29.1-1` staging release.

Reproduction steps:
1. Sign up as a new user
2. Invite a second user within the signup wizard (not certain if this is required, but the step was taken)
3. When redirect occurs to team's dashboard, see below UI error and exception:

![image](https://user-images.githubusercontent.com/103000/36803740-548888f4-1c6d-11e8-830c-b721eab518a2.png)

Exception:

![image](https://user-images.githubusercontent.com/103000/36803666-18a61f7c-1c6d-11e8-9f67-aa7cc933e343.png)

- **OS:** macOS
- **Browser:** Chrome
- **Estimated effort:** 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### Acceptance Criteria (optional)
Users can:
   - New user is able to sign up
   - New user can complete welcome wizard
   - New user can be redirected to dash without seeing error

**Comment by jordanh** [comment]
When I press reload, the error does not occur again.

**Comment by dan-f** [comment]
Hm. I cannot reproduce this particular error, though I'm seeing a different failure.

When I sign up without inviting anyone, all goes fine.

When I sign up, invite someone w/ the welcome wizard, and give them a priority, I get infinite ducks with no errors (no failures observed coming from the server).

<img width="1552" alt="screen shot 2018-02-28 at 1 30 23 pm" src="https://user-images.githubusercontent.com/2146312/36805541-ae2f1936-1c8b-11e8-806f-c72c490f8b68.png">

**Comment by dan-f** [comment]
Another failure with the invitation flow:

When I sign up, invite someone through the welcome wizard, and *do not give them a priority*, I get a blank screen with a dreaded `cannot read property 'undefined' of undefined` runtime error:

<img width="1129" alt="screen shot 2018-02-28 at 1 32 36 pm" src="https://user-images.githubusercontent.com/2146312/36805718-2546523c-1c8c-11e8-8d5b-e7901e8b1235.png">

**Comment by dan-f** [comment]
## 0.29.0 Production

Here's what I get when I go through the welcome flow with an invitation & priority setting:

<img width="944" alt="screen shot 2018-02-28 at 1 39 12 pm" src="https://user-images.githubusercontent.com/2146312/36806028-cd770b86-1c8c-11e8-8853-a0006c9d12e3.png">

When I go through the welcome flow with just an invitation (no priority setting), I get no failures.
