### ISSUE TITLE
bug: when I have no teams, duckies on creating new org and team

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1813]
## Issue - Bug

Reproduction steps:

1. Log in as User 1 and invite User 2 to team, User 2 must be a new user with no pre-existing teams
2. Accept invitation as User 2
3. Remove User 2 from their only team
4. As User 2, create a new Org and new Team
5. Observe duckies

- **OS:** macOS
- **Browser:** Chrome
- **Estimated effort:** 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### Acceptance Criteria (optional)
Users can:
   - Create new org and new team if they no longer belong to any teams

**Comment by jordanh** [comment]
Note: there are no visible exceptions on the client or server ☹️

**Comment by mattkrick** [comment]
how is step 3 accomplished? do you promose User 2 to team lead first? or was that supposed to read User 2?

**Comment by jordanh** [comment]
You caught my typo. Fixed!

**Comment by jordanh** [comment]
@mattkrick reports that he couldn't reproduce. I will take a card to try and repro

**Comment by jordanh** [comment]
I haven't been able to repro this one for awhile either. I am going to close it for now. Will re-open if I see it again.
