### ISSUE TITLE
query built to identify WHO our Pro users are

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#1826]
### Acceptance Criteria (optional)
- Parabol Sales team can access list of Pro user emails

- **Estimated effort:** 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
After deploying #1823 we should start receiving this information into HubSpot automatically. However, I think we should have a utility query as a failsafe.

**Comment by tayamueller** [comment]
The solution should be easily workable for non-technical, non-origination team salesforce.

**Comment by ackernaut** [comment]
Done in Sprint No. 6
