### ISSUE TITLE
Link editor flashes, disappears

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1829]
## Bug

When tapping to edit an existing link, the editor flashes and disappears.

[recordit](http://recordit.co/FKsFqAEuyX)

### Acceptance Criteria (optional)
- Users can edit their links on cards

### Estimated Effort
- 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Note**: may be fixed alongside #1787

**Comment by ackernaut** [comment]
Update: I can see the link editor if I add a space after the link and then move the cursor toward the link.

**Comment by jordanh** [comment]
Same root cause as #1791, let's restest after merging #1829

**Comment by ackernaut** [comment]
Looks like this was fixed, tested again locally!
