### ISSUE TITLE
UI updates (next steps)

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1833]
## Enhancement

We have been updating the styles in the UI including palette, typography, and theme/aesthetic. We are also beginning to update layout and IA to support new feature UX. Here are next steps for reusable UI components:

#### Done in 2nd pass (PR in review #1939)

- [x] Forms updated to match latest style guide and concepts
- [x] Email templates are polished according to latest style guide
- [x] Cards polished to latest concepts (including box-shadows, code blocks)
- [x] Revisit Settings Views (including Pro™ badge etc., integration views, etc.)
- [x] Revisit notifications by type

#### Done in first pass (and PR merged)

- [x] Dashboard headings updated (possible moving of the search filter)
- [x] Buttons match latest visual concepts
- [x] Menus match latest visual concepts (including: box-shadows, link editor/viewer menus)
- [x] Updated GH integration card

### Estimated Effort
- 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
@ackernaut can we make the yellow ring around the avatars more pronounced? or give them a crown? right now, that yellow on a gray background is really hard to see.

**Comment by ackernaut** [comment]
Closed by #1939
