### ISSUE TITLE
Facilitator timer

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1834]
## Enhancement

When facilitating a meeting, the facilitator would like to optionally set a minimal timer so that they are motivated to keep the meeting moving along and track and take discussions and next steps outside of the meeting.

### Acceptance Criteria
- coded as a set of components presented in Storybook
- The timer shows in the facilitator control bar #1676 to the facilitator
- The timer starts at 2:00. Hovering a timer that is not running shows a tooltip “Tap to start timer”
- While the timer is running, the facilitator can tap the timer to add a minute.
- When the time is up it stays at 0:00 but perhaps has a warm color to indicate that time is up.
- Hovering the running timer, or a timer at 0:00, shows a tooltip “Tap to add 1 minute”
- The timer uses the cooler, secondary UI colors until time is up. See the latest design concepts in Figma.
- The timer can be optionally added to the control bar in any view where it makes sense
- The timer does not block forward navigation, it’s just an async tool

### Estimated Effort
- 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
See #1526 and #1525 for reference

**Comment by tayamueller** [comment]
see #933

**Comment by mattkrick** [comment]
probably a good jumping off point: https://reactjsexample.com/renders-a-svg-circle-progress/

**Comment by ackernaut** [comment]
Had an idea for a quick timer control, [see concept in Figma](https://www.figma.com/file/CjRSl4d5IZh3MspudYhgBsPt/Meeting-Controls?node-id=0%3A1) 🔒

**Comment by jordanh** [comment]
@ackernaut could you create a validation issue for your latest designs please?

Iceboxing this one for now

**Comment by jordanh** [comment]
Pulling this out of the icebox, got a fresh [user](https://app.hubspot.com/contacts/3888472/contact/3785951) request:

> It would be great if you could add a timer to some of the phases in the retrospective like on the Reflect, Group and Voting pages sections.

**Comment by ackernaut** [comment]
Close in favor of #2804 and its implementation issues
