### ISSUE TITLE
Meeting help dialog

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1835]
## Enhancement

A meeting help dialog gives us a place to explain context and add tips for the meeting participants to support users new to the theory behind our meeting types. This work basically represent a simpler, low-effort way to purpose some of our facilitation and meeting help discoveries from onboarding.

### Acceptance Criteria

- First step, build as a component in Storybook
- Any meeting participant can toggle the help dialog
- It shows in the facilitation control bar for facilitators
- **Optionally**, it can be triggered to open as part of an on-boarding or tutorial script
- It floats over the UI content as to no detract or prevent users from interacting
- It floats in concert with any “rejoin facilitator” or similar controls.
- It can toggle open/closed
- It can be hidden in views where the context or content makes sense to do so
- It supports purpose, tips, and help text.
- It can link to evergreen content like the “Getting Started” guide
- **In the future**, it can support a sectional video embed

#### Possible Next Steps
- Script the v1 contextual help text and add to meeting (action/retro) views

### Estimated effort
- 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
See #1683 and #1673 as this should satisfy the basic UI/UX affordances without having to address a larger on-boarding UX and logic.

**Comment by ackernaut** [comment]
@mattkrick per our earlier conversation, I think we need an abstract `<LoadablePopup />`:
- It can optionally be toggled by hovering the toggle, tapping the toggle, or by event
- We can declare the presentational component that shows as the dialog’s LoadableContent. I would think that it just wraps children as the content.
- We can optionally include a toggle to close the popup using a method/callback prop as part of the LoadableContent (say it has it’s own close button apart from the declared toggle).
- We can declare the toggle.

The idea that is pop ups in place relative to the toggle, but it’s not a menu or a modal.

We could then use the LoadablePopup for this use case, and have a presentational component for meeting views that shows blocks of content based on the phase, as you were describing?

Just taking these notes here from our conversation? Did I miscommunicate anything?

**Comment by mattkrick** [comment]
this is perfect! the work is 90% done with the `LoadableModal` component, it just needs an optional param that uses `getCoords` to place it next to the toggle instead of dead center.

**Comment by ackernaut** [comment]
Picking back up with this!

**Comment by ackernaut** [comment]
Done in Sprint No. 6
