### ISSUE TITLE
Update icons in app

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1842]
## Enhancement

New icons are being used throughout the visual concepts as we are updating the look and feel. Let’s track implementation here.

### Acceptance Criteria
- New icons are included and bundled in a performant way
- New icons are easy to use when implementing UI
- Usage of icons reflects latest visual concepts
- All components that use icons are updated
- Reference: [Icon Design & Usage](https://docs.google.com/document/d/1y03K2_ikxh8WKI2bGrwwUJxBlT33BleAXmUO7ZoclQs/edit?ts=5aa0f6b7)

### Estimated Effort
- 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
After merging in #2434 we are down to:
- `import FontAwesome` = 20 instances
- `import StyledFontAwesome` = 32 instances
This shouldn’t be too hard to knock out, and I only imagine a few places where sizing may need some love.

**Comment by ackernaut** [comment]
Two places we need brand icons, perhaps SVG format would be fine. Would be nice to find a set:

- GitHub integrations
- Slack integrations

**Comment by ackernaut** [comment]
Looking for some thoughts here @mattkrick . Unlike FontAwesome, Material Design icons do not include:

- GitHub
- Slack
- Google
- Credit card brands (Visa, Mastercard, Discover, etc.)

Also, we have a few icons used for the avatar check-in badges that would probably not look good at 18px, but we could try. In the short term, should we:

- Keep using FontAwesome for a handful of use cases. This is not cool because the entire font file would be downloaded for only a few cases: in dashboards where cards are present (GitHub icon) and in meetings (avatar badges).
- Use some SVG files. This is actually what I had in mind as a fallback for any MD icons that weren’t included in the font file, since they do seem to provide SVG files for more of the icons. I wouldn’t want to load the same SVG in the view multiple times (eg. lots of cards with the GitHub icon). This might not be bad if the SVG files in question were optimized for minimal footprint. Using inline `<svg>` allows us to style the color. Referencing an SVG file in an `<img>` does not and would require exact color usage in the files. If we reference the SVG via `<img>` the browser only downloads the binary once TMK. But we would rely on hover states that used opacity etc. and not color.

**Comment by mattkrick** [comment]
we should be able to mix & match, either by making our own font using icomoon or similar or just falling back to font awesome icons (or another source, for example: https://materialdesignicons.com/)

i'm not too worried about the performance impact of SVG if you go that route

**Comment by ackernaut** [comment]
I’ve done the icomoon thing before. I’d really like to avoid maintaining our own font. 🤢 

I think for now I may just fallback to FontAwesome and ponder a better path.
