### ISSUE TITLE
Summary cards; long links stretch cards

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1845]
## Enhancement

Long links stretch the table-based layout for the meeting summary both in browser and in email.

### Acceptance Criteria
- The link text wraps (probably easier) or is truncated (not too hard)

### Estimated Effort
- 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Iceboxing for now
