### ISSUE TITLE
Update styles/style implementation for new authentication pages

### ISSUE THREAD

**Issue by dan-f** [ParabolInc/action#1848]
## Issue - Enhancement

We should update the styles of the new signin, signup, and password recovery pages to be consistent with the new app styles introduced in #1819.

### Acceptance Criteria (optional)
- Styles are consistent with the new application styling
- Implementation is consistent with new application style primitives

- **Estimated effort:** 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
Thanks @dan-f for creating this issue.

**Comment by ackernaut** [comment]
Closed via #1921
