### ISSUE TITLE
Design: Single Kanban + Team Space

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1852]
## Design

We are exploring UX for new features. We want the information architecture of the app to reflect this UX so that folks can take care of working on their tasks (maker mode) or engaging with their team (manager mode).

#### Single Kanban/Dashboard
- I can see the state of all of my tasks, and all of my teammates’ tasks
- I can apply filters to narrow the list of tasks down easily
- I can search to find tasks or other knowledge across all of the teams to which I belong
- I can expand a task card, leave a comment on it, and easily copy its unique URL
- I can easily see my organizations and the teams that I am on under each organization
- I can easily navigate to my teams
- I can easily navigate to my settings
- I can easily see and respond to notifications (including an archive of my notifications)
- I can add a card anywhere in a list (see: #1875)

##### Meetings
- I can easily start a meeting
- I can easily add to the agenda topic list
##### Teammates
- I can see who is on the team
- I can invite new team members
##### Settings & Integrations
- I can easily access settings
- I can see what integrations are actively being used on the team
##### Handbook
- I can see existing notes that contain team knowledge like processes, policies, role definitions, or unstructured notes
- I can search these notes
- I can create, edit, delete new notes
- I can leave comments on notes
- I can share a unique URL to a note with a teammate
##### Purpose & Roles
- I can see the team’s purpose
- I can see the team’s roles

### Estimated Effort
- 30 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Added #1875 to this list

**Comment by jordanh** [comment]
The way this sucker is written, it may never get prioritized. Suggest in the future it is broken into multiple issues on its own epic.

**Comment by ackernaut** [comment]
If this is done by contract (3-4 weeks) does it have to fall into the sprint process?

**Comment by jordanh** [comment]
Doh! You're completely correct. This is bojan's issue. :)

**Comment by tayamueller** [comment]
*requested by client on 5.21.18

**Comment by jordanh** [comment]
The mother of all issues. Iceboxing for now.
