### ISSUE TITLE
"Start retrospective" CTA overflows off screen

### ISSUE THREAD

**Issue by dan-f** [ParabolInc/action#1856]
## Issue - Bug

When the `retro` flag is enabled, the "Start retrospective" button on the team dashboard overflows the page by forcing it to scroll horizontally.

<img src="http://g.recordit.co/PwD9vuu5az.gif" alt="video of overflow bug" />

### Acceptance Criteria (optional)
- All meeting CTA buttons are visible without the need to horizontally scroll.

- **Estimated effort:** 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Related to #1857

**Comment by ackernaut** [comment]
Yes, this should be fixed by #1857 and then will close this.

**Comment by jordanh** [comment]
Fixed by #1857 (when implemented), closing as duplicate
