### ISSUE TITLE
Handling Errors with GraphQL

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#1867]
For the full discussion, see: https://github.com/ParabolInc/action/pull/1865#issuecomment-371716888

Acceptance criteria:
- [ ] Move all relay onError handlers inside the onCompleted handlers
- [ ] For any onError handler that affects the UI (like popping a toast or printing an error message in a field) refactor that server query/mutation to have the error be part of the schema
- [ ] For subscriptions, only send a GQL_ERROR type if the error occurred before entering graphql (eg there is no query included. i think this is the only one!)
- [ ] Should be merged in tandem with #1865

Effort: 11 points

**Comment by jordanh** [comment]
@mattkrick can we close this now?

**Comment by mattkrick** [comment]
yep!
