### ISSUE TITLE
Design: retrospective free→pro upgrade path

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1878]
## Issue - Enhancement

Let's make some money. Our bet is that adding a team handbook and retrospective meeting type will be enough differentiated value to drive adoption and conversion. Today, we're largely driving conversion through top-down sales. However, we should always have a experience we are testing to drive bottoms-up conversions.

### Some history

When we originally launched Parabol's payment features, Parabol was trial-ware. Teams could try us free for 30 days. They could get another 30 days free if they gave us their credit card number. When the trial expired, their users would lose access to all of their organization's teams until they paid.

*What we learned:* our value prop wasn't thick enough to drive self-adoption, so both free usage _and_ conversions were low.

*What we didn't learn:* trialing for premium features is bad. In fact, trialing for premium features might still be good.

### Goals & Acceptance Criteria (optional)
An designed, lo-fidelity experience where users can:
   - Get to know all of the features of Parabol and get themselves and their teams hooked, meaning:
_(this is how we'll know this design has worked)_
      - See clear:
         - Messages for which features are pro and are subjected to being limited
         - Calls to action for how to convert
      - At least one team is running at least one meeting (action/retro) regularly (at least 1/mo)
      - At the end of the evaluation period, the team converts at least 10% of the time

Validation criteria:
   - The lo-fi design is checked with at least two of our partner/advisors

Once the design is completed, the following are created
   - A list of implementation Issues/stories
   - A list of supporting marketing workflows (for example, emails to send)

#### Trial-ware

In addition to `personal` and `pro`, we create a new tier called `pro-trial` (or, extend the `pro` tier to have an expiration date). When a user creates their first org, their org is in the `pro-trial` tier.

We assume that it takes a quarter (3 months/3x4-week periods) to convert. After 7 weeks, we give them a banner that their trial is about to run out, but they can extend it for 4 more weeks free if they give us their cc now. After a maximal period of 12 weeks, if they do not convert, we offer them the a workflow to demote their account to the `personal` free tier.

We send marketing communications to support conversion.

When the account is in the `personal` tier, we disallow access to things such as Retrospective Meetings and access to the Team Handbook.

#### Limit-ware

All accounts start in the `personal` tier. Some features are limited, just as we limit access to a team's Task archive today.

We begin by adding a limit to the number of Retrospective meetings that can be run. For example, we offer a limit of 3 per org.

We limit the number of Handbook items that can be created. For example, 12 per org.

When one of these limits is exceeded, we decorate the interface with affordances to convert and remove these limits.

We send marketing communications to support conversion.

- **Estimated effort:** 15 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
We held a pretty rich discussion about this on Slack. We came down to the following proposal:

> **let me restate proposal, and let's decide* (edited)
> For personal accounts, on lobby, we show how many free retros are remaining for the org (starting with 3 of 3)
>when there are none remaining, we pop the conversion modal
>*Clarifying qs?*
>
>mattkrick [15:12]
>just for closure, what are your reasons against the expiration date?
>
>jrhusney [15:14]
>I think it adds an additional dimension to the number of corner cases we have to consider
>and
>I think it re-introduces the other problem of "I created an account but I'm not ready to run a meeting on your timeline"
>I think we can introduce a time limit as a conversion tactic if we need to
>(and maybe even A/B test it)
>Any more qs?
>Ok. Let's move onto reactions
>*Reactions?*
>
>terry [15:22]
>sounds good, the whole top-down strategy is similar to what I was thinking—the folks we want to >target right now aren’t worried about saving up retros, they’re worried about getting their teams >unstuck or in the habit of better practices—and we can always iterate on design. I’d rather iterate over back-and-forth assumption sharing.

>mattkrick [15:24]
>i still don't love it. even though the meetings came for free, it's still a finite resource that i'd hesitate >using up
>what's that (redacted) alternative? what's their business model?

>jrhusney [15:28]
>*Amend and clarify*
>I don't love it, but I don't hate it either :slightly_smiling_face:
>(redacted) model is: we tell you transparently on the webpage
>that you get 2 free
>but then we surprise you when you are out and we force a conversion
>it's worked for them, but I can see your point of view @mattkrick
>and I think it is fine to choose a different starting place
>I have no changes to my proposal
>*Objections*?
>Any reason this wouldn't be safe to try?
>Going once...

**Comment by jordanh** [comment]
Design: https://www.figma.com/file/FJ52DGmDUxddTfYlZwzqza7O/Meeting-IA

**Comment by mattkrick** [comment]
done in v2
