### ISSUE TITLE
Design: scrappy Pro messaging

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1879]
## Issue - Enhancement

Currently, we're not doing ourselves many favors when it comes to making our users aware that their are tiers to this product, and they could pay us if they wanted to. Let's be incremental and fix this a little bit:

### Job Stories

When I use the product, I want to know if the product is limited in some way, so that I can be made aware if I could can access to more new and exciting features

When I am a regular user and I've been told that a price increase is coming, I want to know how to lock in a lower price, so I can save money

### Acceptance Criteria (optional)
A lo-fi, feedback, clickable hi-fi, cycle which addresses the following needs:
From a team page:
   - When a team is in the personal tier, they can be made aware, non-obtrusively, of what tier their team is in
   - Click a simple CTA that takes them to their team's billing page
   - Consider upselling in higher-trafficked areas as well without being annoying
From an org's billing page:
   - Click a link, opening a new window, that takes them to the pricing page

- **Estimated effort:** 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
Getting started on this…Sprint No. 6

**Comment by ackernaut** [comment]
Up for review for Sprint No. 6:

[Clickable prototype](https://www.figma.com/proto/DXqOZNFNbfvkBBxvPCKgfiNW/Nudges-to-Upgrade?scaling=scale-down&node-id=1%3A2)

[File with various states](https://www.figma.com/file/DXqOZNFNbfvkBBxvPCKgfiNW/Nudges-to-Upgrade)

**Comment by ackernaut** [comment]
Done in Sprint No. 6 — UX to be implemented in #1980
