### ISSUE TITLE
Design: date assignment on Task cards

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1880]
## Issue - Enhancement

A very common user-requested feature: being able to assign a due date to a card.

Note: this issue is very narrow in scope. It is **not** about:
- how to sort by date
- how to snooze until a date
- how to color a card when the card is before/after a particular date
- how to automatically update dates
- designing a calendar view
- time or time zones, this is a **date** field not a **datetime** field

Rather, it is about:
- adding a control to our Task card that users may use to add an optional due date

Also, this is a pre-req to old issues such as #612 (and many others).

### Acceptance Criteria (optional)
Deliver a lo-fi design, gather feedback, then deliver hi-fi design based on that feedback, to test if users can:
   - See the due date for a card
   - Change the due date for a card

- **Estimated effort:** 15 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Note: we can _absolutely_ opt to use a pre-existing date picker, as long as it is styled appropriately for our product

**Comment by ackernaut** [comment]
I wonder if there is something out there in the wild that allows styling through JS, over CSS/Sass/etc. 🤔

**Comment by jordanh** [comment]
Note: if somebody says they'll pay for this feature, let's elevate its priority. Until then, we'll get to it when we get to it.

**Comment by tayamueller** [comment]
> Hi Taya! We are loving Parabol to help us keep on track with smooth running meetings but we are hoping to see a calendar and the ability to create recurring tasks synced with that calendar. It's the big piece that will get us from loving it >>> to can't live without it. Is there any news on when that might happen?

**Comment by ackernaut** [comment]
Let’s see how #2001 gets prioritized as it is the implementation issue of the latest design concepts.

**Comment by jordanh** [comment]
Resolved in Figma
