### ISSUE TITLE
Upcoming invoice, error on route

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1884]
## Bug

My steps:
1) I created an account on staging
2) I upgraded to Pro using a Stripe testing CC number
3) I saw an invoice for March that I could navigate to
4) I saw an upcoming invoice for April that I could not travel to, but saw an error instead

![screenshot 2018-03-14 13 35 30](https://user-images.githubusercontent.com/307286/37429889-9eada950-279e-11e8-96b5-a2a81f872910.png)

![screenshot 2018-03-14 13 35 41](https://user-images.githubusercontent.com/307286/37429906-aaee6cea-279e-11e8-8eaf-0d23b779c3d1.png)

### Estimated Effort
- 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### Acceptance Criteria (optional)
- Users can see upcoming, estimated invoices

**Comment by mattkrick** [comment]
due to using prod data on staging. we could make it fail a little cleaner, but i'm not too worried about it. for all things billing, we'll just have to create a new account on local/dev/staging and then verify on prod.

**Comment by ackernaut** [comment]
I will test this on production because we think it’s an issue with the staging environment.

**Comment by ackernaut** [comment]
Was able to view the upcoming, estimated invoice on production.
