### ISSUE TITLE
Integrating task card with GH flashes, fails?

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1885]
## Bug

My steps:
- On staging, added GH integration to a team
- Created a card with User B who is not integrated to GH and tapped to add to GH
- The GH styling flashes (optimistically?) but then the card returns to a normal task card type

### Estimated Effort
- 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### Acceptance Criteria (optional)
- GH cards integrate as expected

**Comment by mattkrick** [comment]
fixed on staging! (be sure to merge back to master from prod)

**Comment by ackernaut** [comment]
@mattkrick will definitely merge back to `master`. Should I keep this issue open to track a similar issue? The issue is: any user can create a GH-integrated card, but the owner of the card has to be a GH-integrated user before the card will become integrated.

**Comment by mattkrick** [comment]
yeah, i'll reopen & modify the text

**Comment by jordanh** [comment]
Iceboxing for now. Will reopen, ASAP
