### ISSUE TITLE
GitHub-integrated task card regression

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1891]
## Bug

On production, I’m unable to integrate a task card with GH if the owner of the card is not integrated with GitHub.

### Estimated Effort
- 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### Acceptance Criteria
- Users can create a GH-integrated card regardless of whether the owner is integrated or not

**Comment by jordanh** [comment]
Iceboxing for now. Will reopen.
