### ISSUE TITLE
Coaching page wave decoration missing

### ISSUE THREAD

**Issue by bjanjanin** [ParabolInc/action#1892]
The [Coaching](https://www.parabol.co/coaching) page is missing the wave decoration element (see the [Solutions](https://www.parabol.co/solutions) page as an example. To add it, we need to add

```
<div class="decor hero-decor">
</div>
```
before closing the `.hero` section.

**Comment by jordanh** [comment]
Wrong repo! Closing for now. But that you for reporting!
