### ISSUE TITLE
RemoveFromOrgModal closes before error is shown

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#1903]
Currently, we optimistically close the modal when the button is clicked, if there is an error, it isn't shown.
I think this is good, but we need to propagate the error somewhere, either in a toast or preferably under the button that opened the modal.

Acceptance criteria:
- [ ] when an error occurs in the RemoveFromOrgModal, show the error under the button that opens the modal
- [ ] do an audit for all similar modals, since this affects all modals

Effort: 11 points for all modals

**Comment by jordanh** [comment]
This is still a thing. But, Iceboxing for now.
