### ISSUE TITLE
Add redirect handling for bad routes

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#1904]
Currently, if i try to go to a team dashboard for a team i don't have access to, i get a white screen.
The error handling to prevent white screens works by grabbing partial data, but in this case, that's the only data there is!

Acceptance criteria:
- return a team payload that includes an error (probably the best)
- Add is a `redirect` prop to `RelayTransitionGroup` that can redirect to eg /me on error

Effort: 11 points

**Comment by jordanh** [comment]
[A user ](https://app.hubspot.com/contacts/3888472/contact/32901) just reported this again yesterday:

> when I hit an Action URL for a team that no longer exists I get a very sad looking page. I can click My Dashboard to get all teams to re-appear in my sidebar, but I feel like I should just be re-directed there in a case like this.
