### ISSUE TITLE
Refactor all Root components to use RelayTransitionGroup

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#1905]
We've (finally) got a good, stable, repeatable pattern in using RelayTransitionGroup. It's a clean way to handle loading/error/render state for all queries. We need to get all components using this so when we fix #1904 for the TeamRoot, we fix it for all components.

Acceptance criteria:
- [ ] Upgrade all Root components (~ 25 of them) to use the RelayTransitionGroup

Effort: 11 points

**Comment by jordanh** [comment]
Scrubbed today

**Comment by mattkrick** [comment]
close in favor of #2647
