### ISSUE TITLE
Refactor Action Meeting into new format

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#1906]
To build the retro meetings, we needed a more flexible meeting layout on the front end and back end. we created one that supports different types of meetings. It is simpler, less error prone, more performant, and offers a host of benefits such as:
- being able to execute meeting stages in a non-linear path (something that might be useful for agenda items)
- captures metadata like how long team members spend on each stage #1527
 - allows for custom phases, such as a "metrics" phase
- properly randomizes check-in questions #1822
 - ... and so much more!

It doesn't make sense to maintain both meeting types because a small edit in one means we have to make that same edit in the other. Instead, I propose we move the Action meeting to the new meeting format. This shouldn't be prioritized over the retro meeting, but it should be prioritized over 1-off updates to the action meeting. From here on out, the action meeting format should be in "maintenance mode" and only critical bugs should be fixed in it.

### Acceptance Criteria:
- [ ] Action Meeting stored in NewMeeting table
- [ ] action meeting specifics are removed from the Team table
- [ ] Uses NewMeeting front-end component
- [ ] Updates help menu pattern, see #2341 
- [ ] Action gets its own Meeting Lobby component, see #2342 

### Effort: 13 points

**Comment by jordanh** [comment]
During scrub: we're going to get to this one, I'm sure of it. But, I bet it will be done when we have a trigger for some kind of new feature (custom meeting formats? pinned items? who knows). Iceboxing for now

**Comment by mattkrick** [comment]
bringing out of icebox. not doing this has already cost us about 10 hours of work and quite a bit of goodwill from bugs that affected customers.
We've got 3 options:
- do this next sprint
- agree to not fix bugs pertaining to action meetings
- keep wasting time with hotfixes

**Comment by mattkrick** [comment]
Gonna try and break this into as many bite sized chunks as possible.

First, we'll need to refactor the New Meeting to support multiple meeting types. It kinda does, but when we built the retro, the tools required didn't exist yet (ie React.lazy, hooks)

The goal of this first step it to have each phase load as a module. Then, all we'll need to do is reference different modules

TODO
- verify sidebar transition works
