### ISSUE TITLE
Add "Auto Group" Button

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#1911]
Grouping cards is O(n logn) complexity. That sucks for computers, and for humans, it sucks even more!

I propose we have a button that says "Group these for me". The icon is a magic wand. When i click it once, the cards that are _very_ similar are grouped together & given an appropriate title. If i click it again, the threshold for similarity is decreased. Maybe allow 2 or 3 clicks max.

Acceptance criteria:
- [ ] Add a floating action button called "Auto Group" to grouping phase UI
- [ ] Group cards together based on decreasing thresholds, e.g. [0.75, 0.5, 0.3]
- [ ] After 3 clicks, the button goes disabled

Effort: 12 points

**Comment by jordanh** [comment]
This is a _really_ fun idea. Perhaps we should make the first step collecting a bunch of reflection cards in our database and developing and testing some grouping models?

**Comment by mattkrick** [comment]
@jordanh can you export the cards from our previous retros?

**Comment by mattkrick** [comment]
Thought about this a little more, there are 2 components:
- Weighting
- optimizing

To determine weight, we need to figure out if 2 cards are better together than separate. We can measure that as distance (euclidean, manhattan, cosine, etc). As a naive approach, we can use the cosine similarity, since that's the de-facto standard for this type of stuff. that will yield a number from 0 to 1. if it's better to not group than group, we need the single card score to be higher than the group score, so we can start that at 0.5 as a threshold and work our way up.

Next, we need to optimize. 
- We could brute force it (np-complete, but who cares, it's a small solution space).
- We could use an agglomerated blossom algorithm (i dunno if that's actually a thing, basically just loop over a blossom algo until it converges). Blossom is O(n^3).
- We could use hierarchical clustering. This is kinda like a k-means cluster, except instead of O(n) it runs in O(n^3). But, if we did a k-means we'd have to run it k times, so that's lame. The hierarchy also let's us compute once and determine threshold later. Finally, since it's a hierarchy, we could use that as the sort order (better fit = closer to the top of the stack).

I think I'm gonna go with the hierarchical clustering. The one caveat is I'm gonna swap out the euclidean distance for a cosine distance function, which should make close things REALLY close and far things REALLY far.
