### ISSUE TITLE
Broken staging build v1.2.0-0

### ISSUE THREAD

**Issue by dan-f** [ParabolInc/action#1918]
## Issue - Bug

During the staging build, webpack failed to compile the client app.

https://circleci.com/gh/ParabolInc/action/4861#queue-placeholder/containers/0

### Acceptance Criteria (optional)
- The build passes again

**Comment by dan-f** [comment]
Take a look at the "Possible deployment build" stage:

```
ERROR in 1_b50c21362ed8553705bf.js from UglifyJs
Unexpected token: punc ([) [./server/graphql/types/MeetingTypeEnum.js:8,0][1_b50c21362ed8553705bf.js:60571,4]
```

The problem appears to be that server code is ending up in the client dependency graph, and the client babel config is not properly set up for it.

**Comment by mattkrick** [comment]
looks like this is fixed! closing
