### ISSUE TITLE
Archive Overlap bug

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#1927]
I noticed the archive no longer properly handlers overlaps. probably related to #1900

![archivebugoverlap](https://user-images.githubusercontent.com/5514175/37807208-73c3c24c-2e01-11e8-942e-ce25b4385d90.png)

AC
- [ ] make the overlap problem go away

Effort: 11 points

**Comment by ackernaut** [comment]
Investigating…

**Comment by ackernaut** [comment]
The strange thing here is that sometimes the view will render the cards correctly and other times it won’t. Makes me think there is some race condition for when the card components load their content versus when the view thinks it has the dimensions it needs to render the view. I think #1900 is not related but I could be wrong. I left a comment on that issue as well.
