### ISSUE TITLE
Simple data export

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1930]
## Issue - Enhancement

We've been catching signal that while folks are excited to use our new retro feature, they don't want the tasks to be siloed within Parabol because they already work within other tools.

First, we have a choice of format. The obvious formats (+ commentary):
   - CSV (universal, simplistic but limited importable by Asana, Excel, Sheets, and Trello)
   - TSV (same, same, same)
   - JSON (good for programmers, no universal task schema obvi)
   - XML (obsolete)
   - Plaintext (not machine parsable)
   - xls (only useful for Excel users)

I suggest we start with CSV. And, I suggest we do this with minimal design for starters.

### Format
Let's riff off of the [Asana CSV importer syntax](https://blog.asana.com/2018/01/import-csv-asana-projects/):

| Name  | Value | Comment |
| ------------- | ------------- | ------------- |
| `Task`  | Task contents, as plaintext  | |
| `Assignee`  | Task owner  | |
| `Due Date`  | (null for now)  | |
| `Status`  | Future, Stuck, Active, Done  | Folks can search and replace to map these to Asana names |

### Acceptance Criteria (optional)
Users can:
   - Access a url, /team/:teamId/tasks/csv, and receive a `text/csv`file
     - The file will be named as `YYYYMMDD-HHMMSS Org – Team Name – Tasks.csv`
     - Tasks are ordered by date created, ascending
     - The archive is omitted (we could add this as a future argument to the export)

- **Estimated effort:** 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
I don't want to dictate too much of a solution here, so I marked this as a discussion for shaping

**Comment by tayamueller** [comment]
validated 06.25.18 by a $15k coaching user: "I'd like to use Parabol to work together on the Regional Committee too [...] I really like it, it gives me more control over all the work! [back & forth RE Free/Pro] ohhh, ok! Is there a way to export Done tasks? That would be awesome and worth $5. [back & forth RE Org/Team structure] Ok, that's a good idea. I want to have several teams!"

**Comment by jordanh** [comment]
We have CSV export! Closing.

**Comment by drewhousman1010** [comment]
A [user ](https://app.hubspot.com/contacts/3888472/contact/20404851) 🔒 says:

> If we could export to JSON that would be great. It would be easier to do whatever we want with the data.
