### ISSUE TITLE
Creating a world-class theme estimator

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#1931]
Today, we have in place a super naive model that will extract entities from text, pluck out the most salient of the bunch, and use those for a title.

In the future, once we have enough data, we will be able to train an nlp deep net to do this better. When people have retros and group reflections into themes, we'll set the reflections as an independent variable & the title that they give it as the dependent. Doing so will provide a much nicer title than just a string of nouns.

That's the big picture, but we likely won't get there anytime soon.

**Comment by jordanh** [comment]
Let's give this time and collect lots o' data. Iceboxing for now.
