### ISSUE TITLE
Meeting scratchpad

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1941]
## Enhancement

From a user after looking at a clickable meeting prototype:

>I really want to be able to take notes and jot down anything important that comes up.

### Acceptance Criteria
- Draw up some low effort, pen-and-ink solutions:
  - A) The ability to create team knowledge during the agenda (“jot down anything important”), not just create new tasks. These could be notes that go into the team knowledge “handbook” area.
  - B) The ability to have a single, multiplayer scratchpad accessible during any meeting. At the end of the meeting the final version of the scratchpad content is captured in the meeting summary where it can be reviewed.
- Get feedback from folks on the sketched concepts. One question (of many) is: would folks write things here that would be better off as tasks with an owner (meaning some things got written down, but there were no clear next-steps and no clear accountability.)

#notes #future #handbook #team #meeting

This is similar to #1059 

### Estimated Effort
- 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
I really like this idea and am actually exploring it in a new IA/layout for my dashboard versus the team space. Iceboxing for now, and will create a new issue and reference this one when it is time.

**Comment by ackernaut** [comment]
I think the scratchpad could travel along with you whenever the UX makes sense (dashboard, meeting notes, etc.)

**Comment by tayamueller** [comment]
updates:

use need #1 - "I wish we had some place to write group notes that aren't rasks."

use need #2 - "I wish we had a group whiteboard"

use need #3 - "I wish we could note recurring Agenda items"

**Comment by ackernaut** [comment]
Revisited during S.P.A. 11

**Comment by jordanh** [comment]
Super-ceded by #2808
