### ISSUE TITLE
Upload square parabol logo to repo

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#1951]
some things, like oauth, want a square logo & it'll clip the sides of ours.

acceptance critieria
- [ ] square 8x png uploaded to static/images/brand
- [ ] square svg uploaded to static/images/brand

effort: 10.5 pts

**Comment by ackernaut** [comment]
For sure, we cannot rely on a version of the logo that is trimmed to the shape of the logo. It looks like it would fit perfectly into a square or circle but it does not. So I produce versions that are on a square canvas that give a proper amount of whitespace around the logo, the background can be transparent or solid, depending on the use case. Thanks for capturing, I’ll take a look!

**Comment by mattkrick** [comment]
@ackernaut taya alerted me to the stuff in the marketing folder, which works for everything but slack, which needs a square logo that's a minimum of 512x512 and maximum of 2000x2000.
(we could also stand to refresh the screenshots for the slack app, too, but we can punt on that for now)

**Comment by ackernaut** [comment]
@mattkrick is this still an issue? I see you added some cropped avatars.

**Comment by mattkrick** [comment]
yeah, the logo we submitted to slack is just a blown up version of a smaller image so it doesn't look amazing at full res, but i think this is good enough for now.
