### ISSUE TITLE
Slack integration bugs

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#1964]
I noticed a couple bugs with the slack integration.
We should upgrade slack subscriptions to the new subscription format, there's probably a bunch of bugs in there.

Acceptance Criteria:
- Can click remove slack instance & it goes away
- Can re-add slack instance & re-add the same channel & only 1 channel appears in the channel list

Effort: 11 points

**Comment by mattkrick** [comment]
the first half is fixed by #2517 but we still aren't checking for duplicate channels. will revisit when we revisit the slack integration (move to per-provider model instead of per-team)

**Comment by jordanh** [comment]
Scrubbed. Closing in favor of #2839.
