### ISSUE TITLE
Add "invitation not sent" warning to pending approvals

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#1967]
When an invitee is pending approval, it's not obvious that the invitation didn't go out. If it confuses me, and i wrote the thing, it probably confuses everyone.

Acceptance criteria:
- [x] a design is created & mocked up. maybe a warm warning exists for pending approvals. Maybe the whole row is highlighted or something? (see #2108)
- [x] an implementation issue is created (see [Figma concept](https://www.figma.com/file/DXqOZNFNbfvkBBxvPCKgfiNW?utm_campaign=team&utm_source=slack&utm_medium=message&utm_content=file_comment#1031470))

effort: 11 points

**Comment by jordanh** [comment]
Consider adding a CTA to person requesting an invitation to become the billing leader to avoid having to make this approval in the future

**Comment by ackernaut** [comment]
moving to review on sprint board (sprint no. 9)

**Comment by ackernaut** [comment]
Designed and done in Sprint No. 8
