### ISSUE TITLE
Improve editing socket messaging

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#197]
Instead of calling `present` each time, editing should call `edit` with only the socketId and the field that is being edited. Also, the middleware can block this from getting back to the sender.

**Comment by jordanh** [comment]
Are you envisioning that this would becoming it's own decorator, graphql model, and subscription? Makes a ton of sense...

**Comment by mattkrick** [comment]
Not entirely, I see Presence as an entity, and the userId, editing, and targetId are just fields.

**Comment by jordanh** [comment]
Looked into this a bit just now, looks like SC doesn't support not sending back to the publisher when you emit a message in a channel: https://github.com/SocketCluster/socketcluster/issues/54

That's a pity as socket.io has interface options for that...

**Comment by jordanh** [comment]
Ah wait, I read that incorrectly.

**Comment by mattkrick** [comment]
socket.io has `broadcast` socket-cluster has publish out middleware. essentially does the same thing, but socket-cluster's method is a bit more scalable because making a worker keep track of its clients gets ugly, then propagating that up the broker gets even uglier. Dontcha miss the days when a single CPU on a single machine could serve all your clients?

**Comment by jordanh** [comment]
I see now it's all handled by the `MIDDLEWARE_PUBLISH_OUT` middleware. I'm trying to find the docs for the req object for that middleware...

**Comment by mattkrick** [comment]
http://socketcluster.io/#!/docs/middleware-and-authorization

**Comment by mattkrick** [comment]
A more pertinant example: https://github.com/ParabolInc/action/blob/master/src/server/socketHandlers/mwPresencePublishOut.js

**Comment by jordanh** [comment]
Right, right. I've got that. Thank you :)

I'm looking for the fields on the `req` object. Is socket just a socket.io socket? Where is sender socket id (I assume it's `req.socket.id`)? Where is destination id?

**Comment by mattkrick** [comment]
destination is req.socket.id. If you wanna know who sent it, that person has to include their name in the payload.

**Comment by jordanh** [comment]
Ah, what a drag. Ok.

**Comment by mattkrick** [comment]
for example, when I call `PRESENT` i give my socketId & userId.

**Comment by mattkrick** [comment]
If you wanna do something based on the originator, you might consider PUBLISH_IN.

**Comment by jordanh** [comment]
I added a little something here to block sending back to sender: https://github.com/ParabolInc/action/commit/49a05b8fcbf3f8ec8081947b635b072e85eca3a1

**Comment by jordanh** [comment]
Added `edit` here: https://github.com/ParabolInc/action/pull/199/commits/9fc8253d0ba549f520d85cc42dc76f2fa9766c38
