### ISSUE TITLE
Error when signing in

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1971]
## Issue - Bug

I use different profiles in Chrome (personal, work). I typically use manual email/password, not Google’s option. I can sign in while using 1 Chrome profile but not the other (essentially separate windows/sessions). Not sure why. The URL is the only clue. Also, happens consistently when running the app locally.

```
https://action.parabol.co/signin#error=server_error&error_description=Unable%20to%20configure%20verification%20page.&state=
```

#### Estimated Effort
- 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### Acceptance Criteria
- Users can sign in without a hitch

**Comment by ackernaut** [comment]
I tried on Safari and Firefox (which I do not use regularly to sign in to Action) and am getting the same issue there as well. Also, my buddy had the same trouble signing in for one of our personal teams.

**Comment by ackernaut** [comment]
Ok, tried on my Android Chrome browser…getting the same issue. I wonder if it is related to auth0 configuration or my account.

**Comment by jordanh** [comment]
Clarifying questions:

This is happening for you on production too?
Can you write out the steps, including the usernames and auth0 ids?

**Comment by jordanh** [comment]
As of right now, I can't reproduce this. Here's what I am doing:

1. In an incognito browser tab:
   1. I sign up a new user (jordan+20180405@parabol.co)
   2. I login and use the app as normal
1. In a non-incognito browser tab:
   1. I login using Google and use the app as normal

In these two separate browsers, everything seems to work hunky-dory.

Are you using two separate browsers or just two tabs of the _same_ browser?

**Comment by ackernaut** [comment]
@jordanh 

1) I sign out and hit `action.parabol.co` and I am routed to `/signin`.
2) I enter my email and password
3) I get the URL above `…#error…` with the loading ducks

I saw it using my production user on my personal Chrome profile, but I can log in with the same user on my work Chrome profile (so essentially 2 completely different browser sessions).

My friend is on my org, so maybe that has something to do with it. He uses manual email/password as well.

**Comment by ackernaut** [comment]
auth0 user ids in Slack support channel for Parabol folks

**Comment by ackernaut** [comment]
It seems this is happening when the browser is set to block third-party cookies. Changing to non-critical. Not sure if this is considered a bug.

**Comment by jordanh** [comment]
Root cause (users who've disabled third-party cookies), see: https://auth0.com/docs/cross-origin-authentication

Possible fixes:
   1. Create a [Create a Cross-Origin Verification Page](https://auth0.com/docs/cross-origin-authentication#create-a-cross-origin-verification-page)
   2. Enable [Custom Domains](https://auth0.com/docs/custom-domains)

**Comment by jordanh** [comment]
Looking at the docs, #2 is definitely the way to go

**Comment by jordanh** [comment]
Ok! We're now using custom domains. @ackernaut, can you please verify this is fixed and closed if it is working now?

**Comment by ackernaut** [comment]
Fixed! Thanks @jordanh !!
