### ISSUE TITLE
Retro Style Touchups

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#1975]
Hey @ackernaut here's a list of style things that i wasn't sure about:

- [x] Voting phase sidebar headers & content. The headers look like the column headers, should be pull that out into its own component?
- [x] Group card count. The figma grouping phase has the count pushed to the right, the voting phase has it centered. I think it should be in the same place no matter the phase.
- [x] Voting checkmark. Depending on how we handle the count, we should have the checkmark stay in place so you can double click to give 2 votes (right now, the extra checks will bump it to the side)
- [x] Group Title. The Figma version was bold, the storybook version was light, I'm not sure what to go for, I like the bold though!
- [x] handle validation rules. currently, i just remove the gray checkmark if the viewer has no more votes or has voted for that group the maximum amount of times. please approve.

Additions:
- [x] Summary: Reflection cards are too wide
- [ ] Discuss phase: space out the goto next & end meeting buttons, but the end meeting button stays put if the goto next button goes away

Acceptance Critieria
- The issues above are considered & any changes that @ackernaut sees fit are made

Effort: 11 points

**Comment by ackernaut** [comment]
1) I’ll have to take a closer look, but if I’m understanding correctly it probably could merit its own component.
2) Group card count should hang just to the right of the label text. The label and count are centered as a group. I probably will hang the count by positioning, too, allowing the label text to be truly centered.
3) I think the right-oriented voting makes sense for quick, multiple votes.
4) The group title should be `600` for “SemiBold” variant.
5) Yep, that sounds great! They shouldn’t see controls to add votes unless they remove their last vote (no. 5 of 5).

@mattkrick do you want me to touch any of this in the codebase?

**Comment by mattkrick** [comment]
@ackernaut i think it's safe to play around on 1750-end-meeting. an alternative would be to merge that into master & then you can make a branch on top of it.

**Comment by ackernaut** [comment]
@mattkrick did you need `1750-end-meeting` merged into master in order to work on #1960 PR? I’m happy to jump in wherever I can to make another pass at Retro UI.

**Comment by mattkrick** [comment]
nah, that PR is functional on its own, just ugly.

**Comment by ackernaut** [comment]
Starting this for Sprint No. 7

**Comment by ackernaut** [comment]
Will address control bar button styles in a future update. Done in Sprint No. 7
