### ISSUE TITLE
Simple reflection and reflection grouping overflow designed

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1976]
## Issue - Enhancement

Before we go to general release, we'll need to design for what happens when our reflection and grouping columns get too long, like:

![image](https://user-images.githubusercontent.com/103000/38470236-b4c56a46-3b14-11e8-9cc3-82b35d187b2f.png)

### Acceptance Criteria (optional)
If effort <= 11, design only where users can:
  - Cheap implementation to make current retro usable when columns get long
If effort > 11, design only where users can:
   - Continue to add reflections and group when the list overflows their viewport
   - Move the viewport to see all reflections and reflection groups
 

- **Estimated effort:** 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
The simple way to overflow the phase content view (reflect, group, vote) when the columns are tall was added in Sprint No. 7. We can open a new issue if we design smarter columns that support drag-n-drop and keep controls visible at all times, etc.
