### ISSUE TITLE
Accepting team invites from email when signed out

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1984]
## Bug

Here’s what I go so far:

- Invite User A with User B.
- 😢 User A taps to accept from the email when signed out of Action and gets a developer-speak message about an endpoint. Say wha?
- 😄 User A can still accept from email when signed in.
- 😄 User A can still accept from the notification.

**Exhibit A**
![screenshot 2018-04-10 16 14 57](https://user-images.githubusercontent.com/307286/38584373-b91e4fcc-3cdb-11e8-8012-c6323f35c0ab.png)

**Verdict**: I think folks are blocked by the deprecated auth0 lock when joining teams via email CTA and are not users or are not signed in.

### Acceptance Criteria (optional)
- Users can join from email and are able to either sign up or sign in.

### Estimated Effort
- 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
I wonder if this was a pre-existing bug?

**Comment by ackernaut** [comment]
I remember testing invites often where I would go ahead and sign up (not a user yet). I would see the lock. Not sure how often I tested this flow on production though.

**Comment by jordanh** [comment]
This has been fixed by #1799
