### ISSUE TITLE
come up with a meeting side effect mutaiton pattern

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#1988]
right now, navigating the meeting can trigger different side effects based on where the meeting has been navigated from/to.

those side effects have a wide arrange of payloads ranging from nothing to just about the entire meeting.

we need a clean way to send those messages to the client.

options:
- trigger 2 mutations from the client
- piggyback the side effect on a similar mutation payload (current)
- create a new payload to address the side effect and have the client sub to that. (still not great because it's not progressive. it fully relies on subscriptions to be functional)
- inject the result into the navigate payload & just null it out if it's not necessary (this may be the best?)
- ???

the problem with injecting into the mutation payload is that it's not deferred.

**Comment by jordanh** [comment]
Ah. Glad I deferred thinking about this until I had some headspace on the plane. I think #4 here seems to be best, because the side-effect seems to be closest to the action causing it (navigation). That's what you chose, ya?

**Comment by mattkrick** [comment]
yep, that's the one i chose!
