### ISSUE TITLE
draftjs formatting regression bug

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#1993]
## Issue - Bug

Jordan & I just ran a meeting and experienced 2 possibly related issues:

1)  card formatting is disabled
2) realtime synch is off:

Jordan's live meeting view:
![jordan meeting view](https://user-images.githubusercontent.com/14892189/38687653-2a6bc500-3e45-11e8-99ee-fd943aaf4832.png)

Taya live meeting view:
![taya meeting view](https://user-images.githubusercontent.com/14892189/38687659-2cd9e588-3e45-11e8-9c4b-47627284ad38.jpeg)

Taya Summary online view:
![taya summary online view](https://user-images.githubusercontent.com/14892189/38687835-9af1d986-3e45-11e8-96de-e8cac369d103.jpeg)

Taya Summary email view:
![taya summary email view](https://user-images.githubusercontent.com/14892189/38687708-4ae34ad8-3e45-11e8-947b-087a8801cf66.jpeg)

Taya post-meeting Dashboard view:
![taya post-meeting dashboard view](https://user-images.githubusercontent.com/14892189/38687713-4dfa6ae4-3e45-11e8-96f7-c68798c7d610.jpeg)

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### Acceptance Criteria (optional)
Users can:
   - format cards
   - see the same text as their teammates in realtime

**Comment by mattkrick** [comment]
fixed in in #1994
