### ISSUE TITLE
fix team votes remaining logic

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#1995]
AC
- [x]  hitting the right arrow during checkin marks the user as present if the current value is null
- [x] voting is disabled if the user is not present on the server
- [x] voting is disabled if the user is not present on the client
- [ ] a tooltip pops up on the checkmark if you cannot vote because you are not present
- [x] when marked present/absent, the votesRemaining updates in real time

effort: 11 points

**Comment by ackernaut** [comment]
Agreed, right arrow or enter can be counted as present. A safe default assumption, although it will be inaccurate at times. I imagine the majority of users will either be unaware of the keyboard bindings or not use them and explicitly tap Here or Not Here. And some may tap Here unintentionally on top of that. Gonna cross-ref this comment and issue with #1947 which is over-scoped and I wrote it!

**Comment by mattkrick** [comment]
closed by #1986
