### ISSUE TITLE
Left justify the checkin card buttons?

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#200]
## Issue - Enhancement

It looks a little funny to me that these buttons aren't horizontally aligned. What do you think?

![image](https://cloud.githubusercontent.com/assets/103000/17786732/315d6bfa-6554-11e6-99dd-a3544f7a4fd5.png)

- **Estimated effort:** 1 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
Yes, I agree! Thanks for capturing.
