### ISSUE TITLE
Implement Date Assignment on Task Cards

### ISSUE THREAD

**Issue by bjanjanin** [ParabolInc/action#2001]
## Issue - Enhancement

This issue is for the implementation of #1880, designed in [Figma](https://www.figma.com/file/ZaF5UkRwPdZtNAeKHlffq4zj/Single-Kanban-and-Retros-UI?node-id=221%3A1427).

### Acceptance Criteria

The user can:
- Hover over the card to reveal the date icon.
- Click on the date icon to open the datepicker. 
- Select a due date for the card.
- After selecting a due date, open the picker again to change the date.
- Remove the due date.

The date tag has [three different colors](https://www.figma.com/file/ZaF5UkRwPdZtNAeKHlffq4zj/Single-Kanban-and-Retros-UI?node-id=206%3A0), depending on the due date.

### Estimated Effort
- 13 points

**Comment by ackernaut** [comment]
@bjanjanin this looks great “this user can” is basically under the heading “### Acceptance Criteria” and then you can have a heading “### Estimated Effort” where you guess an effort or pull on a developer to give their estimate (with a link to [CONTRIBUTING](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md
) optional).

**Comment by bjanjanin** [comment]
@ackernaut Thanks! Can you please check if I have the permissions to pick milestones and apply labels (I see no cog icons that are usually there)?

**Comment by ackernaut** [comment]
Ah, good to know @bjanjanin look for an invite and let me know if you can see what you need.

**Comment by bjanjanin** [comment]
@ackernaut Thanks! Still can't apply labels, assign, etc, though.

**Comment by ackernaut** [comment]
@bjanjanin doh! how about now? sorry for the back-and-forth

**Comment by tayamueller** [comment]
> Hi Taya! We are loving Parabol to help us keep on track with smooth running meetings but we are hoping to see a calendar and the ability to create recurring tasks synced with that calendar. It's the big piece that will get us from loving it >>> to can't live without it. Is there any news on when that might happen?

**Comment by ackernaut** [comment]
Shipped in Sprint No. 8 🔥
