### ISSUE TITLE
Handle App Upgrade without requiring a refresh

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2006]
I could swear this issue already exists, but i can't find it.
Anyways, the new login pages borked this, which means this is no longer an enhancement, but it's a bug. We should do this the right way instead of re-implementing the old way.

Acceptance criteria:
- [ ] When the server updates the app, I get a toast saying the app has been updated. I can continue to use the app without having to log out. (This will use an old version of the app, so I may need to refresh to see the latest stuff)

Effort: 10.5

**Comment by jordanh** [comment]
Crazy! I swore we had an issue for this too. Went to look for it. Couldn't find it either.
