### ISSUE TITLE
Retro: cannot navigate from theme->reflect->theme and group again

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2007]
## Issue - Bug

As the facilitator, try:

1. Star a retro
2. Add reflections
3. Proceed to theme
4. Navigate back to reflections
5. Navigate forward again to theme
6. Try to create a group

Observe server message:

```
{"message":"The Theme phase is already complete!","category":"Already completed phase","data":{}}
```

- **OS:** macOS
- **Browser:** Chrome
- **Estimated effort:** 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### Acceptance Criteria (optional)
A facilitator can:
   - When the facilitator hasn't completed the Theme phase, they can navigate the meeting back to Reflect and back to Theme again and still be able to create new groups

**Comment by jordanh** [comment]
The user also cannot proceed beyond Theme, which is a bummer

**Comment by jordanh** [comment]
`icanthackit` also does not work in this state

**Comment by mattkrick** [comment]
fixed in sprint 8
