### ISSUE TITLE
Include task owner name in search filter

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2012]
Typing the name of the user on the card should filter cards for that user. #discussion

### Acceptance Criteria
- The preferred name is included as a search filter parameter
- Users can type “Terry” in the top-bar search filter and see task cards assigned to “Terry”

### Estimated Effort
- 11 points

**Comment by jordanh** [comment]
Let's kick this down the road a bit. For cards assigned to person X, we have a filter control today. In the future, I imagine we'll support this with GitHub style search facets ("assigned: terry") and more or less we'll get this for free when we add real search to the product.

**Comment by ackernaut** [comment]
Sending to icebox via policy
