### ISSUE TITLE
share email, pass between signin/signup

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2017]
One of my pet peeves is typing in my email & pass, hitting sign in & then realizing i need to be on the sign up page, so i click the sign up page & then i have to start from scratch.

We should carry over your email & password to the sign up page.

Honestly, they should be 2 routes that use the same component.

acceptance criteria:
- [ ] go to signin page, type in email/pass, click sign up, the email/pass fields are still there
- [ ] clicking the sign up link carries over the redirectTo search param
- [ ] remove redux-form from all login forms

effort: 10.5

**Comment by jordanh** [comment]
Thank you for documenting this. It's bugged me too

**Comment by jordanh** [comment]
Added to Sprint 23
