### ISSUE TITLE
Retro fixes

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2022]
## design fixes
- [x] Add a reflection button should have userSelect: none
- [x] the scrollbar on the right is always present (probably a linux-only thing)
- [x] yank number of cards per group
- [x] maybe remove column headers on vote stage, maybe move to a LTR grid
- [x] agenda item overflow
- [x] too many scroll bars in discuss phase
- [x] put add a reflection at the top instead of the bottom
- [x] make everyone else's reflections slightly darker during the reflect phase
- [x] consider yanking flag and showing users with no tasks in retro summary (because of attendance)
- [x] clicking end meeting is too easy

## dev bugs
- [ ] cannot ungroup unless dragging to the bottom
- [ ] no emojis
- [x] my votes remaining is very broken
- [ ] too much bottom margin on groups
- [x] let me skip around the topics
- [x] bad slack notification url for start & end
- [x] if a don't make forwards progress, the current theme should not get marked as complete
- [x] after kill, the vote stays red (nuke localStage, localPhase) & the question mark stays high for the facilitator (nuke facilitatorUserId?)
- [x] killing a meeting works all the time

**Comment by mattkrick** [comment]
the remaining 3 dev bugs are big enough to turn into their own issue/PR. @ackernaut feel free to close if this issue no longer serves you.

**Comment by ackernaut** [comment]
@mattkrick that makes sense, I’ll close this issue once I process my list.

**Comment by ackernaut** [comment]
Closing this as the list is addressed in PRs or separate issues
