### ISSUE TITLE
How does retro summary look in mobile browser

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2023]
​

**Comment by mattkrick** [comment]
- header/footer background looks a little weird
- upvoted topics extends height
- crafted with care is off center
- footer is just a bar of color
![screenshot_20180418-103624](https://user-images.githubusercontent.com/5514175/38963098-241a5b3c-4325-11e8-808d-f49b7039dcbc.png)
![screenshot_20180418-103615](https://user-images.githubusercontent.com/5514175/38963099-242faac8-4325-11e8-9b15-68b2b2508fde.png)

**Comment by ackernaut** [comment]
Related to #1957

**Comment by jordanh** [comment]
@ackernaut please add acceptance criteria and estimated effort here

**Comment by ackernaut** [comment]
Closing in favor of #1957 which already has AC and EE
