### ISSUE TITLE
Allow cards to ungroup by dragging off of group

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2026]
I don't want to have to drag a card to the bottom of the column, i want to drag it anywhere that doesn't touch a group.

i don't know if this is possible with react-beautiful-dnd. i tried it before, it wasn't working, but i'll try it again. I'd really, really like to avoid dropping back to the html5 native dnd because it feels harsh. No animations, no keyboard support, etc. 

Acceptance criteria:
- [x] can drop a card on a card/group and it groups.
- [x] can drop a card anywhere else & it ungroups.
- [x] groups have the same bottom margin as single cards
effort: 11 points

**Comment by mattkrick** [comment]
this isn't (easily) possible with react-beautiful-dnd for a couple reasons
- first, there's no easy way to turn off the move-out-of-the-way animation. this is absolutely amazing for reordering cards, but not great for dropping 1 card on top of another. i could monkey patch this though.
- next, and most importantly, is that a Droppable holds an array of Draggables, and if you nest droppables, the draggable only listens to the immediate parent. this is a big challenge because that means it's really difficult to figure out what card you are dragging over. if i don't know what draggable i'm on top of, i can't drop it there to group.

so, i think we have to move back to react-dnd. this is gonna make things a little uglier, and a little clunkier for showing drag state to other clients, but it'll improve the experience by letting you drop wherever.

**Comment by jordanh** [comment]
Let's defer doing this a bit / explore alternatives to moving back to react-dnd.

For example, could we make a div visible at the end if each group that's a gray box labeled "UNGROUP" or some such thing?

**Comment by mattkrick** [comment]
Ah just seeing this now, The move back wasn't too painful, I think it was the right move because now cards stay put when you wanna drop something on top of them, that was a huge annoyance for me (try to drop card A on card B, card B moves away).
