### ISSUE TITLE
Dashboards do not render correctly on Safari

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#203]
## Issue - Bug

While we were doing some testing this morning, one of our testers chose to use Safari. It looks like something doesn't render quite correctly with our dashboard views:

![screen shot 2016-08-19 at 8 24 47 am](https://cloud.githubusercontent.com/assets/103000/17810849/84c109ac-65ed-11e6-987a-853b87a55885.png)

We didn't check if it works functionally or not...

- **OS:** OSX
- **Browser:** Safari 9.1.2
- **Estimated effort:** 3 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
(Let's prioritize this post-alpha)

**Comment by ackernaut** [comment]
Good catch—it is true, I haven’t tested outside of Chrome lately. Will get to this as soon as it makes sense. 👍

**Comment by ackernaut** [comment]
I don’t think this is an issue any longer…but I have Safari 9.1.3, not 9.1.2 (I doubt that patch makes a difference.)

**Comment by jordanh** [comment]
Looks fixed!
