### ISSUE TITLE
Interim Free Retro Lobby Designed

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2030]
## Issue - Enhancement

Until we've designed out a more complete free->pro upgrade experience (captured in #1878); we must do something scrappy before we can push Retros into general availability: a paywall.

@mattkrick implemented a placeholder you can access if 1) your user has the retro feature flag and 2) navigate to the retro lobby from a personal-tier team:

![image](https://user-images.githubusercontent.com/103000/39011660-f25a6e6e-43c6-11e8-858a-a4778c5b05ce.png)

Ideally, when a user clicks the "GET ACCESS NOW" button, they'll be prompted for the stripe credit card form with a link to payment info.

### Acceptance Criteria (optional)
A design where can:
- [x] See an aesthetically pleasing lobby that describes that retros are a premium feature
- [x] A user can see how much the upgrade would cost
- [x] Benefit to upgrading here
- [x] Click the CTA, upgrade
- [x] Create issue(s) that can be prioritized and implemented (see #2103)

- **Estimated effort:** 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Be great to implement this modal so that we could reuse this modal elsewhere to convert uses.

**Comment by ackernaut** [comment]
Getting this started today in Sprint No. 8

**Comment by ackernaut** [comment]
Moving this to the review column, can address feedback as iteration on [this Figma doc](https://www.figma.com/file/FJ52DGmDUxddTfYlZwzqza7O/Meeting-IA) @jordanh let me know if this satisfies the AC and I’ll write up implementation issues.

**Comment by ackernaut** [comment]
Moving to done for Sprint No. 8 (is being built), we can capture new issues for iterations
