### ISSUE TITLE
Retro summary quick stats, fix for accuracy

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2036]
I noticed that the QS for a test retro with partner had 0 Upvoted Topics when indeed there were 10 upvoted topics.
#### EE — 10.5 puntos

**Comment by mattkrick** [comment]
can't reproduce on branch `fix-vote-checkin`, can you verify that this is still an issue? if so, can you provide steps to repro?

**Comment by ackernaut** [comment]
Just ran a test on production. The browser view had the correct number of votes per group, but the email view only has 1 per group. This may be similar to the team name fix that you pushed a while back? It was showing in browser, but not in the email?
