### ISSUE TITLE
Reflect phase UX updates implemented

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2039]
## Enhancement

We want to improve the UX when adding and editing reflection cards. We want to reduce layout change for multiplayer, improve the ability to quickly write many cards, and handle submitting cards versus breaking lines.

### Acceptance Criteria
The behaviors as seen by [this prototype](https://www.figma.com/proto/TLD1OTiMLONajdyYOaErrG/Retro-v1.1.0?node-id=1568%3A9769&scaling=scale-down) are implemented:
- Controls are at the top to add to the column beneath. This is already true as per the latest version.
- [ ] Tapping a control replaces the control with an inline card that is active. If not empty, submitting or blurring the card adds the card to the top of the column. If empty, the control re-appears.
- [ ] As the card is added to the top of the column, the user is presented with another inline card that is auto-focused so that they can quickly add an additional card.
- [ ] Committing the card content uses whatever is current (tab, blur, etc.). This issue does not address changing how we might change that (enter submits vs. enter adds a new line, etc.)
- Cards in the column can be edited by the author. When a card is being edited it shows “Somebody is typing…” This is already true as this is not a change in behavior.
- We've tested this as a group when the PR is issued to make sure that the new behaviors are incrementally better

### Estimated Effort
- 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Attempted to prioritize. I see this still needs AC @ackernaut.

**Comment by jordanh** [comment]
@ackernaut thank you.

Please add a comment on how you'd resolve 3 / 5 in the design, then I think we're in a position to declare this "safe to try"

**Comment by ackernaut** [comment]
I left [a comment in Figma](https://www.figma.com/file/TLD1OTiMLONajdyYOaErrG?utm_campaign=team&utm_source=slack&utm_medium=message&utm_content=file_comment#1139738). Basically I say we give multiplayer feedback when initially adding cards inline, and then once the cards drop into the list, we show when folks are editing those cards that have been added.

**Comment by jordanh** [comment]
Sounds like you'd like one more round of feedback from @mattkrick before proceeding. For my vote, I think what you are proposing is _Safe to Try_™

**Comment by ackernaut** [comment]
Okie dokie, heard another round of feedback and have an iteration here (comments on this frame and the one below it) [ [see Figma](https://www.figma.com/file/TLD1OTiMLONajdyYOaErrG?utm_campaign=team&utm_source=slack&utm_medium=message&utm_content=file_comment#1175427) 🔒 ]

**Comment by jordanh** [comment]
Closing in favor of #2242
