### ISSUE TITLE
Use automerge somewhere in our app

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2045]
I've got a haunting suspicion that delaying our move to automerge (https://github.com/automerge/automerge) is going to cause a lot a heartache, just like when we delayed our move to redis.

I'd like to incorporate it in some part of the app. doesn't matter what, something tiny, but just enough to start using the pattern so i don't have to keep writing very naive hacks to get around collaborative editing.

Notes:
- it provides no security or validation, so the state it shares should be temporal so some idiot doesn't footgun himself.
- we'll need to wrap it in an authenticated mutation so if Alice tries to send Bob a random message, Bob will ignore it because Alice didn't first send something verified by our server

Possible places to drop it in:
- drag state (is another user dragging?)
- retro group titles (let 2 folks edit the title at once, or at least don't completely overwrite!)
- editing state (is another user editing?)

Effort: 12 points

Acceptance criteria:
- [ ] use automerge in the naming of group titles

**Comment by jordanh** [comment]
Love this issue. My vote would be to try this in retro group titles. _Great_ place to get our feet wet here _and_ I ran into a title naming collision when I ran my first on-boarding with The Development Factory.

If you feel comfortable, would you update the AC @mattkrick ? Maybe the EE is 12?

**Comment by mattkrick** [comment]
on 2nd thought, i like the idea of trying this as a scratchpad. plain text to start, then we could implement it as a WYSIWIG

**Comment by ackernaut** [comment]
See #1941 for meeting scratchpad

**Comment by jordanh** [comment]
Scrubbed. Iceboxing for now. Still a fan. I'm sure this will come back around.
