### ISSUE TITLE
Move E2E tests to cypress

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2049]
Let's leave selenium.
Reasons:
- [ ] fails unpredictably. sometimes adding in a console.log will make it pass
- [ ] when it fails, i have to pkill node
- [ ] long startup time

Acceptance criteria
- [ ] move the 3 existing tests to cypress
- [ ] verify that cypress doesn't suck as bad as selenium

Effort: 11 points

**Comment by mattkrick** [comment]
https://blog.bitsrc.io/testing-react-apps-with-cypress-658bc482678

**Comment by mattkrick** [comment]
https://www.reddit.com/r/javascript/comments/97hktn/how_many_of_you_use_cypress/

**Comment by jordanh** [comment]
Scrubbed, but we're working on it now. Leaving it open

**Comment by jordanh** [comment]
We've got Cyprus now
