### ISSUE TITLE
Expand a task card

### ISSUE THREAD

**Issue by bjanjanin** [ParabolInc/action#2066]
## Issue - Enhancement

This issue is the implementation of a part of [1852](https://github.com/ParabolInc/action/issues/1852) ("I can expand a task card, leave a comment on it, and easily copy its unique URL"), designed in [Figma](https://www.figma.com/file/ZaF5UkRwPdZtNAeKHlffq4zj/Single-Kanban-and-Retros-UI?node-id=415%3A3918).

### Acceptance Criteria
Users can:
   - Expand a task card by clicking an icon.
   - Leave a comment in the expanded card.
   - Copy the unique URL of the card.
   - Perform all tasks from the sidebar that are available in the original card menu (available from the 3 dots icon)

### Estimated Effort: 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by bjanjanin** [comment]
@ackernaut Here's another issue ready for review. Thanks muchly!

**Comment by jordanh** [comment]
Scubbed. Iceboxing.
