### ISSUE TITLE
Retro summary, incorrect vote count

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2067]
## Bug

It seems the retro meeting summary is coming in with only 1 vote per theme under “Upvoted Reflections”, when actually there were more than 1 vote for many of the themes.

### Acceptance Criteria
- Users receive a summary with the correct vote count per reflection theme

### Estimated Effort
- 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
i think this is fixed, @ackernaut please reopen if not
