### ISSUE TITLE
Automatic Agenda Item: End Meeting

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#2069]
## Issue - Enhancement

When a team starts any type of meeting, at the stage where the Agenda is shown, it is pre-pop'd with an "End Meeting" topic, which can be prioritized at-will.
 -May help users with frequently observed habit of forgetting to End Meeting
 -May help teammates "see" if the meeting will end early if Facilitator moves "End Meeting" above other agenda items. (prevents mtgs from running too long; encourages collaborative, live, prioritization to ensure passion topics are elevated early)

### Acceptance Criteria (optional)
 - When the team reaches the "Process Agenda" phase of any meeting type, the topic "End Meeting" has been pre-populated
 - "End Meeting" is in a different color and/or font [perhaps orange bold italic?] to indicate difference from other Agenda item types
 - This "End Meeting" topic can be prioritized (moved) per usual
 - When the team reaches "End Meeting", the team sees: "Last Call: any other burning issues to discuss before the next meeting?" and the Facilitator also sees the "End Meeting" button here.
 - When the Facilitator hits the "End Meeting" button, the team immediately goes to Summary view. 

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
We have an End Meeting button in both meeting types now. Going to close this one and see if the need has gone away.
