### ISSUE TITLE
Diagnose e2e test for authentication

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2084]
## Bug

This test has been causing builds to fail over and over. I moved the file from `e2e/tests` to `e2e/stash` ([see commit](https://github.com/ParabolInc/action/commit/f0743ac2ff72708e84f18a25e1ed548c047aed93)) to clear up the build. This is safe as we currently test sign-in and sign-out manually.

### Acceptance Criteria
- Identified the problem with the test timing out on CircleCI
- Fixed the problem if within scope of effort, otherwise scrub this issue when new AC and EE to fix
- Restored the test file when fixed

### Estimated Effort
- 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Closing this in favor of #2049
