### ISSUE TITLE
shift-enter even over enter to blur on retro cards

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2089]
## Issue - Enhancement

This has come up with:
   * Abl Schools
   * August
   * RemoteYear

Folks are _very_ confused why enter does not save cards. I personally like tab to blur, but given that our product is primarily for non-engineers we should:

### Acceptance Criteria (optional)
Users can on Retro reflections:
   - Blur cards by pressing `tab` or `enter`
   - Create newlines on cards by pressing `shift-enter`

- **Estimated effort:** 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
Here's how it is today. please adjust the table as you see fit & we can discuss


|                         | Enter         | Shift+Enter | Tab            |   |
|-------------------------|---------------|-------------|----------------|---|
| Input (HTML Default)    | submit        | submit      | submit         |   |
| Textarea (HTML Default) | new paragraph | new line    | next tab index |   |
| Task                    | new paragraph | new line    | next tab index |   |
| Reflection              | new paragraph | new line    | next tab index |   |

**Comment by jordanh** [comment]
|     Context                    | Enter         | Shift+Enter | Tab            | 
|-------------------------|---------------|-------------|----------------|
| Input (HTML Default)    | submit        | submit      | submit         |  
| Textarea (HTML Default) | new paragraph | new line    | next tab index |   
| Task                    | submit | new paragraph  | next tab index |  
| Task, Code Block  | new line | new line | next tab index |  
| Task, List Context (future)  | new list item* | new line | next tab index | 
| Reflection              | submit | submit    | next tab index |  
| Reflection, Code Block (not supported)  | x | x | x |  
| Reflection, List Context (future) | new list item* | new line    | next tab index | 

*: When enter pressed on empty list item, list ends. Editing context set to new para

Here's a quick cap of how MS Teams does text input for capturing chat input. It's just about the only interaction in the tool I like 😊 

![tvxr3irswz](https://user-images.githubusercontent.com/103000/42139553-daa16202-7d44-11e8-87f4-b8a8a3e8b6f4.gif)
