### ISSUE TITLE
Org info exposed on team settings view

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2092]
## Enhancement

**Assumption**: folks poke around Team Settings and wonder about pending invites etc. oh the mystery

**Low-effort solution**: let’s expose some organization info and give some affordances

### Acceptance Criteria
A lo-fi concept illustrating enhancements on the Team Settings view:
- When I see a pending invite, I can also see who my billing leaders are including email addresses
- I can see what organization this team belongs to, and who my billing leaders are
- If I am a Billing Leader for the organization, I may not even realize it. I may poke around Team Settings looking for a path to upgrade. If I am Billing Leader and the team is on a free org, I want a clear CTA that takes me to the billing view

### Estimated Effort
- 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Closing in favor of #2108
