### ISSUE TITLE
Draggable divider when there are lots of reflection cards

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2093]
## Issue - Enhancement

"I feel like I should be able to drag that divider to see more task cards, rather than forcing me to scroll." – Abl Schools member

![image](https://user-images.githubusercontent.com/103000/39603188-566d8380-4edc-11e8-85cf-90d1f220cf81.png)

### Acceptance Criteria (optional)
Users can:
   - Hover over retro discussion center divider, see pointer change to hand
   - (optional) hover toggles drag control visibility
   - Move divider to change the ratio of the top/bottom viewport

- **Estimated effort:** 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
i really like this!
it'll still need to have a scrollbar in case it takes up the entire height, but it'd be good to have a button where you can click to collapse the Add a Task piece

**Comment by jordanh** [comment]
Obsolete with current design
