### ISSUE TITLE
New & Improved Interrupting Chicken™ 🐔

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2100]
## Bug

Repro with 2 users on 2 devices to maintain focus on task card:
- Get to the Retro Discuss phase with at least 2 upvoted topics
- On 1 device, focus a card
- On the other device, as the facilitator, move to the next topic
- Notice that the editing was interrupted for the other user. Also, when you go back it left the card in a false editing state.

**Estimated effort:** 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### Acceptance Criteria (optional)
- During the discussion phase: users can keep jamming on their task card content even if the facilitator moves forward in the new meeting type. The user has to move forward to rejoin via nav or big floaty button.

**Comment by mattkrick** [comment]
this is a bit more nuanced than an action meeting.

what if you're typing a reflection? when the facilitator moves on, the body of the cards is analyzed, so we can't let folks keep typing.
- do we disable moving to the group phase until everyone is no longer editing?
- do we treat it like interrupting chicken & that user gets an error when they finish typing & try to submit?
- do we disable interrupting chicken for reflections?

**Comment by ackernaut** [comment]
@mattkrick I was thinking of the Discuss phase. When moving from 1 voted topic to the other, folks lose task cards they are editing.
