### ISSUE TITLE
Team dash has org name, billing upgrade CTA

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2101]
## Enhancement

Capturing this from #1980 

### Acceptance Criteria
- [x] Adds the org name to the team dash header [now in production]
- [x] The org name is clickable (routes to org view with appropriate state for billing leader or non-billing leader, free or paid) [now in production]
- [ ] For billing leaders when the team is on a free org, adds a CTA that goes to the billing squeeze view to the team dash

**Note**: this may get done via #2098

### Estimated Effort
- 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
We could conditionally add a panel to the team settings view for billing leaders. [See concept](https://www.figma.com/file/DXqOZNFNbfvkBBxvPCKgfiNW?utm_campaign=team&utm_source=slack&utm_medium=message&utm_content=file_comment#1031530)

**Comment by jordanh** [comment]
I don't think this is low priority. Folks are confused about the org->team linkage all the time. Right now, it's impossible to know which team is on what org. We need to make this clearer. This is a good first step.

Remind me to surface an email from LK at iMatter in support.

**Comment by ackernaut** [comment]
We now have the organization name in the team dash header. Anybody can tap that link and see the org view (essentially read-only sans billing info for non-billing leaders). I think it’s good that org members now have a view into the org and we can put it in the right places.

Next, do we still want to add an upgrade CTA there when that team is on a free org? There is now an upgrade CTA under team settings. I felt that might be the appropriate place.

I would like navigation to teams to be grouped by org when the user is on 2+ orgs. Also, Matt has mentioned having an upgrade CTA that is always visible, perhaps above the logo. We can use the same logic: go to the 1 free org view, or go to the orgs list view with CTAs per free org when 2+

**Comment by jordanh** [comment]
Chose not to do third bullet
