### ISSUE TITLE
Non-billing leaders leaving an organization

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2121]
## Bug

Diagnose intermittent issue when non-billing leaders leave an organization. The non-BL taps “Leave Organization” then taps to confirm in the modal, but nothing happens.

### Acceptance Criteria
- Is this a consistent issue (see #2118)? Diagnose and add reproduction steps
- Fix the issue if it is simple, otherwise add info and update estimated effort, and we can reprioritize

### Estimated Effort
- 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Dup of #1956
