### ISSUE TITLE
Support Downgrades

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2123]
If our goal is to convert a lot more users, we should probably also spend the time to handle downgrades, since it takes awhile right now. No front-end necessary.

Acceptance Criteria
- [ ] any parabol employee can downgrade an organization from the graphiql interface.
- [ ] downgrading refunds the user for any unused time
- [ ] anything to add @jordanh?

effort: 11 points

**Comment by jordanh** [comment]
Good first step! Nothing to add.
