### ISSUE TITLE
Reflection card group layout

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2133]
## Bug

When the cards are in the Group phase, the `DraggableReflectionCard` has the intended margin of `8px` for the stacked effect. During the Vote phase, the cards in a group do not have a correct margin, and the stacking effect is tighter and not intended. The trick is finding a state on the `ReflectionCard` to add the desired margin, and on the correct containing `<div>` to not have unintended layout issues in other views like Reflect and Discuss.

**Estimated effort:** 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### Acceptance Criteria
- Cards visually stack as design

Bad 🚫 
![screenshot 2018-05-14 17 42 32](https://user-images.githubusercontent.com/307286/40027169-42dbec24-579e-11e8-822f-62e30c64e05d.png)

Good ✅ 
![screenshot 2018-05-14 17 42 44](https://user-images.githubusercontent.com/307286/40027177-4dc27608-579e-11e8-98b4-4b30bf58336d.png)

**Comment by jordanh** [comment]
Stuck on #2106

**Comment by jordanh** [comment]
I think we can unstick this one now, right @ackernaut?

**Comment by ackernaut** [comment]
This issue is obsolete because of new design, closing.
