### ISSUE TITLE
Improve Congratulations Modal on Upgrade to Pro

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2136]
The current modal congratulates you for giving us money, which isn't really a cause for celebration:
![confetti2](https://user-images.githubusercontent.com/5514175/40090261-9f565e9a-5865-11e8-8d09-0ad5ac9da888.gif)

Instead, we should have it be more like a video game & tell you what features you've unlocked.

Acceptance Criteria:
- [x] Congratulations modal designed

Effort: 11 points

**Comment by ackernaut** [comment]
[First pass in Figma](https://www.figma.com/file/FJ52DGmDUxddTfYlZwzqza7O?utm_campaign=team&utm_source=slack&utm_medium=message&utm_content=file_comment#1243277)
