### ISSUE TITLE
Hey autogroup, leave those grouped cards alone

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2138]
## Issue - Enhancement

When my team has grouped some cards manually, I don't want the autogroup button to ever take cards out of a group we've created, so that I feel like we have more power than the algorithm

### Acceptance Criteria (optional)
The facilitator can:
   - Group a series of cards manually
   - Press the autogroup button and have manually grouped cards remain intact while
   - Ungrouped cards may join manually created groups and/or
   - Be grouped in to novel groups

- **Estimated effort:** 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
yeah, this is definitely on deck for the next iteration.

**Comment by jordanh** [comment]
@mattkrick during scrub:

> I think the way forward is to not have an autogroup

Let's make the UX obsolete by auto-sorting cards, offering other affordances to easily group cards.
