### ISSUE TITLE
Due date color past due

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2140]
## Issue - Bug

Some due dates are showing the yellow-orange theme when they are past due and should be red. I think it may have to do with how we are rounding time. Perhaps the date was added earlier or later during the day? Just a wild guess.

**Estimated effort**: 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### Acceptance Criteria
- Due dates are the correct color theme for default, due-soon, and past-due states.

**Comment by ackernaut** [comment]
Yeah, I’m thinking it may be related to #2124

**Comment by mattkrick** [comment]
filing as dupe of #2124
