### ISSUE TITLE
Break out lobby from meeting / Revisit old meetings

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2142]
Abl Schools asked to be able to see the contents of past meetings. To do that, we either need to build a separate view with all the info, or just let folks revisit a meeting. i think the latter is better.
to do that, we need a new route for a meeting.

Acceptance criteria:
- [ ] going to /team/:teamId/retro takes you to the lobby
- [ ] if a meeting is in progress, the lobby redirects to /retro/:meetingId
- [ ] going to /retro/:meetingId when the meeting is complete redirects to the last complete stage. A header or subdued coloring lets the user know that the meeting is complete
- [ ] going to an invalid/retro/:meetingId redirects to /me
- [ ] the startNewMeetingMutation no longer requests an obscene amount of fields because going the route guarantees a meeting is already in progress & that's handled by the RootQuery
- [ ] root cause of #2181 patched
Effort: 12 points

**Comment by mattkrick** [comment]
stuck on #1722

**Comment by jordanh** [comment]
Closed during Sprint 18 planning meeting – may revisit later. (Going to stick in the icebox)
