### ISSUE TITLE
Buggy assigning task to new team with team removal

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2143]
## Issue - Bug

This is a fun one. Reported by The iMatter team when trying to split a big team into two smaller teams.

I verified it can be reproduced.

Reproduction steps:

1. As User A, create a team ("Team 1")
2. Invite a new user ("User B") to Team A
3. Assign tasks to User B
4. Create a new team ("Team 2")
5. As User B, migrate tasks to the "Team 2" via My Dashboard
6. Remove User B from the old team

What you'll observe:
* Tasks will be assigned to "User A" on "Team 2"
* Tasks will no longer appear in My Dashboard for "User B"
* If possible to detect the state of Task cards affected by this bug in the DB, a migration to fix them

- **OS:** macOS
- **Browser:** Chrome
- **Estimated effort:** 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### Acceptance Criteria (optional)
Users can:
   - Migrate their tasks from one team to another and,
   - Be removed from old team, preserving proper task user and team ownership

**Comment by mattkrick** [comment]
fixed in hotfix 2.0.1
