### ISSUE TITLE
make invitation urls smarter

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2148]
today, an invite url takes you to the /invitation url, which then redirects you to the signup page.

acceptance criteria:
- [ ] going to /invitation/:inviteId looks up the invite ID, gets the email address, sees if the user exists.
- [ ] if the user exists, send them to the signin page with the email field filled out if the email is not connected via oauth
- [ ] if the user does not exist, send them to the signup page with the email filled out

effort: 11 points

**Comment by jordanh** [comment]
See also, bug #2178
