### ISSUE TITLE
investigate slateJS over draftJS

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2149]
draft-js is the red headed stepchild of facebook offerings. we've been using forked versions of it for awhile now because it doesn't offer all the functionality we need, it has bugs, they've accepted 1 or 2 of my 6-ish PRs. They announced that supporting mobile devices is not in their game plan, which kinda blows my mind, being facebook & all.

It looks like the Slate-js guys have reached a similar conclusion. Slate is largely built off of draft-js, but offers the following features:
- [ ] more active community
- [ ] simpler API
- [ ] better serialization
- [ ] **collaborative editing**
- [ ] a plan to fix the android keyboard bug
- [ ] easier to programatically make changes (paste links, add buttons for super buttons, etc)

We've got some upcoming issues that will require investing some cycle into our draft implementation. before we invest that time, we should check out slate. I'm very hesitant to adopt a technology that doesn't have a major corporation backing the development, but that said, i don't think facebook is backing draft, either.

Acceptance criteria:
- [ ] refactor the reflection card to use slate instead of draft to get a feel for modals, bold/italics, etc. 

effort: 12 points

**Comment by jordanh** [comment]
Slate looks _so_ good. Seems like we should look at this before automerge. Do you agree?

**Comment by mattkrick** [comment]
both at the same time!
slate purposefully leaves out _how_ changes are communicated. i assume they did this so you could use automerge as a drop in, but i haven't dug around to see how folks are sending the diffs.

**Comment by jordanh** [comment]
I think we should try our damnedest to do this in the next sprint. What do you think?

**Comment by mattkrick** [comment]
got sidetracked last night & went down the rabbit hole as to why this is so hard for every rich text editor out there. Probably the most useful is https://bugs.chromium.org/p/chromium/issues/detail?id=812674

To sum it up:
- keydown, keypress, keyup, beforeinput, textinput, input, change events dont give the key code pressed because android uses something called compositions, which is what lets them do autocorrect. they do this because the future is swiping, dictating, etc. it's no longer single chars
- The current thought is to create a 2nd text editor, see how the android keyboard affects it, diff it against the current, derive an event, and then fire that event. They'll build that in august if no one comes up with a better idea before then
- i really like the idea behind https://github.com/humandx/slate-gboard/. basically, instead of listening to key events, you listen to composition events.  there are still bugs & edge cases, but i think this is the right approach & putting a heuristic or 2 in it would still be better than diffing the entire text area on each event
- good writeup on attempts is here: https://docs.google.com/document/d/1Hex89Di-r-Wfpo1DLAtxpetoX588ziXVoNyC87Je3Xc/edit#
- the spec is here: https://www.w3.org/TR/uievents/#event-type-compositionstart

**Comment by ackernaut** [comment]
Oh, solid research @mattkrick !!

**Comment by jordanh** [comment]
Crazy interesting.

**Comment by mattkrick** [comment]
closing in favor of rolling our own.
... or if that doesn't work, probably prosemirror.

i went down a rabbit hole getting android working with slate & i got it working, but slate's internal logic was too slow to keep up. so i fixed that, too, but then they had another hack with how they handled line breaks. also, i don't have much confidence in their OT implementation. they also don't support remote ranges. at the end of the day, it's only marginally better than draft, so i'm gonna punt on it for now
