### ISSUE TITLE
Refactor Task.assigneeId to Task.assigneeUserId

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2150]
for legacy purposes, we have `teamId, userId, assigneeId` where assigneeId === `${userId}:${teamId}`. this duplicate info causes bugs & makes mutations harder.

acceptance criteria:
- [ ] userId is replaced with `assigneeUserId`
- [ ] assigneeId is removed

effort: 10.5 points

**Comment by jordanh** [comment]
Per @mattkrick during scrub:

> Icebox for now, can revisit when we do something in this area again
