### ISSUE TITLE
Collapsible meeting sidebar designed

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2163]
## Enhancement

There has been user feedback about improving the grouping phase layout. I’m assuming it’s easier to review and group a lot of reflection cards if we maximize the workspace. Ideally there is less overflow of cards off screen, so it is easier to compare and also be more aware of multiplayer activity (who’s grouping other cards).

**Proposal**: let’s set the sidebar nav up to be collapsible, with some reasonable options. This would be in support of the effort around a better grid layout for some meeting views. What good is a great grid layout if we don’t maximize space?

### Acceptance Criteria
- Users can toggle the sidebar nav. The main meeting workspace gets wider (header, main content, control bar, etc. are full-width now).
- We can send an event to automatically close or open the nav based on meeting UX. Eg. a facilitator starts a Retro Meeting, we collapse the nav for Reflect, Group, Vote (the user can open it back up if desired), and we expand the nav for Discuss to show the agenda (once again, the user can close it if they want).
- We can optionally disable this in code, essentially fixing the nav in an open state. When the Action Meeting moves to the new meeting, I’m not confident the UX has a strong case for a collapsible nav. I think we actually want the agenda list to remain very visible to build the muscle.
- A subtle animation would be nice.
- A quick pass to see if there are any low-effort wins for small viewports (phones, tablets) would be a stretch goal.

#### Artifacts

- Created [a clickable prototype (Figma)](https://www.figma.com/proto/TLD1OTiMLONajdyYOaErrG/Retro-v1.1.0?node-id=1753%3A253&scaling=scale-down) that shows the visual states
- Created [an implementation issue (2184)](https://github.com/ParabolInc/action/issues/2184
) that can be updated as this design gets reviewed
- This [lo-fi prototype](https://codepen.io/ackernaut/full/PaqWmO) shows how the layout may update if the sidebar is expanded or collapses
- [ ] Validated with external users (after internal review)

**Estimated effort:** 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
@mattkrick mind giving the artifacts a look here for feedback on design and behavior? The details on how I envision it working are on the implementation issue (which can be updated as we find a better way).

**Comment by jordanh** [comment]
@ackernaut some thoughts:

### On clickable prototype (Figma) that shows the visual states

I like the collapse handle and the hover state. Safe to try.

I don't think the "NAV" letters are needed. I think we can rely on knowing what the hamburger does.

I think screen 3 of this proto isn't needed (it shows collapsed sidebar with no hamburger to re-raise)

### On lo-fi prototype 

Wow. Thank you for making this.

Not sure if the animation is the full intent or not, but to my eye it runs a little slow. I think the animation could run 50% faster. I edited the ease in animation to be `.1s` from `.2s` and I liked it much better.
