### ISSUE TITLE
make an html file at build-time

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2167]
today, we build an html skeleton & then fill it up with environment variables at runtime
this is good because we can change variables without changing the build

we do this by passing down a `window.__ACTION__ ` global object that holds all the variables we could ever need.

this is bad because:
- we use the window object, which is kinda hacky, but not too bad
- our initial HTML file is served up by our server instead of by our CDN, which is ~150ms faster!
- our server has an additional load of serving up html

acceptance criteria
- [ ] move all variables to build time (can upload vars to CIRCLE CI)
- [ ] redirect all HTML mime types to our CDN

effort: 11 points

**Comment by jordanh** [comment]
Scrubbed. Iceboxing for now. Nice to revisit when we want to look at performance again
