### ISSUE TITLE
remove double duck flashes & resize

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2169]
when you load or reload the dashboard, you see ducks flash & then flash again, but lower. it's ugly & unpolished. definitely puts a bad taste in your mouth if it's your first time visiting the site

acceptance criteria
- [ ] does not show loading ducks unless loading takes > 300ms
- [ ] only shows loading ducks for 1 component

effort: 10.5 points (2 hours)

**Comment by jordanh** [comment]
I'm glad you created this issue, I've sensed the same thing but struggled with how to capture it or suggest a way forward

**Comment by jordanh** [comment]
Released in v2.13.0
