### ISSUE TITLE
break app into separate repos

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2173]
now that we dont SSR, all the components are part of the client, not universal.
a good first step would be to move the components into the client folder, while the helpers stay in the universal folder.

A next step would be to experiment with a monorepo like lerna. where the client & server can have their own package.json.

acceptance criteria:
- [ ] investigate lerna & see if it'll work for our usecase. likely it'll end up with `client, server, universal` repos

effort: 10.5

**Comment by jordanh** [comment]
To mono repo or not to mono repo? That is always the question.

Scrubbed. Iceboxing for now.

**Comment by mattkrick** [comment]
bringing this out of icebox, refactoring the action meeting saw an explosion in build time & i'm not able to narrow it down without having 2 separate configs

**Comment by jordanh** [comment]
@mattkrick now that we've moved to a monorepo, could we close this one?
