### ISSUE TITLE
Unable to start or end retro meeting

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2181]
## Issue - Bug

User reports that they are unable to start or end a retro meeting on their team:

![image](https://user-images.githubusercontent.com/103000/40927661-20f95290-67d4-11e8-9f27-41516305c215.png)

- **OS:** macOS
- **Browser:** Chrome
- **Estimated effort:** 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### Acceptance Criteria (optional)
Users can:
   - End retro meeting in progress (or start a new one)
   - Root condition that caused odd state understood and cleared

**Comment by mattkrick** [comment]
meetingId is `HJACPuny7`. we'll need to dig into that to figure out why later

**Comment by mattkrick** [comment]
fixed, but root cause not identified. that work is in issue #2182
