### ISSUE TITLE
Add timezone tooltip for team members

### ISSUE THREAD

**Issue by bjanjanin** [ParabolInc/action#2183]
## Issue - Enhancement

This issue is for the implementation of timezone tooltips, first mentioned in the [ideas doc](https://docs.google.com/document/d/1rllBVgZLpQQvP9R3n_2EPigYYnogmQNElLMCUTjzg20/edit?usp=sharing) (see There.pm’s Timezone Overview). The design is in [Figma](https://www.figma.com/file/ZaF5UkRwPdZtNAeKHlffq4zj/Single-Kanban-and-Retros-UI?node-id=477%3A33104).

### Acceptance Criteria
Users can:
   - Hover over the teammate avatar and see a tooltip showing their current timezone.
   - The tooltip follows the cursor while it's placed on the avatar.
   - Users cannot click on the avatar or tooltip.

![screenshot 2018-06-05 09 50 28](https://user-images.githubusercontent.com/307286/40983771-f0585302-68a5-11e8-819e-c6dd9c34b7a4.png)

### Estimated Effort
11 points

**Comment by jordanh** [comment]
New Acceptance Criteria:

- [ ] Current Figma designs updated to capture idea for posterity on newest avatar bar

Estimated effort: 10.5 points

**Comment by ackernaut** [comment]
Here’s an iteration of latest ([Figma](https://github.com/ParabolInc/action/issues/2183)):

1) Avatars are overlapping by default

![team-dash-header-default](https://user-images.githubusercontent.com/307286/51335283-52765e00-1a47-11e9-8f4b-895f63a3c59b.png)

2) On hover they expand LTR, one can tap on an avatar, the menu has a header: name, connection indicator, conditional badge, email, minimal local time

![team-dash-header-avatar-menu](https://user-images.githubusercontent.com/307286/51335282-51ddc780-1a47-11e9-9d41-79b2133df59b.png)

Note: in this iteration all kanban board controls are grouped to the same secondary bar and the team name and settings icon is grouped with the avatars

**Comment by jordanh** [comment]
I like this a lot. It makes the product feel remote-first (which I think is a good default design principle). @ackernaut I'm going to hand you a card to create an implementation issue for this.
