### ISSUE TITLE
Collapsible meeting sidebar implemented

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2184]
## Enhancement

This issue captures implementation details for design of collapsible sidebar nav #2163 ([design](https://www.figma.com/proto/TLD1OTiMLONajdyYOaErrG/Retro-v1.1.0?node-id=1753%3A253&scaling=scale-down)) which is being reviewed! We can update the criteria below based on feedback and validation.

### Acceptance Criteria
- Users can collapse and expand the meeting sidebar navigation with a toggle control
- This is an optional prop for the sidebar component. I propose we do not allow this behavior for Action Meetings as long as the Team Agenda list is built in the sidebar. I propose we allow this behavior for the Retro Meeting to maximize space. I propose we do not allow this behavior in the Meeting Lobby so folks have a better sense of the structure of the meeting.
- This behavior can be triggered by meeting events. I propose we auto-collapse when a Retro Meeting is started and moves to the Reflect phase. Users can expand/collapse if they want at any time. I propose we auto-expand when a Retro Meeting reaches the Discuss phase. The Discuss phase layout better supports the sidebar being open so that folks can see the ranked topics. Users can collapse/expand if they want during this phase.
- There is a collapse toggle in the sidebar when it is visible. It has a hover state. Tapping the toggle collapses the sidebar. There is an animation. The layout fills the viewport width.
- There is an expand toggle in the top header space when the sidebar has been collapsed. It has a hover state. Tapping the toggle expands the sidebar, including animation. The layout fills the width remaining (viewport - sidebar width).
- The meeting top header fills the width available
- The meeting bottom bar fills the width available
- The meeting main content area fills the width available. The child content either adapts to fill the space allowed (e.g. max-width, or grid that fills space) or has a forced horizontal overflow (e.g. min-width of task columns). The main content area should only overflow either vertically (grids etc. Reflect, Group, Vote, Discuss, Agenda) or horizontally (min-width task columns, Updates). The Social Check-In should fit in the space allowed without overflow (responsive sizing). The Action Meeting views should use this main content area behavior, but it depends on viewport size as we are not allowing the sidebar to collapse (e.g. your browser window is small, the sidebar is fixed open, and horizontal overflow has been triggered for Solo Updates because we force a min-width on task columns). Updating the layout when the sidebar collapses or expand also depends on the view (e.g. we allow folks to expand/collapse and we use a masonry style grid for Retro phases, we have to decide when to trigger the layout to update based on the timing of the sidebar animation. Do we wait until it is fully closed to update that grid?).

#### Notes
- This is an enhancement that maximizes space for the new grid layout (#2166)
- This implementation is **dependent** on Vote phase information being removed from the sidebar and added to the bottom bar. (add issue here)

**Estimated effort**: 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
- i'm not sure we need to use relay to keep its state. The only component that this affects in the `NewMeeting` component, so we could just use component state
- i think we should move to a grid layout. it'll make this a lot simpler
- i am against min-width anything (except for itty bitty things like buttons). media queries + responsive layouts should conquer this
- On mobile devices, the standard practice is to put a backdrop on the app & the menu goes on top of that, taking up ~75% width. let's do that.
- i don't think it should ever default to being closed on the desktop.

**Comment by ackernaut** [comment]
Thanks for the thoughts @mattkrick 

### As for your points:
1. I think we should consider relay at some point it we update the menu state from nested components. For example, at smaller widths, if we favor the menu being closed, it would be nice to close the menu on any menu click (see the prototype below).
2. I briefly tried animating a grid layout but I’m not sure this is reliable across browsers and didn’t get it to work: [https://stackoverflow.com/questions/43911880/using-css-transitions-in-css-grid-layout](https://stackoverflow.com/questions/43911880/using-css-transitions-in-css-grid-layout)
3. We need min-width and probably max-width on task columns
4. The prototype is similar to what you describe. One additional element, at smaller widths, it only opens to navigate, otherwise it closes
5. I still don’t think closing the menu when the meeting starts is a bad idea in terms of focus, there’s no real need for it until the discuss phase. However in action meetings, I think collapsing it is a bad idea until we have a better way to access and interact with the agenda.

Here’s a prototype for behaviors:

https://codepen.io/ackernaut/full/ZRqqap

### Grid Layout
- The grid fills the space available
- The content scrolls with overflow-y
- In this demo there is a max-width of 6 columns at 1600px, centered

### Column Layout
- There is a min- and max-width for the columns, and the content is centered on a wide screen
- There is scrolling with overflow-x to access all columns
- There is scrolling with overflow-y to access cards in a column

### Sidebar
- At wider breakpoints it pushes open/closed
- At smaller breakpoints it is layered over the content and favors being closed

### As for meeting UX:
- Initially I didn’t want to allow collapsing the sidebar in action meetings until we have an easier way to access and interact with the agenda
- I didn’t want to allow it in the lobby because it might just be weird, but we could add a toggle at the top of the lobby when closed

### In the future…
…we may render similar components but in a totally unique layout once we start handling viewport size and orientation more elegantly. Not sure how far into the future we want to dream up our target implementation, but this current thinking doesn’t go too far. I’m not sure how far we can afford to think in the future about adaptive layouts. Not sure an adaptive app will feel like a native app designed from scratch anytime soon.
