### ISSUE TITLE
Move vote stuff from sidebar to bottom bar

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2185]
## Enhancement

Implements designs from #2040. This design is meant as an iteration alongside #2166 and #2184.

**Will add some static visuals here.**

### Acceptance Criteria
- Moves the count for my votes and team votes from the sidebar to the bottom bar
- Facilitators see my votes, team votes and advance button in the bottom bar
- All other participants see voting tip, my votes, and team votes in the bottom bar

#### Notes
- #2184 has a light dependency on this. Folks could still votes if the sidebar was collapsed, but the wouldn’t see votes remaining etc. until gets moved to the bottom bar.

**Estimated effort**: 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
Vote phase on a grid, updated bottom bar, for a participant:

![vote phase with grid non-facilitator](https://user-images.githubusercontent.com/307286/40991868-b71e7b60-68ba-11e8-958d-b53058b710e6.png)

Vote phase shows group modal for a participant:

![vote phase with group modal open](https://user-images.githubusercontent.com/307286/40991871-b81d5180-68ba-11e8-97ae-02fc2e425025.png)

Vote phase for a facilitator, no modal open, sidebar collapsed:

![vote phase with sidebar collapsed facilitator](https://user-images.githubusercontent.com/307286/40991873-b84a1418-68ba-11e8-8e10-5bbdd467c3a9.png)

**Comment by mattkrick** [comment]
broke this up.
modals are handled in #2221
voting icon is handled in #2241

moving votes from sidebar is still not handled
