### ISSUE TITLE
Fix new meeting scroll x & min width

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2192]
The current new meeting often has a disable horizontal scrollbar on the bottom (on linux & windows)
if you collapse smaller than 60rem, the background color goes away

![bad](https://user-images.githubusercontent.com/5514175/41075813-3151aa70-69c3-11e8-995d-bf204a95adc7.png)

on mobile, it looks pretty bad
![current](https://user-images.githubusercontent.com/5514175/41075864-85713f58-69c3-11e8-82f7-73f2f7cb6769.png)

acceptance criteria:
- [ ] there is no disabled horizontal scrollbar 
- [ ] a meeting can be any size width and the background color is still there
- [ ] on mobile, the meeting takes up the entire height in portrait mode

effort: 11 points

**Comment by jordanh** [comment]
Scrubbed. May not be a thing any more. Iceboxing.
