### ISSUE TITLE
Move to persisted queries

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2195]
graphql query strings are static. with our hybrid subscription strategy, those strings get really, really long. that makes for a larger initial payload, and larger query requests.

persisted queries is nothing more than using a lookup table on the client & server. query `123` mean `query foo {bar}` the client sends 123, the server looks it up, and bobs your uncle.
this is also safer because no one can request an infinitely complex query, thus locking up our server.

acceptance criteria:
- [ ] persisted queries are implemented
- [ ] the message size of queries, mutations, and subs is reduced

effort: 11 points

**Comment by mattkrick** [comment]
stuck on #2475. the new relay needs a new relay

**Comment by jordanh** [comment]
Hey! We did this! Closing.
