### ISSUE TITLE
deprecation issue: rename all refs from enviornment to atmosphere

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2196]
sometimes relay atmosphere is called relay environment. that's confusing. need to refactor the codebase, ~100 uses.

acceptance criteria: 
- [ ] environment is not used to refer to the atmosphere

effort: 10.5

**Comment by jordanh** [comment]
@mattkrick be nice to have a checklist of refs (maybe) to burn down. Going to leave open for now.

**Comment by jordanh** [comment]
Scrubbed. Iceboxing for now.
