### ISSUE TITLE
Dashboard loading states

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2197]
"It appears you are not a member of any team!" flashes for a split second as the [Parabol Dashboard loads]()

As we iterate toward a target dashboard implementation, we should include real loading states in the design.

### Acceptance Criteria
- Main dashboard containers have a loading state
- Components that load into the dashboard views can handle their own loading state

### Estimated Effort
- 11 points

**Comment by jordanh** [comment]
Might address when we redo the dashboard. Needs AC and EE. @ackernaut can we add?

**Comment by ackernaut** [comment]
I feel like this will be better handled as a part of the acceptance criteria (component X has loading state, etc.) for more specific implementation issues when we work on newer versions of the dashboard. Closing…
