### ISSUE TITLE
Scrollbar implementation, next steps

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2198]
## Enhancement

Handling scrolling and scrollbars is harder than it seems, but here’s where we want to get to:

### Acceptance Criteria
- [ ] The scrollbar component can be used globally anywhere there is overflow by design
- [ ] The scrollbar component can handle vertical and/or horizontal scrolling. Ideally we only design to overflow one direction or the other (eg. min-width columns might overflow horizontally whereas columns of task cards or lists of topics may overflow vertically)
- [ ] The scrollbars play nice with DnD interactions (and next bullet)
- [ ] The scrollbar component can handle scroll zones either as part of its design or plays nice with some other component or package that handles scroll zones. Scroll zones improve scrolling based on intent of drag-and-drop interactions.
- [ ] The look and feel of scrollbars is customizable to match our theme
- [ ] Users can grab the scrollbars (stretch goal?)
- [ ] The scrollbars show on hover of overflown content
- [ ] The scrollbars respect tight component layout (no breathing, no extra gutters/margins/padding, etc.)
- [ ] The scrollbars only show when there is truly overflow, just like a native scrollbar

#### Options to move forward
- [ ] Configure packages like `react-custom-scrollbars` and `react-dnd-scrollzone` because they work out of the box
- [ ] Fork and override packages like `react-custom-scrollbars` and `react-dnd-scrollzone` because they don’t exactly get us what we need
- [ ] Make our own package that 1) creates scrollbars and 2) handles scroll zones for DnD

- **Estimated effort:** 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
Not sure we will get to this in 6 months…will consider ice-boxing (also testing comment for the updated filter)

**Comment by jordanh** [comment]
Iceboxing this for now.
