### ISSUE TITLE
Design DnD tips for grouping

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2202]
it's not immediately clear what different drop targets are or what they do.

Acceptance criteria
- [ ] when a reflection is hovered over a reflection group, tell them they can drop it to add to the group, but tell them without words
- [ ] when hovered over the grid, tell them they can drop to remove from the group, without words
- [ ] when hovered over an invalid drop target, tell them nothing will happen (this may be as easy as doing nothing)

Effort: 11 points

**Comment by ackernaut** [comment]
From a user:
>A couple of points of feedback for you:
>- We found it good to have one person do the grouping, as it can get kind of crazy when multiple people are doing it.
>- The person doing it sometimes wanted to move cards out of groups as she progressed further with the grouping activity (an initial grouping at a later time didn't seem as right). However, not always did she want to immediately move a card from one group into another group. But it didn't appear to her that she could remove a card from a group and make it a standalone card again - it had to go into another group. She says it caused her to lose track sometime of where she wanted cards to go.

**Comment by mattkrick** [comment]
OK, here's my idea: just like we have a tag that shows the person dragging, we should have a tag that shows "drop to ungroup" when hovered over the background.

**Comment by jordanh** [comment]
This would be a great first thing to try

**Comment by mattkrick** [comment]
so the problem i see is i'm dragging & the tooltip is constantly changing as i drag between cards & blank space. The words are also pretty small being just a badge. We could mitigate the constant badge/no badge by always having a tooltip saying "drop here to group" if hovered on a card & "drop here to ungroup" if not on a card, but that's still a lot of wording for something that only beginners need.

a 2nd idea is having a large semi-faded bubble pop up on the bottom of the grid saying "drop here to ungroup" that shows up whenever the background goes lighter.

ideally, we want a visual cue that is obvious, but not tiresome for experienced users. I thought changing the background color was enough, but it looks like we need a little something extra. i think getting it right will involve changing how we display group drop targets, too. Ideally, i'd like to avoid using words because text is blah.

maybe we highlight the thing that you wanna drop on? if you hover a group, the group gets a blue highlight. if you hover the grid, the whole grid gets a highlight?

maybe we leave it as is? a little struggle before discovery leads to a sense of achievement.

**Comment by ackernaut** [comment]
I’m wanting to experiment with the visual representation of the hovered card/group (dropping as a grouped card) and the hovered grid (dropping as a single card). At a minimal I think I want to try the slightly darker background variant that I’ve been using in Figma. Perhaps later we have a throttled tooltip that only shows after a delay. And perhaps we put a clear drop zone at some edge (or all) of the grid that is more explicitly for dropping cards.

**Comment by mattkrick** [comment]
i like it. FWIW i'm not a huge fan of decreasing opacity of the drop target groups when hovered, although i'm not sure of a good alternative. for the background, i was using this as inspo: https://react-beautiful-dnd.netlify.com/?selectedKind=single%20vertical%20list&selectedStory=basic&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

**Comment by ackernaut** [comment]
Noted! I’ll see if I can peel this one out of the backlog sooner than later.

**Comment by jordanh** [comment]
Scrubbed. Iceboxing for now. May reopen after further user observations.
