### ISSUE TITLE
Retro - non facilitators can advance too far

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2205]
today, pressing the right arrow as a non-facilitator advances them to the next phase.

Acceptance criteria
- [ ] when on the grouping phase, a non facilitator presses the right arrow & it does noting

effort: 10.5 points

**Comment by ackernaut** [comment]
@mattkrick another thing I think we should consider, and I can write a separate issue, is that if folks don’t know what arrow keys do (advance, go back) they may inadvertently move from Reflect to Group and totally kill the mood of the meeting. I think we should consider disabling these keys when there is no way to go back from a UX perspective (meaning I can’t get back to the same affordances even if there is a read-only state for that phase). Thoughts?

**Comment by mattkrick** [comment]
yeah, we need to increase friction somehow.
ideas:
- remove hotkeys for phases that you can't go back to
- pop a modal asking "are you sure?" (bad idea)
- make them hit the arrow key more than once (first press highlights the move forward button, next press moves forward)
- make the first press highlight the move forward button & that's it
- pop a "moving forward..." modal that has a cancel button
- ???
