### ISSUE TITLE
add a service worker

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2207]
subsequent page visits should be faster.
let's add a service worker. create-react-app has a pretty good boilerplate.

acceptance criteria
- [ ] server worker added
- [ ] subsequent page loads are faster
- [ ] can detect new versions without logging in

effort: 10.5

**Comment by jordanh** [comment]
I agree with this one in principle. @mattkrick if you still have passion for this, let's open a new issue that more tightly defines what the service worker would do or would be a design issue where we could spend a few days researching it over a sprint.

Iceboxing for now.
