### ISSUE TITLE
fine-tune webpack chunks

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2209]
webpack chunks are super efficient. it finds highly related things & groups them all together in a single chunk.
but, it doesn't know our business logic.
For example, it doesn't make sense to have an "Agenda, invoice, and impersonate" chunk.

the additional code isn't huge, but it'd be nice to not be wasteful.

acceptance criteria
- [ ] chunks analyzed & pieces for uncommon routes are kept separate

effort: 10.5 points

**Comment by jordanh** [comment]
Scrubbed. Iceboxing for now.
