### ISSUE TITLE
Due date when done

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2211]
## Enhancement

When I move a card to the Done column, I don’t expect to see an orange color (due soon) or red color (past due) for the due date. There have been a few ideas floating arround:

- Perhaps it goes back to the neutral gray color since the warm colors may not be helpful in this column. Whatever the date on the card is when in the Done column is seen as purely information.
- We could consider making it green (like ✅ woot it was done) but this is a bad assumption. If I mark a card as due `18-06-14` and I don’t move it to Done until `18-06-21` I didn’t make the due date. Boo hoo, but I shouldn’t see a green color.
- There is the idea that the due date should change to the date it was moved to the Done column. So I marked `18-06-14` and moved it to the Done column on `18-06-21` so that becomes the new date. I don’t think this is helpful because it does not honor when the due date was. It is confusing because now the “due date” is really representing a “done date”. Not sure we need both. I think “date done” might be too granular until we have a timeline of comments and key event messages on the task card “Terry marked this task as Done — 18-06-21”.
- Trello has a checkmark on the due date and a way to warn about upcoming due dates. The due date turns green when the user has checked on it.
- Currently a user cannot select a date before the current date. I think there may be a UX case where a person wants to truly indicate when something was due even if it’s getting done later. I think we should allow adding due dates for past dates since the information is the due date, not the done date. Also, I’ve inadvertently toggled off a date and couldn’t get it back because it was in the past.

Without further design that resolves the UX between Due Date vs Done Date (which I don’t think will be prioritized anytime soon until we have card backs, card comments, card event timeline, etc. which seems more like a target implementation) I think we should do something minimal effort that reduces confusion and does not require design. So here’s the AC…

### Acceptance Criteria
- When a Task card is in the Done column the Due Date badge uses the neutral gray theme
- Allow for marking past due dates for clarity even if the task card is just now being created
- This depends on solving #2208 (closed) and #2140 (closed) and #2124 (open) so that the color is always accurate

**Estimated effort:** 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Scrubbed. Iceboxing for now.
