### ISSUE TITLE
Edge cases for grouping phase

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2214]
A few things that I've ruled out of scope for the initial release, but are still pretty critical:

1. Support multiple tabs for the same user. Right now, drag conflicts completely break when the dragger has 2 or more tabs open, even if one is in the background.

2. If a drop target is attached, the EndDrag mutation should always win. If User A always wins conflicts with User B & User B starts and finishes a drag before it gets a message that User A started a drag, everyone will ignore User B's EndDrag mutation,which means the data is out of sync with the database.

acceptance criteria:
- [ ] can drag and win conflicts with multiple tabs open
- [ ] clients are always in sync with DB. They don't ignore EndDrag events if a dropTarget is not null

effort: 11 points

**Comment by mattkrick** [comment]
3. can steal from self
steps to repro:
- start a drag on card A
- end the drag
- start a new drag on card A before the end message comes back

this can cause a number of bugs, including stuck cards & null boundingBoxes. the fix is when `endDrag` is set optimistically, it should have `isPending = true`. then, when it comes back from the server, `isPending = false`. `canDrag` should return false if `isPending == true`.

![startend2](https://user-images.githubusercontent.com/5514175/41563741-64dc5fca-7305-11e8-822f-7eea80429ee6.png)

**Comment by jordanh** [comment]
I think this might be done, ja?

**Comment by mattkrick** [comment]
yep, closing
