### ISSUE TITLE
Update prompt wrapping

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2220]
When there are many team members (causing for a wide avatar group) the prompt wraps below. It should probably be centered or left aligned while the avatar group remains to the right side when this happens. Will update with images soon.

**Comment by ackernaut** [comment]
will add acceptance criteria and estimated effort in the #future

**Comment by jordanh** [comment]
Touched this one during scrub @ackernaut,  can you please add AC and EE so we can prioritize? (Or close?)

**Comment by ackernaut** [comment]
Closing for now, we will probably have a running list of UI fixes/polish when we refactor Action to NewMeeting #1906
