### ISSUE TITLE
Scrollable retro modal

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2222]
## Enhancement

When a user has a smaller viewport size and opens a retro group in a modal that has a lot of reflections (say 2 dozen) the modal should be scrollable.

### Acceptance Criteria
- Users can scroll the modal content when there are many reflections causing overflow-y

- **Estimated effort:** 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Done!
