### ISSUE TITLE
Team toggle to label when user only on 1 team

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2223]
## Enhancement

When users are only on 1 team, task cards should have a team label, not a team toggle, in the My Dash context.

### Acceptance Criteria
On My Dashboard, users see:
- a team label on task cards when on 1 team
- a team toggle on task cards when on 2+ teams
- updated styles of toggle to match other controls on card

### Estimated Effort
- 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Been 6 months since there's been any activity. Iceboxing for now
