### ISSUE TITLE
Notification: removed from organization

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2226]
## Enhancement

Currently users are notified when:
- billing leaders approve new users
- billing leaders deny new users
- teams are archived
- added to a team where they were previously a member
- somebody assigns them a task
- somebody mentions them in a task
- when they are promoted to billing leader
- when they are removed from a team
- when there is an issue with payment info
- a non-BL is requesting a new user

It seems of low value, but does it make sense to notify users when they are removed from an organization?

### Acceptance Criteria
- Users are notified when they are removed from an organization

- **Estimated effort:** 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
Still a thing.

**Comment by jordanh** [comment]
I want to keep deferring this until it causes a little friction (even though it would be easy to implement)

**Comment by jordanh** [comment]
Scrubbed. Iceboxing for now
