### ISSUE TITLE
All notifications, real time and accurate

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2229]
## Bug

Many of our notifications update in real time and are accurate, however…

Locally when a person has been invited to a team on an org, but is removed from the org, they get sticky notifications that do not apply anymore, like the team invite. These invite notifications probably go away on refresh but are persistent before refresh.

Seems low priority, but capturing just the same.

- **Estimated effort:** 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### Acceptance Criteria
- Notifications view updates in real time when there are notifications that do not apply anymore

**Comment by ackernaut** [comment]
Need to test again since code changes

**Comment by jordanh** [comment]
Iceboxing for now
