### ISSUE TITLE
Billing Leader, Hotel California 🌴

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2230]
## Bug

>You can check out any time you like, but you can never leave

Got this error when trying to remove self (and self is billing leader) from org when there was another newly promoted billing leader:

```
Uncaught TypeError: Cannot destructure property `user` of 'undefined' or 'null'.
    at removeOrgUserOrganizationOnNext (RemoveOrgUserMutation.js:216)
RelayObservable.js:643
```

- **Estimated effort:** 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### Acceptance Criteria
- Billing Leaders can leave

**Comment by jordanh** [comment]
This is the best name bug, ever

**Comment by ackernaut** [comment]
Need to retest this after org user refactor merges

**Comment by jordanh** [comment]
Scrubbed. Iceboxing for now. Hope it's been fixed!
