### ISSUE TITLE
Warning on Add Task toggle, My Dash

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2231]
## Issue - Bug

Updating to use new buttons as toggles for menus. The older portal HOC tries to assign a `ref` but styled components don’t handle `ref`s.

You can see this warning on the Team Dash view from the Add Task button as toggle.

I think fixing #2171 will clear up this warning.

```
Warning: Stateless function components cannot be given refs. Attempts to access this ref will fail.

Check the render method of `PortalHoc`.
    in AddTaskButton (created by PortalHoc)
    in PortalHoc (created by MenuContainer)
    in MenuContainer (created by TaskColumn)
    in div (created by TaskColumn)
    in div (created by TaskColumn)
    in TaskColumn (created by WithStyles(TaskColumn)
    in WithStyles(TaskColumn (created by Route)
```

- **Estimated effort:** 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### Acceptance Criteria
- No warning, happy menus and toggles

**Comment by mattkrick** [comment]
Closing in favor of #2171
