### ISSUE TITLE
Normalize button usage

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2232]
## Enhancement

We use button variants. What are the design principles behind the usage? Is this consistent in the app? Also, we have some controls that could be moved to use button variants for consistency, especially in row components in various settings views.

### Acceptance Criteria
- Initial documentation of button usage written
- Buttons updated to be consistent
- Funky settings controls moved to use button variants

**Estimated effort:** 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
Still a thing. Scrubbed.

**Comment by jordanh** [comment]
Scrubbed. Iceboxing for now.
