### ISSUE TITLE
Update team views when team member removed

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2234]
## Enhancement

When a team lead removes a member under team settings, they can toggle back and forth between the team dashboard and the team settings and it still looks like the team member is there. Meanwhile, the removed team member got a toast, a notification, and has 1 less team in the left nav.

- **Estimated effort:** 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### Acceptance Criteria
- Lead can remove team member
- Team member row is removed (+1 for animation) immediately
- Avatar is removed from top-right avatar group on team views
- Team dashboard is up-to-date (task cards have updated owners)

**Comment by jordanh** [comment]
Good find!

**Comment by ackernaut** [comment]
This will go away soon…
