### ISSUE TITLE
Drag and drop task card over another task card’s editor 📝

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2235]
## Bug

Reproduction steps:

- Go to a dashboard with at least 2 cards
- Drag and drop 1 over the other so that your cursor is over the editor when you drop (note that your card may actually go back to where it originally was because you didn’t move it far enough for a change in sort order)
- You should see a console error that is also caught by Sentry ([see link internally](https://sentry.io/parabol/action-staging/issues/591933546/))
- Note that this doesn’t seem to degrade user experience in any way so non-critical

- **Estimated effort:** 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### Acceptance Criteria
- We handle the events described above so that there is not an error, maybe the editor just ignores the drop event and business as usual?

**Comment by ackernaut** [comment]
Sentry issue: [ACTION-STAGING-4V](https://sentry.io/parabol/action-staging/issues/591933546/)

**Comment by jordanh** [comment]
Well, this certainly solves a mystery as to where these errors had been coming from!

**Comment by ackernaut** [comment]
Just retested. Still a bug.

**Comment by jordanh** [comment]
Still a thing, but Iceboxing for now

**Comment by ackernaut** [comment]
Sentry issue: [ACTION-PRODUCTION-1KJ](https://sentry.io/organizations/parabol/issues/1113176144/?referrer=github_plugin)
