### ISSUE TITLE
Team agenda borked after removing a team member

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2236]
The agenda list gets borked when navigating from team settings to team dashboard after having removed another team member when team lead.

**Status**: saw it in production, trying to consistently reproduce

**Steps**:
- Go to team settings
- Remove a member
- Go back to dashboard
- Note either a breaking error or the agenda list will not toggle open if closed

**Comment by ackernaut** [comment]
possibly related to #2234

**Comment by jordanh** [comment]
EE: 1 point

**Comment by jordanh** [comment]
Discussed during scrub. Likely not an issue after refactoring team members to avatar bar. Closing.
