### ISSUE TITLE
Ctrl + click to copy tasks

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2238]
When I want to assign everyone on my team the same task, i want to write the card once & then give to everyone.

I think the cleanest way to do this is to go to the reassign menu & then hold down ctrl when i click a person's face.

Things up for debate:
- ctrl + click vs. another mod + click
- if i copy card 1 and it makes card 2, then i copy card 2, is the source card 1 or card 2?
- if someone changes 1 card, should it change them all?

acceptance criteria
- [ ] holding down ctrl when hovered on a face changes the pointer to `copy`
- [ ] the menu title changes to "copy to" when ctrl is pressed & the menu is hovered
- [ ] ctrl + click a face creates a new task with identical content
- [ ] a `sourceTaskId` metadata field is added to the new card so we can see how people use this. 

effort: 11 points

**Comment by jordanh** [comment]
Let's [assign design uncertainty level 2](https://app.getguru.com/card/yiyoL6ki/Product-Policy-Design-Workflow) to this and build out some high-fi prototypes to be tested, ideally with codepen or storybook.

**Comment by jordanh** [comment]
This keeps coming up. I'm sure the next time it comes up, we'll do something about it 😏 

Scrubbed. Iceboxing for now.
