### ISSUE TITLE
Refactored billing route to use new upgrade credit card form

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2239]
## Enhancement

The upgrade squeeze modal uses a newer credit card form than the older billing view.

### Acceptance Criteria
- Both the upgrade modal and the billing view use the same, newer credit card form

- **Estimated effort:** 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
I think this is done, correct?

**Comment by mattkrick** [comment]
done!
