### ISSUE TITLE
Change "Sign Up" to "Create an Account" or "Register"

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2246]
Sign In looks too much like Sign Up. We should rename signup. My vote is for "Create an account"

acceptance criteria
- sign up replaced with "create an account" or similar

effort: 10.5points

**Comment by jordanh** [comment]
2nding this. A new user just noticed this today and wrote in to say they didn't like it.

They also suggested changing the background (or some other macro detail) to differentiate the two views

**Comment by ackernaut** [comment]
@mattkrick @jordanh 

I think “Create an Account” sounds good. Do we change routes from `/signin` to `/createanaccount` or `/createaccount`??

**Comment by ackernaut** [comment]
oops, I meant `/signup`

**Comment by ackernaut** [comment]
We could alternatively do “Log In” with `/login` and “Sign Up” with `/signup`

**Comment by ackernaut** [comment]
Something like:
```
/* Auth Labels */
export LOGIN_LABEL = 'Log In'
export LOGOUT_LABEL = 'Log Out'
export SIGNUP_LABEL = 'Sign Up'
```

**Comment by mattkrick** [comment]
hmmm, i'm not sure what a good slug is.
i do like switching to login/logout, but that'll be a larger PR since it's kinda everywhere.

i like the /signup slug.
i also like /join /create, /new, /firsttime, /get-the-party-started

**Comment by ackernaut** [comment]
Also, I would think nothing prevents us from experimenting with CTA text eg. “Create a Free Account” where the normalized label is “Sign Up” or whatever we end up with.

Heading: Create a Free Account
Copy: [here’s how Parabol changes transforms your team and organization]
Button: Sign Up
