### ISSUE TITLE
Agenda item remove buttons show on hover

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#225]
UI Enhancement

When I am using the agenda list (on the team dashboard or within the meeting) I need a remove button that only shows on hover so that I can remove items from a clean, less noisy UI design.

**Estimated effort:** 1 point ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
I'm not sure I agree, since that means mobile users can't delete agenda items...

**Comment by ackernaut** [comment]
I agree with you…but we are ice-boxing handling mobile/responsive/adaptive at this stage. I would want to handle touch through styles, props and/or different components/layouts.

**Comment by jordanh** [comment]
I think @ackernaut's approach is fine for now, since I think the _very_ next thing we do post-Beta is a mobile-first redesign. Let's fight to earn that right.

**Comment by mattkrick** [comment]
implemented in latest PR!
FWIW, I still think it's _really_ confusing for those who don't know it exists. When looking at the page, I have no idea how to delete an item. When i hover over a completed item, nothing happens. Only when i highlight a future item does an X pop up. I think hover is good for non-essentials like darkening a button & should be avoided for core functionality, but it's cool if we disagree!
