### ISSUE TITLE
Meeting sidebar defaults to closed for smaller viewports

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2257]
## Enhancement

We have added the ability to close and open the sidebar. The layout is a decent start for mobile breakpoints, but it does not default to closed in favor of laptop UX as we are deferring on the mobile epic.

### Acceptance Criteria
- The sidebar menu is closed when the browser width is less than the sidebar breakpoint constant
- The sidebar menu is open when the browser width is equal to or greater than the sidebar breakpoint constant
- This happens on load without any flash of state (how can we get browser width before we render?)
- We can update the criteria to be smarter than just viewport width later on (say we add orientation, or look for touch devices, etc.)

**Estimated effort:** 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
So trivial, we should do it.

Scrubbed, but keeping open for now.

**Comment by jordanh** [comment]
Iceboxing
