### ISSUE TITLE
remove elevation from buttons on cards

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2258]
looks like we got mini cards inside our cards. we should probably remove that.

![cardofcards](https://user-images.githubusercontent.com/5514175/42603528-0ef693b6-8523-11e8-8011-6171c57c6876.PNG)

i'd be down for hover effects to be more lightweight. maybe just a darker color or heightened opacity? 

acceptance criteria:
- [ ] buttons on cards don't lift off the card

effort: 10.5 points

**Comment by ackernaut** [comment]
I think flat or text/icon only may work here. I may tackle this along with #2332
