### ISSUE TITLE
Agenda list input link/shortcut

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#226]
UI Enhancement

- When using the Agenda list, the user wants a link control that prompts the action so that it is clear how to use the interface. When the link is clicked, the field is autofocused.
- When using the Agenda list, the user wants a keyboard shortcut so that she can focus on the input quickly and add another item. Using the + character will trigger the same input.

**Estimated effort:** 2 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
Hitting `+` now focuses the agenda item input field (bullet point 2)
I'm not sure what bullet point 1 means...

**Comment by ackernaut** [comment]
![screenshot 2016-09-10 12 41 20](https://cloud.githubusercontent.com/assets/307286/18412446/ede9483c-7753-11e6-9912-50456817949d.png)

**Comment by ackernaut** [comment]
Ooh thanks @mattkrick for bullet #2.

Bullet #1 is referring to this styled link that is both a hit for the shortcut and clickable, which would immediately hide the link and show the focused inline input.

We may want to change this later, but I would at least like to test it with folks and follow latest design for momentum.

**Comment by mattkrick** [comment]
so we wanna hide the input box until someone hits "+"?

we absolutely can do this. before i implement it though, i'd argue that if the input box is the final state, and the final state is smaller (fewer words) than the initial state, then why not just always show the input box like we do now? "+" requires a shift key for laptops, which means i gotta take my hand off the trackpad to use it, so i'm betting most folks will just click, and clicking to focus an input box is more intuitive than clicking a link that replaces itself with an input box & then autofocuses it.

I'm cool with whatever you decide, just wanted to toss in my .02

**Comment by ackernaut** [comment]
Ok, let me look at this and get back with you—this isn’t blocking you ATM @mattkrick ?

**Comment by mattkrick** [comment]
nope, good on the list! next step is mergin the cards branch in & wiring up the realtime!
