### ISSUE TITLE
Implement standing agenda items

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2261]
## Enhancement

See #871 for background and details

### Acceptance Criteria

- Agenda items have a toggle that opens a menu
- Pin icon (as toggle) shows on pinned items at all times
- Vertical ellipsis (as toggle) shows on unpinned item on hover (we can revisit this for mobile)
- The menu allows for inline editing, pinning/unpinning, deletion
- Inline editing is text only, submit on enter
- Pinned items can be in any sort order
- Pinned items do not get deleted at the end of a meeting, they just collapse up in sort order
- Items retain their current UI state design if a meeting is or is not in progress (simple toggle hover when meeting is not active—hover, completed, and out-of-sync with facilitator when the meeting is active and the items are navigable)
- In the future we can consider changing author/owner (#175) 

[See Clickable Prototype](https://www.figma.com/proto/CexaOK4w42TNrfq8l6YInFfE/Agenda-Topics-Checklist-Phase?scaling=scale-down&node-id=38%3A4440)

- **Estimated effort:** 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by tayamueller** [comment]
validation from large Pro user:

**[user] "Looking forward to Pinnable Agendas / Team Checklist feature!"**

[Prbl] "We've de-prioritized these features [...]

**[user] "bummer - we've had it come up quite a bit - and i've been telling folks it's coming based on the models we saw a bit ago. [...modify the wording associated with Solo Updates] not so important for us - would much rather have [Pinnable Agendas / Team Checklist]**

[Prbl] "we're just about to enter into our planning process, I'll make sure your request gets some air time with the team and we'll see what we can do!"

**Comment by jordanh** [comment]
Been 6 months since we've had any updates to this. Iceboxing for now

**Comment by avivapinchas** [comment]
Just dropping my 2 cents here - for action/check-in meetings, this would be quite helpful. Right now, for our weekly Growth team check-ins, I just manually add the standing items. That means having to remember what they are and do some manual work to get them added. Doing this automatically would make it a bit easier, and would also allow others to facilitate more easily (they wouldn't have to try to remember what the standing items are).
