### ISSUE TITLE
Medium-fidelity Omniview journey designed

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2267]
## Issue - Enhancement

Omniview is like Mixpanel for workplace culture. It allows leaders to keep a watchful eye on engagement and cultural trends within their business.

This design issue will allow us to explore the designs for this product feature.

![image](https://user-images.githubusercontent.com/103000/42764458-8103adb8-88ca-11e8-8a7e-12fd170a670d.png)

### Acceptance Criteria (optional)
A set of 3-5 medium fidelity digital design mock-ups that we can use to:
   - Tell the feature story
   - Validate core assumptions of Omniview

That show:
   - Snippet of the Retrospective experience that asks team members quant engagement question(s)
   - Snippet of the Retrospective voting experience showing Reflection themes
   - Navigation to access Omniview
      - Accessible by leadership on limited-time trial unless feature is purchased (addn'l to Pro account)
   - Filter controls:
      - Data selection
      - Team selection that includes overall team health score (median mood of reflection cards combined with pulse survey results)
   - Trends design:
      - Selecting teams on left, and time range at center updates display of themes & verbatim reflections grouped by theme

- **Estimated effort:** 15 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### Positioning against whom

All of the below require regular survey data to populate responses. Most of them have implemented sentiment analysis and topic extraction to surface additional insights.

Only our product surfaces these using a process the team finds immediately valuable.

#### CultureAmp

![image](https://user-images.githubusercontent.com/103000/42764538-bb547cf4-88ca-11e8-970b-ad5e5ac08d6d.png)

![image](https://user-images.githubusercontent.com/103000/42764547-c4225e3c-88ca-11e8-97f4-b10745d266b0.png)

#### CultureIQ

![image](https://user-images.githubusercontent.com/103000/42764614-eac6fee4-88ca-11e8-991f-0dc9f525f3b6.png)

#### Tinypulse

![image](https://user-images.githubusercontent.com/103000/42765009-e127500e-88cb-11e8-8b15-5de804b7d113.png)

**Comment by jordanh** [comment]
See also: https://docs.google.com/presentation/d/10fsiIVYYnIFraSzcadVo_Vt1hH6JE6FIYFWTCi6Bv6A/edit#slide=id.g3acb8b88b4_0_6

**Comment by ackernaut** [comment]
A few questions here @jordanh :

>Accessible by leadership on limited-time trial unless feature is purchased (addn'l to Pro account)

Are there new roles in Parabol to account for leadership? Also, are you referring to an enterprise/business tier subscription upgrade?

>Team selection that includes overall team health score (median mood of reflection cards combined with pulse survey results)

What are you imagining for the pulse survey?

**Comment by jordanh** [comment]
> A few questions here @jordanh :
> Are there new roles in Parabol to account for leadership? Also, are you referring to an enterprise/business tier subscription upgrade?

I want to be _very_ lean about how we design this feature in. For starters, I want to sell it by manually adding a feature flag to the account. Later it might be a new account tier (Enterprise) plus a role that is assigned to give permissions to access this feature...

> What are you imagining for the pulse survey?

Something at the team level (vs. individual engagement). [This instrument](http://www.eye2eyedev.com/wp-content/uploads/2012/05/Team-Health-Check-questionnaire-020512.pdf) looks really good for starters.

What I imagine is we'll add an optional meeting section that will ask a subset of these questions each meeting. The team can get a good picture of how their teammates are feeling and trends on their team's engagement, and the company can keep an eye out for problems.

**Comment by mattkrick** [comment]
Stuck  behind narrative @jordanh

**Comment by ackernaut** [comment]
Closing this as I think this design cycle has been completed. Besides sharing and gathering feedback from others, next steps might look something like #2368 which includes addressing what we learn from others and starting to build a roadmap for implementation.

**Comment by jordanh** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/7111951) 🔒gave us the following feedback:

> Team health check feature (this one is considered to be used by two teams at least in a future)
