### ISSUE TITLE
Unable to change due date

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2268]
## Issue - Bug

Every once in awhile I'll have a task where I am unable to update the due date. Here is an example.

![image](https://user-images.githubusercontent.com/103000/42768174-a9319472-88d3-11e8-8795-a36406598d8c.png)

I imagine we'll have to look at this issue together to see what's special about this issue v. other issues.

- **OS:** macOS
- **Estimated effort:** 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### Acceptance Criteria (optional)
Users can:
   - Always change the due date of a Task card

**Comment by mattkrick** [comment]
dupe, see #2351
