### ISSUE TITLE
Autofocus on the welcome wizard forms

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#227]
## Issue - Enhancement

When a user transitions between steps on the welcome wizard, we should autofocus each form element, to reduce friction.

- **Estimated effort:** 1 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
@atannus if you feel like digging into our equity 4 effort program, this would be a great little PR to get your feet wet!

**Comment by atannus** [comment]
I'm happy to, @mattkrick, I'm currently getting familiarized with the stack.

**Comment by mattkrick** [comment]
Awesome! Take your time & feel free to reach out if you get stuck or see any other improvements as you start to grok the stack.
