### ISSUE TITLE
rate limiting

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2274]
i reread the figma article on rate limiting: https://blog.figma.com/an-alternative-approach-to-rate-limiting-f8a06cf7c94c

It's a neat approach, but a little overengineered IMO

I read another article by kong: https://konghq.com/blog/how-to-design-a-scalable-rate-limiting-algorithm/

it introduced a fascinating idea of keeping a local in-memory rate limit that then pushes to redis periodically. 

i like this idea because even though redis is fast, it'd be nice to not slow down the honest 99.9999999%.
we could even use a C++ hashtable binary if memory became a problem (i've played around with doing this to our pubsub, too, but the need hasn't really arisen yet).

using a sliding log, the key is the userId and the value is the timestamp. 
we have the unique challenge of also needing to store the mutation.
we could do:
`{user123: {inviteMutation: [12000, 140000, 16000]}}`
or `{user123_inviteMutation: [12000, 14000, 16000]}`
or if we're afraid of an attack distributed across many users:
`{inviteMutation: {user123: [12000, 14000, 160000]}}` 

alternatively, we could do something crazy.
we need to create a way to blacklist auth tokens.
we could use that same strategy to rate limit.
For example, Alice logs in, gets token1.
When Alice queries or mutates something, we look at her token & see if it's more than 60 seconds old.
if it is, then we send her a new token.
we also schedule her old token to get black listed in ~10 seconds.
then, if she tries to use the old token, we know it's nefarious.
the downside is if Alice was smart, she'd check for return payloads & update her token accordingly. 
we could get more advanced if we re-implemented the websocket guarantee, but that's no good

another dumb idea is to combine this with analytics in a lazy way.
- log operation to memory or redis instead of just the timestamp
-  before each new operation, apply a sliding log rate limiter using the log op
- when cleaning up the log operation, persist it instead of just deleting it
- free analytics!

**Comment by jordanh** [comment]
The rate limiter we implemented is an awesome and elegant start. Before we close this issue, should we open a new issue to extend our rate limiters state to redis so it will work when we scale?

**Comment by mattkrick** [comment]
i think it may get iceboxed. before better rate limiters we need to:
- reset presence correctly
- migrate the DB correctly
- ditch dokku to accomplish the 2 items above
- break graphql into its own microservice
- build a job queue or an http proxy so the web+socket servers can talk to the graphql endpoint 

that's a fair amount of devops stuff to do!
