### ISSUE TITLE
retro race bug

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2279]
still getting a bug when start & end are fired before start comes back:

![retrobug](https://user-images.githubusercontent.com/5514175/42910153-48adb7ec-8a9b-11e8-9fd0-a9ed0b46f8b8.png)

**Comment by mattkrick** [comment]
repro 1:
- get to grouping phase
- User 1 drop a card to form a stack
- Before the card finishes being dropped on the stack in User 2's view (1 second) User 1 picks the card up again and ungroups it
- NOTE: this only happens when the meeting is initially loaded, hitting refresh stops this from happening

repro 2:
User 1 drops card A on card B
User 2 picks up card B before card A is dropped on it

repro 3:
same user in 2 windows, repeat steps for step 1, get a toast

**Comment by jordanh** [comment]
Confirmed to still exist in PR #2307:

![gif](http://g.recordit.co/A98442j9W3.gif)
