### ISSUE TITLE
Wrong avatar on people

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#228]
## Issue - Bug

@mattkrick: uncomment out the avatar propagation in TeamMember

- **OS:** OSX
- **Browser:** Chrome
- **Node version:** v6.2.0
- **NPM version:** 3.8.9
- **RethinkDB version:** rethinkdb 2.3.4 (CLANG 7.3.0 (clang-703.0.31))
- **Estimated effort:** 1 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))-

**Comment by mattkrick** [comment]
The person creating the team has the cat avatar in Team Dash, their profile picture on the settings, and NO avatar on cards.
