### ISSUE TITLE
MailGun send reliability enhancements

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2283]
## Issue - Enhancement

When a message is attempted to be sent via MailGun and fails, the transmission attempt should be retried a certain number of times until it succeeds

### Acceptance Criteria (optional)
MailGun subsystem refactored such that:
   - it uses a job queue
   - submitted MailGun jobs can be retried X times

- **Estimated effort:** 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
@mattkrick what other AC to add here?

**Comment by mattkrick** [comment]
personally, i think a job queue is a little overkill for an edge case like this since the only work being done is a simple POST request. I'd just repeat the promise x times until it succeeds, and then fail if it doesn't.
