### ISSUE TITLE
Retro masonry not reflowing after received group event

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2284]
## Issue - Bug

When a team of users are grouping cards during a retro, the masonry layout does not (always?) reflow, leaving gaps and other layout bugs:

![image](https://user-images.githubusercontent.com/103000/43085740-93a93ede-8e50-11e8-9025-5eb294b51135.png)

- **OS:** macOS
- **Browser:** Chrome
- **Estimated effort:** 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### Acceptance Criteria (optional)
During group phase, a user's view:
   - Reflows after all local and received group events

**Comment by mattkrick** [comment]
closing in favor of #2279
