### ISSUE TITLE
End accidental meeting control

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2285]
## Issue - Enhancement

From user LK:
> Hi Parabol - had an interesting usage issue come up. We mistakenly started a meeting for the wrong team (started it for our Program Team instead of Anchor Circle). Two things happened:
>
> - Had to go through all the check-ins before we could close the meeting
> - Then - when the meeting was closed - it automatically "removed" all the done tasks from everyone's "done" column on that team. Is there any way we can easily get them back?
>
> Seems like there could be an easier way of stopping a meeting that was accidentally started.

JTBD:

When I start a meeting by mistake, I want a control that allows me to end the meeting as early as possible (and not flush my Done column), so that I can get back to work

Suggestion: we add a menu item under the Facilitator controls by clicking on the Facilitator avatar

### Acceptance Criteria (optional)
A design that:
  - End a meeting early
  - The Done column is not flushed if its an Action meeting
  - Does not clear the Agenda List that may already be in place

Design uncertainty: 3

- **Estimated effort:** 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
deprioritizing because the ask is for the legacy action meeting. we'll pick this one up when we upgrade the action meeting to the NewMeeting format

**Comment by mattkrick** [comment]
done during the 3rd demo sprint
