### ISSUE TITLE
Groups intermittently go missing advancing from group to voting

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2287]
## Issue - Bug

Repro steps:

1. As User A (Facilitator) and User B (Participant)
1. Create a series of retro groups (the more, the merrier!)
2. As facilitator, Advance to voting
3. Go back to grouping
4. Repeat 2-3 until failure is observed as User B

Super quick video capture:

![retro_group-vote_bug](https://user-images.githubusercontent.com/103000/43101450-47e45556-8e7d-11e8-8161-42882d440fc1.gif)

- **OS:** macOS
- **Browser:** Chrome
- **Estimated effort:** 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### Acceptance Criteria (optional)
Facilitator can:
   - Toggle between Group and Vote without Participant dropping groups

**Comment by mattkrick** [comment]
can't reproduce on latest, maybe the grouping fixes fixed this as well?

**Comment by jordanh** [comment]
I have super awesome reproduction criteria for this. Stumbled on it. Check it:

1. Start a retro
2. Create a bunch of reflections
3. Create 1 group of 3 or so reflections
4. Raise the group modal
5. With the group modal raised, advance to vote
6. Notice that the group is missing!

**Comment by mattkrick** [comment]
hahaha oh man, that's funny! i'll try it out tomorrow morning
