### ISSUE TITLE
Presence broken in meeting

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#229]
## Issue - Bug

When in a meeting, you always appear as offline.

- **Estimated effort:** 1 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Also another good "palette cleanser" option :)

**Comment by mattkrick** [comment]
@jordanh I think the new cashay fixed this, at least it did for me. Please confirm & close if so!
