### ISSUE TITLE
Meeting transcripts

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2296]
As we build out a meeting history viewer, i think meeting transcripts will be a huge player & one that folks would pay for. We can do that today as a cheap first pass at incorporating video.

Here's how I imagine it looks:
- There's a "Create meeting transcript" button in the lobby
- When you click it (out of curiosity) a modal opens up saying "To make a meeting transcript, we'll need your team to give us permission to listen to their voice while the meeting is in progress. Hit OK to send a request to your team members"
- When you hit OK, everyone else gets a modal saying "Matt has requested a meeting transcript, but we'd like your permission first. When a see a popup requesting access to your microphone, please click "Allow"
- Everyone gets the HTML5 microphone access request popup, they click allow or deny
- The allow/deny status shows up on everyone's badge in form of a red/green microphone. 
- Clicking on a red microphone sends another request to listen

Behind the scenes:
- The request opens up an audio stream.
- We run that audio stream through the SpeechRecognition API
- We send the text to our server, along with the start timestamp & duration. We do this for every word.
- The server gets the pieces from everyone & reassembles it based on the start times & durations

Phase 2:
- We offer a "Sub Titles" button in the meeting that has the ear icon.
- We open up a data channel via WebRTC (no extra permissions needed!) 
- we broadcast the words as they're generated to everyone who wants them.
- This is great for folks who have bad hearing, or have to mute their audio, or don't have audio, or don't speak english natively.
- The person talking gets a 1.2x sized avatar. If you talk for more than 1 minute, The avatar grows gradually up to 3x, hinting that you should stop your monologue.

Phase 3:
- We offer a "Use built-in audio" button in the meeting.
- This is a substitution for folks who can't access the video call that everyone else is on. For example, a subcon that didn't download zoom.
- Behind the scenes, we send a WebRTC audio track to all listening team members
- Team members listen to the track

Phase 4:
- We send the raw audio to our server in addition to transcriptions
- We perform sentiment analysis on the audio
- Maybe we use more advanced speech recognition if the native one is of poor quality

Phase 5:
- We offer video, which is sent among peers via webrtc
- Each avatar becomes a live feed, and the person talking has a 2x sized avatar

**Comment by jordanh** [comment]
Touched during scrub, be good to talk about `Phase 1`

**Comment by jordanh** [comment]
Let's generate a design issue from this discussion, I'll take a card to do so

**Comment by jordanh** [comment]
Discussed during 2nd scrub, decided to close for now. I assume we'll resurface this and create some design issue(s)
