### ISSUE TITLE
Welcome Wizard Step 1 should pull nickname from auth0

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#231]
This is especially useful for OAuth2 stuff

**Comment by mattkrick** [comment]
was this resolved in that PR #248? I didn't see a `nickname` anywhere...

**Comment by jordanh** [comment]
Oh shoot, I don't think I should have closed this. Moved too quickly.

I believe I closed this after adding `preferredName` and `picture` to the `createTeam` mutation.

Reopening now.
