### ISSUE TITLE
Replace screenshot button on retro-101 page 

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2310]
The "How-to" section of the current retro-101 page has a screenshot of the start button that includes the background. That doesn't look very professional.

Here's the same image with a white background:
![newstartbutton](https://user-images.githubusercontent.com/5514175/43903857-34ce03cc-9ba2-11e8-8bc7-f7d72de738ee.png)

acceptance criteria:
- the button doesn't look like a screenshot hackjob (even though it still is :speak_no_evil:)

effort: 10.5

**Comment by mattkrick** [comment]
yeah, i'm fine with a border around it instead, I just want it to not look like it was just cropped from another image

**Comment by ackernaut** [comment]
I’m using this image instead:
<img width="665" alt="screenshot 2018-09-13 17 22 57" src="https://user-images.githubusercontent.com/307286/45519915-de683880-b77c-11e8-852e-7fa0042181d7.png">

**Comment by ackernaut** [comment]
Per feedback, uploaded a transparent PNG, placed inside the newly added example image box:

![screenshot 2018-09-19 16 44 56](https://user-images.githubusercontent.com/307286/45783463-7063bb80-bc2b-11e8-9ec0-44bd13fe4300.png)
