### ISSUE TITLE
Responsive upgrade modal

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2312]
## Enhancement

This modal should be easy to use on smaller viewports.

![screenshot 2018-08-09 13 17 46](https://user-images.githubusercontent.com/307286/43917888-1ed2296a-9bd7-11e8-8099-e2a582a0101f.png)

### Acceptance Criteria
- The upgrade modal has a responsive layout that supports usage on smaller viewports (design uncertainty 1, a simple layout update in code could be enough for now)

- **Estimated effort:** 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Scrubbed. AFAWK nobody is upgrading on mobile, but we should really do this one day.
