### ISSUE TITLE
break apart toggleMenuState into distinct open/close actions

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2314]
react & toggle commands don't play well because it's possible to click really fast & trick react.
after fixing #2130 i noticed that if i clicked a menu toggle really fast 3 times, i could sneak in an extra click, which would make it look like the card was being edited when it wasn't.

acceptance criteria:
- [ ] use a distinct open & close action instead of a toggle action

effort: 10.5 points

**Comment by ackernaut** [comment]
I caught something similar in #2227 where you can get a false card focus state.

**Comment by jordanh** [comment]
Scrubbed. May re-open if this elevates again.
