### ISSUE TITLE
Updating elevation on components

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2324]
## Deprecation Details

**Deprecated**: we are no longer using `ui.shadow` from `ui.js`

**Moving forward**: we are using `elevation` or any specific named constants (eg. `modalShadow = elevation[24]`) from `elevation.js` for existing and new components, and as we update old components

### Acceptance Criteria

Components are updated to use default elevation (see Material as a baseline), or suggested elevation (per unique component design):

#### Via PR #2248 

- [x] Panels (resting `1dp` and raised `8dp`)
- [x] Base modal aka `DashModal`
- [x] Reflection cards
- [x] Tooltips (giving `0dp` [no shadow] a try ala Material elevation for tooltips)
- [x] Org billing card/panels (resting Personal and raised Pro)
- [x] Tag (yanking option for `hasDepth` to imply `0dp` as we stopped using depth for these)
- [x] Dragged discussion topic in retro sidebar (using `8dp` like a raised card)
- [x] Menus
- [x] Task cards (`OutcomeCard`, `TaskDragLayer`, `CreateCard`)

#### Via future PRs

- [x] Reflection group modal (#2331)
- [x] Raised buttons (#2332)
- [ ] Upgrade modal
- [ ] Dragged agenda item in action sidebar
- [ ] Raised sidebars TBD
- [ ] Raised navigation TBD
- [ ] Raised top/bottom bars TBD

### Effort
- **Estimated effort:** 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
marking as discussion since this looks like it's tracking work being done in other issues.

**Comment by ackernaut** [comment]
perhaps a deprecation label makes sense

**Comment by jordanh** [comment]
Adding deprecation label and making it immune from iceboxing

**Comment by jordanh** [comment]
Closing, I think we're good here now
