### ISSUE TITLE
Add meeting link & video to invite email

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2329]
When i get an invitation to join parabol, i currently see a "develop a weekly rhythm" link and a "add a task to the board" link. we should tone down the taskboard messaging. 

Here's my proposal:
- remove "Add a task to the board" link because it takes you to the same place as the Join Team CTA
- Add a link to the sales pitch-y video instead

in the future, we'll probably create a new user modal that pops up & offers you some more links, but that's TBD.

**Comment by ackernaut** [comment]
It makes me wonder if we get real annoying and pop a modal with a video in it for new users hitting the dashboard. I’m thinking 3 segments (20-30 secs each or less) 1) get the team started with a retrospective meeting 2) keep tasks up-to-date on the dashboard 3) follow up a week or two later with an action meeting

**Comment by jordanh** [comment]
This is the in-code invitation email. Let's design a quick mock before coding.

**Comment by jordanh** [comment]
## Acceptance criteria

- [ ] remove "Add a task to the board" link
- [ ] embed introductory video content & online docs links instead

**Estimated effort:** 10.5 points

**Comment by ackernaut** [comment]
Here’s a first pass: [content](https://docs.google.com/document/d/1G7UJWqGBk9DT52e56nciZAgYHKMsPhWqPoiHEkbLDqE/edit?usp=sharing) 🔒  and [concept](https://www.figma.com/file/BtZ74W4k0aDZlzHiyOK0en?node-id=183%3A2284&utm_campaign=team&utm_source=slack&utm_medium=message&utm_content=file_comment#2550049) 🔒
