### ISSUE TITLE
Refactor color palette

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2334]
Tensions:
- colors are hard to find.
- some colors clash, like if orange & rose & red are all on the same view, it looks not great
- our ui.js is too big

Goals:
- Easy to find a color
- Hard to pick a bad color
- Easy to change the palette & have the website look presentable
- modular files

Proposal:
2 APIs: high-level & low-level

low level API:
- palette with color roles. each role contains an object full of numeric values that have hexcodes
- the goal of the palette is to have a single declared object that contains every color in the entire app.

for example:
 ```
const palette = {
  primary: {
    500: '#F44336',
    900: '#B71C1C'
  },
  secondary: {},
  error: {},
  background: {},
  text: {500, 600, 700, 800}
}
```
  

high level:
- component names, similar to what we have like `ui.cardControlBackgroundColor`, however i'd like to sublcass all those into a `color` object that looks like this:
```
const color = {
  text: palette.text.400,
  textHeader: palette.text.800,
  textError: palette.error.300,
  background: palette.background.500,
  backgroundHighlight: palette.background.200,
  backgroundLowlight: palette.background.700
}
```

The naming scheme roughly follows an element + modifier schema, so `text` is the element and `error` modifies the element, so it comes second. There's 2 reasons for this:
- When I wanna pick a dark background color, i'm not sure what it's called, but i know it's a background of some sort, so i can look at names starting with `background`
- intellisense across all IDEs should be able to pick this up so as soon as you start typing `color.back` it'll give you all possibilities

**Comment by mattkrick** [comment]
i put some thought into this yesterday & came up with the following:

```js
export namespace PALETTE {
  export const enum PRIMARY {
    MAIN = '#493272',
    LIGHT = '#8869C2',
    DARK = '#3F2B63'
  }
  export const enum BACKGROUND {
    MAIN = '#F1F0FA'
  }
  export const enum TEXT {
    MAIN = '#444258',
    LIGHT = '#82809A'
  }
  export const enum ERROR {
    MAIN = '#ED4C56'
  }
}
```

by using `const enum`, it compiles down to the variable value itself. so instead of the client getting a huge import statement, they get just the hex color string. more importantly, it means that there isn't a giant object that we need to include in multiple bundles. the downside is that the consuming files have to be typescript files, but i think that's OK since we'll only use this strategy for new typescript files anyways.

**Comment by jordanh** [comment]
The discussion has yielded a new patter that we've begun to use. Closing it for now.
