### ISSUE TITLE
Refactor help menus in Action meeting

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2341]
## Enhancement

This is 1 small part of #1906 (Refactor Action Meeting into new format) and dependent on starting that issue.

### Acceptance Criteria
- Essentially follows the pattern used for help menu content in the retro meeting
  - [ ] Uses the latest version of the `HelpMenu` component
  - [ ] Moves help content from `helpLookups.js` to the respective view for each phase, and removes file `helpLookups.js`
  - [ ] Removes files `MeetingHelpDialog.js`, `LoadableMeetingHelpDialog.js`, and `MeetingHelpDialogMenu.js`
- **Estimated effort:** 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Scrubbed

**Comment by ackernaut** [comment]
I’ll see if this is still a thing…

**Comment by ackernaut** [comment]
Still a thing, part of Action meeting refactor

**Comment by jordanh** [comment]
Almost all of this work has been done, just a few files need to be removed. Removing stale and re-prioritizing toward top of next sprint
