### ISSUE TITLE
Break out new meeting lobby by meeting type

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2342]
## Enhancement

The UX of each meeting type is unique enough to warrant its own lobby instead of trying to handle everything conditionally in a single lobby to rule them all.

### Acceptance Criteria
- Created a `RetroMeetingLobby` component that maintains latest UI for Retro Meeting Lobby UX
- Created an `ActionMeetingLobby` that maintains latest UI for Action Meeting Lobby UX

### Stuck behind?
This can probably wait until we begin #1906.

### Estimated effort
10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
I like it!
This is a predecessor to #2142

**Comment by mattkrick** [comment]
holding off until we prioritize moving the action meeting to the new format, that way i'll know what to keep & what to toss

**Comment by jordanh** [comment]
Been 6 months since we've updated. No doubt we'll likely open this one again. Iceboxing for now.
