### ISSUE TITLE
Retro 101: Fix header

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2344]
The header on the landing page sits right over the content.
That means when i visit a link like https://www.parabol.co/getting-started-guide/retrospective-meetings-101#social-check-in the header covers up the title & i feel you took me to the wrong spot because i don't see a big & bold title.

The easier way to fix this is to make the header a few lines taller.

Acceptance criteria:
- [x] when i click a link from a help menu in a meeting, it takes me to the help page & i see the title of the section at the top of my screen

effort: 10.5

**Comment by ackernaut** [comment]
Anchors now have space to account for the fixed navbar.
