### ISSUE TITLE
Can’t select a GitHub repository

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2347]
## Issue - Bug

When doing the integration test checklist I was unable to add a repo and got this message:

>Repo 404? Make sure you have admin privileges in GitHub!

- **Estimated effort:** 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### Acceptance Criteria
- Diagnose if the problem is related to user permissions or not
- Update this issue w/ next steps

**Comment by Godokoro** [comment]
experiencing this as well 👎 
<img width="772" alt="screen shot 2018-11-26 at 23 52 35" src="https://user-images.githubusercontent.com/44638851/49059366-8dda7600-f1d6-11e8-8f74-14e71e3b67fa.png">

**Comment by tayamueller** [comment]
Thanks @Godokoro we've prioritized this for a hotfix

**Comment by Godokoro** [comment]
<3
