### ISSUE TITLE
support relay normalizePayload in storybook

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2349]
right now, storybook doesn't throw errors for relay stuff, but it also doesn't handle it.
it'd be great if we could pass in mock relay data. that would allow things like click handlers to work.
i think all it'd take is calling normalize payload with the operation root.
maybe we could use that component's fragment in place of the op root?

effort: 12 points

acceptance criteria:
- [ ] ability to feed mock data into storybook & have real things happen

**Comment by jordanh** [comment]
During scrub: We're not actively designing with Storybook right now. But, I bet we will one day soon! Going to icebox this. If it gets in our way (and I bet it will) we can reopen
