### ISSUE TITLE
Consider adding invitees to the team before they've accepted

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#236]
For a team leader, this means they can add everyone's items & then the person joining up has items when they join.

**Comment by jordanh** [comment]
I think this is a _good_ idea based on our testing; a TL can then pre-assign work. We could also use Team Settings page to then show the state of invitations for these team members.

**Implementation detail:** I think we could simply add an indexed `teamMemberId` field to `Invitations` and perform a joined query on the Team Settings container to be able to display the team member's invitation state. We wouldn't be accessing this state information all that often.

**Comment by mattkrick** [comment]
bumping this to epic 3, this would be a big change that we should execute based on feedback from beta users

**Comment by mattkrick** [comment]
i think this might be required if we move away from email-only invites.
If 2 teams invite the same person, we currently (in add-orgs) send 2 invite emails.
In the future, it'd be nice to only send 1 invite email & then create a notification for them to approve. This isn't possible unless that user already exists in the DB.
I mean it could be possible, we could have a queue of notifications & when the user gets created we check with the queue & then add notifications on, but doing it when we do this means notifications, projects, actions, etc all get added.

**Comment by mattkrick** [comment]
@jordanh any thoughts on this? if we implement this, we should do it now while we're fixing up the invite logic.
