### ISSUE TITLE
Omniview, next iteration designed

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2368]
Let’s capture feedback in this list to address in another design iteration:

- How might **aggregate topics** be presented that represent reflection topics common on multiple teams?
- **Create/Share**: Affordances to create a report and share a report must be clear. Perhaps add a secondary action to the menu list of saved reports to create a new report based on the current parameters.
- **Sentiment** for retro reflections can be positive, neutral, and negative. Explore how this impacts the insights and the qualification of reflections. Should the template customization dialog explicitly identify sentiment for each prompt?
- **Report CRUD**: Can reports be updated? Perhaps v1 they are all read-only.
- **Permissions**: Who can access? Org leaders? Can share report to: 1) other org leaders 2) specified team(s) 3) link-only
- **Awareness/Notifications**: How do we notify or get a user’s attention that this is a Thing™ and that there may be new, useful insights waiting for them there? In what contexts (user/team dashes, etc.) might we link and cross-reference insights?
- **First time in insights UI**: How might we orientate folks to the UI may seem a bit overwhelming at first (similar to something like Google Analytics). “Where to begin?”

### Acceptance Criteria
- [ ] Sketches are provided if introducing new concepts with fuzzy details
- [ ] Existing concepts and prototype are updated to reflect next round of iteration (can start with a copy of the file from the previous effort #2267)
- [ ] Designs are in a state where internal and external feedback can be gathered as needed
- [ ] A roadmap for implementation is started: first version, next version, target implementation

### Estimated effort

- 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
Here’s an [internal link](https://parabol.slack.com/archives/C0A0MRZH6/p1537805156000100?thread_ts=1537391070.000200&cid=C0A0MRZH6) 🔒  to a round of feedback from one of our users.

**Comment by jordanh** [comment]
Iceboxing for now
