### ISSUE TITLE
Prompt template customization dialog sync

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2373]
When 2 users open the template dialog in separate windows and edit the same prompt, it seems the template can become out of sync. This is probably an edge case in reality. I’m not sure how tight we want to sync this view for all players.

### Acceptance Criteria
- A solution proposed for syncing the dialog

### Estimated Effort
- 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
6 months since activity; iceboxing for now
