### ISSUE TITLE
Make editable components keyboard-friendly

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2374]
### Acceptance Criteria
- Folks can tab between editable fields when many are together, like regular input elements (eg. the retro template prompt modal)

### Estimated Effort
- 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Been 6 months since updates. Iceboxing for now
