### ISSUE TITLE
Active chits not showing

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2375]
In the reflect phase, the mini grid updates when new cards are added, but it does not show active editing.

### Acceptance Criteria
- Active chits are showing again

### Estimated Effort
- 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
fixed in #2376
