### ISSUE TITLE
Consistent reflection group stacks

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2381]
The reflect phase has centered stacks while the other phases still have the right-sided stacks.

### Acceptance Criteria
- All views with stacked reflection cards use the centered stack
- May be done along with #2382 

### Estimated Effort
- 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
stuck on #2382

**Comment by ackernaut** [comment]
Fixed in `v2.20.0`
