### ISSUE TITLE
Autogroup button makes groups go bye-bye 👻 🐛

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2383]
In the grouping phase, if you press autogroup a few times, you can bork the meeting. At first you might see the developer message, then if you refresh it seems the groups are gone but any ungrouped cards are still there and you can continue on as long as you can vote for a single card. If all the cards were grouped, then all the cards are gone and you can’t make it past the vote phase.

### Acceptance Criteria
- Autogroup is throttled, less prone to error

### Estimated Effort
- 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Released in v2.13.0
