### ISSUE TITLE
Reflect group modal polish ✨

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2384]
The reflect phase group modal needs some UI polish:

#### GIF
![rhq0fefpoz](https://user-images.githubusercontent.com/307286/45565857-a1eb1a00-b81a-11e8-972c-5f7715c66d92.gif)

#### Screenshot
![screenshot 2018-09-14 12 31 04](https://user-images.githubusercontent.com/307286/45565878-b4655380-b81a-11e8-8c98-cc6c88d9fafc.png)

### Acceptance Criteria
- Animation doesn’t overflow the bottom bar, then clip
- The modal has better inner and outer gutters when overflown
- The modal has elevation
- Consider the read-only state captured by #2400 

### Estimated Effort
- 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Still a fan of this one but iceboxing since its been 6 months since an update has been given.
