### ISSUE TITLE
Retro template select menu with many templates

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2386]
Not sure how to handle a long menu with many templates. I think it is important to see the customize option regardless of quantity of templates. Once 5 more templates are added, customize is lost. The menu scrolls to the current template. Do we create an inner scroll? Add a search pattern? Only show 5 then a link “See more” that adds the rest of the options?

![screenshot 2018-09-14 13 04 26](https://user-images.githubusercontent.com/307286/45567281-f8f2ee00-b81e-11e8-8075-b7efbb0fa497.png)

### Acceptance Criteria
- A menu UI pattern that handles this case and similar needs is designed and implemented

### Estimated Effort
- 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Let's make this a design issue with an uncertainty of 2

**Comment by mattkrick** [comment]
put everything but 'Customize' in a its own scroll container?

**Comment by jordanh** [comment]
Iceboxing as per policy, can re-open should the tension drive us to.
