### ISSUE TITLE
Recolor meeting badges & make meeting avatars bigger

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#239]
the teal & grey are WAY too similar.

**Comment by jordanh** [comment]
I prioritized this for our next beta epic. We know we need to make some tweaks here.

I think there are three elements to play with. I'm probably wrong. But here's a thought starter:

1. **Size**
2. **Handles on progress bar**
3. **Badging**

Currently our design is:

1. **Size:** all `size=small`
2. **Handles on progress bar:** all small squares
3. **Badging:**

User State      |   UI Element
--------------|-------------
Disconnected | Gray badge
Connected | Teal badge
Not attending | X in badge
Attending | Check in badge

A possible shift within this framework:

1. **Size:** lobby all `medium` or `large`; other rounds active participant is larger than the rest
2. **Handles on progress bar:** more obvious handles (outlined shape?)
3. **Badging:**

User State      |   UI Element
--------------|-------------
Disconnected | Warm badge
Connected | Teal badge
Not attending | Empty badge
Attending | Check in badge

**Comment by ackernaut** [comment]
closing this in favor of recent updates to avatars in the meeting
