### ISSUE TITLE
When in emoji picker, design state for no matches

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2390]
## Issue - Enhancement

When @tayamueller was in our retro, she typed a reflection card that ended with :) and tried to submit it by pressing the enter key. It wouldn't submit. This was because she was actual in the contest of the emoji picker, but she was unaware because no emoji begins with the `)` character.

There are a few options:

1. Be like GitHub and when there are no matches, pass the keypress event to the parent (not sure if this is possible
2. Be like Slack's emoji picker and elevate "Oh no! We can't find that emoji"
3. Be like Slack's line editor and match common emoji like :) to 😃 and :( to ☹️ 

### Acceptance Criteria (optional)
A design proposal that:
   - allows users to type words beginning with `:` followed by characters that won't match a named emoji and be surprised when the enter key does not submit the reflection card

- **Estimated effort:** 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
option 2 seems dumb. option 1 & 3 aren't mutually exclusive.
i'll do option 1 for now. we can do option 3 later when we come up with a list.
