### ISSUE TITLE
Retro guest design validation

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2391]
## Issue - Enhancement

Let's move our discussion in issue #1722 to a prototype that can be validated and reduce the uncertainty in this design from level 3 to level 2.

### Acceptance Criteria (optional)
A prototype where we can validate:
   - A user who wants to invite a user without a Parabol account to a retro understand how to do this
      - The affordance open the meeting to guests and create the URL and password
      - The affordance to copy the URL (which contains the password parameter automatically)
   - A user who receives a URL and passcode for a Parabol retro knows how to join the meeting and what to do
      - Screen 1 showing a link and passcode in Slack
      - Screen 2 showing a passcode to enter in the meeting lobby
      - Screen 3 entering an email and password
      - Screen 4 joining the meeting

- **Estimated effort:**  12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
Moving this to “In Review” as we get internal and external feedback. Happy to take more iterations on the concepts and prototype!

**Comment by ackernaut** [comment]
The outcome of this UX design relates to #2447

**Comment by ackernaut** [comment]
Stuck on prioritizing validation (currently working on demo and other epics)
