### ISSUE TITLE
Retro autogrouping improvements

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2396]
## Issue - Enhancement

...from tests conducted during PR review #2395

Auto grouping certainly works – i.e. nothing breaks. There are a couple of things I've observed:

1. The auto-group button no longer disappears when it cannot form new groups. It seems like you can always click it
2. The grouping heuristic doesn't seem super accurate on the data set I tried (dataset below). Not sure if the test was fair

I'm leaning toward merging this so that it's no fully borked. I will open a new issue to track tho.

Here's a screencap:

![gif](http://g.recordit.co/Xfyje8cjns.gif)

### Dataset
* Cookies
* Chocolate chip cookies
* Peanut butter cookies
* Cakes & pie
* peanut butter pie
* Cherry pie
* apple pie
* Pizza pie 🍕 
* Ice cream
* Cherry ice cream
* Vanilla ice cream
* Mango ice cream
* Pie crusts
* Salted caramel ice cream
* The letter pi
* Ice cream cone
* Tutti frutti ice cream
* I wish I had a cookie right now
* I eat ice cream, even in the winter
* Chocolate chocolate cookies 🍪 
* If your kid is being good, give them a cookie
* Eating pie
* Getting out the first slice of pie
* Slicing pie
* I've disabled cookies on my browser
* Ice cream 🍨 
* pie

### Acceptance Criteria (optional)
Users can:
   - Race condition eliminated:
      - When no more groups can be formed, disable/remove the autogroup button

#### Example data set

- **Estimated effort:** 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Needs EE @mattkrick

**Comment by mattkrick** [comment]
yeah, that's the race condition! if that happens reliably, it'll be a good test set to work off of

**Comment by jordanh** [comment]
In the future we should probably spec some test data sets and expected results if we want to improve the grouping performance

**Comment by jordanh** [comment]
For now, let's just make this about the race condition

**Comment by jordanh** [comment]
I just tried retesting this locally. I can no longer reliably reproduce the race condition 😢 Closing this for now
