### ISSUE TITLE
Team settings long team name validation not triggered

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2398]
## Issue - Bug

From test cycle 2 during PR #2392 

Repro steps:

1. Nav Team Settings
2. Rename team
3. Type many, many characters not validation does not seem to trigger

- **OS:** macOS
- **Browser:** Chrome
- **Estimated effort:** 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### Acceptance Criteria (optional)
Users can:
   - Type a long team name in team settings, see validation error
   - Correct team name, see validation disappear

**Comment by mattkrick** [comment]
currently working as intended i think? can you retry @jordanh?

TEST
- [ ] try to add a name that is longer than 50 chars, the input field won't have it

**Comment by jordanh** [comment]
Hmm. yeah, this looks ok now. Strange! Closing for now.
