### ISSUE TITLE
Animated Logo Loader Mission Spec

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#24]

**Comment by ackernaut** [comment]
Hot off the press (not really), here’s the mission spec:

https://docs.google.com/document/d/1rb_yFBR9U1RX_ulXr4j-zFGpO8fLS9AiNZi8jayfW0w/edit#

**Comment by ackernaut** [comment]
## Mission summary
Having a logo is good. Having an animated logo as a loader/spinner is better.

## Estimated Size
3 points ~ three or four days

## Mission Spec
[Read mission spec here](https://goo.gl/9Bvv7U)

## Design assets
[Link to assets on Dropbox](https://www.dropbox.com/sh/k5w3oy8tzahj5yd/AAABe5K5vRY93JzCoSL7bLX5a?dl=0)

**Comment by jordanh** [comment]
We're using our ducks for this. So I am going to close for now.
