### ISSUE TITLE
Retrospective Demo Script

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2416]
## Issue - Enhancement

We must raise the fidelity of our interactive retrospective demo design.

### Acceptance Criteria (optional)
A document that specifies:
   - what is the URL slug of the demo
   - what does introductory modal says
   - who are the simulated users
   - what are the reflections they create
   - what are the groups they create
   - what do they vote on
   - what are the actions that result
   - what are the help prompts that guide the user along the way

- **Estimated effort:** 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
Le document 📄 🔒 http://tiny.cc/e62lzy

**Comment by jordanh** [comment]
See: #2440,  #2441,  #2442
