### ISSUE TITLE
Create timeline events & CTAs

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2419]
AC
- a list of existing mutations by name that trigger a timeline item & the copy of that timeline item
- a list of CTAs to appear on the initial timeline

effort: 11 points

**Comment by jordanh** [comment]
The question this issue answers is, "what existing functionality would we make events from?"

## What are the implementation options?

**informational**: a cheap string that appears on the timeline, no fancy-dancy components trying to drive user behavior
**fancy**: something with some custom CTAs, etc. to drive user behavior

| Mutation Name  | Friendly Event Name           | informational/fancy  |
| ------------- |:-------------:| -----:|
| addTeam      | New team added | informational |
| addTeam      | New team added | informational |

**Comment by ackernaut** [comment]
[Table of events/CTAs here](https://docs.google.com/spreadsheets/d/1PPzFa6Q5-xEdYK37KH3JCyp9Ga93xJpHSliNdTHw9nU/edit#gid=1229019146) and [visuals in Figma here](https://www.figma.com/file/IKMfMmMmOxDUWrHfsVgxU740?node-id=53%3A3&utm_campaign=team&utm_source=slack&utm_medium=message&utm_content=file_comment#3146899)

**Comment by mattkrick** [comment]
At a high level, what's the difference between an event and a notification?
If someone finishes a task i assigned to them, is that event, notification, both, nothing?
When we add the timeline feature, we'll need to migrate folks over to the timeline. What events should we migrate?

**Comment by ackernaut** [comment]
@mattkrick that’s a real good question…let me ponder that. We need to come up with the minimal razor for a notification, an event, and a suggested action. And then we map what we do first, next, and target (future) in terms of what to introduce, migrate, etc. so that we can iterate in small steps. I’ll take a card for a next step on this issue.
