### ISSUE TITLE
Retrospective Demo Prototype designed

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2420]
### Acceptance Criteria
1. A pen-and-ink is created with internal feedback following the script illustrating UI affordances and flow of demo meeting
2. A clickable prototype is created with rounds of internal feedback and iteration
3. The prototype is tested with 3-5 external users
4. UI/UX implementation details captured as 1 or many issues

### Estimated Effort
- 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
Getting started [in Figma](https://www.figma.com/file/ae5A8qkieRAgTRAsvT5ylE4W/Demo-Concepts?node-id=0%3A1) 🔒

**Comment by jordanh** [comment]
@ackernaut to add validation AC to  #2440,  #2441,  #2442 – closing this in lieu of jumping right to implementation
