### ISSUE TITLE
Move check-in round to team settings, disable by default

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2421]
## Issue - Enhancement

When folks don't have a culture of check-in rounds, they find them confusing. Let's disable them by default and make them a team setting.

### Acceptance Criteria (optional)
A design that:
   - Allows a user to enable disable the check-in round (from the team settings or on the lobby)

- **Design uncertainty:** 3 (lo-fi design needed)
- **Estimated effort:** 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
[More validation](https://parabol.slack.com/archives/C836NA350/p1539920556000100)  🔒 [internal link]

**Comment by ackernaut** [comment]
[An early concept in Figma](https://www.figma.com/file/g7TeqDMSxMEx3QYcoQ5jYaxb?node-id=1%3A43&utm_campaign=team&utm_source=slack&utm_medium=message&utm_content=file_comment#2523654) 🔒 [internal link]

**Comment by ackernaut** [comment]
For review (see yellow notes):

1. Add a settings sheet in the lobby
2. Update team and org settings to tabs. Add a tab for meetings under team settings.
3. Move toward a settings sheet with new layout and IA

[See concepts in Figma](https://www.figma.com/file/g7TeqDMSxMEx3QYcoQ5jYaxb/Team-Settings?node-id=0%3A1)

**Comment by ackernaut** [comment]
See next steps in issue #2491 including dependent issues
