### ISSUE TITLE
Demo CTA & link placements designed

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2425]
## Issue - Enhancement

Where do we link our retro demo? 

### Acceptance Criteria (optional)
Considered placement for our retro demo in places including:
   - Retro lobby
   - Front page CTA
   - Future help section of website

- **Estimated effort:** 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))
- **Design uncertainty:** 3 points

**Comment by ackernaut** [comment]
On the homepage, we discussed updating the CTA “Sign Up — It’s Free” for 25% of traffic to primary [Try a Demo — No account required] and then a secondary action link to sign up both in the hero and the header nav.
