### ISSUE TITLE
Improve project columns

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#243]
Enhancement
- [x] Columns (lanes) should fill the vertical height even when empty.
- [x] Columns are independently scrollable when having many cards. 

**Estimated effort:** 1 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
Also -- for columns that have many items, it's auto scrolling to the bottom (in the meeting). We should disallow this.

**Comment by ackernaut** [comment]
I have an idea that I want to try, where we make columns fill the viewport and each column is scrollable. This would be similar to Trello, although not the goal. Thoughts @mattkrick ?

**Comment by mattkrick** [comment]
i like it!

**Comment by mattkrick** [comment]
PS the reason it was autoscrolling to the bottom was the autofocus on empty rule that i set. since the last item was blank, it was autofocusing on it. I think this is acceptable, so no extra work required on my comment up above

**Comment by ackernaut** [comment]
Yeah I forgot to add the detail on each column being independently scrollable. So we are good?

**Comment by ackernaut** [comment]
Updated the bullets! ¡gracias! MK
