### ISSUE TITLE
DnD failure of penultimate agenda items

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2430]
## Issue - Bug

When I have a list of agenda items, neither user was able to reorder the final 2 items after processing several. Here's a gif of the behavior:

![gif](http://g.recordit.co/dUNW2H4bd7.gif)

This is a one-time failure. No repro criteria yet. Opening this to track it, in case it happens again. 

- **OS:** macOS
- **Browser:** Chrome

### Acceptance Criteria (optional)
Users can:
   - Drag and drop all items to any unprocessed position, including the last 2 items

**Comment by jordanh** [comment]
Ok, I have repro steps for this one. It's _super_ corner case-y:

1. Start an action meeting with User A
1. Create 3 agenda items
1. Proceed through updates
1. Proceed through First Call to the first agenda item
1. Navigate back to Updates, note that 1st agenda item is marked as completed
1. Navigate back to first agenda item (the item marked as completed)
1. Try to reorder agenda items 2 and 3, note that this fails

**Comment by mattkrick** [comment]
this is a great excuse to move the action meeting agenda item list to react-beautiful-dnd. that way it'll look the same as topics in the retros meeting.

**Comment by jordanh** [comment]
Implemented in #2490, needs testing

**Comment by ackernaut** [comment]
Fixed in `v2.20.0`
