### ISSUE TITLE
Discuss task grid layout overlap

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2432]
![screenshot 2018-10-03 15 14 12](https://user-images.githubusercontent.com/307286/46436836-89866500-c71f-11e8-845a-f87dc5a7b34b.png)

### Reproduction Steps
- Locally, start a retro with two users using separate browsers
- Advance to the Discuss phase
- In 1 window, add a first task card with 2 or 3 lines of text, then make another card or 2 to get the Add a Task control to wrap to a new row
- In the other user’s view you should see that the 2-3 line card is over the Add control
- The grid layout will update correctly for the user interacting with the cards, but will not update correctly for the observing user who is not actively interacting with the cards

### Acceptance Criteria
- The grid updates once a card has been added/edited and updated so that there is no overlap
- **Note**: may be related to #2455 

### Estimated Effort
- 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
@mattkrick looks like this is a thing during the demo, too:
![screenshot 2018-10-23 15 11 03](https://user-images.githubusercontent.com/307286/47387778-f1541e00-d6d5-11e8-90a0-dd1a4760836c.png)

**Comment by mattkrick** [comment]
any repro steps? i can't get it to do this

**Comment by ackernaut** [comment]
Yeah, you may need to try two users in separate windows. Interactions with the cards seem to cause render updates, but for the other user who is just observing, sometimes it gets stuck.

**Comment by ackernaut** [comment]
@mattkrick I added steps to the top comment, they should be reliable.
