### ISSUE TITLE
Improved agenda queue on team dashboard

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#244]
## UI Enhancement
- Remove hover state for clickable link desc. because a user cannot navigate anywhere.

**Estimated effort:** 1 point ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))
- **(Optional) link to mission spec:** ([duplicate and edit template](https://docs.google.com/document/d/1lgTJnJzBt9-4If883iOvthmc0hy-6C6hBF7KNN-lsXU/edit))

**Comment by jordanh** [comment]
@ackernaut I think we could probably close this one as "wontdo"...I think we've designed around the needs here. What do you think?

**Comment by ackernaut** [comment]
I think we can at least pass in a state that takes away link hover state on dashboard, as you can’t click to anything—so reduce the scope? Would be very minor code change with just bullet two and I can take it.

**Comment by ackernaut** [comment]
Updated!

**Comment by ackernaut** [comment]
This shipped with v0.16.0

**Comment by jordanh** [comment]
Woot!
