### ISSUE TITLE
Seamless auth component anywhere 🔐

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2447]
At key moments in the UX flow (demo meeting, meeting guests) we would like to make creating an account or signing in more seamless, less disorientating. This may look like a sheet or a modal that can stand alone or animate in over the UI view.

### Acceptance Criteria
A concept that explores:
- A sheet UI variation of the component that animates in or can stand alone
- A modal UI variation (perhaps the inner components can live on a page, sheet, or modal)
- The component supports content (can default to evergreen or be context-specific eg. why folks like Parabol) and auth views (sign in, create an account, reset password)
- The layout of the components can be left/right, top/bottom, friendly on laptop, mobile, etc.
- A clickable prototype that is validated internally
- A clickable prototype that is validated internally
- An implementation issue is created with criteria, effort, and next steps

### Estimated Effort
- 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
Here are some concepts in Figma: [auth sheet concept](https://www.figma.com/file/XNxOV2fnHf67Ds2jjn4SzqmY?node-id=75%3A704&utm_campaign=team&utm_source=slack&utm_medium=message&utm_content=file_comment#2523828) and [auth modal concept](https://www.figma.com/file/XNxOV2fnHf67Ds2jjn4SzqmY?node-id=75%3A2615&utm_campaign=team&utm_source=slack&utm_medium=message&utm_content=file_comment#2523833) 🔒 [internal, Figma]

**Comment by ackernaut** [comment]
Relates to #2442 and #2391

**Comment by ackernaut** [comment]
Added a milestone here “Guests” @mattkrick

**Comment by jordanh** [comment]
Scrubbed. Iceboxing for now. Smaller issues capture elements of this.
