### ISSUE TITLE
Demo segment events

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2448]
I'm opening this issue as a discussion to shape the AC.

Certainly we'd like to know:
   * When a user begins a demo retro
   * When a user successfully finishes a demo retro

We might want to know:
   * Individual phases starts/stops

Is there anything else that's a must-have? Anything that'd be nice to have?

**Comment by ackernaut** [comment]
How many do or don’t create an account:

- Via the demo summary CTA
- Via the demo kickoff modal secondary action

Basically what percentage of demo users make it past the sign up phase of the funnel?

**Comment by mattkrick** [comment]
hypothesis: people who run a demo are more likely to run a retro after creating an account

**Comment by mattkrick** [comment]
* how long does the help menu stay open

**Comment by jordanh** [comment]
Collecting our ideas during scrub:
- "When a user begins a demo retro" can be done via a `Loaded a Page` event
- "When a user successfully finishes a demo retro" can be done via a `Loaded a Page` event
- "Individual phases starts/stops" can be done via a `Loaded a Page` event
- "Via the demo summary CTA" can be done via Mixpanel funnel analysis

Only one that we cannot do is:
- "how long does the help menu stay open"

### Questions

1. Should we creation an issue for the above event (i.e. do we think it's important?)
2. What issues need to be prioritized in order to make `Loaded a Page` work for measurement?

I think it's #2500 and #2512. Are there any others?

**Comment by jordanh** [comment]
I think this issue is covered. Closing.
