### ISSUE TITLE
mid-meeting kill switch

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2450]
AC
- [ ] design where to put the kill switch to kill a meeting before it is complete (facilitator bar? requires handling where to put vote info for participants).
- [ ] decide on copy (end meeting vs. kill meeting?)
- [ ] in the demo, the copy is different (eg I'm convinced, let me sign up!) that takes them to the create-an-account route
- [ ] clicking logo, or team name, when not a user, takes them to `/create-account`
- [ ] clicking logo, or team name, when signed in, takes them to `/me`

effort: 11 points

**Comment by ackernaut** [comment]
Working on normalized bottom bar controls [in Figma](https://www.figma.com/file/CjRSl4d5IZh3MspudYhgBsPt/Meeting-Controls?node-id=0%3A1) 🔒

**Comment by ackernaut** [comment]
I think that if somebody ends the meeting prematurely, or hits any links in the sidebar (team name, Parabol logo, etc.) we should send them to the `/create-account` view for now, and perhaps we update the design at some point to include the top feature bullets with icons.
