### ISSUE TITLE
Add CSV download link to email summary

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2453]
## Issue - Enhancement

When I want to download a retrospective as CSV and I receive the email, I want to see instructions or a download link to receive my data, so that I can download it

### Acceptance Criteria (optional)
Users can either:
   - Click a link directly from the email to get the retrospective meeting as CSV or,
   - See an instructional link allowing them to click through to the web version of the summary

- **Estimated effort:** 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
2 options:

A
- each email contains a token. that token is used to create a JWT that can fetch the necessary graphql query

B
- the email includes a link to the summary. if they're logged in, it'll auto download & we could optionally close the window after the download.

having a bunch of non-expiring tokens sit in a person's inbox seems like a bad idea (although it is convenient).

so, i'll go for option B
