### ISSUE TITLE
Agenda phase task card layout clipped

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2455]
During the Action meeting agenda, the layout doesn’t update when the task card sizing is updated. 

**Note**: Maybe related to #2432 

![screenshot 2018-10-23 10 36 21](https://user-images.githubusercontent.com/307286/47576923-4462e680-d90b-11e8-92af-f0ec29698a57.png)

#### Part 1
- Start an action meeting with two players (both have windows that allow for a row of 4 task cards across during Agenda)
- Advance to the agenda
- With P1, add a 1-line task (task card col 1)
- With P2, add a 1-line task (task card col 2)
- With P1, add a 4-line task and blur the card (task card col 3)
- Observe P2 has a clipped card (task card col 3)
#### Part 2 (continued)
- With P1, add a fourth 1-line task (task card col 4)
- With P1, go to the 1st and 2nd task cards and add a second line to each (task card cols 1, 2)
- With P2, go to the fourth card and add 3 more lines (task card col 4)
- Observe P2 has a card that is overlapping the add control (task card col 4)

### Acceptance Criteria
- Change in card height/sizing updates container layout

### Estimated Effort
- 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
@mattkrick okie dokie, this one is a fun game but the steps are reliable, and you should be able to observe both the card clipping by the container (part 1) and the card overlapping the add control (part 2). Once again (like #2432) it seems to be about which player is editing causing updates in layout but the other observing player doesn’t get the correct update in layout.

**Comment by jordanh** [comment]
Fixed along with #2432 in v2.19.0
