### ISSUE TITLE
Exclude private tasks from Retro CSV

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2456]
### Acceptance Criteria
- TBD Private tasks are excluded in the Retro CSV

### Estimated Effort
- 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
i've got no tension showing private tasks to the person who requested them, i think we should wait until we get a little backlash & can revisit then

**Comment by mattkrick** [comment]
keeping open, but removing from backlog since this is a discussion

**Comment by jordanh** [comment]
Scrubbed. Closing per icebox policy.
