### ISSUE TITLE
Meeting Project Updates empty state per team member

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#246]
## Enhancement

While in the context of a meeting, I want to see a helpful empty state (a prompt to carry on?) when a team members does not have projects so that I can have a better meeting flow.

![action-updates-empty-msg 2x](https://cloud.githubusercontent.com/assets/307286/19613947/d78c0c96-97b5-11e6-9bc4-91d011ed840d.png)

**Estimated effort:** 1 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
bumping this as a funnel improvement, @ackernaut feel free to deprioritize if running short on time for the epic

**Comment by ackernaut** [comment]
Deferring until we refactor the Meeting module to use Relay Modern.
