### ISSUE TITLE
change push to history.replace

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2461]
​

AC

- [ ] login page uses replace instead of push

​

effort

- [ ] 10.5 points

**Comment by jordanh** [comment]
@mattkrick could you add some criteria as to why this might be important? Does this have to do with the way we're emitting segment events? Something screwy with the router?

**Comment by jordanh** [comment]
Is this a bug or an enhancement?

**Comment by mattkrick** [comment]
oh dang, didn't see the convo here.
this is useful because it allows users to use the back button. if we push to the login page & they hit back, then it'll go back to the login page, which will then redirect them somewhere else & they'll never be able to hit back more than 1 time.
