### ISSUE TITLE
Finish demo implementation

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2462]
AC
- [x] What happens when somebody taps team name in sidebar (logged in or out) 
- [x] add an extra sleep to group phase in case they fast forward at the very end?
- [x] make "next" bounce when the bot is done
- [x] end meeting goes to create account

effort: 11 points

**Comment by ackernaut** [comment]
- Tapping team name or end meeting (pre-discuss) should go to `/me` when logged in or `/create-account` when logged out
- Tapping end meeting (during discuss) should go to demo summary

**Comment by ackernaut** [comment]
If you move on to the vote phase while one of the bots is dragging, it seems those cards get stuck over the vote phase view.
