### ISSUE TITLE
Group event can bork demo bots, forward progress

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2468]
I’ve been able to reproduce this consistently, in the demo:
1. Move from Reflect to Group
2. Quickly grab the top left card and drop it on the bottom middle card (when the grid layout is 3-col)
3. Note the cards that get stuck on bot DnD events
4. Cannot move to Vote, but you can group other cards or End Meeting
5. Refresh doesn’t seem to help

See [http://recordit.co/WhdJ31s7f6](http://recordit.co/WhdJ31s7f6)

See [https://sentry.io/parabol/action-staging/issues/748586159/](https://sentry.io/parabol/action-staging/issues/748586159/)

### Acceptance Criteria
- TBD a better way at not borking group events with bots

### Estimated Effort
- 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
@mattkrick what are your thoughts here? Do you think this is an edge case, should we ship or patch first?

**Comment by jordanh** [comment]
Good find! I say ship and follow on with a fix later this week
