### ISSUE TITLE
Demo task card mentions 😭

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2469]
Reproduction steps:
1. Go to demo
2. Advance to discuss phase
3. Try mentioning a user in a task card
4. View borks, hard refresh seems to clear it up

### Acceptance Criteria
- Users can mention bot users, or disable mentions

### Estimated Effort
- 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
oh that's good!
