### ISSUE TITLE
Color code reflections by question

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2472]
AC
- [ ] Each column should produce different colored reflections
- [ ] (optional) avoid the extra card height in certain areas by removing the reflection footer & solely relying on the color

Effort: 11 points

**Comment by jordanh** [comment]
This feels like a design issue to me. Suggesting:

## Acceptance criteria
- [ ] Each column should produce cards decorated in such a way that they are easy to see which column produced them at a glance
- [ ] (optional) avoid the extra card height in certain areas by removing the reflection footer & solely relying on the color

### Design uncertainty: 2

**Comment by jordanh** [comment]
Closing this as a duplicate of #2557 during scrub
