### ISSUE TITLE
migrate away from findDOMNode

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2474]
react 16.6 strict mode has deprecated findDOMNode. we'll need to do something to do the same to prepare for v17

AC
- [ ] findDOMNode is removed

effort: 11 points

**Comment by mattkrick** [comment]
this is gonna take a lot of work & some ugly hacks. i'm delaying it for now because i've got a feeling folks are going to be fighting this deprecation.

**Comment by mattkrick** [comment]
blocked on https://github.com/reactjs/rfcs/pull/97
some RFC will land in react before we need to move away from findDOMNode, we'll just have to wait until then

**Comment by jordanh** [comment]
Scrubbed, keeping open as its a pattern deprecation issue

**Comment by mattkrick** [comment]
fixed
