### ISSUE TITLE
migrate away from legacy context API

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2475]
react 16.6 strict mode has deprecated legacy context API. we'll need to do something to do the same to prepare for v17

AC
- [ ] legacy context API is removed

effort: 11 points

**Comment by jordanh** [comment]
This will affect our toast component...

**Comment by mattkrick** [comment]
true, stuck on #2360 #2327

**Comment by mattkrick** [comment]
stuck on react-redux because we need to sometimes access the store itself.
using v6.0.0-beta.2 will break redux-form
https://github.com/reduxjs/react-redux/issues/1083

**Comment by mattkrick** [comment]
stuck on #2172
