### ISSUE TITLE
bulk import of emails

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#2478]
## Issue - Enhancement

onboarding feedback from a Pro user (int'l agile consultant)

> I would also love to import emails in bulk. For our large team it was a real hassle to write them all one by one

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
We have bulk email invite capability, but it is inconsistent with the form under the Team Settings page. You can paste multiple emails when creating a new team or signing up via the wizard. We should make update the design of the form on the Team Settings page to be able to take multiple as well.

## Acceptance criteria:
A design that allows a user to:
   - enter 1 email address into the team settings box, press enter, and invite a user
   - enter more than 1 email addresses into the team settings box, press enter, and invite multiple
      - see validation errors

**Estimated effort**: 12 points

**Comment by jordanh** [comment]
Our new invite modal allows you to paste multiple. Closing...
