### ISSUE TITLE
Team, meeting support settings (start with check-in)

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2492]
### Acceptance Criteria
- [ ] Team, meeting architecture updated to support settings
- [ ] Backend settings support toggling on/off check-in round for each meeting type

### Depends on…
- TBD #2498 vote count UX
- TBD current list of first/next/target settings as expected per roadmap:
  - Per Meeting Type: check-in round on/off
  - Retro Meetings: allow guests to join meetings with passcode
  - All Meetings: require a facilitator role to lead meetings

### Estimated Effort
- 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Closing this issue in favor of more recent developments re: async retros
