### ISSUE TITLE
Updated toggle pattern in UI

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2494]
### Acceptance Criteria
- [ ] Toggle pattern styled to look like [latest concepts in Figma](https://www.figma.com/file/g7TeqDMSxMEx3QYcoQ5jYaxb?node-id=15%3A69&utm_campaign=team&utm_source=slack&utm_medium=message&utm_content=file_comment#2807608)

### Estimated Effort
- 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Scrubbed. Closing because this pattern is introduced in PR #2901 for the Slack refactor.
