### ISSUE TITLE
Vote count sans check-in round

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2498]
If we allow folks to disable the check-in round (see #2491 and #2492), how do we handle voting for participants?

**Some quick, under-baked ideas**:

- The total is team count times 5 and we let the smart humans in the room figure out that some votes belong to some people who are not online. Perhaps a snackbar message to the facilitator? “Total votes = 5 per teammate (even those who aren’t [connected or] participating online)”
- Each participant gets a control bar: “Tap [I’m Voting!] to get your votes” then “Tap [I’m Finished] when you’re ready to move on”
- [Add more ideas here or as a comment below…]

### Acceptance Criteria
- Issue discussed here
- Next step(s) created as issue(s)

### Estimated Effort
- 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
@mattkrick would like your ideas re: vote count sans check-in

**Comment by mattkrick** [comment]
i think the 2nd bullet is basically a manual version of a connectivity check.
the first bullet isn't very intuitive without extra text, so i'd like to avoid it.
i guess we have to use connectivity to check it. so the formula would be a summation of every team member: `'votesLeft * isConnected ? 1 : 0`.
if someone disconnects, that number will bounce, but i think that's a smaller price to pay than adding extra text or steps

**Comment by ackernaut** [comment]
Yeah, I agree with you. What happens if a person votes twice, then drops and regains connection? I assume their votes should persist, and then they have 3? Does the total account for votes that have already been placed?

**Comment by mattkrick** [comment]
mmm good point. it gets tricky because we don't release too much info.
if the vote count changes by 5 because i log out, then we know i have 5 votes left.
we may just have to give everyone their 5 votes, regardless of connection status.

**Comment by jordanh** [comment]
@ackernaut, @mattkrick, if we didn't drop this option it might look like:

1) Button shown "Start Voting", when click user receives 5 votes, total votes remaining incremented by 5
2) When user disconnects, votes removed
3) When user reconnects, "Start Voting" button shown again
4) Facilitator can advance to discuss at any point

What are the holes?

**Comment by ackernaut** [comment]
An alternative idea: we store votes as data by user. I guess this isn’t safe (aka preserves anonymity) if somebody is able to expose the data, but it could be safe if we never expose it in UI.

If a user is connected they can add votes, the meeting knows how many times they vote, when they reconnect their vote state is restored. No need for UI messages or controls. Safe to try?

Perhaps we dump the user vote data after the vote phase is completed? At that point the participants can’t vote anymore and the reflection groups should persist how many votes they received.

**Comment by mattkrick** [comment]
yeah, if per-user voting details are OK to make it to the client the problem becomes a lot easier. 
if we allow that, we can use connection status to determine total votes left.
otherwise, we'll need to say 5 votes * number of team members

**Comment by jordanh** [comment]
Closing in favor of #2808, where we'll handle this
