### ISSUE TITLE
CSV enhancements for consideration

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2503]
A few things to note about the current CSV export:

- It only shows reflections that were voted for.
**For consideration**: *show all reflections*
- It doesn’t show who owns each task.
**For consideration**: *add a column to show owners by preferred name*

### Acceptance Criteria
- Discussion completed
- Next step(s) identified, issue(s) captured/updated

### Estimated Effort
- 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
i say we revisit when we get 20+ teams requesting this

**Comment by jordanh** [comment]
Scrubbed. Iceboxing.
