### ISSUE TITLE
Refine demo summary

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2506]
feedback i've gotten about the demo summary:
- too many click aways
- not sure what the CTA does, how long it'll take (ie scary to click)
- too much distracting from the CTA

we should probably add a line that says something like "Invite your team, you'll be up & running in 30 seconds!" blah blah

effort: 10.5 points

**Comment by ackernaut** [comment]
I think that inviting the team may be a better CTA on the personal timeline, and the CTA here is still “Create a Free Account”

**Comment by jordanh** [comment]
Touched this during scrub. We need some criteria to resolve this discuss. I'd suggest what we need here is for this discussion to resolve into a new issue with AC and EE that would define a B of an A/B experiment and that this discussion urges us to quickly fix our ability to measure the demo funnel.

This design AC can be *really* abstract. All we need is an issue that can contain the work so it can be prioritized.
