### ISSUE TITLE
Agenda task card grid overlap

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2514]
![screenshot 2018-11-27 11 29 29](https://user-images.githubusercontent.com/307286/49115279-05a0b300-f260-11e8-8687-a5ab7ead1012.png)

### Reproduction Steps
- Exact steps are currently unknown, but this involves a user observing the agenda view when others are adding and editing tasks cards. It may be that a user edited a card that already existed and then the card increased in height after the edit was made.

### Acceptance Criteria
- No overlap in grid

### Estimated Effort
- 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Scrubbed. Iceboxing per policy.

**Comment by jordanh** [comment]
See also issue: #2895
