### ISSUE TITLE
Handle accidental retro phase advance/ phase completion communication

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2516]
## Issue - Enhancement

A new facilitator will occasionally hit the "Next" button by accident—either they think they _should_ hit the button as quickly as possible (because its enabled/bouncing)—or they think everybody is done with an activity prematurely.

Additionally, when the facilitator has navigated past a phase and a teammate travels back to a phase, they want to see some indication that the phase is complete and cannot be edited (e.g. no more cards can be added to the group, no more votes will be tallied, etc.), so that they are not frustrated that the controls no longer respond.

This is a discussion issue. It'll resolve when we reach a decision on acceptance criteria.

### Acceptance Criteria (optional)
Facilitators:
   - see the "Next" button in the disabled state until the following happens during each retro phase:
      - Reflect: at least one reflection is entered
      - Group: at least one group is created
      - Vote: all votes have been cast
      - Discuss: ("Next" is always enabled)
   - see the "Next" button bounce when:
      - Reflect: 120 seconds after all categories have at least 1 reflection
      - Group: 300 seconds has elapsed
      - Group: 0 votes remain
      - Discuss: 300 seconds after the Facilitator navigates to the PhaseItem
   - can still click on the disabled "Next" item, but receive a confirmation modal with a helpful message:
      - Reflect: Not all prompts have a reflection. Are you sure you want to move on?
      - Group: Your team hasn't grouped any cards yet! Are you sure you want to move on?
      - Vote: Everyone hasn't cast all their votes! Are you sure you want to move on?
      - Discuss: n/a

When any user navigates back to a completed phase item:
   - They see a helpful message informing them the phase has been completed, and the input cannout be changed

- **Estimated effort:** 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
i think this is necessary, but i'd really like to do it without words/modals if at all possible because i think words just excuse a poor UI.
it sounds like facilitators only screw up when they see a bounce, so let's just focus on making that bounce smarter.

- the logic is deterministic for the vote phase (0 votes) so that's easy
- for the group phase it'll have to be a heuristic & i think we can do better than a 5 minute delay. maybe no drag activity for 30 seconds after the first minute has passed. (earliest it can start bouncing is 90 seconds)
- for the reflect phase, i think it's all too common that they leave a column empty. instead it should only bounce if no one is editing after a 2 minute grace period

The current logic we use to see if someone is "editing" is 
  - on focus, set editing to true
  - on blur, if there is no text present, set focus to false, else, set focus to false after 5 seconds

this doesn't catch the case where they stay focused in the input, but aren't typing.
so, i'd propose the following:
- on focus, set editing to true. (ready to type the next) 
- if no keypress occurs for 5 seconds on an empty input, set editing to false (they typed their last & are done)
- if no keypress occurs for 10 seconds on an input with something in it, set editing to false (they're thinking)
- on keypress, if editing is false, set it to true
- on blur, if input is empty, set editing to false (they're done)
- on blur, if input is not empty wait 10 seconds then set editing to false (they're looking something up/multitasking)

**Comment by ackernaut** [comment]
I like @mattkrick ’s idea as an iterative improvement on nudging forward movement. As for orienting folks when they are in a completed phase, I think we could probably do better there, too. I’m wondering if there is some subtle styling that we could do, like replacing the number with a check in the left nav, and/or adding that same check to the heading (top left of main view). And perhaps some sort of feedback on the controls when there is an attempt to use like a tooltip (“Voting is completed.”)

**Comment by mattkrick** [comment]
yeah, it'd be great if there were a "Completed" icon on the left nav. it'd also be neat to just grayscale the whole content section.

**Comment by ackernaut** [comment]
Yeah, there are probably some nice states we can add to a phase once it’s passed without having to re-invent them too much or add too much verbiage.

**Comment by ackernaut** [comment]
Here’s a list of ideas/candidates:
- Create an implementation issue for Matt’s ideas on voting and input heuristics [above](https://github.com/ParabolInc/action/issues/2516#issuecomment-443802875)
- Iterate on the left nav to show that past phases are completed (explore using color, icons, etc. [see Figma](https://www.figma.com/file/0lOTlvsj87GBFFzgee9OkVWi?node-id=12%3A490&utm_campaign=team&utm_source=slack&utm_medium=message&utm_content=file_comment#3943401))
- Explore using the header to indicate that a phase is completed. We could give the simple tip the first time the phase is being completed, then say that the phase is completed when folks navigate back, [see Figma](https://www.figma.com/file/0lOTlvsj87GBFFzgee9OkVWi?node-id=12%3A490&utm_campaign=team&utm_source=slack&utm_medium=message&utm_content=file_comment#3943410).
- Create a separate design issue to explore having a list of teammates where you can see connection state and participation. Folks could indicate that they’re ready to move on etc. [see Figma](https://www.figma.com/file/0lOTlvsj87GBFFzgee9OkVWi?node-id=3%3A0&utm_campaign=team&utm_source=slack&utm_medium=message&utm_content=file_comment#3943397)
- Do another audit on phase controls. We disable inputs for reflection and pop a toast for voting when those phases are completed. We could do additional work to make those phases more of a read-only state.
- In the future we reconsider our opinions/assumptions on making completed phases read-only versus allowing folks to go back and edit, fix groups, etc.

**Comment by mattkrick** [comment]
@jordanh i'll turn the top bullet into an implementation issue, need your feedback on the other bullets

**Comment by mattkrick** [comment]
@jordanh need your input on the latter bullets

**Comment by jordanh** [comment]
On:
> * Iterate on the left nav to show that past phases are completed (explore using color, icons, etc. [see Figma](https://www.figma.com/file/0lOTlvsj87GBFFzgee9OkVWi?node-id=12%3A490&utm_campaign=team&utm_source=slack&utm_medium=message&utm_content=file_comment#3943401))
> * Explore using the header to indicate that a phase is completed. We could give the simple tip the first time the phase is being completed, then say that the phase is completed when folks navigate back, [see Figma](https://www.figma.com/file/0lOTlvsj87GBFFzgee9OkVWi?node-id=12%3A490&utm_campaign=team&utm_source=slack&utm_medium=message&utm_content=file_comment#3943410).

@ackernaut I left a comment on the design re: color. Other than that, I think it carries us forward. Could you create an implementation issue?

On:

> * Create a separate design issue to explore having a list of teammates where you can see connection state and participation. Folks could indicate that they’re ready to move on etc. [see Figma](https://www.figma.com/file/0lOTlvsj87GBFFzgee9OkVWi?node-id=3%3A0&utm_campaign=team&utm_source=slack&utm_medium=message&utm_content=file_comment#3943397)

Whoa. Cool direction here! This looks like we're getting ready for mobile. @ackernaut, can you create a separate design issue (as you suggested)

After these are done I think we can close this issue

**Comment by jordanh** [comment]
Comment on this: 

> * In the future we reconsider our opinions/assumptions on making completed phases read-only versus allowing folks to go back and edit, fix groups, etc.

As a general strategy, for future designs/implementations I think we should default to being more permissive and start locking stuff down only when we get feedback the freedom is getting in the way. For now, I'm going to wait for us to get more feedback that folks want to go back. When next we hear it I'll open an issue. If we hear it a bunch, we'll do something
