### ISSUE TITLE
App layout / IA updates explored

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2519]
It seems more and more evident that we are outgrowing our current app interface. We need to accommodate new spaces like timeline, users may benefit from more standard UI patterns, and we have better ideas these days on how to support mobile in minimal, usable ways. We also need layout/IA patterns that support a target implementation of having other sub-spaces like a team handbook, or an organization chart, in the future.

### Acceptance Criteria
- Pen and paper sketches and mid-fi concepts that show the visual orientation and hierarchy of:
  - Global user controls (menu, notifications)
  - Collapsible primary nav menu
  - Responsive timeline space and header/controls
  - Responsive kanban space and header/controls
  - Responsive setting spaces and header/controls
  - Basic app messages (meeting alerts, snackbars/toasts, modals)
  - Examples of mobile friendly affordances

This effort is scoped to all views (timeline, kanban, settings) outside of the meeting views.

### Estimated Effort
- 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Super-ceded by other issues, iceboxing as per policy
