### ISSUE TITLE
wordsmith timeline events

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2522]
we need some fancy words for timeline events.

AC words for each of the following:
- [ ] Joined parabol
- [ ] created first team
- [ ] created team
- [ ] completed action meeting
- [ ] completed retro meeting
- [ ] Invite team Suggested Action
- [ ] host retro Suggested Action
- [ ] new timeline feature broadcast

effort: 11 points

**Comment by jordanh** [comment]
See #2419 

Work this list as part of that issue.
