### ISSUE TITLE
Try removing attached pictures from email

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2527]
The green download cloud doesn't show up as a pic to download. Maybe we can do that for the other icons? Let's investigate

AC
- [ ] try to remove attached icons

Effort 10.5

**Comment by jordanh** [comment]
From the scrub, @ackernaut says:

> When a user receives an email from Parabol, some of the images show up as attachments at the end of the email. More research needs to be done in order to figure out why this is the case

Updated Acceptance Criteria:

- [ ] diagnosed why some images show up as attachments at end of email, while others do not
- [ ] if possible, make it so all of our emails no longer have their images added as attachments

Estimated Effort: 11 points

**Comment by ackernaut** [comment]
Use inline images with `Content-Type: multipart/related`? [SO](https://stackoverflow.com/questions/30351465/html-email-with-inline-attachments-and-non-inline-attachments)
