### ISSUE TITLE
Hotfix snapshot id of undefined mid meeting reflect phase

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2528]

**Comment by jordanh** [comment]
From the scrub, @mattkrick says:

> This has to do with a difficult to reproduce drag and drop bug. It is still valid.
>
> Folks see it when they are deleting reflections during the Reflect phase.

Will add details if/when we reproduce.

**Comment by jordanh** [comment]
AC:
  - Triage to root cause (possible opening new issue), fix if less than EE

EE: 11 points

**Comment by jordanh** [comment]
This one may be impossible to do anything with without clear reproduction steps
