### ISSUE TITLE
auth0 token tms out of sync with rethinkdb

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#253]
## Issue - Bug

I noticed a some empty teams after I freshly reset my local development database:

![image](https://cloud.githubusercontent.com/assets/103000/18037341/347a2eba-6d4f-11e6-8beb-207acf8b7488.png)

After thinking and poking, it's because the `tms` meta-field from my development account on auth0 has a bunch of ids that no longer exist in my rethinkdb.

I'm not sure what the best option for fixing this is. However, perhaps a starting place is to:
1. Find all the places where we update the `tms` field on auth0
2. Ensure that those queries are building the `tms` list from a database query, rather than a simple append of the `tms` array
- **OS:** OSX
- **Browser:** Chrome
- **Node version:** v6.2.0
- **NPM version:** 3.8.9
- **RethinkDB version:** rethinkdb 2.3.4 (CLANG 7.3.0 (clang-703.0.31))
- **Estimated effort:** 2 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
This can be remedied by wiping all but parabol & engineering from auth0.
Assuming that auth0 is sometimes unreachable, there is the possibility that this will get out of sync. In that case, every time we log in, we should pull in an array of teams, see if it matches the token, and if not, update auth0 & sign a new token.

**Comment by jordanh** [comment]
Hmm. Yeah, that'd be a solid approach. So we'd need to change/rename the `updateUserWithAuthToken` mutation.

What should we call that thing? `synchronizeAuthProfile`?

**Comment by mattkrick** [comment]
sure, although it'd be small enough that we could still keep it inside. It'll basically be a little conditional.

**Comment by mattkrick** [comment]
@jordanh i think we solved this one awhile back. we made if so our DB is the single source of truth, but that truth is replicated onto auth0 & the client token. But, on a login (for auth0) or websocket connection (for JWT) we make sure that everything agrees. if it doesn't then we propagate what we got from the DB. Closing cuz i think we nailed it, feel free to reopen if i'm wrong.
