### ISSUE TITLE
TypeError: Cannot read property 'left' of undefined

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2531]
https://sentry.io/parabol/action-production/issues/795850112/?referrer=github_plugin

```
TypeError: Cannot read property 'left' of undefined
  at Ra (/production/build/v2.21.0/RetroRoot_2040295f652f3a89d8a0.js:35:388199)
  at HTMLDocument.setViewerDragState.e (/production/build/v2.21.0/RetroRoot_2040295f652f3a89d8a0.js:35:390772)
  at HTMLDocument.o (/production/build/v2.21.0/vendors~app_d23bdd7eac882e5f763a.js:106:8869)
```

**Comment by jordanh** [comment]
Looks to be coming from [handleDropOnGrid.js#L26](https://github.com/ParabolInc/action/blob/15585e87490472ea7246e9e7a502b5640bc462c5/src/universal/utils/multiplayerMasonry/handleDropOnGrid.js#L26). Probably racy.

@mattkrick if an exception like this happens during Group, what happens? Does it mess up their experience in any way?

**Comment by mattkrick** [comment]
you know, i'm just not sure, i've never had it happen to me. i'd assume it would, but the race could happen during an unmounting, which is pretty common among other errors like this

**Comment by jordanh** [comment]
AC:
   - Root cause determined, fixed or new issue created

EE: 12 points

**Comment by jordanh** [comment]
Scrubbed, iceboxing for now
