### ISSUE TITLE
"You are disconnected and checked in"

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2533]
## Issue - Bug

User reported during retro highlighting their avatar told them `You are disconnected and checked in` even though their light was green. This looks like a typo/state rendering bug

See the following screencap from the user:

![image](https://user-images.githubusercontent.com/103000/49691230-516e1a80-faf2-11e8-881d-90a6b4cad597.png)

- **OS:** macOS
- **Browser:** Chrome
- **Estimated effort:** 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### Acceptance Criteria (optional)
Users can:
   - Copy should read `You are connected and checked in` when their connection status is green

**Comment by mattkrick** [comment]
closing in favor of #2555
