### ISSUE TITLE
Expand text in summary emails

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2534]
## Issue - Enhancement

User `google-oauth2|113969018707632982220` reported:

> Parabol would be even better if the Email with the Meeting Summary would not contain abbreviated (truncated) cards, but if it would contain the full text.

Opening this as a discussion to track and see if this tension is carried by other users.

**Comment by jordanh** [comment]
Note: this feedback came in after we added the ellipses expansion feature to the web summary

**Comment by tayamueller** [comment]
> I'm happy to explain a bit more about this particular situation. [We] have a lot of dynamic teams and sometimes we do a system-wide retro around a specific subject. So when the meeting started, [a team lead] created a team on-the-spot, to do a retro together with people that showed up in the meeting (ie not everyone). Then, he forwarded the outcome email of the meeting to others (including me), for a broader awareness for the people that weren’t there. Since I wasn’t part of the original team that he created, I can’t access the web data.

**Comment by jordanh** [comment]
@mattkrick made a decision recently and decided to make this the way it is. We can close it.
