### ISSUE TITLE
Remove old invitation flows from UI

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2538]
AC
- [x] nuke the entirety of the team settings invites. team members are seen in avatar format. resending invites are handled by just re-inviting. kick from team instead of cancel invite. no org approvals.
- [x] remove soft team members flow from list
- [x] add a menu to avatars on the team view
- [x] menu has promote/remove options for the team lead

Effort: 11 points

**Comment by mattkrick** [comment]
Do we need to show invitees in the list of team members?
- I say no. visually, it takes up a lot of space & we'd have to have the visual affordance to make them look different.

So how does the invite flow work?
- You type in an email address, an invitation is sent to that person. if they're on parabol, they also get a notification. that's it. you type in their email again, they get another one. if they activate the token in either email, they're in.
- there's no reactivation. if you got kicked out, you get back in the same way as everyone else
- there's no org approval or status for that
- there's no resend for expired invites. if someone hits an expired invite, they they'll probably ask you for a new one

**Comment by ackernaut** [comment]
I think this makes sense, so:
1) Folks can be invited multiple times
2) Automatically approved
3) Expired invites prompt out-of-band behavior
4) We show 1 avatar for every team member that has accepted an invite

How do we remove somebody? We still have the same list in team settings, sans invite field and pending invite rows? Just checking that I follow correctly. @mattkrick

**Comment by mattkrick** [comment]
we'll just have "promote" and "remove" be menu items for the avatars

**Comment by ackernaut** [comment]
Oh, I like that, we can use the user avatar menu and scrap that user row panel altogether!

**Comment by ackernaut** [comment]
I’m wondering if in the meantime we remove “Team” and “Integrations” tabs under Team Settings and just stack the integrations panel above the “Danger Zone” panel. If users go to the settings view they will only see integrations, and the delete team panel if they are the team lead. At some point we can revisit #2491 .

**Comment by ackernaut** [comment]
@mattkrick as of now, it takes a click to see who the team lead is. Who actually knows this is a thing and who cares to go looking? I’m not sure. Anybody can invite. We are doing away with approvals. I suspect that most of the time the Team Lead doesn’t even realize they have the role.

I think it’s safe to kick the can down the road and stick it in the menu for now. Perhaps every menu could have a header:

PreferredName
[Team Role] where `isTeamLead ? 'Team Lead' : 'Team Member'

And then the horizontal separator, and the actionable menu items.

Another option may be to have a tooltip on hover that shows: PreferredName • [Team Role]

Later on, as the avatar group matures, perhaps we solve a quick way to see this info. I think other demands on the meeting (how to show I’m done, etc.) will make us iterate on how to progressively show info about team members and meeting participants, and these patterns can probably inform each other.

**Comment by tayamueller** [comment]
I've been thinking abt the Facilitator marker; the symbolism of a crown has been bugging me. Facilitators aren't rulers, and they aren't permanent.

How about a bowler hat? Design advantage of being a black & easily identifiable shape that fits nicely on top of a curved avatar. Good associations for a huge spectrum of folks: Charlie Chaplin, Clockwork Orange, Churchill, Annie Hall, Boy George, rural South American women...and especially Mr Potato Head--he's (the only one?) in every Toy Story movie, including TS4 coming out this year.

Also: hat tip / tip o' the hat = acknowledgement/gratitude/welcome (to pass the Role?)

Also: cute.

**Comment by ackernaut** [comment]
Yeah, I agree with the crown symbolism.

I like the bowler hat idea a lot.

What I struggle with is having an icon big enough so that the characteristics of the hat (or any other icon) is easily understood. I say this because we are starting to look at advanced interactions with the avatars, and considering mobile patterns, etc. I do think that an icon can be explained once the avatar is tapped or hovered, either by an informative tooltip or a header to the menu.

**Comment by jordanh** [comment]
See PR #2556
