### ISSUE TITLE
Design invite-specific signup/login pages

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2539]
Acceptance criteria
- [x] /token-expired/:tokenId page exists saying something like "Your token to Team StrikeForce has expired! please request a new token from John at john@teamstrikeforce.co
- [x] /login/google page exists saying something like "Welcome back John! You last signed in using google. Click login below for immediate access to Team Strikeforce. If you'd rather login with your own email & password, click here
- [x] /login/email page exists with email address prepopulated. & the password field autofocused. forget your password is down below.
- [x] /signup/google is exactly the same as above, but we just say Sign Up instead of login
- [x] /signup/email is exactly the same as login/email, but instead of forget your password it says "already have an account? login which redirects to the /login page"
- [x] /login has both Oauth & email/pass options
- [x] /signup has both Oauth & email/pass options

Effort: 12 points

**Comment by mattkrick** [comment]
Error handling
- [ ] if token was already accepted, then we assume they are already part of that team. that means they are going to want to log in. follow the login flow, but don't send the token to the server & instead offer an error message at the top
- [ ] if token expired, there's nothing we can do. show an expired token page & offer a team name & an email address to re-request access
- [ ] if the token was not found, simply tell them it's not found

security:
- a token gives you access to a user & the team. this is fine because in a second they'll have that info anyways.
- it's not fine for an expired token to have access to a user/team in case email got compromised

**Comment by mattkrick** [comment]
fallbacks
- the login views do not have fallbacks. if someone sent an invite to them & they have an account with us, there's no need to ask them if they'd like to log in a different way.
- the google signup view can have a fallback just in case they don't want to associate their google account with us
- the email signup view doesn't need a fallback because we're sure they can't use oauth. note-- this  means i can't log in via oauth with an email that you did not invite me with. that's an edge case i'm willing to accept

**Comment by mattkrick** [comment]
just wrapped up the logic, these designs are now blocking #2550

**Comment by ackernaut** [comment]
Here’s the [set of concepts in Figma](https://www.figma.com/file/PRfpcwnC2fu8UIwa96Fm3sHO/Auth-View-Concepts?node-id=0%3A1).

**Notes**:
- These views should look consistent across all cases
- The views can be dropped in a card on a generic, blank auth page for now
- The views an be dropped in a modal over a specific context later

**Moving to review state**:
- We can tweak copy, spacing, add/yank elements

**Next steps**:
- We’re actively adding the new views that support team invite updates #2550 
- We can update the existing, default auth views (Create Account, Sign In, Forgot Password) to match the latest styles in a separate PR

**Comment by mattkrick** [comment]
design complete!
