### ISSUE TITLE
"Add user" avatar

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2540]
AC
A set of Figma designs where a user can:
- [ ] In the list of team members, an additional avatar exists with a big +
- [ ] Clicking it opens up an invite modal. The modal has a text area that allows you to add 1+ email addresses & a big invite button
- [ ] (OUT OF SCOPE) below the text area, there is url that can be copied that lets anyone on the team if they have that url. we won't do this right now, but let's plan on the visual affordance
- [ ] remove add user from team invite form
- [ ] a set of implementation issues

Effort 12

**Comment by jordanh** [comment]
Design uncertainty: 2

**Comment by mattkrick** [comment]
design complete!
