### ISSUE TITLE
Start Meeting UX conflicts

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2546]
### From a Pro user:

>Someone accidentally started a tactical meeting after we started the retro. A little annoying because it overrode the retro and we had to go through the check-ins and the updates of the tactical to end it and get back to the retro.

>I had started the Retro meeting, and went through check-ins. And then it wouldn't let me move the meeting forward. When I refreshed it took me to the start Retro page but wouldn't let me click to start the meeting. Then we figured out that someone accidentally started a Tactical meeting when they joined late.

>I think they were just confused and trying to join the meeting.

>One thought: it would be great if it were easier to end a tactical meeting if you accidentally open it.

### Acceptance Criteria
- Discussed possible problems and solutions around conflicts in starting meetings and identified next steps (probably a UX design solution—at a minimal, behavior and perhaps some UI feedback—that needs to be implemented)

### Estimated Effort
- 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
It is possible for members of the same team (or the same user in different tabs) to be in both the Retro and Action lobbies at the same time. Starting one meeting causes conflicts when trying to start the other. One possible story I assume is that folks used the “Start Meeting” menu from the Team Dashboard and one user accidentally started the wrong meeting.

I wonder if we have to disable the start control in one meeting lobby when the other type has been started with some messaging for the user.

Also, currently the Action meeting only has an “End Meeting” control during the Agenda and Last Call views. We didn’t add that control in the earlier phases because most UI changes have been deprecated in the old meeting views because we want to refactor the Action meeting to use the new meeting views.

**Comment by jordanh** [comment]
Scrubbed. Iceboxed.
