### ISSUE TITLE
In-app tier upgrade CTAs

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2547]
How do we want to call out the Pro and Enterprise tiers in the Organization Billing and Upgrade Modal views? Also, we have a CTA in the User Menu and the Organization List. I think at a minimal folks should know how to upgrade to Pro or Enterprise in the app without having to maintain duplicate content about the tiers.

**Note**: on the latest Enterprise branch [I made copy changes](https://github.com/ParabolInc/action/pull/2545/commits/c67e70d297a8b34a0b3a1ff08c849c82e6293037) to the Upgrade Modal to reflect our latest Pricing draft.

![screenshot 2018-12-13 12 06 28](https://user-images.githubusercontent.com/307286/49958180-a7b2d300-fecf-11e8-8e71-76cd98cbb576.png)
![screenshot 2018-12-13 12 06 40](https://user-images.githubusercontent.com/307286/49958181-a7b2d300-fecf-11e8-982d-707eca8c0512.png)
![screenshot 2018-12-13 12 06 50](https://user-images.githubusercontent.com/307286/49958182-a7b2d300-fecf-11e8-9413-29850a21b20f.png)
![screenshot 2018-12-13 12 06 57](https://user-images.githubusercontent.com/307286/49958184-a84b6980-fecf-11e8-9e31-4934d4b5e3a3.png)

### Acceptance Criteria
- Discussed content strategy and decided on next steps…

### Estimated Effort
- 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Thank you for bringing this up @ackernaut. Your attention to detail is much appreciated!

I'm thinking for now we could get away by adding "[Want enterprise tier instead?](https://parabol.co/pricing)" beneath certain key CTAs. Most of our enterprise conversions I don't anticipate will be bottom-up adopted.

What do you think?

**Comment by ackernaut** [comment]
Agreed it can be minimal per strategy and the direction of adoption.

**Comment by ackernaut** [comment]
I think we can close the discussion. Tension is low and attention needs to be on other problems.
