### ISSUE TITLE
In-Person & Blended Remote/Non-Remote Meetings

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#2549]
feedback from [this CTO](https://app.hubspot.com/contacts/3888472/contact/902601) of this [31-person Pro Org](https://app.hubspot.com/contacts/3888472/contacts/list/view/all/?query=%40ax-semantics.com):

> During experimenting with different formats for the action meeting (because we are mixing remote and non-remote standups), we wanted to use only 1 PC for the non-remotes, that means that the action meeting happens on a beamer/wall setup with an interactive whiteboard, but we cannot add cards for the other accounts while we are in an action meeting. would there be a way to do that? (Same problem for users who don't have a laptop but want to join

**Comment by jordanh** [comment]
Scrubbed. Iceboxing.
