### ISSUE TITLE
Agenda & Agenda Processing sprint part 2

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#255]
## Issue - Enhancement

Following #149, here is part deux of the agenda processing sprint:

- [x] Agenda Item view has an initial state with LTR `CreateCard` components.
- [x] Agenda Item view can navigate to next item (forward progress!).
- [x] Agenda Item view can handle `OutcomeCard` interactions in various states.
- [x] Last-call view can show current total of processed Agenda Items, Projects captured and Actions captured.
- [x] Last-call view has an “End Meeting” button. In this sprint we will only lay out the button. Implementation of ending a meeting will start in a Summary sprint.

- **Estimated effort:** 3 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
>  Agenda Item view can handle OutcomeCard interactions in various states.

Let's discuss styles.

Instead, I'd like to see a card that's updated on a per-keystroke.
When someone creates a new card, it looks like a `NullCard`, but updates per keystroke instead of per blur.

I'll hold off on wiring it up until we merge the card styles into this @ackernaut.
