### ISSUE TITLE
When is my team ready to move on? 

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#2552]
submitted by [this user](https://app.hubspot.com/contacts/3888472/contact/1964701) from this [26-person Personal team](https://app.hubspot.com/contacts/3888472/contacts/list/view/all/?query=%40digi.com)

> Voting number seems arbitrary and being able to communicate that team members are all done voting would be nice. Being able to state that you are done with a particular stage (knowing that all participants are done), and then show many outstanding members are not done with any particular stage.

**Comment by jordanh** [comment]
Voting number probably deserves its own discussion issue to track user feedback. Knowing when to move on was recently enhanced so the thing bounces when folks are ready.

Iceboxing.
