### ISSUE TITLE
Less friction when forming teams within organizations

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2558]
From [a Scrum Master](https://app.hubspot.com/contacts/3888472/contact/1885451) of a [15-person Pro team](https://app.hubspot.com/contacts/3888472/contacts/list/view/all/?query=%40reachmee.com):

>It would also be nice to be able to form virtual teams within an organization without everyone having to get an email invite again. For example we have two dev teams, and today when I wanted to do a joint retro I had to create a new team and add everyone’s email addresses again.

### AC (solution candidates)
- Autosuggest org members (like the @mention in a task card) in the team invite field. Field can handle a mix of org users and new emails at the same time.
- Option to invite another team or teams to a retro (probably one-time, meeting gets its own URL and lobby until the meeting is completed)
- Option to form a team by merging other teams or branching off of an existing team (not sure about this idea, needs a lot of exploration)
- Discuss IA of team of teams, and probably deprecates the organization object (per MK)
- Another idea

### EE 10.5

**Comment by ackernaut** [comment]
@mattkrick here’s the user feedback ala team of teams

**Comment by mattkrick** [comment]
from the feedback, i don't think having a team is the problem, it's creating it.
magic invite url fixes this. as will pull invites (pop a toast when a rando hits your team page & ask you to allow them)

**Comment by jordanh** [comment]
Scrubbed. Iceboxing. Mass invite took away a lot of user tension here, I think
