### ISSUE TITLE
UX for identifying/compiling team wins in/from retrospectives

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2559]
​How might we surface team wins from retro data when there may be natural behaviors from the team in the retrospective of acknowledging success, hitting goals, etc.?

### AC
- Design uncertainty 3
  - Needs problem exploration, show research, notes, possible definitions
  - Needs a list of candidate solutions
  - Some lo-fi sketches on paper of ideas when helpful
### EE
- 11 points

**Comment by jordanh** [comment]
This needs some AC before it can be added back to the Sprint board

**Comment by jordanh** [comment]
Scrubbed. Iceboxing for now. (Bring it back at S.P.A!)
