### ISSUE TITLE
Multiple and customizable columns, multiple spaces

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2563]
## Issue - Enhancement

[User](https://app.hubspot.com/contacts/3888472/contact/2692?interaction=note):

> **What I am missing or what I would like to see improved in the software offering**
> I am missing customizability of a lot of features. Example: Even for most basic taskboards I want other columns than the columns you offer.
> ...

**Comment by jordanh** [comment]
Some thoughts for discussion:

The future of Parabol is working with data that lives in other software. Being able to present and summarize data across systems is valuable. To supports this, let me introduce the concept of a "space":

![spaces_1](https://user-images.githubusercontent.com/103000/50811200-3560c300-12c2-11e9-9f08-d4f45a8fe272.jpg)

Spaces are a place for teams to keep additional task data—either Parabol native tasks or data from synchronized with other apps.

When a user limits their task board to a single team, they can also filter by a space. In the below example, a user has filtered their task board by tasks belonging to the `Product` team and tasks from (1) all spaces:

![spaces_2](https://user-images.githubusercontent.com/103000/50811625-1fec9880-12c4-11e9-8d5f-15f3b68289b4.jpg)

(2) Column headers are replaced instead by "summarization label ribbons." These ribbons allow for the common summarization of tasks across multiple systems. It will be demonstrated how they work with a specific integration in the next example. (3) Cards have been extended to display the their space of origin. (4) The `+` control to add a new card has been removed from the column header, and instead a region is provided that displays a control to create a new card when hovered. This same control is provided when a user hovers between cards (not shown).

In the next example, when the `Product` team is filtered by the (1) `Action GitHub` space:

![spaces_3](https://user-images.githubusercontent.com/103000/50811868-321b0680-12c5-11e9-9046-f77d2b8a922b.jpg)

(2) The ribbons extend over multiple columns. If a user wishes the collapse a ribbon, they can do so by clicking on it. Comparing the `Backlog` column of this example to the previous example one can see how the ribbons summarize data across the `Backlog` and `To do` columns. If a user wishes to adda new column, they (3) hit the `+` control provided below and at the extreme right of the ribbon.

Were we to explore this concept a bit further, I don't believe we'd start by implementing spaces & integrations. Rather, I believe we'd provide users with the ability to have multiple Parabol task boards per team and customize the columns for each space. From there I expect we'd have much of the information architecture we'd need to synchronize with other Kanban systems.

Thoughts?

**Comment by tayamueller** [comment]
see #212

**Comment by mattkrick** [comment]
Value add: visibility across platforms
challenges:
- avoid making users classify tasks
- filter out low-priority tasks
- allow user-defined classifications
- hierarchies are not user friendly
- users don't want to leave their tools of choice

proposed solution:
- for user-defined classifications
  - remove status, make it a user-defined tag
  - e.g. "new feature blog #backlog #todo"
  - assumption: the fact that todo is a child of backlog is relatively unimportant to the user
 
- filter
  - track diffs & report on those in a timeline
  - a timeline filters & prioritizes events that are important to the user. it servers this purpose pretty well

**Comment by jordanh** [comment]
Scrubbed. Iceboxing.
