### ISSUE TITLE
Reflection card has inline group affordance

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2567]
When users have a large batch of cards to group and they want to quickly add a card to an existing group when scrolled far, far away, they have a convenient affordance on the card itself to allow for this.

### Acceptance Criteria
- [ ] Concepts shown in mid- to hi- fidelity that illustrate card controls and affordances that allow for quick grouping especially when navigating a large grid of cards
- [ ] A clickable prototype that can be tested both internally and externally
- [ ] Created a next-step implementation issue with the outcome from this design effort

### Estimated effort
- 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Scrubbed. Iceboxing for now
