### ISSUE TITLE
Improve card states when no content/textarea value

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#257]
UI Enhancement

Currently, cards only display in “editing” state when a user blurs on the card content textarea and there is no value. If the text field is not being used we should not show editing state, allowing others to add content to the textarea.

**Estimated effort:** 1 point ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

![screenshot 2016-09-07 11 37 04](https://cloud.githubusercontent.com/assets/307286/18325587/853d7fc2-7507-11e6-92b6-0c2054ac0721.png)

**Comment by mattkrick** [comment]
Can you explain this a bit more? I'm not quite sure I understand. You want the `NullCard` to go away if someone starts to create a new card but abandons it?

**Comment by ackernaut** [comment]
@mattkrick yeah, basically I should at least state the problem and am not 100% sure on the solution. Basically if a person backs out of a card, it can remain, indefinitely. So another person will see @person is adding a project when in fact that @person may just be ignoring a card in a column and have gone to another place in the app. The card has an empty textarea. Could we check for cards with an empty text area and no focus? Do we put a timer on it? If another person sees that card with the placeholder text, they probably will not know the intention of the person who created the card, unless they had some conversation (in Slack, on a Hangout, in person).

**Comment by ackernaut** [comment]
Meaning if we dropped the “adding” message and allowed the card to remain for all to see, sans content.

**Comment by mattkrick** [comment]
how can we delete cards? not archive, but delete.
For example, i'm in a meeting agenda item, i make an action, realize it's stupid & want to delete it.

however we do that should also answer this question.

**Comment by ackernaut** [comment]
I added a button, on my side branch, in the inset menu to delete action cards.

**Comment by ackernaut** [comment]
It’s not my favorite design, but was just one step closer for alpha.

**Comment by mattkrick** [comment]
a `NullCard` that is abandoned (blurred) should be _deleted_ not archived.
Additionally, we should treat `null` and `''` equally, so if someone wants to delete something, they remove the text & blur the box & it goes away.
