### ISSUE TITLE
Intermittent bug when leaving a team

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2571]
Sometimes tapping “Leave Team” from the avatar menu doesn’t work. Here are the best details we have so far:
- It seems to happen when accepting an invite to a team and then trying to leave in a single session
- There are no apparent logs in the server or client consoles locally, or client logs in production
- The problem seems to go away after a hard refresh
- We feel this is an edge case since folks probably don’t join and leave a team in a single session (and more of a test case when quickly testing the functionality in a staging or dev environment)

### Acceptance Criteria
- Diagnose
- Fix if within effort, or update issue

### Estimated Effort
- 10.5 points

**Comment by ackernaut** [comment]
I did test quickly to see if any simple mouse click events were being blocked by some silly DOM issue (capture/bubble, pointer events, etc.) but didn’t spend a lot of time on it.

**Comment by jordanh** [comment]
Scrubbed. Iceboxing for now.
