### ISSUE TITLE
Design loading timeline mock 

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2579]
While the timeline is loading, we need to show a loading indicator

most timelines show a list of mock events & instead of text they just have gray bars that are kinda like indeterminate progress bars.

AC
- [ ] a TimelineEventMock is designed & accepted in figma

effort: 11 points

**Comment by ackernaut** [comment]
[See Figma](https://www.figma.com/file/IKMfMmMmOxDUWrHfsVgxU740?node-id=28%3A96&utm_campaign=team&utm_source=slack&utm_medium=message&utm_content=file_comment#3706427)

**Comment by mattkrick** [comment]
```
animation-duration: 1s;
    animation-fill-mode: forwards;
    animation-iteration-count: infinite;
    animation-name: ;
    animation-timing-function: linear;
    background: linear-gradient(to right, rgb(238, 238, 238) 8%, rgb(221, 221, 221) 18%, rgb(238, 238, 238) 33%);
```
