### ISSUE TITLE
Create rule for rerendering the `fromNow` string

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#258]
`fromNow` gives us a friendly "just now" or "5 mins ago" string. If the site is left open, these don't update. Yeah. we're _that_ efficient. _Too_ efficient. We should be updating these every 1 minute or so. We could do something naive like invalidate the child on a setTimeout. Or we could get really complex. 

Estimated Effort: 3 points  + 10 bonus points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Monark is on this one...

**Comment by ndey96** [comment]
I'll pick this one up next for the 13 point estimate :)

@mattkrick what did you have in mind for something more complex than invalidating the child on a setTimeout?

**Comment by jordanh** [comment]
I think this is a great issue to pick up next. It's yours for 13 points.

May I suggest a first step is to propose a more fleshed-out approach here?

I can see at least two options (registering a `setTimeout` on the card, or, just flat out comparing timestamps and using `shouldComponentUpdate`). However, there are probably more approaches than this one! Probably, the simpler the better.

**Comment by ndey96** [comment]
@jordanh @mattkrick Here what I propose:

fromNow methods:
getFromNowString(updatedAt) -> returns “5 mins ago” string for example
getTimeoutDuration(updatedAt) -> returns 1 minute if timeElapsed < 1 hour, 1 hour if timeElapsed < 1 day, and so on.. 

in EditingStatusContainer:
setTimeout(this.forceUpdate(), fromNow.getTimeoutDuration());

This approach will minimize the amount of renders while keeping the granularity we desire.

To decrease the amount of timers we have going we can only call setTimeout if timeElapsed < 1 day

I hope this makes sense 😛

**Comment by mattkrick** [comment]
@ndey96 for the more complex solution, i'd suggest a new timer based on the next interval. For example, if we just created something, do a 30 second setTimeout. if it's a minute old, do a 60 second setTimeout. If it's an hour old, do a 1 hr setTimeout, etc.

alternatively, we could do a ~30 second setTimeout on the parent component that has all of the cards. That way there's only 1 timer going.

**Comment by ndey96** [comment]
@mattkrick Is it better to have a timer for every card but minimize the number of renders or 1 timer which will cause several unnecessary renders? I am leaning towards the former, what are your thoughts? Is it expensive to have several timers going?

**Comment by mattkrick** [comment]
yeah, the former certainly seems cheaper.

**Comment by jordanh** [comment]
@ndey96, you've been credited 13 points. [Your new point total is 40!](https://docs.google.com/spreadsheets/d/1NZGiusAxdvZaZ13oeCln-HFOut83o-pJsrjm-XEjimE/edit#gid=161861678).
