### ISSUE TITLE
Design timeline right drawer placeholder

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2580]
When there is nothing to put in "what's new" and the user has no active tasks, we need a placeholder for the right drawer. It should probably be a cute drawing of some sort telling you to create a task by going to the tasks page. Alternatively, this could be where we put the youtube link easter egg.

AC
- [ ] Design a placeholder & optional action image for the right drawer in the timeline

effort: 11 points

**Comment by ackernaut** [comment]
Here are the ideas we have for the right sidebar so far:
### Placeholders
- Move the date and YouTube rally link (we could start here and yank it when we get something better)
- Add a pro tip box (with rotating tips), like what we have in the Retro reflect phase, we could even link to 101 or blog content when there is content that supports a tip
### Content/controls
- Add a card, or an animated card, promoting what’s new
- Add filters for the timeline
- Add a component that shows tasks that are due soon

I’m open to more ideas/candidates…

![my dashboard_ timeline](https://user-images.githubusercontent.com/307286/51870635-cce19080-2319-11e9-8a77-f1338b67a317.png)

![my dashboard_ timeline 2](https://user-images.githubusercontent.com/307286/51870769-22b63880-231a-11e9-986d-98ddbaf5606a.png)

![gift-slide-icon2](https://user-images.githubusercontent.com/307286/51870816-4a0d0580-231a-11e9-8a45-56b67e6b8caf.gif)

I’m open to more ideas…

**Comment by mattkrick** [comment]
i'm not sure if the 2nd one will clash with suggested items, do you have a view of the 2 together?
how would the 3rd one look when we have a toast or 2 present? i'm a bit weary of this one because it's a new kind of global UI component to worry about (toasts, top notification bar, dashboard modal, etc.)

**Comment by ackernaut** [comment]
Yeah, I agree with the clash for no. 2 and the elevation confusion for no. 3…perhaps a combination of no. 2 and 3 for the new blog ad. I’ll add something.

**Comment by mattkrick** [comment]
For the placeholder, i'm thinking about a small drawing & the words "All caught up!" below it. something to let users know that's where the active tasks will be.

**Comment by mattkrick** [comment]
Placeholder for the placeholder is at: TimelineNoTasks.tsx

**Comment by mattkrick** [comment]
right now the placeholder is a thumbs up & a link to a rally video. this needs to be improved. moving to the backlog
