### ISSUE TITLE
Design animation for dimissing a suggested item & showing the next one

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2582]
When the last suggested item goes away, i animate the height to 0 & scale it to 0 so it looks like it flies away & fades.

Not sure how to animate when 1 goes way & the next one appears right on top of it. any links to inspiration welcome

AC:
- [x] example animation showing how to animate between suggested actions

effort: 10.5

**Comment by ackernaut** [comment]
[https://tympanus.net/Development/CardStackEffects/](https://tympanus.net/Development/CardStackEffects/)

In this set of examples “Dian” shows a single card go away and another card slightly spring in. Not sure that I like the left/right flop movement of the card going out but I think this example is a good direction.

**Comment by ackernaut** [comment]
Another resource, [Animista](http://animista.net/play/entrances/slide-in-fwd), where one can quickly play with different animation effects and generate styles.

**Comment by ackernaut** [comment]
here’s one iteration:
![card-change](https://user-images.githubusercontent.com/307286/51641456-d17a0380-1f2b-11e9-9e27-40e2f154c0d3.gif)
- top card eases out both translate-Y 64px and 100% to no opacity
- bottom card eases in 0-100% opacity, “spring” style bezier curve to scale in from 90% to 100% from center

**Comment by jordanh** [comment]
This is gorgeous!

We're doing newest items at the top of the timeline, right? Maybe having it transition up instead of down makes more logical sense? The content below the card is going to move up the page after the card is dismissed, right?

**Comment by ackernaut** [comment]
Yeah, I think the upward direction may make more sense. If the card is dismissed and there isn’t another CTA that pops into the same spot, then the cards below would move up. We could probably shrink the height of a placeholder while the card animates away, so that the cards below slide up into place.

**Comment by ackernaut** [comment]
![timeline-cards](https://user-images.githubusercontent.com/307286/51643483-3e909780-1f32-11e9-85f7-ba46dbf534f1.gif)
- the first CTA card slides up and fades out
- the second CTA card scales in and fades in
- the second CTA card slides up and fades out
- the event cards below slide up into place

**Comment by jordanh** [comment]
OH HECK YES
