### ISSUE TITLE
Design iteration for “what’s new blog” sidebar ad

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2587]
### AC
- Shows concepts with options for images, copy, CTA, etc.

### EE
- 10.5 points

**Comment by ackernaut** [comment]
Here are 2 concepts:

![gift-slide-icon2](https://user-images.githubusercontent.com/307286/51870961-aec86000-231a-11e9-8396-66170f5b735e.gif)

![my dashboard_ timeline 2](https://user-images.githubusercontent.com/307286/51870975-bab42200-231a-11e9-96dc-227db31c7c1e.png)

**Comment by mattkrick** [comment]
i think we need another round of design to come up with something that isn't toast-esque but also doesn't clash with the sugested actions.

moving this back to the backlog

**Comment by jordanh** [comment]
Iceboxing for now
