### ISSUE TITLE
Design copy for retro meeting completed timeline event

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2590]
When a retro meeting completes, i wanna see something show up in my timeline about it.

AC: 
I want
- a link to the summary
- to see what # it was
- see how many tasks it generated
- see how long it lasted
- what else would be useful? See which phase lasted the longest? this is where we should flex our analytical muscles!!
- should we show different stats after each meeting?

I also want fallback copy:
- if the meeting duration was under 5 mins 
- if no tasks were generated

Example: 
```
You completed Retrospective 5 with Team Strikeforce 

It lasted 1 hour 22 minutes and generated 12 tasks.
...
```

Effort: 10.5 points

**Comment by jordanh** [comment]
Some ideas here:

```
{{CONGRATULATORY_STR}}! You completed your {{MEETING_NUM_ORD_STR}} Retro with {{TEAM_NAME_STR}}. It lasted {{DURATION_HUMAN_STR}} and generated {{NUM_TASKS_INT}} tasks.

{{FINAL_WORDS_STRING}}
```

Notes:

- Our branded meeting is a "Retro", let's be consistent with our menuing
- For a little extra pizazz, let's use ordinal numbers for meeting numbers (`your 1st Retro`) for `{{MEETING_NUM_ORD_STR}}`
- Possible `{{CONGRATULATORY_STR}}` values:
   - `Congrats!`
   - `Bravo!`
   - `Nicely done!`
   - `You did it!`
   - `Nice work.`
   - `You done good.`

- Possible {{FINAL_WORDS_STRING}} values:
   - `Remember, the only wrong way to do a retro is not to do one at all.`
   - `Now's a great time to get the next Retro scheduled.`
   - `The time for looking backward is over, its time now to look to the future.`

Example:

```
You done good. You completed your 3rd Retro with Parabol Product. It lasted 42 minutes and generated 7 tasks.

Remember, the only wrong way to do a retro is not to do one at all.
```

**Comment by jordanh** [comment]
Question: will we have a CTA to navigate to the meeting summary, or should we add:

```
You done good. You completed your 3rd Retro with Parabol Product. It lasted
42 minutes and generated 7 tasks. _See meeting summary_.

Remember, the only wrong way to do a retro is not to do one at all.
```

**Comment by mattkrick** [comment]
I'm OK with either a button or link to the meeting summary.

Instead of a generic footer (which gets old after 10 retros), I'd love to include some value-add analysis in there. Is there any meaning we could extract from the meeting metadata? Eg one discussion item was talked about 5x longer than any other, this retro generated 3x more reflections/per person than any previous retro, number of participants, etc.
