### ISSUE TITLE
create first timeline event menu action

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2593]
The 3 dots in the upper right corner of each timeline event should open a menu.
I'm not sure what to put in that menu.

AC:
- a list of 1 - 3 events to put in the menu

effort: 11 points

**Comment by ackernaut** [comment]
I like that you excluded it for now until we know what kind of actions to afford. I got ahead in Figma so we would know what it might look like, but not sure what assumptions to test first in terms of UX.

**Comment by mattkrick** [comment]
it'll take some research on other site's newsfeeds.

ideas:
- pin (to top)
- copy (put on clipboard)
- share (i dunno)
- hide (remove this from my timeline forever, no way to undo it. useful for mock meetings, meetings of teams i'm on anymore, etc.)

**Comment by jordanh** [comment]
@mattkrick I think this is done now, right?

**Comment by mattkrick** [comment]
nah, i wrote this one as an implementation (although i guess it's both get feeback+ implementation). Any thoughts on what you'd like to see?

**Comment by jordanh** [comment]
I bet, a similar issue is going to come back around eventually
