### ISSUE TITLE
Add tooltip to invite control

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2594]
Any iconic controls without a label should have a tooltip, esp. the important ones!

<img width="1024" alt="invite tooltip" src="https://user-images.githubusercontent.com/307286/51873462-e0ddc000-2322-11e9-87b7-1696eedc1b86.png">

### Acceptance Criteria
- Tooltip shows on hover
- Tooltip goes away on tap
- Invite modal shows on tap
- Extra points for any reusable pattern for other controls (I know this particular case is tricky because the control is a toggle for a modal portal, and the tooltip is also a portal).

### Estimated Effort
- 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
Recommended for next Sprint 20%

**Comment by jordanh** [comment]
Yeah, let's get this one going

**Comment by ackernaut** [comment]
@mattkrick I’m pretty sure you have opinions here. I’m pulling for thoughts first so that I don’t burn a lot of trial-and-error time on a bad pattern. Here are my initial thoughts about the design:

The goal is to have a control (eg. icon-only button) that can trigger both a tooltip and a dialog. We separate the concerns of the components:
- A button can have events like `onHover` and `onClick`
- `onHover` can trigger something like a tooltip portal
- `onClick` can trigger something else like a dialog portal
- We can pass button coords to the tooltip portal so the tooltip knows where to appear relative to the button

As for the component implementation:
- I see that `usePortal.tsx` is probably the latest hotness for dialogs
- `Tooltip.js` looks a little older and probably is due for a TS refactor

**Comment by mattkrick** [comment]
If you wanna cut your teeth on it, I'd say try writing a react hook called `useTooltip` that mimics `useMenu`. Maybe it returns a `{showTooltip, hideTooltip, tooltipPortal}`.

then you could write
```
<Button onMouseEnter={showTooltip} onMouseLeave={hideTooltip}>
{tooltipPortal(<div>Hi there</div>)}
```

**Comment by ackernaut** [comment]
🔥 thanks Matt that looks like a great pattern to work towards
