### ISSUE TITLE
Implement avatar menu header

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2596]
![meeting-avatar-menu-header](https://user-images.githubusercontent.com/307286/51881357-7471b980-2340-11e9-98e9-cc2a3b7e19f1.png)

![team-dash-avatar-menu-header](https://user-images.githubusercontent.com/307286/51881358-750a5000-2340-11e9-972f-942e1f8c0aa8.png)

### Acceptance Criteria
- The avatar menu has an informational header including:
  - Preferred name
  - Connection indicator
  - Optional: badge for team lead
  - Second line for team dash has email address
  - Second line for meeting has connection and check-in status
  - Has user’s local time and timezone

### Estimated Effort
- 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Iceboxing for now
