### ISSUE TITLE
Error: ResizeObserver loop limit exceeded

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2604]
https://sentry.io/parabol/action-production/issues/706326536/?referrer=github_plugin

```
None: ResizeObserver loop limit exceeded
  at None (/retro/_zYsBI1Y07/discuss/4)
```

**Comment by jordanh** [comment]
AC:
  - Triage to root cause (possible opening new issue), fix if less than EE

EE: 11 points
