### ISSUE TITLE
TypeError: Failed to fetch

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2613]
https://sentry.io/parabol/action-production/issues/741307035/?referrer=github_plugin

```
TypeError: Failed to fetch
  at _promiseRejectionHandler (/me/settings)
```

sse-ping returns a series of 200s *& then fails returning(?) null

**Comment by jordanh** [comment]
AC:
  - Triage to root cause, fix if less than EE

EE: 11 points
