### ISSUE TITLE
Exception on demo reflection deletion

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2633]
## Issue - Bug

Was standing over the shoulder of a techstars member who was demoing our product. Noticed this bug:

1. Go to: https://action.parabol.co/retrospective-demo
2. Enter a few reflections
3. Delete one

- **OS:** macOS
- **Browser:** Chrome
- **Estimated effort:** 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### Acceptance Criteria (optional)
Users can:
   - Delete reflections from the demo

**Comment by mattkrick** [comment]
dupe of #2528
