### ISSUE TITLE
Add optional descriptions to Retro reflection prompts

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2634]
## Issue - Enhancement

I observed a user at Techstars try our retrospective process. He was familiar with the concept of a retrospective and a "lessoned learned meeting" but had never run a formal agile retrospective. He became frustrated by the reflect interface, specifically he didn't know what "Start" "Stop" and "Continue" were trying to tell him

We should add an element for additional copy. Here's an ultra-low fidelity prototype

![image](https://user-images.githubusercontent.com/103000/52450631-bf35c300-2af0-11e9-8108-d3bf7c6d7fab.png)

### Acceptance Criteria (optional)
A design where users can:
   - Use Retro template "Customize..." modal to:
      - create/update/delete descriptions for each prompt field they add
   - Start a retro with a given template and see description fields (if set)

Also:
   - A spreadsheet of description fields for existing prompts
   - Implementation issue(s) to bring this design to production

- **Estimated effort:** 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
See latest progress [in Figma](https://www.figma.com/file/MZ1A8PG7aOuupJK0cxzEwmMn/Reflect-Phase?node-id=0%3A1)

**Comment by ackernaut** [comment]
[Working draft](https://docs.google.com/spreadsheets/d/10kog95I4TDJtTWptv9UqhTfnhOkDkmiNFQBGJj_qfss/edit?usp=sharing) (Google Sheet) to propose title/prompt edits and add descriptions to existing templates
