### ISSUE TITLE
High fidelity designs - Company Hierarchies

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2643]
tl;dr- orgs should do whatever a team can do, teams should have teams in them.

I say screw orgs. You've got people & teams. Teams can belong to other teams. What we call an org today is really just a team of teams + people. Who's to say an entire org can run a retro?
Org should be synonymous with "Top Level/Billing Team". That reduces hierarchy.

Next, teams should be able to include teams. When 1 team has another team, it includes all the people who are currently on the child team. Note that this means multiple orgs can have the same team! That's good, that's like slack's portals.

**Comment by jordanh** [comment]
Still a great idea. No doubt will get to this one day (soon?)
