### ISSUE TITLE
Integrations design exploration

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2654]
## Issue - Enhancement

Multiple potential enterprise users have volunteered that Jira and Confluence integrations would be pre-requisites to making a purchase. Of course, I prefer to sell it first before we build it.

Let's make a super low fidelity (think Pen and Ink) that we could use a basis for kicking around.

Let's also invite each other to a Jira and Confluence instance so we can all poke around.

### Acceptance Criteria (optional)
Users can:
   - Add integrations to Jira and Confluence on a team level
   - Assign/export new tasks as Jira tickets, mapping Parabol users to Jira users
   - Have the meeting summary automatically export to a new Confluence page
      - We need to learn how to organize these:
         - Do we need to specify a folder? Tags? Etc.?

- **Estimated effort:** 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
Stuck on:
- Using Jira + Confluence ourselves for selected domain to build empathy and product knowledge
- Interviewing active users and potential users about their experience using Jira and Confluence, and their expectations about integrating these with Parabol. Consider building this list of users biased toward assumed ability and willingness to purchase at a Pro tier

**Comment by jordanh** [comment]
We're getting more of these interviews set up... I think we're going to be "unstuck" from a user empathy stand point in the next sprint

**Comment by jordanh** [comment]
This has been broken into smaller issues. We can close and trust it is tracked elsewhere.
