### ISSUE TITLE
squelch url attacks from server console logs

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2661]
silly researchers are blowing up our server logs with url encoding attacks.

AC
- [ ] we should first be catching these in sentry (i ignored wrapping the body parser error handler)
- [ ] we should not propagate these errors to the console
- [ ] we should consider something fun like a 301 to a silly gif

effort: 11 points

**Comment by jordanh** [comment]
Ha. Silly gif.

**Comment by jordanh** [comment]
Scrubbed. Icebox for now.
