### ISSUE TITLE
Error: SSE response not found

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2664]
https://sentry.io/parabol/action-production/issues/884526022/?referrer=github_plugin

```
Error: SSE response not found
  File "app:///graphql/httpGraphQLHandler.ts", line 19, in null.<anonymous>
    sendToSentry(new Error('SSE response not found'), {userId: viewerId})
...
(3 additional frame(s) were not displayed)

Error: SSE response not found
```
AC
- [ ] SSE works

effort: 13 points

**Comment by mattkrick** [comment]
nothing obvious happening locally, so the 3 people that this affects must have some crazy proxy settings. we'll need to talk to them personally about their firewall

**Comment by jordanh** [comment]
@mattkrick matt can you jot down their parabol user ids here and I can reach out to them?

**Comment by jordanh** [comment]
Affected users:
* https://app.hubspot.com/contacts/3888472/contact/2744051
* https://app.hubspot.com/contacts/3888472/contact/3177951
* https://app.hubspot.com/contacts/3888472/contact/3177451

**Comment by jordanh** [comment]
I spoke to [a user](https://app.hubspot.com/contacts/3888472/contact/4270951) today and gathered some more info. When their users behind their firewall encounter this, it manifests as:

- Several minutes of good connectivity
- Parabol says it disconnects
- Then Parabol reconnects and disconnects in a loop—updates become intermittent and the app becomes less responsive
- If a user reboots, then they once again get several minutes of good connectivity

It's fascinating to me that a refresh "fixes" this. The symptoms make me believe there is something we can do about it. This user is also checking to see if this behavior is the same if they use their VPN from home.

I had them run https://websocketstest.com/. Here's what I learned:

- WebSockets connection fails over SSL (port 443)
- He is connecting via a corporate proxy, which identifies itself as: `McAfee Web Gateway 7.7.2.17.0.26803`

This last bit of info is great. Failing getting access to the customer site, we might be able to set this up on our own.

@mattkrick anything we might be able to triage or work around given that a refresh is required to fix the connectivity? Does Trebuchet not fully close and open a new HTTP connection unless it is refreshed?

**Comment by jordanh** [comment]
Note: I just put in a request to download an evaluation copy of this firewall software

**Comment by jordanh** [comment]
The root cause of this issue was websockets being denied by a corporate McAffee firewall. Further, their firewall filtered out long-polling SSE.  The resolution was to request their firewall whitelist websockets for the Parabol domain
