### ISSUE TITLE
Error: Not meeting facilitator

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2671]
https://sentry.io/organizations/parabol/issues/885795430/?project=107196&referrer=github_plugin

```
Error: Not meeting facilitator
  File "app:///graphql/mutations/navigateMeeting.js", line 49, in resolve
    return standardError(new Error('Not meeting facilitator'), {userId: viewerId})

Error: Not meeting facilitator
```

AC
- [ ] When the facilitator reconnects, they should get the current meeting state & optionally promote themselves back to facilitator 

effort 12 points

**Comment by jordanh** [comment]
This has been fixed
