### ISSUE TITLE
Social Check-In CTA

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#2683]
## Issue - Enhancement

Users continue to be confused at this stage; most attempt to type their response in the question customization box, which overwrites the question. 

> We were confused during the social check-in. Our instinct was to type our responses."

Multiple users have suggested we add clarifying text to indicate verbal vs written response. Let's test a few variations.

### Acceptance Criteria (optional)
Users can:
   - Immediately understand that they should speak their answer out loud
   - Do not attempt to type their response
   - Facilitator is still able to customize the prompt

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
Consider MD icon `record_voice_over`

**Comment by tayamueller** [comment]
Feedback from [this Free-tier user](https://app.hubspot.com/contacts/3888472/contact/5413301):

> I really didn't understand how the social check-in worked. It seemed broken... There was no way for people to answer the question.
