### ISSUE TITLE
carriage returns

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#2684]
## Issue - Enhancement

> Wasn’t sure how to complete a task. When I hit Enter I expect it to close the task & create a fresh task box. Tasks + carriage return = weird"

### Acceptance Criteria (optional)
Users can:
   - Do this
   - Do that
   - Cannot do that

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
is the quote the acceptance criteria?
in ALL cases we want to create a new task when you hit enter?
like during the discuss phase?
and when you edit an existing card?

**Comment by jordanh** [comment]
> is the quote the acceptance criteria?
> in ALL cases we want to create a new task when you hit enter?
> like during the discuss phase?
> and when you edit an existing card?

In short, yes all the cards should behave the same now. Reflections during Discuss. And all Tasks everywhere.

Adding acceptance criteria.

AC:

A user can:
   * Press enter to submit on all card surfaces (Tasks, Reflections)
   * Press shift-enter to create a line break

EE: 10.5 points
