### ISSUE TITLE
Meeting navigation updates to indicate completed phases

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2688]
Pulled from issue #2516, [see Figma](https://www.figma.com/file/0lOTlvsj87GBFFzgee9OkVWi?node-id=12%3A490&utm_campaign=team&utm_source=slack&utm_medium=message&utm_content=file_comment#4585533)

### Acceptance Criteria
- Left navigation shows completed phases
- Phase header shows completed phases

### Estimated Effort
- 10.5 points

**Comment by jordanh** [comment]
Iceboxing for now. Would love to re-open this one.
