### ISSUE TITLE
Designed list of teammates/participants in meeting

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2689]
## Background
Pulled from #2516, [see Figma](https://www.figma.com/file/0lOTlvsj87GBFFzgee9OkVWi?node-id=3%3A0&utm_campaign=team&utm_source=slack&utm_medium=message&utm_content=file_comment#4585816)

I want to explore a component where I can see all teammates/participants and useful information like connection state, or if they have affordances to indicate they are willing to move on to the next phase.

I’m making an assumption that it may be helpful to separate concerns between a component that shows participants, a component that shows video feedback per layout options afforded, and a component that indicates the current phase/stage by owner (rounds!).

Also, this component may have an updated iteration on a clear primary action for inviting others to join. This component needs to be clear and usable on both desktop and mobile devices. The component could fill a dialog, side sheet, drawer, etc. based on the screen real estate/interactions.

### Acceptance Criteria
- Mid-fi concepts reviewed internally
- Next steps identified: test with users, write implementation issues, etc.

### Estimated Effort
- 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Part of ongoing effort. Superseded by #3077
