### ISSUE TITLE
Error: Invalid document ID

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2690]
https://sentry.io/organizations/parabol/issues/887411769/?project=107196&referrer=github_plugin

```
Error: Invalid document ID
  File "app:///graphql/handleGraphQLTrebuchetRequest.ts", line 47, in handleGraphQLTrebuchetRequest
    throw new Error('Invalid document ID')
  File "app:///graphql/httpGraphQLHandler.ts", line 31, in null.<anonymous>
    const response = await handleGraphQLTrebuchetRequest(req.body, connectionContext, {
...
(4 additional frame(s) were not displayed)

Error: Invalid document ID
```

This is caused by pushing a new version to prod.
Queries are hashed. If an old hash is requested, the server doesn't know about it.

To better handle this, we'll need to persist the old ones.
i'd like to avoid keeping them in a DB table, but i'm not sure how else to accomplish this.

**Comment by jordanh** [comment]
This is fixed
