### ISSUE TITLE
Error: Not facilitator

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2691]
https://sentry.io/organizations/parabol/issues/897495039/?project=107196&referrer=github_plugin

```
Error: Not facilitator
  File "app:///graphql/mutations/moveMeeting.js", line 114, in resolve
    return standardError(new Error('Not facilitator'), {userId: viewerId})

Error: Not facilitator
```

AC
- [ ] each meeting has a "preferredFacilitator". when that person reconnects, they check to see if they are preferred. if they are, then they request to be facilitator again.

**Comment by jordanh** [comment]
This has already been fixed
