### ISSUE TITLE
Error: ResizeObserver loop limit exceeded

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2692]
https://sentry.io/organizations/parabol/issues/888625752/?project=107196&referrer=github_plugin

```
Error: ResizeObserver loop limit exceeded
  at None (/meeting/Byw8SozA/agendaitems/7)
```

it's back. let's ensure that we're using the Chrome native resize observer in action meetings, too.

**Comment by jordanh** [comment]
Closing, will reopen if resurfaces and/or we re-prioritize it
