### ISSUE TITLE
create uwebsockets mediasoup microservice

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2695]
for video, i'd like to go with mediasoup & uwebsockets
- mediasoup v2 is a very fast SFU: https://webrtchacks.com/sfu-load-testing/
- it is just a node module (with all the critical stuff written in C++)
- mediasoup v3 is gonna get released this week or next & promises to be even faster

for a signalling server, i'd like to use uwebosckets:
- uwebsockets is supposedly stupid fast. like, faster than nginx fast. https://github.com/uNetworking/uWebSockets.js

**Comment by jordanh** [comment]
The questions we might be curious about:

- When do we connect to our SFU, always? Only when >X participants in a meeting?
- How would recording work with this SFU?
- How would SIP/telephony be architected in?
- If we were to test this SFU, what would expect of it to evaluate it?
- Do we have to wait for uWebSockets, could we do something sub-optimal for starters?

**Comment by jordanh** [comment]
Scrubbed. Iceboxing until we revisit video.
