### ISSUE TITLE
Add 'su' override for teams on GraphQL graph

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2707]
## Issue - Enhancement

As a superuser, I want to be able to see what teams a user is on. Currently, we limited the scope to show only the teams the viewer has permission on with no `su` override. I'd like to change this.

Example query:

```graphql
query {
  user(userId: "auth0|58fa9345fef8086b7f91a0e7") {
    id
    email
    organizations {
      id
      name
      tier
    }
    organization(orgId: "SJRUQzdAl"){
      name
      tier
      billingLeaders {
        name
 	email
        inactive
      }
      teams {
        id
        name
      }
    }
  }
}
```

### Acceptance Criteria (optional)
Super users can:
   - See all the teams a user belongs to via:
      - User
      - Organization

- **Estimated effort:** 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
@jordanh the above example query is working as intended.
it also doesn't mention "team" anywhere, so maybe you meant another query?
could you please provide a broken query or the explicit userId & orgId if this one is broken?

**Comment by jordanh** [comment]
For sure! I'll update the query above. I pasted the wrong one 😊

**Comment by jordanh** [comment]
Updated query!
