### ISSUE TITLE
Design mockup of jira icon on task card

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2708]
AC
- [x] Figma design shows a jira button on the task card
- [x] Design shows that when you click the button, it exports to jira (same as what happens in GH today)
- [x] Jira is added to the integrations list (below GH above slack)
- [x] Mockup of ticket in Jira

Effort: 12 points

**Comment by jordanh** [comment]
Adding some notes from a user:

> I recall specifically commenting in one of our reviews that it would be nice if the task cards could get converted into Jira tasks or stories. Specifically, it would be nice to specify which they got converted into (tasks, stories or epics)

Might be interesting if pressing on the Jira logo would let you specify what kind of object it creates...

**Comment by ackernaut** [comment]
Should we assume and test that most teams work from 1 Jira project? And a power user may be wanting to define a task, story or epic from a Parabol task card for that project?

### 1 project
If only 1 project integrated, we show the Jira logo and simple menu options…
- Add as task
- Add as story
- Add as epic

### 2+ projects
If 2+ projects, users pick the project first, then the menu refreshes to add as [type] like above…
- Add to project PROD
- Add to project SPRT
- Add to project DSGN

**Comment by ackernaut** [comment]
Up for review ([see Figma](https://www.figma.com/file/aFFwcgvkGJhjwQlMUxB4g3Zt?node-id=132%3A2291&utm_campaign=team&utm_source=slack&utm_medium=message&utm_content=file_comment#5123841)) also being reviewed #2735

**Comment by ackernaut** [comment]
[re: epic vs story vs task](https://community.atlassian.com/t5/Jira-Core-questions/epic-vs-story-vs-task/qaq-p/204224)

**Comment by ackernaut** [comment]
re: tasks/stories/epic [in Figma](https://www.figma.com/file/aFFwcgvkGJhjwQlMUxB4g3Zt?node-id=137%3A5836&utm_campaign=team&utm_source=slack&utm_medium=message&utm_content=file_comment#5130697)
