### ISSUE TITLE
Video Rollout Plan

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2716]
Here's the plan for rolling out video in phases:

- [x] refresh video PR #2710
- [ ] design video in figma #2715
- [ ] implement design & ship to prod
- [ ] add TURN server(s)
- [ ] add screensharing
- [ ] add transcripts
- [ ] add subtitles 
- [ ] add recording (canvas-based)
- [ ] add free-flow meeting type 
- [ ] refactor action meeting into eos level 10
- [ ] add SFU
- [ ] add server-based recording piped from SFU (higher quality, individual feeds)

**Comment by jordanh** [comment]
Scrubbed.

Iceboxing for now. Will very likely revisit soon.
