### ISSUE TITLE
Tooltips added

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#272]
## Issue - Enhancement

When users need a little extra help with Action UI, they want tooltips for simple explanations, tips, definitions, etc. so that they can use Action more efficiently.

The Tooltip component:

- [ ] Uses a module pattern similar to Menus: component/container/ducks + portals-hoc
- [ ] Has options for behavior: `onHover` `onClick` or `triggerBy` another event/method
- [ ] Has options for presentation/orientation: centered `top|right|bottom|left` of the visual element that the tooltip describes.

Presentation specs:

![tooltip example](https://cloud.githubusercontent.com/assets/307286/25153348/dcea1b6e-2451-11e7-8c91-e42378127047.png)

```
background: ui.palette.dark,
borderRadius: ui.borderRadiusSmall,
color: 'white',
fontSize: appTheme.typography.s2,
fontWeight: 700,
padding: '1rem'
```

- [ ] Add appropriate box-shadow for correct level of depth
- [ ] Add small arrow variants, centered top | right | bottom | left

**Estimated effort**: 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
## Options

Here are some options for tooltip components:

- https://github.com/react-component/tooltip
- https://khan.github.io/react-components/#tooltip
- http://react-toolbox.com/#/components/tooltip
- https://github.com/gilbarbara/react-joyride (also provides tutorial walkthrough capability)
- https://github.com/wwayne/react-tooltip

## Analysis

`react-joyride` requires custom CSS or SASS. `react-toolbox` also requires SASS. So, these are probably out for now.

Both `react-component/tooltip` and `react-tooltip` are lacking somewhat in quality documentation. Comparing the two interfaces, `react-component/tooltip` nests around a component like this:

```jsx
<Tooltip placement="left" trigger={['click']} overlay={<span>tooltip</span>}>
  <a href='#'>hover</a>
</Tooltip>
```

While `react-tooltip` searched through the virtual DOM to magically extend components:

```jsx
<ReactTooltip />
<p data-tip="hello world">Tooltip</p>
```

I find `react-tooltip`'s approach scary and dangerous.

## Conclusion

I think we should start by trying https://github.com/react-component/tooltip, and search for other options if we find it doesn't suit us.

**Comment by ackernaut** [comment]
The `react-component/tooltip` ships with some version of Bootstrap’s tooltip styles in Less. [https://github.com/react-component/tooltip/tree/master/assets](see here)

**Comment by ackernaut** [comment]
I wonder if we could just take the “good” JS parts and build our own JS styles?
https://github.com/react-toolbox/react-toolbox/blob/dev/components/tooltip/Tooltip.js

**Comment by mattkrick** [comment]
it's still tween years for component libraries. No one can agree on how to style & where state should be stored. It'd be nice to stick to inline styles, but to achieve that, we'll just have to piece together what we like. Another library to look at (but not use): http://www.material-ui.com/#/components/icon-button

Finally, it's worth noting that when I went down the tooltip road about a year ago, I couldn't find anything I liked. I wanted something that was animated & fun, but that could include links & bullet points, maybe even pictures. Many tooltips don't let you hover over them. Those that do don't go away easily. So, I made my own. We could borrow some logic from there, if you like the animations: https://github.com/mattkrick/meteorTooltips

**Comment by jordanh** [comment]
I'm moving this to "The Future" – we can tackle with onboarding enhancements.

**Comment by ackernaut** [comment]
@jordanh this might make a good mid-level E4E project. It can sit there unless we finally get to it?

**Comment by ackernaut** [comment]
PS. re: E4E I could tighten up the spec and show a visual design

**Comment by jordanh** [comment]
Sure, I am certainly in support!

**Comment by mattkrick** [comment]
Setting this as freemium since we'll need a tooltip to tell people to upgrade it they want custom check-in questions

**Comment by mattkrick** [comment]
i'll start with https://github.com/react-component/tooltip but in the future we'll end up building our own. it floors me

**Comment by mattkrick** [comment]
ended up building my own because:
- animations were SUPER janky with the one above
- used deprecated animations package
- insanely bloated
- didn't reposition based on how far away it was from the edge
- didn't encapsulate the children. it forced you to write children to handle it. this is a no-go when the child is a 3rd party component like FontAwesome. 

@ackernaut feel free to modify the styles in `TooltipModal.js` as well as create a new animation based off of `AnimatedFade`. The fade is great for menus, not so much for tooltips.

**Comment by ackernaut** [comment]
👍  I made a first pass in Figma of what the component looks like. When you’re ready just assign this one to me.

**Comment by mattkrick** [comment]
all you, gotcha started on epic7-tooltips branch

**Comment by ackernaut** [comment]
👾  thanks @mattkrick !!
