### ISSUE TITLE
Fix Remove From Org

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2721]
​

AC

- [ ] can remove someone from an org

​

Effort: 11 points

**Comment by jordanh** [comment]
@mattkrick are there repro steps for this or a linked Sentry issue? Doing some scrubbing. This looked important.

**Comment by mattkrick** [comment]
i think this came from Taya saying she had to do it & it worked on the third try

**Comment by jordanh** [comment]
Closing for now until we get a fresh report or reproduction steps
