### ISSUE TITLE
Implement task card integration menu updates [WIP]

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2723]
Note: the AC is a WIP, not ready for sprint board yet

[Example visual concepts in Figma](https://www.figma.com/file/aFFwcgvkGJhjwQlMUxB4g3Zt?node-id=34%3A0&utm_campaign=team&utm_source=slack&utm_medium=message&utm_content=file_comment#4920397)

#### No connected providers
- Uses MD icon `add` for the card button
- Menu shows options to connect GitHub and Jira with respective logo and labels
- Tapping menu options direct the user to the settings view for the selected provider
#### 1 connected provider
- Assuming the team may only use that integration, we use the provider logo for the card button
- We show 1 or many integrations (eg. GitHub repos) that create the issue in a single click
- We show a menu divider and a menu option to “Manage integrations…” that directs to team settings
- Folks can add the another provider in team settings
#### 2+ connected providers
- Uses MD icon `add` for the card button
- Menu options include creating an issue in Jira or creating an issue in GitHub
- If 1 integration per provider (eg. Jira project, GitHub repo), creates the issue
- If 2+ integrations per provider, updates the menu to select the destination once you tap a provider
- Alternatively we put up to top 5 recently used integrations with an inline search to find others
- Consider keeping “Manage integrations…” option at the bottom separated with a menu divider

### Estimated Effort
- 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
alternate icon ideas:
- sync
- cloud_upload
- publish

publish probably gets my vote

**Comment by ackernaut** [comment]
Closed in favor of #2735
