### ISSUE TITLE
Design Video Flow

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2729]
We need to design how video looks & what it can do. Here's my take:

@jordanh @ackernaut 

Acceptance Criteria:
mockups of the following stories:
- At any point in a meeting, a user can click a "Start Video (Beta)" button (probably in the header by the avatar group)
- When a user clicks the "Start Video" & an HTML5 camera permissions dialog is going to pop up
  - a black overlay covers the meeting
  - a modal pops up on top of that overlay saying something like "Parabol needs access to your camera and microphone so your team can see & hear you. Click "Allow" in the prompt to begin"
 - If a user clicks "Block" the modal says something like "Parabol is current blocked from accessing your camera. Please grant access to the camera to join the call." Then, show browser-specific messaging like "Click Here: chrome://settings/content/camera"
- If a user does not have a camera and microphone, show a message like "You need a microphone..."
- After a user has given permission to use their camera, their avatar is replaced with their face. and the "Start Video" button is replaced with 2 buttons: Video and Audio on/off toggles
- When video is toggled off, there's a slash through the video icon on the toggle button & their face is replaced with their avatar
- When audio is toggled off, there's a slash through the microphone icon on the toggle button & their face has a dark overlay & a dark red microphone that gains opacity when hovered over.
- when a team member is muted, they have a red sound wave badge on their avatar on the lower left 
- During the check-in round, the user's video shows in the center & their avatar in the corner goes back to their icon
- when you double click their avatar, the face grows to ~320x240 (most everything is double-click to expand, i think this is the right feel)
- there's a grid button next to the avatar group(?) & when you click it the avatars fill up the entire screen brady bunch style with a dark overlay over the meeting content. clicking anywhere animates them back to normal.
- when a user can't connect & we think the browser is to blame, they get a modal saying "You need a modern browser to use the video chat"
- when a user can't connect & we think it's an asymmetrical NAT, mobile network, etc, we say "Free video is not supported for mobile users or users behind corporate firewalls. Get in contact with us."  
- when the ~5th video connects, we pop a snackbar toast from the bottom saying "Free video does not support high quality video for more than 4 people. Get in contact with us". we then degrade video quality for [all/future] peers to try and keep up. we start by degrading resolution, then once we hit ~64x64px, we degrade frames down to 15 fps. (no hard limit is set because i'm curious how hard folks can push it.)
- when a person is talking, an indicator like a ring around their avatar lights up & maybe gets brighter the louder they talk.

Effort: 13 points

**Comment by ackernaut** [comment]
Revisited in S.P.A. 11

**Comment by jordanh** [comment]
Iceboxing for now
