### ISSUE TITLE
Updated Team Settings with new tabbed design pattern

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2733]
## Issue - Enhancement

@ackernaut when do you want to pull the trigger and implement that new tabbed pattern in Team Settings?

### Acceptance Criteria (optional)
Users can:
   - Use the new tab pattern, instead of the boxy boxes

- **Estimated effort:** 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
Duplicate of #2493 on the sprint board

**Comment by jordanh** [comment]
Iceboxing for now
