### ISSUE TITLE
Implemented new card integration control pattern for Jira

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2735]
## Issue - Enhancement

[See concept in Figma](https://www.figma.com/file/aFFwcgvkGJhjwQlMUxB4g3Zt?node-id=132%3A2291&utm_campaign=team&utm_source=slack&utm_medium=message&utm_content=file_comment#5123841)

### Acceptance Criteria
Users can:
  - Click a `publish` icon (instead of the current GitHub Octocat) to reveal a list of possible Task Card destinations
  - **0 connected providers**
    - Clicking opens a 2nd tab navigated to Team Settings to add the integration
    - Configuring the integration updates the 1st tabs state so the integration may be used
    - (optional) Toast is sent to team notifying them a new integration is available
    - In the future, let’s consider a Provider dialog that can open inline over the cards, or in Team Settings (see Figma)
  - **1 connected provider**
    - Show icon of connected provider on card
    - Menu shows destinations (Jira projects or GitHub repos)
    - Teammates must go to Team Settings to add more providers or destinations
  - **2+ connected providers**
    - Show `publish` icon on card
    - User selects a provider (Jira/GitHub)
    - Menu updates so that user can select destination (project/repo)
  - **Integrated cards**
    - Show link: {Provider Issue No.}
    - Show watermark
    - Are read-only, no integration button
  - **Notes**
    - N.B. we are explicitly _not_ implementing the "Recent destinations..." enhancement this first pass
    - Max height of menu is 5 options, otherwise scrolling if multiple destinations (projects/repos)
    - In the future, if there is 2-way sync, perhaps we use `sync` icon instead of `publish`
    - For V1, in Jira, we only create issues on projects. Later we can learn more about being able to publish/sync by type (issue, epic, etc.)

### Estimated Effort
- 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
Need to resolve this with #2723

**Comment by ackernaut** [comment]
Updated with latest from Figma, closing #2723

**Comment by ackernaut** [comment]
Up for review alongside #2708

**Comment by ackernaut** [comment]
PS. Review that these are the best criteria, then move it back To Do so that it can be implemented.

**Comment by ackernaut** [comment]
Will update criteria after reviewing further with @mattkrick today, some quick notes:
- Each user has the option to connect their own Atlassian/Jira account or create an issue as the first integrated Jira user (who is the default integration admin so-to-speak)
- Connecting from the card menu (first time or as your own user) opens a new tab. Oauth magic and integration management happens on that tab (no modal UX). The user stays in the same context on the initial tab, but their menu options would be updated to reflect their new abilities.
- Additional integrations have to be added via Team Settings, unless a user is initially connecting their own account

**Comment by mattkrick** [comment]
closing in favor of design issue #2773
