### ISSUE TITLE
Jira integration settings sheet designed

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2736]
## Issue - Enhancement

When I want to add the Atlassian Jira integration, I want to configure the possible destinations for Parabol Task cards, so that I can create Jira Tasks & Stories in the appropriate spots

### Acceptance Criteria (optional)
Users can:
  - CRUD destinations for Jira Tasks and Stories

- Captured as implementation issue #2740 

- **Estimated effort:** 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

- **Design uncertainty:** 2

**Comment by ackernaut** [comment]
[re: epic vs story vs task](https://community.atlassian.com/t5/Jira-Core-questions/epic-vs-story-vs-task/qaq-p/204224)

**Comment by ackernaut** [comment]
[See Figma](https://www.figma.com/file/aFFwcgvkGJhjwQlMUxB4g3Zt?node-id=137%3A4615&utm_campaign=team&utm_source=slack&utm_medium=message&utm_content=file_comment#5129002)

**Comment by ackernaut** [comment]
Figma concepts ready for review

**Comment by ackernaut** [comment]
New details to be added (after further review with @mattkrick):
- Jira integration comes via connecting through a single Atlassian account
- A Jira user has access to sites
- A site has many projects
- The user picks a first site to integrate Parabol with Jira
- The user can see what sites are integrated via their user
- A user can add other sites they are a member of
- A single Atlassian connection could be used for both products: Jira (issues in projects), Confluence (pages in spaces)
- Are `site/project` destinations that are available to other members but not me (via Jira ID) visible and read-only in integration view?
