### ISSUE TITLE
Add My Actions to Team Dashboard

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#274]
## Issue - Enhancement

Feedback from Aaron Dignan.

Actions are indeed private to the individual. That is to say, they are not visible by your teammates. However, when a team member is looking at their team dashboard, they want to see their projects _and_ actions, so that they can prioritize what to do next.

A team member's actions should also appear on the team dashboard. Perhaps in a collapsable and scrollable list just above the team agenda items.
- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
closing as we're headed a different path...
