### ISSUE TITLE
Implements updates to {Provider} settings view

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2740]
Capturing latest details from #2736, see [Figma designs](https://www.figma.com/file/aFFwcgvkGJhjwQlMUxB4g3Zt?node-id=137%3A4615&utm_campaign=team&utm_source=slack&utm_medium=message&utm_content=file_comment#5129002)

### Acceptance Criteria
The provider settings view:
- Opens in a dialog
- Has a primary action to connect or add destination
  - Add destination is a button with a dropdown menu. Tapping an option adds the destination
- Has a secondary menu to refresh token and remove provider connection
- Has a list of integrated destinations (Jira projects, GitHub repos, Slack channels)
- Each destination has a name as external link, shows users as applicable, shows actions either with 1 flat button, or consider a flat button beside a secondary menu for other options, or stuffing all options in a menu sans flat button
- Dialog can open over settings view or over connecting via task card for first time on team

### Changes to existing providers:

- Remove GitHub details view
- Update GitHub row of provider list so it matches new design
- Remove all the GitHub repo specific stuff
- Removes `integrationCount` and `userCount` per design

### Estimated Effort
- 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
stuck behind #2814

**Comment by mattkrick** [comment]
things to delete
- remove github repo mut
- [x] GitHubRepoRow
- [x] LeaveIntegrationMutation
- [x] GitHubReposMenuRoot
- [x] githubreposlistmenu
- [x] GitHubIntegrationsRoot
- [x] githubintegrations
- [x] AddGitHubRepoMutation
- [x] IntegrationJoinedSubscription
- [x] JoinIntegrationSubscription
- [x] LeaveIntegrationMutation
- [x] IntegrationLeftSubscription
- [x] RemoveGitHubRepoPayload
- [x] removeGitHubReposForUserId
- [x] githubRemoveMember
- [x] githubAddMember
- [x] archiveTasksForManyRepos
- [x] leaveIntegration
- [x] removeGitHubRepo
- [x] addGitHubRepo
- [x] leaveIntegration
- [x] joinIntegration
- [x] maybeJoinRepos
- [x] JoinIntegrationsPayload
- [x] integrationJoined
- [x] integrationLeft
- [x] githubRepoAdded
- [x] GitHubRepoAddedSubscription
- [x] githubRepoRemoved
- [x] GitHubRepoRemovedSubscription
- [x] githubMemberRemoved
- [x] GitHubMemberRemovedSubscription
- [x] AddGitHubRepoPayload
- [x] RemoveGitHubRepoPayload
- [x] GitHubMemberRemovedPayload
- [x] LeaveIntegrationPayload
- [x] GitHubIntegration
- [x] githubRepos
- [x] AddGitHubRepo
- [x] getOptimisticTeamMember
- [x] GITHUB table

things to update
- [x] removeTeamMember
- [x] removeProvider
- [x] RemoveProviderMutation
- [x] rootMutation
- [x] addProviderGitHub
- [x] rootSubscription
- [x] IntegrationSubscription
- [x] User(githubRepos)
