### ISSUE TITLE
Video Beta

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2742]
After video alpha is in master, here's what's left to go into beta:

- [x] add permissions info screen (navigator.permissions.query({name: 'camera'}).then(console.log))
- [x] handle denied webcam access errors
- [ ] show video during check-in round & logo in av group
- [ ] segment events added #2793

**Comment by jordanh** [comment]
Goal state for this sprint: merged to master and shipped to prod so we can alpha with our team during weekly meetings

**Comment by tayamueller** [comment]
question from [this distributed team leader](https://app.hubspot.com/contacts/3888472/contact/3254151/):

> I also saw that you are integrating video call in parabol, that's nice! Will this be compatible with google meet? All our hardware videoconf tooling is based on that, if it is not integrated with meet we won't be able to use it in our meeting rooms.

**Comment by jordanh** [comment]
Iceboxing for now
