### ISSUE TITLE
Error: Meeting phase already completed

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2745]
https://sentry.io/organizations/parabol/issues/877277361/?project=107196&referrer=github_plugin

```
Error: Meeting phase already completed
  File "app:///graphql/mutations/voteForReflectionGroup.js", line 48, in resolve
    return standardError(new Error('Meeting phase already completed'), {userId: viewerId})

Error: Meeting phase already completed
```

people are voting after the meeting has moved on

AC
- [ ] no error thrown in sentry

Effort: 11

**Comment by jordanh** [comment]
This is interesting. Scrubbing this now. @mattkrick can you please add AC and EE to this? Else, we can close and re-open if we see it a bunch. Your call.

**Comment by mattkrick** [comment]
This also happens for the editReflection mutation

**Comment by jordanh** [comment]
Iceboxing for now
