### ISSUE TITLE
TypeError: Cannot read property 'email' of null

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2749]
https://sentry.io/organizations/parabol/issues/885672625/?project=107196&referrer=github_plugin

```
TypeError: Cannot read property 'email' of null
  at c (./src/universal/components/StandardHubUserMenu.js:30:14)
...
(5 additional frame(s) were not displayed)
```
AC
- [ ] no error thrown in sentry

Effort: 11

no repro known

**Comment by jordanh** [comment]
@mattkrick can you add repro steps, AC, and EE to this?

**Comment by jordanh** [comment]
Scrubbed. Iceboxing
