### ISSUE TITLE
Check-in order only works 3/4 times

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#275]
Check that users are sorted by checkInOrder.
Borked in safari!

**Comment by jordanh** [comment]
I think this has been fixed too, ja?

**Comment by mattkrick** [comment]
Pretty sure. Let's say yes & re-open if not.

**Comment by mattkrick** [comment]
http://stackoverflow.com/questions/4299062/why-wont-safari-5-sort-an-array-of-objects
