### ISSUE TITLE
Jira settings sheet implementation

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2766]
## Issue - Enhancement

Implementing the settings for Jira from [this design](https://www.figma.com/file/aFFwcgvkGJhjwQlMUxB4g3Zt/Integrations?node-id=136%3A6257)

### Acceptance Criteria (optional)
Users can:
   - After clicking Jira you land on integration settings page
   - Can click on Add Project add projects
   - Can see list of linked projects granted to you
   - Can click 3 dots at the top to link more sites
   - Can click 3 dots to remove Jira integration
   - If you are the project lead, you can click 3 dots on project row to remove the project
   - _Optional:_ Can unlink yourself from a project

- **Estimated effort:** 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
closing in favor of simplified design #2773
