### ISSUE TITLE
Connection status on sign-out view

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2768]
I noticed that a teammate will show as connected to the team when they sign out and are sitting on the sign-in screen.

### AC
- Next steps, what should the UX be?
### EE
- 10.5 pts

**Comment by jordanh** [comment]
Removing this from sprint board until AC is set.

**Comment by jordanh** [comment]
This is fun. I'd expect that if they sign out their token is invalidated and a message has gone out the room their teammates are subscripted to that would turn their light gray. @mattkrick is this a bug?

**Comment by mattkrick** [comment]
yes, we should fix this next sprint.

**Comment by jordanh** [comment]
Related to #3259. Scrubbed. Will icebox and let #3259 address this issue as well.
