### ISSUE TITLE
graphql browser CSS trouble

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#277]
## Issue - Bug

I think our latest migration away from `react-look` for `/graphql` may not be completely kosher.

![image](https://cloud.githubusercontent.com/assets/103000/18683262/7752e5ba-7f3d-11e6-9250-16bb13bf6143.png)
- **OS:** OSX
- **Browser:** Chrome
- **Node version:** `v6.4.0`
- **NPM version:** `npm --version`
- **RethinkDB version:** `rethinkdb 2.3.4 (CLANG 7.3.0 (clang-703.0.31))`

**Comment by mattkrick** [comment]
argh! it _was_ working, but then I upgraded Graphiql... lemme do a lil version bump

**Comment by mattkrick** [comment]
still can't really figure out a good way around this.
codemirror, which is the graphiql underlying editor, magically updates the height, width, and left props when it loads. when the css is loaded via helmet, it messes up. If we go back a few commits (but after the one where we extracted the css) we can push the css file down without helmet & it works. however, the latest commits don't even work if you take helmet out of the equation. very strange. i'd say stick this as low priority for now. there is an issue in graphiql that could fix this if it turns into a PR.

**Comment by jordanh** [comment]
Boo on codemirror! Shall we temporarily revert the graphiql version.

Thank you for looking into this.

**Comment by mattkrick** [comment]
We could, but that also means finding a crafty way to load the css.
There are 3 things necessary: 
- the `Graphiql` component cannot be wrapped in a div, otherwise it autocollapses (no clue why)
- the version must be at 0.7.3 (0.7.8 autocollapses)
- the css cannot be loaded via helmet (I think this has to do with a race condition to load the css?)
