### ISSUE TITLE
Add control/dialog in demo

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2771]
I wonder if there’s some missed opportunity when a user hits the ➕ add control to invite team members in the demo:

![Screenshot 2019-04-03 15 16 51](https://user-images.githubusercontent.com/307286/55511634-afd18280-5626-11e9-8d84-bb3182d9b265.png)

### Acceptance Criteria
- UX discussed as a team

### Estimated Effort
- 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Not quite sure what this is referencing. Added agenda item to clarify. Removing from sprint board for now.

**Comment by jordanh** [comment]
After talking, I see this is about inviting folks during the product demo!

**Comment by jordanh** [comment]
Decided during action meeting to first sent segment invite and measure how often this is happening.

**Comment by ackernaut** [comment]
As a stretch goal, I added a conditional CTA for the team invite modal in the demo since I was in that neck of the woods. I still want to open an issue to track interactions with the invite button/modal using segment. Going to close this issue.
![Screenshot 2019-06-06 12 16 45](https://user-images.githubusercontent.com/307286/59052587-00e33a00-8855-11e9-9379-cc9d03f3913c.png)
