### ISSUE TITLE
Retro > Group > Vote > (column headers)

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#2774]
user feedback submission: 

> During a retrospective (S-S-C format), after we enter our reflection cards, when we go to the Group phase, the cards are no longer grouped by "Start, Stop, Continue" which makes it really hard to work through all the reflections and group them. This seems very messy atm."

### Acceptance Criteria (optional)
Users can:
   - Do this
   - Do that
   - Cannot do that

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Dup of #2557
