### ISSUE TITLE
Async Retros: I want to create reflection cards before the meeting

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#2775]
user feedback submission: 

> We were using a Google sheet to run our retrospectives, but it has shown its limits. On the multiple tools I found on the internet, yours looks the most promising. Is there a possibility to prefill some tickets before the retrospective (to avoid forgetting, or to introduce a subject if they are not able to attend the retro). I used to create a Google sheet few days before the retro day so people were able to add stuff before the retro started."

**Comment by jordanh** [comment]
Making this a discussion and removing from sprint board

**Comment by jordanh** [comment]
Closing in favor of #2803 (opened from S.P.A. 11)

**Comment by tayamueller** [comment]
feedback from [this 44-person distributed team leader](https://app.hubspot.com/contacts/3888472/contact/4605201/):

> I tried Parabol and I liked the UX. But our process and the way Parabol implements it, are not compatible: we open a retrospective board right at the start of the sprint, so people can add anonymous comments there as the sprint happens; also vote (and comment would be nice). When we start our retrospective, we just review those items and add action items as we see fit. Once in a while, someone adds something extra during the retrospective.

**Comment by tayamueller** [comment]
feedback from this [12-person distributed team leader](https://app.hubspot.com/contacts/3888472/contact/3254151/):

> We are the first people in my company to work in a distributed manner. We opened a second tech center and half the team is in France, the other in germany. We were using a Google sheet to run our retrospectives, but it has shown its limits. On the multiple tools I found on the internet, yours looks the more promising. Concerning new features, some of my teammates asked me if there is a possibility to prefill some tickets before the retrospective (to avoid forgetting or to introduce a subject if they are not able to attend the retro). I used to create a Google sheet few days before retro day so people were able to add stuff before the retro started.

**Comment by jordanh** [comment]
@ackernaut now that we've got this broken down into some smaller issues, do we want to link them here and close this one?

**Comment by ackernaut** [comment]
Sure, the intent of our design is to address this tension
