### ISSUE TITLE
skip Social Check-In

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#2776]
recent user feedback:

User 1 
> it’d be good to be able to skip the Social Check-In entirely. Note the reason for this in my case was that the project was fresh, the team is already in a good place, etc and it felt redundant to do something like that."

User 2 
> I didn't get any intro to Parabol, but was just pushed into a meeting where we used it. I wasn't really clear on the purpose of the tool. Is it just a tool to get us sharing our feelings? We're all highly trained technical developers so we are often not concerned with anyone's feelings and just want to get things done."

**Comment by ackernaut** [comment]
Revisited in S.P.A. 11, also part of #2803 AC

**Comment by jordanh** [comment]
Making this a discussion

**Comment by jordanh** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/3488551) writes:

> We don’t really find use of the ice breaker style questions, so being able to turn these off would streamline things

**Comment by jordanh** [comment]
Resolved!
