### ISSUE TITLE
Reflection card width updated

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2784]
### Acceptance Criteria
- Reflection cards (including stacks, grids, input controls, etc.) are set to a fixed width of `296px` instead of `320px` ([see guidelines](https://app.getguru.com/card/cBb5rG9i/Task-card-layout))

### Estimated Effort
- 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
i believe this is fixed everywhere
