### ISSUE TITLE
Agenda drawer in team dash

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2785]
### Acceptance Criteria
- The agenda sidebar opens in an elevated drawer on smaller viewports

### Estimated Effort
- 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Issue superseded by newer IA work. Iceboxing
