### ISSUE TITLE
Task column layout

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2786]
### Acceptance Criteria
- Columns fill space allowed, honoring task card min- and max-widths, cards fill column and do not cause horizontal overflow
- Columns container has a min- and max-width based on card min- and max-widths
- Columns overflow horizontally when there isn’t enough space, including when the agenda sidebar/drawer is present
- Columns container is centered once the viewport gets wide
- This column layout is used everywhere: action updates, team dash, my dash, etc.
- [See guidelines](https://app.getguru.com/card/cBb5rG9i/Task-card-layout)

### Estimated Effort
- 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Came up during scrub, iceboxing for now
