### ISSUE TITLE
Left navigation drawer designed

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2787]
### Acceptance Criteria
- Designs supporting a left navigation drawer for dashboard views that can be collapsed

### Estimated Effort
- 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
@ackernaut not sure if this design includes the content or just the swipeability. if it's the latter, we can close this due to #3003

**Comment by ackernaut** [comment]
Well the separate issue is the IA, what to put in the different spaces (left/right drawers, top/bottom bars, etc.) The tension isn’t going away, now that it is a UI affordance we can focus more on the structure, probably a separate issue if it doesn’t exist. I’ll close this when I wrap up the review.
