### ISSUE TITLE
Persisted check-in question

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2789]
Some users have expressed interest in persisting the same check-in prompt for every meeting.

**See comment below** ~Current idea: when the facilitator’s editing the check-in prompt a checkbox appears to persist the question. If they check the box the same question is used in every meeting. They later have the option to edit the prompt again, or uncheck the box. The question would update on the next meeting. Maybe we add a secondary action to the prompt editing mode to generate a new prompt randomly from our set of pre-written prompts.~

### Acceptance Criteria
- **See comment below**
- ~Designs validated~
- ~Implementation issue written~

### Estimated Effort
- 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
### AC
- Tapping the edit icon allows the facilitator to customize the prompt
- The custom prompt persists across meetings
- Tapping the refresh icon cycles through our random prompts
- If the current prompt is custom, tapping the refresh icon replaces it with a random prompt. This resets the meeting to have a random prompt until another custom prompt is added.
- The layout is simple and mobile-friendly: avatar, greeting, prompt, two icon buttons with tooltip

### EE
- 10.5 points

![check-in-update](https://user-images.githubusercontent.com/307286/62501363-2dadc200-b7b0-11e9-8dcf-0dc11bd84d8f.png)

**Comment by jordanh** [comment]
Closing in favor of #3476
