### ISSUE TITLE
Create account link added to Demo designed

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2794]
### Acceptance Criteria
- Design uncertainty 2, showed concept in Figma and validated

### Estimated Effort
- 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))​

**Comment by ackernaut** [comment]
First round of ideas:
- Add a floating action button “Create Free Account” over the bottom bar
- Replace (+) [add control] in the top right with a text button “Create Free Account”
- Add a button in the left sidebar where the logo is

[See Figma for nuanced comments](https://www.figma.com/file/0lOTlvsj87GBFFzgee9OkVWi?node-id=121%3A5519&utm_campaign=team&utm_source=slack&utm_medium=message&utm_content=file_comment#6094619) — follow the comment trail! (This one’s in messy, early stage)

**Comment by ackernaut** [comment]
[Target IA](https://www.figma.com/file/0lOTlvsj87GBFFzgee9OkVWi?node-id=163%3A542&utm_campaign=team&utm_source=slack&utm_medium=message&utm_content=file_comment#6326026) and [iterative IA](https://www.figma.com/file/0lOTlvsj87GBFFzgee9OkVWi?node-id=163%3A544&utm_campaign=team&utm_source=slack&utm_medium=message&utm_content=file_comment#6326032) for “Create Free Account” button in Retro Demo
#### Iterative IA
![Iterative IA](https://user-images.githubusercontent.com/307286/57245353-487d6880-7000-11e9-8af8-6d8e572ae0d9.png)
#### Target IA
![Target IA](https://user-images.githubusercontent.com/307286/57245354-487d6880-7000-11e9-962e-2fad83eb53d6.png)

**Comment by ackernaut** [comment]
[Implementation issue created #2868](https://github.com/ParabolInc/action/issues/2868)
