### ISSUE TITLE
Update landing page header

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2798]
The header for the landing page should be:
- features
- pricing
- sign-in
- Octocat (A/B test with Open-source)
- Try Demo CTA

**Comment by jordanh** [comment]
Going to reduce the scope on this one in order to make forward progress.

New AC:
- New header:
   - Pricing
   - Sign-In
   - Open-source (A/B with Octocat)
   - Sign-in
   - Try Demo CTA

What's missing? Features! Going to defer adding this to the header until we have the page
