### ISSUE TITLE
Draft content for solutions page and sub-pages

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2799]
AC
- a page exists with 2000 words for each of the following
  - [ ] weekly check-in meetings
  - [ ] non-technical teams
  - [ ] distributed teams

- [ ] a /solutions page that includes links to all pages above exists
- [ ] the footer includes a link to /solutions

Effort: 13 points

**Comment by jordanh** [comment]
Edited!

**Comment by jordanh** [comment]
Also iceboxing this
