### ISSUE TITLE
Add favicon and Apple touch icons

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#28]
Mission summary
=============
No web application is complete without the ubiquitous favicon; help give Action a little more personality by integrating in our graphical assets.

Estimated Size
===========
1 point ~ less than a single day

Mission Spec
==========
[Read mission spec here](https://goo.gl/wO1eoa)

Design assets
===========
[Link to assets on Dropbox](https://www.dropbox.com/sh/wyb227i909zbhgk/AADPFO6GaK24YlIibdD2V2bca?dl=0)

**Comment by ackernaut** [comment]
This looks good!

**Comment by awmichel** [comment]
I'm interested in working on this for 1 point! PR incoming!

**Comment by jordanh** [comment]
Sold! @awmichel you've got it. Please create a branch `favicon-#28` and we look forward to the PR! Let us know here if we can answer any questions or join our [Slack community](slackin.parabol.co).
