### ISSUE TITLE
Draft /features landing page

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2801]
A /features page exists with the following:
- [ ] header text of ~100 words saying why it's the best
- [ ] Infosec Approved
  - FOSS (auditable!)
  - business friendly TOS
  - help passing infosec. we've already passed at {List of Logos}
- [ ] Integrates with your team's tools
  - Jira
  - Confluence
  - Slack
  - GitHub
- [ ] Retros for all kinda of teams (I think we were unsure of this one?)
- [ ] Meeting Summaries and follow-up
  - Meeting summaries direct to your inbox
  - Parabol is the only tool that has check-in meetings to complement retros

Effort: 13

**Comment by mattkrick** [comment]
This slack clone has good stuff: https://flock.com/usecases/engineering/

**Comment by jordanh** [comment]
Gosh, I hadn't seen that link until now. I like the design. I bet we could handle that ourselves.

**Comment by jordanh** [comment]
I could use a review on this, so we can iterate @mattkrick @ackernaut @tayamueller: https://docs.google.com/document/d/1Uxz8SdrMGmH6-C6D3JVXdN-JU2IUTahtO3ppQlRezJ8/edit

**Comment by jordanh** [comment]
Adjusting AC:
- a *draft* of the above
- subsequent issue or task created to cover its implementation
