### ISSUE TITLE
Design meeting timer in footer

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2804]
Allowing users to run an async meeting introduces the need to be explicit about the time remaining in phases. A portion of the UI needs to be reserved to display the time remaining in a phase.

The way we display this time may vary if it's a sync meeting or an async meeting. Or, maybe not. Maybe it's always xx**h** yy**m** zz**s** 

AC
- [ ] IA of where to display timer
- [ ] how time is displayed
- [ ] how time is set and reset
- [ ] written thoughts on when notifications are sent, and how
- [ ] one or more implementation issue(s)

**Design uncertainty:** 3

Effort: 12 points

**Comment by ackernaut** [comment]
[First round of sketches in FIgma](https://www.figma.com/file/CXR8YpgiZyC7XOStCUYQNILv/Timebox?node-id=0%3A1)

**Comment by ackernaut** [comment]
Drafted an implementation issue for a timer component #2871

**Comment by ackernaut** [comment]
Drafted an implementation issue for a phase date timebox affordance #2872

**Comment by ackernaut** [comment]
Moving to review column

**Comment by jordanh** [comment]
See validation questions on each implementation issue

**Comment by ackernaut** [comment]
[Prototype v2 in Figma](https://www.figma.com/proto/CXR8YpgiZyC7XOStCUYQNILv/Timebox?node-id=101%3A7029&viewport=260%2C213%2C0.5&scaling=scale-down)
