### ISSUE TITLE
make loading code/data seamless

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2811]
we got rid of the flashing ducks, which makes the app feel a little nicer.
Unfortunately, the spinner still flickers between loading code & loading data.
this is fixed by using `useLoadingDelay`, but we need to deploy it everywhere, namely dashboards.

AC
- [ ] `useLoadingDelay` is used on all menus
- [ ] also used on team dash
- [ ] and my dash tasks

Effort: 11 points

**Comment by jordanh** [comment]
Scrubbed. Added milestone

**Comment by jordanh** [comment]
Scrubbed. Iceboxing.

Will reopen a similar issue after Dashboard IA refactor
