### ISSUE TITLE
mock list loader

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2820]
we'll eventually need a loader that isn't a spinner, but rather a list of items.

We can use something like this:

0% {
    background-position: -450px 0px;
}

100% {
    background-position: 450px 0px;
}
linear-gradient(to right, rgb(238, 238, 238) 8%, rgb(221, 221, 221) 18%, rgb(238, 238, 238) 33%)

**Comment by jordanh** [comment]
Very true. Will icebox for now
