### ISSUE TITLE
Slack integration notifications refactored

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2839]
## Issue - Enhancement

Slack have deprecated their team token API, requiring us to reimplement if we want to be able to do more stuff.

### Acceptance Criteria (optional)
Users can:
   - Integrate against Slack using new auth API
   - Configure a set of team events that are read-only if you didn't set them up, editable otherwise
   - Configure a set of user events (e.g. re-syndicating our Notifications feed on task assignment, etc.)
   - Meeting notifications work the same as before

- **Estimated effort:** 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
stuck on designs for the slack integration row (notification types & channels)

**Comment by ackernaut** [comment]
@mattkrick once your ready for UI polish, should I do that on PR #2901 ?

**Comment by mattkrick** [comment]
sure, lemme prep it for ya, should be ready by monday
