### ISSUE TITLE
Slack integration configuration design updated

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2841]
### Acceptance Criteria (optional)
Users can:
   - Add Slack integration
   - Configure a set of Team notifications as a set of checkboxes
      - Pick one or more channels to send team notifications
      - If they added Slack, notifications are editable else read only
   - Configure a set of Personal notifications preferences
      - First is sending Parabol notifications to a Parabol app channel

- **Estimated effort:** 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
[First round of sketches in Figma](https://www.figma.com/file/aFFwcgvkGJhjwQlMUxB4g3Zt?node-id=444%3A7&utm_campaign=team&utm_source=slack&utm_medium=message&utm_content=file_comment#6257610)

**Comment by ackernaut** [comment]
Got a draft of an implementation issue (#2869) and more views [in Figma](https://www.figma.com/file/aFFwcgvkGJhjwQlMUxB4g3Zt/Integrations?node-id=444%3A0), sending to review column

**Comment by ackernaut** [comment]
I’m still wondering if the personal notifications are well-validated with our users. Has anybody asked for this? How could we get a show of hands of folks who would use this? Is this just a marginal value that is a bit of UX utility vs sales-driving value? (even so, it’s probably ok to chip away at marginal UX utility debt)

**Comment by jordanh** [comment]
See also: specific validation questions on the implementation issues

**Comment by ackernaut** [comment]
This is done, [see target in Figma](https://www.figma.com/file/aFFwcgvkGJhjwQlMUxB4g3Zt?node-id=493%3A4&utm_campaign=team&utm_source=slack&utm_medium=message&utm_content=file_comment#6855842)
