### ISSUE TITLE
Add to agenda from Retro Discuss phase

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2845]
Sometimes the next step when discussing a theme in a retro meeting may be to add it to the agenda of the next check-in meeting. Usage of this affordance could show more attachment to both meeting types.

### Acceptance Criteria
- Discovered next steps, if any

### Estimated Effort
- 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
I agree with this @ackernaut. Let us not forget. But also, let us `icebox` it
