### ISSUE TITLE
Project card overflow design

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#285]
## Issue - Bug

@ackernaut, just doing a little playing around on master this morning. I see this:

![image](https://cloud.githubusercontent.com/assets/103000/18787927/f30e34a2-8172-11e6-9838-51a02602f6e8.png)

What should our overflow strategy be? Should we grow the cards vertically? Make them scrollable? I'm leaning a bit toward the former...

- **OS:** OSX
- **Browser:** Chrome

**Comment by ackernaut** [comment]
I had tried this [https://github.com/andreypopp/react-textarea-autosize](https://github.com/andreypopp/react-textarea-autosize) early on, but I’m wondering if it was conflicting with `redux-form` or another library upon implementation? @mattkrick is that the case?

**Comment by ackernaut** [comment]
I'm trying it again and it seems to work, I'll test as well as I can on a small side branch.
