### ISSUE TITLE
Error: InvalidStateError: Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not...

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2853]
https://sentry.io/organizations/parabol/issues/970241171/?project=107196&referrer=github_plugin

```
Error: InvalidStateError: Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'

InvalidStateError: Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'
```

AC
- [ ] graceful fallback designed to catch this error (probably the error we get when someone is behind a NAT?)

Effort: 11 points

**Comment by jordanh** [comment]
Scrubbed. Added to project, added labels and milestone.

**Comment by jordanh** [comment]
Scrubbed. Iceboxing for now.
