### ISSUE TITLE
Password recovery needs link back to sign-in form

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2857]
This confirmation (after sending an email to reset password) provides a link back to the password recovery, but not to sign in again. If I’ve reset my password, then I have to find the sign-in form again.
#### Password reset confirmation
![Screenshot 2019-05-01 11 25 37](https://user-images.githubusercontent.com/307286/57028175-00c39f00-6c04-11e9-89b5-acbcd20ed423.png)
#### This is all auth0 gives me when resetting the password
![Screenshot 2019-05-01 11 27 28](https://user-images.githubusercontent.com/307286/57028231-25b81200-6c04-11e9-9a52-3399b68d2521.png)

### AC
- Provide a simple way to go back to the sign-in form and try the new password
### EE
- 10.5 pts

**Comment by jordanh** [comment]
Adjusting priority of this one cause it's easy and important
