### ISSUE TITLE
Android textarea z-index

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2859]
During a Retro, on Android, I see the textarea is probably above the side drawer backdrop when open:

![Screenshot_20190501-121842](https://user-images.githubusercontent.com/307286/57033022-5eaab380-6c11-11e9-9f1b-4f5d82fd4251.png)

### Acceptance Criteria
- Triaged and fixed textarea z-index/elevation

### Estimated Effort
- 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
This maybe was fixed? Will icebox until we noticed again 🤷‍♂
