### ISSUE TITLE
Mobile reflect layout, center reflection group dialog

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2860]
For consideration as we improve New Meeting mobile-first layouts. When reflecting the group dialog centers over the width of the prompt columns, whereas a dialog with backdrop should always max out at viewport width and center according.

May be part of the effort in #2830 

#### Group dialog is open, but over the center column (of 3)
![Screenshot_20190501-113757](https://user-images.githubusercontent.com/307286/57033553-cf9e9b00-6c12-11e9-8856-57a91051b314.png)

### Acceptance Criteria
- Retro dialogs have a max-width of the viewport (for backdrop, centering dialog, etc.)

### Estimated Effort
- 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Already fixed
