### ISSUE TITLE
Add all groups to agenda in retro

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2862]
## Issue - Enhancement

[A user](https://app.hubspot.com/contacts/3888472/contact/3469901) writes:

> We were wondering why groups that don't get voted on don't show up on the side panel.  We had a retro with a lot of reflections today so some of the groups didn't get votes but the team still wanted to talk about them.  

Ideas to resolve this:

   A. Make it configurable at the start of the meeting
   B. Just add all the groups, and show they got zero votes
   C. Add a control to the bottom of the meeting to "add 0-vote groups"

Others?

My vote is probably just to start with B.

**Comment by ackernaut** [comment]
Option B probably makes sense, and then the summary gets them all too? solving #2741

**Comment by jordanh** [comment]
[Another user](https://app.hubspot.com/contacts/3888472/contact/2358351) writes:

> Thanks for reaching out, the biggest detractor for the teams was the voting which reduced the topics down to a max of 5 if I'm not mistaken. That max topic limit really was a downer for the teams.

This may or may not be directly related. Asking user for clarification.

**Comment by jordanh** [comment]
See also: #2503, consider adding to AC to be able to include all reflections in exported CSV.

**Comment by jordanh** [comment]
See also: #2862, show all groups during discussion, even those that do not receive votes

**Comment by jordanh** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/1377251) writes:

> Even if grouped topics are not upvoted they should still be listed in the discussion. Just mark them as 0 upvotes, sure, but if they were typed I want to see them and have the option for bringing them up for discussion. Currently they just disappear - which makes some of us upvote the ones that we feel won't get upvoted "just in case", which is not helpful for the facilitator to help the team focus on the really important stuff.

**Comment by jordanh** [comment]
I think we have enough validation around the AC here.

## Acceptance criteria:

When performing a retrospective:
- Include all grouped topics in retrospective agenda, showing they got zero votes

## Estimated effort: 10.5 points

**Comment by ackernaut** [comment]
We just shipped v4.9.0 which implemented the solution for this issue, but got this feedback today (assuming they haven’t ran another retro yet) from user. It’s interesting to hear how they compensated for the UX:
>One thing that I feel (and have received feedback on)  is that some items are now lost in the weeds if they are not voted on and grouped with other tickets. To manually fix this, we now read out every ticket before starting grouping, to both clarify meaning and ensure all voices are heard. Not sure of the best way to productize that, but thought it would be a good thing to note.
