### ISSUE TITLE
Task card link editor URL error message UX

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2864]
In the task card link editor menu, the URL error message layout is wonky, and perhaps a little too sensitive?

[http://recordit.co/Hi0Py9iCFm](http://recordit.co/Hi0Py9iCFm)

### Acceptance Criteria
- Error message is a block under input, not changing input width, but perhaps height of menu instead
- Bonus points for perhaps throttling the error message somehow

### Estimated Effort
- 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Fixed the layout, iceboxing sensitivity portion of this
