### ISSUE TITLE
Card integration menu width when searching

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2865]
The variance in the card integration menu width when searching doesn’t feel polished.

[http://recordit.co/M4j2RNCmUB](http://recordit.co/M4j2RNCmUB)

### Acceptance Criteria
- Picked a UI pattern and implemented (probably fixed width with ellipsis on long menu options)

### Estimated Effort
- 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Iceboxing
