### ISSUE TITLE
Implement personal Slack notifications [WIP]

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2869]
TBD as we review and finalize designs (#2841) for a first version:

### Acceptance Criteria
- I can opt in/out of 2 notifications:
  - When somebody assigns me a task
  - When somebody mentions me in a task
- TBD my personal Slack notifications are configured per team, per org, or single preferred:
  - Per team: I can opt in/out per team either as an item under my notifications settings, or per team settings view
  - Per org: I can opt in/out per org (add an org, point it to a Slack account, can do again) as an item under my notification settings
  - Single preferred: I can opt in/out and send that to a single preferred Slack account/channel for all teams/orgs
- TBD these are configured in a sub view of Notifications or Team Settings

### Estimated Effort
- 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Everything that is old, is new again. We recently discussed this. Iceboxing for now, but good chance like the Terminator, "[It'll] be back!"
