### ISSUE TITLE
Action Meeting bug - can't start meeting

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#2878]
## Issue - Bug

from [this Pro Billing Leader](https://app.hubspot.com/contacts/3888472/contact/1305601/):

2019.05.06:
> Hi, when starting an action meeting it jumps to the summary page where the social check in is not selected like before. When selecting social check in manually it shows no question and the option to "rejoin facilitator" this goes back to the summary page. This error lasts a week now and happens at both teams we use. Can you fix this?

Permission to log in granted; unable to reproduce issue. No action taken, but bug seems to have cleared for 1 team anyway:

2019.05.09:
> The customer success team works fine now. But our other team carpentry does not. Even clearing browser cache does not help. All our teammates tried but they were all not able to start it. When you wrote me the last mail, you did not abort the meeting. The meeting was still in progress when I checked it. I was able to end it and then start a new meeting as normal. But well, then please do that trick again. I attached a video on how it looks like on our side.

[[see video](https://parabol.slack.com/archives/C4JAUUZ9P/p1557421173001900)]

### Acceptance Criteria (optional)
Users can:
   - Do this
   - Do that
   - Cannot do that

**Comment by carsten-z** [comment]
moving this back to Prioritize would be nice as we currently can't start a meeting at this team.

**Comment by jordanh** [comment]
@carsten-z we've got a permanent fix for what you and your team are running into. We're testing it right now and hope to get it deployed in the next day or 2. We'll keep you posted!

**Comment by mattkrick** [comment]
fixed! pushed live today
