### ISSUE TITLE
Migration needed for Projects.teamId

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#288]
## Issue - Bug

After the merge of #287, it looks like we need a new migration to add `teamId` and an index for that field. Old projects are not showing up after merging this pull request.

- **Estimated effort:** 1 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
I'm on it!

**Comment by mattkrick** [comment]
Can this be closed?

**Comment by jordanh** [comment]
You betcha!
