### ISSUE TITLE
Remove From Team / Leave Team / Remove From Org broken

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#2880]
## Issue - Bug

submitted by [this 12-person team leader](https://app.hubspot.com/contacts/3888472/contact/3254151/):

> We've been using parabol for 3 months or something and we definitely love it. I have a pretty annoying bug though, that I cannot remove someone from a team. **That's quite an issue because **people that are not in the team anymore are receiving all tickets and actions**** even though they are not part of the team anymore. Easy to reproduce: just click on the avatar of someone on the top right, click "Remove ... from team", on the confirmation window click on "Remove ...". Nothing happens here, the guy is still there and there is no network call in the debug console so the issue probably comes from your frontend.

[note: "Leave Team" from dashboard and "Remove from Org" under Settings are similarly not working]

### Acceptance Criteria (optional)
Users can:
   - Do this
   - Do that
   - Cannot do that

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
live in prod at v3.10.1
