### ISSUE TITLE
Implement UI details for Action meeting

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2886]
### Acceptance Criteria
- [ ] “Social Check-In” has top bar heading
- [ ] “Team Agenda” has top bar heading
#### If First/Last Call stages still exist
- [ ] Add “Team Agenda” top bar heading
- [ ] Hint text has hint type styles

### Estimated Effort
- 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Scrubbed, iceboxing for now. Will be superceded by some more specific issues
