### ISSUE TITLE
Remove First/Last Call stages

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2887]
### Background

The First Call view was intended to allow pause in a sync meeting for the addition of agenda items, especially if folks have a habit of adding them last minute.

The Last Call view was intended to allow pause in a sync meeting to add those “oh, one more thing” agenda items and not immediately end the meeting.

### Acceptance Criteria
Design uncertainty 1: we can describe changes with written criteria
- Removed First Call
- Last stage of Updates navigates to first agenda item of Team Agenda
- Last state of Team Agenda has a centered “End Meeting” control
- *Idea*: After pressing “End Meeting” in the bottom bar, the facilitator sees a dialog “Are you sure?” with a tip to ask the team to add any additional agenda items

### Estimated Effort
- 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Scrubbed, iceboxing for now
