### ISSUE TITLE
Action meeting refactor task grid layout bug

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2889]
## Issue - Bug

Repro steps:

1. Create 4ish tasks on an agenda item during an action meeting—enough to fill the full horizontal width
2. See this:

![A4uiidYk7b](https://user-images.githubusercontent.com/103000/57898247-d7b72700-781d-11e9-9fc6-e12eb8153c60.gif)

- **OS:** macOS
- **Browser:** Chrome
- **Estimated effort:** 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### Acceptance Criteria (optional)
Users can:
   - Enter text on the rightmost card having the width remain constant

**Comment by ackernaut** [comment]
See comments in #2891
