### ISSUE TITLE
unable to end Action meeting

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#2893]
## Issue - Bug

as reported by [this Free user](https://app.hubspot.com/contacts/3888472/contact/2488551/):

> We're unable to end the meeting that we held last Monday. When we exited the meeting, the list still remains open. Is there anything that we can do to force it to end so that we can move on? I have taken three screenshots for you. Essentially when you click end meeting." [see Slack correspondence]

- **OS:** macOS / Linux / Windows / ?
- **Browser:** Chrome / Safari / Lynx / ? + version
- **Node version:** `node --version`
- **NPM version:** `npm --version`
- **RethinkDB version:** `rethinkdb --version`
- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### Acceptance Criteria (optional)
Users can:
   - Do this
   - Do that
   - Cannot do that

**Comment by jordanh** [comment]
Scrubbed. Checking to see if this is still an issue...

**Comment by jordanh** [comment]
No longer an issue, closing
