### ISSUE TITLE
Agenda uses task card grid

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2895]
### Acceptance Criteria
- Follows [grid criteria](https://app.getguru.com/card/cBb5rG9i/Task-card-layout)
- The grid is 1-4 cards in Agenda view, depending on viewport space (I’m open to increasing the number for large displays, 6-8 is probably the max if the sidebars are closed)
- The grid is centered horizontally
- The grid has outer margins that match the grid gutter
- The grid does not cause horizontal overflow for the main content area
- The grid updates when sidebar is opened/closed
- The grid updates when the window is resized (can use throttling)
- Note: the grid behavior is probably similar to the Discuss task card grid, it fills the space allowed (I can see 1-3 cols depending on viewport)

### Estimated Effort
- 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
@ackernaut was this implemented already? Or, am I mistaken?

**Comment by ackernaut** [comment]
Not implemented, still a Thing™

**Comment by ackernaut** [comment]
Iceboxing for now, this may go away if we use a discussion thread UI for agenda items.
