### ISSUE TITLE
Mobile timeline horizontal scroll bug

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2898]
## Issue - Bug

See: https://youtu.be/8Hh7wZUleEo

- **OS:** iOS
- **Browser:** Safari
- **Estimated effort:** 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### Acceptance Criteria (optional)
Users can:
   - Scroll horizontally without covering leftnav

**Comment by jordanh** [comment]
I'm guessing we'll do some IA changes before we fix this. But, wanted to capture.

**Comment by ackernaut** [comment]
Yes, we’re definitely in need of some mobile-first/friendly IA enhancements. As for this particular scroll behavior, it may be better since the refactor. Can you try using staging on your phone?

**Comment by jordanh** [comment]
Somewhere this got fixed along the way. Closing.
