### ISSUE TITLE
Name Update Fails via Settings

### ISSUE THREAD

**Issue by faludi** [ParabolInc/action#290]
When I try to update my name under My Setttings (https://action-staging.parabol.co/me/settings) it does not take effect. Name remains unchanged. Tried this under Firefox and Chrome, same (non-)results.

**Comment by jordanh** [comment]
It looks like the name is being updated in the database – any projects appearing on a dashboard update with the new name. It looks like it's actually just it's just the UserHub component that's not reacting to the change...

**Comment by mattkrick** [comment]
I'll dig into this during the Me Dashboard sprint, should be resolved in the next day or 2

**Comment by mattkrick** [comment]
fixed in 3f5b3f5 on the me-dash-dos branch, will merge this branch as soon as we knock off a few more things. thank you _very_ much @faludi!
