### ISSUE TITLE
Agenda autoscroll/overflow behaviors regression

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2900]
When moving the agenda navigation to the new meeting sidebar, the overflow behaviors are not the same per design of the new meeting sidebar. It took a little TLC to get these polished behaviors so I wanted to capture them to see if we can reimplement. 

The TL;DR of the behaviors we’re losing:

- The input is always visible, becoming pinned to the bottom for a long list
- When adding a new item to the long list, it scrolls into view
- When navigating the list it automatically scrolls so users can see what’s next

After the refactor:

- The input gets buried in the overflow, not visible
- You don’t see what your typing until the input comes into view (I think this is a native browser behavior) but not bad
- The agenda does not autoscroll

#### Behaviors after refactor

![agenda-new-meeting](https://user-images.githubusercontent.com/307286/58191611-8cb96b80-7c84-11e9-96ff-bbfe0bc5ab7c.gif)

#### Team dashboard, before refactor

![agenda-team-dash](https://user-images.githubusercontent.com/307286/58191623-94791000-7c84-11e9-88d1-60f1d2612a57.gif)

#### Action lobby, before refactor

![agenda-lobby](https://user-images.githubusercontent.com/307286/58191631-99d65a80-7c84-11e9-9cb8-4551e0a3c9c2.gif)

#### Action team agenda nav, before refactor

![agenda-items-nav](https://user-images.githubusercontent.com/307286/58191644-a0fd6880-7c84-11e9-9a18-4f5241b19067.gif)

### Acceptance Criteria
- Decide if we want a new design, or rework what we had (I think it can mostly be achieved through flex and overflow behaviors, so mostly styles, see comment below)
- Flip this into an implementation issue and the effort is probably the same

### Estimated Effort
- 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
I think I can probably crack this one, but not sure if we will before we ship the Action refactor. So, I wanted to capture those behaviors in production before they go away!! :) I like what we had, and would probably want to reimplement in the short term. In the long term I think some changes may be coming to this sidebar per IA updates.

**Comment by jordanh** [comment]
On #2992
