### ISSUE TITLE
Action prompt design updated

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2905]
The phase views for the Action meeting were designed some time ago, we’ve since been moving to an updated meeting IA. The basic needs:
- The prompts don’t live in the top bar; that space is for controls, way finding, should be small as necessary, is global to all phases, etc.
- The prompts follow a consistent IA as possible given the UX of each phase view
- Stretch goal: considerations for video, updated avatar group, updated left nav

### Acceptance Criteria
- Design uncertainty level 2: updated hi-fi concepts in Figma
- Proposed design specs
- Specs interpreted as implementation issue

### Estimated Effort
- 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
I think this is still a thing. However, came up as stale during scrub. Iceboxing for now to encourage contemplating whether the tension exists and revised AC in the form of a new issue.
