### ISSUE TITLE
Designed mobile snap-to column UI pattern

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2908]
A common pattern for mobile viewports is to center 1 column at a time. Typical behaviors:
- The column snaps into place
- Sometimes the left/right side bleeds into view by design, other times there is a clean gutter by design
- Users can gesture, swiping left/right to see columns
- Sometimes there are dot indicators for navigation, way finding
- Sometimes there are tabs, tapping taps jumps to the respective column

This could be used for various UX cases:
- Task card columns (Team Kanban, User Kanban, Action Updates)
- Could be used to navigate Retro phases (Reflect, Group, Discuss, etc.)

### Acceptance Criteria
- Design uncertainty level 2: concepts show various states, options of UI pattern
- Implementation issue written

### Estimated Effort
- 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Did we maybe do this? Not sure what "snap into place" means exactly. Came up during scrub. Iceboxing for now.
