### ISSUE TITLE
Mobile browser viewport height

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2909]
Chrome for mobile treats `100vh` (100 view height units) as the visible area including the browser top bar. So initially the browser top bar is in view, and the bottom `56px` (Google MD bar height) is not in view. Consequently, that is the height of our bottom bar for the meeting and it is perfectly out of view. Once you find the bottom bar and start using it, it tends to stay in view as the browser top bar stays scrolled away.

#### Before scroll, hidden meeting bottom bar

![Screenshot_20190523-114712](https://user-images.githubusercontent.com/307286/58271374-8644f580-7d51-11e9-80cc-a58687d18eb2.png)

#### After scroll, meeting bottom bar showing

![Screenshot_20190523-114726](https://user-images.githubusercontent.com/307286/58271383-8c3ad680-7d51-11e9-9074-fa263cdb2381.png)

### Acceptance Criteria
- Researched and implemented a reliable fix:
  - Examples: using [this](https://dev.to/peiche/100vh-behavior-on-chrome-2hm8) or maybe a root container using position (fixed to the viewport, updating on what’s available)
- Ideally
  - The fix needs to be progressive (not the default for all devices)
  - The fix should work for various mobile browsers (Chrome, Safari, Firefox)
  - Works when changing views, without or without browser bar showing

### Estimated Effort
- 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Not sure if this is still a thing. Scrubbed. Iceboxing.
