### ISSUE TITLE
Video fails to start on OSX Safari

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2911]
## Issue - Bug

This might not be a surprise. Just opening this to track.

Repro steps:

1. Navigate to a meeting lobby
2. Add video
3. Note perms are not asked for, avatar does not start moving

- **OS:** macOS
- **Browser:** Safari
- **Estimated effort:** 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### Acceptance Criteria (optional)
Users can:
   - Start video on Safari

**Comment by jordanh** [comment]
May be related to #2791

**Comment by mattkrick** [comment]
dupe of #2791
