### ISSUE TITLE
DB scrubbed for pro orgs w/o Stripe subscriptions

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2912]
## Issue - Bug

Determine if we have a bug preventing Parabol from being paid, or, if we need to scope an enhancement that let's us know when a user's payment information cannot be used to pay us.

### Acceptance Criteria (optional)
Clean up manual downgrades:
  - downgrade mutation run on list of folks in https://app.hubspot.com/contacts/3888472/lists/69 and remove them from the list when done

Root cause determined:
   - Why is `stripeScriptionId` `=` `null` on the `Organization` record when the `tier` `=` `pro`?

Issue opened:
  - To remediate root cause

Estimated Effort: 11 points

**Comment by mattkrick** [comment]
- downgraded all (1 person) manually that existed in the hubspot list
- created PR #2935 to address the root cause
- created issue #2936 to handle affected users
