### ISSUE TITLE
webcam light stays on after end meeting

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2917]
AC
- [ ] when a meeting is ended, my webcam feed should end & my webcam "on" light should turn off

Effort: 11 points

**Comment by ackernaut** [comment]
Should video/audio stay on for the browser summary?

**Comment by jordanh** [comment]
Scrubbed. Milestone added.

**Comment by jordanh** [comment]
@ackernaut when the camera is not in use, the video should turn off. So, it should only stay on in the summary if the summary still allows video...

**Comment by jordanh** [comment]
Still a thing. Iceboxing for now.
