### ISSUE TITLE
Implement timer

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2922]
Depends on outcome of #2804 (see [prototype v2](https://www.figma.com/proto/CXR8YpgiZyC7XOStCUYQNILv/Timebox?node-id=101%3A7029&viewport=260%2C213%2C0.5&scaling=scale-down)) which is being validated

This is meant to share UI patterns (toggle, menu, countdown snackbar) with timebox #2923 

#### Shared with timebox
- Menu toggle control is in bottom bar for facilitator
- Menu toggle label changes to match the mode “Timebox” or “Timer”
  - The toggle label stays in that mode until the running timer/timebox ends
- TBD heuristic to set the default mode (e.g. 3+ meeting viewers = timer, 1-2 meeting viewers = “Timebox”)
- The countdown snackbar (mins for timer, days/hours/mins for timebox) displays to everybody
- The facilitator can tap the countdown snackbar to toggle the menu, just like the bottom control
- When the menu is open and no timer/timebox is running, user can toggle the mode
- The running timer/timebox is broadcast to all participants via countdown snackbar
#### Timer functions
- Facilitator can pick time in mins for countdown
  - The default time is the time last picked for that phase if in phase history or our Parabol default (what we think is best until we know more better)
  - Time values for timer options use format `m` and `s` (e.g `30s` or `1m 30s` or `5m`)
- Facilitator can start timer
- Countdown snackbar shows w/ mins and secs remaining
  - Time displayed updates every second (e.g `30s` or `1m 30s`)
- Facilitator can reopen menu to add time to countdown via selector
  - Facilitator can toggle “Timer” via control in bottom or by tapping the countdown
- Facilitator can stop timer
### Estimated Effort
- 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Consider:
   - Opening a separate issue for sound

**Comment by jordanh** [comment]
Feedback [from users](https://app.hubspot.com/contacts/3888472/company/1709302309):
   - Timer value needs units (e.g. "15m" or "1h 15m")—timebox had units but timer design did not

**Comment by ackernaut** [comment]
[Prototype v2 in Figma](https://www.figma.com/proto/CXR8YpgiZyC7XOStCUYQNILv/Timebox?node-id=101%3A7029&viewport=260%2C213%2C0.5&scaling=scale-down)
