### ISSUE TITLE
Done cards don't make it to archive after action meeting

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2934]
## Issue - Bug

I noticed after running an action meeting on v3.11.2 and v3.12.0 that cards in the done column receive the `#archived` text in their content area, but don't actually get archived.

Repro steps:

1. Add 3 tasks to done column
2. Run action meeting
3. Note behavior occurs, as described above

### Acceptance Criteria (optional)
Tasks in Done column are archived after action meeting is run or #archived typed into content area of cards and saved

**Comment by jordanh** [comment]
I could have sworn this was a dupe of something @ackernaut had found, but I couldn't find it.

**Comment by ackernaut** [comment]
I think this may be a race condition, try tapping through to the team dashboard quickly once the summary appears in browser.

**Comment by ackernaut** [comment]
Also, I don’t recall creating an issue because I thought it was marked as fixed, so thanks for capturing!
