### ISSUE TITLE
Can’t initialize database after v3.11.2

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2939]
I deleted my local database in order to create a new copy in a state before the latest Slack migration, so that I could integrate with Slack then migrate on [this branch/PR](#2901 ) and see if the old Slack integration still works. I can’t get the app to run with the initial state of the database.

The only time I’ve been able to run master and branches caught up with master was to check out `v3.11.2` then run `git bisect` to step through the commits to see where it breaks. Well it went all the way to the latest commit and was working.

If I check out `v3.11.2` and get my database unstuck, then try checking out master and migrating up, it doesn’t work.

### Acceptance Criteria
- Triage potential issue with initial database state between `v3.11.2` [commit](https://github.com/ParabolInc/action/commit/47ecb21877d57125b49050ce35fb45a50862a7a4) and latest on master at this [commit](https://github.com/ParabolInc/action/commit/4af84cf3b4de942c14e254b929e35b5138cf257f)

### Estimated Effort
- 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
error message?

**Comment by ackernaut** [comment]
Local server console:
```
Error: Invalid document ID at handleGraphQLTrebuchetRequest (action/src/server/graphql/handleGraphQLTrebuchetRequest.ts:45:17)
```

**Comment by jordanh** [comment]
Is the resolution for this one to run `yarn postdeploy`? If so, we should also update the `README`...

**Comment by mattkrick** [comment]
yarn postdeploy no longer necessary. we now just send the full payload in dev
