### ISSUE TITLE
Get into the meeting with just a link

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2949]
## Issue - Enhancement

This tension keeps recurring so I'm opening a newer issue to track (related: #1722 and #2391). 

I believe the root of the tension is people want to drop a link into an email or Slack, vs. digging up everybody's email and relying in them to click a unique link.

Here's [a quote from a user](https://app.hubspot.com/contacts/3888472/contact/4804901):

> The invitation process was clunky for me. I would have much preferred to be able to send a link out rather than have to scrap through all my teammate's emails. The meeting invite email didn't just let them in. If I had external parties, that would make it challenging since I wouldn't want them to be apart of all our retros 

### Acceptance Criteria (optional)
This discussion is resolved when we have a design issue we can explore

- **Estimated effort:** 15 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
I think it is ok if the link makes the user enter their email and a password.

I think it's also ok if the facilitator is asked if so and so is able to join the meeting. Or, offer a toggle that allows anybody to join.

**Comment by ackernaut** [comment]
I think we’ve decided next steps with #2959 which needs to be prioritized? Can close this?
