### ISSUE TITLE
Client exception when receiving notification from Retro summary

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2955]
## Issue - Bug

Repro steps:

1. Log in as User A and User B
2. Smoke test retro, leaving User B on Retro summary
3. Navigate User A to Task Dashboard
4. Create Task @mentioning User B
5. As User B, click on toast to see notification
6. See error

- **OS:** macOS
- **Browser:** Chrome
- **Estimated effort:** 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### Acceptance Criteria (optional)
Users can:
   - @mention other users when they are navigated on summary page and when toast clicked, error is not encountered

**Comment by mattkrick** [comment]
whoaaaaaa how long has that been there?! good find!
