### ISSUE TITLE
invites without email addresses

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2959]
AC

User, with token:
- [ ] when a user goes to a team-specific page that they do not have access & the query includes an `invite_token` param, they join immediately

Non-user, with token:
- [ ] when a non-user does the same as above, they are asked to create an account to join the team & then immediately join that team

Team members:
- [ ] the invite team member modal includes a hyperlink that is the same url as the url they are currently on, plus an invite token query param
- [ ] if you click the clipboard next to the hyperlink, it gets copied
- [ ] if you click the refresh button next to the hyperlink, a new access token is generated & the old one is invalidated

Effort: 12 points

**Comment by ackernaut** [comment]
Is there a difference between inviting to a team and inviting to a meeting? Should we differentiate in order to allow for meeting guests?

**Comment by mattkrick** [comment]
nah, same flow, meeting guests will just be temporary meeting members

**Comment by mattkrick** [comment]
the link shouldn't be good indefinitely, that's too risky.
it's probably OK if the link is good for 24 hours.

so, the credential needs to change every 24 hours.
starting when?
- midnight (UTC?)
- beginning of local working day
- starting when that link is seen

if we do UTC, it's possible that it's expired if folks are working from 23:59:59 to 00:00:01.
if we do local, then we'll need to get a local time for the team member.
if we do time of visit, then we'll need to write a mutation to start/restart the clock on each view. gross.

an alternative would be to have a bunch of tokens. the token includes the teamId, userId, and an expiration in a JWT. if the JWT is valid & not expired, then we know the team and user that want to invite the person.

**Comment by jordanh** [comment]
In other words, the invite token JWT would expire 24 hours from issuance, right?

**Comment by mattkrick** [comment]
yeah, 1 day without a blacklist mechanism feels a little insecure though.
Ideally, we'd also have a refresh button next to the link that would invalidate all previously issued tokens for the team, but i guess i'll let the tension arise.

**Comment by mattkrick** [comment]
AC reduced.
Push invitations moved to #3002
