### ISSUE TITLE
Error: Meeting already started

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2963]
Preventing a user from running their retros with their team. See [this ticket](https://app.hubspot.com/contacts/3888472/ticket/32530828)

https://sentry.io/organizations/parabol/issues/909204900/?referrer=github_plugin

```
Error: Meeting already started
  File "app:///graphql/mutations/startNewMeeting.ts", line 49, in resolve
    return standardError(new Error('Meeting already started'), {userId: viewerId})

Error: Meeting already started
```

AC:
   - Root cause understood, fixed or new issue created

EE: 10.5

**Comment by mattkrick** [comment]
tested locally, can create meeting. 

this will be fixed automatically when we move to handling multiple meetings on the same team, not fixing until then

**Comment by mattkrick** [comment]
stuck behind #2925

**Comment by jordanh** [comment]
This has been fixed, closing
