### ISSUE TITLE
Dialog backdrop/container positioning

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2965]
The backdrop and dialog container positioning fails within long, scrollable views. Separately, I know it’s a little off in some mobile views, too. Viewport height is tricky for mobile browsers (known issue).

**Example**: here’s the dialog to leave an organization when an org has many members. Depending on scroll position, a user might not be able to access the primary action by click and have to refresh the view.

![Screenshot 2019-06-19 15 04 10](https://user-images.githubusercontent.com/307286/59796604-80382b00-92a3-11e9-9242-57884f1a1159.png)

### Acceptance Criteria
- [ ] Triage and fix dialog component positioning

### Estimated Effort
- 10.5 points

**Comment by jordanh** [comment]
Verified fixed during scrub. Closing
