### ISSUE TITLE
Clumsy UX when visiting an accepted invite

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2966]
### Repro steps
A non-user…
- gets invited to team, doesn’t have an account
- users taps the action in the invite email, a new tab opens
- in that tab, accepts invite, creating account, is now a bonafide user
- is redirected to the team dash or to the team meeting in the same tab
- goes back to the email tab, taps the invite link again
- gets the invite accepted dialog in yet another new tab with link to tap to team dash or to team meeting
- taps the link to go to the team dash or meeting, but ends up on the sign-in view
- signs in and then tries the steps above again, it doesn’t repeat, now tapping the accepted invite will take him to the team dash or meeting
- didn’t expect to see the sign-in view the first time when the link looked like it would take him to the team dash or meeting
### Notes
- Confirmed the steps above when inviting a non-Google email using Firefox with cookies locked down. I suspect for some reason the existing tab in the browser doesn’t have a token when the user has only signed up from the new tab with the invite.
### Acceptance criteria
- [ ] Invite accepted view gets a signed-in user to team dash or meeting as the link says
- [ ] If there’s a case where the user has to sign in after hitting an accepted invite, perhaps we have that link, too?
### Estimated effort
- [ ] 10.5 points

**Comment by jordanh** [comment]
Iceboxing for now
