### ISSUE TITLE
Select dropdown wrapping

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2967]
The Pro tag wraps in an unintended way in the select dropdown component. I wonder how other content wraps in this component as well.

![Screenshot 2019-06-19 14 06 19](https://user-images.githubusercontent.com/307286/59797498-71527800-92a5-11e9-9200-00406f48b11e.png)

### Acceptance Criteria
- Fixed the wrapping, maybe by truncating the label before the tag
- Tested and fixed long strings of text, probably truncating with ellipsis

### Estimated Effort
- 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Verified fixed by @ackernaut during scrub
