### ISSUE TITLE
Include applied stripe coupon(s) and refunds on invoice

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2972]
## Issue - Enhancement

Occasionally we may need to offer discounts to paying users. Stripe supports discounting in the form of coupons which may be applied at time of purchase, or, after purchase on the back end.

See [this subscription](https://dashboard.stripe.com/subscriptions/sub_FI7briks68DWSd) for an example of an applied coupon.

Customers will want to see these discounts applied on their invoices.

### Acceptance Criteria (optional)
Users can:
   - Catch when a coupon is applied via a webhook:
      - See when a coupon has been applied on their invoice
      - See the total deducted from the total, if it's a % discount
      - See the per user discount, if it's a hard dollar amount off of a subscription item
   - Catch when a coupon is removed
   - Catch the refund webhook:
      - Display a refund on the proper invoice
   - Cannot apply coupons themselves

- **Estimated effort:** 15 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Opening this just to sketch the work. Not likely to prioritize before gathering a few more users.

Users with discounts applied: 1

**Comment by jordanh** [comment]
@mattkrick would this need a design cycle first?

**Comment by mattkrick** [comment]
nah, easy enough to do. it _should_ semi-work today, price will be right & an invoice line will exist, but the wording might just be what stripe says it is. we could test on staging to see what changes would be needed.

**Comment by jordanh** [comment]
Scrubbed. We should probably do this, but we'll let user tension (or compliance) drive re-prioritization. Iceboxing
