### ISSUE TITLE
New to Parabol? copy in email

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2974]
I realize we could check if the person is a user. Should we scrap the “new to Parabol?” and tighten up that email for existing users?

<img width="574" alt="Screenshot 2019-06-21 11 01 14" src="https://user-images.githubusercontent.com/307286/59935678-f196eb80-9413-11e9-9435-fd6c5569a92e.png">
<img width="560" alt="Screenshot 2019-06-21 11 01 31" src="https://user-images.githubusercontent.com/307286/59935679-f196eb80-9413-11e9-9c69-b35bde7aafcf.png">

### Acceptance Criteria
- [ ] Decided to do, prioritized
- [ ] Added check for user and conditional block to email

### Estimated Effort
- 10.5 points

**Comment by jordanh** [comment]
Scrubbed. Not a lot of tension around this one (funnel-wise), but a good catch. Iceboxing for now.
