### ISSUE TITLE
Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for com...

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2979]
https://sentry.io/organizations/parabol/issues/1055157001/?referrer=github_plugin

```
Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.
  at onDataChange (./src/universal/components/QueryRenderer/QueryRenderer.js:198:12)
  at Array.forEach (<anonymous>)
...
(24 additional frame(s) were not displayed)
```

urls include a /meeting and then a retro phase or vice versa. why the meeting type/meeting phase mismatch?

AC
- [ ] root cause IDd

Effort: 11

**Comment by jordanh** [comment]
17 users affected. Should be prioritized reasonably soon.

**Comment by mattkrick** [comment]
i believe this is a dupe of #2988, will reopen if we see it again
