### ISSUE TITLE
When a timebox is active, no bouncy

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2982]
## Issue - Bug

When a timebox is active, we should shortcut the logic that makes the advance button bounce.

### Acceptance Criteria (optional)
Users can:
   - only see the phase advance button bounce if there isn't an active timebox (and the regular rules apply)

**Comment by mattkrick** [comment]
makes sense for reflect & group.
for vote, it bounces where there are no votes left, i think that logic is AOK.
we don't bounce it for discuss, unless it's the demo, and in that case, i think we should bounce it when the bots are all done.

**Comment by jordanh** [comment]
Fixed in #2992
