### ISSUE TITLE
Segment event discussion

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2983]
I want to know if folks:

- are using the timer/timebox #2998
- are connecting Slack, when/what notification types are fired #3000
- are skipping/disabling Check-In (future)

To simplify, I’m wanting to know if/how folks are using the affordances that we’ve worked to ship recently or are designing. I want us to test our hypothesis and perhaps discover unknown behaviors, get new ideas, etc.

I’m curious to hear from the team about this:

### What is our razor/purpose for capturing an event?
- If the interaction is essential (e.g. team invite), gating usage/adoption
- As a way to continue validating new features
- As a way to continue testing usage
- To see adoption patterns, how to engage users in the funnel
- If somebody feels the tension, add it?

### Ways to specify, implement
- As a stand-alone issue, I’m okay with this
- As an item under the acceptance criteria for implementing an affordance (e.g. issue with 3 bullets: adds timer controls, adds timer data/query model, adds timer Segment event) — I’m okay with this, too

### The pattern
Seems like we have a clean pattern for this, I’m wanting to implement #2942 (team invite dialog), have looked a little at it, and will become more familiar. This hasn’t been something I’ve done but want to start doing more regularly since I’m feeling the tension.

**Comment by jordanh** [comment]
Let's fill out #2998 with the AC

**Comment by ackernaut** [comment]
Some additional thoughts:
- What is the question you are trying to answer?
- What actions might it drive?
- What insights may be discovered?
