### ISSUE TITLE
Timebox client exception after self promotion to facilitator

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2984]
## Issue - Bug

Repro steps:

1. With team with user A and user B, start timebox on reflect phase as User A
2. Disconnect User A
3. When User B joins, they will become facilitator. Submit reflection
4. Disconnect User B
5. Connect User A and promote else to facilitator
6. Click on Timebox, see error:

![image](https://user-images.githubusercontent.com/103000/60195185-7fe1e780-97ef-11e9-8fb8-e6cce31350f6.png)

This is non fatal. A refresh fixes it.

- **OS:** macOS
- **Browser:** Chrome
- **Estimated effort:** 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### Acceptance Criteria (optional)
Users can:
   - When a Timebox is running, self promote to facilitator and access timebox update menu without encountering an exception

**Comment by ackernaut** [comment]
Good find!

**Comment by jordanh** [comment]
Fixed in #2992
