### ISSUE TITLE
defaultFacilitator logic added for async retros

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2985]
## Issue - Enhancement

When a meeting leader starts a Retro and adds a timebox, they expect to be the facilitator when they rejoin the meeting, so they can continue to move the meeting forward.

### Acceptance Criteria (optional)

- a meeting has a `facilitator` and a `defaultFacilitator`
- when a meeting is started, both are set to the person who started the meeting
- when a facilitator disconnects, another member elects themselves as the `facilitator` unless a timebox is active
- when someone reconnects, if they are the `defaultFacilitator`, they get promoted to `facilitator` 
- when someone promotes themselves to facilitator (not due to disconnect) they become the `facilitator` and `defaultFacilitator`

- **Estimated effort:** 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
See discussion #2918 for more context

**Comment by ackernaut** [comment]
>when a facilitator disconnects, another member elects themselves as the facilitator unless a timebox is active

You mean another member is automatically promoted to `facilitator`?
