### ISSUE TITLE
fix invitation-required flow

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2986]
Repro
- [ ] be a parabol user
- [ ] be logged out
- [ ] have an invitation to a team in your inbox
- [ ] goto a retro lobby for the team that you're invited to
- [ ] see lobby w/o having the teamId in your JWT

AC
- [ ] works as intended

effort: 11 points

**Comment by jordanh** [comment]
Similar to #2988

**Comment by mattkrick** [comment]
closing in favor of #3002
