### ISSUE TITLE
Join meeting from invite error

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2988]
### Steps
- Via email, accepted an invite as a 2nd user from a 1st user
- Joined the meeting, left the meeting
- Hit the “Join” button from the invite email again
- Saw the invite dialog with meeting context, clicked the link to join the meeting
- Saw the error message view, wouldn’t clear up on refresh
- Could still see meeting view with 1st user, refreshed from the 1st user view
- Went to `/me` for the 2nd user, then went to meeting and it was working
### Screenshot
![Screenshot 2019-06-26 16 13 49](https://user-images.githubusercontent.com/307286/60215745-ef76c780-982d-11e9-87af-abb4093cca41.png)
### AC
   A user can:
      - Triage this bug, fixing if possible, opening new issue if not such that a user can...
         - ...join a meeting, leave, and re-use email invite link to join again without an error
### EE
   - 10.5 points

**Comment by mattkrick** [comment]
the updated invitation stuff had a bad slug, it was static at `meeting` instead of being based on the meeting type. all fixed
