### ISSUE TITLE
Combine cards by dragging one atop the other

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#299]
## Issue - Enhancement

Sometimes over the course of a given week, a user has tackled a bunch of cards that are related to one another. To reduce clutter and consolidate the update given during project updates it'd be cool to be able to combine two cards together by dragging one over the top of another.

Suppose you have card A, "balloons bought," and card B, "cake baked". You might want to merge these two. You drag B on to A and get:

```
balloons bought
cake baked
```

We could also focus a little modal that would ask for the name of the combined card. We could then render the card like:

```
birthday party planned
-----------------------
* balloons bought
* cake baked
```
- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
👍  I like this idea…

**Comment by mattkrick** [comment]
I like the little modal idea, especially since I can see someone accidentally dropping 1 card on another when they really meant to drop it above/below. Let's implement this after we implement markdown, since we'll probably use the markdown bullet points to make it work.
