### ISSUE TITLE
Retro Group phase UX, solo or team activity?

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2993]
User verbatim pulled from #2948 but this issue is about a separate concern: do folks know they can group, too? Do they feel like they have the autonomy to group?

From user via email:
>I found the grouping part to be awkward. It left time where I as the facilitator was just doing things and everyone was just staring at me. In the future we would do that part before everyone walked in the room OR if we could all work on it together where the facilitator wasn't the only one that could move cards

Captured for group UX research.

**Comment by jordanh** [comment]
One more bit of feedback to capture from [a user](https://app.hubspot.com/contacts/3888472/contact/3861651):

> After you grouped the cards. There is no way to see what’s in them unless you click on the groups. It’d be great to be able to see what you’ve grouped and take in the big picture (JH: maybe it’s a tab button that let you see things expanded with headers that you can scroll). Robert also said, maybe we can group within groups—just like you would with Post-It® Notes

**Comment by jordanh** [comment]
Sticking this here to (same user as above):

> Feedback on the autogroup thing: we clicked the autogroup thing and then we didn’t know how to turn it off. It was really akward.

**Comment by jordanh** [comment]
Scrubbed. Iceboxing
