### ISSUE TITLE
assigned "Due Dates" vs broadcasted "Target Dates"

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#2995]
## Issue - Enhancement

from [this user team](https://app.hubspot.com/contacts/3888472/company/2076127100/) RE "due dates" introduced as an autonomous, self-assigned method of broadcasting your prioritization goals to your teammates vs externally-assigned "due dates" which can create anxiety

> I am reaching out because I hoped to speak more to your "due dates" line of thinking. I think what you said about due dates being more of a broadcast to your team is something that Parabol should somehow educate its users on! Maybe Parabol can add a little "Info" or "?" button when you hover over the clock? And explain how we use and update due dates, instead of assuming we are sworn to these dates. Also, I am one of those users that forgets to add the due date as soon as I complete a card. It would be awesome if as soon as you hit "Enter" to submit your card, the little clock would flash, spin, or do something cute to remind you to add a due date to it! Something the user can experience as a little flicker of a reminder.

**Comment by jordanh** [comment]
Iceboxing for now. Will reopen with new user feedback.
