### ISSUE TITLE
Add Reflections during Group Phase

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2996]
## Issue - Enhancement

I was surprised I couldn't find an issue for this already. Adding now.

### JTBD:

When my colleague's Reflections are revealed to me in the Group phase, I want to be able to add more cards if their feedback prompts additional thoughts, so that my thoughts can be included in the retro too

### Acceptance Criteria (optional)
An implementation issue opened containing a design for:
   - Hitting a control at the end of the masonry to add a new, ungrouped, Reflection (a la a Task card)
   - Optional: Hitting a control during the group phase _within an existing group_ to add a new Reflection

- **Estimated effort:** 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/3861651) said:

> It’d be great to be able to add cards during the group phase.

**Comment by ackernaut** [comment]
- [Notes WIP](https://docs.google.com/document/d/1g0OK_Qs7mcduFxAj2810ItUZVP3p0K_5ScN8uG-ihOI/edit#) (private to team)
- [Concepts in Figma WIP](https://www.figma.com/file/Rz8nce3zxvJYR2xNcO3g38Nh/Retro-Group-Phase?node-id=118%3A13) (anyone can view)

**Comment by ackernaut** [comment]
⬆️ implementation issue added (#3027)

**Comment by ackernaut** [comment]
From a user via email:
>While conducting the retrospective, I was unable to go back and add comments under the reflect tab. It was rather disappointing as the team had some to add and edit.

**Comment by ackernaut** [comment]
Updated implementation issue for a possible lean iteration #3027

**Comment by ackernaut** [comment]
Feedback from [user](https://app.hubspot.com/contacts/3888472/contact/5290451/) via email:
>Two of the biggest things I’d like to see added are 1) being able to add more cards to the retro board after they are all showing (often ideas are hatched during the conversation after all the post its are up on the board) and 2) having the cards ordered in groups/columns. If I am doing a start/stop/continue retro, I’d like to see all the START cards in one group—same with STOP, and CONTINUE. Though I do LOVE how I can combine similar cards.
