### ISSUE TITLE
Trello one-way task integration

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2997]
## Issue - Enhancement

Genuinely _shocked_ ⚡️I couldn't find an issue for this to un-icebox. Opening this as a discussion to collect user feedback to gather signal before committing.

[A user](https://app.hubspot.com/contacts/3888472/contact/3861651) said:

> My clients user Trello and all the Atlassian apps. Engineers all use Jira but everybody else uses Trello. Being integrated against Trello would allow me to include everybody.

Further discussion may change the below AC.

### Acceptance Criteria (optional)
Users can:
   - See Trello as an integration from the `ProviderList` and Task card surfaces
   - Integrate against Trello
   - Add a Task card to any Board and Lane (showing as `Board: Lane`) in the card pick list

- **Estimated effort:** 15 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Iceboxing. Will reopen if we add more user feedback

**Comment by gcrickman** [comment]
A user writes via chat:

> How do I migrate the team dashboard to another system e.g. trello?

**Comment by gcrickman** [comment]
A [user](https://app.hubspot.com/contacts/3888472/contact/50186001) 🔒 writes:

> Do you have any integrations with Trello, or are you planning any?

**Comment by thedrow** [comment]
I have the same situation as well and I'm really interested in this feature.
In fact, I would have immediately upgraded to a paid plan if this integration would have existed.
