### ISSUE TITLE
Timer/timebox segment events 

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2998]
Folks are not required to use the timer or the timebox. They can hold a synchronous or asynchronous ​without the affordances. However, I would like to have an idea of how many folks are using them, during what phases, etc. Any insights into usage may help us form better inquiry for testing other sync and async affordances.

Feel free to push back on these for whatever technical reasons:

### Acceptance Criteria

The following segment events are implemented:

**Event name:** `Timed Phase Started`
Properties:
   - Mode: `timer` or `timebox`
   - TimeValueSelected: what time value was selected
   - MeetingPhase: what phase/stage the meeting was in
   - PresentCount: wow many folks were present when started
   - SlackIntegrated: `bool` whether or not the team was integrated with Slack
   - SlackEnabled: for timebox, `bool` whether or not the team was integrated with Slack; always `false` when for timer 

**Event name:** `Timed Phase Stopped`
Properties:
   - Mode: `timer` or `timebox`
   - TimeValueSelected: what time value was originally selected
   - TimeValueElapsed: how many actual time elapsed when the timer/timebox was stopped
   - MeetingPhase: what phase/stage the meeting was in
   - PresentCount: wow many folks were present when timer stopped
   - SlackIntegrated: `bool` whether or not the team was integrated with Slack
   - SlackEnabled: for timebox, `bool` whether or not the team was integrated with Slack; always `false` when for timer 

### Estimated Effort
10.5 points

**Comment by ackernaut** [comment]
AC and EE added!

**Comment by jordanh** [comment]
AC updated
