### ISSUE TITLE
Unit tests for falcor-saddle

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#30]
Mission summary
=============
[falcor-saddle](https://github.com/ParabolInc/falcor-saddle) is a dependency of Action's. It's the little Falcor router helper that greatly reduces the repetitive code we'd need to write to stitch Falcor and RethinkDB together. falcor-saddle is in need of a suite of unit tests, and, perhaps a few small fixes as those unit tests are created.

Estimated Size
===========
8 points ~ Less than two weeks

Mission Spec
==========
[Read mission spec here](https://goo.gl/RlliIU)

**Comment by jrwells** [comment]
I've got this one.

**Comment by jordanh** [comment]
Yes you do! Proceed good sir!

**Comment by jordanh** [comment]
Merged on 3/5/2016: https://github.com/ParabolInc/falcor-saddle/issues/1
