### ISSUE TITLE
Markdown added to outcome cards

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#300]
## Issue - Enhancement

Formatting _is_ **useful**. Markdown has become widely used and accepted on the web.

Let's add markdown to our outcome cards.
- [ ] Project cards render plaintext as markdown
- [ ] Action cards render plaintext as markdown
- [ ] Focusing an outcome card renders the textarea as plaintext, not markdown.
- **Estimated effort:** 5 points + 10 bonus points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
I've added this to our [Equity for Effort program](https://focus.parabol.co/equity-for-effort-v2-0-7ca93e0a3968). If anybody in the community is interested in tackling this, please add a comment here!

**Comment by ndey96** [comment]
@jordanh I'd like to take this one on :) I'm going to tentatively agree with the 5 point estimate

**Comment by mattkrick** [comment]
This is a great one @ndey96! Check out the `Editable` component for a source of inspiration-- it shows a div until you click it & then it turns into an input field.

I think this will turn out to be quite similar-- show a div with the markdown applied until someone clicks on it, then show a text area with the raw markdown.

**Comment by jordanh** [comment]
@ndey96 it's all yours for 5 points + the 10 point bonus. Have fun!

**Comment by jordanh** [comment]
Closed by #640. Great work! 🌠 

Crediting you 15 points. [Your new total is 27 points](https://docs.google.com/spreadsheets/d/1V1KZJn6oKFsqrYwqr430rO3hkIkekSY7oYFzX3cVty4/edit#gid=679741853).
