### ISSUE TITLE
Segment event for Slack

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#3000]
### Acceptance Criteria
- Segment fires an event when somebody connects to Slack

### Estimated Effort
- 10.5 points

**Comment by ackernaut** [comment]
At a minimal, we could know how often folks use our Slack integration…any interest here @jordanh @mattkrick ?

**Comment by mattkrick** [comment]
i personally don't have any burning questions that this would answer

**Comment by jordanh** [comment]
scrubbed, iceboxing
