### ISSUE TITLE
restyle toasts to be snackbars

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#3001]
everytime i see a toast it looks like some ancient artifact. it should look like a snackbar & probably pop up from the bottom. easy to do, it's really just a styling problem.

AC
- [ ] prototype toasts appearing as snackbars

Effort: 11 points

**Comment by mattkrick** [comment]
hey @ackernaut you got a a figma link handy showing the latest snackbar concept?

Thoughts:
- I like the plain dark gray background
- Do we want different levels e.g. info, warning, error, success? if so, how do we show those?
- How do we show a single action?
- How do we show 2 actions (eg accept/deny)?
- Can we show multiple snackbars at once? (material design says no).
- If we can only show e.g. 1 snack at a time & 2 snacks get sent, i imagine the 1st snack will last however long it's supposed to (e.g. 5 seconds) and then the 2nd one will show up after it. if that first snack has a long autoDismiss (or none at all) should we show that there are other snacks waiting to be seen? e.g. "...and 1 other message"?
- the toasts had a title + message. material design seems to favor only having a message field. that cool with you?

**Comment by ackernaut** [comment]
Hey @mattkrick 
- I can get a proper file together in Figma quickly. Yes, dark background is default.
- I’ll ponder different purposes (info, warning, etc.)
- I’m okay starting with [the MD guidelines](https://material.io/design/components/snackbars.html) but we may diverge. As we do, we could write down our reasoning here or in Guru
- Maybe we stick to the MD’s prescription of single action. I’m not sure how many cases there are currently for 2 actions, like Accept/Deny. In this case maybe we only show Accept for however long (5 seconds) and they can always deny or ignore in the notifications view. The principle being show the preferred or most likely action and let the other way of doing it be secondary (in another view etc.).
- As for multiple message, maybe the razor is all messages should have an alternative way of doing the same thing. And they all have a priority level (1 message per 1 level). And then let the most important message trump the others.
- Yank the title!

**Comment by mattkrick** [comment]
all sounds good!

wrt the 2 actions-- how should we handle the push invitations? i was hoping to use snackbars to get folks to accept/deny someone to the team, but if we only have 1 action then we'll have to create a new kind of component just for that.

**Comment by ackernaut** [comment]
@mattkrick re: 2 actions

If we have a clear enough case with good heuristics/principles then that’s where we fork from MD’s suggestions and write down our own use case w/ examples. Probably safe to document in Figma, or could be Guru.

**Comment by mattkrick** [comment]
i like it.
overall i wanna just cut the noise down as much as possible. for example i'm thinking instead of having a "youre back online" snackbar, we just remove the "youre offline" snackbar.
