### ISSUE TITLE
Re-join facilitator helper button implemented

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#301]
## Issue - Enhancement

When a team member is participating in a meeting, they may want to diverge from what the facilitator is currently looking at. However, when a team member wants to rejoin the facilitator, they will want the act of rejoining the facilitator to be as frictionless as possible.

In order to achieve this, I propose the "Re-join facilitator" button. It's similar to the "Recenter map" in Google Maps.

If you see the button, it means you've diverged from the current phase and item of the meeting. If you press the button, you get zipped to where the facilitator is currently.
- **Estimated effort:** 2 points + 10 bonus points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
I think this is a perfect use case for a floating action button (https://material.google.com/components/buttons-floating-action-button.html#buttons-floating-action-button-large-screens). I'll leave it to @ackernaut to design, the code behind it should be really simple.

**Comment by jordanh** [comment]
I am a _huge_ fan of this one. But, going to defer to the future.

**Comment by ndey96** [comment]
This one sounds pretty valuable :) Interested in picking it up for the 12 pts 👍

**Comment by ndey96** [comment]
@mattkrick I'm going to take this one on next, could you provide some more implementation details for me? This sounds cashayesque

**Comment by mattkrick** [comment]
Ooo, this is gonna be a fun one.
So first step is detecting that localPhase + localPhaseItem !== facilitatorPhase + facilitatorPhaseItem. You could do that as a boolean in MeetingContainer probably, let's call it `inSync`. There's no need to compute this if you are the facilitator, so you could shortcircuit for that.

Then, we need a rejoin button, I'd probably take a page out of the material design handbook & do a floating action button that's just a little circle with an icon in it. Hovering the icon will eventually need a tooltip that says "Rejoin the facilitator" but for now you can use native tooltips. 

Now in the JSX you just show that in the lower right if !inSync.
The event handler won't even need to touch the server, rather you just use the router to redirect the user to `/facilitatorPhase/facilitatorPhaseItem`. Not every phase has a phase item, so I made a helper in there somewhere to make sure the route is correct. Then, just do a `router.push`. No cashay needed, all local!

**Comment by tayamueller** [comment]
suggestion: (see #715 ) work toward building true "go-to-user" capability where users can join the view of any user by clicking on their avatar. Per #715, if they become untethered (or go rogue) they rejoin by simply clicking on the hot-pink-ringed avatar (Facilitator)

**Comment by mattkrick** [comment]
Oh this is interesting. If anyone can see what I see, does this discourage
me from going rogue since I have the fear of big brother peeking in on me?

**Comment by ackernaut** [comment]
Figma has a “see what the other person is seeing” when you click on that person’s avatar. I don’t feel the need for it for all users—just with the facilitator. One is either roaming anon or tethered.

**Comment by ackernaut** [comment]
With Figma, I may need to see what they are working on as we are chatting about it etc. so there is a value there.

**Comment by mattkrick** [comment]
Yeah, if we persist state for each user, it's gonna be... Non-trivial.

**Comment by ackernaut** [comment]
Haha! I would agree—non-trivial and probably not a value add. I think the value add is focusing on improving the UX of staying together (and knowing how to re-join when one needs to wander off).

**Comment by jordanh** [comment]
@ndey96 I've credited you with 12 points. Your new point total is 64 points! You're also still the current Equity for Effort leader :)
