### ISSUE TITLE
Add sidebar toggle at small breakpoint

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#3017]
We merged new sidebar behaviors, but don’t have an explicit toggle control (using the `menu` icon). Users might miss that there’s a menu if they’re kicking the tires on mobile.

We can add the toggle in these 4 places until we update the dashboard IA. My latest thinking is that we use `clientSchema` like we do for the meeting sidebar.

### Acceptance Criteria
- Mobile breakpoint is below `DASH_SIDEBAR.BREAKPOINT`
- [ ] User dash header `UserDashMain` has menu button at mobile breakpoint
- [ ] User settings header `SettingsHeader` has menu button at mobile breakpoint
- [ ] Team dash header `Team` has menu button at mobile breakpoint
- [ ] New team form `NewTeamForm` has menu button at mobile breakpoint

### Estimated Effort
- 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Duplicative of #3448
