### ISSUE TITLE
Single card group title doesn’t persist in demo

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#3018]
I noticed that in the demo a custom title for a single card group (by tapping the single card) does not persist to the vote phase, it looks like an autosuggested title takes its place.

### Acceptance Criteria
- Adding a title to a single card persists to the vote phase

### Estimated Effort
- 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
to better tackle this issue, and also support adding cards during the group phase, we should probably re-evaluate how smart titles are generated.
today, they're created when advancing to the group phase.
this is to minimize the amount of chatter we have with the google API.
a more costly, but more robust solution is to process the card immediately after it's created/edited.
this gives us the power to perform autogrouping on the client, too, when we refactor it into something more useful.

**Comment by mattkrick** [comment]
must've been fix backed when we fixed the rest
