### ISSUE TITLE
Change "My Dashboard" cards to include team name, not my face.

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#302]
## Issue - Bug

I just noticed that the cards on "My Dashboard" all have my face on them, and not their team ownership.

![image](https://cloud.githubusercontent.com/assets/103000/18882722/6f8c5ae8-84ae-11e6-813a-0646481e518c.png)

@ackernaut, we had a different design, right?

**Comment by ackernaut** [comment]
Yes, there is a different design for team avatars. The beginnings of that presentation option are in the outcome card footer component, but right now it is simply set to owner styles. It may make sense to have separate `Avatar` and `TeamAvatar` components. Thanks for capturing.

**Comment by mattkrick** [comment]
oh shoot, didn't see Terry took this one. Fixed in latest branch
