### ISSUE TITLE
memory analysis for 3.16.1

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#3022]
went through the diff, here's what could affect memory:
- rate limiter keeps an array of every hit for user/query combo for the past hour. that means if someone hits our endpoint 100k times in an hour for a particular query, we have to store that 100k array. the fix is easy: blacklist the IP at nginx when that happens
- reduce dataloader-warehouse ttl. i bumped it up to 10 seconds for handle facilitator negotiation on disconnect. we can easily bump it back down to 5 seconds & just not use it for those disconnect events. 
- upgrade graphql-redis-subscriptions. there's a mem leak in this version of the iterall package. https://github.com/davidyaha/graphql-redis-subscriptions/pull/138

i want to let the server start leaking for a day to see what impact, if any, the latest push made. then, we can tackle these from bottom to top.

**Comment by jordanh** [comment]
@mattkrick shall we close this?
