### ISSUE TITLE
Navigation state, untethered from facilitator

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#3025]
My local active nav item looks like the nav item that shows where the facilitator is:

![Screenshot 2019-07-16 11 22 02](https://user-images.githubusercontent.com/307286/61311872-df169480-a7bc-11e9-9046-5381f2a6ff55.png)

### Acceptance Criteria
- Local nav item styles and nav item styles for facilitator’s location are fixed
  - Local nav item has the bar and background highlight
  - Facilitator location has the orange dot and text

### Estimated Effort
- 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
We think this is fixed
