### ISSUE TITLE
Implement adding a card during the Group phase

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#3027]
Based on UX design output from [#2996](https://github.com/ParabolInc/action/issues/2996#issuecomment-510964764) and [design notes](https://docs.google.com/document/d/1g0OK_Qs7mcduFxAj2810ItUZVP3p0K_5ScN8uG-ihOI/edit#bookmark=id.fok8semi91a1)

#### Lean Iteration
- For all phases, the help FAB is removed from the bottom right, it becomes an inline menu toggle (a simple `help` icon) in the top bar by the phase title
- There is a FAB with the `edit` icon floating (bottom right of the card grid)
- Tapping the FAB reveals a menu with the prompt options
- Tapping selects the prompt, the card grid scrolls to the bottom, and a new card appears
- The card has `autofocus`, placeholder text “My reflection… (press enter to add)”, and the prompt label is visible
- Type text and press enter, or blur, and the card persists
- Blur the card without adding any initial text and the card disappears
- Folks can edit their own existing and new cards
- Folks can remove their own existing and new cards
#### Target Iteration
- The ability to edit/add reflections could be a phase option. This option could be set as a meeting template, or a toggle during the phase, exposed to all participants or only the facilitator

### Estimated Effort
- 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
The product team will look at this together during our next design review

**Comment by mattkrick** [comment]
i don't love the idea of putting this on the FAB because it isn't the primary action for the view (neither is help, but that's another story...)
i propose just adding a blank card at the end of the grid. having to scroll down to the bottom every time you want to add a card adds friction, which is a feature, since we want to passively discourage this activity.

**Comment by mattkrick** [comment]
stuck on designs, i see some sketches in figma, but not sure what to implement

**Comment by ackernaut** [comment]
@mattkrick thanks for noting. I’ll make a second pass at designs at update here when something is ready.

**Comment by mattkrick** [comment]
stuck on email to send when they click upgrade later

**Comment by ackernaut** [comment]
### Short-term
- Add [a small, secondary icon button](https://www.figma.com/file/Rz8nce3zxvJYR2xNcO3g38Nh?node-id=231%3A0&utm_campaign=team&utm_source=slack&utm_medium=message&utm_content=file_comment#9858613) `add` to the top of the view (phase header, not top bar)
- Hover reveals tooltip `Add Reflection`
- Tap reveals menu with an option for each prompt
- A card with placeholder text is added to the bottom of the grid, the container scrolls to, and the editable content is focused
- I wouldn’t mind another text control `Add a reflection` in the shape of a card at the bottom of the grid that is replaced with the focused card with placeholder on tap. Basically it doesn’t show if a user is actively working on a new card regardless of which control they hit (top icon button or placeholder add card control)
### Long-term
- Depending on how we implement #3094 
- Add a small, secondary icon button `add` at the top of each column (hover = tooltip, no need for a menu to select a prompt if the column is based on the prompt, if the column is based on some group then we would need to pick the prompt).
- Since the columns will probably be long, I wouldn’t mind a text control `Add a reflection` at the bottom of each column
- I think we scroll down to the bottom of a column to add the new card so that the top order doesn’t move for other viewers
### Shared behaviors for both versions
- A user enters to commit
- Blurring an empty card deletes it
- User can edit or delete any of their own cards

**Comment by ackernaut** [comment]
@mattkrick what do you think re: [comment](https://github.com/ParabolInc/action/issues/3027#issuecomment-523557359)

**Comment by jordanh** [comment]
Add feedback from a user (came in via chat, not sure who to attribute it to):

> I moved my retro to "group" phase and back to "reflect".  Now people cannot add items.  How do I fix this?

**Comment by mattkrick** [comment]
@ackernaut i dig it. i'd opt for just going for the long-term since the short term is gonna take awhile, anyways. i imagine columns will look like a cross between the task kanban & the reflection phase (on mobile). if you've got any desire to redesign how the task kanban looks i think now would be the perfect time! i'm hoping we can share the headers component across the 2.

**Comment by ackernaut** [comment]
Yeah, @mattkrick I’ve been working on Reflect and Group phase design for both mobile and laptop. You can start perusing from [this frame](https://www.figma.com/file/0lOTlvsj87GBFFzgee9OkVWi/Meeting-Layout?node-id=340%3A9968) in Figma.
