### ISSUE TITLE
Outcomes, agenda items can haz emojis

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#303]
## Enhancement

Card text and agenda item text should be able to handle emoji characters because: 1) PLAY 2) millennials 3) 💥 💣 👾 👍 💯 

See #684 for Markdown customizations

**Estimated effort:** 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
this is an interesting one...
we've got 2 ways of doing it:
- the nerd way-- accept markdown characters `:smile:`
- the apple/venmo way-- suggest emojis based on words (https://github.com/felixrieseberg/emoji-autocomplete)

**Comment by ackernaut** [comment]
Ah, is this last option similar to what GitHub does? Where `:` triggers a drop-down/auto-complete.

**Comment by mattkrick** [comment]
nah, github/slack follow the first option. check out ios10 or venmo for the last option, where it auto-detects certain words/phrases
