### ISSUE TITLE
Implements optional Social Check-In phase

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#3030]
### Acceptance Criteria
- A meeting can have optional phases
- Phases can be included or excluded by default
- New meeting lobby UI can include the phases (depends on designs from #3028)
  - Ability for users to opt in to Social Check-In
- ~**Stretch goal**: consider phases that may follow a specific order (e.g. Social Check-In, Metrics, Updates, Agenda). How to order the Social Check-In and Metrics before Updates and Agenda?~
  - ~We probably suggest defaults in our templates?~
  - Or ~we use a default position when adding a certain phase?~

### Estimated Effort
- 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

EDITS: 
   - @jordanh: tightened AC to only include social check-in phase to start

**Comment by jordanh** [comment]
Validation from [a user](https://app.hubspot.com/contacts/3888472/contact/5677651/):

> It would be nice to choose whether or not we wanted the "social" feature on/off; sometimes it was nice, but sometimes it felt like wasting time

**Comment by jordanh** [comment]
Validation from [a user](https://app.hubspot.com/contacts/3888472/contact/5332851?):

"I really want to skip the ice breaker round"

**Comment by jordanh** [comment]
Validation from [a user](https://app.hubspot.com/contacts/3888472/contact/6470501):

> I usually click through the check-in, because I don’t want to do it. Could be an option for you to skip it completely instead of checking everyone in. I know it’s important, but it takes time to get your team to that level (we’ve never done this and are already doing this for ages this way blabla)

**Comment by mattkrick** [comment]
BURNDOWN
- [ ] to squelch involvement notifications, we used `isCheckedIn`. instead, we should see if the person who updated the task is in a meeting & send a notification to the involvee only if they are not in that same meeting
- [ ] in action meetings for the updates stages, we ask a different question if the person is not checked. instead, we should ask that if they are not connected
- [ ] in the votes phase, voting would auto-check-in someone in case they slipped in without checking in. now it doesn't do that
- [ ] in the meeting summary & csv export, we classify each meeting member as present or absent. this should be calculated based on if they hit the meeting route at least once. we should do this by just using the "CheckInMutation" if the meeting does not have a check in round.
- [ ] the votesRemaining field is measured by the number of people checked in. if we implement the above correctly, this should still work fine.
