### ISSUE TITLE
Designed updates to meeting alert banner

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#3031]
### Acceptance Criteria
- Visual concepts illustrate how users can:
  - See what meetings are active, probably anywhere in the dashboard
  - Click through to a single meeting, or
  - Click to a list that shows multiple meetings that are running
  - Probably uses an updated [banner pattern](https://material.io/design/components/banners.html)
- May depend on some effort from #3029 depending on prioritization
- Implementation issue written

### Estimated Effort
- 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Capturing feedback from [an enterprise customer](https://app.hubspot.com/contacts/3888472/contact/7349901): 
> You cannot smoothly have a retro board set up in advance for folks to add things to (when you create the retro meeting, it locks the board so folks

**Comment by jordanh** [comment]
@ackernaut it makes me wonder if we don't just remove the modal blocking updates and leave the notification bar at the top. If they have a retro running, they won't be able to run an action meeting—but—big deal. They can't do that already today. But, at least they could touch the task board.

What do you think?

**Comment by ackernaut** [comment]
@jordanh I think we consider these 2 criteria to remove the modal blocking the kanban:
- Start a Meeting button becomes Go to Meeting button in the top right of the team dashboard when there’s an active meeting
- If folks go to a link to a meeting lobby, it automatically redirects to the active meeting

**Comment by jordanh** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/1377251) writes:
> It would be nice to see the cards on the homepage while doing a retro. I will make cards when people slack me ideas for retro throughout the sprint, and then can't see them when I'm in a meeting. Same with agenda items! It's frustrating to list agenda items, but not have those pulled into the meeting when you start one.

**Comment by mattkrick** [comment]
I think the first half of this will come from an "Inspirations" section that is present during the reflect phase. it will look a lot like the updates phase, where it shows diffs.

not sure what the user means about agenda items

**Comment by mattkrick** [comment]
i think this issue has been solved for by removing it entirely. closing
