### ISSUE TITLE
Team agenda, 1 or many check-in meetings?

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#3032]
Although discussed, I’m not sure that we nailed down a decision on how to handle team agenda in a system where many meetings can run concurrently.

- Can a team start more than 1 check-in meeting?
- Is there just 1 team agenda?
- If many check-in meetings, does each have its own agenda list?

My hunch is that most teams are currently interested in Retro meetings. For those teams that run Action meetings, I could see those being run while a long-standing Retro is open. I’m not sure folks are interested in running more than 1 Action at a time in its current form.

So maybe the first move is that a single Retro and a single Action meeting can run concurrently? That constraint may be good UX. Then we wait to see if folks want more than 1 type at a time? In the future maybe we’ll have other meeting types (decision making aka governance?)

Also, I’m not as concerned how we express the affordance of an agenda list in terms of UI (is it a sidebar, is it a list that pops up, etc?) but more the UX (are we working from a single list and checking in with a single meeting as a team?).

This could impact the design of #3028 (as in, I can only start a new meeting of a type that’s not currently running).

### Acceptance Criteria
- A decision is made here, looking for consent:
  - A) Let’s only allow 1 Retro and 1 Action at the same time (for now, and learn more)
  - B) Let’s allow multiple Retros and 1 Action at the same time
  - C) Let’s allow for multiple of both and each Action has its own agenda
  - D) Something smarter

### Estimated Effort
- 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
@mattkrick @jordanh

**Comment by mattkrick** [comment]
B.
IMO concurrent retros make sense, concurrent check-ins don't.


the agenda is attached to the team.
when a check-in meeting starts, it copies over the list to the meeting in progress.
while the meeting is in progress, new agenda items get added to both the team & the meeting.
when the meeting finishes successfully, the team agenda list is flushed.

**Comment by ackernaut** [comment]
@mattkrick in this case, if there’s a single view to start a meeting, would the Action meeting option be disabled for that team? Would the user have to pick the team first before picking the type?

**Comment by mattkrick** [comment]
naive approach would be to just wait until they click "Start Meeting" and then show an error message explaining that an action meeting is already in progress & maybe a link so they can go there and/or close it out.

order shouldn't matter since I imagine it'll just be a single form & not a wizard.

making it disabled from the dropdown would be a nice touch, but we'll definitely need an affordance for the error state in case 2 people try to create a new meeting at the exact same time.

**Comment by mattkrick** [comment]
Another approach would be at the time the meeting begins, we move the agenda items from the team to the meeting.

This would lift the 1-action-meeting-per-team constraint.

I think i like this because it better encapsulates meetings & teams.

**Comment by ackernaut** [comment]
@mattkrick I like this. To expand on the idea, if a team runs a meeting (pre-formatted type or custom) that includes an agenda phase, it pulls that in off the team and processes it.

**Comment by mattkrick** [comment]
implemented unlimited everything. 
if you have 2 action meetings & add an agenda item, it only goes to the first.
this probably feels like a bug. maybe we limit to 1?

**Comment by ackernaut** [comment]
Yeah, it probably makes sense to limit to 1 check-in in the short term, but then again it’s probably an edge case. I say kick the can…

**Comment by ackernaut** [comment]
Gonna close this discussion. We can always reference, or re-open.
