### ISSUE TITLE
Group phase topic column for laptop+ views

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#3036]
### Acceptance Criteria
For laptop+ breakpoints:
- [See Figma](https://www.figma.com/file/Rz8nce3zxvJYR2xNcO3g38Nh/Retro-Group-Phase?node-id=123%3A13)
- The card/group grid takes up the space allowed of the main view
  - Depends on if any sidebar is open
  - Probably at least 2 cards across, probably 3-4
- There’s a column to the right that automatically populates group topics as they are generated
- Tapping on a group topic shows the group dialog
- TBD the grid doesn’t scroll to the actual group because the person may be referencing other cards where they were and we want to avoid too much movement (orientation) or we do scroll to the group because the person wants to know where the group is (we could show a little arrow on hover if the group is not in view and a tapping that secondary control goes to the group)
- A card can be dragged into a topic item in the side column instead of having to find the group in the grid
- Stretch: the title can be edited in the side column item
- Out of scope (handled by #3037): mobile gets a swipe-able column interface that shows columns by prompt or by topic with a jump-to filter and controls to send cards to a topic, a new topic, or ungroup

### Estimated Effort
- 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Iceboxing for now
