### ISSUE TITLE
Mobile group phase view option

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#3037]
### Acceptance Criteria
- [See Figma](https://www.figma.com/file/Rz8nce3zxvJYR2xNcO3g38Nh/Retro-Group-Phase?node-id=123%3A33)
- Initially the mobile view shows a swipe-able column for each prompt
- Prompt columns probably show groups with only the cards of that prompt. Tapping the group takes user to the topic column for the group showing all prompts.
- While looking at prompt columns, there’s a filter to tap to the column view for any existing topic. Maybe there’s an Ungrouped column, too, while viewing columns by Topic
- While looking at topic columns, there’s a filter to tap to the column view for any of the prompts
- For mobile the cards have a lower right control that opens a menu to move to a New Group, an existing group, or to Ungroup
- When a new group is created the initial name is the autosuggested name
- The name can be tapped in order to edit on mobile
- For laptop+ we probably don’t have this lower right control, but use the topic column instead, see #3036 
- Depends on the swipe-able column pattern of #2908 and #2962

### Estimated Effort
- 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Scrubbed. Iceboxing. This is a level of fidelity that we may or may not reach. But, we've identified the target and created newer implementation issues.
