### ISSUE TITLE
Design Reactji on Reflections

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#3058]
AC
- [ ] competitive analysis performed
- [ ] focus applied figure out if reactjis are applied to reflection or group. how do we prevent all the reactjis appearing on the first reflection when they're meant for another one in the stack?
- [ ] design created adding ability to add reactjis to reflections in the group+ phase

Effort: 12 points

**Comment by jordanh** [comment]
Here's feedback from [a user](https://app.hubspot.com/contacts/3888472/contact/7288801) that could be implemented using reactji:

> So, during the "grouping" stage, we had quite a lot of items. My team sits in front of a TV during this stage because we want to discuss the items, and after the grouping, each team member is voting at his desk. At some point, it was difficult to know what card was already discussed, because the cards are moving in an unpredictable way if you are grouping two cards. I guess, one option is for the cards to stay fixed, or to have some kind of checkbox to mark it as "read" (and the colour changes).

**Comment by ackernaut** [comment]
From a [user](https://app.hubspot.com/sales/3888472/contact/6507651) re: reactji feature feedback:
>More emojis plz!

**Comment by ackernaut** [comment]
Here’s [the Figma doc](https://www.figma.com/file/GeEy1MNpxhFn9m0w9QKtOo/Reactji?node-id=1%3A14) with very early concepts and a raw idea

**Comment by jordanh** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/1274051) writes:

> [We want] basic emoji reactions on ideas and action items

**Comment by jordanh** [comment]
@ackernaut can you write an implementation issue for this?

**Comment by ackernaut** [comment]
I think that in the abstract a group of reflections is really a thread of comments. It seems safe to say that usually the top comment leads the discussion, but is still just another comment. In this case I think that comments (contextually, reflections) get reactji. Perhaps we explore “make this the top comment” when a single comment really captures the intent of the thread.

**Comment by ackernaut** [comment]
Going to close this in favor of #3437 and #3438
