### ISSUE TITLE
Empty state vs. loading state

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#306]
Open discussion on how to handle the empty state before the subs load:
Let's use the Action List as an example:

When `actions.length === 0` We show a single item saying you don't have any items.
There are 2 scenarios where this happens:
- The user doesn't have any actions
- The user's actions haven't loaded yet

The latter is ugly, because that means it flashes the empty state & then begins loading the actions once they start coming in.

There are a few things we could do:
- Show loading state (nothing?) until a query returns stating how many actions there are. if actions.length === 0, then show empty state. This is a little expensive since it's another hit to the DB & another round trip
- Same as above, but have the subscription return the length from the server. This reduces the extra upstream message & extra query, but still hits the DB. This gets tricky because we tell GraphQL that the `actions` subscription will return a list of actions, so instead we'd send it through the pubsub using our custom protocol. maybe `add, remove, update, READY`. Then our subscriber listens for `payload.ready`.
- wait for the socket to subscribe to the channel. This is cheap, but this will return before a doc does, so it essentially just shortens the duration of the flash.
- do nothing
- if actions.length === 0, show loading state for 2-3 seconds. not very robust, but very simple.
- ???

@jordanh @ackernaut thoughts?

**Comment by ackernaut** [comment]
I think a loading state makes sense when there is a reasonable wait time. I’m not sure about the costs of hitting the DB. I can design loading states if needed. :)

**Comment by jordanh** [comment]
Off the cuff: are counts on indexes cheap in rethinkdb? If so, we could pop a loader by default but always query the item count first. If item count == 0, then we display empty state...

**Comment by mattkrick** [comment]
I'm beginning to solve this.
Here's how I did it for actions:

- call an `actionCount` query that returns an integer alongside the `actions @live` subscription
- if the `actionCount === null` then show loading state
- if the `actionCount === 0` then show empty state

this pattern can be used to solve #757, among all other cases.
