### ISSUE TITLE
Org lock-out UI state designed

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#3063]
Coming out of S.P.A. 12, we felt the need to design and implement the ability to disable an org when it’s over the limit and is unresponsive to the sales team. Notes:
- This is not automatic, it’s a mutation ran by the sales role
- Members of the org can’t access any teams on the org
- Members of the org can’t use the meeting lobby for the org’s teams
- Members can still see their timeline and meeting summaries
- Members can still see the tasks from their My Dashboard view
- Members can still see teams from other free/unlocked orgs
### AC
- Artifacts showing:
  - Disabled state of dashboard navigation
  - Disabled state of team dashboard
  - Disabled state of team meeting lobby
- Implementation issues written
### EE
- 11 points

**Comment by jordanh** [comment]
This is very likely to come back. But for now, we'll icebox it
