### ISSUE TITLE
update checkin questions

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#3066]
If you were going to be frozen tomorrow for a one-way 1000-year interstellar voyage, what would you most want to communicate (and to whom) before you leave?
What’s the most important thing to remember daily that you haven’t been able to?
What help could you most use that you haven’t asked for?
What is your one piece of advice to everyone here?
What was the last thing you fell in love with?
When was the last time you felt unbounded optimism?
Who was the last person you felt inspired by?
What simple thing still blows your mind?
What sparked your curiosity in whatever you’re most curious about now?
If you could know the absolute and total truth to one question, what question would you ask?
Which question can you ask to find out the most about a person?
What color best describes your personality today?

from: https://lamaalrajih.com/2019/07/24/skip-the-small-talk-part-one/

AC
- [ ] questions added

effort: 10.5

**Comment by jordanh** [comment]
Pared down the above question list to be more evergreen (i.e. they can be asked over and over again and not get boring).

Made me think, we could later enhance our question lists to have 2 groups of question types: evergreen and single-use. We'd roll the the single-use questions once and then only cycle through the evergreen questions ever after.

What do you think of that?

**Comment by mattkrick** [comment]
i like that. in a perfect world, each question has `text, viewCount, maxViews`. when viewCount >= maxViews, you no longer see it. first we gotta validate the long term viability of the phase though...
