### ISSUE TITLE
push invitation: jordan didn't get a snackbar

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#3067]
Repro
- [ ] 3 people in meeting, new person hits meeting url, everyone but facilitator sees push invitation

Effort: 11

**Comment by jordanh** [comment]
AC:
   - facilitator sees snackbar too

EE: 10.5 points

**Comment by mattkrick** [comment]
can't reproduce, writing it off as a network hiccup.
the message sent to all is _not_ robust, nor is the message persisted anywhere, so if your network hiccups at the perfect time, you'll never see the invite.
reason for this is architecture is
- if someone hit your team page w/o a mass invite token, it's reasonable that they can't get in. it's just a nice to have.
- everyone on the team gets the message, but only one needs to answer. chances of everyone having a hiccup? pretty low
- if this were persisted, it's possible the message outlives the time that the requestor stays on the page invitation-required page
