### ISSUE TITLE
Projects do not change when switching between teams

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#307]
## Issue - Bug

Encountering this on [action-staging](https://action-staging.parabol.co), it looks like it could be a reprisal of #187:

![screencast](http://g.recordit.co/8O0aYz3ge4.gif)

Steps to reproduce:

1. Create second team via `/welcome` wizard
2. Switch between old project team and new project team
3. Observe projects from old project team appear in columns where new projects shoudl be

- **OS:** OSX
- **Browser:** Chrome
- **Estimated effort:** 2 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Note: reloading the browser window on the desired team route _does_ load the correct projects for the team.

**Comment by mattkrick** [comment]
fix in the latest me-dash-dos
