### ISSUE TITLE
TypeError: Cannot read property 'children' of undefined

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#3071]
## Issue - Bug

[A user ](https://app.hubspot.com/contacts/3888472/contact/5290451) is unable to access one of their teams from their dashboard, preventing them from accessing their task cards or (easily) running a new meeting.

Here is the exception they are encountering when they access [this URL](https://action.parabol.co/team/tb-f9bvkp-):

```
breadcrumbs.js:58 TypeError: Cannot read property 'children' of undefined
    at E (convertFromRawToDraftState.js:178)
    at t.exports (convertFromRawToDraftState.js:215)
    at NullableTask.tsx:31
    at Object.useMemo (react-dom.production.min.js:159)
    at useMemo (react.production.min.js:23)
    at i.a.memo.isPreview (NullableTask.tsx:30)
    at Yo (react-dom.production.min.js:150)
    at Ai (react-dom.production.min.js:178)
```

#### Screenshot

![unnamed (1)](https://user-images.githubusercontent.com/103000/62156961-e95a8780-b2c0-11e9-97a1-9f1fc7340957.png)

- **OS:** macOS / Linux / Windows / ?
- **Browser:** Chrome / Safari / Lynx / ? + version
- **Node version:** `node --version`
- **NPM version:** `npm --version`
- **RethinkDB version:** `rethinkdb --version`
- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### Acceptance Criteria (optional)
Users can:
   - fixup database so user may access their team
   - quick triage of root cause, if warranting a fix create a new issue to fix generally so that it may be prioritized appropriately

**Comment by mattkrick** [comment]
root cause unknown.

somehow, a task was updated to be an invalid draft-js document.

i deleted that task (it was empty) and now it's fine

next steps:
- [ ] on the server, do better validation/normalization for task updates
- [ ] on the client, try to wrap a Nullable Card in an Error Component so it just borks the card, not the whole app
