### ISSUE TITLE
Meeting content header redesigned for mobile

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#3077]
Before we get a bunch of traffic, we need to make a better impression on mobile users:

AC
- [x] The facilitator bar looks good on all devices
- [x] The meeting content header looks good on all devices
- [x] Toggles meeting participant (team) #2689

Effort: 12 points

**Comment by jordanh** [comment]
Is this a design issue?

**Comment by mattkrick** [comment]
yeah, i think just the 2nd one needs to be addressed. we'll need to restyle the action meeting top bar to match the retro & then make them both mobile friendly

**Comment by ackernaut** [comment]
Writing an implementation issue at #3141 with a link to notes and Figma concepts

**Comment by ackernaut** [comment]
Closed with new issues:
- #3178
- #3179
- #3180
- #3181
- #3182
- #3183
- #3184
- #3185
