### ISSUE TITLE
Add beta signup link to readme

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#308]
## Issue - Enhancement

An issue to track this work item :)

- **Estimated effort:** 1 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
should we update the copy before we unleash it to the github crowd or is it good as is?
http://www.parabol.co/beta/
