### ISSUE TITLE
Change reflection width to 296

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#3089]
reflection widths are stuck at 320 today.
some devices only have 320 pixels.
this breaks our card policy: https://app.getguru.com/card/cBb5rG9i/Card-layout-specs

AC
- [ ] reflection cards look good on a mobile device with a width of 320

Effort: 11 points

**Comment by ackernaut** [comment]
I bumped down the size of the reflections and inputs, but a viewport at `320` still doesn’t have enough room for a card at `296` with the inner and outer gutters of the swipeable columns

**Comment by jordanh** [comment]
Implemented in swipe-able columns PR
