### ISSUE TITLE
track down mem leak introduced in 3.16.0

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#3091]
v3.16.0 introduced a memory leak.

AC
- [ ] audit all server code, diffing v3.15 and v3.16

effort: 11 points

**Comment by mattkrick** [comment]
changes
- getEntitiesFromText, getSyntaxFromText no longer have try/catch wrappers
- acceptTeamInvitation accepts & verifies a massInviteToken
- createTask was refactored & has better validation
- disconnectSocket fixed promoting a new facilitator if one leaves & doesn't come back
- updateTask was refactored & now ignores sending snacks to in-meeting mentionees
- Team now signs & sends a massInviteToken upon request
- bumped graphql version
- bumped google NLP packaged
- fixed bug where we didn't correctly send tags to sentry

of all the changes, the sentry one is the only one that makes sense to me. if that doesn't fix it, we'll have to go back to this list though.

AC for fix
- [ ] CPU, system memory, and network traffic return to normal levels

**Comment by jordanh** [comment]
Note: it was the changes related to sentry tags!

**Comment by mattkrick** [comment]
> bumped google NLP packaged

running locally, i was able to reproduce a small leak by hitting the google client repeatedly.
i replaced google's client lib with a dumb rest call + JWT solution, which i found buried in the docs here: https://developers.google.com/identity/protocols/OAuth2ServiceAccount
