### ISSUE TITLE
Loading states

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#310]
# Enhancement

As we see spaces in the UI fill up with content (actions, cards, oh my) there is a difference between empty (not loaded) and empty (no Thangs™). A few views that come to mind:
- Project column (loading projects)
- Action list (loading actions)
- Archive (loading archived projects)
- Project card (loading details? there’s not much there ATM but later on if there is markdown etc. it may take a second to load and/or format)

Questions/assumptions:
- Is there a general pattern that needs to be implemented to help loading contexts across the app?
- We then take care of each space/component case by case for specific UI/UX?

**Estimated effort:** 3 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
Oh I'm so glad you brought this up. In the wonderful world of websockets, this becomes a pretty complicated issue. Allow me to explain why:
- Sometimes, we don't know if any items will come (eg Actions) This is called a "0 or many"
- Sometimes, we know at least 1 item will come (eg TeamMembers). This is called a "1 or many"
- Sometimes, we want to know when all initial items have arrived (eg all 4 team members, render). This is loading all at once vs. 1 at a time
