### ISSUE TITLE
Pay dialog updates implemented

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#3103]
Based on design efforts from #3059 (see [Figma](https://www.figma.com/file/GW38GQlJ8H5LyHKgpfUZ0S/Pay-Now-or-Later-Dialog?node-id=15%3A4526))
### Acceptance Criteria
- Dialog is mobile-first
- Lead content is a quote, we should pull 3+ that show randomly (need to get copy, avatar, name/title — look for new quote content from Tim)
- Code the feature bullets for possible A/B content (stored away as a styled component)
- Header has `info` icon that links to `/pricing`
- Form lead line is Stripe message by default
- Form lead line changes to single warning or multiple warning `A few fields need review` or something similar (the goal is just to keep it to a single line)
- The CC brand icon shows top right once it’s been verified, will need new SVGs at a base color that can be adjusted with opacity
- The form has a minimal cost breakdown table: `no. active users` `$6/ea` `$total/mo`
- Retained cc, expy, and cvc fields (no change)
- Primary action is `Upgrade Now`
- In the org billing view we only offer the primary action “Upgrade Now” and we don’t use the squeeze mode with the secondary action, even if it has been set to show in this org’s meetings.
- Secondary action is available `Upgrade Later` when in squeeze mode
   - When 'Upgrade Later' is hit a new segment event with the following format:
      - `name:` `Upgrade Later Clicked`
      - with traits set for the viewer (i.e. the clicker)
- Success has updated content and back to business secondary action
- Opt to pay later shows the stick confirmation view: X meetings remaining, over the 2 team limit, we’ll send an email, back to business
  - Data is added to the org `meetingsRemaining` that informs the X meetings countdown
  - Segment event is sent `Meetings Remaining` and count that informs us when folks are wanting to convert for fear of losing access
- This dialog (or a set of mostly shared components) can be used in upgrade-only mode when visiting the organization view
- This dialog (or a set of mostly shared components) can be used in squeeze mode with the upgrade later option during the high value moment (e.g. before Discuss phase or before Starting a Meeting with everybody waiting to begin)
#### Notes
- Tapping upgrade later sends an email to everybody in the org, anybody in the org can upgrade and becomes a billing leader. This happens every time somebody from the org taps upgrade later. Note: we should a/b test sending to all vs. sending to who clicked
- The squeeze mode context is triggered manually by a mutation from sales lead
- We need a lock-out org state design #3063 

### Estimated Effort
- 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
Needs
- quotes w/ pics, names, titles
- feels weird that squeeze mode is triggered manually instead of contextually. visiting the billing page after i've been squeezed once should probably not yield squeeze mode
- what does the "update billing info" modal look like?

**Comment by ackernaut** [comment]
@mattkrick I’ll pull together the quotes and I’ll push on some more mobile-first org views/states like updating billing or downgraded with invoices, etc.

As for the second bullet re: squeeze mode. I think that in the billing view we only use the default mode. The squeeze mode only shows up in the high-value moment (starting a meeting or starting the discuss phase are the 2 best that I can think of so far).

**Comment by ackernaut** [comment]
I added a bullet to the AC:
>In the org billing view we only offer the primary action “Upgrade Now” and we don’t use the squeeze mode with the secondary action, even if it has been set to show in this org’s meetings.

**Comment by ackernaut** [comment]
Latest re: billing views and components [here](https://www.figma.com/file/GW38GQlJ8H5LyHKgpfUZ0S?node-id=75%3A6728&utm_campaign=team&utm_source=slack&utm_medium=message&utm_content=file_comment#9697691) and [here](https://www.figma.com/file/GW38GQlJ8H5LyHKgpfUZ0S?node-id=1%3A604&utm_campaign=team&utm_source=slack&utm_medium=message&utm_content=file_comment#9695672)

**Comment by mattkrick** [comment]
STUCK ON:
- Upgrade later email. Where is it & how do I send it?
- Cannot implement meetings remaining until we have a plan for when that number hits 0. IMO, we should ditch that req & keep the process manual.

**Comment by ackernaut** [comment]
@mattkrick I’ll get started on a draft of the email. Is this a template we maintain and send, like invites and summaries? I think JH and I had discussed not worrying about what happens when it hits 0, that we could adjust once we start seeing that. It’ll be up to the sales lead I suppose, to manually disable the org or subset of teams based on seeing that info.

**Comment by mattkrick** [comment]
i think @jordanh wanted to do it in hubspot, but i'm not sure if we can call the hubspot API to do that. @jordanh can you confirm?

**Comment by jordanh** [comment]
All I need is the `Upgrade Later Clicked` event with who clicked it and the number of free meetings remaining as props and I can take it from there in Hubspot. @ackernaut no need to draft anything

**Comment by mattkrick** [comment]
@jordanh wouldn't you need everyone in the org? are we still thinking about sending it to every org member? also, will it go out automatically? need to know if i can say "we sent you an email"

**Comment by jordanh** [comment]
Plan was to only hit clicker, but hit entire org with banner via manual mutation. Let's start herr, we can always do more...
