### ISSUE TITLE
Refactor group masonry grid to columns

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#3126]
Based off #3094 (see [this](https://www.figma.com/file/0lOTlvsj87GBFFzgee9OkVWi/Meeting-Layout?node-id=340%3A9968) and other frames in Figma)

AC
- [ ] top of each column has an add button allowing you add a new reflection
- [ ] there's no description in the header
- [ ] the columns scroll individually, similar to the task kanban
- [ ] cancel logic: if the drop target is the same as the drag source, it's a cancel
- [ ] cancel logic: if there's 1 reflection in the group that's being dragged & it's not dropped on another group, it's a cancel
- [ ] ungroup logic: if the drag source group has more than 1 reflection & the drag source is dropped on anything but another group, it's an ungroup
- [ ] ungroups go back to their prompt column
- [ ] there is no "description" in the column header
- [ ] column header title is sticky on top when scrolled
- [ ] a draggable card is read only by default. clicking the card once makes it editable. the card cannot be dragged while it is editable. to re-enable readonly, the card must lose focus

(next up: prompt colors implemented #3124)

fixes #3034
 
Effort: 13 points

**Comment by mattkrick** [comment]
TEST
messages:
- start, end works as expected
- start only: end is called locally if no update is received for 5 seconds
- end only: animates from A to B  
- end, start a buffer of ends without starts is kept. if a start has a drag id that is in the buffer, then it is ignored. 
- startA, startB, endA, endB: if startB loses conflict, it's ignored, so it becomes startA, endA, then a separate end only endB. if startB wins conflict then endA is applied to startB and endB separate.

- basic rule is to always trust an end event. if possible, tie it to the start event in progress, even if the drag IDs don't match. this is because the end events represent the data as it exists in the DB.

**Comment by mattkrick** [comment]
UI for the grouping is getting to be a little heavy.
So far, a single click can accomplish the following:
- drag
- edit card, if owner
- edit group title
- expand group
- show single-card group title

i think we may need a button to make it feel more intuitive. but, here's the proposal:

- before mouse up, if the cursor moves 3+ pixels, call it a drag & not a click
- if it's a click on a single card that the viewer owns, focus the card, show the group title, show delete button
- if it's a click on a single card that the viewer doesn't own, show & focus the group title
- if it's a click on 2+ cards, expand the group

then, we need to fix the logic around the single group titles.

**Comment by ackernaut** [comment]
@mattkrick thanks for noting re: UI, let me know what you need
