### ISSUE TITLE
GraphQLError: Cannot read property 'creditCard' of null

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#3134]
## Bug

It looks like the new upgrade modal might not be capturing all the information correctly and invoice generation regressed. See:

https://sentry.io/organizations/parabol/issues/1194166012/?referrer=github_plugin

```
GraphQLError: Cannot read property 'creditCard' of null
  File "app:///billing/helpers/generateInvoice.ts", line 359, in generateInvoice
    creditCard: organization.creditCard,
  ?, in async Promise.all
  File "app:///../client/utils/resolvePromiseObj.js", line 11, in resolvePromiseObj
    const values = await Promise.all(promises)
  File "app:///graphql/mutations/stripeCreateInvoice.js", line 29, in resolve
    await resolvePromiseObj({
```

Repro steps:

1. Upgrade org via `4242 ...` credit card to Pro
2. Wait a bit, observe server exception

## AC

1. Can upgrade to pro and invoice generate without exception

## EE

Points: 10.5

**Comment by mattkrick** [comment]
that invoice lives on staging. the bug would occur if don't have ultrahook open
