### ISSUE TITLE
Implement Enterprise SSO and SAML

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#3138]
## Issue - Enhancement

The trigger for implementing this will be an enterprise sale requiring SSO and SAML

### JTBD

As an enterprise IT admin, when users use Parabol, I want to use my enterprise authentication directory, so that I can control access to third-party applications in the way that I'm used to

#### Admin setup for SAML

1. An enterprise customer creates a DNS CNAME record like `parabol.enterprise.com` pointing to action.parabol.co
1. Using Active Directory Federation Services as an example, here's what an admin must do: https://auth0.com/docs/connections/enterprise/adfs
1. They must give us the proper URLs, metadata, and/or X.509 certificate to complete setting up the SAML connection

#### Parabol Admin setup

1. An enterprise `Organization` record is mutated to contain 1 or more `SSO hosts` which map to a single `SSO Auth0 Connection`

For example consider the `Organization`:

```json
{
   "id": "abc123",
   "SSOHosts": [ "parabol.enterprise.com" ],
   "SSOAuth0Connection": "adfs:enterprise.com"
}
```

2. An auth0 enterprise connection must also be created using the connection name `adfs:enterprise.com`: https://manage.auth0.com/dashboard/us/parabol-action/connections/enterprise

#### If a user lands at action.parabol.co

1. A user sees a link "Sign in with SSO", when a user clicks it they are taken to a new page with a form asking for only their email address
(https://trello.com/login/sso?returnUrl=%2F) for an example)
1. Their email address is used to look up matching `Organization` data, if the domain matches a known SSO domain, we redirect them to auth0's universal login endpoint (see **SSO login**, below)

N.B. we only support one SSO connection per user email for now, in the future if users have more than one we can return multiple login options

#### If a user accesses parabol.enterprise.com

1. When the Parabol server is accessed from a host not matching the server's domain (i.e. `parabol.co`, we lookup the custom login domain in our database (probably kept on the `Organization` table). If found, we map this to a auth0 `CONNECTION` name
1. We redirect them to auth0's universal login endpoint (see **SSO login**, below)

#### SSO login

1. When a user is redirected to auth0 endpoint, the form of this redirect follows:

https://login.parabol.co/authorize?response_type=token&client_id=2H141TYegZ6100G2bv6PSskgkBHI5tRw&connection=CONNECTION&redirect_uri=https://action.parabol.co&state=STATE

...where `CONNECTION` above is replaced with the user's auth0 SSO connection name from our database

2. auth0 will then redirect handle the authentication with the appropriate SAML endpoint and return our application a JWT

### Research

The current auth0 party line is to use auth0's "Universal Login" to support the SSO login flow. Theoretically, we could also use the auth0.js client-side library but I think we have enough evidence that it's garbage-y and not to be trusted. Even auth0 says to avoid using this library for SSO.

Here are some related docs to look over:

- https://auth0.com/docs/universal-login
- https://auth0.com/docs/universal-login/new
- https://auth0.com/docs/protocols/saml
- https://auth0.com/docs/connections/enterprise/adfs

**Comment by mattkrick** [comment]
I'd prefer to do this without auth0.
Here's how I'd propose it:
- we get the SAML metadata from the client
- preferably they give us a guest account to test (may require vpn)

Then, the flow looks like this:
- their SSO request hits parabol
- parabol looks up their idp metadata & forward them accordingly
- they login via their idp
- their idp sends parabol the assertion
- parabol turns that assertion into a JWT & returns it to the client

**Comment by jordanh** [comment]
Sounds like a plan to me. I'll make it a part of our ask to get an account for testing. Likely we can do it without the VPN.

Easy enough to ask him to configure their auth provider to hit our endpoint instead of auth0.

**Comment by mattkrick** [comment]
more thoughts:
- asking for an email is lame. they may already be logged in. all we need is to know what idp to hit. we could do this via url. say `parabol.co/login/:idp`

so new thinking:
- client goes to parabol.co/login/:idp
- server receives request, looks up the redirect url for that idp, & responds with a redirect: e.g. `parabol.enterprise.co/login`.
- client is redirected to the idp. what happens here is a blackbox & we don't care, as long as it returns a redirect with an assertion. it'll probably show a login screen if they haven't logged in, or it'll immediately respond with the assertion.
- the idp server creates an assertion & redirects to parabol.co/saml/:idp?key=foo
- the client is redirected to that url
- the parabol server receives the assertion, which includes the user email (and ideally photo url). it verifies the payload with the X.509 certificate. the server then looks up the user by email. if no user exists, it creates one. if user does exist, it ensures that the user has that IDP listed. that way an IDP can't claim an email that doesn't belong to it.

**Comment by mattkrick** [comment]
extra thoughts:
- if they log out of their idp, should it log them out of parabol? if so, we'll need to add a jwtBlacklist to the user. we should do that anyways, but we'll prioritize it if they want it.
- if they log out of parabol, should it log them out of their idP? This is called single log out (SLO). if they want this, they'll need to provide us with a logout endpoint to call. ideally that would come with the assertion.
- our "login with sso" doesn't need the tld or the email address, just the company name.

Things we need from them:
- guest account to test
- issuer url (e.g. parabol.enterprise.co/idp). optional since they'll be providing us with a X.509, but nice to have.
- X.509 certificate (yep, even for ADFS) 
- example saml assertion


Things we need to provide them (they may tell us more things they need):
- Assertion Consumer Service (ACS): this is the redirect url. eg `parabol.co/saml/:idp` where idp is their name

**Comment by mattkrick** [comment]
implemented awhile ago
