### ISSUE TITLE
Support enterprise tier

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#3142]
AC
- [x] a `draftEnterpriseInvoice(orgId, seatCount, email?)` internal mutation exists. it creates a stripe customer, subscription & invoice. it sends the invoice to to email OR billing leader, if email is empty. it attached the orgId to the objects in stripe. it attaches the stripe object ids to the org in our system.
- [x]  calls to adjustUserCount support enterprise (@jordanh are we using proration for enterprise?)
- [x] billing details view supports a null creditcard (could be ACH or 14 other things)
- [ ] stripeSucceedPayment checks the subscription of the payment. if it's an enterprise subscription & the org is not enterprise, it flags the org as enterprise & all its teams, thus completing the enterprise upgrade flow
- [ ] stripeCreateInvoice supports generating enterprise invoices (stuck behind #3152)
- [ ] the billing view correctly shows the invoice and upcoming invoice
- [ ] pause/unpause users is disabled on enterprise org users (for changing subscriptions)
- [ ] pause/unpause toggles are hidden & the underlying server mutation is disabled  for enterprise

Effort 11

**Comment by jordanh** [comment]
May we discuss these AC? To avoid reworking things down the road, I'd like to modify the workflow on our early stages.

Here's how I envision this conversion pathway going for the next while:

1. An enterprise deal advances to "In Negotiation" and we drop them a quote for their pricing tier and addn'l setup charges (e.g. customer integrations, SAML setup support, etc.)
2. When the quote is accepted, paper is signed and we issue them an invoice
3. We mark the deal as "Won" in Hubspot and immediately create a task 11 months out to service the deal
4. On stripe, we manually:
   - Create a new customer record
   - Create a new subscription
5. On Parabol, we call a mutation to upgrade the account, it:
   - Upgrades the org to 'enterprise' tier
   - Links the subscription to display invoice information

Open question for me:

   - How do we handle the migration of user data? If I started with an auth0 id of `auth0|abc123...` or `google-oauth2|deadb33f...` and I log in using SAML do I have to sign up as a new user? Or, do we somehow migrate the data automatically? Or, do we manually migrate the data using a mutation we write (see: #3140)?

We should probably discuss this ASAP...

**Comment by mattkrick** [comment]
i'd like to combine 4 & 5 to reduce work. creating a subscription on stripe before we create it in parabol is really bad news. we add a lot of metadata on both sides. 

SAML usurps non-saml users:
- i create a user with email/pass
- my company goes saml
- i try logging in with my email/pass & get redirected to saml login

behind the scenes, it goes like this:
- i blur the email form field / click log in
- client asks parabol if the email belongs to SAML
- if yes, redirect to SAML
- if no, continue logging in with auth0

since the user is still under auth0, metadata updates are still sent to auth0.
however, auth0 has no knowledge of them logging in

**Comment by jordanh** [comment]
> SAML usurps non-saml users:
>
> i create a user with email/pass
> my company goes saml
> i try logging in with my email/pass & get redirected to saml login

Are you using the word usurp, just so you don't write out the word trump? 👅 

All joking aside, this is a very good idea. I like it. What's the format of a user-id if they don't exist in parabol yet? `parabol|abc123` or `saml|abc123` or `orgid|abc123` or something else?

**Comment by mattkrick** [comment]
`sso|123`

the edge case is for oauth2 users. there's no way to catch them before they go through auth0. we can catch them on the server & then send an error message to the client, but if the company uses google as an email provider, then i really don't see the difference in them using oauth2 vs. saml. same account, different protocol, should be AOK. ya?

**Comment by jordanh** [comment]
Yeah, should be AOK

**Comment by mattkrick** [comment]
@jordanh @ackernaut  AC revised. open for comments!

**Comment by mattkrick** [comment]
Moving forward & setting proration to `false` for enterprise tier.
That means when the year & the cost for the new year is calculated, no extra cost OR refund is attached.

Example:
- Org buys 100 licenses, at month 6 hits grows to 500. They still pay for the 100 & get the 400 free. When the subscription renews, it renews at the cost of 500 licenses.
- Org buys 100 licenses, at month 6 shrink to 1. They still pay for the 100. Renews at the cost of 1 license.

happy to send segment events when they're over tier (eg enterprise X is over their limit by Y licenses), but will wait until asked to do so.

**Comment by mattkrick** [comment]
The subscription should begin when the invoice is paid, _not_ when it's created.
To accomplish this, the following workflow is used:
- subscription is created with a 60 day trial
- invoice is sent with a due date of 60 days
- when invoice is paid, trial is set to 0

**Comment by jordanh** [comment]
> The subscription should begin when the invoice is paid, not when it's created.
> To accomplish this, the following workflow is used:

@mattkrick I think we can simplify this

Here's the flow from the business side:

1. Lead is pitched Enterprise version and quote and agreement is sent from Hubspot
2. When quote is accepted (verbally or via email), Lead's finance department issues a purchase order
3. When purchase order is sent, trust is established between Parabol and the new Customer

What I imagine happens here is:

  - Customer record, subscription, and invoice are created on Stripe
  - Mutation is called to upgrade user to `enterprise`

What chu think?

**Comment by jordanh** [comment]
> I propose we ignore it until an enterprise takes advantage of our kindness, we reach out, and they're unresponsive. Most likely, we notify them, they remove some consultants from the org that haven't been using it, and then they're back in action.

Totes agree

**Comment by mattkrick** [comment]
just following up with the actual implementation:

1. Lead is pitched Enterprise version and quote and agreement is sent from Hubspot
2. When quote is accepted (verbally or via email), Lead's finance department issues a purchase order
3. When purchase order is sent, trust is established between Parabol and the new Customer
4. confirmation for which `orgId` to upgrade is received by lead
5. existing teams to migrate to `orgId` is received by lead  
6. all company teams are moved to that orgId by calling `moveTeamToOrg`
7. org is upgraded when parabol calls `draftEnterpriseInvoice` endpoint for that orgId
8. sales ensures that payment is received within 30 days & if not, org is reverted.
