### ISSUE TITLE
SSO Burndown

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#3144]
limitations:
- a user created with sso will always be sso.  
  - if they leave the company, then they lose access. a workaround is to create a new org & user, invite the user to the new org & transfer tasks (in the future: teams) to the new org.
  - if the company downgrades from SSO, then access is lost. this is no different than signing in with google & then deleting your gmail.

to do:
- [x] do not update auth0 when the user is SSO
- [x]  creating/logging in using oauth/password for a domain under SSO results in a redirect to the IdP
- [x] team invitations (sign ins & create accounts) both redirect to the IdP with an "isInvited" relay state
- [x] mass invitations use generic authentication & simply include a massInvitationToken
- [x] if the consumer endpoint returns a token or null. if null, then an error is shown on the login. if token, then the client checks for invitation token. if exists, it accepts. then, it redirects to the redirectTo

**Comment by jordanh** [comment]
I'm going to put this at the top of the current sprint
