### ISSUE TITLE
Enterprise invoice CSS updates

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#3152]
See: https://github.com/ParabolInc/action/pull/3158 for current implementation

AC
No Figma design required, we think we can jump straight to implementation

- [ ] Current invoice implementation updated to match Parabol brand standards

effort: 12 points

EDITS: @jordanh adjusted AC

**Comment by ackernaut** [comment]
Just to clarify, if I’ve upgraded a local org to Enterprise via mutation (which I have), then I should see an invoice after paying with the fake CC in about an hour, and should style any related Enterprise details beyond where they are currently?

**Comment by mattkrick** [comment]
if you've got your webhooks set up correctly, yes. sometimes stripe takes more than an hour though. cloning will be a lot faster
