### ISSUE TITLE
Design Discount line in invoices

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#3153]
AC
- [ ] Our invoices support a line for discounts, if any are present. it's probably a line between subtotal & total & probably in red
- [ ] Implementation made directly on branch, or, design made in Figma and implementation issue created

Effort: 12 points

**Comment by jordanh** [comment]
@ackernaut it can be helpful to see how discounts are applied in Stripe to see how to design this. Tap me or @mattkrick if you want this input

**Comment by ackernaut** [comment]
I assume it’s possible for me to add a test discount using the test admin mode in the Stripe admin and apply it to my own local user?

**Comment by mattkrick** [comment]
sure, as long as it's using test data it's all good!
