### ISSUE TITLE
Bug: new user joins, meeting view doesn’t update for others

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#3232]
### Repro
- Start a meeting with User A
- Send an invite
- Create a brand new user
- User A doesn’t see the new user join; it requires a hard refresh

(Note: this may be happening on the dashboard, too. I just reproduced it from an active meeting.)

### AC
- When a new user joins, all viewers see the new user
### EE
- 10.5pts

**Comment by mattkrick** [comment]
cannot reproduce. was this bug found locally? if so it could just be the server restarting or the subscription ending

**Comment by ackernaut** [comment]
I will test on dev or staging, thanks for the note

**Comment by ackernaut** [comment]
Ok, tested on `action-staging` at `v4.8.1` and was not able to reproduce
