### ISSUE TITLE
Read-only reflections once Vote phase has been reached

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#3236]
### Repro Steps
- Start a Retro, make it to the Vote phase
- Open a stack of cards to the dialog in the Reflect or Group phase
- The cards are not read-only in the dialog

### Acceptance Criteria
- Set the cards to read-only in the dialog once the Vote phase has been reached

### Estimated Effort
- 10.5pts

**Comment by mattkrick** [comment]
can't reproduce, there is probably some nuance here

**Comment by ackernaut** [comment]
I’ll try to reproduce again.

**Comment by ackernaut** [comment]
Reproduced on staging a v4.9.0

I went back to the group phase from the vote phase with a non-facilitator, opened a group, and tried editing a card:

![Screenshot 2019-10-31 17 16 23](https://user-images.githubusercontent.com/307286/67989886-3d4b7400-fc02-11e9-83e4-e90057491b8f.png)

**Comment by jordanh** [comment]
@mattkrick @ackernaut has updated reproduction steps. Mind taking another look?
