### ISSUE TITLE
Configurable meeting process checklist

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#324]
## Issue - Enhancement

This is a step toward adding in actual embeddable metrics into the product.

When a team holds their weekly action meeting, they'll want to add in additional sections to surface data – such as a metrics review, so that they can create good agenda items.

I propose we create team settings allowing for an optional section to be added called "Checklist".

If that section is enabled, a series of check list items can be added. For example, "Weekly metrics review" could be an item.
- **Estimated effort:** 10 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
Ah we can merge this and #330 ...and continuing exploring UX/UI.
