### ISSUE TITLE
Separate server and client sentry DSNs

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#3247]
## Issue - Enhancement

In order to better prioritize making bug fixes, it'd be better if we separate our server and client bug reports.

I've gone on to create the project in sentry, but we need to separate out our environment variables.

### Acceptance Criteria (optional)
We can:
   - Set `SENTRY_DSN_SERVER` to configure the server project destination
   - Set `SENTRY_DSN_CLIENT` to configure the server project destination
   - Remove the old `SENTRY_DSN` environment variable

- **Estimated effort:** 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
Looks like we can't query across multiple DSNs unless we upgrade.

A wonderful way to mitigate this issue is to simply use the `environment` flag.

Moving forward, we'll have 2 environments. "server" and "client". then, we can search across both without giving sentry more $$.
