### ISSUE TITLE
Customize number of votes during Vote phase

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#3249]
## Issue - Enhancement

Tracking users who'd like to be able to customize how many votes each participant receives during the vote phase.

### Acceptance Criteria (optional)

Sketching some AC here as feedback comes in.

The facilitator can:
   - have a reasonable number of votes selected for them based upon the number of groups to vote for
   - adjust the number of votes upward (no backsies)

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
A user writes:

> Since we had so many different topics, I would have preferred to offer more votes per person (e.g. 10 instead of 5) or may be even to have the possibility to customize the number of votes and decide on it each time anew.

**Comment by mattkrick** [comment]
https://retrospective.tools/#parabol

this seems like an easy win to get another checkmark

Customisable Dot Voting
--




Customisable Dot Voting
--

**Comment by mattkrick** [comment]
the backend is already designed to support this. all that's needed is the input boxes.

closing this in favor of a design issue
