### ISSUE TITLE
Fatal crash when # editor suggestions empty

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#3272]
## Issue - Bug

Repro steps:

1. Make a new card
2. Begin typing `#` and then continue typing a character that isn't `a` or `p`, such as `3`
3. See crash

- **OS:** macOS
- **Estimated effort:** 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### Acceptance Criteria (optional)
Users can:
   - Type whatever they like after `#`

**Comment by mattkrick** [comment]
fix in #3273
