### ISSUE TITLE
Demo summary when signed in

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#3278]
### AC
I would expect to see “Go to My Dashboard” or similar instead of “Create Free Account” when I’m already signed in.

### EE
- 10.5pts

_Originally posted by @ackernaut in https://github.com/ParabolInc/action/issues/3275#issuecomment-542417467_

**Comment by mikennaji** [comment]
Ideally,
 If they are logged in this should be shown instead and they are redirected to the dashboard on the click.
![go to my dashboard](https://user-images.githubusercontent.com/11260020/67875432-b799cc80-fb0c-11e9-97f3-cafe39fbb769.jpg)
