### ISSUE TITLE
Remove Auth0

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#3298]
auth0 no longer provides enough value to keep it.

Migration strategy:
- Phase 1) Add Authentication table & have all new signups use it. When people log in, first check our Authentication DB. if not found, then check the auth0 table.
- Phase 2) Load all emails & hashes in our DB. add flags (sentry) for users who have to fall back to auth0.
- Phase 3) Remove auth0 fallback & cancel service 

AC
- [ ] request emails & hashes from auth0. put them in their own "Authentication" table (this is probably cleaner than putting them on the User table)
- [ ] modify the login endpoint to accept a password & email.
- [ ] use oauth directly from google (consider built-in upper right hand corner message)
- [ ] create send forget password endpoint that sends an email with a key to trigger a password reset
- [ ] create reset password endpoint that handles the key from the email
- [ ] max password length of 1000 chars (bcrypt only uses first 72, anyways)

Effort: 12 points

**Comment by mattkrick** [comment]
security from auth0:
```
Shield 1 is triggered after 10 failed login attempts on a single account from the same IP address.
Shield 2 is triggered after 100 failed login attempts from a single IP address via different usernames in 24 hours or after 50 sign-up attempts in one minute from the same IP address.
When Shield 1's threshold is reached, an email is automatically sent to the user, which an administrator can edit however he or she wishes. This initial email looks like...
```

This is security theater. Any decent bad actor is going to vpn across multiple IPs. That said, it's probably great for quieting down security researchers, so let's do something similar.

- after an IP address fails to login to a single account 10 times, we just always return a fail. this should make a normal person reset the password, which resets the counter & means we avoid an extra email approval flow.
- after an IP address fails login 100 times in 24 hours, we're pretty sure they're bad. we just say invalid no matter what account.
- after an IP address creates 50 account in a minute or 500 in an hour, we fail via ratelimiter.

**Comment by jordanh** [comment]
@mattkrick 

May I have a few other AC? (please edit your list above for the ones you agree):

- Private schema query to easily count number of total registered accounts (regardless of tier)
- Private schema mutation to add/remove token decorations, including `su` access
- Private or public schema mutation to disable a user's login
   - If you go the public route, make sure that `su` has access

**Comment by mattkrick** [comment]
> Private or public schema mutation to disable a user's login

what happens when they try to log in?

**Comment by jordanh** [comment]
>> Private or public schema mutation to disable a user's login

> what happens when they try to log in?

I've been thinking about this some, and what we'd want to do is preserve the behavior now when a user is deleted from auth0 (which allows us to honor deletion requests from users). The desired behavior is the user can sign up again and get a whole new authentication id if they want (N.B. this differs from a potential "block" mutation we could implement in the future if we want to parity auth0's functionality). I suggest the following AC.

An user can:
   - Call a public schema mutation to disable a user's login
      - If not the viewer itself,  `su` is required to perform
   - Optional:
      - Sets flag on `User` object marking object as soft deleted (opens the path for hard deleting user data in the future)

**Comment by jordanh** [comment]
Since this is in flight, do you want me to open a separate issue to track?

**Comment by mattkrick** [comment]
yeah, deleting & blocking is sounding like its own thing, maybe 2 different issues even? gotta get some user stories on both, i could see a GDPR-compliant delete being useful, but not sure when a soft delete or block would be handy
