### ISSUE TITLE
Metrics Review

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#330]
## Enhancement

When a team is having an action meeting, they need an organized prompt and check-list for metrics so that they can focus on processing the same data together.

When a team member is working async during the week, they need access to the metric document links for the team so that they can review existing metrics or add/edit/delete links to existing metrics.

Specs:
- [ ] The metrics review phase is optional. A team can include this phase from the team settings view on the team dashboard.

**MVFeature**
- [ ] The metrics review is simply a prompt. Teams must share whatever documents, dashboards, etc. within their video conferences etc.

**MVFeature++**
- [ ] The metrics is a list of documents. The schema is a document title and an external link.
- [ ] Each metric can be clicked representing progress for the meeting.
- [ ] The next phase link is disabled until all metrics have been reviewed (checked).
- [ ] The same list of documents is accessible and editable from the team dashboard as a sub-view, or sub-panel of links.

Needed:
- UX discussion around meeting flow.
- UI exploration around team settings and metrics list view for team dashboard.

**Estimated effort:** 3 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

UI Concept for Metrics Review phase:
![metrics-review-concept 2x](https://cloud.githubusercontent.com/assets/307286/19080941/3828f83e-8a1e-11e6-8bb1-4271fad65eb1.png)

**Comment by ackernaut** [comment]
Ah we can merge this and #324 ...and continuing exploring UX/UI.

**Comment by ackernaut** [comment]
@jordanh I like the idea of calling this phase “Checklists” to be more open-ended. Perhaps each checklist item could have an optional external link?

**Comment by ackernaut** [comment]
We should explore having links to key documents/metrics accessible on the team dashboard (perhaps as a sub-view, like Archive). We should explore optionally including links to those metrics in summary and/or ship-style emails that can be subscribed to by stakeholders.

**Comment by tayamueller** [comment]
Highly recommend boosting this one in importance. Since beginning user research sessions, I have never observed a team that did NOT have a standing agenda item to review Metrics.
