### ISSUE TITLE
Team sharing and visibility

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#332]
## Enhancement

As a team makes weekly progress, they need helpful tools to share that progress with stakeholders.

Some ideas for discussion:
- As we make progress on team and organization design, perhaps teams can optionally be read-only (not private) to any member of an organization?
- Any member of an organization could subscribe to any read-only team that is not private.
- A team has settings for including emails of stakeholders outside of the organization. Those individuals will receive summary and/or ship emails.
- A team has settings to add any organization member as a subscriber. This would be helpful for a team that wanted to be private.
- Perhaps there are organization-level leads that can subscribe and/or admin a team without having to be on the team.

**Estimated effort:** ??? points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
Just capturing some thoughts here. Perhaps we can schedule a UX discussion as we start thinking of teaming and organization design. We might not add these types of features right away, but we can at least think about them as we start working on the basic team and org needs for our Beta Milestone.

**Comment by jordanh** [comment]
All good, old thoughts in here. I'm sure we'll revisit units of this discussion again soon. Iceboxing for now.
