### ISSUE TITLE
Distribute auth0 clientId and domain via GraphQL

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#333]
## Issue - Enhancement

I'm filing this one under the rare "bugenhancement".

While bringing up our production infrastructure I noticed that the env variables for `AUTH0_CLIENT_ID` and `AUTH0_DOMAIN` where not making their way into the client – the client was using the compiled in defaults. Investigating this a bit, I found that these variables are only set once: via webpack from the build environment. Woof.

So, if we want servers to be able to easily change auth0 credentials (good) that leaves us with a couple of options:

1. Push building to the servers (ick) – I want to be able to use the _same_ build between staging and production

2. Transmit the server's auth0 configuration to the client

Let's opt for number 2.

Turns out we have an awesome way to transmit information between the server and the client: GraphQL! If we use Cashay, it'll get cached on the client too. 

- **Estimated effort:** 2 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
I've got this one, I'm going to see if I can tackle it today. I will submit it as a PR...

**Comment by mattkrick** [comment]
alternatively, couldn't we just send down a script from the server that says `window.__ENV__ = {foo: 'bar'}`? That way it gets there without a 2nd request

**Comment by mattkrick** [comment]
then on the server, we'd probably want a __STAGING__ webpack var, and `PROD = __STAGING__ || __PRODUCTION__`.

**Comment by jordanh** [comment]
We could...

You imagine we would set that in `server/Html.js`?

**Comment by mattkrick** [comment]
yep!
