### ISSUE TITLE
Design Multiple Meeting Master Plan

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#3330]
Here's the living spec. Please read & make changes as you see fit. @jordanh @ackernaut. 
My goal is to agree on a spec, design the whole thing, and then break it down into small chunks to implement

AC

Dashboard: GOAL = start or join a meeting in 2 clicks
- [ ] The Join Meeting button on the Team Dash goes away
- [ ] The Meetings in progress banner goes away

No Active Meetings
- [ ] There is a FAB in the lower right with the meeting icon
- [ ] Clicking the icon will go to /new-meeting

1 - 5 Active Meetings
- [ ] There is a long FAB that says e.g. "3 Active Meetings".
- [ ] If 1+ of the meetings was started less than an hour ago, it's glowing
- [ ] When "3 Active Meetings" is clicked, mini-FABs will appear above it. 1 for each meeting + 1 for "start new meeting". The original FAB turns into an X

6+ Active Meetings
- [ ] There is a long FAB that says e.g. "3 Active Meetings".
- [ ] If 1+ of the meetings was started less than an hour ago, it's glowing
- [ ] clicking the fab goes to /new-meeting, where they will see meetings in progress at the top

New Meeting Lobby (/new-meeting/:?teamId) #3028
- [ ] if the User has access to meetings in progress, a section with meetings in progress appears at the top. 
- [ ] If the User has scheduled any meetings, a section with scheduled meetings appears at the top. Clicking it goes to /edit-meeting/:meetingId (idea: combine this with the meetings in progress section & add a "SCHEDULED" flag next to these meetings). 
- [ ] At the top is a dropdown box with all the teams. A team must be selected. It is auto-filled based on context clues. This goes on top because the settings are dependent on the team selected & settings should be next to the meeting type
- [ ] On the left side is a carousel of meetings with large left/right echelons.
- [ ] Each item in the carousel is a custom image of that meeting type with the meeting title below
- [ ] On the right side is a "How To Run a ____ Meeting" corresponding to the selected meeting type.
- [ ] The "How to" has no more than 4 steps (e.g. 1. Pick your prompts below, 2. get the team to reflect 3. ??? 4. Profit!) and ends with a link to the how to blog article.
- [ ] In the future, those 4 steps are replaced with a video. On mobile, it's just a "Learn More" link below the carousel
- [ ] Below is a settings area. For now, it only includes "Prompts" for the Retro Meeting. In the future, check-in phase optional. (#3030)
- [ ] On the bottom right is a Button group with 2 buttons. a Secondary "Schedule Later" and a Primary "Start Now"
- [ ] Start now takes the viewer right into the meeting

Schedule Later Modal (/new-meeting)
- [ ] When "Schedule Later" is clicked, a modal similar to the timebox modal opens.
- [ ] It has Date & Time fields
- [ ] If GCal is connected, a button exists that says "Add to Calendar". When clicked, a GCal meeting is pre-filled including all invites on that team, based on their email addresses & a permalink.
- [ ] If GCal is not connected, a button exists that says "Add to Google Calendar" which opens an Oauth2 prompt & then redirect to above.
- [ ] The permalink is generated when the "Schedule" button is clicked. That means the meeting is created at that time, too.
- [ ] Below there is a click-to-copy permalink to the new meeting.
- [ ] There is an OK button at the bottom. Clicking OK sets the date/time on the created-but-not-started ("future") meeting
- [ ] A future meeting doesn’t appear as an active meeting until 5 minutes prior to start

Editing a Future Meeting (/edit-meeting/:meetingId)
- [ ] This looks identical to /new-meeting, except there is also a red DELETE button to the left of the Schedule Later button
- [ ] Every field that gets updated triggers an updateFutureMeeting mutation

Cleanup
- [ ] the /meeting/:teamId and /retro/:teamId routes trigger a query to get the meetingId of an existing meeting of that type for that teamId. If found, it forwards to /meet/:meetingId
- [ ] No lobby exists

Meetings (/meet/:meetingId)
- [ ] subscribes to the meetingId in the url #3233
- [ ] Has no lobby
- [ ] The name can be edited by clicking the pencil next to the name

**Comment by ackernaut** [comment]
Reading through this now…thanks for taking the first pass.

**Comment by ackernaut** [comment]
[Link](https://www.figma.com/file/V5yZlKMvRGvJXDqGbptPXy/IA-Sketches-S.P.A.-13-Oaxaca?node-id=0%3A1) 🔒 to sketches for reference

**Comment by ackernaut** [comment]
This write-up looks almost exactly like our output from S.P.A. So I’m ready to make some prototypes and do some user testing. We can get more granular as we dive in!

**Comment by jordanh** [comment]
Excellent work here team!

**Comment by jordanh** [comment]
A perspective on scoping here:
  - Can this be broken down into multiple issues?
  - Can one of these issues be unblocking Matt's new lobby that offers a design to implement #3030 ?

**Comment by mattkrick** [comment]
> Can this be broken down into multiple issues?

yep! each route is designed to be a standalone & work can begin once #3341 is complete. Ideally, (almost) all designs would be done before implementation to suss out any conflicts aren't apparent from the text.

> Can one of these issues be unblocking Matt's new lobby that offers a design to implement #3030 ?

yep, The new meeting lobby #3028 should be designed first. that will unblock everything else.

**Comment by ackernaut** [comment]
Closing this one in favor of: #3374 #3393 #3392
