### ISSUE TITLE
Multi-meeting part 1

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#3341]
The first step of supporting multiple meetings #3330 is to have a URL that points to a particular meeting, not the team.

AC
- [ ] meetingId and newMeeting are removed from the GQL Team object, since we can no longer guarantee a single meeting per team
- [ ] `name` is added to the `NewMeeting` GQL type, since we cannot infer the name from the team
- [ ] all existing meetings have a `name` field a la migration that defaults to the meeting type & number
- [ ] if i go to /retro/:teamId & the team has a meeting in progress, it forwards to /meet/:meetingId
- [ ] if i go to /meeting/:teamId & the team has a meeting in progress, it forwards to /meet/:meetingId
- [ ]  if i go to either of the above 2 & there is no meeting in progress, then it goes to the correct lobby
- [ ] from the lobby, when i click "start meeting" i & all the participants are redirected to /meet/:meetingId
- [ ] a retro subscription exists that subscribes to all the mutations triggered by a retrospective meeting
- [ ] an action subscription exists  '''
- [ ] isMeetingSidebarCollapsed is refactored to `showSidebar` and lives locally on the `NewMeeting` object. This means the sidebar cannot be collapsed in the legacy lobby (OK for now, it'll be gone soon)
- [ ] ViewerNotOnTeam supports a teamId or meetingId
- [ ] When a meeting is killed, participants get sent back to their team dash (since a lobby doesn't really exist in the future)

**Comment by jordanh** [comment]
Hey @mattkrick, would it be too much to ask to cheese in a "Start with check-in round?" checkbox in the lobby? Then we could also tackle #3030 ...

I'll bring it up in today's Action Meeting
