### ISSUE TITLE
Invite dialog updates

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#3346]
### AA
- Promotes the invite link to first position, consider blue emphasis color
- Demotes the invite by email textarea to second position
### EE
- 10.5 pts

**Comment by mikennaji** [comment]
Hi,

I would like to work on this issue please!

**Comment by ackernaut** [comment]
Hello @mikennaji 

I appreciate your interest in taking the issue. However, I need to work on this one. There are some changes not specified that I’ll be addressing from a design role.

In general, our preference is for folks to bid for issues on [this board](https://github.com/ParabolInc/action/projects/1) where we ask for community contributions via the help-wanted label. At any rate, I’d encourage you to wait for a confirmation from us if you want to start working on any issue. Thanks for your consideration!

**Comment by mikennaji** [comment]
Noted for next time thanks for the feedback !

**Comment by ackernaut** [comment]
Of course!
