### ISSUE TITLE
create shorter mass invite token

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#3359]
today, the mass invite token is pretty long. too long to be user friendly (although pretty darn secure).
i'd like to shorten this up so the whole URL can fit in the invite modal. to do this, we'll need to store info about that token in a database, not in just the token itself.

here's how i imagine it:
- when a team member queries a mass invite token, we hit the MassInviteToken db table (indexed on teamMemberId & createdAt).
- if the token exists (<= 1 hour old), use it
- else, create a new one

when using the token, we simply look up the doc & ensure that it is not expired. knowing the difference between expired & non existent is good for UX.

code length:
- we'd like to make it as short as possible, something that can be told from 1 person to another. so ideally, it's just upper case + numbers
- we can rate limit attacks by userId, although this won't stop a botnet
- 4 chars (uppercase + numbers) = 36^4 = 1.6M
- 6 chars = 36^6 = 2.1B

both 4 & 6 char codes fall terribly short of snowden's 1 trillion attempts/second = 86 quadrillion per token lifetime. to make it more secure we can:
- shorten the token lifespan (e.g. 8 hours). this impacts the late night "hey, try this" on slack
- watch for a brute force. if globally we're getting more than e.g. 1000 attempts/second, we require a team invitation, instead. this means bad actors can do that just to mess with us.
- expired token landmines. log every time an adversary hits an expired token for a particular team & userId. then, when a valid token is hit, see how many expired tokens were hit _after the valid token was created_. e.g. the valid token was created 10 minutes ago, there have been no expired tokens hit since then, good to go! The token was created 23 hours ago, since then 10 expired tokens have been attempted, chances are someone is up to no good.
- honeypots. we plant a few landmines. if they are hit, we silently lock that account from successfully getting in, ever.
- silent lock on rate limit hit. same as above, but just by the number of attempts.

 collisions:
- if we never reuse a 6 digit code, it's possible we'll eventually hit some collisions. to be precise, we'll have a 50/50 chance of a collision as soon as we get 54k invitations, which seems pretty dinky (`Math.sqrt(.25 + 2 * Math.log(2) * 2100000000) + .5`). That means we'll probably have to remove expired invitations, which is not great for UI ("That invitation has expired/doesn't exist) but marginally better for security.

**Comment by mattkrick** [comment]
After that auth0 sprint, i've got a new take.

- A team generates a new mass invite token if the current one is good for less than 23 hours
- Mass invite is good for 24 hours
- token is 6 digits long, A-Z,-0-9, no lowercase
- 10 fails in 24 gets you blacklisted for 24 hours (success does NOT reset this). meaning that user cannot use any mass invite token
- 100 fails gets you blacklisted for life

So now we have to estimate how many outstanding tokens will exist at one time.

realistically:
1 token per team
5k teams (currently at 10k)
= 5000 outstanding tokens 

upper limit:
24 tokens per team
* 100k teams (currently at 10k)
= 2.4MM outstanding tokens

**Comment by mattkrick** [comment]
@jordanh need your wisdom here, i can't find a reasonable, safe solution

**Comment by jordanh** [comment]
After discussing:

- 12-14 chars
- 24 hours
- use short url (prbl.app/i/:key)
- parabol.co redirect rules updated to support above
- 10 fails in 1 hour gets you blacklisted for 24 hours (success does NOT reset this). meaning that user cannot use any mass invite token
- 100 fails gets you blacklisted for life
- optional: 3+ fails forces a recaptcha on each attempt

**Comment by mattkrick** [comment]
more thoughts:
- the ability to see the invite modal gives people the ability to join the team
- we should have a way to void tokens for e.g. someone accidentally screen sharing
- since each new token is a write to the DB, it should be a mutation
- the token should be specific to team member

so, i imagine theres a `createMassInvitation(voidOld: boolean)` mutation.
- the mutation is called when the team invite modal is opened (or maybe hovered) and the current invitation token is > 30 mins old. we know it's old not because of a query, but because a previous mutation put it there
- the modal has a `void old and refresh` icon. when clicked, it calls `createMassInvitation(true)`
- while loading the invitation token, we should show something fun, maybe the token is constantly changing a la the matrix & the copy button is disabled
- on the server, `createMassInvitation` checks `voidOld` and if true, looks up all old tokens for that team member & expires them
- the team object has a massInvitation object with expiry & token. it resolves to the MassInvitation table, but doesn't update it, so chances are it's pretty useless (but it's there in case we wanna check it out for later uses)
