### ISSUE TITLE
Bug: existing users get error when trying to join meeting on differing org

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#3370]
## Issue - Bug

A user reports this issue:

> If you are already a member of a Parabol org (as I am), and try to sign into a meeting for a different org, you get a cryptic error saying "An error has occurred! We've alerted the developers. Try refreshing the page." After some digging, we found out this happened because I hadn't accepted the invite to the new org before trying to access the meeting. It'd be nice to relay an error to the user that they are not a member of the organization.

- **Estimated effort:** 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### Acceptance Criteria (optional)
Existing users can:
   - attempt to join a meeting on a different org and be redirected to accept an existing invite or,
   - be informed they need an invitation to join the meeting (if the invite is no longer valid)

**Comment by mattkrick** [comment]
I _think_ i fixed this a couple weeks ago. the issue had to do with the /invitation-required logic, specifically if you had an invitation outstanding already.
i couldn't reproduce on latest, so i'm filing as fixed.
