### ISSUE TITLE
First version of single meeting lobby

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#3374]
See [this Figma doc](https://www.figma.com/file/2CdDxgchV8PHXT8YfWfGpw/Meeting-Lobby?node-id=0%3A1) for example visuals:

#### Team dash
- [ ] The team dash has Start Meeting if no meeting is running. It goes to the single lobby
- [ ] The team dash has Join Meeting to join a single meeting that is active
- Note: this will be replaced by the first version of the Super Meeting FAB and improved IA for users to understand that multiple meetings are running and clear options of which to join
#### Single lobby
- [ ] There is a back button to the previous place (in this case, the team dash—later, to whatever dashboard view where the user was previously)
- [ ] There is a carousel for Retro and Action meetings, the Retro is in the first position
- [ ] Both have a control with the team selected already since we know where the user is coming from. In the future this may not have a value if the user arrives from a general dash view
- [ ] An additional control animates in/out when scrolling to/from the Retro that is the template selector
- [ ] Both have a checkbox for including the Social Check-In. It defaults to unchecked
- [ ] There is a heading with bullets of how to run (3-4 steps). This is collapsed at the mobile breakpoint. This content fades in/out based on the carousel interaction. A min height should cover content blocks for both meeting types so that the Start Meeting button doesn’t move up and down. The Learn More link goes to Retro or Action 101 pages in a new tab.
- [ ] There is a Start Meeting button. In the future, if a team is not selected, this is disabled
- [ ] **Mobile layout order**: back button, meeting illustration, meeting name and carousel arrows, how to run collapsed, select components (team, template), social-checkin checkbox, Start Meeting button
- [ ] **Laptop layout order**: left side (back button, meeting illustration, meeting name and carousel arrows, how to run collapsed, select components (team, template), social-checkin checkbox) right side (how to run expanded content, Start Meeting button)
- [ ] **Large display**: [see this frame](https://www.figma.com/file/2CdDxgchV8PHXT8YfWfGpw/Meeting-Lobby?node-id=42%3A409)—the wave graphic can fill the screen (SVG, scale proportions), basically centered. The content area has a max width and probably is centered on both axes.
#### Old lobbys
- [ ] The files for these views are cleaned up 

### Estimated Effort
- 12 points

**Comment by mattkrick** [comment]
Lgtm!
