### ISSUE TITLE
Font variants not loading

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#338]
## Bug

Only one variant (regular 400, non-italic) of Karla and Merriweather are being added as `@font-face` declarations in the `<style>` tag. Bold and italic styles are being faked by the browser resulting in fuzzy rendering for bold and skewed regular variant for italics.

The most apparent component showing the issue is the agenda item list and input. Here’s a shot from staging. Still getting the same locally.

![screenshot 2016-10-05 09 58 30](https://cloud.githubusercontent.com/assets/307286/19118658/b7ec1e1a-8ae2-11e6-87a5-b1ed61de83a8.png)

The `style` tag only has one variant of each locally (I’m seeing base64 for Karla on staging, but still only one variant of each):

```*{box-sizing:border-box;-moz-box-sizing:border-box;}*::before, *::after{box-sizing:border-box;-moz-box-sizing:border-box;}@font-face{font-weight:400;font-stretch:normal;font-style:normal;font-family:Karla;src:url('/static/043e4cdf5885439a67d13e36ccb69bd7.woff2') format('woff2');}@font-face{font-weight:400;font-stretch:normal;font-style:normal;font-family:Merriweather;src:url('/static/27fdab23b208a024d5bd8c88e600f41f.woff2') format('woff2');}html{font-size:16px;font-family:"Karla","Karla","Karla","Karla","Merriweather","Merriweather","Merriweather","Merriweather";}body{color:#08070a;font-family:Karla,Helvetica Neue,Helvetica,Arial,sans-serif;-moz-osx-font-smoothing:grayscale;-webkit-font-smoothing:antialiased;font-size:16px;font-weight:400;line-height:normal;margin:0px;padding:0px;}```

- **OS:** OSX
- **Browser:** Chrome Version 53.0.2785.143 (64-bit)
- **Node version:** `node v6.7.0`
- **NPM version:** `npm 3.10.3`
- **RethinkDB version:** `rethinkdb 2.3.5 (CLANG 7.3.0 (clang-703.0.31))`
- **Estimated effort:** 2 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
@ackernaut can you confirm that this is still a problem after hotfixes-10-4 got merged?

**Comment by ackernaut** [comment]
Locally, yes. I have latest master, tried a new copy of the repo, installed modules from nada. @mattkrick

**Comment by mattkrick** [comment]
GAHHHH found it!
Aphrodite's latest version (which fixes this bug) hasn't landed in npm yet, so i'll update the package to use a tarball from gh.
