### ISSUE TITLE
Cannot reliably drag Reflection card

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#3388]
Reproduction is intermittent. Goes like this:

AC:

1. Start Retro meeting
2. Create 6 or more Reflection cards (number not specific)
3. Advance to group
4. Hover mouse cursor over card, click and hold to begin drag, drag
5. Note that card does not move

EE: 12 points​

**Comment by mattkrick** [comment]
wrap onMouseDown in a useEventCallback

**Comment by mattkrick** [comment]
also in DraggableReflectionCard make canDrag include the bar minimum (phase stuff), else use the onMouseDown handler.
