### ISSUE TITLE
Designed dashboard IA

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#3394]
In support of #3330 

### Acceptance criteria
- [x] Figma concepts that show layouts for both mobile and laptop based on [output of S.P.A. Oaxaca](https://www.figma.com/file/V5yZlKMvRGvJXDqGbptPXy/IA-Sketches-S.P.A.-13-Oaxaca?node-id=0%3A1) in support of #3330 
- [ ] Stretch goal: a clickable prototype that can be shared, tested

### Estimated effort
- 12 pts

**Comment by ackernaut** [comment]
Getting started [here](https://www.figma.com/file/mN1tnQnNR8ZeY1W7Q0zOA6/2019-App-IA?node-id=0%3A1), not much to see yet

**Comment by ackernaut** [comment]
Here are the take-aways after more cycles on dashboard IA. I’ll break down each into discrete issues.
### Navigation
- Left-based navigation ([laptop+](https://www.figma.com/file/mN1tnQnNR8ZeY1W7Q0zOA6?node-id=75%3A1270&utm_campaign=team&utm_source=slack&utm_medium=message&utm_content=file_comment#15404000), [minimized](https://www.figma.com/file/mN1tnQnNR8ZeY1W7Q0zOA6?node-id=75%3A1270&utm_campaign=team&utm_source=slack&utm_medium=message&utm_content=file_comment#15404010), [mobile](https://www.figma.com/file/mN1tnQnNR8ZeY1W7Q0zOA6?node-id=75%3A1270&utm_campaign=team&utm_source=slack&utm_medium=message&utm_content=file_comment#15404021))
- Links for locations (timeline, tasks, teams, and any future locations like notes or knowledge)
- Team sections by org, [add a new team inline per org](https://www.figma.com/file/mN1tnQnNR8ZeY1W7Q0zOA6/2019-App-IA?node-id=2%3A90)
- Create a new org (opens a large dialog view to create a new org and a first team on the org)
- Uses a menu toggle to hide on mobile, or minimize for laptop+
- May have user hub info on mobile TBD
### Search
- [Rich component in top bar](https://www.figma.com/file/mN1tnQnNR8ZeY1W7Q0zOA6/2019-App-IA?node-id=102%3A5012)
- Contextual filter in place based on location (e.g. in Tasks view is showing tasks only by default)
- Filter options show up in rich menu with scrim, maybe use filter chits for multiple filters
- Results show up inline in rich menu with scrim
- Search input collapses down to an icon for mobile and expands to an input with a tap
### User hub
- [Pinned right side of top bar](https://www.figma.com/file/mN1tnQnNR8ZeY1W7Q0zOA6/2019-App-IA?node-id=100%3A1) except maybe hidden in left nav for mobile
- Has menus for help, notifications, meetings, and user
- Notifications and meetings have [badge](https://www.figma.com/file/mN1tnQnNR8ZeY1W7Q0zOA6/2019-App-IA?node-id=100%3A238) and [emphasized states](https://www.figma.com/file/mN1tnQnNR8ZeY1W7Q0zOA6/2019-App-IA?node-id=95%3A913) to take action and join meetings
- Alt. we could move the probably mostly static user info into the left nav on mobile (TD visual concept)
### Timeline
- Has active and scheduled meetings [at the top](https://www.figma.com/file/mN1tnQnNR8ZeY1W7Q0zOA6?node-id=75%3A1270&utm_campaign=team&utm_source=slack&utm_medium=message&utm_content=file_comment#15331186)
- Has suggested actions at the top (TD figure out meetings and actions layout)
- Has a rich filter menu (probably start out searching by team)
- Primary action is Start Meeting
### Tasks
- A [single kanban with a rich filter menu](https://www.figma.com/file/mN1tnQnNR8ZeY1W7Q0zOA6/2019-App-IA?node-id=95%3A636) to rule them all (owner, team, archived)
- Primary action is Add Task
### Team
- Team view ([mobile example](https://www.figma.com/file/mN1tnQnNR8ZeY1W7Q0zOA6?node-id=93%3A4&utm_campaign=team&utm_source=slack&utm_medium=message&utm_content=file_comment#15404314))
- Show and edit team name
- Links to organization
- More menu for integrations, settings, archive etc.
- Editable purpose (stretch goal)
- Members (invite, edit roles, tap through to single member view, full list can open in right inspector)
- Explore this team (goes to another view e.g. tasks or timeline filtered to the team, all members)
- Primary action is Start Meeting (this team selected)
### User profile (future)
- [Shows avatar](https://www.figma.com/file/mN1tnQnNR8ZeY1W7Q0zOA6?node-id=101%3A329&utm_campaign=team&utm_source=slack&utm_medium=message&utm_content=file_comment#15400867), teams (for the orgs based on team to team member navigation), roles (stretch), explore (shows another view filtered to this user like tasks or timeline)
- Primary action is to start a 1:1 or impromptu video call with simple agenda builder
### Notes (future)
- This is an idea #3391 where a user can capture things then upgrade them in the system (note becomes an agenda item on a team, or a reflection in an async retro, or some knowledge or thread etc.)
- Private to me except for things I’ve upgraded to shared loops (meeting etc.)
- Primary action is to capture a new note

**Comment by ackernaut** [comment]
@mattkrick the notes above may not be a perfect distillation of the IA thinking, some of which we did together closely, but I think it’s a high enough level of fidelity to break into smaller issues and then we can tackle finer details later. I’ve got some to-do stickies in Figma. Some of the issues representing the above may split into implementing v1 and designing v2, or more design first, or we’re close enough to implement.

Let me know if there are any bad gaps. I’ll take a task to write issues.

**Comment by jordanh** [comment]
This is brilliant, thank you all the hard work
-- 
Jordan
@jrhusney <http://twitter.com/jrhusney> / +1612 227 5673 <+16122275673>
Follow: @jrhusney <https://twitter.com/jrhusney>
Read: 6 Tips for Managing Distributed Teams
<https://focus.parabol.co/6-tips-for-managing-distributed-teams-b87ed1116b21>
PGP Key <https://keybase.io/jrhusney/key.asc>
