### ISSUE TITLE
Start meeting added to My Dashboard

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#3412]
## Issue - Enhancement

Now that our new meeting lobby has shipped and users can select the team with which they'd like to meet, meetings can (and should be) able to be started from more places in our product.

As `My Dashboard` is the first place folks see when they create an account, it could use a Start Meeting button:

![image](https://user-images.githubusercontent.com/103000/70343486-408edc80-180c-11ea-8101-8b038b4d55c4.png)

Doing so would be a quick, interim solution before shipping a refactored IA (likely with our new floating meeting button). Feel close this Issue in favor of a smarter (but still quick) Issue.

### Acceptance Criteria (optional)
Users can:
   - Start a meeting from `My Dashboard`

- **Estimated effort:** 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
Look at #3393

**Comment by ackernaut** [comment]
Here’s [some additional thinking](https://www.figma.com/file/mN1tnQnNR8ZeY1W7Q0zOA6?node-id=95%3A64&utm_campaign=team&utm_source=slack&utm_medium=message&utm_content=file_comment#15330741) on a primary action iteration in Figma
