### ISSUE TITLE
Refactor server GraphQL usage

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#3416]
After writing a new subscription handler, it's apparent our graphql route flow has turned to spaghetti over the years.

My goal is to write it in such a way that we can break it into its own microservices later.
There are 2 microservices I see:
- graphql executor (stateless)
- graphql subscriber (socket server)

executor
- has its own dataloaderwarehouse, ratelimiter, and document cache. in the future, we can share these across services by moving them to redis
- processes all graphql requests including:
  - webhooks (caches trusted string, hits the private schema)
  - connect/disconnects (caches trusted string, hits the private schema)
  - GraphiQL(does not cache string, can hit public or private schema)
  - http/websocket/SSR (caches documentId, hits public schema)
  - subscription response streams (caches documentId, hits public schema, reuses the mutation's dataloader, if available)

DataLoader
- there are 2 ways we can scale the dataloader. we could hit the DB once per server, or we could persist the results in redis & hit redis once per request. In other words: do we go dataloader -> cache -> DB, or  cache -> dataloader -> DB. i think it makes the most sense to put the cache between the DB and dataloader. eventually, the dataloader will just hit a caching layer instead of going direct to DB. that way, the API of requesting data doesn't change.
- the operationId sent to redis will need to include the processId of the originator so other servers know not to look for the dataloader. probably `pid:opId`
- when a request is received, if the pid matches, it uses the dataloader. else, it creates a dataloader with that same pid:opid (or uses it, if it already exists because a previous subscriber created it)
- keeping track of exactly when to dispose is more trouble than it's worth. each subscribe server has to tell the executor how many times it will use a particular data loader. if that number is off (e.g. the subscriber doesn't want to execute a response for the socket that triggered the mutation) then the subscriber has to call the executor anyways. the extra call overhead & extra memory to store the subscribers that have already called & how many calls remain diminishes the returns when compared to a ttl. 
- ~~~the subscribe listener adds a listenerCount to each payload it sends out. when dispose is called, it subtracts 1 from that count stored on the dataloader. when the count == 0, we know we can dispose for good (without a pesky TTL). ~~~
- SSR is a tricky one because graphql is calling itself. i settled on calling the executor "endpoint" with the dataLoaderId and authToken. this works, but it'll be kinda silly when a load balancer gets in front of the graphql executor cluster. it'd be better to just call itself, but not sure the best way to write that unless i just stick the call itself in the context, but doing that all the time for a handful of things seems useless. 

Burndown:
- [x] move connect/disconnect to the private schema
- [x] create the executor
- [x] create the subscriber
- [x] remove the auth token from the datalaoder

**Comment by jordanh** [comment]
This is awesome. Takes us closer to a clean arch for horizontal scaling.

+1 on dataloader -> cache -> DB

As for `pid:opId` used as a key in the redis cache, is the idea to make these ids distinct across machines and process restarts? If so, including a machine-unique id in addition to pid would be a good idear. Something like: https://github.com/pid/puid

**Comment by mattkrick** [comment]
that's good insight! yeah, pid won't be great for scaling. when the time comes, i figure we'll have k8s pass down an id to each node, or at least pass down a seed to all nodes so we can just use shortid. i'll abstract that out so we don't forget later
