### ISSUE TITLE
Meeting can be renamed

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#3424]
#### Editing the name in the left nav
Users can:
   - Tap the meet name in the left nav to begin editing
   - Make changes and commit on enter (similar to how team name changes work today)
   - See the subtle use of a pencil icon `edit` (text gray, bottom/baseline right) indicating they can edit the name

- **Estimated effort:** 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
From [user](https://app.hubspot.com/sales/3888472/contact/8106651) :lock::
>We run many retros and I'd like to be able to rename meetings to reflect the release we're discussing, is there a way to do that or do I have to start a whole new team? We have 4 Working teams that have releases for each so having to create a new team for each release is kind of cumbersome.

**Comment by ackernaut** [comment]
Another option would be to [include a name field](https://www.figma.com/file/2CdDxgchV8PHXT8YfWfGpw/Meeting-Lobby?node-id=180%3A1612) in the lobby. This wouldn’t exclude an affordance to edit the name in the left nav.

**Comment by mattkrick** [comment]
constraints:
- only the facilitator can rename
- 50 char limit
