### ISSUE TITLE
Memory Leak: ArrayBuffer in uncaughtExpcetion

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#3428]
We've got a few ArrayBuffers that are being created & never being released.

<img width="1459" alt="Screen Shot 2019-12-11 at 8 25 21 AM" src="https://user-images.githubusercontent.com/5514175/70629572-d0a79a00-1bef-11ea-9738-0fe74afef327.png">

The thing to look at here is the retaining object, which is `uncaughtException`.

Looking up everything that has an uncaughtException handler, I'm led to believe that it's likely Sentry (although there's no stack trace to confirm). Here's their handler: https://github.com/getsentry/sentry-javascript/blob/master/packages/node/src/integrations/onuncaughtexception.ts

Another item is the `ServerEnvironment`, which doesn't get GCd after it is used to create a meeting summary.

**Comment by ackernaut** [comment]
Assuming this is a bug; adding label, project, milestone

**Comment by mattkrick** [comment]
this was a bug in node 12. fixed in node 13.6.0
