### ISSUE TITLE
agenda list meeting mockup -- local phase item

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#344]
![screen shot 2016-10-05 at 11 24 50 am](https://cloud.githubusercontent.com/assets/5514175/19126084/5f7f70ae-8aee-11e6-9854-92428931815c.png)

This is one for @ackernaut. We've got the meetingPhaseItem in pink.  We've got completed items with a strikethrough & faded. But, we don't have any way to know where the facilitator is or where we are!

My suggestion:
- Items are faded if they are not completed. This more or less answers the meetingPhaseItem question
- Item is pink if that's where the facilitator is
- Item is highlighted? for localPhaseItem

For the previous 2 phases, localPhaseItem is shown as black, but that is almost always covered up by the pink facilitator phase item marker. it'd be cool if the 2 used the same color (maybe localPhaseItem is a pink border & facilitator phase item is a pink box?)

**Comment by ackernaut** [comment]
@mattkrick I like your thinking. Thanks for capturing this enhancement. I agree, I think that the facilitator location should use the warm palette. So what we don’t have is the local active style. I'll work on some updates and share.

**Comment by ackernaut** [comment]
@mattkrick also, to note, I think we should use a similar logic to the Progress Bar where the processed agenda items are the farthest point (minus 1) that the facilitator has reached without skipping ahead. The farthest point would be un-processed until he passed it, even if he goes back navigation-wise or skips.

**Comment by mattkrick** [comment]
@jordanh can we move this up to bugfixes? i think there's a lot of value in knowing where the facilitator is. plus, pink = facilitator state everywhere else. having it mean meeting state breaks that pattern & makes for a confusing UI.

**Comment by jordanh** [comment]
Sure. I can see that being a "bug"

**Comment by mattkrick** [comment]
@ackernaut any ideas or mockups for this guy?

Here's my ugly naive approach:
- pink: facilitator state
- black & bold: local state (if different from facilitator)
- green: not completed
- strikethrough & faded: completed

**Comment by ackernaut** [comment]
@mattkrick yeah that is more or less what I was thinking based on the existing styles:

- warm: facilitator location
- dark: local location when different from facilitator location
- cool: not completed
- strikethrough, faded, cool: completed

I’ll drop this is figgy Figma real quick and post a shot here.

**Comment by jordanh** [comment]
Closed by #851
