### ISSUE TITLE
Admin query to count registered users

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#3440]
This replaces our metrics collection capability we had within the auth0 dashboard.

### AC
A Parabol superuser can:
   - Run a query counting the total number of register users, including inactives​

### Estimated effort: 10.5 points

**Comment by ackernaut** [comment]
Needs acceptance criteria and estimated effort

**Comment by mattkrick** [comment]
see `signups` query on the private schema

**Comment by jordanh** [comment]
Ah. I guess I could use `signsups` but make the date the beginning of time, eh?

**Comment by mattkrick** [comment]
yep! still need to come up with a clever way to publish this to slack on a weekly cadence
