### ISSUE TITLE
Dashboard left navigation updates

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#3448]
See the outcome of design efforts [here](https://github.com/ParabolInc/action/issues/3394#issuecomment-566770853) (see [Figma for IA designs](https://www.figma.com/file/mN1tnQnNR8ZeY1W7Q0zOA6/2019-App-IA?node-id=0%3A1))

#### Menu toggle
- [ ] A menu toggle hides/opens the left nav at mobile breakpoints, fixes #3017 
- [ ] A menu toggle [minimizes the left nav](https://www.figma.com/file/mN1tnQnNR8ZeY1W7Q0zOA6/2019-App-IA?node-id=75%3A1270) at laptop+ breakpoints
#### Nav items
- [ ] Timeline links to latest version of timeline
- [ ] Tasks links to my task kanban or the single kanban when it exists
#### Teams
- [ ] Teams are divided into sections by org ([see Figma](https://www.figma.com/file/mN1tnQnNR8ZeY1W7Q0zOA6/2019-App-IA?node-id=109%3A8986))
- [ ] If user is on 1 org, the label says My Teams
- [ ] If user is on 2+ orgs, the label says the organization’s name
- [ ] There’s a nav item for each team that I’m on
- Note: in the future instead of a label for the organization we’ll probably have a nav item that links to a top-level team named by the org that includes all members of the org.
- Note: in the future each team nav item will link to a new team view [TK issue] as the single team kanban will be obsolete
#### Add a Team
- Note: No real change, just note that the control is separated from the team section(s) by a horizontal rule. Since this is an occasional task, the left nav remains minimal with a single action to create a new team on a new or existing organization.
#### Mobile details
- [ ] Tapping the scrim closes the navigation
- [ ] Tapping through to a location closes the navigation
- [ ] Parabol logo is bottom left of mobile left nav
#### Mobile user hub consideration
- Depends on top-right user hub issue #3453. If we don’t include the user hub in the top right at mobile breakpoints we put user hub here ([see Figma](https://www.figma.com/file/mN1tnQnNR8ZeY1W7Q0zOA6/2019-App-IA?node-id=109%3A10015)):
- [ ] Top section has user’s avatar, name, email. Tapping goes to their editable profile (a simple first version of #3459)
- [ ] Conditionally show a CTA to Upgrade to Pro or the Pro/Enterprise badge
- [ ] Sign Out link goes to the bottom left above the Parabol logo

### Estimated Effort
- 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
At a minimum, we need to design left nav & top bar in conjunction.

Burndown

Mobile left nav:
- left nav shows "Upgrade" CTA on personal plan
- left nav shows pro/enterprise when not on personal plan
- left nav team name list looks good with 0, 5, and 20 teams

Dash left nav:
- collapses when top bar is clicked

Mobile top bar: 
- NA

Top bar:
- Search bar hides when not on user tasks or team tasks
- search bar works on user/team tasks
- badges for notifications & meetings works
- clicking the meetings button opens a menu showing active meetings
- if no active meetings, has good 0 state



Here's a list of things I'm leaving out for now:
- Notifications menu. for now, it just redirects to the notifications page
- over limit copy, scope creep
- mobile top bar page names. we'll need to change the name whenever the route changes. for now, it's just parabol
- search icon on mobile, animations will take too long to get right
- help icon, keyboard shortcuts isn't enough. we need 1 more before i want to add this

**Comment by ackernaut** [comment]
@mattkrick to clarify, your bullets are the design elements that are missing, or what’s in Figma isn’t developed enough into the shape you need? How can I help?

**Comment by mattkrick** [comment]
nah figma has good stuff! it's just got the final state, so i needed a scratch pad to keep track of the intermediary steps
