### ISSUE TITLE
Alert to active and scheduled meetings in the meeting lobby

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#3461]
This implements a secondary feature in the meeting lobby, to alert users to active and scheduled meetings on a selected team before starting a new meeting. See [the concept and comments](url) in Figma

### Acceptance Criteria
When a user selects a team in the meeting lobby and there are active and/or scheduled meetings:
- [ ] A secondary control appears above the start meeting button
- [ ] The label shows a count of meetings (e.g. 2 Active & 1 Scheduled)
- [ ] Tapping the control opens a menu inline, much like the meetings menu #3454, but filtered to this team
- [ ] The user can tap through to an active meeting
- [ ] The user can edit a scheduled meeting, see #3392 (**Note**: if #3392 is blocking we could build a first version of this menu that only shows active meetings)

### Estimated Effort
- 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
added additional filter for meeting type so e.g. when you're trying to create a retro meeting it doesn't warn about current action meetings
