### ISSUE TITLE
Meeting lobby remembers last meeting type ran

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#3473]
Acceptance criteria:
A user can:
   - by default visit the Meeting Lobby and see retro meetings
      - remainder of meeting types follow in alphabetical order
   - see the last meeting type they've selected first, otherwise

Estimated effort: 10.5 points

**Comment by mattkrick** [comment]
if we default to alphabetical order that means first time users will see action before retrospective. probably should default to retro

**Comment by jordanh** [comment]
Good call! Updated the AC
