### ISSUE TITLE
Users table lastLogin field not updating

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#3474]
## Issue - Bug

I've got some new sales tools I've been writing that work with backend data, knowing the `lastLogin` date would be very helpful.

At present, the `lastLogin` date doesn't seem to update.

- **Estimated effort:** 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### Acceptance Criteria (optional)
Administrators can:
   - query the `lastLogin` date, which updates each time the user logs in

**Comment by mattkrick** [comment]
can you use `lastSeenAt`?

**Comment by jordanh** [comment]
Most certainly I could use `lastSeenAt`. Should we remove the `lastLogin` field then? I’d like to remove the fields we don’t plan on using to keep the schema tight

**Comment by mattkrick** [comment]
Yep, the user take is full of some old fields, probably time till do a cleanup

**Comment by mattkrick** [comment]
lastLogin is not on the GraphQL schema, #3541 removes it from the User database object
