### ISSUE TITLE
Reverse account creation flow for domain blacklist

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#3475]
## Issue - Enhancement

To prevent social engineer attacks and offer an additional security offering let's do the following:

### Acceptance Criteria (optional)
Parabol super users can:
   - Run a mutation to add a domain (e.g. `parabol.co`) to a 'verification required' list
   - Run a mutation to remove a domain from the 'verification required' list
   - Run a query to read the list

For users on the 'validation required' list, users must:
   - validate their email address before being allowed to login

- **Estimated effort:** 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
@mattkrick for your review!

**Comment by mattkrick** [comment]
when signupWithPassword is called, we can't verify the email.
so, on the server, we first check to see if the domain + tld is in a list of blacklisted domains in the `SecuredDomain` table
- if it exists on the table, then we do the following:
- send a verifyEmail email with a link
- write a row to `PendingVerifiedEmail` table with the email, expiration, hashed password, and token
- when the link it clicked, call `verifyEmail(token, isSignUp: true)`
- if expired or invalid, show that
- if already a user, show expired
- if the token is good, call a subfunction of signupWithPassword (this time the PW will be hashed)

**Comment by mattkrick** [comment]
table: EmailVerification
cols: id, email, expiration, token, hashedPassword (only if signup)

mutation: verifyEmail(token)
validation: if expired, invalid, already verified, show error
if hashedPassword exists, create account
if !hashedPassword, look up User, turn on isEmailVerified to true

**Comment by mattkrick** [comment]
when to send email:
- if verification is required
- if an email verification has never been sent before, send a new one
- if verification has expired, send a new one

note: this means an attacker can spam signup once per expiration duration in hopes that the victim clicks the link in the email.
conversely, it means if a real user accidentally deletes the email, they have to wait until it expires.
to combat the accidental delete, we'd have to offer a "resend" functionality, which an attacker could use as well. to limit the attacker, we'd have to only allow a resend every X hours/days, which basically brings us back to the starting point.
so, I figure 1 email every 24 hours is a happy medium. if non-users get too many emails, we can adjust. 
if an attacker attempts too many creations, then this should be caught before the require verification step.
