### ISSUE TITLE
Superuser account deletion mutation

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#3477]
## Issue - Enhancement

With the removal of auth0, our previous method of honoring account deletion requests is no longer available. We need a replacement. See open customer support tickets [#75105961](https://app.hubspot.com/contacts/3888472/ticket/75105961/) 🔒 and [#74937938](https://app.hubspot.com/contacts/3888472/ticket/74937938/) 🔒.

Related to #3159.

### Acceptance Criteria (optional)
Parabol superusers can:
   - run a single mutation taking an email or userId as an argument to delete a user acount
      - account deletion cascades across all Teams and removes them (allowing removal business logic to run)
      - account deletion cascades across all Organizations and removes them (allowing removal business logic to run)
   - if user is an Organization owner, billing lead or team leader, mutation throws an error
      - these conditions are checked first before making any mutations, making this function atomic
      - for now, if an error occurs support ticket will need to be resolved by asking users to manually change these roles. This user interaction is a feature, not a bug :)

- **Estimated effort:** 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
what do you want to happen when they try to login? 
or create a new account with the same email?

> account deletion cascades across all Teams and removes them

i assume you mean soft delete, right? otherwise this will be a month long process.

> if user is an Organization owner, billing lead or team leader, mutation throws an error

everyone is the owner of their own org (if one was created for them), and team leader of their first team. not sure how to proceed?

**Comment by jordanh** [comment]
I'll open a new issue, shorter in scope (soft delete) and refer back to this issue

**Comment by mattkrick** [comment]
removing in favor of #3504
