### ISSUE TITLE
Cannot start meeting

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#349]
## Issue - Bug

When pressing start meeting, v0.7.2 (on staging):

![image](https://cloud.githubusercontent.com/assets/103000/19153280/db3033cc-8ba3-11e6-9b13-7aaaa6788ba6.png)

> Uncaught TypeError: Cannot read property 'startsWith' of undefined

- **Estimated effort:** 1 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Exception occurred here:

```javascript
   var project = _cashay.cashay.query(projectCardSubQuery, {
     op: 'projectCardContainer',
     key: projectId,
     variables: { projectId: projectId },
     resolveCached: {
       project: function project() {
         return projectId;
       },
       team: function team(source) {
         return function (doc) {
           return source.id.startsWith(doc.id);
         };
       },
       // example of returning a string instead of a function so it runs in O(1)
       teamMember: function teamMember(source) {
         return source.teamMemberId;
       }
     }
   }).data.project;
```

**Comment by mattkrick** [comment]
Fixed in latest agenda PR
