### ISSUE TITLE
Use updated meeting name in timeline and summary

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#3497]
We now allow folks to rename meetings. We should use this name in the timeline and summary.

### Acceptance Criteria
- Updated meeting name is used in the timeline and summary

### Estimated Effort
- 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
in addition to timeline & summary, we'll want to replace every instance of the meeting label with the meeting name. This will better position us for supporting multiple meetings (e.g. alert them which meeting has progressed, not just a retro meeting)
