### ISSUE TITLE
Account soft delete/archive mutation

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#3504]
## Issue - Enhancement

Precedes #3477 for speed ⚡️🏃‍♀️.

In order to service the increased volume of account removal requests, we need a way of disabling accounts similar to the workflow we had when auth0 was out in front of our system.

In order to honor a user's wishes, we should probably record if the intent of mutation is an archive operation or a hard delete. When we have hard deletion capability, we can query these users and purge their data.

### Acceptance Criteria (optional)
Viewer or superuser can:
   - Soft delete a user record
      - N.B. a user could create a new account with the same email after this operation is complete
   - A field on the User record records wither the deletion operation intends to be archived (soft) or hard (pending deletion)

- **Estimated effort:** 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Note: we've got user 4 deletion requests pending as of this morning from 3 different orgs

**Comment by mattkrick** [comment]
AC
- [ ] TeamMember record is soft removed
- [ ] OrgMember record is expired
- [ ] email is removed, isRemoved is set on the User
- [ ] login returns false if User isRemoved
- [ ] signup returns true if User is added
