### ISSUE TITLE
Font loads twice error

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#351]
Steps to reproduce:
- start a meeting
- get all the way through to last call
- go back to check in
- hit refresh
- click Updates on the sidebar
- notice the flicker & the fonts that got double requested from the server

I think the solution is to make a PR to aphrodite for global styles, since currently how they load fonts is kinda hacky (it's the only bad thing about the whole entire package).
There is a PR from a khan academy staff in the works, but it hasn't been accepted yet & IMO it does some dangerous stuff (eg lets users mix global styles and modular ones in the same call). I voiced my concern & a way to fix it, but no reply yet.
I could fork that PR & write up a `injectGlobal` function for it, but who knows if they'll accept it or not, and if not, then we'll be running off a fork indefinitely...

**Comment by ackernaut** [comment]
@mattkrick thanks for working on this!

**Comment by mattkrick** [comment]
This will land in https://github.com/Khan/aphrodite/pull/157. It still requires a few more unit tests before they'll merge. Until then we'll just use the fork.
