### ISSUE TITLE
Bug: revisit lobby to start 2nd meeting = blue spinny

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#3526]
## Issue - Bug

I got a couple of reports this evening of a bug that felt introduced when we shipped our new design. Folks are visiting the lobby and trying to start a meeting, only to get the blue ball of infinity spinny:

![image](https://user-images.githubusercontent.com/103000/73238122-a9c80780-414c-11ea-8f03-ff3bd6dc8393.png)

I had a look into the account of [one user](https://app.hubspot.com/contacts/3888472/contact/9469651) 🔒 and was able to determine what was going on: they had already started a retro and abandoned it. Then, they hit the big ol' start meeting button again to try and restart the meeting only to get the spinny.

They got into this state because they wanted to see how to start a meeting before starting one with a bunch of colleagues. They didn't think to press end meeting. As "Start Meeting" is our most obvious CTA (and the in-progress meeting list is very quiet), it's easy to get back to the Lobby and have a _Bad Time™_ 

Because it makes our product look broken, I'm going to suggest we hotfix this sucker. Simple AC below, with a discussion in thread below.

- **Estimated effort:** 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### Acceptance Criteria (optional)
Users are:
   - Redirected to a meeting in progress of the same type, if one is already started

**Comment by jordanh** [comment]
I'm open to alternative AC to fix this. Suggest is the most logical thing my tired self could think of tonight.

By the way: this signal does point to needing a lobby design revision to show meetings in progress. @ackernaut is this something we have sketched out?

**Comment by mattkrick** [comment]
fix in #3527
