### ISSUE TITLE
Add a counter for how many Action meetings a team has held, a user has attended

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#353]
## Issue - Enhancement

There is some analytics I'd like to track on a team and user level:
- [ ] total count of Action meetings a team has held
- [ ] total count of attended meetings per user (from marking a user "present" during check-in round)
- **Estimated effort:** 2 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
Sounds like a good place for gamification. Trophies every 3, 10, 25, 100 meetings?

**Comment by jordanh** [comment]
Covered by #352
