### ISSUE TITLE
DnD Task cards on iPad

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#3531]
# Issue - Enhancement

Just like Reflection cards during a retro, it would be wonderful to be able to drag Task cards on a dashboard on an iPad

### Acceptance Criteria (optional)
Users can:
   - using touch to drag a Task card to assign status or priority

- **Estimated effort:** 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
hmm @jordanh can you drag the card if you long-hold on the card?

**Comment by jordanh** [comment]
Oh gee, I don’t know why that wasn’t obvious to me the first time i tried it. Long pressing works just great. Maybe I’m just an ipad noob. Closing this now

**Comment by ackernaut** [comment]
Oh no! To be fair the drag for touch seems nearly instant in the Retro columns, but requires the long hold on the kanban. I suspect this is by design given the UX of each but that would be MK’s handy work.

**Comment by mattkrick** [comment]
It's probably worth standardizing the 2.
Things that can't be grouped use react-beautiful-dnd. The business logic is: https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/sensors/touch.md

Things that can be grouped use a custom solution. The business logic is to begin dragging after you press and move 3 pixels.
