### ISSUE TITLE
Allow team leaders to skip step 3 of the welcome wizard

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#354]
## Issue - Enhancement

Hey, let's get to know each other before you involve my friends...

When a TL is unwilling to invite a teammate, they want to skip step 3 of the welcome wizard, so that they don't involve others into their process of exploration too prematurely.
- **Estimated effort:** 2 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
If they do this should we prepopulate their board? Then have a little button to blow away the demo data.

**Comment by ackernaut** [comment]
Should we remove the fields for adding first projects altogether? Otherwise, should we pre-populate the dash for each invitee that accepts with the project that was added during step 3? As of now, we were just showing it in the invite email.

Really step 3 is optional because they do not have to complete the fields. I add “optional” to the label for those fields.

**Comment by ackernaut** [comment]
Ah, I see that #219 addresses this.

**Comment by jordanh** [comment]
I added this to our [Equity For Effort](https://github.com/ParabolInc/action/projects) program.

**Comment by ackernaut** [comment]
@jordanh I think they can already skip step 3, as those fields are optional. Now, transferring those to actual cards ala #219 would be a big win, especially coming from the community.

**Comment by jordanh** [comment]
It's not skipping the "first projects" fields, it's skipping the invitation of teammates altogether.

Now that we've got Team Settings merged and shipped, we can offer a "let me kick the tires first" (to paraphrase @mattkrick) button to skip Step 3 completely.

**Comment by ackernaut** [comment]
Ah, gotcha! Makes a lot of sense—let’s do it!

**Comment by ackernaut** [comment]
*Does this get us what we need for now?*

![welcome-skip-invites 2x](https://cloud.githubusercontent.com/assets/307286/20494703/d14f20a2-afe3-11e6-8f54-631c26b7ce10.png)

**Comment by ackernaut** [comment]
Basically, just add a link to skip (the next view is Dashboard, no?)

**Comment by mattkrick** [comment]
it could just be me, but it looks almost _too_ encouraging to click. maybe a smaller icon? or no icon? maybe put it next to the CTA so it kinda visually makes a fork in the road?

**Comment by ackernaut** [comment]
I agree on those points…and I was thinking we want to encourage them to continue anyway, so why not give them a clear path forward? I think it’s safe either way.

Also I think the copy “For Now” or something similar is a subtle way of letting the user know that they can do this later, [so no worries]!

I did think about the side by side version, as well. I can explore some different versions.

**Comment by jordanh** [comment]
@ackernaut let's test the version as you have it. We'll let the data point the way...
