### ISSUE TITLE
support new notifications

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#3544]
before we implement the new notifications, there are a few things we need to change. first, the business logic:

- a notification has a createdAt, not startAt
- a notification belongs to 1 person
- a notification never gets deleted
- if a task gets deleted, the notification that references it shows "DELETED TASK"
- if a task is not viewable because it's assigned to a non team member, or a non-team, or made private then it also shows "DELETED TASK"
- when a notification is in the viewport, a mutation is sent that flags it as "viewed"
- when a notification is clicked, it is flagged as "clicked"
- seeing the subject of a notification doesn't affect the viewed/clicked state (e.g. looking at task123 doesn't affect the notification that says you should look at task123)
- notifications are sorted first by "stick/not-sticky" then sorted by newest to oldest
- payment rejected is the only sticky type so far.
- there exists a bespoke notification type that 
- notifications older than 12 weeks are subject to being put into deep freeze (never deleted, but not shown to end users, in the future, we can move to a DeepFreezeNotifications table)
- consider a compound index so we can get all notifications for a user that are newer than 12 weeks. 
- a team invitation notification is only valid until the person is on the team. once on the team, it is invalid. that way, you can kick someone off & they can't get back on by clicking the notification

TEST
- batch notification email query works
- send invitation, user accepts invitation, kick user out, user cannot use old notification invitation to rejoin

**Comment by jordanh** [comment]
Will ship in v4.22.0
