### ISSUE TITLE
After team member accepts invite, direct them on next steps

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#355]
## Issue - Enhancement

When a TM completes account creation, they want to understand what their next step is (inputting projects, then waiting for their first action meeting from their TL), so they feel like they are working toward some kind of a tangible goal.

We'll need to perform some sort of design cycle here...
- **Estimated effort:** 3 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
Here is a concept for more specific next steps:

![first-time-team-member 2x](https://cloud.githubusercontent.com/assets/307286/19907229/e899da42-a04b-11e6-9b05-9652b105b134.png)

And a more concept with more generic tips for any user:

![first-time-dashboard-tips 2x](https://cloud.githubusercontent.com/assets/307286/19907258/fb92cb4a-a04b-11e6-9b64-39a886a843ad.png)

**Comment by jordanh** [comment]
Rad!!
