### ISSUE TITLE
After a team leader joins, direct them on next steps

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#356]
## Issue - Enhancement

After a TL has invited their team, they want to be directed on the next step – scheduling their first action meeting with their team, so that they can try working in a new way.

We'll need to design this first
- **Estimated effort:** 5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
Here is a concept using a dashboard modal pattern, thoughts?

![first-time-team-lead 2x](https://cloud.githubusercontent.com/assets/307286/19907164/b2652d78-a04b-11e6-9789-59a0a62f6d95.png)

**Comment by mattkrick** [comment]
as a new team leader with new software, i'm kinda thinking "screw you guys, i just wanna kick some tires. i'm not gonna invite my team to something i've never even seen". Maybe we don't show this until one of their team members has accepted the invite and/or has created some projects?

**Comment by ackernaut** [comment]
@mattkrick I like that idea, as it may be more timely. Also, I’m wondering if some evergreen content might be helpful: “Getting Started with Action” but that could exist in parallel.

Perhaps we have some timed messages (modals or emails) at a few points:
1) Team lead and members join, but hadn’t had a meeting yet (after 2, 3 weeks?). At that point we nudge them to schedule a first meeting.
2) Team lead sends invites, but nobody joins after 2 or 3 weeks. We could send a reminder email to those invitees?

Just thinking out loud.

**Comment by jordanh** [comment]
Will tackle during onboarding
