### ISSUE TITLE
Fix meeting completed segment event

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#3562]
## Issue - Bug

Oopsie! When we merged in changes to change the name of the meeting, we inadvertently broke the `X Meeting Completed` metric. 

Before, we used to emit:
   - `Retro Meeting Completed` for retro meetings and
   - `Action Meeting Completed` for action meetings

While it's broken, I propose we change our event schema slightly and move the meeting type to a prop called `meetingType`. If there are other things we'd like to track, might be a good time to add them too.

- **Estimated effort:** 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### Acceptance Criteria (optional)
Segment event emitted per user when:
   - A meeting begins called `Meeting Started`
      - Properties include all existing props and add:
         - `meetingType` – either `retro` or `action`
         - `meetingTemplateName` – present if a template is being used
   - A meeting ends called `Meeting Completed`
      - all the above properties

**Comment by mattkrick** [comment]
why a meeting started event?  are we trying to match a start event to an end event? if so this won't do it because i could start 2 of the same type before 1 ended. we'd need a meetingId field.

**Comment by jordanh** [comment]
Decided to drop `meeting completed` event from the AC
