### ISSUE TITLE
Release test v4.21.1

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#3565]
Add the `release` label to this issue
## The basics
Run through this list at least once:
- [x] Smoke tested the demo, unauthenticated
- [x] Created an account
- [x] Verified invite via mass link works
- [x] Verified invite via email works
- [x] Added Slack, verified meeting notification
- [x] Added GitHub, verified issue created
- [x] Added Jira, verified issue created
- [x] Smoke tested the retro meeting with 2 players
- [x] Smoke tested the check-in meeting with 2 players
- [x] Smoke tested cards on the dashboard
- [x] Created a 2nd team
- [x] Upgraded to Pro
## What’s changed
Complete the tests for any merged PRs or other issues (as needed, at your discretion):
- List each PR or issue with a header and link to ([title], #[issue id])
- Copy and paste tests, or note what was tested, in this issue
- Run the equivalent test on staging that you would run in a local environment as closely as possible (e.g. updating the database to simulate cases, etc.)

### Hotfixes: prompts, invoices, drop flicker #3563
- [x] drop a reflection from 1 column to another, there's no flicker
- [x] you can add an `apEmail` to the `draftEnterpriseInvoice` if you want the customer to be a non-user
- [x] the number of prompt columns is increased from 5 to 12

### Fix mass invitation null after expiry #3561
- [ ] on master (not this branch)
- [ ] start a meeting, go to invite someone, copy the mass invitation link, exit the modal
- [ ] go to DB and expire the link manually:
```
r.db('actionDevelopment')
.table('MassInvitation')
  .get('RHPMU031RNSS')
  .update({expiration: new Date()})
```
- [ ] go back to the meeting & go to invite someone again. see •••••••••

- [ ] repeat the steps on this branch, it works

**Comment by ackernaut** [comment]
@mattkrick trying to test the mass invite link changes:

- On staging
- I coped the invite link
- I expired the link manually
- I open the dialog again and I see the same invite token
- I refresh the browser and I see a new invite token

Am I on the right track or was that token supposed to refresh on the fly?

Otherwise, everything is looking 👌

**Comment by mattkrick** [comment]
yep, that's correct!
