### ISSUE TITLE
Upon facilitator disconnection, choose a new one automatically

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#357]
## Issue - Enhancement

If the facilitator disconnects, the other TMs will want a new facilitator chosen quickly (and perhaps automatically), so the meeting can continue without interruption.

It's possible we could also pop a toast, letting people know what happened.
- **Estimated effort:** 5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
Oh this should be fun. I kinda wanna pop a toast that originates from the avatar though. That way we can ingrain the association between the pink circle and the facilitator role.

**Comment by jordanh** [comment]
Hey, we did this one! 👏
