### ISSUE TITLE
Beta invitations signup and throttling

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#358]
## Issue - Enhancement

When we are rolling out action, we’ll want to control the number of folks who are able to sign up, so we don’t overwhelm our infrastructure.
- [ ] When folks sign up for our beta, we add them to a special beta queue table
- [ ] We generate an email containing a link they may return to see their current place in line

Team members and team leaders can invite whomever they want (we do not throttle referrals).
- **Estimated effort:** 5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
We made not need this, going to deprioritize in epic.

**Comment by mattkrick** [comment]
closing for now, we've got a mailing list that is naive, but works.
