### ISSUE TITLE
Action beta administration

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#359]
## Issue - Enhancement

When we want to admit new users, we navigate to a special administration page. We can paginate the list and select who we’d like to invite.
- **Estimated effort:** 5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
Things to include in the admin portal:

- [ ] beta signup
- [ ] GraphiQL
- [ ] rendered emails
- [ ] table form of cashay store 1 table per entity.

**Comment by mattkrick** [comment]
closing for now, we can invite folks via a mailing list instead so i can focus on stripe integration
