### ISSUE TITLE
Creating organizations

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#360]
## Issue - Enhancement

This issue may require no changes to our codebase, only testing. We may be able to use our existing invitation system.
1. Click on new control on left nav, switching to org-level view
2. Click on “Create new organization,” naming org.
3. Show list of all teams for which user is Team Leader
4. Drag-n-drop teams into new org.

We'll need to design this before we start.
- **Estimated effort:** 5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
Assuming 2 teams unknowingly join action, we'll need a way to invite teams, too. Either via email, which requires a verified email, or we need an in-app inbox.

**Comment by mattkrick** [comment]
add `firstOrgCreatedAt` to the user doc so we know if they're eligible to create an org & get a free trial.

**Comment by mattkrick** [comment]
closed in favor of putting orgs in the user settings
