### ISSUE TITLE
Organizational settings for discoverablility

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#361]
## Issue - Enhancement

An organizational leader can enable two levels of transparency for their organization to enable discovery by other team leaders:
1. **Organization undiscoverable**: it can only be joined when organization leader invites other leaders by email
2. **Organization discoverable by email domain**: team leaders can discover and add their teams to the organization from their team settings page if their email address matches one of the configured email domains
- **Estimated effort:** 5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
I don't think this is safe to try. A subordinate should not be granted permission without the consent of the parent, and consent implied via domain name means any disgruntled, recently fired employee can attack the parent org. Who invites who doesn't matter I don't think, but there should be a 2 way handshake.

**Comment by jordanh** [comment]
@mattkrick, good point.

I think it's best if we only tackle 1, above, during our beta epic for starters.

I think 2 is safe if the organization mandates all logins are federated (i.e. they don't use username-password authentication via auth0, but instead rely on their corporate authentication scheme).

**Comment by jordanh** [comment]
Obsoleted by current org/billing design.
