### ISSUE TITLE
Organizational invitations

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#362]
## Issue - Enhancement

When an organizational leader wants to invite a user to the organization, they can navigate to their organization's settings page and invite a leader by email address, so that the team may be added.
- **Estimated effort:** 5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
Can one invite a user to be a part of an organization without having any implications on teams? Also, does it make sense that an org admin would invite a team and then the team leader approves?

**Comment by ackernaut** [comment]
This would imply that any member of team automatically becomes a member of an org if a team gets added to an org.

**Comment by jordanh** [comment]
If I understand you correctly: organizations have teams. Organizations do not have users directly.

I think adding and removing organizations should _always_ be double approved. So, if an org leader invites a team lead, the team lead must approve. Visa Versa, if a team lead requests to join an org, the org leader must approve.

I think that keeps it securish...

**Comment by ackernaut** [comment]
I see a value in building a list of users based on any teams that are added to an organization, so that I can easily find and invite users in the organization. You probably have certain workflows and models in mind, so this may not be of much value at all.

**Comment by ackernaut** [comment]
And agreed on the double-approval mechanism!

**Comment by jordanh** [comment]
@ackernaut, I think the org-wide view of all users is key. I think an org "settings page" (or whatever we call it) should show a list of all users who belong to the org. I also think the org admin should be able to mark any user they please as inactive.

**Comment by ackernaut** [comment]
Ah, ok! Good clarification.

**Comment by mattkrick** [comment]
i think we got this pretty well figured out with the current structure, closing for now.
