### ISSUE TITLE
Team leaders add teams to organizations.

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#363]
## Issue - Enhancement

Once #361 is completed:

If an organization's leader has opted to make their organization discoverable by email domain, team leaders may navigate to their team settings page and add their team to the organization.

The organization's leader will then receive a notification to confirm the request to join the organization. The request must be confirmed, because joining the organization could have an impact on billing.
- **Estimated effort:** 5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
As a user under one email, a person can be a member of teams that are tied to different organizations and/or no organizations?

**Comment by jordanh** [comment]
Obsoleted by current org/billing designs.
