### ISSUE TITLE
Card content auto-resize

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#370]
## Bug

Sometimes long `textarea` content does not auto-resize until hover: http://recordit.co/5djnjz4G8T

I suspect Aphrodite styling and `react-textarea-autosize` need to talk to each other a little more?

**Estimated effort:** 1 point ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Reevaluate during WYSIWYG epic.
