### ISSUE TITLE
Read-only team name outline/focus

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#373]
## Bug

Improve the read-only state of the card team name. Remove the outline.

![screenshot 2016-10-11 15 56 15](https://cloud.githubusercontent.com/assets/307286/19288380/67a9acc2-8fcb-11e6-90a2-f5031aab3611.png)

**Estimated effort:** 1 point ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
I'd be up for an outline:0 prop on all buttons...
Oh crap, come to think of it this is a button cuz I was trying stuff out.
We could make it a div again if we wanted

**Comment by ackernaut** [comment]
I can push a patch.
