### ISSUE TITLE
Encrypt data at rest

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#375]
## Issue - Enhancement

For corporate deployments, we may have to be like Slack and encrypt our data at rest. It should be readable only to the organization. Stuff like: team names, projects, actions, etc.

We could _probably_ stick a symmetric, team-level key in the token and decrypt on the client.
- **Estimated effort:** 10 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
resources:
https://friendlybit.com/security/how-to-make-e-mail-encrypted-for-everyone/
