### ISSUE TITLE
Redirect meeting participants (not just Facilitator) to team dash on Meeting End

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#378]
## Issue - Enhancement

When the Facilitator clicks the end meeting button, they get redirected to the team dashboard. However, the other meeting participants only get redirected to the Lobby.

We should also redirect them to the team dashboard.

We might also want to pop a toast, letting them know what happened.

- **Estimated effort:** 1 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
Is this temporary until we have a Meeting Summary view?

**Comment by mattkrick** [comment]
ah, forgot about the summary view! yeah, we should just direct em to there instead.

**Comment by jordanh** [comment]
Ah! Good call. Ok, I will close this and add the redirect to the Meeting Summary checklist.
