### ISSUE TITLE
Uncaught TypeError: Cannot read property 'openArea' of undefined

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#379]
## Issue - Bug

This one might be tricky to reproduce. I encountered it this morning with the following steps:
1. Long running tab open to production server, navigated to `/me` (My Dashboard)
2. Clicked on wrench icon to move a completed project to **Done**, project card moved over but then did not completely render content:

![image](https://cloud.githubusercontent.com/assets/103000/19349984/f11a62fe-9123-11e6-8832-88c5a3eebd78.png)
1. Clicked on another project's wrench, clicked on **Done**, but UI stopped responding. Checked console and saw:

![image](https://cloud.githubusercontent.com/assets/103000/19350024/14eb6048-9124-11e6-8357-0f1c288db665.png)

![image](https://cloud.githubusercontent.com/assets/103000/19350037/2539a072-9124-11e6-9f4a-2bfca04fbc95.png)

![image](https://cloud.githubusercontent.com/assets/103000/19350059/3c904cda-9124-11e6-8f79-7dc1ce68b5f7.png)

When I reloaded, I was unable to reproduce this issue. Perhaps it was a dead socket?
- **Estimated effort:** 3 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
Is this related to #437 ?

**Comment by mattkrick** [comment]
mmm, seems like it! No way to know until we fix it though... i'll dig through the logs again & see if i can find a pattern...
