### ISSUE TITLE
where should the meeting sidebar >> agenda link go?

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#382]
We can click the agenda link from 5 different states:
- meetingPhase is < firstCall phase: don't go (make it unclickable? pop a toast saying you can't go there yet?)
- meetingPhase === firstCall phase: goto firstCall
- meetingPhase === agendaItem phase: goto to wherever the facilitator is? or wherever the meeting is?
- meetingPhase === lastCall phase: goto last call?
- meetingPhase > lastCall phase: goto `agendaItems/1`?

What do you guys think?

**Comment by jordanh** [comment]
I can't improve on this, it's perfection, toast and all!
