### ISSUE TITLE
Websocket does not always reconnect when disconnected

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#385]
## Issue - Bug

During an active browser session (i.e. the tab wasn't left open or sitting around to time out), the socket appeared to disconnect. Then, this message was produced on the console.

![image](https://cloud.githubusercontent.com/assets/103000/19443371/7f59076c-945a-11e6-93aa-1837e9e2dbef.png)

I had to reload in order to get reconnected.
- **OS:** OSX
- **Browser:** Chrome

**Comment by mattkrick** [comment]
next time this happen, send me a screenshot of the websocket traffic.

**Comment by jordanh** [comment]
I saw this one again this morning, this time on my home internet (vs. the sometimes crappy internet at the coworking space). Steps were:

1) Navigate to https://action.parabol.co (credentials had expired), login
2) Click to apply a check to mark an action as completed, noted that action did not disappear
3) Opened console and saw:

![image](https://cloud.githubusercontent.com/assets/103000/19520000/6bd4a1aa-95dc-11e6-9cd0-11bc173b484b.png)

I didn't have the console open and logging network traffic, so I didn't capture it. I'll keep using action today with logging enabled to see if I can catch it...

**Comment by jordanh** [comment]
I haven't seen this one again. Closing for now.
