### ISSUE TITLE
GraphQL error permanently fails welcome wizard

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#386]
## Issue - Bug

This is a _fun_ one. I think it's related to #385. 

Erica at August was going through the process of onboarding her team. During step3 of the welcome wizard, she hit the `Looks good!` button and..._goose egg._

Luckily I was nearby and had a look at her console. There was a GraphQL error "unable to resolve `https://<production server url>`

Turns out the internet has been patchy here all day. This bug probably needs two things to resolve:
- [ ] Pop a toast on network trouble
- [ ] Gracefully catch network exceptions
  - [ ] http transport
  - [ ] socket transport

---
- **OS:** OSX
- **Browser:** Chrome

**Comment by mattkrick** [comment]
we do catch the exceptions, we just don't do anything with em :smile:.

Network trouble is pretty easy. we have a `setTimeout` to pop a toast that goes off in 20 seconds. When the server sends us a message, we cancel that timeout & reset it.

However, we could fail in between heartbeats, which I'm guessing is what happened. When this happens, the error gets put in redux, but we currently don't do anything with it. We could do a few things:
- make cashay write to a global error field & write a component way up in the tree to pop a toast if this value changes
- write our own custom Transport that pops a toast
- write a handler for every single query/mutation

**Comment by jordanh** [comment]
Closing this for now.
