### ISSUE TITLE
My Dashboard active under settings route

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#388]
## Issue - Bug

My Dashboard link `/me` is set to the active state because of the `me/settings` route when in the personal settings section. I think it should only be active when one is actually at their My Dashboard space.

![screenshot 2016-10-17 16 32 37](https://cloud.githubusercontent.com/assets/307286/19456574/ab853720-9487-11e6-8719-385345160b97.png)

**Estimated effort:** 1 point ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
i turned this on because if you go to `/team/team123/archive` we want to still highlight the team.
Should `/me` be a special case?

**Comment by ackernaut** [comment]
I _think_ so but I could be wrong. At some point in the future we will probably need to iterate on the chrome and navigation, but I think that in this case “My Dashboard” should only be active in one scenario—if you’re there! :)

**Comment by ackernaut** [comment]
PS. I’m thinking through navigating sub-sections under settings.
