### ISSUE TITLE
Do not require enter key to advance check-in

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#393]
## Issue - Enhancement

When performing the check-in phase of the meeting, I want to simply press a key (**P**resent or **N**ot present) to advance the card, so that I can save keystrokes.

Needing to press enter isn't quite obvious enough...

- **Estimated effort:** 1 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
i love this! so we should advance if they press p/n?

**Comment by jordanh** [comment]
Yes, exactly Matt!
