### ISSUE TITLE
Migrated to inline styles

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#40]
## Mission - Enhancement

We're migrating Action's react containers and components to use inline styles (either Radium or react-look). The enhancement will give us the following advantages:

- Smaller/optimized client payload
- Component re-use
- Easier targeting to react-native for a future mobile app

**Comment by jordanh** [comment]
[react-look](https://github.com/rofrischmann/react-look) looks like a winner. We've got it wired up in [an experimental branch](https://github.com/ParabolInc/action/tree/inline-style-experiment).

One issue remains before we commit: @ackernaut presently generates a set of SCSS [theme classes](https://github.com/ParabolInc/action/tree/master/src/universal/theme/variables), one of which generates a [rather rich palette](https://github.com/ParabolInc/action/blob/master/src/universal/theme/variables/_theme.scss). When we move to javascript inline styles, we rather not compute this on every request but have it precompiled by webpack.

A couple options to consider:

1. Keeping the theme as SCSS or PostCSS and offering the entire file as a small inline static asset
2. Rewriting it as JavaScript and finding a way to 'build it' (i.e. unroll the loops) via webpack and have `react-look` only include theme variables that are used in the rendered HTML.

@mattkrick, what do you think? Any other options you can think of? Personally I find 1 the most straightforward...

**Comment by mattkrick** [comment]
ultimately, babel. For the interim, I say we write a quick n dirty function that inputs the palette to compute & outputs a `.js` or `.json`. Then, juse use that. Since the palette will almost never change, it'd actually be better than babel since it'll keep run times down.

**Comment by jordanh** [comment]
This is what I ended up doing. Have a look / tear apart: https://github.com/ParabolInc/action/commit/29499573fa1263f9e834d1d643feb12f39cc2658
