### ISSUE TITLE
Safari browser styling compatibility

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#403]
## Issue - Bug

Sasha reported that our dashboard layout was massively broken on Safari.

I tested this morning and was unable to reproduce, but I also have a newer version of OSX and Safari. The only issue I could find on the Dashboard was with card rendering:

![image](https://cloud.githubusercontent.com/assets/103000/19518809/156b6358-95d7-11e6-8ca9-77f907459000.png)

If I find out more, I'll add to this issue.

- **OS:** OSX
- **Browser:** Safari Version 10.0 (12602.1.50.0.10)
- **Estimated effort:** 2 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
that bug is present in chrome as well. i think it's because the auto-resizing textbox plugin we have doesn't do so lazily, so it grabs the measurements before the text gets loaded by redux.

**Comment by ackernaut** [comment]
This might be one way of seeing the layout issues (run the version of Webkit that corresponds to Sasha’s version of Safari): http://stackoverflow.com/questions/33423269/is-there-a-way-to-install-emulate-an-older-version-of-safari-i-e-8

**Comment by mattkrick** [comment]
i think @ackernaut fixed up the safari sidebar styles & the resize is covered by #370. feel free to reopen if i'm wrong
