### ISSUE TITLE
Meeting summary stand-alone improvements

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#408]
## Enhancement

If we use a stand-alone view, it needs:

- [ ] A team name
- [ ] A date
- [ ] A link to the team dashboard
- [ ] Better zero states when there are no agenda items or projects/actions etc.

Currently:

![screenshot 2016-10-19 10 14 27](https://cloud.githubusercontent.com/assets/307286/19524936/020fb80a-95e5-11e6-9827-719c555a5860.png)

Something to work towards:

![summary-stand-alone 2x](https://cloud.githubusercontent.com/assets/307286/19527526/f7b9a47a-95ed-11e6-9aa8-8be22d60b2d7.png)

- **Estimated effort:** 1 point ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
The mock-up doesn’t show suggestions for zero states, but working on that! Otherwise, how does this look @mattkrick ?

**Comment by mattkrick** [comment]
Does it make sense to bump up the "An email summary..."? the email will include just about everything in there, above & below that message
