### ISSUE TITLE
First Call / Last Call with Agenda List input inline

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#418]
## Enhancement

On the First Call view (and perhaps on Last Call), it would be great to have a large input in the middle of the text here (mock-up coming):

![screenshot 2016-10-20 16 42 27](https://cloud.githubusercontent.com/assets/307286/19579162/bca6f4d0-96e4-11e6-8b90-84ca0c74fe13.png)
- **Estimated effort:** 1 point ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
What about something like this? Should we do it for the Last Call too? I think NOT see we have some inline stats on meeting progress and the End Meeting button.

![agenda-first-call-inline-input 2x](https://cloud.githubusercontent.com/assets/307286/19579643/57edd434-96e7-11e6-87cf-fd670042bd2c.png)

**Comment by mattkrick** [comment]
i like the idea!
so this means we'll have 2 places to add stuff. should these be controlled inputs so updating 1 updates the other? I'm thinking no, but it could be.
Should we autofocus it? 
Is there some way to visually tie the input box to the list of agenda items on the left? maybe animate the box out from the left?

**Comment by ackernaut** [comment]
Yeah I like those ideas @mattkrick !

I’m thinking only one input can be used at a time, so only one input should be active locally. But I like exploring some way to associate the center input with the left list.

**Comment by jordanh** [comment]
I'm considering pushing this to The Future. It's a _really_ good enhancement but perhaps we start with tooltips?

**Comment by ackernaut** [comment]
I can agree to using tooltips first, to move faster on this.

**Comment by jordanh** [comment]
Make sure to see #469 for latest designs.
