### ISSUE TITLE
Team Invite email enhancements

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#423]
## Enhancement

A few things I think could help here.
- [x] We can improve the main message (you have been invited to TEAM) by perhaps using the call-out box pattern or something similar.
- [x] Add a link to “How to Navigate Uncertainty” on “develop your weekly rhythm”. In the future we can link this to Action 101.
- [x] Fix the text color. Gmail adds a dark purple color to un-styled, repeated text in email chains, but it can be overridden by CSS styles within the email.

![screenshot 2016-10-21 17 30 05](https://cloud.githubusercontent.com/assets/307286/19613820/c9dc744c-97b4-11e6-8cbe-c329f44900c5.png)
- **Estimated effort:** 1 point ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
![invite-email-minimal 2x](https://cloud.githubusercontent.com/assets/307286/19867847/799e0e34-9f73-11e6-87dd-6ab60a5aa1bf.png)

**Comment by ackernaut** [comment]
An effort to make this email a little more clear—safe to try?

**Comment by jordanh** [comment]
Definitely safe to try!
