### ISSUE TITLE
fix end meeting redirect to summary

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#425]
@jordanh can you help me reason through this?

When the facilitator clicks end meeting, we need to:
- generate the summary
- redirect all participants to the summary page
- reset the meeting (setting meetingPhase to LOBBY)

As you can see, when i reset the meeting, it tells everyone to go to the lobby. So, I need to make certain that everyone is on the summary page before that gets triggered. The only way I can think of doing it is waiting x seconds before reseting the meeting, because as we saw, doing it immediately after can cause a race. & a url that doesn't match up with the screen.
Alternatively, we could publish something to that socket channel, but then we'd have to account for folks who are on that team but in other meetings, etc etc...

There has to be a better way!

**Comment by jordanh** [comment]
Could you detect the transition on the client from X -> lobby and interpret it as "summary is coming..." rather than an explicit call to return to the summary?

**Comment by mattkrick** [comment]
I think that works! My only reservation was the super secret escape hatch, but as long as oldProps.meetingPhase === LAST_CALL && nextProps.meetingPhase === LOBBY then it will work. Granted, you won't be able to use the escape hatch once you've made it to last call, but I guess that's OK for now.

The only alternative that I could see would be to move the meeting phase to summary, wait 10 seconds, and then move it to LOBBY. It would be more expressive, but at the cost of a setTimeout since there's no easy way to signal that all members have reached the summary page.

**Comment by mattkrick** [comment]
nope, doesn't work. we can still get new props on the same tick, causing it to reset to the lobby url.

**Comment by jordanh** [comment]
Ah bummer. So setTimeout it is then?

**Comment by mattkrick** [comment]
not necessarily. here's everything we need to do:
- client -> server "End meeting"
- server generates summary
- server -> client "goto Summary"
- server resets meeting

and here's the implementation: https://github.com/ParabolInc/action/blob/summary-one-size-fits-all/src/server/graphql/models/Team/teamMutation.js#L282-L292

Now, this works off the following assumption:
- server -> DB set phase to summary
- DB -> changefeed handler send updated team doc with phase == summary
- server -> DB set phase to lobby
- DB -> changefeed handler send updated team doc with phase == lobby

As it's written, it works. The DB sends down a new doc before the next action on the server. I think this is guaranteed by RethinkDB because we aren't using a squash so every change is guaranteed to get sent in the order that it was received.

**Comment by jordanh** [comment]
Just tested with v0.9.4 on staging. I still got the lobby link. This is a tricky one! Perhaps you and I can look at this later today?

**Comment by mattkrick** [comment]
fixed!
