### ISSUE TITLE
redirect after login

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#436]
if i type in `http://localhost:3000/meeting/team123/lobby/` then it takes me to the home screen if i'm not logged in.

after i log in, then it should take me back to the lobby.

**Comment by jordanh** [comment]
**Estimated effort:** 2 points + 10 bonus points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
pinging @ndey96, i think this would be a fantastic next project after the rejoin facilitator sprint.

**Comment by jordanh** [comment]
**Hooray! 🎉 ** @ndey96: I've [credited you 12 more points, you're new total is 52](https://docs.google.com/spreadsheets/d/1V1KZJn6oKFsqrYwqr430rO3hkIkekSY7oYFzX3cVty4/edit#gid=679741853).
