### ISSUE TITLE
Fix linting errors after Meatier migration

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#44]
## Issue - Bug

After migrating to [Meatier](https://github.com/mattkrick/meatier), nearly 200 linting errors were introduced, not surprisingly, since Meatier used the rules from [xo](https://github.com/sindresorhus/xo).

To complete this mission, reduce the number of linting errors to 0. Please use the latest version of `eslint`, `>=v2.7.0`.

- OS: `OSX 10.11.4`
- Node version: `v5.10.1`
- NPM version: `3.8.6`
- RethinkDB version: `rethinkdb 2.2.5 (CLANG 7.0.2 (clang-700.1.81))`
- Estimated effort: 8 points ~ less than two weeks ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))
- Link to mission spec: https://goo.gl/ESjhWB

**Comment by jordanh** [comment]
Hey @jrwells, will you accept 8 point bid for this one?

**Comment by jrwells** [comment]
Yeah, I'll take it for 8 points.

**Comment by jordanh** [comment]
Sold to you @jrwells (retroactively)
