### ISSUE TITLE
Add hover to avatar in team meeting to show location of participant

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#441]
## Issue - Enhancement

Wouldn't it be nice to know where folks are? We could add a hover state to avatars in the meeting to inform people where they are.
- **Estimated effort:** 5 points + 10 bonus points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
Is this too much sharing?

"Hey Matt, stop goofing off in the updates section!" could very easily trigger the same fearful feelings of "Hey Matt, I see your browser history. I'm gonna pray for you."

**Comment by ackernaut** [comment]
Yeah, I hear your point @mattkrick —at any rate, I feel this belongs on a list of explorations rather than enhancements. But I like having a place to capture our ideas…do we add a label `exploration`?

**Comment by mattkrick** [comment]
oooo yeah, RFC exploration type stuff would be a good category

**Comment by jordanh** [comment]
Let's just call them "Ideas"
