### ISSUE TITLE
Change hard link to meetingLayout/lobby in Sidebar.js

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#454]
## Issue - Bug

I saw this requests to `/meetingLayout/lobby` on Mixpanel, and thought it looked strange. Here's where it's defined:

https://github.com/ParabolInc/action/blob/v0.9.5/src/universal/modules/meeting/components/Sidebar/Sidebar.js#L41

Right now our router will kick folks to `/` then to `/me` so it's not a huge show-stopper, but we should fix it!

- **Estimated effort:** 1 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
fixed in #453.
