### ISSUE TITLE
Leave team

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#459]
A team member should be able to leave a team. 
- if they are a regular member, should we notify anyone if they leave?
- if they are a leader, should we offer to inactive the entire team or have them select a new leader?
- if they are the last person on that team, should we offer to delete the team?

**Comment by ackernaut** [comment]
It seems that team owner or team admin might be a more appropriate title and role than team leader. Perhaps if a team owner/admin leaves, they are prompted to select a team member who will assume that role? If that person really didn’t want it, perhaps they can pass it on to somebody from within team settings?

**Comment by mattkrick** [comment]
this was completed in the team settings sprint
