### ISSUE TITLE
Re-enable minification in production, add sourceMap output to webpack

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#462]
## Issue - Enhancement

This is a bit of a meta-issue, but we'll keep here to track.

- **Estimated effort:** 2 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
@jordanh dumb question-- why do we want to ship sourcemaps in production? on a less-than-great connection, they'll take up that precious bandwidth, right?

**Comment by mattkrick** [comment]
of note: comments aren't getting minified right now, that's a bummer. will need to investigate more.

**Comment by jordanh** [comment]
Ah, the comments thing is a bummer.

What we want to do is enable the generation of source maps, but not have them pulled down by clients by default. Then, if something breaks, we as developers can enable using them at runtime so we can debug things comfortably.

I'm not sure the _how_ on this yet, but this is the desired state :)

**Comment by mattkrick** [comment]
wow, i'm not really sure if that's possible. the only thing i can thing of is looking for `rol: su` on the token & using HTTP2's server push to push the sourcemaps. 

I think a simpler method is taking the state output from raven & setting that as the current state as the current user on staging.

**Comment by jordanh** [comment]
How about? https://plus.google.com/+AddyOsmani/posts/2iyJecVeK1Q

**Comment by mattkrick** [comment]
Good ol' googlers... That looks super legit! So we wanna build the
sourcemaps in the prod build, but default to not serving them?

**Comment by jordanh** [comment]
Yes, exactly!

**Comment by jordanh** [comment]
Waiting on:

via @mattkrick 
> This may help with source maps:
>https://github.com/kossnocorp/assets-webpack-plugin/pull/56
