### ISSUE TITLE
Collapsible project columns

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#463]
## Enhancement

Let’s explore a UI design for collapsing project columns in dashboard views. Some initial thoughts:

- Use a control in the project column header to collapse.
- Collapsed project column icons (done, active, stuck, future) could sit in the project columns header space with other controls.
- Perhaps add a badge to see how many cards are in a collapsed column.
- Any subtle, tasteful animation?
- Save the state per user, so that when they return to a dashboard view users see columns as they left them.

**The value to users?**

I’m thinking that it would be a simple, utilitarian way to organize the dashboard space in a way that is helpful for prioritizing what to focus on.

**Estimated effort:** 2 points + 10 bonus points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by sarakhatri** [comment]
[Parabol Animation Guidelines ](https://docs.google.com/a/parabol.co/document/d/1UnjHCEHsRWsmTLIsGrbBFY8hVyoiRyw0EQXPgSN4xDM/edit?usp=sharing)
