### ISSUE TITLE
Websockets not falling back to http polling?

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#464]
## Issue - Bug

@tayamueller was paired to her hotspot this morning and was surprised that her teams and dashboard weren't loading.

When I cracked open the dev console there was an error showing that the client could not connect via websockets to the server. It looks as though her phone does not support websocket connections (or does so half-assed where the socket attempts can be made but don't actually reach our server). Her problem went away when she connected to the local Wifi AP.

There are probably two things we should do to resolve this:

1) Double check under which circumstances we'll degrade the socket to a polled HTTP connection
2) We should pop a toast or some other error to more clearly indicate connection trouble (and underlying causation if possible)

- **OS:** Chromebook
- **Browser:** Chrome
- **Estimated effort:** 5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
Fallback is something exclusive to socket.io i think. I'd be more interested in seeing why her hardware doesn't support it (too old? firewall?). I'm cool with popping a toast, but supporting a fallback would mean a huge rewrite of socketCluster.
