### ISSUE TITLE
Press escape to blur agenda list input

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#466]
## Enhancement

Users should be able to press the `escape` key to blur the Agenda List input.

**Estimated effort:** 1 point ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
On dash or meeting?

**Comment by ackernaut** [comment]
Both?

**Comment by jordanh** [comment]
Definitely both!
