### ISSUE TITLE
First Call / Last Call multiplayer enhancement

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#469]
## Enhancement

**JBTD #1**: What a team is on the first call, they need a way to build the agenda as a primary action (central, multiplayer UI over sidebar, chrome utility) so that they can be engaged and capture any remaining tensions before kicking off the agenda round.

**JBTD #2**: When a team is on the last call, they need to clearly know if new/unprocessed agenda items are still in the queue (or being added) so that they can process instead of end the meeting.

First pass checklist:

- [ ] Shows new/unprocessed agenda items front and center.
  - [ ] Can click to agenda item.
  - [ ] Can remove to agenda item.
- [ ] Bonus points: shows who is adding an agenda item in the main view.
- [ ] Bonus points: if we build an input for the main view, we can use here. #418 

**Note**: Assuming only the facilitator can end the meeting, I think we should defer disabling the End Meeting button (what if something gets stuck??), and perhaps consider a confirmation modal (“Are you sure? Still seeing some unprocessed agenda items!”) when unprocessed items are still in the queue.

**Estimated effort**: 18 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
**Here are a couple of mock-ups for feedback**:

Last Call has inline input with multiplayer feedback:

![agenda-last-call-agenda-inline 2x](https://cloud.githubusercontent.com/assets/307286/19987335/a5a49788-a1e8-11e6-98c2-6b1bddb1692b.png)

Last Call shows unprocessed items with controls to navigate/remove:

![agenda-last-call-agenda-items 2x](https://cloud.githubusercontent.com/assets/307286/19987336/a5ad77a4-a1e8-11e6-8a0f-5fab8a2c001d.png)

**Comment by jordanh** [comment]
See duplicate #418 for more thinking and information
