### ISSUE TITLE
Add form validation

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#472]
I need to build a package for universal type validation. Both server & client should rely on the GraphQL custom scalar types. It should probably function as a yup plugin.

**Comment by mattkrick** [comment]
As we wrap up alpha, I'm digging into this a little bit, since a beta means a bunch of punks submitting 30MB base64 files for their team name and our poor little DB wondering why we're punishing it. 

Looks like a yup plugin wouldn't be all that useful. However, a cashay plugin would be extremely useful.

Something like:
```
import makeValidate from 'cashay-validation';
import * as types from 'server/graphql/models/types';
const validate = makeValidate(types);
cashay.create({validate});

// in a redux form validation
const validate = (values) => {
  return cashay.validate(values, 'updateUserProfile');
};
```
Since cashay is a singleton, we could just add in a validate method to that singleton.
The third arg could be an options thing which would validate only part of the argument object, or override the server error message, etc. I don't like that cashay is used for 2 things (do 1 thing do it well...) but to maximize code reuse & make validation so stupid easy, this is the only way I see it working.

**Comment by jordanh** [comment]
There are some really nifty possibilities here. A few questions for exploration:

1. Would the package be capable of using the GraphQL types directly _and_ the extracted schema (as provided on the client)?

2. Instead of writing your own whole-cloth validator, what about creating a package `yup-graphql-shape` that returned a yup `shape` object from various points on the schema? Would that cover all/most of the use cases?

3. If you wrote your own validatator (which I can see why it would be appealing) would you use another validator package under the covers?

**Comment by mattkrick** [comment]
1. it would basically map the GraphQL types onto the cashay client schema
2. We could, but thinking about it some more, that means writing very terse GraphQL custom scalars, and then just having something convert those scalars to a yup schema. Might as well just write a yup schema to begin with
3. Using GraphQL as a one-stop shop for validation won't really work. Right now, we'll need extra validation, both sync and async, on both client & server (eg does the email already have an outstanding invitation?)

It's a bummer. I think GraphQL's validation goes _just_ far enough to flirt with being useful, but in the end, we'll need to write our own validation & include it in the resolve function. GraphQL basically scratches the itch for `isRequired` and `typeof`, but leaves us high & dry for everything else.

Ultimately, I think we'll end up with a validation function for each type that is used as an arg in a GraphQL query or mutation. That function could include some basic stuff (probably using yup) and some complex stuff (custom logic). The client would have its own function that would share the basic validation, but the complex stuff would be written separately (sometimes it'll need to be async).

**Comment by mattkrick** [comment]
man, getting really bummed out using yup.
- all validation is async
- an error object is stuffed inside an Error subclass when it could be an array of errors
- To get the error, you have to either use try/catch or `then`. Neither is great for pretty code.
- doesn't lazily evaluate the schema (you can do it with a `lazy` call, but that adds overhead)
- still need to transform the output to match what redux-form expects

Think I could do a better job with a LOT less code using monads. Here goes.
