### ISSUE TITLE
Meeting: pop tooltip on agenda during updates, first, and last call

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#481]
## Issue - Enhancement

Follows #272. Feedback from Clay at [aug.co](http://aug.co).

We instruct a user to press `+` to add agenda items during first and last call. He told me he had difficulty finding where the agenda was. Others have shared they don't really understand what the agenda list is for during updates.

I believe some tooltips on the agenda list input box could help clear this up.

- **Estimated effort:** 2 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
so if we really wanna gamify this...
our onboarding experience could have different achievements unlocked 
![image](https://cloud.githubusercontent.com/assets/5514175/19983850/e7ca41dc-a1c8-11e6-9d6a-4a6670fdd66a.png)

- Added my first agenda items
- started my first meeting
- ended my first meeting
- participated in my first meeting
- added my first action
- added my first project
- took over a project for a team member
- created a new team
- joined an org

so let's take agenda items...
when we hit first call, if they _haven't_ unlocked that achievement, we auto pop an onboarding tip telling them what it is & how to get there ("hit the + button" == "do a barrel roll")

**Comment by jordanh** [comment]
Matt Daniels and poly-graph.co also couldn't find the agenda list. When they came to first call, they thought we hadn't implemented it yet.

So, +1 to this.

**Comment by mattkrick** [comment]
Assigning to @ackernaut to put in his ever-growing design queue. Let's go for quick & dirty for now & then during the onboarding sprint we can homogenize all the helpers.
