### ISSUE TITLE
Improved progress bar navigation controls

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#484]
## Enhancement

Currently, meeting views show a progress bar that is navigable under the team avatars when we one can navigate to other team members (during Check-In and Updates phases).

The clickable location controls (squares under each avatar) are small and not obvious.

Some suggestions and considerations for improving:

- We could make the avatars clickable, but this would be inconsistent during Agenda processing as the order is based on agenda items and not team members.
- When the block containing the avatar group and progress bar is hovered, we could show more obvious controls—and then they could become even more obvious when when each point on the progress bar is actually hovered.
- We’ve thought of future design where clicking the avatar would show a drop-down menu with items like: Go To, Make Facilitator, etc.

Just logging and designing for now!

<img width="367" alt="screenshot 2016-11-01 11 13 57" src="https://cloud.githubusercontent.com/assets/307286/20010183/2d5b25ac-a275-11e6-846d-f6e74c3fc439.png">

**Estimated effort:** 2 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Of the options above, I intuitively like the hover idea the best... That also encourages exploration.
