### ISSUE TITLE
Agenda input advances from First & Last Call views

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#491]
## UX Bug

When pressing `enter` in the Agenda List input, it advances to the next view. If there is at least one item, it navigates to that item from First Call. If there are no items, it navigates to Last Call from First Call. If a Facilitator presses enter from Last Call it ends the meeting.

Suggestion: Scope `enter` to submit only when interacting with the Agenda List field.

**Estimated effort:** 1 point ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
closing in favor of #494 as that encompasses the overarching problem.
