### ISSUE TITLE
Regression: other component's hotkeys remain active when agenda list focused

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#494]
## Issue - Bug

When the agenda list input has focus, other component's are still listening and active when the characters are input.

For example, when a user is processing an agenda item and decides to add a new item to the list, a new project or action can be created accidentally if the agenda item contains either an `a` or a `p`:

![jw3itr0arb](https://cloud.githubusercontent.com/assets/103000/20038857/916a69e2-a408-11e6-83e0-d8860693a75d.gif)

Oof-dah.

Here's list of scenario:

- Pressing `enter` after having input an agenda item during project updates
- Pressing `enter` after having input an agenda item during first call
- Pressing `enter` after having input an agenda item during last call
- Adding an agenda item during agenda processing

This fairly seriously affects usability. We should fix ASAP.

- **OS:** OSX
- **Browser:** Chrome
- **Estimated effort:** 2 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
I'm working this one now. I think a good approach here is to do the following:

1. Extend [react-hotkey-hoc](https://github.com/mattkrick/react-hotkey-hoc) with functions that allow for the registration of a custom [Mousetrap.stopCallback()](https://craig.is/killing/mice#api.stopCallback) function.
1. Register a custom stopCallback when the agenda list is focused to ignore all keybindings but the ones used in the textarea field.

**Comment by mattkrick** [comment]
Let's remove the mousetrap class name from the input. Then hotkeys don't
activate

**Comment by jordanh** [comment]
@mattkrick if we did that, then escape wouldn't work to exit the field. I think I've got a better way. Standby.
