### ISSUE TITLE
Invitations for new teams not really optional

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#496]
## Issue - Bug

When you create a new team, you can't really just leave it blank:

![image](https://cloud.githubusercontent.com/assets/103000/20045083/3d7c5994-a46c-11e6-9e4f-98a975c0ccc5.png)

- **OS:** OSX
- **Browser:** Chrome
- **Estimated effort:** 1 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
i'd say this falls into a "form validation" sprint that we _really_ need before public beta. Should we tackle validation first or orgs?

**Comment by mattkrick** [comment]
this was fixed during the form validation sprint.
