### ISSUE TITLE
Color coding - tabs vs columns

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#499]
## Issue - Enhancement

There is no visual distinction btwn team duties in My Dashboard view. Currently, each card is color-coded to match the column it sits in. Change background color of each column to lightest value of it's "theme" color, then change the top color of each card to correspond to Team color.

**Comment by jordanh** [comment]
I've got this feedback from others as well: there is a desire to use color to label teams, rather than to label card status.

**Comment by tayamueller** [comment]
Frequent, undeniable feedback that pre-assigned color-coding is not helpful. I recommend this gets moved up in priority; particularly as we begin work on Trello integration.

Recommendations:

1) Eliminate column header colors entirely. Feedback suggests that a card's physical presence in any of the 4 vertical lanes is enough visual link to 100% grok its state of done/active/stuck/future. Our pre-assigned color coding is not necessary to make that any clearer.

2) Most new users ask about changing the names of the column headers...I believe this is already an Issues? (Our own use-case of this: JH & I would love to have a board for fundraising where we can move investor targets through a "process" but the current column headers don't work...so we're using Trello :)

3) I observe that most new users immediately look for ability to self-assign color-coded project or theme tags--this is true whether they are previous users of Trello (which offers this feature) or not! This suggests something that maybe should have been obvious earlier: our own Team only uses our "Parabol Product" Board to work on ONE project together. However, our Parabol ExCo team (and most other teams in the working world) will need to use Boards for multiple projects. Therefore, the most useful function of color-coding is for self-assigned theme tags, NOT our pre-assigned state (done/active/stuck/future) tags. I strongly believe this may be the single biggest barrier to adoption for Trello users, and I see strong signals that it's an instinct for non-Trello users as well. 

* Future scenario: imagine a team like Parabol Exco, which currently has cards that could easily be self-assigned color coded themes/tags as "Payroll", "Fundraising", "Hiring", "Outreach", etc. As our team grows and adds more Sales, Opps, Marketing, etc teammates--we will eventually be too big to efficiently exist as 1 ExCo team any more. We will need to spawn "pup" teams for each function/division as we grow. It would be AWESOME to be able to "grab" all the cards tagged as "Hiring" and start a new HR Team that is pre-populated with all those cards & any teammates assigned to them....

**Comment by ackernaut** [comment]
I like the suggestions and there are probably related issues. I have some ideas for project columns as well. I do agree that we should bump this to Epic 5 (which I did) because I think it will be part of the design discussion for integrations in general. We create cards from other systems based on what criteria and into what columns?

See:

#620 
#623 

Etc.

**Comment by ackernaut** [comment]
Reviewing for design iterations/considerations:

I would dig an expanded palette that could be used for auto-generated team avatars. Originally I saw user avatars as being circles and team avatars as being rounded squares.

I think status colors still make a lot of since but can be minimized in the UI. I think a consistent team avatar color may help. Also maybe we work in status icons a little more.

**Comment by jordanh** [comment]
Groomed 14-Feb-2017, decided not to icebox. @tayamueller will apply acceptance criteria

**Comment by tayamueller** [comment]
I believe this user need will be fulfilled by #1474 + experimenting with "Titles" at the top of each card
