### ISSUE TITLE
Show by Team Member filter implimented

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#505]
## Issue - Enhancement

Let's wire up the "All Team Members" filter control:

![image](https://cloud.githubusercontent.com/assets/103000/20121978/7c29f86e-a5e2-11e6-809b-dc74e81926ee.png)

It:

- [ ] can drop down to select one team member and,
- [ ] filter the projects in the kanban lanes that appear below

- **Estimated effort:** 2 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
I added this to our [Equity For Effort](https://github.com/ParabolInc/action/projects) program.

**Comment by mattkrick** [comment]
just wrapping this one up:
- when i go from Team A to Team B, what is the expected behavior? Do i reset the filter? Do i reset only if the selected filter doesn't exist for Team B?
- when i got back from Team B to Team A, do I keep the original Team A filter? Or does it reset?

**Comment by mattkrick** [comment]
for now, i assumed that the filter should reset when you leave that team dashboard (most naive implementation).

**Comment by jordanh** [comment]
I really like the implementation you chose. In the future, I could see us making it such that when you click on the avatar image above the `TeamProjectsHeader` that it would also drive filter selection.
