### ISSUE TITLE
Team settings sprint: unable to fully join new team on invite without logout/login cycle

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#509]
## Issue - Bug

This is a funny one. I wonder if it isn't a pre-existing bug...

Steps to reproduce:

1. `npm run dev`
1. Login as `matt@prbl.co` and navigate to team settings
1. Invite new user `frank@prbl.co`, open console and copy invite URL
1. Open incognito browser and paste invitation URL
1. Set name
1. Observe that teamId is correct in URL bar, but team does not appear in left nav
1. Logout, login

Video:

![screencast](http://g.recordit.co/CsORT2V52T.gif)

- **OS:** OSX
- **Browser:** Chrome
- **Estimated effort:** 1 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
fixed in latest team-settings
