### ISSUE TITLE
Team settings sprint: invitations subscription does not remove pending invites without reload

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#511]
## Issue - Bug

If I leave a browser window open on team settings, when an invitation is accepted it does not remove the row for the pending invitation. However, it does insert the new team member.

Here is the state after the user `franky` has accepted his invitation:

![image](https://cloud.githubusercontent.com/assets/103000/20242960/49e51be6-a910-11e6-9b59-8a838b1fa5a3.png)

- **OS:** OSX
- **Browser:** Chrome
- **Estimated effort:** 1 point ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
will be fixed in team-settings sprint.
