### ISSUE TITLE
Relabeling Actions and Projects during agenda processing

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#514]
## Issue - Enhancement

2 of 2 users tests demonstrated confusion around the difference between projects and actions. After the test, I asked them to tell me what they thought a "Private Action" and a "Team Project" would do.

Folks told me a "Team Project" probably goes on the team's board. A "Private Action" they thought sounded like it would be visible only to them, but, they weren't sure in the current design where they would go to see such a thing. I imagine that could be cleared up a bit by #274.

What do you think about:

- New Action (shortcut: `A`) -> New Private Action (shortcut: `P`)
- New Project (shortcut `P`) -> New Team Project (shortcut: `T`)

- **Estimated effort:** 1 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
I think I like:

New Private Action (the “A” remains underlined and `a` is the shortcut)
New Team Project (the “P” remains underlined and `p` is the shortcut)

So basically, update the labeling but keep the atomic OOUX for the shortcuts.

**Comment by jordanh** [comment]
Safe to try! (Perhaps, even safer to try)
