### ISSUE TITLE
Team settings sprint: user gets ducks if removed while viewing team route

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#516]
## Issue - Bug

This is a low priority bug.

Given two users TL and TM. If TM is viewing `/team/team123` and the TL removes TM from the team, TM's view will rerender and display the loading ducks.

TM's view should probably be redirected to `/me` with a toast, "you've been removed from team 'team123'."

- **OS:** OSX
- **Browser:** Chrome
- **Estimated effort:** 1 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
this should happen. i designed this to happen. this doesn't happen? what are the repro steps?

**Comment by mattkrick** [comment]
just double checked & this worked for me locally. perhaps it wasn't working due to #515?

**Comment by jordanh** [comment]
I can no longer reproduce this with the latest. Closing for for now.
