### ISSUE TITLE
Team settings sprint: removed team member does not redirect away while on team dashboard

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#518]
## Issue - Bug

Similar to #516, perhaps.

If a user is logged in and viewing the team dashboard while they are removed from the team, they will see a toast message saying "So long" but:

- They will not be redirected elsewhere
- The sidebar will still show their old team membership
   - However, they will not be able to add new team projects

- **OS:** OSX
- **Browser:** Chrome
- **Estimated effort:** 1 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
will address this right now

**Comment by jordanh** [comment]
Sure thing – have only deployed to staging. Happy to redeploy before the day is done.

**Comment by mattkrick** [comment]
found it, the problem is that we're kicking them off the channel, but we're not removing it from the client cache. while we're at it, we should remove everything else from the client cache that is associated with the team. fix coming soon
