### ISSUE TITLE
Switch to react-hot-loader for HMRing everything, including stateless components

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#52]
Placeholder for when the package goes stable (likely before June 1).
Upgrading this will hopefully put an end to manually reloading the client when in dev mode.
We could upgrade now, but meh, still in beta. Might as well wait for others to find the bugs & create documentation because learning how this thing works well enough to debug issues would take awhile.
https://github.com/gaearon/react-hot-loader/pull/240

**Comment by jordanh** [comment]
I've used this puppy before. It's what we used before we switched to Meatier. Worked _wonderfully_.

I may take a stab at this today / next week.

**Comment by mattkrick** [comment]
v3 is a COMPLETE rewrite and totally different methodology. i'd wait until the issue is closed until we make the switch, otherwise we're sure to burn some hours debugging that could otherwise be avoided if we just wait for them to clean it up. Functionally, the only thing we're missing out on currently is support for functional components, which isn't a huge loss.

**Comment by jordanh** [comment]
I could start it on a branch, no? I assume their interface won't change tremendously. I'm itching to keep pushing on something 👯

**Comment by mattkrick** [comment]
Ah, well then by all means, push it to the limit!
If you're looking for another project, I'd love some feedback on how the subscriptions API should look for cashay: https://github.com/mattkrick/cashay/issues/27
We'll need to build that out before we integrate it into action.

**Comment by jordanh** [comment]
Ah. True enough. Ok. Sounds like @ackernaut and I should keep pushing forward and we can refactor things for Cashay soon...
