### ISSUE TITLE
Create a png of AvatarPlaceholder

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#520]
We currently have an avatar placeholder that is just a big fontawesome icon question mark.
I'd like to either replace this, or have the additional option of a png file.
That way, when we see something like this, we can have an onerror handler supply a default image.src:
![screen shot 2016-11-15 at 4 20 19 pm](https://cloud.githubusercontent.com/assets/5514175/20329867/a4266218-ab4f-11e6-9c45-63976a225bf5.png)

@ackernaut low priority, but something that makes stuff look polished in the off chance that the picture is no longer there or it hiccups & can't read it.

**Comment by ackernaut** [comment]
@mattkrick just pushed these—I suggest using the @2x or @3x as the default.
