### ISSUE TITLE
race condition on team subscription

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#521]
the latest PR introduced a race condition on establishing a ws connection + setting up a subscription handler.
this is fixed in the latest commit of the dnd branch & will get merged to master shortly.

**Comment by jordanh** [comment]
Should I delay pushing v0.12.1 to production?

**Comment by mattkrick** [comment]
i _think_ it may already be in v0.12? i could write a hotfix if this is a big issue.

**Comment by jordanh** [comment]
Oh, it's not a big deal. If you fixed it on `dnd` nothing from that branch has been merged back to master. Let's see how far we get today on `dnd` and then judge from there. If it looks like we'll get a first cut of drag-and-drop deployable by Friday afternoon, we can just hold off until then.
