### ISSUE TITLE
Turn ProjectColumns into an array of redux-form fields

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#522]
Currently, we treat each card as its own separate 1-field form. This doesn't work easily because we can drag a card from 1 column to the next, which triggers an init/destroy which do not have a guaranteed order. That means values don't always get initialized when they get dragged across columns (it tries to initialize something that was destroyed).

Currently, to fix this we just set destroyOnUmount to false. That works great, but it leaves us open to a memory leak. We want to destroy those outcome card forms, but only when they ALL get unmounted. To do that, we have to know when their common parent gets unmounted (ProjectColumns) and call destroy on all of them.

**Comment by jordanh** [comment]
I advocate this. Is encourage us to do this in a second pass, starting next week. It'd be wonderful to get DnD in the hands of our users quickly. However, as always I leave it in your hands.

**Comment by mattkrick** [comment]
this isn't blocking dnd. This is just to close up a possible memory leak (eg someone creates & deletes 1 million cards). I'd put form validation ahead of this in terms of priority.

**Comment by mattkrick** [comment]
fixed this by using component internal state instead of redux.
