### ISSUE TITLE
Simple hover state for dashboard avatars

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#523]
## Issue - Enhancement

Let's add a simple hover state to display the user's preferred name for the avatar images in the upper right-hand corner of the dashboard interface.

![image](https://cloud.githubusercontent.com/assets/103000/20399521/55ecf708-acbf-11e6-9b61-bdb1ce37202f.png)

This will take one step toward disambiguating the avatars when images are similar or when folks have similar initials.

- **Estimated effort:** 1 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
and a presence badge?

**Comment by ackernaut** [comment]
I was wondering if we only show avatars of people currently online—but I kinda dig the suggestion to include the presence badge here—and in that way the avatar group would look a lot like the group in the meeting views.

Would a `title` and/or `alt` attribute be enough?? Or do you want a minimal…t o o l t i p?

**Comment by mattkrick** [comment]
i'll tackle this today. will add a title & presence badges for the avatars in the dashboard headers.
