### ISSUE TITLE
Actions DnD: duplicate team selection after reordering

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#530]
## Issue - Bug

This is a goofy one. To replicate:

1) Create 5 action cards on "My Dashboard"
2) Reorder a few of the actions from the top
3) Create a new action, note the replicated team name:

![image](https://cloud.githubusercontent.com/assets/103000/20507073/771fe89e-b026-11e6-8015-b11056ef5b7a.png)

- **Estimated effort:** 1 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Ah, it also makes the Project add component do a similar thing:

![image](https://cloud.githubusercontent.com/assets/103000/20507372/52151ef0-b028-11e6-819f-0587e14772f1.png)

**Comment by jordanh** [comment]
Ah interesting, the leftnav also updated:

![image](https://cloud.githubusercontent.com/assets/103000/20507521/2446f7e0-b029-11e6-9d10-a4f5ec89917a.png)

**Comment by mattkrick** [comment]
that's all kinda of weird! i'm gonna rework actions so it does the same thing as agenda items & projects. fewer handlers, better performance, no super wonky behavior.
