### ISSUE TITLE
Warning: Stateless function components cannot be given refs...

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#534]
## Issue - Bug

Just a little warning. Doesn't seem to be causing any harm, as far as I can tell. Stack trace isn't much help.

Full message:  

```
Stateless function components cannot be given refs (See ref "child" in DashboardContainer created by DragDropContext(DashboardContainer))
```

![image](https://cloud.githubusercontent.com/assets/103000/20547293/1224291e-b0e9-11e6-8e50-da6de3b7567f.png)

- **Estimated effort:** 1 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
this will go away whenever react-dnd accepts a PR.
