### ISSUE TITLE
Sort archived projects by last updated, descending

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#537]
## Issue - Enhancement

This is a simple one. Currently, when we visit the project archive for a team, the projects appear to be unsorted.

Let's sort them by their last updated timestamp, so the most recently archived items appear at the top.

- **Estimated effort:** 1 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
+1

**Comment by mattkrick** [comment]
fixed!
