### ISSUE TITLE
Loading screen for archived items

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#538]
## Issue - Enhancement

Related to #306 – now that we've got quite a view archived projects the archive takes a while to load.

Once we resolve a pattern for #306, let's tackle this one.

- **Estimated effort:** 1 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
i'd love to push this one as far back as possible. Open RethinkDB still has a resumable changefeed that's supposedly in the pipeline & if we could hold out for that, I think it'd provide the perfect pattern for paginated subscriptions.

**Comment by jordanh** [comment]
I read about that! It's exciting. Yes, let's hold off...
