### ISSUE TITLE
close the welcome route to people who have created a team

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#546]

**Comment by mattkrick** [comment]
oh man, this is delightfully tricky.
so ideally, we could just see if they have a tms token, because if they do, that means they are on a team. BUT, we give them a `tms` on step 2. so, we could do `!tms || (tms && completed == 2)`, but then what happens if they close their browser? 
well, that'd take em to the dashboard. i think that's OK, since that's basically the same logic that `loginWithToken` uses.

**Comment by jordanh** [comment]
Checked into PR
