### ISSUE TITLE
Click updated timestamp to toggle created on date

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#551]
## Issue - Enhancement

Hey! Wouldn't it be fun to see when a project was first created by clicking on the updated on timestamp in the card's upper-right hand corner?

![image](https://cloud.githubusercontent.com/assets/103000/20774770/9651d5c8-b70c-11e6-9d65-9f6d2f433a53.png)

Also consider making it such that the word "created" appears to the left of the timestamp when toggled, then fade it out. When we toggle back to the updated timestamp, animate the word "updated" in a similar way.

- **Estimated effort:** 3 points + 10 bonus points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
**Additional idea**:

I like the idea of being able to toggle between “Created Feb 2” and “Updated an hour ago” —I’m thinking we could have a filter/control for all the columns where one could toggle all cards at once. This would reset the state for every card, which could then be manipulated one by one again.

**Comment by ndey96** [comment]
@jordanh @ackernaut I'd like to take this one on next!

I'll get to work on implementing the click to toggle between: “Created Feb 2” and “Updated an hour ago”

@ackernaut I like the idea of having a switch to toggle all timestamp strings rather than having per-column switches

**Comment by jordanh** [comment]
You got it @ndey96!

**Comment by jordanh** [comment]
@ndey96 are you going to finish this one up or shall we return it to the community?

**Comment by ackernaut** [comment]
Reviving this one as card updates are coming after editor updates for GH integration UX.

- Default to Created
- Toggles to Updated (user taps to toggle)
- Timestamp is now bottom left under content and above the avatar
- Timestamp meta doubles as realtime message (“Editing...” “Terry is editing...” “Saved!” etc.)

**Comment by ackernaut** [comment]
Basically the same as #1080 for this Epic.
