### ISSUE TITLE
Handling security bugs

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#552]
Handling bugs wrt security is tricky. We don't wanna be transparent. If we find a security related bug, we wanna keep it on the DL until we can push a fix to master. How should we do that? Separate private repo that is nothing but an issue tracker? (Yes, I did stumble upon one so it's not hypothetical :smile:)

**Comment by jordanh** [comment]
Oooh. Good issue! Maybe peg it to this [private repository](https://github.com/ParabolInc/action-devops)?

**Comment by mattkrick** [comment]
okie doke
