### ISSUE TITLE
DnD acts strangly when user filter active on team dashboard

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#553]
## Issue - Bug

When a user filter is active, DnD doesn't always work well. Performance drags, and we can't always drop.

Here's a screencap:

![screencap](http://g.recordit.co/B8K6c0qGcQ.gif)

- **OS:** OSX
- **Browser:** Chrome
- **Estimated effort:** 3 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
I think this may also be causing an exception:  https://sentry.io/parabol/action-production/issues/188910333/

**Comment by jordanh** [comment]
New version, new old bug. 🆕 👴 🐞 

Repro steps:

1. Navigate to a team dash
1. Filter by a user
1. Drag a project between columns. Note it will add itself to the first column dragged to, at the bottom of the list

Gif:

![ewclgqczlp](https://cloud.githubusercontent.com/assets/103000/23880420/f3759244-0829-11e7-96dd-9db957cc7010.gif)

**Comment by jordanh** [comment]
From Sentry, this now classic exception: https://sentry.io/parabol/action-production/issues/234039602/

**Comment by mattkrick** [comment]
yay for reproducing this bug! and locally too!
