### ISSUE TITLE
Delete team

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#555]
When a team no longer has a purpose, a user wants to delete the team so that their dashboard reflects the most current state of their teaming.

- [ ] Add a flat button to the team settings header
- [ ] Add an inline confirmation text field

**Current**: Just delete the team completely?

**Future**: Decide on a design for soft delete (or archiving teams) vs. permanent delete?

**Design**: [See slides 3 and 4 on this Google Presentation](https://docs.google.com/presentation/d/1gzreTpsjTy4NrutRe0RRlZC3YACGHcjFo9VCkzh0ulI/edit?usp=sharing)

**Estimated**: 13 points

**Comment by ackernaut** [comment]
Ooh, I’ll look at this more closely, but I am still thinking in the white dashboard header space where the team name is edited.

**Comment by ackernaut** [comment]
@mattkrick updated! but Future so not urgent.

**Comment by jordanh** [comment]
Examining other teaming tools, hard delete is rarely used in this context. Trello archives boards. Slack archives channels. Aside from removing anxiety, I think having the historical data will be nice for us and for our users.

Here's a sketch.

## It should:

- [ ] allow team leads and org owners to archive teams ([See slides 3 and 4 on this Google Presentation](https://docs.google.com/presentation/d/1gzreTpsjTy4NrutRe0RRlZC3YACGHcjFo9VCkzh0ulI/edit?usp=sharing))
- [ ] send a notification to team members when a team has been archived
- [ ] list archived teams under the org settings, allow archived team to be restored

**Comment by mattkrick** [comment]
I'd add that we should provide a hard delete for accidents. We might detect an accident by either teamMember.length === 1, or projectCount === 0, but i like the first better because you can't hard remove a teamMember from a team.

**Comment by ndey96** [comment]
I'll take this one on for 13 points :)

**Comment by jordanh** [comment]
Yo @ndey96. I've just credited your Equity for Effort standings 13 points. Your new total is **101 points** 🔥 !

This makes you the first person to qualify for an equity grant from us at Parabol. From all of us here, _thank you for all of your contributions & hard work._
