### ISSUE TITLE
New members don't show up with name in team overview

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/action#5553]
When a new member is invited and joins, their avatar shows up but without a name, see
![Missing name for new members](https://user-images.githubusercontent.com/7331043/138253001-d48addd3-6e58-4142-91b1-0cbdca8e580a.gif)
Issue is gone after refresh.

### Acceptance criteria:
* newly added members show up with name

**Estimated effort:** 3 hours

**Comment by RiyaNegi** [comment]
Hey, this is still an issue. Mind if I pick this up? 😄
