### ISSUE TITLE
Select org dropdown menu during add team

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#561]
When a user clicks the Add Team button, we'll need them to select an org. This requires a dropdown menu. @ackernaut i know this sprint is really heavy on ya, so if you can design something rough in sketch, I can build the component. We've already got the menu build, so we just need to build the part that shows the name & the dropdown arrow. prioritizing this will make it much easier to test the org buildout with real data.

also, this is a little tricky because we'll have a "create new org" selection. not sure how ya wanna handle that (modal popup, turn it into an input field, etc).

**Comment by ackernaut** [comment]
In one of the first concepts, we had an additional field or set of fields in the Add Team form. I think we could try that? Then the left nav action is just a route. What do you think?

This is just the old mockup for reference. I think we can do better.

![create-new-team-more-fields 2x](https://cloud.githubusercontent.com/assets/307286/20951943/8d16ffd8-bbee-11e6-8f8e-15737715fc94.png)

**Comment by mattkrick** [comment]
yeah, this is a good place to start. I think we can nuke the "who can see..." part for now to reduce scope. I imagine when I click the dropdown arrow i see:
- Marimar's Org
- Create new org...
So, the only part to figure out is what happens when I click "Create new org..."

> Then the left nav action is just a route.

Not sure what this means. Is that referring to the old 'New Team...'?

**Comment by ackernaut** [comment]
Ah the “Add New Team” is still just a route to the form.

Yeah I think maybe clicking “Create new org” would drop a field inline below the select or something. We can experiment with the actual controls, and agreed—no need to design privacy settings right now.

**Comment by ackernaut** [comment]
Closed, shipping in #584
