### ISSUE TITLE
Split the only one existing Redis instance on two different. One for Caching and the other for Pub/Sub

### ISSUE THREAD

**Issue by mariogruizdiaz** [ParabolInc/action#5616]
## Enhancement

Having at least two different Redis instances for different purposes, we will be one step forward on isolating bottleneck issues one of each other

### Acceptance Criteria 

- [ ] Update the docker-compose.yml file to deploy one more instance of redis
- [ ] Update the env files to let the cache to connect the new Redis instance
- [ ] Test the site to ensure that continue working as usual

**Estimated effort:** 12 points

**Comment by mattkrick** [comment]
Closing for now as we're not going to be able to tackle this within the next 6 months
