### ISSUE TITLE
[v0.13.5] our avatar section has sprouted a "mini-me"

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#565]
## Issue - Bug

I am seeing this on staging after I tested the deploy of v0.13.5:

![image](https://cloud.githubusercontent.com/assets/103000/21036599/0a9add1a-bd95-11e6-98d1-2f862faa2fa2.png)

![image](https://cloud.githubusercontent.com/assets/103000/21036605/155690e6-bd95-11e6-8b5c-7f0cc385982e.png)

- **OS:** OSX
- **Browser:** Chrome

**Comment by mattkrick** [comment]
that's hilariously horrible!
