### ISSUE TITLE
Default avatars for teams/orgs

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#566]
@ackernaut @tayamueller auth0 gives us "good enough" avatars for users, but for teams/orgs we'll need something. Any ideas on free pics, or just themes in general?  For orgs, we could even steal the avatar from the team, so really we just need something for the team & that'll be good enough to get us started.

**Comment by ackernaut** [comment]
So a couple of things:

I’m thinking the win for teams having an avatar is: 1) Ownership 2) Teams over individuals and 3) Play. It can be something that a team can have fun with and have a sense of identity & purpose. I could see an org having a self-imposed theme for teams: Team Tiger, Team Peacock, Team Walrus

With organizations it seems a little easier as there is most likely a brand/logo that can be used.

As for a default we could use something like this:

[Identicon generator](http://identicon.net/)

Where the text used is Org Name + Team Name. It is ugly enough that folks may want to change it. I was thinking we could even throw the first and last letters of the team name over it for fun: Engineering would be “Eg” over the generated identicon for “Parabol Engineering”

**Comment by mattkrick** [comment]
My concern with the identicon is that the icon is tied directly to the name, so if a name changes, the icon (should) change, which might get confusing.

**Comment by ackernaut** [comment]
@mattkrick could be! but maybe it would be a passive nudge toward actually adding an avatar?

**Comment by jordanh** [comment]
Let's do this as a static image stuck up on S3. Pulling into epic 2.
