### ISSUE TITLE
Meeting Milestone Markers

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#567]
## Issue - Enhancement

Let's send pleasant moments to folks that reach milestone meetings--a note/invitation sent to each active team member to yield multiple perspectives:

Mtg 10) [cascading explosion!] Wow--you've completed your first 10 Action meetings! Hope your team is loving it--and we're still building, so if there's anything we can do to make your experience even better, feel free to drop us a note: love@parabol.co

Mtg 20) [happy puppies!] WOW--you've just completed your 20th Action meeting! You're practically an expert now, so we'd love to take a moment to listen to your feedback. Please consider taking our short survey: [link to brief, irreverent survey]

Mtg 50) [exploding hearts!] Holy moly! 50 meetings complete! Hope we've helped you accomplish some amazing things with your team. Can we invite you to coffee and learn more about your experience with us? We'd love to schedule a 30-minute coffee chat with one of our founding members, either over coffee in NYC, or over video in your town. Sign up here: [link]  ***note: if not in NYC, find out what town they're in during the call & send them a $10 gift card to a local coffee shop as follow-up afterward

Mtg 100) send 'em a physical treat...this is, like, 2yrs in! t-shirt? keychain? microfiber cleaning cloth?

**Comment by ackernaut** [comment]
Oh wow @tayamueller I’m really digging this idea!!

**Comment by tayamueller** [comment]
When a user has been with us for a significant amount of time (annual, etc.) it would be nice to send them a subtle reminder of how long they've depended on us, along with a small perk, a la the MOO-versary campaign:

![mooversary](https://user-images.githubusercontent.com/14892189/35739191-d0c59d0e-07fe-11e8-954c-951a6922b892.jpeg)
