### ISSUE TITLE
Reorder default lane order, once again

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#571]
## Issue - Enhancement

Folks who have Agile experience tend to be rubbed the wrong way by our lane order. When asked what they suppose the order should be, they are consistent (which is good!). From left-to-right:

1. FUTURE
2. ACTIVE
3. STUCK
4. DONE

Keeping a tally of folks who've spotted this:

- Rob F.
- Derrick B.
- Aaron D.
- Derek L.

- **Estimated effort:** 2 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
Yeah there is a lot of sense in that workflow, too.

Do we change it for everybody or allow users to reorder, rename?

**Comment by ackernaut** [comment]
I also envision a multi-select in the filters that allows one to toggle which lanes are visible.
