### ISSUE TITLE
Amazon S3 returning 403 for VPN clients

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#573]
possible sources of fixes: 
- http://stackoverflow.com/questions/26691286/amazon-s3-bucket-returning-403-forbidden
- http://docs.aws.amazon.com/AmazonS3/latest/dev/WebsiteAccessPermissionsReqd.html
- https://www.google.com/search?q=amazon+s3+vpn&oq=amazon+s3+vpn&aqs=chrome..69i57j0j69i64.2338j0j7&sourceid=chrome&ie=UTF-8#q=amazon+s3+403+error+vpn+site:forums.aws.amazon.com

**Comment by jordanh** [comment]
I updated the bucket policy with:

```
{
	"Version": "2012-10-17",
	"Id": "Policy1481757499952",
	"Statement": [
		{
			"Sid": "Stmt1481757495986",
			"Effect": "Allow",
			"Principal": "*",
			"Action": "s3:GetObject",
			"Resource": "arn:aws:s3:::action-files.parabol.co/*"
		}
	]
}
```

Would you mind retesting? I hope this fixed it...

**Comment by mattkrick** [comment]
well that does it!

**Comment by jordanh** [comment]
Thank goodness!
