### ISSUE TITLE
Add to team -> Process for adding to org

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#574]
Scenario 1:
- Matt is the billing leader. 
- Terry and Jordan are regular Team members on team "Parabol Product".
- Terry clicks "add team" He invites `jordan@prbl.co, steve@foo.co`
- Matt receives a notification that he must approve `steve@foo.co` to the `Parabol, Inc` org.
- If Matt clicks "deny", a modal pops up asking for a reason & that reason is sent to Terry via notifications telling him that steve was not invited
- If Matt clicks "accept", an invitation is sent to `steve@foo.co` and a notification is sent to Terry saying that steve was approved & an email invite was sent. 

Questions (Click the check for Yes):
- [ ] Does Terry receive a toast telling him that `jordan@prbl.co` got added immediately? Y/N
- [x] Does Terry receive a toast telling him that `steve@foo.co` needs approval from Matt? Y/N
- [ ] Does Terry receive a notification telling him that `steve@foo.co` is pending an approval from Matt? Y/N
- [ ] Does Matt receive a notification saying a new team was created? Y/N

Scenario 2:
- Matt is the billing leader. 
- Terry and Jordan are regular Team members on team "Parabol Product".
- Matt clicks "add team" He invites `jordan@prbl.co, steve@foo.co`

Questions:
- [ ] Does a modal pop up telling Matt that steve isn't part of the team & adding him will increase cost? Y/N
- [ ] Is there special treatment if Matt is within the trial period? Y/N

**Comment by ackernaut** [comment]
@mattkrick good questions/job stories, Matt:

For S1 I think that Terry receives a toast for new users and Matt receives a notification to approve. I think that on the team member list (under Team Settings) the user row item for Steve can say “Pending approval by Matt <matt@prbl.co>”?

I think there is currently no need to notify on new team creation.

For S2 I would be interested in reducing friction, so Matt’s invites are automatic as billing lead during the trial. During regular usage, I’m thinking we can have a modal that says “Steve is new to the org, increasing the monthly invoice by $5 [Okay button] [Cancel invite]” (we prorate but no need to explain here, as $5 monthly is accurate)

**Comment by mattkrick** [comment]
this aligns with what i was thinking except now I'm against the post-trial modal-- if you're the billing leader, you know you're paying $5/month/user, so why should we tell them every time? I can't imagine anyone ever clicking No, so it just becomes an extra click that doesn't add any value. No super strong opinion either way, but seems like we've got a way forward for everything else!

**Comment by ackernaut** [comment]
@mattkrick I am persuaded. Let’s scrap that confirmation modal idea for now?

**Comment by mattkrick** [comment]
alrighty, will scrap that & i'll work on building out the backend logic for all this tricky stuff.

**Comment by jordanh** [comment]
Conversation resolved.
