### ISSUE TITLE
Chore: Simplify GraphQL InputObjects and Add index to descriptions

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#575]
Currently, we use thunks to differentiate between input objects that are similar, but have different required fields. 
Now that we have external validation, we can get rid of that.
Also, we should go through the database, get all the indices, and mark which fields have indices in the GraphQL schema so we don't have to go to the DB to figure it out.

**Comment by dan-f** [comment]
Document the GraphQL endpoint so that we know which query fields are indexed in the underlying DB.

**Comment by jordanh** [comment]
- Database indexes are marked as an asterisk in the GraphQL Scheme

Estimated effort: 11 points

**Comment by jordanh** [comment]
Iceboxing this chore for now
