### ISSUE TITLE
Pop a toast when a participant tries to move ahead of the meeting facilitator

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#576]
## Issue - Enhancement

When a meeting participant tries to navigate ahead of the facilitator, presently the click falls into a void. For example, when a participant tries to click on an agenda item while the facilitator is still in Project Updates. It can sometimes feel like our app is broken.

I suggest we pop a toast when this happens to that participant that reads:

> **Hold your horses! 🐴** 
> You'll have to wait for the facilitator
> before you can go there.

- **Estimated effort:** 2 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
This issue is available under our [Equity for Effort program](https://focus.parabol.co/equity-for-effort-v2-0-7ca93e0a3968). Comment below if you'd like to take it on!

**Comment by jordanh** [comment]
This popped up in #578.

Here's what I think happened:

1. The facilitator started the meeting but never ended it
2. A second user logged in to try and use Action (probably to use the team dashboard) and they see that a meeting is active
3. They join the meeting with the intention of ending it but they can't (without knowing the secret incantation)
4. Most importantly, the user didn't even realize they were not the facilitator - it just look like our software was stuck

Super frustrating!

In addition to this bug, what to do? Brainstorming options (in addition to the above):

1. If a meeting has been active for >24 hours, end it automatically (requiring a server task)
2. Add a button to the team dashboard modal offering to end a meeting if it has been active for > 24 hours
3. Add a button to the meeting sidebar for the same

I'll open a separate issue to track.

**Comment by mattkrick** [comment]
1. Why 24? We write opinionated software, let's add some opinions! If it's over an hour, we should pop a notification. If it's over 90 minutes, we should go Online Banking on their ass & pop a notification saying "this meeting has been running for 90 effing minutes! Click Extend to extend it for another 30", which extends the field `timeMeetingShouldEnd`. If they don't click Extend in 5 mins, it ends. We don't need to cronjob this, when `startMeeting` is called, we put a self destruction timeout at the end that ends the meeting _if_ `new Date() < timeMeetingShouldEnd`.

Alternatively, we make them the facilitator.
- Jordan starts a meeting by himself, then ditches it
- I see a meeting, I join
- After all teamMembers have been loaded (requires a little extra work to do this right, we could just use a simple setTimeout for now), I see if the facilitator is online. if he isn't then i request to become a facilitator. The server then promotes me to facilitator.

Another option
- if i'm the only one present & the meeting is beyond the lobby phase, then I get a note asking if i want to be facilitator.

**Comment by jordanh** [comment]
Closing in favor of solution from #592
