### ISSUE TITLE
Meeting Stuck at First Call

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#578]
## Issue - Bug

Clay Parker Jones at August showed me today that they have a team that is in a stuck meeting state. They are unable to advance beyond the First Call phase.

Steps (for him):

1. Log in
2. Click into meeting in progress (resumes at First Call)
3. Unable to advance

They can add agenda items, but he is unable to navigate.

No exceptions are triggered.d

- **OS:** OSX
- **Browser:** Chrome & Safari
- **Estimated effort:** 1 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
Oh, so whack! Did you show them the super secret key sequence?

**Comment by jordanh** [comment]
I didn't want to whack it yet. I wanted to preserve the state so we could see what might be wrong first... ;)

**Comment by ackernaut** [comment]
Yeah, I thought you might be thinking that!!

**Comment by mattkrick** [comment]
investigating now...

**Comment by mattkrick** [comment]
Unable to reproduce. Here are the steps I took:
1. Login to matt@prbl.co
2. Start a meeting
3. navigate to first call
4. exit to team dashboard
5. refresh
6. click modal to go to meeting
7. continue with meeting

**Comment by mattkrick** [comment]
state:
```
"facilitatorPhase":  "firstcall" ,
"facilitatorPhaseItem": 1 ,
"id":  "r1PMTqCkx" ,
"meetingId":  "Sym5_1j0yg" ,
"meetingPhase":  "firstcall" ,
"meetingPhaseItem": 1 ,
```

**Comment by jordanh** [comment]
@mattkrick I deployed the new user impersonation feature up to staging. Check it out!

   1. Login as yourself with admin privileges.  
   2. Then, navigate to `https://action-staging.parabol.co/admin/impersonate/google-oauth2%7C116815927261241926932`
   3. Resume the meeting

Fun!

**Comment by mattkrick** [comment]
_Very_ cool! Guess we should probably remove `rol: 'su'` from every fake account now, huh?

**Comment by jordanh** [comment]
Good good thoughts Matt: it should already be done on production!

**Comment by mattkrick** [comment]
@jordanh have you been able to reproduce?

**Comment by jordanh** [comment]
Yes, but only switching to Clay's account. Try it on staging. It's neat. If you want to look together, ping me!

**Comment by jordanh** [comment]
Ah ha! It was as I suspected. Clay is not the facilitator. His colleague Alix is. That means he can't go forward, and he can't end the meeting. Super frustrating!

This makes #576 more important. Let's continue the conversation there.
