### ISSUE TITLE
Agenda input: give me at least some of my chars, yo!

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#579]
## UI/UX Bug

When I type too many characters into the agenda field and hit enter, I lose everything:

[vid link](http://recordit.co/ajtXQDAZY0)
[GIF](http://g.recordit.co/ajtXQDAZY0.gif)

I also noticed that the field has a max. I suggest a simple solution, that we capture the characters before the max and return those as content for a newly created item. This would prevent us from having to add visual feedback (tooltip, etc.).

```
message: '{"content":"Try something a little shorter"}',
locations: [ [Object] ],
path: [ 'createAgendaItem' ] } ]
```

- **Estimated effort:** 1 point ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
that's a good catch! i changed the max to 63 on the client but left it at 50 on the server, so it was getting rejected. Now, everything should have a max of 63

**Comment by ackernaut** [comment]
So good! Thanks @mattkrick
