### ISSUE TITLE
Upload new organization avatar modal

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#582]
When I click on the "EDIT" overlay on top of my org avatar, I expect a modal to pop up that lets me either type in a URL or look for a file on my computer to upload.

on the backend:
- if it comes from the computer, let's upload it to S3
- if it comes from a url, let's resolve the url & copy it to S3

**Comment by jordanh** [comment]
I'm happy to contribute the S3 pattern here. How would we like to store the images? With #493 I suggested we store user assets under a path like:

   * `/production/store/`

What do we think about:

   * `/production/store/:model/:id/asset.ext`

Also, I think we should generate a short id for `asset.ext`.

So, perhaps, org avatars are stored under a path like:

   * `/production/store/Organization/abc123/xyz456.ext`

What do we think?

**Comment by mattkrick** [comment]
i think that works! the only consideration is that by putting the assets in folders, we make it easier for attackers who want to target a specific org. For example, if i know your teamId and I want to grab your team avatar, then I know i can head to `/Team/team123/` and then issue 64^7 requests for headers and see which ones give back 200 codes. 
here's how facebook does it:
`/pictureSize/pictureHash?oh=requestKey`. I'm guessing that `requestKey = pictureHash * serverSecret`. Not saying we need something this secure, but it's an option.

**Comment by jordanh** [comment]
It would be very, very easy for us to XOR all of the file ids with a server secret. I like that idea a lot.

**Comment by jordanh** [comment]
Scratch that, I see...it's actually a key that authorizes the request. I'm not sure how easy that would be for us to implement on S3. I'll look into this a bit more deeply...
