### ISSUE TITLE
Invitations sprint

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#59]
## Issue - Enhancement

Let's allow team leaders to be able to invite their fellow team members!

- **Estimated effort:** 5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))
- **(Optional) link to mission spec:** ([[Action] Invitations Sprint](https://docs.google.com/document/d/1TbToMmIYXs7Iad4IhMX-ZVu5EgXi0XB52HpuA7Mpb_0/edit#))

**Comment by ackernaut** [comment]
Considering breaking this down into a few bite-size pieces (branches):

- [ ] Invite email

- [ ] Email parsing

- [ ] Invite by email front-end view

- [ ] UI mock-up for profile (scope?)

- [ ] UI mock-up for team meeting landing page (scope?)

**Comment by jordanh** [comment]
@ackernaut I like the bite-sized pieces. Here's what we wrote on the board:

![slack for ios upload-1](https://cloud.githubusercontent.com/assets/103000/15932420/a0e11f4c-2e29-11e6-83af-9d06f3ecd676.jpg)

In addition to above, suggest we tackle next:

- [ ] New route `/welcome/invitee?invitation=X` for `Welcome` module to create new user and join to team by invitation token. Then:
- [ ] ...new `Me` module created with route `/me/:id/profile` (and param to catch invitation state), then:
- [ ] Redirect to new `Team` module and dashboard (can literally say, "coming soon!")

**Comment by jordanh** [comment]
Will be closed by #82

**Comment by jordanh** [comment]
Merged to master in #82. ✨
