### ISSUE TITLE
User assistance privacy toggle (codename: creepy pockets)

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#591]
we may need to remotely assist folks.
but we don't wanna do that unless they give us permission.
So, @ackernaut we need a toggle in the user dash that says "allow remote assistance" (default false)
Then, when we help them (either in realtime or at another moment), our mutation creates a notification that says "hey, we remotely assisted you" and it unchecks "allow remote assistance".

**Comment by ackernaut** [comment]
So we would back up and add a moment to this story right?

A user needs help. They reach out to us. We ask them to turn on their “allow remote assistance” switch. We help, then are able to end the session somehow, that triggers a notification (I like the idea of an [maybe optional] brief summary of what you did). Then it automatically toggles that switch to off?

We can reformat the first comment into a bulleted user story.

**Comment by ackernaut** [comment]
I am thinking that a system like Intercom might be nice for this so we have less to build. A user can reach out to us through Intercom. We can assign to one of us. We can message them about toggling on their remote assistance. Before we end the session we can toggle it off for them. Then we can tell them what we did through Intercom?

**Comment by ackernaut** [comment]
So what could we do technically that prevents us from assuming users using auth0?

**Comment by mattkrick** [comment]
i'm not sure we need to tell them what we did, since they already know what we're gonna do & that's why they gave us access. I do imagine that we can expand the token to have an `imp: true` field. Then, when you hit the `/signout` route it checks for the `imp` field. if it's there, then it sets `remoteAssistance: false`. I do really like the intercom-type chat window, and that is really nice & is also a good catchall (bugs, feature requests, etc).

**Comment by mattkrick** [comment]
> So what could we do technically that prevents us from assuming users using auth0?

right now, all users use auth0, so that's a no-op. all the logic is done on our own server though, so we could ditch auth0 & there'd be no changes needed.

**Comment by ackernaut** [comment]
So we are responsible for adding that layer of turning super-admin power on/off?

**Comment by mattkrick** [comment]
yup, we just leave that as a manual thing

**Comment by jordanh** [comment]
Let's prioritize this for "The Future." I think we earn the right to implement this feature upon product-market fit.
