### ISSUE TITLE
Trial is up; No billing added!

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#593]
## User Stories

So Andrea (persona) didn’t add billing information before the initial 30-day trial ended.

What happens now?

In the context of one of the teams associated with Andrea’s trial:

If a user navigates to a team dash URL or team meeting URL, the user is redirected to the initial team dash view that is disabled by a modal that says: “Trial ended; Ping Andrea” (if user is Andrea, modal says: “Trial ended; Add billing”

Since Andrea did not get the 30-day extension, does his billing cycle start there, with the first invoice being charged 30 days later?

`Best scenario: 30 days, billing added before trial is up, 30 days added to trial and completed, billing cycle starts, 30 days after first cycle, card is first charged`

`Andrea’s scenario: 30 days, billing is NOT added before trial is up, billing is added later, billing cycle starts, 30 days after first cycle, card is first charged`

User Dash:

I am a user on one of Andrea’s team, and a team on another org, what happens to my dashboard?
- Are my projects and actions associated with Andrea’s team disabled (cannot change)?
- I can still interact with other actions and projects on other teams?
- Can I still sort (DnD) any outcome?
- Do I get a conditional toggle to hide teams where the trial has ended without billing? (kind of like a super filter by the filter where I can see outcomes by team).

Lots of questions here.

**Estimated effort:** 3 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
If Andrea never adds billing, can I leave that team (or hide it) from my own settings?

**Comment by jordanh** [comment]
These are good questions. I am going to come back to them after some thought.

**Comment by mattkrick** [comment]
I'll take a crack at it:
1-2 times/day we have a cron job that goes hunting for trials that are about to expire. When it finds them, it
 - sends a notification to the billingLeaders
 - sets `isTrial` to false on the Org
 - sets `isActive` to false on each team under the Org

- Subscriptions to teams, teammembers, projects, actions, presence, etc. are filtered by {isActive: true} for the team. That means no data team data comes down the wire
- On the sidebar, we gray out the team names that are `isActive: false` and put a red exclamation mark next to it
- On the team dash/meeting for an inactive team, we show a dialog saying that their org hasn't paid & to contact 1 of the billing leaders (we'll give them their emails). The header is a cute picture of a hunter  with a shotgun in 1 hand and the 3 loading ducks in the other, dangling by their feet with Xs in their eyes. Something so sad that the person thinks, "Oh wtf those poor ducks! I'LL pay the fee!".
- You can't hide teams that are in default. We want them to be an eyesore. You can leave them, though.

**Comment by jordanh** [comment]
@mattkrick, that's a very elegant interaction and fits well with what's already implemented. Awesome!

One additional answer:

> Since Andrea did not get the 30-day extension, does his billing cycle start there, with the first invoice being charged 30 days later?

Yes, if he missed the opportunity for 30 _additional_ days free, he missed it. The billing cycle begins when the billing information is added.

@mattkrick is correct, we'll need to carefully design the dialogs to coax persuasion of the billing leader.
