### ISSUE TITLE
Custom Avatars

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#601]
### Issue - Enhancement

Assuming our users will be looking at their own avatars every day (and at each other's at least during weekly stand-ups) it would be groovy if they could be customized on-the-fly:
-face/eyebrow/eye/ear/mouth hair shape & color (including non-human options, for fun/drama)
-menu of accessories to reflect "today's mood" or daily activity
-menu of background options (can we geolocate user's background weather as default?)
-menu of rollover effects/sounds? (yawn, clap, ahem, jump, grin, etc.)

(A gently bobbing wizard's hat above, or ring of twinkling stars around, the 'Tator instead of a static pink ring?)

(Extra groovy if we can make it easy for folks to export/share their 'tar on social. Can't think of another app that makes this easy & free; certainly not a work-related one. Dumb. Work = 1/2 of waking life.)

**Comment by dan-f** [comment]
Related: https://github.com/ParabolInc/action/issues/1532
