### ISSUE TITLE
Allow Project cards to be assigned to a different team

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#604]
## Issue - Enhancement

Capturing this from one of our internal Action meetings.

- **Estimated effort:** 5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
big question-- do we leave a trace of the old project? This isn't too crazy, we just create a new project & copy over all the props. But then what would you like to do with that old project? straight up delete it? flag it as `transferred`?

**Comment by ackernaut** [comment]
My thoughts:

- Copy **project A** as **project B**. Archive **project A**. **Project A** history ends there.
- New **project B** now exists on the other team and has brand new history.

**Comment by tayamueller** [comment]
I can see this being super useful when a Team has grown (or a company has evolved) to the point where a second team is desired. Our own use case: starting an Ops team from ExCo and a Design team from Product

**Comment by dan-f** [comment]
Related/dup: https://github.com/ParabolInc/action/issues/1032

**Comment by jordanh** [comment]
Closing b/c dupe.
