### ISSUE TITLE
Rapid reprioritization card controls

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#605]
## Issue - Enhancement

Add controls to rapidly move a card to the top of the list, to the bottom of the list.

Perhaps the controls appear on hover?

- **Estimated effort:** 5 points + 10 bonus points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
It would be cool if there was a way to focus on the whole card. I could push ⬆️  ⬇️  to move 1 spot, or `tab || shift || command + [arrow up/down]` to make it jump to top/bottom.

An alternative idea—we still need a way to focus on the whole card, but could then double click at the top or bottom of the project column and it would appear there.

**Comment by jordanh** [comment]
Iceboxing
