### ISSUE TITLE
Revise lobby help text; bring your own conferencing

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#606]
## Issue - Enhancement

Via user feedback: some folks are confused that Action is actually conferencing software. For remote teams, we should provide them with an explicit message in the meeting lobby that you must bring your own conferencing.

Perhaps this is a one-time toast that must be acknowledged/

- **Estimated effort:** 2 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
Might be cool if they give us their meeting URL and then we open that page
for them when they enter the lobby... Then they only have to worry about 1
URL. OURS.

**Comment by jordanh** [comment]
That is some slick UX @mattkrick, I like that idea a lot.

**Comment by ackernaut** [comment]
Hmm—hit the lobby and we open any link in a new tab that they have added to a “Meeting Start-up List” (it could be a video conference link, a link to metrics, multiple?) Might be overwhelming to have a bunch of tabs open automatically, especially if unexpected.

Perhaps there is an optional panel in the lobby where the lead can add the links necessary to follow along: video conference, metrics, etc. Then the team member can open if they want. They may be at the table, so don't need the video conference, but do want to see the metrics, etc.

Then in subsequent views, the Meeting Docs link list could be top left under the team name, or at least a toggle to pop open the list of links?

**Comment by dan-f** [comment]
Could link folks to an appear.in meeting, for example

**Comment by jordanh** [comment]
Iceboxing
