### ISSUE TITLE
Refactor components to Cashay

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#61]
## Issue - Enhancement

Refactor components to use @mattkrick's brand spanking new [Cashay](https://github.com/mattkrick/cashay).

- **Estimated effort:** 2 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
I'm thinking like 5-7 points (days?) here. This involves:
- Switching over what we have with query/mutations (2 pts)
- Build out an HTTPTransport (1 pt, almost done)
- Build out `cashay.subscribe` (4 pts)

**Comment by jordanh** [comment]
Brilliant.

Let's limit the scope of this mission to only switch over what we have to Cashay query/mutations. Then, when we're together the three of us can sprint to tackle the next bit of user invitations.

After everybody flies home, @ackernaut & I can continue on invitations and you can build out `HTTPTransport` and `cashay.subscribe`.

When you get that done, we'll be onto user presence and such. It'll be _perfect._

**Comment by jordanh** [comment]
One of the questions to consider: https://github.com/mattkrick/cashay/issues/53

**Comment by jordanh** [comment]
Going straight to #63
