### ISSUE TITLE
Date assignment and styling (aka The Passing of Time)

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#612]
## Issue - Enhancement

As a preliminary step to "floating boats", and as a step closer to "omniscient social automation":

1. (This should be an optional feature, not required)
2. ICON - create a simple calendar icon on the upper left - allow user to click & drag-select a Due Date.
3. COLORING - 4 densities of color: DARK=1wk out, MED=2wks out, LIGHT=3wks out, FAINT=4wks+; the color of the card is determined by what date the user selects
4. PROGRESS - Color progression from Faint > Light > Med > Dark is fully automated (and can be reset by the user at any time
5. LOCATION - column placement of the card is automated for first placement: Faint & Light = Future column; Med & Dark = Active column (automatically reset if user changes Due Date)

**Comment by jordanh** [comment]
Deferring these deeper design enhancements (coloring, progress, location) behind adding the calendar control and integrating cards created in the last meeting in their date order

**Comment by jordanh** [comment]
Iceboxing

**Comment by jordanh** [comment]
Forgot to close when iceboxing. Doing this now, put also creating a pre-req email.
