### ISSUE TITLE
Card predecessors & auto-stuck

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#614]
## Issue - Enhancement

Each card gets an incrementing integer (per team, like Github). If you mention another card like #XYZ, it becomes dependent on that card being completed first.

This would allow us to put cards into the stuck status automatically and send notifications to folks who are blocking.

**Comment by dan-f** [comment]
Related to https://github.com/ParabolInc/action/issues/1469

**Comment by jordanh** [comment]
Iceboxing
