### ISSUE TITLE
New avatar gifs every meeting

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#617]
When i click my avatar I am presented with a new gif capture moment to take a snapchat-length video. That gets compressed & uploaded to S3 as a new avatar image. That way, I can make a frowny face or something & everyone can see that as my face.

**Comment by jordanh** [comment]
**Estimated effort:** 10 points + 10 bonus points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

We'll be looking for a set of jobs-to-be-done and perhaps some pen and ink designs on the bid for this one...

**Comment by dan-f** [comment]
#delightful
