### ISSUE TITLE
Slack Integration - Assigning Tasks

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#618]
## Issue - Enhancement

Many of our users are also using Slack, and XX% have connected the Slack integration feature. Let's make that feature more robust, and help them work in the way they prefer.

### Acceptance Criteria (optional)
When a Team has activated the Slack integration...when a user assigns a card or @mentions a teammate outside of the context of a live Team Meeting...in addition to a Parabol notification, the assignee receives a Slack notification in the same Slack Channel linked to their Parabol Team

(This way, the assignee can ask the assigning eammate any questions they may have, in the their preferred #channel)
- Notifications settings dialog for user prototype designed
- Slack messages designed
- Frontend and backend issues created in order to implement

- **Estimated effort:** 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
This is most definitely still a thing. Issue is well-written. Let's reopen when it's requested again. Iceboxing per policy.

Be great to get Slack to pay for this feature.
