### ISSUE TITLE
First time meeting summary message - revision

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#619]
## Issue - Enhancement

CURRENT TEXT:
Way to go on your first Action Meeting!
You are unlocking new superpowers.
Make it a habit:
If you haven’t already, schedule a 30 minute meeting,
preferably recurring on Mondays or Tuesdays.
Include the following link to the meeting lobby
in your recurring calendar event:

---
REVISED TEXT:

[For a non-Team Leader:]
You’ve completed your first Action Meeting!
Look for an invitation to keep the momentum going next week.

[For a Team Leader - this prompt should appear EACH time until they complete this function]
You’ve completed your first Action Meeting!
Action works best as a weekly habit.
Click Here to help your team keep up the momentum.

“click here” should launch a GCal appointment with the following settings:
Title = “[Team Name] Check-In”
Repeat: Weekly every 1 Weeks, on [day of week], starts on [next week], Ends Never
Pre-populate all team email addresses
Prompt to enter personalized Location & Description

**Comment by mattkrick** [comment]
breaking this into 2 separate messages (leaders/non-leaders) is non trivial since we currently send out the same email to everyone. if there were a time to do @jordanh's idea of putting the recipient's projects at the top of the list, this would be it. lemme hear some thoughts & i'll dig into this guy.

**Comment by jordanh** [comment]
I think we should be ruthless about keeping this epic quick. Let's be incremental and reduce a bit of friction. Here's my suggestion.

It:

- [ ] uses the below copy, **First-Time Meeting Summary Message**
- [ ] renders two icons – one for GCal and one for Outlook – that,
   - [ ] when clicked create a recurring weekly 30-minute meeting at 10:00a local time on Mondays
   - [ ] is titled "Weekly Team Action Meeting"
   - [ ] contains a link to their team's meeting lobby
   - [ ] contains the below copy, **Meeting Description**

- - - 

## First-Time Meeting Summary Message

Way to go on your first Action Meeting! You are unlocking new superpowers.
High-performing teams have regular habits! Create a 30-minute meeting at the start of each week.
Click here to schedule: (GCal icon) (Outlook icon)
Or, make your own and include this link as the location: (http://link)

## Meeting Description

Our weekly meeting to update each other on our progress, build and process an agenda to unblock one another and track new projects.

Add your conference or dial-in bridge information here.
