### ISSUE TITLE
Team Templates

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#620]
## Issue - Enhancement

Some users will likely use Action for short, recurring projects. Example: HR onboarding

 * Team Lead (in this case HR head) creates a Team dashboard pre-filled with known tasks & projects required for successful new employee onboarding.
 * Option to select "Create Template" and name it
 * New employee cohort is added to the "Team" and they can see as each employee progresses through the process, conduct weekly check-ins to build culture & ask each other questions/help each other on Stuck items, etc.
 * When the cohort "graduates", Team Lead can delete the team members (or delete the whole team, as they wish) and then reset by "Select Template" and start anew w/ next cohort

(ALTERNATE: this could also be quick-fixed sooner via integration: if users can import Trello boards, they can create & store a template there and import it anew to Action.)

**Comment by jordanh** [comment]
I think "copy team" would be a good way of getting at some of these needs.
