### ISSUE TITLE
Personal Archive

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#621]
## Issue - Enhancement

**Pro user request:**

When** a user is asked to report on "what did you do this week/month/quarter?" it would be useful to see all of their personal accomplishments in one place as an Archive view in My Dashboard. It makes both the ask and the fulfillment lighter.

ACCEPTANCE CRITERIA:
-When a user clicks on "My Archive" inside of "My Dashboard" they can view all previous activity across all of their Teams.

**"When you’re selling to management you’re selling reporting." -a smart guy we know**

**Estimated Effort**
XX points (see CONTRIBUTING.md)

**Comment by ackernaut** [comment]
See [comment](https://github.com/ParabolInc/action/issues/1689#issuecomment-360840000)

**Comment by jordanh** [comment]
This is going to need estimated effort. I suspect that we should gate behind having a unified "Task Board"...

**Comment by jordanh** [comment]
**Expected effort:** 15 points

**Comment by tayamueller** [comment]
stuck behind #1852

**Comment by jordanh** [comment]
Addressed by #1852; so let's consider this a duplicate.
