### ISSUE TITLE
Column ordering, dash/sortable, meeting/structured

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#623]
## Enhancement

When a user is on their dashboard, they need flexibility in changing column order (and possibly visibility). When a user is in a meeting, we (in an opinionated fashion that we want to measure) think that users should have a fixed column order from Done to Future (during the Updates phase) so that they can share data that informs the Agenda phase.

**Estimated effort:** 2 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Iceboxing
