### ISSUE TITLE
Give me a control to expunge my action items

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#628]
## Issue - Enhancement

Feedback from Mari: I want to leave my done action items on my list so I have a feeling of accomplishment at the end of the day.

Perhaps give controls to archive items on my choosing?

- **Estimated effort:** 5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
We don’t have a list of action items anymore. :)
