### ISSUE TITLE
Add “What is Action” video to Action landing page

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#629]
## Enhancement

When a potentially new user arrives to the Action landing page (web app, logged out), they should see the “What is Action” video in order to know what service the app provides.

- [ ] Re-design the header space to include the video
- [ ] Provide a clear and easy path to signing up for new users
- [ ] Provide a clear and easy path to signing in for existing users
- [ ] Replace the pink, flat background with a photo with a team meeting context

**Possible metrics**:

- Quantitative: measure how many new users arrive to the page vs. sign up
- Quantitative: measure how many existing users arrive to the page vs. sign in
- Qualitative: have a 1:1 user test with somebody who has not seen the landing page (test the new version)
- Qualitative: have a 1:1 user test with somebody who has seen the landing page (test the new version)

**Estimated effort**: 2 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
@jordanh should we just the WISTIA embed here?

**Comment by jordanh** [comment]
Yes, for sure. We're almost ready to record a new vid, too. But, getting the design in place to embed it artfully will be a good first step.
