### ISSUE TITLE
Refactor: sprint to begin new user journey

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#63]
## Issue - Enhancement

Time to get serious! Let's refactor what we have into a real welcome journey we can use.

Use [Cashay](https://github.com/mattkrick/cashay/)!

- **Estimated effort:** 2 points ~ 2 days ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))
- **Mission**: https://goo.gl/jHX918

- [x] Create new `Welcome` module, route, and container

- [x] On successful account creation, send welcome email and redirect to `Welcome`

- [x] Create new `UserProfile` for user, navigate to step 2

- [x] Create new `Team` for user

- [x] Stub out component (can literally say "TBD") for team invitations (see: #59)

For reference:

![slack for ios upload](https://cloud.githubusercontent.com/assets/103000/15932050/32a27d38-2e28-11e6-980e-0f33c2884e0c.jpg)

**Comment by jordanh** [comment]
I am wondering @mattkrick if you'd like to take the lead on this?

**Comment by jordanh** [comment]
Much of this is *not at all* required for this mission, but I wanted to scratch it out here.

To summarize, we are moving toward the following locations:

1. A "public" site that houses our landing page, Pricing, FAQ, etc. handing off of `/` and a few other routes.

2. A `/welcome` route. When a team leader creates an account, they are redirected here. A team is created for them, and they are able to invite their team members here. Once the process is done, they are redirected to `/team/:id`.

4. A `/team/:id` route, houses the team dashboard (and will eventually pop a toast 🍞 ) if there is an active meeting in progress

6. A `/me/:nickname` route, that allows a user to access their personal dashboard

7. A `/me/:nickname/profile` route to edit a user's own profile

Following this mission we'll need to implement the journey for folks who've been invited by their team leader to join the team. I imagine, routes-wise, this is how that'll work:

1. Email is sent to invitee containing link to `/welcome/invitee?token=d3adb33f`

2. User will create account, and `/welcome/invitee` will validate token, render a basic user prefs component and collect information.

3. When complete, it will redirect the user to their `/team/:id` dashboard

**Comment by mattkrick** [comment]
@jordanh most definitely! i'll dig in on my flight tomorrow & shoot ya back any clarification questions tomorrow night.

**Comment by mattkrick** [comment]
@jordanh @ackernaut 
Let's chat `CachedUser` and `UserProfile`. 
- Two different tables? We'll need both on the initial user query, so many just 1?
- What fields should `UserProfile` have?
- Should we store them in the same place in cashay?

**Comment by jordanh** [comment]
I separated them only so it was clear what was being stored in Auth0.

That still makes sense to me, but if you want to change it, it won't break my heart!

Jordan
@jrhusney(http://twitter.com/jrhusney)/612.227.5673(tel:612.227.5673)

**Comment by mattkrick** [comment]
Nono, I'm up for anything, I just need to design `UserProfile` and `TeamMember` before I can move forward.
We'll need something like a `createdTeam` or `payerAccount`, but those will probably reside on `TeamMember` since they're team specific. You haven't by chance scratched out a rough draft relational schema, have you? :smile:

**Comment by jordanh** [comment]
Not beyond:
https://docs.google.com/document/d/1KyHMvagyepPoGrfa38LWNIbcBfRzCfaILSLkQa9D2Ng/edit#heading=h.qwhnypti21k8



Sent with Mixmax





On Wed, Jun 15, 2016 6:32 PM, Matt Krick notifications@github.com wrote:
Nono, I'm up for anything, I just need to design UserProfile and TeamMember before I can move forward.
We'll need something like a createdTeam or payerAccount , but those will probably reside on TeamMember since they're team specific. You haven't by chance scratched out a rough draft
relational schema, have you? 😄

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub , or mute the thread .



Jordan @jrhusney / 612.227.5673

**Comment by mattkrick** [comment]
Proposing a slight change to this:
let's replace `/me/:id` with `/me`. The `id` is just state, they're only ever going to visit a single `/me/:id`, and not only does this clean up urls, but it makes it super easy for UX. 

User story: "Hey Jordan, where do I go to see my dashboard?" Jordan copies his url & pastes it. "Here you go Terry: http://localhost:3000/me". "We love Action!". THE END.

**Comment by jordanh** [comment]
Awesome!

**Comment by mattkrick** [comment]
After #71, #73, I think we're good to close this, ya?

**Comment by jordanh** [comment]
Ja!
