### ISSUE TITLE
Team member filter active; create new project

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#630]
## Enhancement

When Kayla is interacting with the team dashboard and has the projects filtered to a single member, Jerry, Kayla may expect to see a card pre-assigned to Jerry when Kayla taps to add a new project to a column. Currently Kayla sees nothing and is sad. Then when Kayla changes to filter by all team members or goes to the My Dashboard view, there are a bunch of empty project cards assigned to Kayla. (No bugs, just working as designed.)

[See GIF](http://g.recordit.co/k5GDwGhrWz.gif)
[See LINK](http://recordit.co/k5GDwGhrWz)

**Opinion**: Parabol believes people should be asked if the accept a project or action. This acceptance of a trackable outcome may happen outside of the app meeting space, say on a post-it during an all-hands retreat, so there is yet another use case for being able to assign others asynchronously.

**Needs UX feedback**: Alternate use cases: Does Kayla expect to see a pre-assigned card to Jerry? Or a card for herself, after having focused on what Jerry is working on?

**Estimated effort**: 2 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
@mattkrick do you mind taking a gander and pondering the UX of this? We can totally change the first draft of what I’m suggesting. I’m also unsure of what Epic this may fall under. Also, would you mind taking this on if and when whatever effort needs to be done?

**Comment by jordanh** [comment]
Hey, we fixed this at some point!
