### ISSUE TITLE
Seed projects for team lead funnel

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#632]
## Enhancement

When Steve completes the Welcome workflow and lands on the Dashboard for the first time, he wants some direction as to next steps so that he can learn how to use the software successfully with his team.

- [ ] Automatically create a card assigned to Steve, in the Active column, with content: “Try a test run of an Action meeting. Tap on ‘Meeting Lobby’ in the dashboard header above.”
- [ ] Automatically create a card assigned to Steve, in the Active column, with content: “Invite team members to join your team. Tap on ‘Team Settings’ in the dashboard header above.”

**Does this pass our [Voice Test](https://docs.google.com/document/d/1hmASgB4pB4tsv_o5cdNIpYw01VCt_viV1EbypNsZXfw/edit?usp=sharing)**?

**Metrics**: We should expect an increase in Meetings and Team Invites.

**Estimated effort**: 1 point ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Let's try three projects. Here's the copy I've got:

1. **ACTIVE** Try a test run of an Action meeting. Tap on ‘Meeting Lobby’ in the dashboard header above.

1. **ACTIVE** Invite any missing team members to join the team. Tap on ‘Team Settings’
      in the dashboard header above.

1. **FUTURE** Make good teaming a habit! Schedule a weekly Action meeting with your team. Pro-tip: include a link to the meeting lobby.
