### ISSUE TITLE
Handle inactive users

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#633]
For inactive users, the current process is:
- log every period of inactivity 
- when the org invoice is created, grab all inactive periods for all users within the billing cycle date range
- for inactive periods that have no `endAt` (meaning the user is still inactive) set `endAt` to the end of the billing cycle & create a new inactive period with the `startAt` also equal to the end billing cycle datetime
- set the `MIN_THRESH` to 7 days
- filter out inactive periods that are less than `MIN_THRESH` days AND `endAt !== billingCycleEndAt` to make sure we don't punish someone who just recently turned inactive before the bill is due

Questions:
- Do we like the 7 day minimum inactivity threshold?
- Are we OK with someone being able to manually inactivate their entire team 6 days before billing day end?

**Comment by jordanh** [comment]
I like this design a lot. A LOT.

I like 7 day minimum inactivity. I think that's safe to try for starters. 

On the first point: question back at you, do you think we should send the inactive user and/or the team lead an email when a user passes this threshold?

I am OK with someone being able to manually inactive their team to receive a discount. For now. If it happens in larger numbers, I won't be. But heck, it'd be an honor to be gamed in this way right now.

**Comment by mattkrick** [comment]
i don't think the team lead needs an email that the org lead inactivated an account, especially because `active` does not solely apply to an org, it applies to all the orgs a user is on, so while an org can deactivate someone, it only provides a benefit if that user never logs on to check out another org.

for automatically inactivated users, i propose:
- cron job runs every day on every user
- checks if the user has established a socket connection in the last 30 days
- if they haven't established a socket connection & they aren't on a trial, then add a period of inactivity that starts the day after their last socket connection (underlying assumption: a socket connection lasts 1 day)

so the logic would look kinda like this:
- jan 1, i log in for the last time before vacation
- jan 15 my org gets billed for dec 15 - jan 15, i am charged full price
- feb 1, my account is flagged inactive & a 30 inactivity period is added to my account
- feb 15, my org is charged but receives a 150% refund for my account, since they charged me full price last month even though i was gone

alternatively, we could start the inactivity period when they get flagged as inactive & not give them the retroactive treatment.

**Comment by ackernaut** [comment]
Whether we give the retroactive treatment or not, I like the designs and logic you have here! Good stuff!

The only thing that I wonder about is the UX of inactivity across multiple orgs. But I think we do not know enough to understand the use case. It will potentially be another good problem to have in the future. :)

**Comment by mattkrick** [comment]
@ackernaut i hear ya, this should be better for UX. If we have org-level inactivity, then the UX gets really messy. For example, as is, if you establish a websocket connection, we assume you're active & remove your `inactive` status. if it's org level, we can't make that assumption, which means people have to manually reactivate themselves.

**Comment by mattkrick** [comment]
digging into the weeds, this seems easiest if we go retroactive to the beginning of the billing period, but not before that. In other words, no refund can be more than 100%. This is because this logic is implied in the manual refunds. If I flag myself as inactive on Day 10 & the invoice is on day 15, then credit for 6 days are added to that invoice, we don't wait until the next billing cycle to catch em all.
