### ISSUE TITLE
Stripe server integration

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#639]
After reading almost the entire stripe docs, i've got a new plan of attack:

- [x] Create a stripe customer when an org is created. If the org is created during the welcome wizard, set the `trial_period_days` to 30.
- [x] Create a stripe customer with no trial when an org is created from something other than the welcome wizard (addTeam, addOrg?). 
- [x] When billing details are added and `now < trial_end` set the `trial_end` to `trial_end + ms('30d')`.
- [x] When a new user joins an org, call `stripe.subscriptions.update` with quantity + 1 and set metadata = `{type: 'addUser', userId}`. This will create a new line item & prorate the subscription from the time of the call.
- [x] When a user is set as inactive, call `stripe.subscriptions.update` with quantity - 1 and metadata = `{type: 'pauseUser', automatic: true, userId}`.
- [x] To eliminate gaming, before calling the above, call `stripe.invoices.retrieveUpcoming`. and filter for `metadata.type === 'pauseUser' && metadata.userId === userId`. If there are more than **4** records, don't allow it. 
- [x] When a user gets automatically flagged as inactive, use `type: 'pauseUser', automatic: false`. If we wanted to, we could set `prorationDate` to the date of their lost login, but for now I say we just keep it simple. We're already saving them money, I doubt they'll get mad about us not saving them an _additional_ $5.
- [x] When a user comes back from being inactive, undo the pause with `type: 'unpauseUser'` and quantity++
- [x] When a user is removed from the org, use `type: 'removeUser'` and quantity--
- [x] Set up a webhook to listen for `invoice.created`
- [x] inside that webhook, run a map-reduce on the invoice line items by `metadata.type`. This will give us 5 values (the 4 listed above + an undefined). The undefined is the primary line item (eg 10 users * $5). Then, each type can be map-reduced again to make 4 parent line items of `addUser, removeUser, pauseUser, unpauseUser`. This is what we can show on our invoice (eg 5 New Users, prorated = $18.21). If they click details, then we can show them the breakdown by user & period (eg jay@prbl.co added on Sept 10... $3.30). We'll write all this write all this to our own `Invoice` table.
- [x] inside the ` invoice.payment_failed` webhook expire the trial or send a notification.
- [x] write a webhook for `customer.source.updated`. This will trigger when a customer receives a new card (eg lost/stolen/new expiry). see: https://stripe.com/blog/smarter-saved-cards
- [x] eliminate race conditions for all mutations that involve stripe 
- [x] refactor `trialExpiresAt` to `trialOrg` on the user doc

This is a little more math to do on our end for the map-reduce stuff, but in the end, it's a solid win because we can remove the `InactiveUser` table and the cron job and all the tougher-than-i-thought logic that goes into it. Plus, we don't have to add any hacky one-time invoice items. @jordanh

**Comment by mattkrick** [comment]
There exists a race condition when we unpause users.
Alice logs in & hits server A
Alice logs in & hits server B

server A looks up Alice, sees that she's inactive, quantity++ on stripe
server B looks up Alice, sees that she's inactive, quantity++ on stripe
since she's inactive on both, then we up the quantity on stripe. this would cause an overbilling.

to make it atomic:
- use `replace` instead of `get` & set returnChanges to true
- remove `inactive` update `updatedAt` update `lastSeen`
- look at the old_val. if it has inactive set to true, then we know we need to run the unpause script

**Comment by jordanh** [comment]
Wow. Incredible. Yes. This seems much more sensible. Thank you for reading the docs.

So, no separate cron server needed?

**Comment by mattkrick** [comment]
nope. we could host a separate server just for the webhooks, but i'm not sure if that's really worth it... probably better to just write the endpoint & deploy it to every worker cluster than have 1 dedicated worker that is sitting idle almost always.

**Comment by mattkrick** [comment]
The mapreduce strategy on invoice items fails for a couple reasons:
- when `quantity` is changed, stripe creates 2 invoice items
  - 1 to refund the prorated amount of the subscription
  - 1 to charge the prorated amount of the new subscription (where subscription = price * qty)

so, for an example, let's say I create my 1 man team. Stripe instantly bills me $5.
Now, say Terry joins my 1 man team after 6 days in a 30 day month:
- Refund $4 (since I used $1 of my $5 subscription)
- Charge $8 (2 x $4, since $4 is the amount left in the month)
- Charge $10 for next month

So, my next invoice will be $14. Makes sense, simple, but NOT user friendly in the LEAST.
To simplify, I can figure out how much Terry cost the team by summing up the 2 invoice items attached to him (-4 + 8 = $4). 

The trick is figuring out how to attach those invoice items to Terry. updating subscription metadata doesn't update the invoice item metadata. So, we have a couple options:

Option 1 (naive):
- update the subscription with metadata
- put a webhook on `invoiceitem.created`
- inside that webhook, query the subscription metadata & attach it to the invoice item

This works, but it opens us up to race conditions. For example, if billing leader 2 updates the quantity before both `invoiceitem.created` webhooks fire, then we have a stale read. Granted, the chances of this happening are slim, but i don't like it.

Option 2 (scalable):
A better solution would be to store that metadata ourselves in a DB table. The only problem with that is we need to figure out how to link the _input_ from the `subscriptions.update` to the _output_ of the invoice item. The only field that fits the bill is `proration_date`, since `update.proration_date === invoiceitem.period.start`:
- create `InvoiceItem` table
- calculate `prorationDate = ~~(Date.now()/ 1000)`
- create an object with the prorationDate as the primary key, `userId, type` as fields
- attempt to insert it into the database. if it doesn't insert, we detected a collision. Add 1 to the prorationDate & keep trying until we succeed
- when the `invoiceitem.created` webhook is triggered, grab the `period.start` do something like `r.table('InvoiceItem').get(period.start)`. 

@jordanh feel free to review, i'm headed to the gym right now, will start coding up option 2 when i get back.

**Comment by jordanh** [comment]
If you feel _super duper_ strongly about biting off Option 2 now, go for it. Else, I don't find the UX of the line items...

> Refund $4 (since I used $1 of my $5 subscription)
> Charge $8 (2 x $4, since $4 is the amount left in the month)
> Charge $10 for next month

...to be bad (nor a bad place to start). My advice, start there – let's test – and revisit. Else, _vaya con dios_ con opcíon dos!

**Comment by mattkrick** [comment]
Heh, that was my original thought, but if someone onboards a team of 10
that'd be 21 line items, and the line item charges aren't as pretty as I
made them seem... The only problem I see with option 2 is that it puts a
hard limit of 1 transaction per second across the entire user base. In
reality I'd probably index on timestamp + org.

On Jan 16, 2017 1:47 PM, "Jordan Husney" <notifications@github.com> wrote:

If you feel *super duper* strongly about biting off Option 2 now, go for
it. Else, I don't find the UX of the line items...

Refund $4 (since I used $1 of my $5 subscription)
Charge $8 (2 x $4, since $4 is the amount left in the month)
Charge $10 for next month

...to be bad (nor a bad place to start). My advice, start there – let's
test – and revisit. Else, *vaya con dios* con opcíon dos!

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/ParabolInc/action/issues/639#issuecomment-272969447>,
or mute the thread
