### ISSUE TITLE
Summary of Done items

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#644]
## Issue - Enhancement

If you are a:
 - team leader who creates weekly/monthly/quarterly reports on progress
 - a teammate who misses a meeting (sick, vacation, etc)
 - a teammate looking for archive/review purposes
 - a passive observer that reviews summaries but doesn't participate in the actual mtg (e.g. a leader 1 circle of influence higher/lower; Parabol teammates on our ExCo, etc.)

then it would be useful to see Done items included in each team meeting Summary.

Current view has white Projects followed by yellow Actions--perhaps add greyed-out Done items at the end of the queue and a 3rd horizontal bullet at the top btwn the avatar & the boxes ("9 New Projects * 4 New Actions * 7 Done"

### Parameters
- Cards occupying the "Done" section are the same as those which would be rolled up in the archive after a meeting
- Teammate who "done"-d the issue should be clear! Recommended we group by teammate.

### Acceptance Criteria
- "Done" section added to meeting summary

### Points:
- 13

**"when you’re selling to management you’re selling reporting." -a smart guy we know**

**Comment by jordanh** [comment]
I generally agree with this. This is pointing at the higher need for giving teammates a sense of progress. This might be a good place to start. There may be also a mid-week or end-of-week communication (a la Friday Ship) we could consider.

**Comment by tayamueller** [comment]
This continues to feel like a strong accountability & transparency feature. Recommend moving this up in priority:

 1) August team noted that including Done items in the Summary would be helpful for absent teammates 

2) Avalon wanted this feature as they're adding new teammates each week as the project grows. 

3) Also mentioned: it will be helpful to see what has been Done each week so she can facilitate re-assigning/balancing workload--some teammates are naturally eager volunteers while others aren't; this could help prevent burnout.

4) Avalon (and probably future corporate clients) also have a requirement to submit a weekly progress report and they were THRILLED that this could function as that report IF it included Done items. (could also help us with writing Friday Ships :)

**Comment by tayamueller** [comment]
"when you’re selling to management you’re selling reporting." -a smart guy we know

**Comment by jordanh** [comment]
See #1686

**Comment by ackernaut** [comment]
Shipped with #1731
