### ISSUE TITLE
db:migrate-up goes ALL the way up

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#649]
reproduction:

migrate down to addOrgs
type `npm run db:migrate-up`
it says it will migrate up 1
it migrates up all of them

**Comment by jordanh** [comment]
https://github.com/JohanObrink/rethink-migrate/issues/26

**Comment by jordanh** [comment]
https://github.com/JohanObrink/rethink-migrate/pull/27

Waiting on a PR. The maintainer of rethink-migrate has not been very active. Perhaps we should take this project over?

**Comment by mattkrick** [comment]
take over!
