### ISSUE TITLE
Reintroduce -p to webpack builds in build:deploy

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#65]
## Issue - Enhancement

#64 stripped -p from `build:server` and `build:client`. We'll reintroduce these flags in a `build:deploy`.

- **Estimated effort:** 1 point ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Taking a moment to think about this @mattkrick. Really we only care about the client bundle being minified and uglified. Ok to re-add `-p` to `build:client`? That won't get in the way of your server development.

For all client dev, I assume you'll just use `run dev`, yes?

**Comment by mattkrick** [comment]
Here's my workflow:
- Adding functionality to the client: `npm run dev` (wait for server startup + client compilation)
- Adding functionality to the server (first time): `npm run bs` (wait for server startup, compile & write client & server configs)
- Adding functionality to the server (every other time): `npm start` (wait for server startup)

If we uglify & optimize the production build, then we go almost 50% slower when we call `npm run bs`. Not the end of the world, just a little annoyance. I can just leave it disabled all the optimizations (https://github.com/ParabolInc/action/blob/master/webpack/webpack.config.prod.js#L57-L59) & re-enable them before I make a PR if you wanna leave it in.
