### ISSUE TITLE
Secure RethinkDB so we can use the web UI in production

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#650]
@jordanh giving this one to you if you want it.
https://www.rethinkdb.com/docs/security/#securing-the-web-interface

**Comment by jordanh** [comment]
I accept this mission!

**Comment by jordanh** [comment]
Hey @mattkrick – I made us a little something. Give [this](https://github.com/ParabolInc/action-devops/blob/2a1fa5ce0ca93be5dc96ed17da836736c2b07443/dokku/rethinkdb-secure-tunnel.sh) a try:

```bash
   $ ./rethinkdb-secure-tunnel.sh -s x@action-staging.parabol.co -p 8081:8080
```

Where x is the staging administrative user.

Then, point your browser to `http://localhost:8081`.

Voila!

**Comment by jordanh** [comment]
Donzo.
