### ISSUE TITLE
Failed payment notification email

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#651]
## Enhancement

When a payment fails for a billing cycle, the customer wants to receive a notification email so that they can fix any issues with billing (i.e. update CC info) so that their teams can continue using Action.

**Estimated effort**: 3 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Over a year now, not a strong tension. Need more customers!
