### ISSUE TITLE
Payment_failed hook

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#653]
So let's say I join, i get my 30 day trial, i use it for 25 days, and then i take a week off. In the mean time, my trial lapsed and now when i log in, i need to add billing info.
- If i add my billing info on day 31, then `Team.isPaid = true`and I can keep trucking along. No worries.
- if I add my billing on day 55, should I really be charged for the 25 days that I didn't even use? Probably not, but how should this be handled? What if i join on day 200? 

So, my question @jordanh @ackernaut @ndey96:
- What's the threshold for determining which action to take? 0 days? 1 day? 1 week?
- What should happen afterwards?

Background:
When a trial expires, stripe attempts to bill the customer. if no CC exists, stripe changes the subscription status from `trialing` to `past_due`. Then, they send a `payment_failed` webhook. In stripes eyes, there is no difference between a trial expiring and a user's credit card getting denied.

Proposal:
- set our Stripe settings to _not_ cancel the subscription, which they will do by default if payment fails after 3 attempts
- When the stripe `payment_failed` webhook fires, we should:
  - set `isPaid` to false on all teams so no one on any team can do anything
  - set `quantity = 0` in stripe so beginning at the time of the failed payment, they don't accrue a balance
- When the stripe `payment_succeeded` webhook fires, we should:
  - set `org.validUntil` to the new `period_end` as provided by stripe
  - set `team.isPaid` to true for all teams
  - set `org.isTrial = false` (this will already be false for all the regular customers)
  - set `quantity = org.activeUserCount` on stripe so they start accruing the balance for all their members. As a side benefit, in the very unlikely event that quantity was off due to the lack of atomicity in stripe's API, it'll get corrected.

The pros:
- no arbitrary threshold to determine when to continue a subscription vs. when to start a new subscription
- customers don't feel cheated if they update their billing info late, which should improve conversions (or at least reduce complaints when they do).

The cons:
- They'll get a $0 invoice for every month that they're away. we'll still handle those & in the future, we'll have a bunch of people who used our trial, didn't convert, and now we're still making invoices for them. At some point (2 or 3 months?) we'll want to stop that.

Another option:
- cancel the subscription immediately when a failed payment occurs
- set isPaid to false on all teams
- send out a notification (either TRIAL_EXPIRED or PAYMENT_REJECTED depending on the value of `isTrial`)
- set `org.stripeSubscriptionId = null`
- Then, when they add billing/fix billing, we check for `org.stripeSubscriptionId`. if it's null, then we create a new subscription for them based on the number of activeUsers they have.

Pro
- no infinite flow of invoices

Con
- a crappy dude could just go delinquent every other month to avoid paying half his invoices. For example, on Jan 1 pay for Jan 1 - Feb 1 for 1 user: $5. Then on Jan 2, add 9 users. Then the bill on Feb 1 will be 9 * $5 = $45 for Jan + $50 for Feb 1 - Mar 1 = $95. To mitigate this, we could add the bill to the `account_balance` on the customer.

Let me hear some thoughts

**Comment by jordanh** [comment]
This is a fun one. All designs are so simple until they meet another org's API.

When we churn folks who don't convert after trailing, we'll need to find good ways of maintaining a marketing relationship with them so we have a chance of converting them later. Hitting them up with spammy $0 invoices doesn't help us :)

Option #2, cancel the subscription, feels cleaner to me. I think we could detect the frequency of the subscription scammers/delinquents through BI reporting and adapt. Classic "safe to try." Classic problem I want us to have.

**Comment by mattkrick** [comment]
yeah, that's my thought, although having to play with an account balance doesn't excite me. But i guess that's the price for a pretty invoice instead of a generic stripe one.

**Comment by ackernaut** [comment]
@mattkrick thanks for taking the time to give the details on this one. I am leaning to option no. 2 as well. I think we hire the person who games us and tell them to make our funnel better, white hat.

**Comment by mattkrick** [comment]
option 2 it is!
