### ISSUE TITLE
UX enhancement: slow speedy facilitators

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#654]
## Issue - Enhancement

We've observed a tendency for facilitators, when new to Action, to want to speed through meeting stages without reading the facilitation prompts to their team.

Some ideas on how to resolve this:

   1. If the item/phase advances less <500ms from landing on the page, pop a toast
   1. If the item/phase advances less <500ms from landing on the page, animate the facilitation prompt
   1. Animate in the facilitation prompt

What other ideas do we have?

- **Estimated effort:** 15 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
I have a few ideas here:

1) We decouple the P/N presence buttons from navigation like we originally had it. It was an extra bit of friction that made sense to me. I mark the person present but they still have the floor. I still find that I want to go ahead and mark them and wait for them to finish talking. Then navigate. Right now we’ve made it even easier to blaze through.

2) I think we animate in the prompt as the first element in the view (beside the meeting chrome components): 1) FLASH: Look I'm an important thing! 2) FLASH 2: Look here is the name of the person (implying that they ask the person). Then we animate in the cards and can cycle through.

**Comment by jordanh** [comment]
Perhaps no longer an issue? Iceboxing.
