### ISSUE TITLE
Idea: "I got what I needed button"

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#655]
## Issue - Enhancement

When an agenda item is processed, the facilitator has to implicitly know to ask the agenda item owner if it is ok to proceed. We coach asking, "did you get what you needed?" However, it would be better if we automated this.

Consider the following design:

- By default, the agenda item owner has to hit the "I got what I needed" button in order to proceed
- The facilitator _can_ skip this safeguard, but some form of, "are you sure?" is asked of the facilitator first
- If multiple people enter items, then they too much also hit a button labelled "I got what I needed"
- All meeting participants can see how many people still need to hit the button before the meeting advances

- **Estimated effort:** 20 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
Hmm…I feel like the UI+UX of this can be tricky.

It may be easier (cognitive load and UI confusion) to keep 1 button mapped to the original person who wrote the agenda item. However, if that person is not on a laptop (just sitting at the table) we may have somebody else entering the agenda item for them and consequently tapping that button. “Hey, can you add an agenda item for me?” or they already added it before hand in the team dash. So it is good that the facilitator can bypass it. Maybe the facilitator has a similar UI. They have to tap a button before they can navigate forward. We introduce some friction to help the meeting flow.

This also makes me think of #175 where somebody in the room may be entering on a lappy for somebody else.
