### ISSUE TITLE
Xmit user hover states on project cards

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#656]
## Issue - Enhancement

When a user's cursor hovers over a project card on a dashboard or in a meeting (say during the updates phase or agenda processing phase) pass which card is being hovered on in the same manner we pass the "editing state."

Style the project card special. This will add a "more people in the room" vibe to the software.

- **Estimated effort:** 15 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
What ideas do you have on how this will look? What visual feedback?
