### ISSUE TITLE
Improve AWS S3 file upload strategy

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#657]
currently, we create a random hash, send it to the client & the client can then upload their file to the server.

In the future, that hash should not be random. It should be a hash of the photo itself. Then, when they upload the file, if the file already existed, they'll overwrite it so we don't keep a million duplicates on our server.

**Comment by jordanh** [comment]
Oh, this is a fun idea. We'd have to calculate the hash on the client – but no big deal there.
