### ISSUE TITLE
New Team Member Invite Bug

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#660]
# Issue - Bugs

[this seems high priority b/c our current users may be experiencing these bugs as well?]

On an onboarding call today:

Bug 1:
* Jordan created "Paul's Team" & invited Paul, Jordan, Taya
* Jordan invited me 2x but I got 3 invites
* When I clicked on Join Team I got this error screen:
![error](https://cloud.githubusercontent.com/assets/307286/22266692/9534ecf6-e246-11e6-9637-342f3849a95a.jpg)

Bug 2:
* (the green check-circle didn't work; I had to manually press Enter)
* and then I was sad & lost because I wasn't actually trying to create a new team, I was trying to join the team invite I'd received....so the #engineering channel has a bunch of instances of "*Taya <taya@parabol.co>*  did *Welcome Step1 Reached*."

Bug 3:
* Because I'm an insider, I checked my Dashboard to see if "Paul's Team" had just appeared there--it did not, until about 10min later I noticed it there.

Bug 4:
* I actually just noticed I now have TWO "Paul's Teams" on my Dashboard even though Jordan manually deleted us from the team before ending the onboarding call. (have we built Delete Team yet?)
* interestingly, when I archived all the cards from one "Paul's Team" they did not disappear from the 2nd "Paul's Team"....

Bug 5:
* interestingly, when I click "Team Settings" on either instance of the "Paul's Team" I'm listed as "Lead" (I was not lead, Paul was)

**Comment by jordanh** [comment]
Should be fixed already by Epic 2.
