### ISSUE TITLE
Can end meeting without covering newly added agenda item

### ISSUE THREAD

**Issue by ndey96** [ParabolInc/action#661]
## Issue - Bug

Test steps:
- Navigate to team dashboard
- Have no agenda items
- Start a meeting
- Click through check-in and updates
- Click "Let's take care of our agenda items"
- Add an agenda item

Bug(s):
- The number of agenda items displayed in ```We worked on 0 Agenda Items resulting in 0 Actions and 0 Projects.``` string does not change
- It is possible to end the meeting without covering the agenda item you added
- If you end the meeting, the agenda item you created won't show up in the team dashboard

Suggestion:
As soon as the agenda item is added I think all meeting participants should jump to that agenda item

My test setup:
- **OS:** OSX
- **Browser:** Safari 10.0.2
- **Node version:** v6.9.2
- **NPM version:** v3.10.8
- **RethinkDB version:** rethinkdb 2.3.5 (CLANG 8.0.0 (clang-800.0.38))
- **Estimated effort:** 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
This is a good catch.

I'll add this to your Epic queue if you'd like to tackle it @ndey96. Else, we'll get to it when we get into  refining product experience.

**Comment by jordanh** [comment]
I think we fixed this! @ndey96, if you're out there, please give it another test and let us know?

😄
