### ISSUE TITLE
Notification settings, trial context

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#664]
## Enhancement

(Background: I’m capturing this because I think it’s a good idea, and I was annoyed by another SaaS recently where the trial had expired, and I could not turn off notifications.)

When a user has an expired trial, he only wants notifications or nudges about re-activating the account via billing, so that he can know exactly how to continue to use the software.

&

When a user has an expired trial, he does NOT want notifications that he cannot act upon or turn off because his account is blocked or restricted (outside the scope of billing, re-activiating, etc.).

**Estimated effort**: 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by tayamueller** [comment]
so important.

**Comment by jordanh** [comment]
There is another service ("I Done This") that is doing this to me right now. It is ) _no bueno._

The question is: how will we know we've implemented this issue?

**Comment by ackernaut** [comment]
Oooh, I would think that the design spec would be: Notifications (other than those flagged as nudges for billing, account reactivation) do not get pushed if an account is expired.

And, yes it was I Done This that triggered the tension.

**Comment by jordanh** [comment]
No longer applicable, b/c we no longer trail.
