### ISSUE TITLE
Empty action items, can remove?

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#665]
## Enhancement

Does it make sense to allow users to remove empty action items from the list? Is this easy to implement without conflicting with textarea/card behaviors in other contexts?

[recordit.co](http://recordit.co/ExLbCw2x7J)
[recordit.co, GIF](http://g.recordit.co/ExLbCw2x7J.gif)

**Estimated effort**: 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Yeah, this one has bugged me for a little while. We clean this one up. Let's keep it in Future for now. But, we may escalate when we scrub the backlog.

Thank you for opening this!

**Comment by jordanh** [comment]
We no longer have action items! Closing.
