### ISSUE TITLE
clean up DashModal styles

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#666]
Now that we're using portals, we can probably clean up some of the magic that @ackernaut used to make modals work in the first place. @ackernaut let me know if you've got any questions on how it all works, I set up a basic animate-in/animate-out just to make sure it worked, but feel free to make it pretty.

**Comment by ackernaut** [comment]
@mattkrick ooh, high fives for this one—I’ll dig in.

**Comment by jordanh** [comment]
Already done in epic 2!
