### ISSUE TITLE
Links in Agenda items

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#669]
## Issue - Enhancement

useful to have live links in Agenda items to reference and/or show & tell during Action check-ins

**Comment by ackernaut** [comment]
+1, extend MD into agenda items?

**Comment by mattkrick** [comment]
it sounds like you're asking for something very trello-esque. Each agenda item has a title & then a body. The title is small & simple, the body has links & formatting.

**Comment by jordanh** [comment]
I think this idea deserves a deeper design cycle. Connecting some dots: and implementation of #613  may have a card from the future column come up as an agenda item at the appropriate time to get broken down into smaller tasks.

I think #613 and this issue are pointing at the idea of an "agenda payload" or "agendaItemNote". Perhaps an agenda item can accordion downward to add these notes?

**Comment by ackernaut** [comment]
Ah, and maybe there’s a quick way to convert notes into card content, which is in the ballpark of #568

**Comment by jordanh** [comment]
Closing in favor of duplicate #1018
