### ISSUE TITLE
Configurable meeting sections

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#672]
## Issue - Enhancement

We've received user feedback that having configurable meeting sections is a desire. Examples include: turning on and off check-in round. Adding metrics. Etc.

We've also received signal that having a "discussion" section is desired. This is a section that would be added to the end of a meeting to simply talk about stuff.

One user mentioned how there is a client team who puts asterisks next to agenda items they'd like to have discussions about. We could provide a control to "move to discussion" for agenda items. We could also provide "schedule meeting to discuss agenda item" UX.

**Comment by ackernaut** [comment]
I'm glad you captured this.

Re: discussion section—I am guessing it has to do with how the discussion section feels (soft skills, rules) as on paper is seems redundant to have agenda items that are queued for a discussion session, whereas we discuss agenda items already? I guess the other agenda items get processed more quickly with little discussion, just generating actions/projects whereas they need a discussion section to take time to talk about the other items marked with asterisks.
