### ISSUE TITLE
OutcomeCard labels/tags

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#674]
## Issue - Enhancement

This has come up multiple times with users. First with August public, and most recently with a user DH in San Francisco.

There are at least two contexts for use:

1. When I want to see outcome cards on a team related to a single outcome, I want to filter by label/tag, so that I can get a handle as to what's going on
1. When I want to see the same type of thing (e.g. customer meeting, development effort, etc), I want to filter by label/tag, so that I can see how much of a certain activity is happening on my team

### UX suggestions/thought starters:

Similar to how GitHub works, pressing `#` will open a portal to auto-complete a tag. Available tags will be scoped to a team. See #684 

```
Tomatoes bought. #inventory
```

```
Fridge repared. #maintainence
```

```
Pasta bought. #inventory
```

It should provide a multi-select filter control (with checks) to be able to filter a board to one or more tags. See #692 

### Technical implementation notes:

Since tags are scoped to team, search isn't yet a thing, we can do the indexing on the client in the front end as outcomes are loaded. We could store them in a duck:

```javascript
tags: {
   'tag1': [outcome id_0, outcome id_1, ... outcome id_n],
   'tag2': [outcome id_0, outcome id_1, ... outcome id_n],
   /* ... */
   'tagn': [outcome id_0, outcome id_1, ... outcome id_n],
}
```

- **Estimated effort:** 30 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
👾

**Comment by ackernaut** [comment]
I like the idea of extending our current menu component to handle `up` and `down` movement, `enter` to toggle tags that are selected and reuse `tab` to save?

**Comment by ackernaut** [comment]
If the menu is single select both `enter` and `tab` could save.

**Comment by jordanh** [comment]
Still a good idea, will get to something like this eventually. Iceboxing for now.
