### ISSUE TITLE
Square avatars, The Right Way™

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#679]
## Enhancement

We want avatars to be square at all times. And currently, we prefer that they be rounded using CSS to a circle shape. So there is a quick way (#678) and a more involved way to do this:

### The Right Way™

- We improve our avatar uploading modal.
- Users are presented with a cropping sub-view in the modal that is constrained to square dimensions.
- The user crops and commits.
- :boom: square avatar that really is square. Existing styles using `background-cover` can remain in place for any avatar images that still exist pre-cropping tool daaaays.

**Estimated effort**: 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Still a thing. Closing as per icebox.
