### ISSUE TITLE
Use auth0 refreshToken to keep a user logged in during a meeting

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#68]
## Issue - Enhancement

It would be a stinky user experience of a user's JWT authentication token expired during a meeting. Instead we could:

- [ ] Request a refreshToken on behalf of the user when they log in
- [ ] If the JWT expires, and the user is attending a meeting, request a new JWT for them instead of asking them to reauthenticate

- **Estimated effort:** 5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Quoting @mattkrick to keep this idea:

> My thought there is that if the token has less than X days left, renew it on the socket handshake...

**Comment by mattkrick** [comment]
we wanna keep middleware fast & sync, so let's not do it there.
Instead, on the server, we listen for the internal handshake message.
we decode & check the expiration (sync)
if the exp - time < 30 days, then promise to create a new token (async)
when that token is created, call `setAuthToken(data, [options])` and it'll do the rest.
