### ISSUE TITLE
Same question, multiple teams?

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#680]
## Enhancement

When a user is on many teams that meet on a weekly cadence, she wants a different check-in question for each meeting so that check-ins are fun in the context of all teams.

Problem to solve: How to rotate week over week with multiple teams without using random?

**Estimated effort**: 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Implemented!
