### ISSUE TITLE
GitHub card integration

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#690]
## Enhancement

A user can quickly create a card representing an issue or PR on GitHub:

See #684:

Can use `+GH#123` at beginning of `textarea` to create a card with the GH issue/PR title and a link to the issue on GH. This requires org/team integration setting: “Add GitHub”

**Estimated effort**: 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Consider following 1st 3rd party integration (Epic 6?)

**Comment by mattkrick** [comment]
i think this is good, but i think the flow is backwards. in the future, i want my cards to be populated by github automatically so i don't have to manage 2 sources of truth.

**Comment by ackernaut** [comment]
Closing in favor of #945
