### ISSUE TITLE
Card templates

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#691]
## Enhancement

User can create a card template for common outcomes (projects/actions) to team/org:

**Schema**:
- Title (for usability)
- Content (including Markdown)

**UI**: Can use `=` at beginning of `textarea` to create a card using a template. This requires card templates `{ title, content }` that can be managed by team/org. The `=` would trigger a menu with autocomplete where the user can type strings from the card template title and/or content. See #684 

**Note**: Make templates separate from recurring/due date
- Template is for content
- Recurring and/or deadline may be different per outcome that is generated by template

**Question**: Where to CRUD card templates? Does each team own their own templates? Organization?

**Estimated effort** 15 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Still a good idea. It's going to come back. Probably in Notes with Roles and such.
