### ISSUE TITLE
Menus, add multi-select

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#692]
## Enhancement

**UX examples**:
- A user can filter by multiple options
- A user can add multiple labels #674 

**Idea for UI**:
- Add `up` and `down` to navigate menu options.
- Single-select menus will update with the selection and close on `enter` and `tab`.
- Multi-select menus will toggle individual menu options with `enter`. Pressing `tab` will applied the new set of toggled options and close the menu.
- Pressing `esc` will cancel changes in selection (??).

**Note**: See #693 for menu autocomplete enhancement

**Estimated effort**: 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Captured in designs for Single Kanban – this will likely resurface. Closing as per Icebox.
