### ISSUE TITLE
Menus, add autocomplete

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#693]
## Enhancement

In order to quickly select options like labels (see #674) we should have an autocomplete feature that updates the list of menu options currently visible. See #692 for ideas on single select, multi-select.

Also see Markdown customizations #684 

**Estimated effort**: 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Let's revisit this when we've plumbed search into the product. Closing as per Icebox policy.
