### ISSUE TITLE
Welcome Step 3 is skipped [EP2: add-orgs]

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#695]
## Issue - Bug

When I create a new user via the welcome wizards, it renders the `Welcome Step3` component and then immediately drops to the dashboard.

Steps to reproduce:

1. (Delete any existing user from auth0 development instance)
2. Sign up for a new account
3. Complete Step 1
4. Complete Step 2
5. When Step 3 renders, note failure

- **OS:** OSX
- **Browser:** Chrome

**Comment by mattkrick** [comment]
fixed on add-org-invites
