### ISSUE TITLE
On New User, Trial Already Expired [EP2: add-orgs] 

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#696]
## Issue - Bug

After a new user is created, I see the following:

![image](https://cloud.githubusercontent.com/assets/103000/22567697/ff16fd52-e95e-11e6-8287-022fcbfc31ff.png)

If I navigate to my team I see the following:

![image](https://cloud.githubusercontent.com/assets/103000/22567714/0f41fb3c-e95f-11e6-9ddc-a83585bfb6cc.png)

**Comment by mattkrick** [comment]
fixed in add-orgs
