### ISSUE TITLE
Clean up signup/signin

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#698]
Currently, what we do is a huge mess with trusting data from auth0 over our own DB, long signins, etc.

The way forward:
- Sign in with auth0, it returns `openid rol tms` in the token.
- Based on that if `!token.tms` then redirect to the welcome wizard, else, `/me`.
- Call `updateUserWithAuthToken` but don't await it. This means the preferred name & photo might not be there as soon as they get to the next screen, but maybe it will since the next screen is a huge chunk. Either way, it's better than waiting.
- updateUserWithAuthToken validates the token the client gives it, and if no tms is present, it fetches the profile from auth0 and inserts a new user into the DB. Then, it fetches the user.preferredName, email, etc and sends it back to the client. That reduces it to 2 async calls for new users & 1 for returning users. 

Next, we remove name & picture from auth0, just trust our DB.
Finally, this still doens't solve the duplicate `tms` problem. We like the `tms` coming from auth0 because that means only 1 round trip for a login. Otherwise, we'd have to get the auth0 token, take that to our server, validate it, and return a new token with the `tms` field. I think the replication is fine as long as we never have to wait for it. For example, when we add someone to a new team, just hit up auth0 with that new tms info async.

Prioritizing on epic 2 because I'm running into a lot of stuff that involves exactly this in the new org creations.

**Comment by jordanh** [comment]
Perfect!

**Comment by mattkrick** [comment]
@jordanh do we use the name & avatar for segment? if we don't have to wait for those fields to come back, we can go 1 round trip faster. alternatively, we can find a better place to stash the identify event type.

**Comment by jordanh** [comment]
We do use those fields. We need to call identify before any of the other events are called. But you can call it with incomplete info the first time, then complete info the next time. Have a good place to do that?

**Comment by mattkrick** [comment]
ah gotcha, i think it's a pretty easy refactor. what about `created_at`? Still useful? I only se

**Comment by jordanh** [comment]
If it's a bother, we can omit it. We don't use it for anything right now...

**Comment by mattkrick** [comment]
cool, i noticed it was only coming in from fresh logins & not on any other `setAuthToken` so i figured it wasn't too important. all refactored, there is a noticeable speed boost!

**Comment by jordanh** [comment]
Holy crap really?? I can't wait to try it!

**Comment by mattkrick** [comment]
fixed in add-orgs
