### ISSUE TITLE
RFC Add roles to JWT

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#70]
## Issue - Enhancement

It makes sense to keep team-based permissions out of the JWT to keep it lightweight, but we should add in some app-level permissions.
I'm proposing a `rol` field inside the JWT (protocol is to keep a field limited to 3 chars). By default, it will not be included. But if it is, it could have the following values:
- `su`: superuser. can visit the `/graphql` page and email templates that @ackernaut is setting up. Can query and mutate entities that do not belong to it. Given to parabol employees. Certain sensitive items, like the `inviteToken` are still hidden via graphql & require direct DB access.

By including this in the token, we don't have to hit the database to check for admin privileges on every single query. This is useful for a query like `getTeamById` where we only want to return a value if the person is a member of that team OR if they are a parabol employee.

By using `su` as the value, we save 2 characters compared to using `true`, plus it allows us to add in more roles later, for instance, maybe certain employees can only view credit card info...

**Estimated effort:** 1 point ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
I like this. I can take it on.

**Comment by mattkrick** [comment]
nice! if we do it for just employees, i don't think there's any need to write a graphQL script yet. We can just get into auth0 and manually add app metadeta (i already did it for a@a.com)

In the future, we can write a GraphQL mutation, but that's definitely not necessary for the MVP:
https://auth0.com/docs/rules/metadata-in-rules
