### ISSUE TITLE
Pattern for graphql-enabled unit tests

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#702]
## Issue - Enhancement

We have _a lot_ of code to test from Epic 2. We need a testing pattern that can help us. This issue is to get us started.

### It:

- [ ] should use avajs
- [ ] should start the server
- [ ] should run all migrations

#### First test case:

- [ ] create a new user
- [ ] set the user's preferred name
- [ ] create the user's first team and org via the `createFirstTeam` mutation
- [ ] invite a number of team members via the `inviteTeamMembers` mutation

- **Estimated effort:** 15 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
superseded by #744

**Comment by jordanh** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Other Thing](https://trello.com/c/TLoPHcu7/3-other-thing)
