### ISSUE TITLE
Summary cards link to dashboard

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#704]
## Enhancement

When a user is reviewing the summary of a meeting (in browser or email), she wants to tap on a card to see the card on the dashboard view.

**The simple version**: we link to the team dashboard view where the card should be living if not archived…

**Estimated effort**: 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
First step would be to give cards permalinks. Still a good idea, iceboxing for now.
