### ISSUE TITLE
Can't Delete Team Members

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#714]
## Issue - Bug

1) tried to remove previous members of a  demo team, it appeared to work

2) typed the first email of the new teammate & hit send--her name did not appear in the list and all the OLD members re-appeared

3) hit refresh; still old team/no new teammate

4) went back to Team Dashboard, couldn't access Settings again until I refreshed

5) can now access Settings but cannot delete the old teammates that are still there

**Comment by mattkrick** [comment]
fixed in add-orgs
