### ISSUE TITLE
Improving Tethering

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#715]
## Issue - Enhancement

Frequent observation that Facilitator tethering is not understood/noticed until discussed/explained.

Once explained, our version of tethering is perceived as an IMMENSELY helpful feature:
1) elegantly solves the problem of "being on the same page"
2) unlike "share screen" (everybody else's solution) participants stay active thanks to multi-player editing ability & our social/discussion prompts

Suggestion: perhaps a visual reminder of tethering/untethering to keep folks aligned? Similar to the slow-blink red button when a Zoom is being recorded...maybe the hot pink Facilitator indicator could be a) bigger b) slow-pulse-glowing when tethered, then static/lighter color value if untethered

**Comment by ackernaut** [comment]
Closing in favor of 1) rejoin facilitator button 2) new avatar group styles showing where the facilitator is at 3) the facilitator badge and 4) the improved copy in the lobby...(all shipped!)
