### ISSUE TITLE
Improving Check-In Round

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#717]
## Issue - Enhancement

Folks are still blowing through the social prompts in the Check-In Round/general confusion about what this "is for" (frequent: "taking attendance". 

Suggestions:
1) Might help to reverse the visual hierarchy of the "Hello" conversation box vs the speaker box (avatar + P/N box). Recommend making the conversation box ~30% bigger and the speaker box  ~50% smaller. Better visual representation of the purpose of this section.

2) General confusion about A) whether action is required (yes: mark Present/Not Present; this is often missed) and B) who is responsible for the action. Recommend creating some white space under the conversation box with a small "Facilitator:" to indicate that the actions below are not for the whole group (akin to the psychological function of "For Office Use Only")

* In the future where everything is better, it would be amazing to have an animation so that when someone is marked "Present/Not Present" that status is visually linked with the person's avatar in the top row to draw attention to that row's function. Maybe the status "flies up", maybe the top avatar glows with the new status, etc.--something to connect that the action in the bottom is impacting the signifier in the top.

3) "Next teammate (press enter)" has caused some confusion--is this a command for the next teammate to carry out, or is it an instructional prompt for the Facilitator? Recommend deleting the copy entirely and moving the green arrow circle to BETWEEN the current teammate and the fuzzy "next teammate". (There has been zero confusion about the fuzzy next teammate--very clear that this is because they are the next "on deck"; might as well move the arrow to that line to emphasize the linear flow of action)

**Comment by ackernaut** [comment]
I like these suggestions, marking as Epic 3 for scrubbing/prioritization.

**Comment by mattkrick** [comment]
this is looking more like a terry job than a matt copy edit job so i'm gonna hold off on this one for now.

**Comment by ackernaut** [comment]
Closed via #876
