### ISSUE TITLE
Notification for Leaving A Team

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#718]
## Issue - Bug

Happened too fast to grab a screen shot, but when I left a team, I got an upper-right yellow pop-up that said something like "You've successfully left Team [Team Name]" but it read "You've successfully left Team !@#$%^& [nonsense]"

**Comment by ackernaut** [comment]
Adding to Epic 2.5

**Comment by jordanh** [comment]
Good find! Great capture of this bug. It's really easy for us to take action and prioritize when it's one item per issue.

**Comment by jordanh** [comment]
Just verified, this has already been fixed on `add-orgs`. Huzzah!

**Comment by mattkrick** [comment]
fixed in add-orgs
