### ISSUE TITLE
refactor isTrial on org

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#720]
just thinking aloud here...

currently, isTrial isn't really useful.

if we get a failed payment, we use it to detect if the customer was trialing (ie did not convert) or if their card went bad. We could do this just as easily by seeing if they have a credit card.

we use it in `addBilling` because if it is true, then we extend their period end date. we could use as easily check for the presence of a credit card.

we use it on `UnpaidTeamModalContainer` for a customized message. we could use CC here (or the presence of CC if we don't want to send the last4 or brand to the client).

we use it in `OrgBilling` for the expiredTrialCallout. Again, just check for CC and periodEnd < now.

for reporting (in the future) we can just look at orgs created in the last 30 days that don't have a CC.

we can get away with all of this because we have the constraint that you cannot create your first org with a CC. i think this business logic will stay fixed because no one likes entering their CC to try something. We also say that you can't create a new org without a CC. I think this will stay the same, too.

so, i think we can remove `isTrial` or at the very least make it a computed value of `!creditCard`.

**Comment by ackernaut** [comment]
I like your thinking. So basically when developing we have to check for credit card and the date the org is created etc? Will we keep a constant for the trial period (30 days)?

**Comment by mattkrick** [comment]
you got it! we've got a TRIAL_PERIOD server constant for that

**Comment by jordanh** [comment]
Yes, this seems sounds.
