### ISSUE TITLE
Organizations can be deleted

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#721]
## Enhancement

TK User Story

TK Spec hard or soft delete?

Initial concept for UI: deactivate org and confirm

![me-organization-deactivate-start 2x](https://cloud.githubusercontent.com/assets/307286/23068308/c59afcaa-f4e8-11e6-8380-19441cf991f9.png)

![me-organization-deactivate-confirm 2x](https://cloud.githubusercontent.com/assets/307286/23068307/c59a4a9e-f4e8-11e6-9d4c-fe1f8a66d059.png)

**Estimated effort**: 15 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
- [ ] Remove TRIAL_EXPIRED and TRIAL_EXPIRES_SOON notifications from the org when we delete it.

**Comment by jordanh** [comment]
This is still a thing for sure. One day we'll get to this. I expect a new issue to be opened. Closing as per Icebox.
