### ISSUE TITLE
top notification bar & dash modal overlap

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#724]
not too important, but something that @ackernaut may want to look into. the modal covers up the notification bar. i'd rank this as pretty dang low priority in the current epic. (maybe you were already looking into this per your question about children being aware of notifications?)

![screen shot 2017-02-17 at 6 37 05 pm](https://cloud.githubusercontent.com/assets/5514175/23089594/36a1535c-f540-11e6-8066-bcddf1dbb914.png)

**Comment by ackernaut** [comment]
Yes! I have a fix in the works…
