### ISSUE TITLE
Enter vs Tab 

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#730]
## Issue - Enhancement

Folks tend to hit "Enter" when they're done writing, instead of "tab"...this seems to be too common  a habit from Microsoft/Google/Trello/Slack to ignore

I believe the convention is "Enter" gets you out of the type box, and "OPT+CMD+Enter" (or similar) is the command for a line break

**Comment by ackernaut** [comment]
Yeah, maybe we use `shift + enter` to break lines?

**Comment by mattkrick** [comment]
will this hold true for actions too?

**Comment by ackernaut** [comment]
@mattkrick yeah, I think so—that is how it is already for actions, no?

**Comment by mattkrick** [comment]
in the past, actions were submit-on-enter and projects were newline-on-enter. i think both should probably be submit-on-enter.
