### ISSUE TITLE
"Press <tab> to end" text does not always appear

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#731]
## Issue - Bug

"Press <tab> to end" text does not always appear on outcome card. This was observed during a meeting.

- **Estimated effort:** 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
fixed in add-orgs
