### ISSUE TITLE
Summary information at top of Last Call is confusing

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#732]
## Issue - Enhancement

During a demo on-boarding session, @tayamueller asked the participant, "what do you think this screen is for?" and they responded that they thought it was a meeting summary. Later, the _actual_ meeting summary was given as a "more detailed meeting summary."

I'll offer the following: because the Last Call view shows the number of items processed it feels like the final end to a meeting. Really, we want optimize for the following:

- We want to display how long the meeting has been running, to encourage timeliness (kicking this to #887, Future Epic)

- [x] - We want to invite users to add agenda items if they need anything. Perhaps prompts like:
      * Does anybody else need anything? Anyone still stuck this week? (ships in Upcoming Epic 3 PR)

- **Estimated effort:** 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
I'll give this one to terry, need to see how the timer will look
