### ISSUE TITLE
Design for restricting public templates

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/action#7332]
We would like to restrict some public templates to Pro & Enterprise users. See [Notion doc](https://www.notion.so/parabol/Template-limits-on-starter-plan-limited-number-and-or-limit-sharing-customization-e5231a1dcfa5450a99b2dc5c09480a0a) 🔒 for further context.

![custom-template](https://user-images.githubusercontent.com/39854876/197519614-14e5ed3b-ef67-4338-a246-f9183e39c10c.png)

I suggest that we show an emoji at the right-hand side of the template item. For instance, at the far right of "Mountain Climber", we could show a lock 🔒 for free tier users and an unlock 🔓 emoji for paying users. 

On the template preview on the right side of the modal, we should include text that lets free users know it's a premium template. We could include a sentence of text under "Created by Parabol", for example?

We should also change the CTA button from "Use Template" to "Upgrade Now" and possibly update the colour to differentiate it from templates the user has access to.

### AC

- [ ] Design created that gives the user feedback that a retro template item is a premium template
- [ ] Design includes a sentence in the template preview that explains that it's a premium template
- [ ] The "Use Template" CTA is replaced with an "Upgrade Now" CTA

**Comment by Dschoordsch** [comment]
Just a note on the template icons: These are part of the title and cannot easily be changed for pro/non-pro. Showing additional icons is not a problem.

**Comment by nickoferrall** [comment]
### Design proposal

Public templates all have the "Created by Parabol" subtitle. While it's useful for custom templates in the Organization tab to show who created the template, it's not useful in the Public tab as they're all created by Parabol (see img in this issue's description).

I propose removing that subtitle and adding `Premium Template` if it's a premium template:

![locked-public-temp](https://user-images.githubusercontent.com/39854876/199548694-68dd3e63-ae43-4556-9700-9faa4bfa9809.png)

I considered two alternatives, but I think `Premium Template` is better than `This is a premium template` because it's less wordy, and I prefer the locked emoji next to the subtitle instead of at the far right of the item as it's more obvious to me what the lock emoji relates to:

<details>

![lock-at-end](https://user-images.githubusercontent.com/39854876/199549147-0065a6c7-ba1e-4004-bd63-e98bd2c6b7c8.png)

![locked-public-template](https://user-images.githubusercontent.com/39854876/199549384-292abf7f-f55a-454e-ba9d-5543e705cb70.png)

</details>

For Pro & Enterprise users, we should give them feedback that they're using a premium template, so I went with some sparkles:

![sparkles](https://user-images.githubusercontent.com/39854876/199549619-3dc438c6-e22d-41b1-88ba-dec693744431.png)

I considered the unlock emoji but it's difficult to tell the difference between the lock & unlock emojis:

<details>

![unlock](https://user-images.githubusercontent.com/39854876/199549746-b272e6b3-435d-49b9-890a-c8292b07f478.png)

</details>

On the right-hand side of the template picker, the subtitle lets the user know that it's a premium template. I've changed the colour of the CTA button to green so that it's distinct from the blue "Use Template" CTA. I chose green as I think it's a colour that suggests all is good in life and they should go ahead and click it...


![upgrade](https://user-images.githubusercontent.com/39854876/199550006-9580acdb-1c14-4817-be36-df15a8971e37.png)

For Pro & Enterprise users, they see the sparkles emoji next to the subtitle and the regular "Use Template" CTA:

![upgraded-premium-template](https://user-images.githubusercontent.com/39854876/199549909-fd96626c-9b7d-4891-8f66-68d5a8a892c5.png)

Custom templates will continue to show who created the template & when it was last used.

**Comment by acressall** [comment]
@nickoferrall I like this solution a lot! Especially that you can still see what the template includes. Love the idea of the sparkles emoji for pro/enterprise users!

Can we make the upgrade button the pink/red gradient? I get the concept of the green, but am not sure about 2 things:

- It's the same level of contrast as the blue, so for those with any visual difficulties it may be hard to distinguish
- We're not using the green much anywhere, especially for buttons. We could make a case for adding it if we think it could be used elsewhere, but I don't think we need to. WDYT?

**Comment by nickoferrall** [comment]
> Can we make the upgrade button the pink/red gradient? 

For sure! Choosing pink/red for accessibility & consistency makes a lot of sense to me, thanks!

Maybe this "Upgrade Now" colour?

![image](https://user-images.githubusercontent.com/39854876/199808884-d9a1b142-ef27-42b4-896c-01bb2063239f.png)

**Comment by acressall** [comment]
Yes, looks good! I think this issue is ready for implementation!

**Comment by nickoferrall** [comment]
Great! 🙌  I'll mark this as closed
