### ISSUE TITLE
New team member first meeting project updates welcome state

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#734]
## Issue - Enhancement

When a team member is new and they don't yet have any projects, the empty state of their project update board should say, "welcome new team member, you don't have any projects!"

It could be a portal that stretches across all four columns...

- **Estimated effort:** 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
@jordanh are you thinking something similar to #246

**Comment by jordanh** [comment]
Yes, but special if you are a new team member. Design should give a very "welcome to the team!!!" warm feeling.

This is low priority. I will market it as such.

**Comment by ackernaut** [comment]
Ah, I see!

**Comment by jordanh** [comment]
Iceboxing
