### ISSUE TITLE
permutations on invoice

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#736]
for @ackernaut 
things we need the invoice to account for:

1. Trials (maybe showing $0 charge isn't enough?)
2. Unknown line items fed from stripe
3. starting (and maybe ending?) account balances

![screen shot 2017-02-22 at 3 19 10 pm](https://cloud.githubusercontent.com/assets/5514175/23237488/79ee2c22-f912-11e6-8299-e6e42c2a6c19.png)

**Comment by ackernaut** [comment]
@mattkrick do you have what you need here with my latest commits on #584 ?

**Comment by mattkrick** [comment]
One addition: an invoice could have a failed (or pending) charge. I change the wording, but we may want to make it stand out a bit more. Could you check it out n gimme your thoughts?

**Comment by mattkrick** [comment]
@ackernaut any update on this?

**Comment by ackernaut** [comment]
No change ATM
