### ISSUE TITLE
Navigate to Team Settings, error ensues

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#738]
## Bug 🐛 🐛 🐛 

To reproduce, or not to reproduce:

1. Navigate to a team dashboard
2. Navigate to said Team Settings (see error in console)
3. Navigate back to team dashboard
4. Cannot navigate back to Team Settings (main content does not change)

```[redux-raven-middleware] Reporting error to Sentry: TypeError: (0 , M.default) is not a function```

```Uncaught (in promise) TypeError: (0 , M.default) is not a function```

- **Estimated effort**: 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
I think may be happening on the team where I have pending invites.

**Comment by ackernaut** [comment]
Navigating to and from team settings and other team dashboards is fine when I am on existing teams without invites. When I am on a newer team with pending invites, I have to navigate back to My Dashboard to clear up the routing issue.

**Comment by ackernaut** [comment]
This bug happens locally on `master` branch when inviting a new user to the mock team.

**Comment by mattkrick** [comment]
fixed in the add-orgs branch (now merged) please reopen if you're still getting it!
