### ISSUE TITLE
Beta "Stamp"

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#739]
## Issue - Enhancement

Let's make it publicly/obviously known that the product is under construction (and improving constantly)--I'd love to add a "beta" stamp on our logo at least until we start charging, maybe longer. I'm visualizing a cow brand style, but I'm sure @ackernaut has a more elegant solution :)

**Comment by tayamueller** [comment]
Can this be moved up?

**Comment by jordanh** [comment]
It's still prioritized for Epic 3. We'll get there soon! We gotta get Epic 2 out the door first...

**Comment by ackernaut** [comment]
![screenshot 2017-04-13 10 26 48](https://cloud.githubusercontent.com/assets/307286/25011692/d4a16312-2033-11e7-973c-d8031cac5f3c.png)
