### ISSUE TITLE
Sprint to start meeting

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#74]
## Issue - Enhancement

Placeholder for now, we can work on user flow on Monday.

- **Estimated effort:** 10 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))
- **(Optional) link to mission spec:** ([duplicate and edit template](https://docs.google.com/document/d/1lgTJnJzBt9-4If883iOvthmc0hy-6C6hBF7KNN-lsXU/edit))

**Comment by jordanh** [comment]
May I suggest we move in smaller chunks? I see three issues we could tackle.

First @ackernaut and I can refine what you've just completed:

- [ ] send welcome email formatted with `oy`
- [ ] style `welcome` module layout
- [ ] implement invitation interaction, email address parsing and validation
- [ ] call 'inviteTeamMembers' mutation (not `inviteTeam`)
- [ ] send invitation email formatted with `oy`

While, second, you move on to prep for meetings:

- [ ] implement some strategy for #77 
- [ ] add/remove agenda items on Team dashboard
- [ ] stub in _lobby_ (subscribe to and show socket presence only, no field editing yet)

Then, together we:

- [ ] stub in _team checkin_ (for each team member, answer full present/not attending)
- [ ] stub in _project updates_ (for each team member, list projects {no editing yet})
- [ ] stub in _agenda building_ (get list of items from by `Team`, allow add/remove
- [ ] stub in _agenda processing_ (progress through agenda, no new actions/projects yet)
- [ ] stub in _end meeting_ (allow for last minute agenda ads, else end meeting)
- [ ] stub in _summary_, triggers stub email to be sent to Team on backend, button offered to user to navigate to Team dashboard

For this latter chunk of work, I think we might consider implementing the flow and interactions first in "single-user mode" until we're happy with the queries/mutations for that context. Then, we make it multi-user by layering on the appropriate subscriptions. What do you think?

**Comment by jordanh** [comment]
Moving on to #121

**Comment by jordanh** [comment]
Closed by #114
