### ISSUE TITLE
Organization Leader Easter Egg

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#742]
When looking at the members of an organization, there is a menu that pops open where the leader can do a few certain tasks:
- They can promote someone to a leader (if they aren't one)
- They can demote someone from being a leader (if they already are one)
- They can kick someone out of the org
- They can leave the org (if they aren't the only leader)

However, if they are the only leader, then they can't demote themselves & they can't leave, so what do we do? we could just hide the menu all together, but that looks lame. Easter egg time!

![screen shot 2017-02-24 at 6 15 31 pm](https://cloud.githubusercontent.com/assets/5514175/23327251/9fe7fc3a-fabd-11e6-80ef-9909dbd02696.png)

@tayamueller SHOW ME WHAT YOU GOT

**Comment by jordanh** [comment]
Richard Simmons gif. Duh.

**Comment by ackernaut** [comment]
My first thoughts are to show a tooltip or similar that coaches how to add a second billing leader (can pass along the role) etc. instead of a menu (since there are no menu actions).
