### ISSUE TITLE
Document Testing recipes

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#744]
We're gonna need to write a doc on how to write/run tests for onboarding new employees.
making a list of key points here, we can turn it into a doc later.

- When testing redux:
  - use 'redux-mock-store'
  - use snapshot testing instead of lengthy static objects that are subject to change
- When troubleshooting a test
  - `npm i -g jest-cli`
  - call `test.only` instead of `test` so it is the only one in the suite that runs
  - to run a single file in the test suite, eg ./src/a/b/c/fooDuck.test.js, run `jest fooDuck`

**Comment by mattkrick** [comment]
## TrimSnapshot

The problem: 
- we use snapshot testing because writing a series of 50 expect statements is lame.
- some fields have unique IDs in them
- those UIDs must be unique amongst all concurrently running tests because, for example, if i store a user with ID: '123' in the DB, then it may so happen that 2 tests both act upon that document. 1 may try to delete it, 1 may try to update it. so, we need a unique DB setup for each test.
- we still want to know that those unique IDs have correct references. for example, if i am testing a mutation that adds someone as a billing leader, it will set push their userId to the notification `userIds` field. We wanna make sure it's there

The solution:
- So, what this thing does is grab all the unique IDs in a JSON, makes a library, and replaces them with deterministic IDs (1,2,3, etc). 
- As a best practice, we deploy this strategy on a per-test basis. this is nice because even if we run 2 snapshots in the same test, the eg `orgId` will have the same ID in both snapshots

**Comment by mattkrick** [comment]
## MockDB

Many, many companies mock their entire database when unit testing because the DB is slow. I think that's dumb because that means they aren't really testing their DB queries. So, how do we get the best of both worlds?

The answer is to create the DB we want in memory, then insert that in-memory DB into RethinkDB with a series of concurrent table insertions.
Then, when we test a mutation, we're testing it with real data.

MockDB has a method chaining API. 
For example: 
```
const mockDB = new MockDB();
mockDB.init().newTeam().newUser().org(0, {creditCard: null})
```
Each entity will have 2 corresponding methods:
 - a _new_ method (newUser, newTeam)
 - a selector method (user, team)

Each new method takes 2 args: overrides, templates
Overrides are fields that override the default field. for example, if you want to create a user with a special name it'd be `newUser({preferredName: 'Matt'})`

Templates are syntactic sugar that serve the purpose of reducing imperative calls of overrides.
For example, given the notification type `TRIAL_EXPIRES_SOON` i know that the `userIds` will be every billing leader on the org. I also know the start date will be now + 14 days. The varList will be some function of the entire db.

Each selector method has 2 args: 
- Index to select
- overrides

For example, if i want to flag the first user as inactive, i would call `.user(0, {inactive: true})`.
It's still useful use a selector without an update. for example, if I want to create a new org, then create a new team on the first org, i'd do `mockDB.newOrg().newOrg().org(0).newTeam()`. By calling `org(0)` it sets the context to the first org than was entered into the db.

Since most tests will require an org, users, teamMembers, and a team, there is the shortcut `mockDB.init()` that gives you 8 users on a single team in a single org. 

The data is sent to the database when you `yield` or `await` the call. if you don't need to wait for it, you can call `.run()` If you need the data synchronously before the results are sent to the DB, just access `mockDB.db`. The tables match the actual RethinkDB database tables with the exception that they are camelCase, not PascalCase.

**Comment by mattkrick** [comment]
## Dates

All `new Date()` references are mocked to February 25, 2017.

## Stripe

For the most part, stripe is completely mocked out. This is necessary because stripe is essentially a 2nd database. If we have a mutation that eg gives the user an extra 30 days on their trial, we want to make sure stripe receives that request & updates the user accordingly. a special `stripe.__snapshot()` method is attached to the mocked stripe object. Under the hood, this uses `TrimSnapshot` to make the snapshot deterministic. For space & speed, it only snapshots the methods that have been touched.

## fetchAndTrim

Our initial DB start is created with MockDB. Then, the unit test mutates the DB. Finally, we need fetch the entire contents of the DB, serialize it, make it deterministic, and compare it to the snapshot. That's what this does. you pass in an object where each key is the camelCase value of a table, and a promise to fetch all the docs used in that table. Remember, other tests could be running concurrently, so only take what you need. For each table, there is user-defined list of non-deterministic fields. When it finds those fields, it'll fix their values so it's ready for a snapshot. Since all tables are stored in a single JSON, only 1 snapshot is required no matter how many tables are touched.

**Comment by mattkrick** [comment]
## setTimeout

`jest.useFakeTimers` is full of gotchas. Like. tons.
Many of our graphQL resolve functions call stuff inside a setTimeout to take it off the critical path, and at least one (endMeeting) calls it to move folks to the summary page & then reset the meeting. 
If that setTimeout is put at the beginning of the resole function, before all other `await` calls, then we can do something like this:
```
jest.useFakeTimers();
const promise = resolve();
jest.runTimersToTime(5000);
await promise

// resolve.js
resolve = () => {
  setTimeout(() => {},5000);
  doStuff();
}
```

this is brittle because it must come before all await clauses. That makes sense because if it comes after the first one, the timer is not instantiated yet. While this is the simplest way, it isn't great if whatever is inside that clause is supposed to come after whatever happens in the rest of the function. This could be acceptable in some cases, like analytics where we want to make sure the thing occurred, but most times, we'll need the thing in the setTimeout to have data from `doStuff()`

The second option is
``` 
    jest.useFakeTimers();
    await endMeeting.resolve(undefined, {teamId}, {authToken, socket});
    jest.runTimersToTime(5000);
    jest.useRealTimers();
    await new Promise(res => setTimeout(() => res(), 100))
```
The ending await clause is necessary because we have to wait for whatever is inside that setTimeout to finish (in this case, a hit to the DB, so 100ms is more than enough). This is better than option 1 because now the uncertainty is in the test, not the production code. Still, there is uncertainty, so it's possible that a test could fail (and up to 99ms of unnecessary wait time).

The final option is the "right" way to do it, which is to break it into 2 things & unit test each of them.

```
import * as resetMeeting from 'server/graphql/models/Team/endMeeting/resetMeeting';

const mockFn = resetMeeting.default = jest.fn();
expect(mockFn).toBeCalledWith(teamId);
```
Where `resetMeeting` is a setTimeout wrapped in a promise, we can mock it out of the initial call. Then, if we want, we can write a test specifically for resetMeeting. Jest is still super crappy at handling ES6 imports, which is why we have to `import *` and then replace it with a mock fn, but it should be fastest & most bulletproof.

**Comment by jordanh** [comment]
TODO: make E4E; assign to intern to document
