### ISSUE TITLE
Jest unit tests not failing CircleCI build

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#748]
## Issue - Bug

We want the `npm run test` command to fail our CircleCI build process. It doesn't appear to be doing that presently.

See: https://circleci.com/gh/ParabolInc/action/1893

- **OS:** Linux

**Comment by mattkrick** [comment]
you working on the epic2-unit-tests branch?
If so, i just fixed it.
Jest doesn't support `forceExit` in the config (yet). it only supports it as a CLI arg.
i added it to the test script for the time being. 
the arg is necessary to send the exit signal when the tests finish.

**Comment by mattkrick** [comment]
fixed by adding a teardown script
