### ISSUE TITLE
Build graphQL schemas and tables for meetings

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#75]
## Issue - Enhancement

Entities needed:

- TeamMember Actions
- TeamMember Projects
- Meeting Agenda Items
- Meeting History
- Meeting Changelog
- Participants
- Connections

Items of note:
- I'm pretty sure we'll want the TeamMember Actions/Projects to live off the user profile since the hot queries (user dashboard) will be grabbing all actions/projects for all teams for a given user.
- 1:1 relationships usually aren't great for performance, and since each team can only have 1 meeting, we can combine team/meeting/lobby into 1 DB table (maybe explicitly rename it to `TeamMeeting`), and then break them apart in the GraphQL schema if need be.
- Agenda items is given its own table for now, but we could bring it into `Team` later on depending on how hot queries get.

Proposal:
![new doc 4_1](https://cloud.githubusercontent.com/assets/5514175/16360639/f6e5101a-3b21-11e6-93ce-1b8e4b4066ed.jpg)

This is a predecessor to #74 and https://github.com/mattkrick/cashay/issues/27  

- **Estimated effort:** 3 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Looks like a fine starting proposal. 👍 

With TeamProjects and TeamActions hanging off of the UserProfile, which queries would drive the team dashboard? We'd want to be able to query:

- getProjectsByTeam(teamId)
- getProjectsArchivedProjectsByTeam(teamId)

**Comment by mattkrick** [comment]
That's a good catch!
![Why not both?](http://i.imgur.com/PEI5HHj.png)
- getProjectsByUserId: `r.table('Projects').getAll('userId', {index: 'userId'})`
- getProjectsByTeamId: `r.table('Projects').getAll('teamId', {index: 'teamId'})`
- getArchivedProjectedByTeamId: `r.table('Projects').getAll('teamId', {index: 'teamId'}).filter({status: 'archived'})`

**Comment by jordanh** [comment]
Well, then, just peachy! I think we've got a starting model.
