### ISSUE TITLE
Filter handle alignment regression [Epic 2]

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#755]
## Issue - Bug

There's a little buggy boo with the alignment of dashboard filter handles:

![image](https://cloud.githubusercontent.com/assets/103000/23364598/acf60d92-fccd-11e6-8df8-296012d37b51.png)

- **OS:** OSX
- **Browser:** Chrome

**Comment by mattkrick** [comment]
@ackernaut did you fix this one? on master in development it looks good

**Comment by jordanh** [comment]
Oh, I am still seeing this one on staging:

![image](https://cloud.githubusercontent.com/assets/103000/23780546/96946288-0515-11e7-8bd8-ba05dbd319b1.png)

**Comment by ackernaut** [comment]
Ooh, that pesky bug—I’ll take a gander.

**Comment by mattkrick** [comment]
it's the same css taking precedent in prod issue. fixed!

**Comment by jordanh** [comment]
Rad!

**Comment by ackernaut** [comment]
Pushed a patch for this
