### ISSUE TITLE
Drag-and-drop reordering exception loop [Epic 2]

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#756]
## Issue - Bug

The clients generates a few thousand exceptions when the following steps are taken:

1. Navigate to a team dashboard
1. Activate a filter handle, selecting a single user
1. For a column that has multiple projects, re-order them a few times
1. Observe exceptions:

![image](https://cloud.githubusercontent.com/assets/103000/23364707/2295ac4c-fcce-11e6-88af-67bf1bbe48e5.png)

- **OS:** OSX
- **Browser:** Chrome

**Comment by mattkrick** [comment]
this is gonna be a whole can of worms.
let's close in favor if #533 because the discussion is already there
