### ISSUE TITLE
UserId exposed on notification [Epic2]

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#764]
## Issue - Bug

![image](https://cloud.githubusercontent.com/assets/103000/23438121/a590de58-fdde-11e6-968e-9008c866bd7c.png)

Who's `google-oauth2|104933228229706489335`? Let's use our `preferredName` instead.

- **OS:** OSX
- **Browser:** Chrome
- **Estimated effort:** 1 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
closing in favor of #765. Chased the blame to https://github.com/ParabolInc/action/commit/ce12cc00e9155385aa6d25c8ae70647c972eee4b
