### ISSUE TITLE
Improved invoice panel UI states

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#770]
## Enhancement

My Organization ➡️  Billing ➡️ Invoice (panel)

- [ ] Loading state styled
- [ ] Empty state styled
- [ ] Load more styled

**Estimated effort** 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
We think this might be implemented. Closing!
