### ISSUE TITLE
CircleCI Errors

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#771]
During the `install dependencies` step, i often get:

```
npm info linkStuff yarn@0.21.3
/usr/local/bin/yarnpkg -> /usr/local/lib/node_modules/yarn/bin/yarn.js
npm ERR! Linux 3.13.0-107-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "-g" "yarn"
npm ERR! node v7.6.0
npm ERR! npm  v4.1.2
npm ERR! path /usr/local/bin/yarn
npm ERR! code EEXIST

npm ERR! Refusing to delete /usr/local/bin/yarn: node_modules/npm/bin/npm-cli.js symlink target is not controlled by npm /usr/local
npm ERR! File exists: /usr/local/bin/yarn
npm ERR! Move it away, and try again.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/action/npm-debug.log
Exited with code 1
```

Rebuilding fixes the issue. 

CircleCI v2

**Comment by jordanh** [comment]
We had to stick at yarn v0.16.1 for deployment on dokku, however, v0.21.3 just came out. Let me try it on staging and see if we get better results.

I'm guessing the old version of yarn is causing this trouble.

**Comment by jordanh** [comment]
Ah. Nope, here's why: https://github.com/yarnpkg/yarn/issues/2816

**Comment by jordanh** [comment]
Ah the fun of docker! CircleCI automatically uses the latest Linux container image to do its testing. It started to include `yarn` all by itself. That's where this error was coming from.

I've removed the yarn install from our config, and now all is right with the world. Just merge in the latest `master` to get the goodies...
