### ISSUE TITLE
getAuthedUser has more than 1 instance [Epic2]

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#772]
## Issue - Bug

This error was reported [via Sentry](https://sentry.io/parabol/action-staging/issues/227723326/).

```
getAuthedUser has more than 1 instance.
          For updateUserProfile, please include an 'ops' object in your options
```

It looks like its happening during a user settings update – perhaps during an avatar update.

@ackernaut, I think this might be what you were seeing.

**Comment by ackernaut** [comment]
Yeah, I think that is the one! Thanks for capturing.

**Comment by jordanh** [comment]
This one was my bad.

**Comment by jordanh** [comment]
Ah! Never mind! After updating to `v0.16.1` properly, I still this is still an issue. I believe this is the root cause behind #754

**Comment by mattkrick** [comment]
This is fixed in the dnd branch
