### ISSUE TITLE
Team settings invite validation allows multiple emails

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#780]
## Issue - Bug

This is probably _no bueno_:

![image](https://cloud.githubusercontent.com/assets/103000/23592556/b2ee0ff8-01b7-11e7-9cff-3d14d75ba06f.png)

Repro steps:

1. Go to team settings
1. Type multiple emails into the invitation form, e.g. "moe@prbl.co, larry@prbl.co"
1. Observe!

**Comment by mattkrick** [comment]
oh well that's just amazing. lemme get a bugfix branch up!

**Comment by mattkrick** [comment]
should we allow for multiple entries? or should we throw an error if the regex simple doesn't match the pattern for 1?

**Comment by jordanh** [comment]
Let's start simple and throw and error for now
