### ISSUE TITLE
Where are my archived projects at? [Epic2]

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#782]
## Issue - Bug

While poking around on [staging](https://action-staging.parabol.co), I was doing some testing.

I:

1. Logged in using my Google account
1. Chose me demo team
1. Ran a meeting, creating a new project for myself
1. Archived it
1. Navigated to the archive

And see:

![image](https://cloud.githubusercontent.com/assets/103000/23598013/599e9f46-01ec-11e7-8fe8-6ef053db56bd.png)

Uh, oh! Where are my archived projects at?

I can also reproduce this locally using `npm run dev`.

**Comment by jordanh** [comment]
Ah ha, here's the server exception:

```
Creating a pool connected to localhost:28015
1488779087725 - Origin: Worker (PID 97328)
   [Error] ReqlOpFailedError: Index `teamIdCreatedAt` was not found on table `actionDevelopment.Project` in:
r.table("Project").between(["team123", r.minval], ["team123", r.maxval], {
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    index: "teamIdCreatedAt"
    ^^^^^^^^^^^^^^^^^^^^^^^^
}).filter({
^^^^^^^^^^^
    isArchived: true
    ^^^^^^^^^^^^^^^^
}).pluck(["content", "id", "isArchived", "status", "teamMemberId", "updatedAt"]).changes({
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    includeInitial: true
    ^^^^^^^^^^^^^^^^^^^^
})
```

**Comment by jordanh** [comment]
The exception is fixed (I had to re-add the index by hand because an existing migration was changed), but I still don't see any archived items. There are no client exceptions, no new server exceptions.

When tracing the socket:

![image](https://cloud.githubusercontent.com/assets/103000/23780093/bc7fe7f4-0512-11e7-9787-1a8b7bf0a46b.png)

Looks like the sub goes out, but the server never responds with any archived items...

**Comment by mattkrick** [comment]
this did the trick for me. can you try to cut n paste this?
- `r.db('actionDevelopment')
 .table('Project').indexCreate('teamIdCreatedAt', (row) => [row('teamId'), row('createdAt')])`

**Comment by jordanh** [comment]
Oh yes, that did it just fine! I made a mistake when re-adding the index to staging. I didn't make it a multi-index. Danke!
