### ISSUE TITLE
Itty bitty invoice icon styling bug [Epic2]

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#784]
## Issue - Bug

@ackernaut looks like we have a possibly unstyled icon:

![image](https://cloud.githubusercontent.com/assets/103000/23630031/58fde1b4-026e-11e7-8784-f17d268baa3d.png)

I encountered it on this route: https://action-staging.parabol.co/me/organizations/Sk1mZJ-E9ce

- **OS:** OSX
- **Browser:** Chrome
- **Estimated effort:** 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
this is a load order issue with the font-awesome css. oddly enough, in dev it works, but on prod it breaks. (the fa takes priority over our icon classnames).
i thought that this was determined by class name order, so you put the overrides on the tail end, but apparently this isn't being honored for some reason.

**Comment by jordanh** [comment]
Can we !Important?

**Comment by mattkrick** [comment]
yup, but that's kinda the duct tape approach. good nuff for now i suppose

**Comment by ackernaut** [comment]
In a lot of cases I just write an inline style object for FA icons to override the CSS for certain properties (like `font-size` and `line-height`). I guess I got away with it here because of the order.

`<FontAwesome name="file-text" className={css(styles.fileIcon)} style={iconStyle} />`

**Comment by mattkrick** [comment]
ahhh i was always wondering why you had to do inline overrides. Yeah, that seems more robust
