### ISSUE TITLE
Deleting Team Members

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#786]
## Issue - Bug
[submitted by a user; anonymized by TM]

"I’ve run into a couple issues when working in action and wondering if you can help me out. I’m trying to both delete and add a new member to the [XXX] team. I hit the “Remove” link on [XXX], but nothing is happening. Similarly, when I try to type in a new email address to which to send an invite, nothing appears on the screen."

[see team image in related email]

**Comment by mattkrick** [comment]
should be fixed in master branch, will write unit tests to ensure we don't have a regression soon.

**Comment by jordanh** [comment]
It's been fixed (for awhile)
