### ISSUE TITLE
invoice final touches

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#792]
@ackernaut got a couple final touches on the invoices for ya:
![screen shot 2017-03-09 at 6 25 18 pm](https://cloud.githubusercontent.com/assets/5514175/23779535/d79bb512-04f5-11e7-8b0c-9b4b48437828.png)

this looks a little weird since we don't have any adjustments for last month. should we just nuke that section if it's empty?

![screen shot 2017-03-09 at 6 26 33 pm](https://cloud.githubusercontent.com/assets/5514175/23779550/fa4fe894-04f5-11e7-933c-56d522fc8901.png)
certain things about this list i don't like:
- an upcoming invoice while i'm trialing gives me the heebie jeebies. any good ideas on how we can eloquently say "hey, this is what it'll cost you after your trial runs out, if you wanna keep using us. if not, then you don't pay anything".
- an invoice for $0.00 with a "paid on" line seems weird, can we wordsmith?
- can we make it more obvious that the first invoice is a demo? should we just hide it? i like having _something_ there, but i could go either way.

@tayamueller get in here with those comments

**Comment by ackernaut** [comment]
hey @mattkrick I think I goofed on the bit for previous balance:

https://github.com/ParabolInc/action/blob/master/src/universal/modules/invoice/components/Invoice/Invoice.js#L133

That should be `!==` instead of `===` right?

**Comment by mattkrick** [comment]
oh that looks like it'll do something

**Comment by mattkrick** [comment]
oh nevermind, that handles the starting balance correctly, but the past-month adjustments is something different

**Comment by ackernaut** [comment]
@mattkrick I would like the first invoice they see be the pending amount to be paid after their trial is up—I would hide anything prior.

**Comment by ackernaut** [comment]
We discussed not showing Total and Previous Balance if the previous was $0.00 so I should’ve written `!==` right?

Also, we could hide adjustments if there are not any??

**Comment by ackernaut** [comment]
if starting balance === 0 then I do not need to show Total and Previous, just the Amount Due

so `startingBalance !== 0 && Total, Previous` is the update I would make...I had it backwards whe I wrote it.

**Comment by mattkrick** [comment]
it's a different section. we've got next month, last month, balance+total, and amount due. your logic takes care of balance+total, but i think we may also want to handle hiding "last month", based on separate logic. thoughts?

**Comment by mattkrick** [comment]
1 more issue--

when i add a CC during the trial, i don't get any feedback that the 30 days has been added on to my subscription. the upcoming invoice still has the same month (since we cache that).

- [ ] invalidate old upcoming invoice
- [ ] invalidate orgList
- [ ] maybe highlight the new date? Show X days left?
