### ISSUE TITLE
Card hover/active state gets stuck

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#797]
## Bug

Sometimes the hover/active styles of card content gets stuck. One can interact with other cards and the state remains. To clear the state one must hover on and off the card.

![screenshot 2017-03-11 11 42 52](https://cloud.githubusercontent.com/assets/307286/23825482/1049f210-0650-11e7-8fd4-81f7b4deb963.png)

- **Estimated effort**: 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
wuuuu this is gonna get tricky.

i think what we wanna do is use a function in the setState to mitigate the async nature of setState calls. i'll throw something up & we can try and reproduce, but since success is gonna be based on the 14ms render cycle, it's gonna be tough to test.

**Comment by jordanh** [comment]
Do you have a handle on what's happening? It sounds like it, but I'm still scratching my head. I'm not sure I understand how this sort of bug is possible...

**Comment by ackernaut** [comment]
I’m ok making this the very last bug in the 2.5 epic list in terms of priority, and then we can punt if we want to move on to the next epic.

**Comment by mattkrick** [comment]
ok let's do that, i don't really have a good way to test so i can't be sure if my idea would fix it

**Comment by mattkrick** [comment]
bumping to a future epic until we can figure out a way to reproduce

**Comment by ackernaut** [comment]
I think this is essentially fixed with both latest aesthetic and how we use styles. Closing for now.
