### ISSUE TITLE
Add org name to dash nav items

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#798]
## Enhancement

When folks work with multiple orgs they may need to know which teams belong to which orgs —and it is feasible to have similar names on different orgs “Product” “Engineering” “Marketing” etc.

**ITFWEIB** we may have a good problem and redesign dashboard nav to group teams.

In the meantime, let’s iterate and add a secondary label to the nav items?

If we want to get fancy pants with it we can see if a user is on `> 1` org and then show the org labels, otherwise just show the team name.

Here’s an early concept:

![group 2x](https://cloud.githubusercontent.com/assets/307286/23825525/0406f204-0651-11e7-9960-c87b40e6b87a.png)

**Estimated effort**: 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
@mattkrick if I have the team, then in theory I could get the `orgId` and then the org name?

**Comment by mattkrick** [comment]
yeah, basically i'd copy the subscription that the `newTeam` form uses for its dropdown. we just subscribe to all the orgs that we're a part of. Then, you join on orgId!

**Comment by ackernaut** [comment]
Ok, I'll give that a try!

**Comment by ackernaut** [comment]
@mattkrick where’s a good example of joining based on an id?

**Comment by mattkrick** [comment]
let's say you've got a `team` object and an `organizations` array.

```
const {name} = organizations.find(org => org.id === team.orgId) || {};
```

i usually do the default value because in the land of subscriptions, one might arrive before the other.

**Comment by ackernaut** [comment]
See `dash-nav-with-orgs` branch once we pick this back up

**Comment by jordanh** [comment]
Covered by new designs. Will be implemented soon. Closing as per Icebox.
