### ISSUE TITLE
make circleCI database migrations fail hard

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#799]
check out https://circleci.com/gh/ParabolInc/action/2100
and look at the DB migration step. clearly it failed to migrate, but it "passed" any idea how to make this fail hard @jordanh?

**Comment by jordanh** [comment]
Oh, that's a good one. A real good one. Yes, I think there are some patches others have submitted to `rethink-migrate` we can apply...

I'll have a look.

**Comment by mattkrick** [comment]
yay for owning our own migrate package!

**Comment by jordanh** [comment]
Fixed in 0af636a3
