### ISSUE TITLE
persist + devtool = broken

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#80]
## Issue - Bug

redux-persist works fine, unless we include devtools (either chrome extension or integrated). Rolling back versions of each & both do not help.
stranger still, for master branch it breaks after 2 refreshes. for my current working branch, it breaks after 1 refresh.
normally i'd just forget about it, but devtools is really necessary, and persisting a token for longer than a refresh is also pretty important to the dev experience.

I'm betting this has to do with the fact that `authRehydrate` is a store enhancer and right now, i can't figure out why it isn't just middleware. will write my own middleware & see if it solves the problem.

**Comment by mattkrick** [comment]
90% sure the problem is within redux-devtools. it still breaks with a different local storage package. Digging in, it looks like it's a problem with `replaceReducer`. When we replace the reducer, the liftedReducer is somehow grabbing the initial state & that is overriding the current state. Maybe they're pushing when they should be unshifting? We're among a few small group that uses async `replaceReducer`, so it'd make sense that this bug hasn't been caught yet...

**Comment by mattkrick** [comment]
The problem (thankfully!) wasn't in redux-devtools. It was in how redux-persist enhances the reducer. redux-persist uses a store enhancer to create a reducer enhancer, but it doesn't supply a lifted reducer, so when you call `replaceReducer`, it doesn't include the reducerEnhancer.

Personally, I don't agree with using a lower-than-necessary API (storeEnhancer), so I went with one that used a reducerEnhancer (redux-storage). It works a little differently, some good stuff, some bad.

- I like how it returns a promise instead of using a callback.
- I also like how it uses middleware instead of a subscriber to write to the persisted state. I think this makes more sense.
- I  also like how it keeps everything in 1 localStorage key/value, since a given action can mutate the entire state, anyways (thanks to middleware). I think this will be more performant.
- I don't like that redux-form calls an action to close a form when you exit the page. By triggering an action, the current state gets persisted, which makes it comically difficult to manually delete an `authToken` for debugging. A workaround is to crash the browser so redux can't fire another action.

Will submit a fix shortly so we can move on to bigger & better.

**Comment by jordanh** [comment]
👍 ⚡ ⚡ ⚡ 

You know you can disable `redux-form` from dispatching that destroy action right?

For example:

```javascript
export default reduxForm({
  form: 'welcomeWizard',
  destroyOnUnmount: false,
})(Step2TeamName);
```

**Comment by mattkrick** [comment]
oh whao, that's nice! i guess i got some reading to do

**Comment by jordanh** [comment]
I am having a love affair with `redux-form`.
