### ISSUE TITLE
Capturing Emails

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#802]
## Issue - Enhancement

Connect MailChimp to ensure capture of all Action user signup emails

**Comment by ndey96** [comment]
@jordanh Do you think this would be a good candidate for the internship epic?

**Comment by jordanh** [comment]
@ndey96 we've got this one! It can be done through marketing automation vs. code.

**Comment by jordanh** [comment]
@tayamueller do you want these emails to be captured as a separate list in Mailchimp? If so, what would you want this list called?

**Comment by tayamueller** [comment]
"Active Users"...?

**Comment by jordanh** [comment]
Duplicate of #854
