### ISSUE TITLE
Notification Icon Color

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#803]
## Issue - Enhancement

The circled number indicating unread notifications is usually red--lessmakeit our hot pink

**Comment by jordanh** [comment]
We'll look at this one.

**Comment by ackernaut** [comment]
Our notification badge is using the hot pink palette color:

![dashboard components 2x](https://cloud.githubusercontent.com/assets/307286/23862351/c4ca8660-07da-11e7-8f07-b95cf928567d.png)
