### ISSUE TITLE
verify users are safe from their own markdown links

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#812]
source: https://mathiasbynens.github.io/rel-noopener/

i want to make sure that the malicious page doesn't have access to our window object because that's where localStorage lives. This seems like a crazy huge/obvious attack vector so i can't believe it would actually apply...

**Comment by mattkrick** [comment]
hey the markdown package does it safely. yay!

**Comment by jordanh** [comment]
W00t
