### ISSUE TITLE
refactor Button to not use style

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#813]
@ackernaut some good parts in the lint:
we currently have a Button component that takes a prop called `style` (flat, raised, etc).
we probably should rename that because there already exists a `style` that takes an object.
any ideas on the name we should change it to?

**Comment by ackernaut** [comment]
Ah, good catch. How about:

- `type`
- `buttonType`
- `buttonStyle`
- `uiStyle`

**Comment by mattkrick** [comment]
type it is!

**Comment by mattkrick** [comment]
er, that was taken too, going with buttonStyle
