### ISSUE TITLE
Support multi-tab logout

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#815]
i think a race condition exists when 2 tabs are open & you go to log out. 

Tab A: Nuke the state!
Tab B: huh, something changed, better persist the state (including the old auth token)
Tab A: I'm logged...in?

**Comment by jordanh** [comment]
Good find. What do you think we need? Publish a message from the backend?

**Comment by mattkrick** [comment]
since this only happens given a particular client state, i'd like to solve it on the client. 

oh the joys of not having a single source of truth!

we could put a watcher on localStorage, or before persisting data we could see if the localStorage value !== the state value.

**Comment by jordanh** [comment]
Tackle after switch to relay modern?

**Comment by jordanh** [comment]
@mattkrick:

> this will be fixed for free when we take auth out of redux.

Requested a new issue with that AC. Closing this one for now as per Icebox.
