### ISSUE TITLE
highlighted team no worky

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#818]
this guy again (chrome canary):
![screen shot 2017-03-14 at 6 01 18 pm](https://cloud.githubusercontent.com/assets/5514175/23929014/5ac6c5ce-08e0-11e7-9036-cb71a44a0357.png)

**Comment by mattkrick** [comment]
hey @ackernaut i tracked this down to `src/universal/styles/helpers/makeHoverFocus.js`. naive style question, why do we need to do this for `:focus`?

**Comment by mattkrick** [comment]
fixed. router.isActive needs the react-redux mSTP above it to be impure.

**Comment by ackernaut** [comment]
Hey @mattkrick I like making those anchors since they are navigation, and one can `tab` through those jokers:

**record.it**
[link](http://recordit.co/QYTCmga1vJ)
[gif](http://g.recordit.co/QYTCmga1vJ.gif)

**Comment by ackernaut** [comment]
So, I make hover/focus have the same styles**
