### ISSUE TITLE
Update server-side segment events with metadata

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#819]
## Issue - Enhancement

It'd be super nice to be able to see segment-triggered webhooks like our Slack webhook contain user identity data. Let's update all server-side segment events to send this meta-data using a helper function.

Challenge: avoiding a DB hit upon each segment event

On the client, sending the identity metadata is easy. It's always just sitting around in the redux store. On the server, it's more difficult: the identity metadata isn't just sitting around anywhere. All we have is the token. We could keep an in-memory cache and fetch the identity data if the cache doesn't hit. However, without using something like memcached or redis, the cache would be uneven across nodejs processes.

- **Estimated effort:** 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
correct me if i'm wrong, but the metadata is sitting on the segment server when we call `identify`. Then, when we wanna hit them again with a `track` we just grab their userId from the authToken & pass along any additional context. At least that is my naive understanding of the premise, what am i missing?

**Comment by jordanh** [comment]
Your understanding is correct. Except, some things about segment seem to stink.

We use segments Slack webhook integration to send messages to our Slack instance. The webhook only contains the metadata provided on the track call. Why oh why they would make it work that way, I have no idea. But to our user (us and @tayamueller) we see a lot of empty messages.

**Comment by mattkrick** [comment]
- [ ] add re-identify logic to updateUser mutation
- [ ] write an IntranetJob to re-identify all users on segment

**Comment by jordanh** [comment]
Closed via #849
