### ISSUE TITLE
Add CC conversion events to segment

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#820]
## Issue - Enhancement

Let's track more of the user conversion funnel.

1. When a user clicks on a trial conversion modal
1. When a user clicks to add their CC info
1. Whan a user successfully adds their CC info

Any other events I should consider?

- **Estimated effort:** 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
Should we capture when a card is declined or an organization goes into unpaid state? Might be a good, direct customer service opportunity that doesn’t scale well later on.
