### ISSUE TITLE
Organizations Visible to Non-Billing leaders

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#822]
## Issue - Enhancement

Make sure all team members can see their Orgs in the upper left, even if they're not Billing Leader

**Comment by mattkrick** [comment]
why? what's the use case? gimme a user story! paint me a picture!

**Comment by jordanh** [comment]
When I belong to multiple organizations, I want to know which organizations I belong to and who the members of the organization are,

...so that I know who else belongs to the organization and what my privileges are within it.
...so that I know who the admin is.

**Comment by jordanh** [comment]
Dup of #1694
