### ISSUE TITLE
Editing/Cursor Bug

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#824]
## Issue - Bug

When trying to edit copy inside a completed card, cursor keeps moving to the bottom of the card after typing each letter.

**Comment by ackernaut** [comment]
Ooh this one is funky. Also, it seems that Markdown isn’t working properly (and may be the underlying issue)?

**Comment by ackernaut** [comment]
Nope, Markdown seems to be working fine. I just had reverse order for the `[]()` for a link, ha!

**Comment by ackernaut** [comment]
But I am experiencing the issue where the cursor jumps to the end after each edit.

**Comment by mattkrick** [comment]
https://github.com/erikras/redux-form/issues/2049

**Comment by jordanh** [comment]
Wow. What a crazy, crazy set of interactions. A strange workaround you found there too ;) I bet others will find that interesting.

I'll be fun to watch the community figure out just what the true root cause is!

Who knows, maybe its a browser bug?
