### ISSUE TITLE
Short URL implemented

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#827]
## Enhancement

Hey there, didn’t we register `prbl.io`? Let’s shorten our meeting lobby links!

**Estimated effort**: 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Hey there @ackernaut – I took a moment and configured the domain. Can you please verify that it seems to work as you expect?

**Comment by ackernaut** [comment]
Yep, @jordanh seems that `prbl.io/path/path/` will redirect to `action.parabol.co/path/path/` —which is a good start…

**Comment by jordanh** [comment]
prbl.io has been registered, configured, and is active. We just need to put it in the product. Requested @ackernaut open a new issue with finer AC. Closing this one for now based on Icebox policy.
