### ISSUE TITLE
New facilitator election on disconnect not working [Epic2.5]

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#828]
## Issue - Bug

Expectation: when a facilitator disconnects, a new facilitator is elected from among connected clients

Repro:

1. Start a meeting with 2 people
2. Proceed to Updates phase (for funsies)
3. Close facilitator browser window

**Comment by mattkrick** [comment]
oh this was interesting.
it was a remnant from the `@cached` thing where the entity still existed even though it was removed from the subscription. guess using `@cached` as a filtering mechanism is a bad practice if we can't guarantee that the entities are not stale 😞
