### ISSUE TITLE
Terms of service

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#829]
## Enhancement

When signing up for Action, users need a view where they can see and agree to terms of service (before being redirected to the dashboard or welcome workflow), so that they can become an active user of the product.

- [ ] Needs first shippable terms of service
- [ ] Needs layout and controls for viewing and accepting
- [ ] The view needs to show after the auth0 modal and before the dashboard (invited team members) or before the welcome workflow (new users creating a first team)

**Estimated effort**: 15 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Obviously still very much a need. However, not gating the business in any way. Let's re-open as funding allows—we should spend some lawyer time on reviewing a draft.

Closing as per Icebox.
