### ISSUE TITLE
Transfer teams to other organizations

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#830]
## UX Enhancement

When users create a team that ends up on their own organization, they need the ability to transfer it to another organization so that the other organization can assume responsibility for managing users and billing.

**Estimated effort**: 15 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Still a good idea. Will have to do one day. Closing as per Icebox.
