### ISSUE TITLE
Glassfrog/Holacracy SEO Optimizations

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#838]
## Issue - Enhancement

SEO to attract Holacracy consultants. Design TODO.

- **Estimated effort:** 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
![screen shot 2017-03-21 at 12 43 46 pm](https://cloud.githubusercontent.com/assets/5514175/24167469/18ed8828-0e34-11e7-9acb-413b5a11645f.png)

No "Try Now"? if google doesn't know we're a SaaS, I'm betting we aren't being categorized as well as we should be

**Comment by jordanh** [comment]
Quite possibly. Background for others: 
![image](https://cloud.githubusercontent.com/assets/103000/24294683/eea10afe-106d-11e7-98cc-f35119a54782.png)

**Comment by mattkrick** [comment]
closing as there's nothing to do on this front yet
