### ISSUE TITLE
Reorder column components in dash views

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#840]
## Issue - Enhancement

Our current column ordering causes much mental friction with folks who've used Kanban systems before. This user feedback is so frequent, this is probably the right time to address it.

On **My Dashboard** and **Team Dashboards** change the ordering to (from left to right):

1. Future
2. Stuck
3. Active
4. Done

- **Estimated effort:** 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
i'll take the E4E points on this one, please :wink:

**Comment by jordanh** [comment]
Ha! Nice work!! 😉 

Some interesting responses on this Twitter thread: https://twitter.com/jrhusney/status/844273370028036096

Don't mean to be fickle. But I'd like to clarify this task.

Dashboard view:

1. Future
1. Active
1. Stuck
1. Done

Meeting view (the reverse):

1. Done
1. Stuck
1. Active
1. Done

**Comment by mattkrick** [comment]
why would they be different? if you log into your dashboard every day & see future on the left & then you have a meeting, wouldn't you expect to see future to be on the left?

**Comment by jordanh** [comment]
It's to encourage an order for how to communicate: start with what you did, then talk about where you are stuck, what you're working on this week, and what's coming up.

Or, we can choose to not do it that way...but I'd like to try it. :)
