### ISSUE TITLE
Collapsable meeting agenda list 

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#841]
## Issue - Enhancement

Let's recover some real estate and make that agenda list collapsable.

- **Estimated effort:** 15 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
by default?
how is the state stored: 
by user? 
by team? 
by session?

**Comment by jordanh** [comment]
Good Qs!

Not by default – let's allow folks to see that it's there.
State is stored by user.

**Comment by mattkrick** [comment]
to confirm-- by user or by team member?
for example, if i collapse for Team A, does that collapse for Team B?
and you want this to persist when i log back in?
can i collapse while in-meeting?

**Comment by jordanh** [comment]
More good Qs.

By Team Member. Yes, let's make it persist.

No, you cannot collapse while within a meeting. It's only for the team dashboards to recover some Kanban breathing room.

**Comment by mattkrick** [comment]
whatcha mean by breathing room? you wanna make the cards wider?

**Comment by jordanh** [comment]
That's right
