### ISSUE TITLE
Project card metadata schema updates

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#844]
## Issue - Enhancement

This may change a bit, but in order to support integrations. Let's add:

- [ ] Due Date
- [ ] Stuck on
   * Consists of a type `PROJECT` or `TEAMMEMBER`
   * `PROJECT` another Project's id
   * `TEAMMEMBER` a team member id, in the future we can trigger a notification
- [ ] Read-only flag (for one-way sync) 
   * Can only change prioritization, not status
- [ ] Title
- [ ] Tags

Migrations

* Existing card content -> title

- **Estimated effort:** 15 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
SO many questions here:

How do you CRUD a due date?
How do you keep this fun while adding due dates?
Does a due date apply to every status? 
Do cards in future have a due date as well as a dontShowBefore date?
When a due date is provided, how does the Project behave differently?

When a project is stuck on something, how does it behave differently?
Where does the predecessor show up?
How can you change the stuckon value?
What happens if the team member it's stuckOn goes inactive or is removed from the team?
Do you want to check for circular logic? eg A -> B -> C -> A Is invalid. Do we allow that? Is explaining that to the user suck the fun out of it?

Aside from integration, is there any other reason to go read-only? (We could just check if the card is from an integration)

What's title? 
How's it different from content? 
Does it have markdown?

How do you CRUD tags? Are we cloning trello?

**Comment by jordanh** [comment]
So many thoughts. Few definitive answers. I think we should design this UX first before we implement and test with folks.

The questions are _so_ helpful thought.

> How do you CRUD a due date?

Read-only cards: no UD. Otherwise, just like Trello. Click, change arbitrarily.

> How do you keep this fun while adding due dates?

This is a good question. I think by not calling them due dates, for one. We may have to start by digging deeper. What kind of dates are out there? What are they used for? Off the top of my head I can think of a few contexts:

- When I want to re-evaluate something...
- When I want to keep track of an unmovable deadline...
- When I want to indicate relative priority...
- When I want to indicate temporal dependence (project A must happen before project B)...
- And more...

Not all of these contexts are valid for our product. The one most interesting to me is the one at the top of this list.

> Does a due date apply to every status?

Most certainly not!

> Do cards in future have a due date as well as a dontShowBefore date?

Is possible, my hunch is that there is only one date. When in the future column the date means "show this to me again on date X." But, that's just a guess.

> When a due date is provided, how does the Project behave differently?

It displays it. In the future, it might do other stuff.

> When a project is stuck on something, how does it behave differently?

It also displays who it's stuck on. In the future, we may generate notifications/emails. And or, include this information in a _Ship_ report.

> Where does the predecessor show up?

I'm thinking we could provide a search syntax that would reveal all projects related to a certain card. We could provide some control on the card (or something like a long click/press) to focus on all predecessors and descendants.

> How can you change the stuck on value?

I'm not sure yet. I'm imagining some sort of inline control.

> What happens if the team member it's stuckOn goes inactive or is removed from the team?

We'll reassign to the team lead.

> Do you want to check for circular logic? eg A -> B -> C -> A Is invalid. Do we allow that? Is explaining that to the user suck the fun out of it?

Or does it add fun? Like, "you've just tied an impossible knot!"

I don't think we worry about it for now :)

> Aside from integration, is there any other reason to go read-only? (We could just check if the card is from an integration)

I don't think so... not that I can see yet.

> What's title?

A content limited region that allows for multiple cards to fit within a viewport. It's required content.

> How's it different from content?

Content can be super long. Like the first message in a GitHub issue.

> Does it have markdown?

Both have markdown, I think that's safe to try.

> How do you CRUD tags? Are we cloning trello?

Have a look at TroopWork. I'd like your feedback there...

**Comment by jordanh** [comment]
Closing this for now, as we'll catch many of these changes when we more deeply consider integrations
