### ISSUE TITLE
"Friday" ship

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#845]
## Issue - Enhancement

We might push this out to a future epic. However, I suspect this might be a way to drive up utility and engagement which is something we definitely want to do!

JTBD:

- When team members want to get a sense of team momentum, they want an opt-in email communication, so that they can see what changed
- When a team leader wants to enable this, they want a control in team settings, so that they can turn it on and off
- When a team leader wants to change the interval on ships, they want to change a setting like "send my every X weeks on Y day of week at Z o'clock", so that they can allow enough time for the updates to be meaningful

Tasks:

- [ ] Design settings panel
- [ ] Design email template
- [ ] Write query to compare between current time and historical interval
- [ ] Wire it all up
- [ ] Create cron task to fire hourly

- **Estimated effort:** 23 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
This is an epic!

**Comment by jordanh** [comment]
How right you are!

**Comment by ackernaut** [comment]
I like the idea of having a setting to throttle and send out the project change log to subscribers. A secondary enhancement (comes later, improvement) that I can envision:
- A visualization at the top of a Team Insights view that shows a positive/negative bar per status (Done, Stuck, Active, Future) kind of like this: [https://github.com/ParabolInc/action/graphs/code-frequency](https://github.com/ParabolInc/action/graphs/code-frequency) or something visually interesting
- An history index of ship emails that were sent out that open to browser view?

**Comment by jordanh** [comment]
Capturing more JTBD from our S.P.A.:

> When my team works for a configurable period of time, I want to understand at both a high-level (via summarization) and the details of what's changed (status & content), so that I can understand where my team is at.

> When I'm preparing a Friday Ship or quarterly report for my managers or stakeholders, I want to be able to query across a specific time range and annotate it, so that I can share helpful quant (status) and qual (narrative) information

**Comment by jordanh** [comment]
Scope this down to a report email on

- [ ] what's got done
- [ ] what's stuck

And perhaps surface some cleaver (simple) insights such as:

- [ ] what project has been open the longest (suggest: "break this into a smaller next step?")
- [ ] what's been stuck the longest (suggest: "add an agenda item?")
- [ ] statistical insights (project stats this week / last week / active users meybe?)

etc.

**Comment by jordanh** [comment]
We can totes Icebox this one.
