### ISSUE TITLE
TypeError: r.createdAt.getTime is not a function

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#850]
## Issue - Bug

This is all me. It may be that not all users have a `createdAt` field. I'm going to look into it...

![image](https://cloud.githubusercontent.com/assets/103000/24201599/f1cdeab8-0ee6-11e7-9246-a22ca2cc725a.png)

**Comment by mattkrick** [comment]
did that hotfix close this?

**Comment by jordanh** [comment]
Yep yep! Fixed in `v0.16.11`. Closing...

**Comment by mattkrick** [comment]
found this, fixing it on the agenda branch coming up...

**Comment by jordanh** [comment]
Oh awesome. Thx.

**Comment by jordanh** [comment]
Closed again by #851
