### ISSUE TITLE
MailChimp API integration

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#854]
## Issue - Enhancement

Soooooooooo, I discovered that the Segment integration to MailChimp – although extremely fast, easy, and automatic to set up – will cost us $100 bucks a month to use (it's a premium integration).

Rather than put this on the critical path for us – or ponying up to the $100/mo right now – let's make this an Equity for Effort/internship project. It should be real quick. Almost as fast as me creating this here issue.

It:
- [ ] should extend `.env.example` with a new environment variable `MAILCHIMP_API_KEY` and `MAILCHIMP_LIST_ID`
- [ ] should use the user's email as its primary key for interfacing with mailchimp
- [ ] should keep the list identified by `MAILCHIMP_LIST_ID` in sync in the server code anyplace we call `segment.identify` today
- [ ] should update the user's email and preferred name
- [ ] should also contain a migration for synchronizing existing users in the database to MailChimp

Whoever picks this up should create their own MailChimp account in order to demonstrate that it works.

- **Estimated effort:** 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
@ndey96 I was thinking of you for this, if you'd be down

**Comment by jordanh** [comment]
If anybody else is interested on bidding on this one, let us know! Just say, "I'll do it for X points."

**Comment by ndey96** [comment]
@jordanh I'll take this on next :)

**Comment by jordanh** [comment]
@ndey96 if you don't mind, I'd like to save this one for a batting practice for one of the folks you referred over to us :)

**Comment by elliotCooper** [comment]
@jordanh I'll take up your suggestion and get to work on this

**Comment by jordanh** [comment]
Ok @elliotCooper, it's all yours. Go ahead and do it!

**Comment by jordanh** [comment]
@elliotCooper no longer has time to complete this issue, so it is once again up for grabs!

**Comment by burin** [comment]
I had to do some reading to build up some context to understand what "Segment integration to MailChimp" meant for me. I knew what each piece was on its own, but was unclear how they all would play together. 

Here's what I learned! It might help someone else understand too. 

#### Basic Context

- Parabol uses Segment to track events. 

- Segment is a service that lets you push events/info to, and from there they push data to different apps/services through their integrations that you can configure. They act as a hub for analytics.

- MailChimp is a service that lets you manage mailing lists and send out emails.

#### How it all fits together:

Segment provides an integration with MailChimp that would allow Parabol events and user info to flow to MailChimp through Segment.

`Parabol -> Segment -> MailChimp`

#### After integration, these are the things you'd notice:

MailChimp mailing lists get automatically updated as folks use Parabol (adding MailChimp users)

MailChimp user info is updated given Parabol user info, if they already exist in MailChimp (perhaps  we had an email in MailChimp from another channel but not first/last name)

#### Things this integration isn't (these probably are "duh" for everyone, but I didn't know!)

- Triggering emails to be sent from MailChimp upon some event happening in Parabol

More info:

https://segment.com/docs/destinations/mailchimp/

**Comment by mattkrick** [comment]
Hey Burin, looks like your understanding is spot on!
The best example I can think of is we add a sweet new feature and we wanna tell all our users about it.
To do that today, we'd have to query our DB, grab all the active users, go into mailchimp, make a new list, copy n paste, bleh.

It'd be so much easier to simply:
- copy all that stuff from our data into a new mailchimp list 
- add to that list whenever a new user signs up
- edit a user whenever they change their name

**Comment by jordanh** [comment]
Re-reading my own issue, I'm not sure if it the main idea was clear. This _isn't_ an issue to integrated Segment.io with MailChimp, it's to integrate our server backend directly with MailChimp's API.

The core issue is we _don't_ want to have to pay Segment, yet ;)

**Comment by burin** [comment]
@jordanh it's all coming together now!

So really this is `Parabol -> MailChimp`, but using the Segment integration feature set as inspiration.

Another question on the integration:

What's your philosophy on bringing in API wrappers? There are a couple node.js MailChimp API wrappers we could use to validate the overall approach real quick, then if we don't want to bring in more dependencies, we could go lower level and rip out the wrapper before merging.

For this pass we only need to use 1-2 API endpoints, so there's less of a reason to bring in the API wrapper, but bringing it in now could reduce friction for integrating more interesting features later, if this provides value.

I don't really feel strongly for or against API wrappers, but I know there are strong opinions out there for both sides. Just trying to get a sense for what it means for this app.

**Comment by mattkrick** [comment]
hey @burin go for the wrapper. As long as they're popular & make the code cleaner, I'm all for it.

**Comment by jordanh** [comment]
We've moved away from Mailchimp. Closing.
