### ISSUE TITLE
TypeError: undefined is not an object (evaluating '__gCrWeb.autofill.extractForms')

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#856]
## Bug
https://sentry.io/parabol/action-staging/issues/242104676/

```
TypeError: undefined is not an object (evaluating '__gCrWeb.autofill.extractForms')
  at global code (/:1:85)
```

**Comment by jordanh** [comment]
This is a strange one. I'm not even sure where it is coming from! Looks like it happened when an iPad user clicked "Get Started"

**Comment by mattkrick** [comment]
chrome bug! https://bugs.chromium.org/p/chromium/issues/detail?id=590375

will close for now as there ain't nothin we can do
