### ISSUE TITLE
Show organization name in meeting sidebar header

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#862]
## Enhancement

When a user is meeting with her team, she wants to see both the team name and the organization name so that context switching is less of a cognitive burden, and she can be fully present.

**Estimated effort** 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
👾

**Comment by jordanh** [comment]
Delaying this work for a future UI redesign of larger scope
