### ISSUE TITLE
Jira fields not showing in Sprint Poker

### ISSUE THREAD

**Issue by gcrickman** [ParabolInc/action#8622]
## Issue - Bug

An Enterprise [user](https://app.hubspot.com/contacts/3888472/record/0-1/138810801) 🔒 isn't seeing fields configured in Jira during a Sprint Poker meeting.

> Hello,
> I do not see all the JIRA fields in sprint poker estimation. I can only see story points, although other fields like T-shirt size are added to the screen in project settings. Could you please guide me on how I can bring in fields to update through parabol.

> I recently added T-Shirt size field to the screen on jira. But none of the older fields are showing up either. Only “Story points” field is currently showing in sprint poker.

Link to [Slack thread](https://parabol.slack.com/archives/C4JAUUZ9P/p1690811119847579)

**Comment by mwermuth** [comment]
Looked at during backlog grooming.

@gcrickman can you ask them which type the new T-Shirt size field is? We only support text and number types, not custom enum types.

**Comment by mwermuth** [comment]
@gcrickman we checked the ticket and there wasn't any response. So we are closing this for now. Should they respond we can open it back up.
