### ISSUE TITLE
Add panel UI to team members (like organization members)

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#864]
## Enhancement

Organization settings were designed after team settings. Organization members are grouped in a panel. Team members and invite can probably be grouped in a panel, too. Note: the team settings will have a panel for the Danger Zone (Archive Team) once that ships.

- [ ] The team members panel needs to retain some type of scroll-ability in case the list of team members gets long (which we discourage, but you know). Currently, the list scrolls once it reaches the bottom of the viewport, without scrolling the whole viewport.

**Estimated effort** 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
I wonder if this couldn't be a good E4E project if we gave a couple of screenshots?

**Comment by ackernaut** [comment]
I like that idea, I’ll work up a screenshot and write some specs, then we can kick it over.

**Comment by ackernaut** [comment]
Easiest way to show was to just do it:

![screenshot 2017-04-13 16 22 24](https://cloud.githubusercontent.com/assets/307286/25024877/6a880184-2065-11e7-8174-487350883191.png)
