### ISSUE TITLE
Free Trial Date Notification Bug

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#866]
## Issue - Bug

 My trial shouldn't expire until April 12 (today is March 30)

![untitled](https://cloud.githubusercontent.com/assets/14892189/24517766/7f4f6328-154d-11e7-913f-babf313262a2.jpeg)

**Comment by jordanh** [comment]
This looks like a bug, it should say "in XX days," but evidently the date is off. Do we have a bug in the migration @mattkrick?

**Comment by mattkrick** [comment]
oh dang, just seeing this, lemme dig in

**Comment by mattkrick** [comment]
the data is correct in the DB (yay no hard fix!). The problem is the `fromNow` function doesn't work with future dates anymore, lemme fix that up...

**Comment by mattkrick** [comment]
oh shoot, i meant to create a hotfix branch 🙈 . ah well. fixed!
