### ISSUE TITLE
Free Trial Date Copy Change

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#867]
## Issue - Enhancement

Syntax off:
![untitled](https://cloud.githubusercontent.com/assets/14892189/24517781/8fb9b218-154d-11e7-89b4-d8c8e7c8bb1d.jpeg)

Suggestion:

"Your free trial [will expire in XX days]. Want another...."
OR
"Your free trial [has expired]. Want another..."

(include "will expire in" to the variable bit)

**Comment by jordanh** [comment]
This looks like a bug, it should say "in XX days," but evidently the date is off. Do we have a bug in the migration @mattkrick?
