### ISSUE TITLE
Agenda Formatting: Single-User

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#868]
## Issue - Bug

from user:

"I'm continuing to use Action for weekly tactical meetings with a client and bumped into a glitch today. I’m not sure if it’s user error or not. Here’s what happened:
- I was facilitating and the only one logged in. 
- I entered 8 agenda items
- After processing an item, capturing a project or action, I clicked “Next Agenda Item”
- After processing each item, I noticed that the completed items were not being crossed out. (See screenshot)
- When I finished the last item, it DID become crossed out
- After clicking “Wrap-up the meeting," it appears that output from all but the last agenda items were not captured into the system. (See screen shot. I haven’t closed it out yet, because I’m afraid I’m going to loose all the new projects I captured in the meeting.

[screen shot omitted for user/client privacy; see email thread]

**Comment by jordanh** [comment]
Ah ha! After some fiddling around I have clear reproduction steps for this one. It was a "nice find" by our user.

Repro steps:

1. Start a meeting with only a single participant, you, the Facilitator
2. Advance the meeting all the way to Last Call
3. Add 3 agenda items, click on the first item
4. Process the item and adavance to the next
5. Observe bug!
