### ISSUE TITLE
User preferred name persists in local client?

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#869]
## Issue - Bug

I use multiple “People” user profiles in Google Chrome.

In my profile for Parabol, I updated my preferred name (on Action, production environment) and it shows up the same (“Terry 👻”) in both the user hub (top left) and in the card footer.

In another profile, I am logged into production but did not make any change to preferred name. My user hub shows the older name (“Terry 👾”) and the card shows the new name “Terry 👻”.

(Pictures or it didn’t happen === POIDH)

![screenshot 2017-03-31 14 32 13](https://cloud.githubusercontent.com/assets/307286/24566504/601b9094-161f-11e7-913b-dfcaf7033ef8.png)

![screenshot 2017-03-31 14 32 20](https://cloud.githubusercontent.com/assets/307286/24566579/9bf2bf48-161f-11e7-8235-4470e0d29843.png)

**Estimated effort**: 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
i don't know chrome profiles very well. do they share the same localStorage? if so, we can't fix this...

**Comment by jordanh** [comment]
No, they don't share the same localStorage context. It's a completely different localStorage. I think this may be an `@cache` issue...

**Comment by jordanh** [comment]
Can we triage this now, and if it is too much to fix quickly prioritize it for the future?
