### ISSUE TITLE
Desktop notifications

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#872]
Pop up stuff even when the website aint open.
Push notifications wooooo

**Comment by jordanh** [comment]
From S.P.A.:

> I want optional desktop push notifications so I don't need to keep the tab open b/c I live on github, not Action

**Comment by jordanh** [comment]
Generally speaking, I think this JTBD is a refinement on the above:

> When I am working outside of Parabol, I want to be notified by Action on my preferred channel, so that I don't have to keep polling the Parabol interface

And:

> When I want to be notified by Parabol, I want a configurable checklist of notification channels including Email, Slack, as well as Desktop notifications, so that I can be sure to see important information on my channel of preference

For me, for example, this would be Slack.

**Comment by jordanh** [comment]
Iceboxing
