### ISSUE TITLE
Check-In Round Attendance vs Forwarding

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#877]
## Issue - Enhancement

Even our most seasoned users continue to blow past the Present/Not Present prompt, going directly to the "Next teammate (press enter) ->" option

So: "attendance" may not be useful data. Consider getting rid of this "feature"

IF we keep it, here's a suggested visual rejigger of this view from top-bottom:

1) [line of avatars]
2) question prompt
3) delete 2nd avatar (this is redundant; force the eye to #1 which is permanent anyway--might help with the "who's the facilitator" problem, too)
4) delete box
5) make "p" and "n" a) capitalized b) teal green vs pink
6) change language:

[Present]        > move to Matt
[Not Present] > skip to Matt

7) delete "Next teammate (press enter) ->"

![untitled](https://cloud.githubusercontent.com/assets/14892189/24668551/4c69f766-1935-11e7-87bf-0d754b10657c.jpeg)

**Comment by ackernaut** [comment]
Ah, we have a very similar line of thinking @tayamueller check out the latest WIP that I pushed here: #876

**Comment by ackernaut** [comment]
Closed via #876
