### ISSUE TITLE
"Archive" Team vs. "Delete" Team

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#882]
## Issue - Enhancement

"Archive" plants false hope that the team is recoverable, Let's just call it "Delete" Team

**Comment by ackernaut** [comment]
In the future, we may build out UI to recover the teams that are set to `isArchived`, but I think this is safe for now!

**Comment by jordanh** [comment]
I think @tayamueller has a point. Perhaps just some expository text to the delete field (warning: teams cannot yet be unarchived) might be enough for now.

**Comment by mattkrick** [comment]
i like calling it delete. the only reason we don't do a hard delete is in the case of a client making an oopsie & us being rockstars & undoing it (not to mention that sweet, sweet data for aggregate reporting).
