### ISSUE TITLE
Double dash alert…alert!!

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#883]
## UI Bug

The meeting progress modal needs correct layout when there are 2 dash alerts at the same time.

![screenshot 2017-04-05 11 45 59](https://cloud.githubusercontent.com/assets/307286/24721975/99fd0496-1a07-11e7-88b3-40bd269f32d2.png)

**Estimated effort**: 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
dont worry about this, in the future, we'll wanna promote the alert area to being much higher up the DOM tree & we'll just send it its own personalized subscriptions. then, we'll be able to say blur the whole working area.

**Comment by ackernaut** [comment]
Yeah, the nuance here is our soft wall on accessing team dash (what that team is meeting). We don’t want to cover up the left nav. The dashboard design may get a complete overhaul so this may very well change. So “future” it is for now.
