### ISSUE TITLE
Need a better way to calculate card width during drag state

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#885]
## Enhancement

Currently we [tediously subtract the chrome from viewport width and divide by four columns](https://github.com/ParabolInc/action/blob/master/src/universal/containers/ProjectCard/ProjectDragLayer.js) for both dashboard views and meeting views.

The chrome changes when collapsing agenda.

The dashboard design and layout may get a complete overhaul before we get to this issue.

[http://recordit.co/3k81K2Ez8x](http://recordit.co/3k81K2Ez8x)
![http://g.recordit.co/3k81K2Ez8x.gif](http://g.recordit.co/3k81K2Ez8x.gif)

**Estimated effort**: 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Still a thing, but iceboxing for now.
