### ISSUE TITLE
Team Sheet: Merge My Dash & Team Dash

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#892]
big picture, i think "my dashboard" & "team dashboard" are waaay too similar. one is filtering by `userId`, the other is filtering by `teamId`. One of our core values is being opinionated & if there are 2 ways to see my active projects, then the opinion isn't strong. To this day, it still confuses me when i'm on my dash & i don't see everyone else's projects.

I propose that team dash goes away. To replace it, we have a page that includes: 
- a button (maybe floating action button) to start a meeting. big and pronounced
- an agenda list
- team settings
- a button to open up integrations
- new settings like: 
 - links to show in the lobby
 - customize tinyUrl
 - adding/updating gCalendar invites

Our product does 2 things. We prioritize tasks & we host meetings. By keeping the meeting details separate from the projects, we decrease the mental payload for the user.

For My Dashboard, we have a filtering input box at the top (think YouTube)
- By default, the sort is on `@Matt`, which is a default childFilter (more on this later)
- Upon clicking it, you get a dropdown suggesting Teams to filter by. Clicking one of these becomes the ParentFilter & eliminates the child filter
- A parent filter is just like github's `This repository` filter. You hit backspace & it goes away, but if you search for something, then the search is applied with that filter already applied (eg select Team "Product" now search for `#private` or `@Terry` and i only get private projects within that team).
- The add project logic is the same. If no filter is applied, then it prompts you to select a team. if you selected a team, then it'll make a new project for that team. 

On the backend, going to this page subscribes to things: 
- projects by `myUserId` (to populate the kanban)
- team names (for the sidebar)
- notificationsCount (for the badge)
- Dash alerts (eg meeting in progress, not paid) for the top bars

This will increase data sent over time, but decrease initial page load, which is more important. 

When you activate the dropdown menu, it subscribes to a `filterOptions` subscription including:
 - tags (from Action and from Integrations. New tags added to github will be captured by our microservice & we will query all those tags before returning the result to the client)
 - @ mentions (all the users you share a team with and the intersection of your shared teams)

filterOptions is unioned with team names to create the initial suggestions in the dropdown.

_In the future_:
- we'll create a parentFilter called "search everything". When this filter is selected, you can search for a string of text and our typeahead API will return up to 10 projects that match the string. These projects will appear on the board rather than in the dropdown menu & the string will appear highlighted on the card.

gimme some thoughts @jordanh @ackernaut

**Comment by ackernaut** [comment]
@mattkrick this is good:

I had left a comment in #design on Slack about renaming Agenda to Inbox and follow your logic:

1. Inbox has a dropdown of your teams where you can drop an item into the queue for the next meeting.
2. Meeting has the same dropdown where you can jump to the lobby for that team.

For both, if you are filtered down to a team then they are automatic (kind of like creating new projects on the current user dash when filtered by team).

Question: we are going to cut the left team nav, right?

**Comment by ackernaut** [comment]
@mattkrick PS I really like a lot of the thinking here. I think we can continue the lo-fi UI explore and also start writing some jobs around this.

**Comment by mattkrick** [comment]
i think we'll still need something on the left side to get to your teams. it could be something like youtube subscriptions or facebook groups, where it shares the background of the main stuff. It could also become a drawer so folks can get rid of it when they need.

**Comment by jordanh** [comment]
From S.P.A.:

> I want a Team Dash that shows me everything pertaining to the team + meeting. It lets me know metrics, TODOs, docs, calendar invites, summary email settings, agenda for upcoming meeting, historical meeting summary, integrations, invitees, etc.

**Comment by ackernaut** [comment]
Yes, unless there is an objection I’m calling this the “Team Sheet” and I’ve got some designs in mind (starting from my sketchbook)…

**Comment by jordanh** [comment]
I like team sheet, a lot.

**Comment by mattkrick** [comment]
good discussion, but not active. closing for now
