### ISSUE TITLE
1st Agenda Item bugs

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#896]
## Issue - Bug

1) can't re-order 1st agenda item during Updates phase
2) can't delete 1st agenda item during Updates phase

**Comment by ackernaut** [comment]
I’m going to add to this bug:

If there are 2 agenda items, and you delete the 2nd one during updates, you can’t navigate to the first one.

**Comment by ackernaut** [comment]
Correction: it seems that if you remove any agenda item (besides the first one) it gets stuck.
