### ISSUE TITLE
Leave Team makes duplicate, null team

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#897]
## Issue - Bug

No reproduction steps on this yet. Just capturing.

I promoted another team member and left a team that had 4 team members (BBI). When I did, I saw this:

![image](https://cloud.githubusercontent.com/assets/103000/24842326/f475127e-1d63-11e7-9ece-e03e3008f73d.png)

TeamId within URL for the duplicate team is `null`.

- **Estimated effort:** 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
Followed reproduction steps but couldn't reproduce, although it did help me find something I missed in the previous scrub actions PR. I think this is infrequent enough that we could let it slide until we get a new cache.

**Comment by mattkrick** [comment]
gonna close for now to clean up the epic.
