### ISSUE TITLE
Sticky actions for archived teams

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#898]
## Bug

There are action items that cannot be checked and removed. They do not show a team name, as the team was archived:

1. Create a new team
2. Create actions for that team
3. Archive the new team
4. Try checking the action items

![screenshot 2017-04-10 10 12 55](https://cloud.githubusercontent.com/assets/307286/24868738/95607c2e-1dd6-11e7-9cad-f6e41e0abc96.png)

Question is…will we fix this before we get rid of actions entirely (in favor of private projects)? 😄 

**Estimated effort**: 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
No longer a thing!
