### ISSUE TITLE
Meeting/dashboard link for archived team

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#899]
## UX Bug

You can find a link to the meeting lobby and/or team dashboard in a summary email for a team that has been archived.

- When you arrive to the lobby all you see is ducks.
- When you arrive to the team dash, you see the dashboard header and nav, but ducks for the content.

Can we cause links to lobby and dash of an archived team to redirect to My Dashboard?

**Estimated effort**: 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
We need a 404 page!

**Comment by jordanh** [comment]
Iceboxing for now
