### ISSUE TITLE
Replace react-markdown with markdown-it

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#900]
react-markdown isn't gonna be powerful enough for what we want because we need to create new nodes based off of new tokens such as `#, @, :`.
https://github.com/rexxars/react-markdown/issues/61

What we want is https://yarnpkg.com/en/packages?q=markdown-it
(PS look how awesome yarn makes it to find the most popular packages! npm can just go pound sand.

There isn't a popular react wrapper for it, but i'm assuming that's because all you have to do is
`<span dangerouslySetInnerHTML={{__html: this.renderMarkdown(this.props.source)}}/>`.

**Comment by ackernaut** [comment]
🔥
