### ISSUE TITLE
Keyboard shortcuts for markdown

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#905]
## Issue - Enhancement

Tools like very Github allow users editing in a textarea to be able to highlight words with the cursor and press well known keyboard shortcults such as `<cmd>+k` for a url, `<cmd>+b` for bold, and `<cmd>+i` for italic.

Let's implement those within Action!

![image](https://cloud.githubusercontent.com/assets/103000/24971425/f5ec5918-1f85-11e7-8a2d-394f4a4ee21e.png)

![image](https://cloud.githubusercontent.com/assets/103000/24971566/6fdf2e30-1f86-11e7-8ae0-0fb88cdc01db.png)

It should:

- [ ] replace selected text with `[text]()` and place the cursor within the parantheses when `<cmd>+k` is pressed
- [ ] replace selected text with `**text**` and place the cursor after the final `**` when `<cmd>+b` is pressed
- [ ] replace selected text with `_text_` and place the cursor after the final `_` when `<cmd>+i` is pressed

- **Estimated effort:** 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by vishaalc** [comment]
I want to take this on! I think the process requires me to "bid" on it,  so I agree to the estimated effort points (13)

**Comment by jordanh** [comment]
Perfect! It's all yours!

**Comment by vishaalc** [comment]
Should the shortcuts be applied to just the cards in the "Done" column of Projects (both Dashboard, and Teams pages), or in all cards across the board?

**Comment by jordanh** [comment]
All cards across the entire product. Good clarifying question...

**Comment by vishaalc** [comment]
Written solution should work on Action, here's a fiddle I was working on to test it out: https://jsfiddle.net/x83x2yos/ - will submit a pull request now ✨

**Comment by jordanh** [comment]
@vishaalc would you still like to complete this issue – or, shall we make it available again for another member of the community?

**Comment by vishaalc** [comment]
Hey Jordan,

Sorry about the late response. You can go ahead and make it available for
the community! Hopefully once I have a bit more time on my hands I can pick
it up once again, or perhaps even pick a different issue open - looking
forward to it.


Regards,
Vishaal

**Comment by jordanh** [comment]
This item is once again available under our [Equity for Effort](https://github.com/ParabolInc/action/projects) program. If you, out there on the internet, would like to help us take this one on please confirm the point total you'll complete the work for by commenting on this issue and we'll transfer ownership to you!

**Comment by jordanh** [comment]
Head fake. We're going to press pause on this one until we've finished refactoring our card and editing components.

**Comment by ackernaut** [comment]
closing, switched to DraftJS over Markdown
