### ISSUE TITLE
Trial expiration date bug

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#914]
## Issue - Bug

I expired 2 days ago but everything is still functional:

![screenshot 2017-04-14 at 2 32 37 pm](https://cloud.githubusercontent.com/assets/14892189/25052329/49083c8a-211f-11e7-8c04-eca50e916bdd.png)

**Comment by mattkrick** [comment]
We didn't have a production endpoint set up for stripe so we weren't capturing any webhooks!!!
To remedy this we'll need to:
- [x] add the webhook endpoint on stripe
- [ ] write a migration (or a cron job?) to get caught up on all the webhooks we've missed

**Comment by mattkrick** [comment]
Steps for migration:
1. Modify `invoiceCreated` to adjust `status` if the invoice has already been paid or failed.
2. get all invoices from slack. filter out the recently created good ones by removing any IDs that exist in the parabol DB.
3. process them 1-by-1 using `invoiceCreated` webhook. go in serial & not parallel to avoid any rate limiting that stripe might impose (should take < 20 mins).

@jordanh the only headache is that i'm not sure how we could do a dry run. Stripe intentionally won't let us load prod data into their testing DB. Any thoughts?

**Comment by mattkrick** [comment]
hey @ackernaut were you seeing this locally on the draft branch or in production? 

i've been trying to reproduce locally to no avail.
tried:
- new name (worked)
- using + on the new name (worked)
- using + on an existing name (worked)

**Comment by ackernaut** [comment]
@mattkrick oh good—you figured it out! Yep, I would type “Terry”, “Teaming”, and then quickly tab to the “kick the tires” link and press `enter`. http://recordit.co/Lrl4Dv9Kfm

**Comment by mattkrick** [comment]
@jordanh i think this got erroneously closed by the force push. if i'm wrong feel free to close again
