### ISSUE TITLE
Convert "My Actions" column to "Add Agenda Item" [to any team] in My Dashboard

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#915]
## Issue - Enhancement

[per April User observations]

There is tension around flipping btwn "My Dashboard" to individual Teams. For any user on more than 1 team, My Dashboard is where they “live” most of the time. The only reason to leave My Dashboard is to add an Agenda item to a particular Team. How might we facilitate adding Agenda items to any Team from within the “home base” My Dashboard?

1) Once we eliminate "My Actions" feature on My Dashboard, let's replace it with an "Add Agenda Item" column (similar to Team Boards) 

2) Let's add a feature to allow any new Agenda item (on ANY board) to be assigned to any Team Board that a user is on. Often occurs that a user will think of something in a Team mtg that needs to be elevated in a different Team--right now you have to jot that note down outside of ACTION. This is also usually the one reason users leave the My Dashboard view in favor of a Team board view during the week between Check-Ins

**Comment by jordanh** [comment]
By removing the action column from `My Dashboard`, we are no longer doing this one.
