### ISSUE TITLE
Error during render during staging deploy [epic3]

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#926]
## Issue - Bug

@ackernaut, it looks like the new landing page is giving us a little grief on the staging server during the initial render. Have a look here: https://action-staging.parabol.co/

I see that it says, "Error during render!" and then renders just fine.

Once we patch this buggy up, I'll retest and push to prod.

Everything else looks great!

**Comment by ackernaut** [comment]
Going to try `componentDidMount()` instead…

**Comment by ackernaut** [comment]
Ready to test (master on staging)
