### ISSUE TITLE
Typeface updated

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#930]
## Enhancement

Parabol Action needs a richer typeface for UI.

I suggest we use Roboto and dress it up with Roboto Slab.

I also think this will work fine for our current branding as everything is BETA and can be improved in the future.

**Estimated effort**: 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Does it look too funky if you swap the typefaces out in our stylesheet for starters? Or, do we need to spend a deeper cycle on this?

**Comment by ackernaut** [comment]
@jordanh I think I could make quick work of it, adjusting specific fontSizes where things are no longer a reasonable size, and/or wrapping funny. This is why we have UI and theme vars! To keep and update things consistently.

**Comment by ackernaut** [comment]
I think Epic 4 is ok for this work.

**Comment by ackernaut** [comment]
Bumping this to the future as I think we’d prefer to stick with Karla for the short-term.

**Comment by ackernaut** [comment]
We did update! To IBM Plex. Yay.
