### ISSUE TITLE
Airtime Equality & Meeting Time-Keeping

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#933]
## Issue - Enhancement

[per April User observations]

We are not fixing airtime imbalance. Our Users still have the well-researched problem of "90% of the airtime in company meetings is consumed by 5% of the attendees, which leads to disengagement, disenfranchisement, and poor team culture."

1) OVERALL TIMEKEEPING: Reminded again of the idea of having a small clock ("Bertie the Turtle" walking from left to right) to subtly show how long the meeting has been going in relation to optimal target of 30min.

2) TEAMMATE TIMEKEEPING: Show how much airtime is being consumed by each teammate: Imagine if the size of each teammate’s avatar inflates to reflect the size of air time. Go all the way with this--make it overlap & start to obscure other teammate avatars. "Don’t get a big head, Violet Beauregarde” [aka take a seat; let somebody else talk]. This feature is active during each teammate's Social Check-In and Solo Update phase, and reported in Summary. In the future, we could measure airtime during Agenda processing via voice metrics.

**Comment by ackernaut** [comment]
@tayamueller gets the award for best-written issues! hehe, I dig it!

**Comment by jordanh** [comment]
Related to #1834

**Comment by jordanh** [comment]
Removing this one from the sprint board until it's `groom-ready`. @tayamueller is this a problem space that needs to be designed? Can you please add acceptance criteria so we can know when this issue is considered "done"?

**Comment by jordanh** [comment]
Iceboxing for now

**Comment by tayamueller** [comment]
submitted by [this user](https://app.hubspot.com/contacts/3888472/contact/1964701) from this [26-person Personal team](https://app.hubspot.com/contacts/3888472/contacts/list/view/all/?query=%40digi.com)

> I’m not sure how to do this within the tool, but one problem I struggle with is that some team members are very quiet and others dominate. I’ve dealt with this by soliciting feedback around the table. I felt that using the tools was a little less effective in making sure all voices were heard.

**Comment by Dyljyn** [comment]
I would like to share my interest/demand for this request.

I have a team member that dominates meetings quite a lot. Very often, he gets side-tracked by his examples around an item, leading into out-of-scope items. Though there are other factors, I believe having a visual timer will help him stick to the scope of the item and motivate others to speak because of the timeframe.

**Comment by jordanh** [comment]
@Dyljyn we implemented a timer! https://www.parabol.co/blog/async-retrospective-meetings-ready-set-timer
