### ISSUE TITLE
Random Facilitator Assignment & Kickoff

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#934]
## Issue - Enhancement

[per April User observations]

1) Our software should randomly assign a Facilitator, to combat the cultural norm of the most charismatic personality automatically self-assigning (or assumed) Facilitator each week. Can be overridden in the lobby by any teammate clicking that the assigned Facilitator is "Not Present" which triggers another random re-assign.

2) This feature could also incentivize timeliness--sucks to be the late one if you were auto-assigned to facilitate!

3) When our product is connected to calendaring capabilities, this feature can also kickstart the beginning of the meeting: that awkward time when everyone is present but nobody has kicked it off yet. At the calendar'd time, the software simply alerts the Team "[Teammate X] is facilitating today--time to get started!] Yet again: automating naggy admin business that nobody wants to do. Good prompt to get any stragglers to the meeting lobby, too. 

4) Let's build unique facilitation prompts the whole team doesn't see: “You’ve been here [Agenda item] a while, ask [name] what they need to move on.” This could work well in conjunction with the time-keeping capabilities in #933 Serves dual purpose as time-keeping and as facilitation coach. How might we empower teammates that are new/shy abt facilitating?

**Comment by jordanh** [comment]
Removing this one from the sprint board until it's `groom-ready`. @tayamueller can you write acceptance criteria for this one. Is it just item #1 that should be done? What would it look like? Is this a design issue?

**Comment by jordanh** [comment]
Iceboxing
