### ISSUE TITLE
Prompt to Hotlink to 3rd-Party Software/External Tabs

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#935]
## Issue - Enhancement

[per April User observations]

Users leave to open 3rd-party software frequently. Is it possible to create a prompt if Parabol "notices" users leaving frequently: "Would you like to create a link to that doc?" [is this technically possible??]

**Comment by ackernaut** [comment]
I like the idea of having a hint somewhere that Markdown is available (offering the formatting, including links).

I also like the ideas in #606 where recurring links/docs can be added to a list in the lobby and/or sidebar of the meeting. Think of it as a little panel or drawer where the 3-5 links might live (our Zoom/hangout/appearn.in, our Metrics, our pipeline spreadsheet, another thing we always look at, etc.)

**Comment by jordanh** [comment]
Closing. "Creepy pockets"
