### ISSUE TITLE
Teams have purpose statements

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#938]
## Enhancement

Teams do not just need a name. They need an optional purpose statement.

**High-level job story**: While juggling busy schedules, folks who hold multiple roles need to maintain a cognitive sense of purpose across teams/projects/orgs, so that they can be focused on what matters most and feel like they are contributing to the purpose in a meaningful way.

**Estimated effort**: 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
I think this (design & data updates) would be a good candidate for E4E and/or an Intern Epic.

**Comment by jordanh** [comment]
This is captured in other issues. Iceboxing for now.
