### ISSUE TITLE
Roles of team members

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#939]
## Enhancement

**Background**: With our first iterations of team member invites we asked “What’s their priority this week?” with a goal to begin to collect project information. We made both team member invitations optional, and the answer to the question was optional.

**Proposal**: We ask (optionally) “What’s their role on the team?”

**User story**: When joining new teams, team members want to know their role on the team in order to increase clarity of their scope and ownership of projects. [ooh this can be better]. When forming new teams, team leaders want to identify the roles that they need in order to get the work done in the best way.

**Big vision**: We want our software to automate mapping out the roles on teams within an organization to improve reporting, compensation, insights on bottlenecks, suggestions to form new teams, improve clarity and accuracy of performance. Etc.

**The future**: Add autosuggest to the field. Build out a space to add information to existing roles and/or create new roles.

**Estimated effort**: 15 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
This one will come back as a refined issue, I'm sure of it. Iceboxing for now.
