### ISSUE TITLE
build:client is broken

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#94]
## Issue - Bug

`build:client` currently fails because `getCashaySchema` uses a `babel-register` that doesn't know how to resolve from paths starting with `"universal..."`. Fixed in branch `create-meeting-backend`.

- **Estimated effort:** 1 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Did you not push your commit yet? I'm looking out for this one 👀

**Comment by mattkrick** [comment]
not yet, i was already a good way through my work on subs when i found it.

**Comment by jordanh** [comment]
OK, I can look into it...

**Comment by mattkrick** [comment]
oh no, the work is already done, i just didn't want to rewrite the fix for the master branch as well, since you guys are still working on the client it shouldn't affect your workflow yet.

**Comment by jordanh** [comment]
Heh. You're timing is hysterical. I just pushed a fix. Is yours much different than mine?

I wanted to resolve these bugs, cherry to master, and then push out to staging for testing purposes...
