### ISSUE TITLE
Autocomplete, inviting new team members

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#942]
## Enhancement

When creating a team, or inviting to an existing team, I want the email address field to auto-suggest from exiting organization members so that I can send the invitation without looking up an email.

**Estimated effort**: 15 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
This is a good one, but let's icebox for now.
