### ISSUE TITLE
Syntax highlighting for Markdown

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#943]
## Enhancement

When capturing snippets of code as project card content, I want better formatting so that I can read and scroll the code snippet, not the whole card/project column.

- [ ] 👾  Improve Markdown rendering of code to include syntax formatting

**Estimated effort** 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
With our WYSIWYG editor, this no longer applies
