### ISSUE TITLE
Consider relay modern

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#944]
there are a number of things that i need to do to fix up cashay:
-  pagination (this is gonna be a showstopper for invoices, archived cards, etc. as those lists grow...)
- remove graphql from the dependencies to shrink the file size
- move validation from runtime to build time
- optimistic UI
- reduced payload (initial & incremental)
- ...the list goes on

relay modern has fixed my biggest complaints with relax classic. It's decoupled from React, mutations are imperative & greatly simplified, and file size is much smaller. Certainly not a priority, but it's nice to know that for less than the time investment it would take to fix up cashay, we could move to something that someone else maintains. subscriptions are possible, but i think facebook wants to make that more of a graphql problem than a relay problem, so it should get easier as graphql iterates. for us, since we already have a mq in redis, evented subs should be good.

estimated time to seriously discuss/implement: july - aug.

**Comment by Panoplos** [comment]
I would be interested how one would go about using Relay Modern with SocketCluster. Any tips would be appreciated. I am going to attempt to slog this one out, as well. :^)

**Comment by jordanh** [comment]
@Panoplos we are doing it now on [this branch](https://github.com/ParabolInc/action/pull/1154) :)

**Comment by jordanh** [comment]
@mattkrick I am going to shift to this the current epic. I think we can close it soon 😉

**Comment by mattkrick** [comment]
already implemented on the past slack branch, which was already pushed to master & staging (and could be pushed to production at any time). ready to close!
