### ISSUE TITLE
Email integration lite

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#946]
## Issue - Enhancement

Reading [this post](https://praxis.fortelabs.co/one-touch-to-inbox-zero-a74cfa02e5bf) reminded me how empowering it is to have _one_ place where all of your tasks are – including responding to emails that take time to respond to.

For an initial stab at an email integration, I'm thinking of something like these job stories:

- **When** I get an email that is going to take time to respond to, I want to forward it to Parabol, so that I can prioritize it with my other tasks

- **When** it's time to finally get back to that email, I want to click a link that will take me right back to my email account and preferred editor, so that I can get right to work

- **Estimated effort:** 23 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
👾

**Comment by jordanh** [comment]
I'm sure this integration will come back. But, Iceboxing for now.
