### ISSUE TITLE
Mysterious Container missing dispatch message [add-tags]

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#948]
## Issue - Bug

Encountering this exception after navigating to a Team Dashboard:

```
Warning: Failed prop type: The prop `dispatch` is marked as required in `Connect(DashLayoutContainer)`, but its value is `undefined`.
    in Connect(DashLayoutContainer) (created by DashboardWrapper)
    in DashboardWrapper (created by TeamContainer)
    in TeamContainer (created by Connect(TeamContainer))
    in Connect(TeamContainer) (created by SocketWithPresence)
    in SocketWithPresence (created by withRouter(SocketWithPresence))
    in withRouter(SocketWithPresence) (created by Connect(withRouter(SocketWithPresence)))
    in Connect(withRouter(SocketWithPresence)) (created by SocketClustered)
    in SocketClustered (created by RequiredAuthAndRole)
   ...
```

I only looked into this one a little bit, it wasn't obvious.

- **OS:** OSX
- **Browser:** Chrome

**Comment by mattkrick** [comment]
when i debug, i manually change the `.babelrc` development config to match the testing config. in doing so, i get:
- hot module reload
- no regenerators (easy to reason await/async functionality)

but i give up
- ability to debug on safari
- proper class property transforms (the warning you're seeing)

i just need to remember to not commit the change 😄
