### ISSUE TITLE
Project card does not enter on submit for non-special hashtag

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#951]
## Issue - Bug

Minor UX bug. Reproduction steps:

1. Create a new card
2. Enter text as follows:

```
I am the very model of a
modern major #general
```

3. Hit enter after last word, observe that card does not submit

- **OS:** OSX
- **Browser:** Chrome

**Comment by mattkrick** [comment]
ah, i haven't thought about custom tags yet. what do you want to do with them? should we put them in the `tags` field so we can filter by them? should we add that as a suggestion for the next time they start to type it?

**Comment by jordanh** [comment]
We will most certainly add free-form tags at some point, so, if it's not hard to extract them and add them to the database that's probably the route we should take.

**Comment by mattkrick** [comment]
done!
now how do you manage tags? let's say i `#nailedIt` and now `#nailedIt` is showing up in my autocomplete. My boss thinks that phrase is vulgar and i need to get rid of it in the autocomplete. how do i get rid of it? what if i still have a project with that tag?

**Comment by jordanh** [comment]
I'm not sure yet. It's a real good question. Is this important to consider for now, or can we backlog it?

**Comment by mattkrick** [comment]
we can backlog it. for now, you can add a hash to anything. and that hash gets added to a list of tags that persists on the project, but that's all

**Comment by jordanh** [comment]
That's perfect!
