### ISSUE TITLE
Meeting UX issue: #private, #archived projects disappear

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#956]
## Issue - Enhancement

Ah, what would life be without corner cases?

Try the following:

1. Start a meeting with two participants
2. Add an agenda item to process
3. Proceed to that agenda item
4. Create a new card for yourself, make it `#private`
5. Change the ownership to the other team member, observe it disappears
6. End the meeting, observe the card in the summary

This goes for `#archived` as well.

If easily possible, we should make these cards hang around while agenda processing so that the team can always be working from the same shared context...until the meeting is over.

**Comment by mattkrick** [comment]
oooo great edge case!
another one might be assigning a private item to someone else. after you assign it, it goes away & you can't edit it. that feels a little weird because there's no undo. any thoughts?

**Comment by jordanh** [comment]
Yeah, I've encountered that last one for sure. I think we might want to let it slide for now, and capture an issue to implement undo on the dashes. That sound about right to you?

**Comment by mattkrick** [comment]
yeah, i think it was meistertask that had an activity log of everything you do. i think we could build something similar & just stick an undo button next to each one (simple in theory, but i know that's gonna be a headache).

**Comment by jordanh** [comment]
Yeah, that's a good way to handle that!

**Comment by mattkrick** [comment]
so back to the original issue, there are 2 ways to solve this:
- have 1 subscription that grabs all private projects & archived projects (!!!)
- have 2 subscriptions, the current projects sub & a 2nd one that grabs projects by agendaId, no matter the tag

i opted for the 2nd choice. i didn't implement unsubscribe logic, but that should be OK for now. In the future, we'll change around how we do sub/unsub so the payload only comes down the pipe once, but for now getting the same thing twice from 2 different subs is the cheap fast way of doing it.
