### ISSUE TITLE
invitations route auth0 modal is missing styling

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#957]
need to make sure the global styles are applied via the invitations route

**Comment by ackernaut** [comment]
Is this because I yanked this file?

https://github.com/ParabolInc/action/commit/52d5c2c73995b416ede4b7ba34af9d8f266f8c0e#diff-2de0cfdc8a86c5cc7a7b92518f3c92cb

I couldn’t see how it was being used in the codebase so I assumed it was dead code.

**Comment by ackernaut** [comment]
I also yanked a `main.css` file.
