### ISSUE TITLE
Minimal retro idea

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#958]
## Enhancement

**High level**: When work is getting done over time, team leads want to review what has been done so that good trends can be acknowledged and improved and bad trends can be recognized and addressed [this can improve structure, process and/or product development].

**Background**: Using Action creates a history of projects set to done (and archived if teams are meeting regularly). We can use batches of projects marked as done as content for a retro.

**Idea**: Teams can hold a meeting to review projects done over a certain timeframe:
- We recommend and notify the team lead to hold a retro based on a recurring team setting, default to once a month?
- The retro pulls any projects marked as done for that timeframe (the default, 1 month).
- All team members can review projects (timed, multiplayer). Marking 😄  or 😦  allows them to create an agenda item.
- Project cards with a reaction get processed, ordered by highest number of reactions to least. Any agenda items per card are processed in order of creation. Processing optionally results in projects. As a team setting, we could allow an optional timer for retro length (process quickly folks)!
- Summary: 1) Reactions are part of the project history (this can be emailed, optionally found in Team Insights view)? 2) New projects are the outcome with a meeting summary.

**Note**: Can reuse a lot of existing agenda logic and UI with some special rules around the new logic of what to process.

**Estimated effort**: 20 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Archiving this for historical purposes. One day, they will sing it's valor in song.
