### ISSUE TITLE
Feature flag system

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#965]
## Enhancement

**Background**: Can ship more often if we can hide upcoming changes behind a flag?
**Explore**: Do we need architecture/structure for this? Do we need an admin UI view?

**Estimated effort**: muchos points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
@jordanh @mattkrick I like your idea on this—just making it a Thang™.

**Comment by dan-f** [comment]
@jordanh spoke recently about this! Let's collect some use cases / requirements of a solution:

## Use Cases
- As a member of the product team, I want to ship the product as often as possible! Long-running feature branches get in the way of this, however most often value lands as a sequence of many PRs. We need a way of "soft" merging code to master which passes tests, but does not yet fully implement a feature.

## Requirements
- We must be able to conditionally expose UI to all users programmatically.

## Nice-to-have
- It would be nice to conditionally disable certain back-end API changes programmatically
- For disabled features, it would be nice to not ship their implementing code to the browser.
- If a feature is misbehaving in production, it would be nice to have the ability to turn it off as quickly as possible, without needing to redeploy.
- If I've got an experimental feature that I'd like to test on a subset of the user base or two solutions to a problem that I'd like to A/B, it would be nice to roll out different tech to different users.
  - In this case, for a particular user, we should be able to know which population they've been assigned to for debugging purposes

**Comment by dan-f** [comment]
Adding this for documentation purposes, but I'm finding [Martin Fowler's article](https://martinfowler.com/articles/feature-toggles.html) on this to be super useful!
