### ISSUE TITLE
Card editor: basic editing

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#975]
## Enhancement

The card editor supports basic formatting with keyboard shortcuts:

- [x] bold `command + b`
- [x] underline `command + u`
- [x] italic `command + i`
- [x] strikethrough `shift + command + x`

**Estimated effort**: 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

#WYSIWYG

**Comment by ackernaut** [comment]
In the spirit of :shipit: faster, I’m going to break this down into smaller issues, in the assumed order of iteration:

1. Card editor: basic editing
2. Card editor: Markdown
3. Card editor: links
4. Card editor: user mentions
5. Card editor: tags
