### ISSUE TITLE
Add a log out route

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#98]
## Issue - Enhancement

During the auth sprint, I spaced making a route for logging out. This would be really, really helpful for debugging.

We can copy the basic pattern from Meatier:
- `/logout` dispatches a redux action that clears the token from the state
- Then we redirect to home
- and give em some toast confirming that they're logged out

No need for blacklisting JWTs on the server, we'll handle that when we cross the token-refresh bridge.

- **Estimated effort:** 1 point ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))
- **(Optional) link to mission spec:** ([duplicate and edit template](https://docs.google.com/document/d/1lgTJnJzBt9-4If883iOvthmc0hy-6C6hBF7KNN-lsXU/edit))

**Comment by jordanh** [comment]
Added on `dashboard-scaffolding-#95` branch. PR #101 will close this issue.
