### ISSUE TITLE
@Mention Notifications

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#982]
### High-level Job to be Done ("JTBD")

When somebody @mentions me, I want to receive a notification, so that I may respond.

### Details:

There are two kinds of notification channels: online and offline. Online notifications all happen via our built in notification system and are generated while a user is connected to us. Offline notifications happen when a user is not currently connected to us.

### Subordinate JTBD:

When I haven't configured my notification preferences, I want all of my offline notifications to be delivered via email, so that I don't miss anything

When I don't want notification emails from Parabol and I have a Slack team, I want the option to configure my offline notifications to be sent to me on Slack, so that I can avoid getting too many emails

When my offline notifications are configured to be delivered via email, I want to batch up the last 5 minutes worth, so that I don't get too many emails.

When I am offline and somebody @mentions me, I want to receive a notification, so that I can respond

When I am offline and somebody assigns me a new project, I want to receive an offline notification (e.g. an email or slack message), so that I can respond

When I am online and somebody assigns me a new project, I want to receive an online notification, so that I can respond

When I am @mentioned, I am subscribed to the card, so that I don't miss subsequent updates

- **Estimated effort:**  33 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Related to #987

**Comment by jordanh** [comment]
Per one team leader:

> If a new project is added to a team member, can there be a notification to the team member that a project has been added for them?

**Comment by ackernaut** [comment]
Related to #17

**Comment by ackernaut** [comment]
Related to #1430

**Comment by mattkrick** [comment]
closing in favor of #1430. the only difference between the 2 is the copy of the notification. 1 tells them they own the project, the other says they were mentioned.
