### ISSUE TITLE
Create GitHub issues from meeting agenda

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#984]
## Issue - Enhancement

**JTBD**: When I have an agenda item that can be resolved via a GitHub Issue (such as a bug report), I want to be able to create the Issue without leaving the meeting, so my workflow and the meeting isn’t interrupted.

**Estimated effort**: X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Let the output of this be an issue or set of issues each with checklist spec and links to designs.

**Comment by ackernaut** [comment]
See #1105 and #1103
