### ISSUE TITLE
Meeting progress links stay focused

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#992]
## Issue - Enhancement

During a meeting, tapping the flat buttons “Next team member” and “Next Agenda Item” in order to advance have a sticky focus state.

**Estimated effort**: 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
@mattkrick any idea on how to make these flat buttons refresh? Basically, when the `onClick` event happens I want them to blur, then run the method to `gotoNext`.

**Comment by ackernaut** [comment]
@mattkrick ah I was being dense, I think I can just set the `key` property to the phase item number and that should cause a refresh on the flat button component rendering. I’ll give that a try first.

**Comment by mattkrick** [comment]
that should work! although i think the root cause might be nested in how we're using the CSS in the button component. do you see it happening in any other component? Perhaps we should make a key for it...
