### ISSUE TITLE
Emojis don't trigger after a newline

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#995]
## Issue - Bug

Repro steps:

1. Create a new card, type some text
1. Add an emoji like ☕️ 
1. Press shift-enter to create a newline
1. Now, add another emoji...

**Comment by mattkrick** [comment]
flagging as low priority as this will only be useful until WYSIWYG

**Comment by mattkrick** [comment]
removing from epic 4.5, will fix in the WYSIWYG epic coming next week! will close when WYSIWYG is implemented

**Comment by ackernaut** [comment]
@mattkrick I can’t reproduce this…but don’t see any commits or PRs referenced where it was probably fixed. Can we close?
