### ISSUE TITLE
Create agenda item from card

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#996]
## Issue - Enhancement

When I want to discuss the content of a particular card, I want a helper that allows me to add that card as an agenda item, so that I may unpack what I need within the context of a specific project

- **Estimated effort:** 23 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
One idea, see #861 

>Adding a tag in the text of an agenda item: a card could be referenced #123 and would be the first card in the row when that agenda item is processed.

**Comment by jordanh** [comment]
Iceboxing
